server.go
test/end2end_test.go

fix double wrapping of rpc status

---

transport/http2_client.go

so that we check the max concurrent stream constraint before sending headers frame.

refactor the NewStream a bit

---

transport/control.go
transport/http2_client.go
transport/http2_server.go
transport/http_util.go
transport/transport.go

This is mostly covered by the interop test. I am working on another pull request to have better test coverage; we do not support runtime window setup change now.

send settings/window_update frames when the initial window size is not equal to the default.

---

benchmark/stats/counter.go
benchmark/stats/histogram.go
benchmark/stats/stats.go
benchmark/stats/timeseries.go
benchmark/stats/tracker.go
benchmark/stats/util.go

mostly ported from a google internal version

stats lib for benchmark

---

transport/control.go
transport/http2_client.go
transport/http2_server.go

mostly ported from a google internal version

Ack Ping frame

---

grpclog/logger.go

Remove dependency on `glog`

---

grpclog/glogger/glogger.go

Add grpclog/glogger to restore glog functionality

---

benchmark/benchmark_test.go
transport/control.go
transport/http2_client.go
transport/http2_server.go

ack settings frame before applying the settings.

---

credentials/oauth/oauth.go

The first step in implementing #220.

Add credentials/oauth

---

clientconn.go
rpc_util.go
transport/http2_client.go

according to the latest designdoc at https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md

revise reconnect backoff strategy

---

rpc_util_test.go

it is not appropriate for the new algorithm.

remove backoff unit test

---

credentials/credentials.go
grpc-auth-support.md
interop/client/client.go

Remove OAuth support from `credentials`

---

transport/http2_client.go
transport/http2_server.go

handle empty data frame

---

clientconn.go

following the spec at https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md.

Add ClientConn state

---

clientconn.go
credentials/credentials.go
test/end2end_test.go

according to https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md.

Add ClientConn state API 

---

interop/client/client.go
metadata/metadata.go
test/end2end_test.go
transport/http2_client.go
transport/http2_server.go
transport/http_util.go

Modify the Meta data to support multiple values and case-insensitive.
fixes #256 
fixes #242

Revises Metadata

---

health/grpc_health_v1alpha/health.pb.go
health/grpc_health_v1alpha/health.proto
health/health.go
test/end2end_test.go

Remove the host field in healthcheck request

update healthCheck service

---

credentials/credentials.go
interop/client/client.go
server.go
test/end2end_test.go
transport/http2_client.go
transport/http2_server.go
transport/http_util.go
transport/transport.go

Allow access of some info of client certificate from Metadata API

---

credentials/credentials.go
server.go
test/end2end_test.go
transport/http2_client.go
transport/http2_server.go
transport/http_util.go
transport/transport.go

according to the offline discussion with @neild.

Separate auth info from normal metadata

---

examples/route_guide/client/client.go
examples/route_guide/routeguide/route_guide.pb.go
examples/route_guide/routeguide/route_guide.proto
examples/route_guide/server/server.go

rename proto for route_guide example

---

credentials/credentials.go
test/end2end_test.go

credentials.TLSInfo: export State

---

clientconn.go

Fix a reconnecting bug

---

examples/README.md

Misc fixes to the getting started guide to address issues seen on grpc.io

Fix go getting started

---

examples/gotutorial.md

I believe, there is stream.Recv() not stream.Read(), in RecordRoute(), isn't it?

Fix: Read() -> Recv()

---

rpc_util.go

add accessor for the error desc of rpcError

---

clientconn.go
server.go

grpc: add event logging
This is a recreation of PR #287 after git sadness.

grpc: add event logging to ClientConn and Server

---

README.md
call.go
clientconn.go
picker.go
stream.go

Prepare for custom naming and load balancing.

Introduce Picker API

---

README.md

document the no-deps design constraints

---

naming/etcd/etcd.go
naming/naming.go

according to some offline discussion. Prepare for custom naming support.

revise naming API

---

call.go
clientconn.go
picker.go
stream.go

prepare for roundrobin picker.

refactor the interaction between ClientConn and Picker

---

.travis.yml

try to address the issues caused by 2 repo names

---

call.go
clientconn.go
stream.go

recently introduced by Picker refactoring.
fixes #391

bug fix: stop busy wait on new transport

---

rpc_util.go

- msgFixedHeader
- change length to unint32 in encode()
- toRPCErr handles rpcError input

some cleanup

---

transport/http2_server.go

attach content-type to trailer if the trailer is the only response.

---

interop/client/client.go

rename some interop client flags

---

transport/http2_client.go

put ctx cancel into the right place

---

transport/http2_server.go
transport/transport_test.go

Cancel the contexts of all active streams when a server connection is closed

---

transport/control.go
transport/http2_client.go
transport/http2_server.go
transport/transport_test.go

Attach the payload from ping frame to ping ack

---

examples/helloworld/greeter_server/main.go

fix a typo

---

call_test.go
transport/http2_client.go

Allow >16k status desc

---

server.go
stream.go

Finish trace for premature error

---

benchmark/client/main.go

Fix the benchmark client

---

stream.go
test/end2end_test.go
transport/http2_client.go
transport/transport.go

Force flush headers frame for bi-di streaming

---

server.go

Tune the server accepting code

---

call.go
clientconn.go
rpc_util.go
server.go
stream.go
test/end2end_test.go

by removing Compressor/DecompressorGenerator

Simplify compression API

---

server.go

server: break up the Server.Serve method into some reusable parts

---

test/end2end_test.go

The docs at https://golang.org/pkg/testing/#T.FailNow say:
> FailNow must be called from the goroutine running the test or
> benchmark function, not from other goroutines created during the
> test.
(Fatalf is documented as "Fatalf is equivalent to Logf followed by
FailNow.")
This was manifesting itself as a race with two concurrently failing
goroutines in my other CL, masking whatever the real problem was.

Don't call t.FailNow in goroutines started by tests.

---

call_test.go
picker_test.go
transport/transport_test.go

Follow-up to #515 based on comments there from @maniksurtani.

Fix more cases of Fatalf being used from goroutines started by tests.

---

examples/helloworld/helloworld/helloworld.proto
examples/route_guide/routeguide/route_guide.proto

grpc/grpc-java#1381
Ideally this would wait until grpc/grpc#5041 to be merged, but if it's merged a bit sooner it probably doesn't matter much.

Sync example protos from main repository

---

test/end2end_test.go

Fix test-only goroutine leaks; add leak checker to end2end tests.

---

server.go
test/end2end_test.go

introduced by #508 
fixes #528

Close ServerTransport instead of the raw connection

---

server.go

refine the comments of grpc.Server.Stop()

---

test/end2end_test.go

This removes serverSetUp and clientSetUp. They had too many positional
parameters and weren't readable at the call sites.
With this change, it's now much more obvious how a test differs from
others just be looking at what is tinkered with after newTest.

test: improve test readability; use newTest helper everywhere

---

health/grpc_health_v1/health.pb.go
health/grpc_health_v1/health.proto
health/health.go
test/end2end_test.go

grpc.health.v1alpha ==> grpc.health.v1

change health check package name

---

doc.go

fix the grpc website url

---

examples/helloworld/greeter_client/main.go
examples/helloworld/greeter_server/main.go

I ran gofmt over this repository using prbot, an automated tool.

gofmt everything

---

test/end2end_test.go
transport/http2_server.go

Specialize http2.StreamError when the server reads frames

---

transport/http2_client.go

lowercase credential keys

---

rpc_util.go
transport/http2_client.go
transport/http_util.go
transport/transport_test.go

Use ErrorDetail() to provide better error msg for malformed HTTP2

---

transport/control.go

Fix minor "recieved" typo (should be "received")

---

transport/control.go
transport/http2_client.go
transport/http2_server.go

fixes #632 
The test is a bit tricky. will add it in a separate PR with some refactoring and improvement of the current flow control machinery.

Fix window update counting for the canceled streams

---

transport/control.go
transport/http2_client.go
transport/http2_server.go
transport/transport_test.go

Refactored the inbound flow control and fixed a couple of issues.

---

benchmark/stats/histogram.go
benchmark/stats/stats.go

Protobuf:
https://github.com/grpc/grpc/blob/master/src/proto/grpc/testing/stats.proto#L52
C implementation:
https://github.com/grpc/grpc/blob/master/src/core/lib/support/histogram.c

Change histogram to comply with benchmark worker requirements

---

test/end2end_test.go
transport/http2_client.go

Release the quota taken in streamsQuota when an rpc is timeout or canceled

---

test/end2end_test.go

Temporarily disable handler-tls for TestStreamServerInterceptor due to #619

---

transport/handler_server.go
transport/handler_server_test.go
transport/http_util.go
transport/http_util_test.go

Ignore plus and semicolon and anything following in Content-Type

---

balancer.go

Refactor round-robin impl

---

clientconn.go

remove duplicate balancer field

---

call.go
call_test.go
rpc_util.go
rpc_util_test.go
server.go
stream.go
test/end2end_test.go

This pull request takes the commits from #699, and adds a new commit to fix type assertion errors after doing rebase.
The reason for creating a new pull request is to get this change checked in before GA.

Make grpc.Errorf return struct pointer

---

reflection/serverreflection.go
reflection/serverreflection_test.go
server.go
server_test.go

Split methods and streams in service info

---

reflection/serverreflection.go
server.go

Fix comments for MethodInfo and reflection

Fix comments

---

call.go
clientconn_test.go
stream.go
test/end2end_test.go
transport/http2_client.go
transport/http2_server.go
transport/transport.go

- fixes #764
- fixes #665  
- Improves some tests

Fixed some bugs

---

transport/handler_server.go
transport/handler_server_test.go
transport/http2_server.go
transport/http_util.go
transport/transport.go
transport/transport_test.go

Signed-off-by: Peter Edge <peter.edge@gmail.com>
https://github.com/grpc/grpc-java/pull/1517/files

Do percent encoding matching grpc-java for the statusDesc

---

transport/http2_client.go

Eliminate empty desc Internal error

---

credentials/credentials.go
credentials/credentials_util_go17.go
credentials/credentials_util_pre_go17.go

Avoid modifying passed-in tls.Config

---

.travis.yml
balancer_test.go
benchmark/client/main.go
examples/route_guide/client/client.go
examples/route_guide/server/server.go
health/health.go
reflection/serverreflection.go
rpc_util_test.go
server.go
server_test.go
test/end2end_test.go

Includes gofmt, goimports, golint, and go vet.

*: enforce various linters

---

metadata/metadata.go
metadata/metadata_test.go

Allow comma in metadata Binary-Header value

---

clientconn.go
server.go
test/end2end_test.go
transport/http2_client.go
transport/http2_server.go

Fix a couple of races when goaway lives with connection shutdown.

---

examples/gotutorial.md

fix examples/gotutorial.md error link

---

server.go
test/end2end_test.go

Fix deadlock when GracefulStop()ing multiple times

---

clientconn.go

When goaway is received by client, a new ac should replace the old ac.
Without this change, ac is removed first and a new one is added later,
ac.tearDown() and cc.newAddrConn are two functions called consecutively,
So there's a small chance that getTransport is called in between and
misses the new ac. After this change, the value in map conns is replaced
directly, and this issue should be resolved.

Replace cc.newAddrConn with cc.resetAddrConn

---

backoff_test.go

Reverts grpc/grpc-go#819
Accidentally merged to the base repo

Revert "added two new testcases for backoff.go"

---

clientconn.go

Previously, cancellation of the context would cause these transient
errors to be swallowed since the function would return before the
log line was reached.

resetTransport: log all transient errors when they occur

---

stream.go

Finish trace when newclientsteram returns error

---

benchmark/stats/histogram.go

Fix histogram clear()

---

balancer_test.go
clientconn.go

Make non-failfast RPC get new transport instead of waiting

---

transport/http2_client.go
transport/transport.go

Use user context instead of creating new context for client side stream

---

transport/http2_client.go

Add comment for why use the user provided ctx in client side stream

---

server.go
stream.go
test/end2end_test.go
transport/transport.go

Allow multiple setTrailer

---

Documentation/grpc-metadata.md

correct spelling error for the word suffix

correct spelling error for the word suffix

---

benchmark/worker/benchmark_client.go

This affects only streaming calls on the benchmark clients. Comparing perf adhoc runs to new benchmark updates, it seems to have all around increases in streaming qps.
A couple of runs on the 32 core performance workers are in https://grpc-testing.appspot.com/job/gRPC_performance_adhoc/123/console and https://grpc-testing.appspot.com/job/gRPC_performance_adhoc/122/console
(I'm comparing the results of those runs to the numbers in https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5760820306771968)
cc @iamqizhao @ctiller

Remove extra goroutine in benchmark clients

---

server.go
test/end2end_test.go

The current behaviour is a little surprising: the first call to GacefulStop blocks as documented, but any later calls terminate immediately, even if the stop hasn't completed.
This PR lets all concurrent GracefulStop calls proceed to the Wait, and ensures they are all woken up when the server is stopped.
The test is copied from TestServerGoAwayPendingRPC with changes to test that concurrent GracefulStops block and are all unblock when the stop completes.

Make concurrent Server.GracefulStop calls all behave equivalently.

---

call_test.go
server.go
tap/tap.go
test/end2end_test.go
transport/http2_server.go
transport/transport.go
transport/transport_test.go

Add transport tap

---

stats/stats_test.go

https://travis-ci.org/grpc/grpc-go/jobs/174948404

fix flaky stats test

---

metadata/metadata.go

add comment to metadata FromContext

---

server.go

add always returns non-nil error comment to server.serve()

---

call.go
clientconn.go
clientconn_test.go
rpc_util.go
stream.go
test/end2end_test.go

The overview will be published in grpc/grpc shortly.

Add the initial service config support

---

call.go
clientconn.go
server.go
stats/handlers.go
stats/stats_test.go
stream.go
transport/http2_client.go
transport/http2_server.go
transport/transport.go

Change stats API from one static handler to one handler per server or client.

Change stats APIs

---

metadata/metadata.go
rpc_util.go

add comments

---

server.go
test/end2end_test.go

This allows users to customize the response to unknown method. It exposes a `StreamHandler` for custom implementation by users.
There are three use cases:
1. Not leaking the information of what services are implemented on a public facing server to unauthenticated users.
2. Building a "fake server" for integration tests. It works by looking up the service name on disk and comparing the inbound requests received and serving outbound ones. Not having to modify the code of the "fake server" to add new test cases is a big boon for us.
3. Unblocks building a gRPC proxy on top of gRPC-go. See linked ticket.
Changes:
* added `UnknownStreamHandler` option
* modified the codepath of `handleStreams` to commonize unknown code handling path.
* added an end2end test

add support for user-provided UnknownStreamHandler

---

credentials/credentials.go

add document to ClientHandshake about returning temporary error

---

status/status.go
status/status_test.go
test/end2end_test.go
transport/http_util.go

Use proto import from google.golang.org instead of github.com

---

transport/http2_client.go
transport/http2_server.go

Reverts grpc/grpc-go#1130
fixes #1196

Revert "To adhere with protocol the server should send RST_STREAM on observin…"

---

codec.go

fix Invoke #1218

---

transport/http2_client.go
transport/http_util.go
transport/transport_test.go

fixes #896
fixes #1190
Http to gRPC status code mapping :
https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md

Http status to grpc status conversion

---

balancer.go
clientconn.go
grpclb.go
grpclb/grpclb_test.go

So that if proxy is specified by the dialer, grpclb will also get that proxy.

Pass custom dialer to balancer

---

codes/codes.go
transport/transport.go

Fixed comment spelling

---

transport/handler_server.go

fixes #1257
cc: @jefferai  PTAL.

Initialize stream properly in handler_server.

---

go16.go
go17.go
rpc_util.go
transport/go16.go
transport/go17.go
transport/transport.go

Addresses contributing factor of #1201

Avoid panic caused by stdlib context package errors

---

test/end2end_test.go
transport/handler_server.go
transport/handler_server_test.go

~Will revert the commit reverting #1248 when #1257 is fixed.~

Re-enable handler tests

---

.github/ISSUE_TEMPLATE
CONTRIBUTING.md

Go counterpart of https://github.com/grpc/grpc/pull/11303

Improve contributing.md and add issue template

---

call.go
rpc_util.go
server.go
stream.go
test/end2end_test.go

Revert "Server shouldn't Fatalf in case it fails to encode."

---

stream.go

Add goroutine safety doc on stream

---

stream.go

Updated documentation of ClientStream.

---

test/bufconn/bufconn.go
test/bufconn/bufconn_test.go
test/end2end_test.go

Create bufconn package and use it in end2end tests

---

test/end2end_test.go

This reverts commit c7e2c00ed1df1690ec11b9984b3fa8da1bfafbdd.
There is a race between Dial and Close that causes goroutine leaks in the
end2end tests.

Revert "Use bufconn in end2end tests."

---

transport/http_util.go
transport/transport_test.go

This reverts commit 3ddcdc268d88595eb2f3721f7dc87970a6c3ab6e.

Revert "Make all "grpc-" metadata field names reserved (#1391)"

---

examples/route_guide/client/client.go
examples/route_guide/server/server.go

Use log instead of grpclog in routeguide example

---

stats/stats.go

Change comment on stats.End.Error

---

transport/handler_server.go
transport/handler_server_test.go

Complementing the work done in https://github.com/grpc/grpc-go/pull/1156/files

Add status details support to server HTTP handler

---

transport/transport_test.go

Remove unnecessary function handleStreamSuspension

---

balancer_test.go
clientconn_test.go
stream.go
test/end2end_test.go
transport/transport_test.go

Fix context warnings from govet

---

balancer_test.go
call_test.go
clientconn_test.go
grpclb/grpclb_test.go
proxy_test.go
server_test.go

Add leak goroutine checking to grpc/balancer tests

---

grpclb.go

Should do a blocking dial with timeout, instead of set deadline on the streaming RPC.

Fix deadline error on grpclb streams

---

test/end2end_test.go

Also, reduce sleeps elsewhere to bring the total runtime from ~5 minutes to ~20 seconds.
TestRetry will be significantly improved in a subsequent PR.

Speed up end to end tests by removing an unnecessary sleep

---

transport/transport.go

Removing defers in recvBuffer and controlBuffer show a 5-15% latency reduction for small messages.  Benchmarks for throughput and QPS are not impacted significantly.
Results (a bit noisy for some reason):
https://gist.github.com/dfawley/c5229dc253cbac1c4a1bfc8600ab5cf8

transport: remove some defers

---

stats/stats_test.go
test/end2end_test.go

fix TestServerCredsDispatch

---

vet.sh

Reverts grpc/grpc-go#1561
Since `honnef.co` is back.

Revert "Temporary disable staticcheck"

---

transport/http2_client.go
transport/transport.go

transport: minor cleanups (comment and error text)

---

proxy_test.go
test/end2end_test.go

Skip proxy_test in race mode

---

rpc_util.go

Update fail fast documentation to remove retry language

---

call.go
rpc_util.go
stream.go

Add functions to ClientConn so it satisfies an interface for generated code

---

codec_benchmark_test.go

codec_benchmark_test: fix racy unmarshal behavior and make some cleanups

---

examples/README.md

So users can copy the command and try with their own protos.
fixes #1650

Add protoc command to example/readme

---

balancer_conn_wrappers.go

Eliminate race on ac.acbw

---

codes/code_string.go

update code_string.go for new stringer changes

---

balancer_conn_wrappers.go

Solve data race mentioned in https://github.com/grpc/grpc-go/issues/1667

Eliminate data race in ccBalancerWrapper

---

balancer/base/balancer.go
balancer/base/base.go
balancer/roundrobin/roundrobin.go

Refactor roundrobin to support custom picker

---

transport/http2_server.go

After sending second goaway, close conn if idle.

transport: fix bug where GracefulStop would fail to close connections with no streams

---

transport/transport_test.go

Adjust keepalive paramenters in the test such that scheduling delays don't cause false failures too often.
Moreover, turn off BDP in TestServerWithMisbehavedClient because, although rarely, it leads to timeouts.

Fix flaky keepalive tests

---

examples/route_guide/server/server.go

examples: fix concurrent map accesses in route_guide server

---

test/gracefulstop_test.go

Fixes #1766
There is a different flake even with this fix, but I believe it's in the code and not in the test, and should be covered by #1738.  I'd like to commit this fix to the (~10x) more frequent problem first and then work on the next one.

Fix TestGracefulStop flakiness

---

server.go
test/end2end_test.go

server: fix bug preventing Serve from exiting when Listener is closed

---

encoding/gzip/gzip.go

gzip: add Name const to avoid typos in usage

---

clientconn.go

Explain target format in DialContext's documentation

---

transport/http2_client.go

stats: Fix bug causing trailers-only responses to be reported as headers

---

call.go
stream.go
test/end2end_test.go

Fixes #1801
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/1835)

Implement unary functionality using streams

---

transport/handler_server.go
transport/http_util.go
transport/transport_test.go

Merged the two relevant PRs
related to: #1672

Expunge error codes that shouldn't be returned from library

---

clientconn.go
clientconn_test.go

fixes #1787 #1750
Ran 10000 successful runs.

Fix flaky test: TestCloseConnectionWhenServerPrefaceNotReceived

---

clientconn_test.go

Since small deadlines are prone to flakes on Travis.
fixes: #1830

Fix Test: Update the deadline to a large value.

---

examples/route_guide/server/server.go

Same as https://github.com/grpc/grpc/pull/14794.

routeguide: reimplement distance calculation

---

balancer/balancer.go
channelz/funcs.go
channelz/types.go
clientconn.go
grpclb_remote_balancer.go
server.go
test/channelz_test.go
test/end2end_test.go
transport/handler_server.go
transport/http2_client.go
transport/http2_server.go
transport/transport.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/1811)

Stage 1: Channelz registration and deletion

---

rpc_util.go

documentation: mention peer will only be populated after RPC completes

---

balancer/balancer.go
resolver/resolver.go

For package `balancer` and `resolver`.
fixes #1973

documentation: mention Register functions should only be call at init time

---

balancer/base/balancer.go
balancer_v1_wrapper.go
benchmark/benchmain/main.go
benchmark/benchmark.go
benchmark/worker/benchmark_client.go
clientconn.go
encoding/encoding.go
encoding/proto/proto_test.go
grpclb.go
grpclb_util.go
proxy_test.go
resolver/dns/dns_resolver.go
rpc_util.go
stream.go

Apply various code simplifications and cleanups found by [gosimple](https://github.com/dominikh/go-tools).
One commit per category. Please see individual commit msgs for details.

Simplifications and cleanups (gosimple)

---

resolver/dns/dns_resolver.go

dns resolver: create rand seed at init time

---

call_test.go
encoding/proto/proto.go
interop/test_utils.go
rpc_util.go
rpc_util_test.go
server.go
stream.go
test/end2end_test.go

Fixes https://github.com/grpc/grpc/issues/15247

interop: Fix unimplemented method test

---

test/channelz_test.go

`doClientSideFailedUnaryCall` is to create the condition that a stream is successful at server side and fails at client side. The way to achieve it is to let server send a response larger than what client allows.
However, race condition can exist between server `WriteStatus` after sending the oversize response and server receives the reset stream sent by client due to larger than allowed response. Therefore, the stream can possibly fail at server side if rst stream is received and processed before `WriteStatus`.
The decision is to delete this case as there's no good way to rule out race condition here,

fix flaky test caused by race in channelz test

---

clientconn.go
clientconn_test.go
resolver/dns/dns_resolver.go
resolver/dns/dns_resolver_test.go
resolver/resolver.go
resolver_conn_wrapper.go

fix #1998
- also change not found SRV record and TXT record log level from warning to info

client: introduce WithDisableServiceConfig DialOption

---

test/gracefulstop_test.go
transport/controlbuf.go
transport/http2_client.go
transport/http2_server.go

Fix possible data loss; Only let reader goroutine handle connection errors.

---

test/end2end_test.go

test: make end2end test use split grpc / proto imports

---

transport/http_util.go

Account for user configured small io write buffer.

---

transport/controlbuf.go
transport/http2_client.go
transport/http2_server.go

Reduce error logs in transport.

---

test/gracefulstop_test.go

Account for the fact that Dial on client-side can return successfully before Accept has finished on server-side.
Fixes #1766

Fix flaky test: TestGracefulStop 

---

transport/flowcontrol.go
transport/transport_test.go

Fix flaky tests in transport.

---

transport/controlbuf.go
transport/http2_server.go

Register incoming stream with loopy as soon as it gets created.

---

interop/client/client.go

Allow interop client to use call creds on any secure channel

---

clientconn_test.go

Fix test: wait on server to signal successful accept.

---

stream.go

Fix flaky test: TestClientStreamingError

---

resolver/resolver.go

resolver: document that SetDefaultScheme should be called at init time

---

interop/client/client.go
interop/test_utils.go

interop: implement special_status_message interop test

---

testdata/testdata.go

testdata: get test assets related to package root instead of GOPATH

---

channelz/service/service.go
channelz/service/service_test.go
clientconn.go
internal/channelz/funcs.go
internal/channelz/types.go
pickfirst.go
resolver_conn_wrapper.go
test/channelz_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/2262)

channelz: channel tracing

---

install_gae.sh

Make goapp use go version 1.9.

testing: upgrade appengine sdk to version 1.9.68

---

.github/lock.yml

Add lock.yml for locking closed, stale PRs/issues

---

internal/binarylog/binarylog.go
internal/binarylog/binarylog_test.go
internal/binarylog/env_config.go
internal/binarylog/env_config_test.go
internal/binarylog/method_logger.go
internal/binarylog/regexp_test.go
internal/binarylog/util.go
internal/binarylog/util_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/2299)

binarylog: implement env variable config parsing

---

clientconn.go
internal/transport/http2_client.go
test/end2end_test.go

This also includes #2336 as a separate commit; please just review the second commit for this PR.

client: read from Conn while writing preface to unblock synchronous Conns

---

balancer/balancer.go
internal/transport/http2_client.go
stream.go
test/balancer_test.go

This includes / extends the test added in #2358.

balancer: add trailer metadata to DoneInfo

---

balancer/balancer.go

I forgot to change the last PR to add the comment you recommended before merging.

balancer: add clarifying note to PickOptions.Header

---

internal/transport/http_util.go
test/end2end_test.go

server: fix handling of RPC timeouts that overflow int64 nanos

---

.travis.yml

travis: remove Go 1.6 and 1.8 tests

---

internal/binarylog/binarylog_end2end_test.go

Access to testSink.buf should be protected by mutex.

binarylog: fix end2end test race

---

examples/features/multiplex/README.md
examples/features/multiplex/client/main.go
examples/features/multiplex/server/main.go

Show that a channel can be shared by two stubs and two services can share a
server.
fixes #2486

examples: multiplex

---

keepalive/keepalive.go

keepalive: typo

---

balancer/roundrobin/roundrobin_test.go

This PR refactor the code with a simple cleanup function.

internal: cleanup roundrobin_test with cleanup function

---

balancer/base/balancer.go

This PR refactors `connectivityStateEvaluator` with `balancer.ConnectivityStateEvaluator`.

roundrobin: use balancer.ConnectivityStateEvaluator in roundrobin

---

examples/features/encryption/ALTS/client/main.go
examples/features/encryption/ALTS/server/main.go
examples/features/encryption/README.md
examples/features/encryption/TLS/client/main.go
examples/features/encryption/TLS/server/main.go

example: encryption

---

examples/features/compression/README.md
examples/features/compression/client/main.go
examples/features/compression/server/main.go

example: compression

---

examples/features/interceptor/README.md
examples/features/interceptor/client/main.go
examples/features/interceptor/server/main.go

example: interceptor

---

clientconn_test.go

- Remove the slice of servers approach, since there's specific
logic at server 2 that's different from server 1. This has the
advantage of making the test more readable without sacrificing
anything (given the previous point).
- Defer server close at initialization time instead of at the
end.
- Remove a time.Sleep(time.Second): use timeout + select around
serverDone instead.
- Use a goroutine to keep the connection reading, instead of
using a for loop in the server goroutine. This causes the
defer close(server2Done) to happen immediately after preface
is sent, which combined with the aforementioned time.Sleep
removal causes the test to go from 1.00s to ~0.05s.

internal: rewrite TestDialWithMultipleBackendsNotSendingServerPreface

---

clientconn_state_transition_test.go
clientconn_test.go

And instead of setting state notify channel in balancer, create a new notify
channel at Build.
fixes #2576

internal: split StateRecordingBalancer in test to balancer and builder

---

server.go

fix https://github.com/grpc/grpc-go/issues/2585

fix MaxSendMsgSize comments error

---

Documentation/server-reflection-tutorial.md
examples/features/reflection/README.md
examples/features/reflection/server/main.go
examples/helloworld/greeter_server/main.go

Move reflection example to a separate folder.
fixes #2587

examples: reflection

---

dialoptions.go
rpc_util.go
test/end2end_test.go
vet.sh

client: deprecate CallCustomCodec and provide new version using encoding.Codec

---

naming/dns_resolver.go

Signed-off-by: Tom Wilkie <tom.wilkie@gmail.com>

Fix typo s/banlacer/balancer/

---

clientconn.go
clientconn_test.go

Currently, the connect deadline is recalculated per-address. This PR amends
that behavior such that all addresses for a single connection attempt share
the same deadline.
Fixes #2462

internal: resetTransport connect deadline is across addresses

---

examples/features/keepalive/README.md
examples/features/keepalive/client/main.go
examples/features/keepalive/server/main.go

examples: add keepalive example

---

benchmark/client/main.go
benchmark/server/main.go
benchmark/stats/stats.go
benchmark/stats/util.go
examples/helloworld/greeter_client/main.go
examples/helloworld/greeter_server/main.go

Description: In this pull request, we are adding comments at the package level for multiple files. I generated these comments based on the documentation here: https://github.com/golang/go/wiki/CodeReviewComments#package-comments
Ref: #1967

ADDED package level comments for: benchmark/, examples/helloworld/

---

README.md
examples/route_guide/server/server.go
test/end2end_test.go
test/stream_cleanup_test.go

- **README.md**: fix http to https for more security
- **examples/route_guide/server/server.go**: initialize variable type can be omitted
- **test/stream_cleanup_test.go**: initialize variable type can be omitted
- **test/end2end_test.go**: error string log be capitalized by [Golang coding convention](https://github.com/golang/go/wiki/CodeReviewComments)

Fix styling

---

balancer/grpclb/grpclb_remote_balancer.go
balancer/grpclb/grpclb_test.go
benchmark/benchmain/main.go
benchmark/benchmark.go
dialoptions.go
internal/internal.go
test/gracefulstop_test.go

dialOption: export WithContextDialer()

---

balancer/xds/edsbalancer/balancergroup.go
balancer/xds/edsbalancer/edsbalancer.go
balancer/xds/edsbalancer/edsbalancer_test.go
balancer/xds/edsbalancer/util.go
balancer/xds/edsbalancer/util_test.go
balancer/xds/xds.go
balancer/xds/xds_test.go

The balancer that handles eds response and does two level balancing (locality level and endpoint level).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/2624)

xds: eds balancer

---

server.go

ErrConnDispatched is a normal error -- we should not fill up logs with it.

server: Don't log errors on ErrConnDispatched

---

resolver/dns/dns_resolver.go
resolver/dns/dns_resolver_test.go

per https://github.com/grpc/proposal/pull/44

dns: prefixing txt record lookup with "_grpc_config."

---

clientconn.go

Refactor retry loop after #2673

addrConn: resetTransport loop cleanup

---

internal/transport/handler_server.go
internal/transport/handler_server_test.go

transport: remove http.CloseNotifier from handler server

---

balancer/grpclb/grpclb.go
balancer/grpclb/grpclb_remote_balancer.go
grpclog/grpclog.go

Downgrade grpclb package info logs to V(2).

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature.md
.github/ISSUE_TEMPLATE/question.md

update to use new fancy issue templates

---

balancer_v1_wrapper.go

grpc: remove excess new line from the log statement

---

codes/codes.go

Per recent discussions.
Java: https://github.com/grpc/grpc-java/pull/5595
C: https://github.com/grpc/grpc/pull/18761

docs: add note about retrying UNAVAILABLE

---

balancer/xds/edsbalancer/edsbalancer.go
balancer/xds/edsbalancer/edsbalancer_test.go
balancer/xds/edsbalancer/util.go
balancer/xds/edsbalancer/util_test.go

Load report needs the drop category.

xds: save category in dropper

---

balancer/xds/edsbalancer/edsbalancer.go
balancer/xds/edsbalancer/edsbalancer_test.go
balancer/xds/lrs/lrs.go
balancer/xds/lrs/lrs_test.go
balancer/xds/xds.go
balancer/xds/xds_client.go
balancer/xds/xds_client_test.go
balancer/xds/xds_lrs_test.go
balancer/xds/xds_test.go

xds: report loads to traffic director

---

balancer/xds/edsbalancer/balancergroup.go
balancer/xds/edsbalancer/balancergroup_test.go
balancer/xds/edsbalancer/edsbalancer.go
balancer/xds/edsbalancer/edsbalancer_test.go
balancer/xds/edsbalancer/test_util_test.go
balancer/xds/edsbalancer/util.go
balancer/xds/edsbalancer/util_test.go
balancer/xds/xds.go
balancer/xds/xds_client.go
balancer/xds/xds_client_test.go
balancer/xds/xds_lrs_test.go
balancer/xds/xds_test.go

This reverts commit b03f6fd5e3dfa7663a225c36a15d623159f6724b.
Context: #2748

internal: balancer/xds remove build constraint >= 1.12

---

balancer/xds/xds.go

Make it consistent with other receivers

internal: lint receiver name

---

channelz/grpc_channelz_v1/channelz.pb.go

internal: update channelz.pb.go

---

balancer/xds/edsbalancer/balancergroup.go
balancer/xds/edsbalancer/edsbalancer.go
balancer/xds/edsbalancer/edsbalancer_test.go

Locality weighted load balancer can be enabled by setting an option in
CDS, and the weight of each locality. Currently, without the guarantee
that CDS is always sent, we assume locality weighted load balance is
always enabled, and ignore all weight 0 localities.
In the future, we should look at the config in CDS response and decide
whether locality weight matters.

xds: ignore localities with weight 0

---

internal/transport/http2_client.go
test/end2end_test.go

metadata: write original md before appended md

---

server.go
test/gracefulstop_test.go

Internal cleanup: replace quit/quitOnce/done/doneOnce with grpcsync.Events.

server: immediately close all connections created after GracefulStop

---

internal/transport/transport.go
test/context_canceled_test.go

transport: fix race between header and RPC cancellation

---

xds/internal/balancer/xds_test.go

Rename TestXdsBalanceHandleResolvedAddrs as TestXdsFallbackResolvedAddrs
and add comments to explain what the test is doing. Also added some
other comments and made minor formatting changes.

Improve xds_test.go

---

Documentation/concurrency.md

doc: clarify client concurrency

---

examples/features/debugging/README.md

Testing PR access and stuff :)

docs: fix debugging README typo

---

clientconn.go

clientconn: fix potential deadlock caused by ResetConnectBackoff

---

test/end2end_test.go

Fixes #2981
In the event of a race, the first server may not be fully serving before the
client attempt to connect, then the second server may attempt to field the
FullDuplexCall, which it does not implement.
Fix the race by giving the client only the first server's address until after
the FullDuplexCall is started.

test: fix flake in GoAwayThenClose

---

clientconn.go
grpclog/grpclog.go

Signed-off-by: yuxiaobo <yuxiaobogo@163.com>

internal: fix typos in comments

---

xds/internal/balancer/xds_test.go
xds/internal/internal.go

cleanup: fix various misspellings

---

.travis.yml
examples/helloworld/greeter_client/main.go
examples/helloworld/helloworld_test.sh

https://github.com/grpc/grpc-go/issues/3072
Adds a bash script that runs a regression test on the hello world example.

examples: add regression test script to hello world example

---

internal/binarylog/binarylog.go

This PR adds more detailed log messages.

more detailed log message

---

go.mod
go.sum
xds/internal/client/fakexds/fakexds.go
xds/internal/client/lds.go
xds/internal/client/lds_test.go
xds/internal/client/rds.go
xds/internal/client/rds_test.go
xds/internal/client/types.go
xds/internal/client/v2client.go
xds/internal/client/v2client_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3144)

xds: Initial implementation of a client using the v2 API

---

xds/internal/client/cds.go
xds/internal/client/cds_test.go
xds/internal/client/eds.go
xds/internal/client/eds_test.go
xds/internal/client/lds.go
xds/internal/client/lds_test.go
xds/internal/client/rds.go
xds/internal/client/rds_test.go
xds/internal/client/types.go
xds/internal/client/v2client.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3203)

xds: CDS implementation in v2Client.

---

internal/leakcheck/leakcheck.go
xds/internal/balancer/xds.go
xds/internal/balancer/xds_client_test.go
xds/internal/balancer/xds_client_wrapper.go
xds/internal/balancer/xds_test.go

And some cleanup
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3205)

xds: in EDS balancer, use xds_client from attibutes

---

xds/internal/balancer/cdsbalancer/cdsbalancer.go
xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
xds/internal/balancer/xds.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3224)

xds: Implementation of the CDS LB policy.

---

internal/buffer/unbounded.go
internal/transport/transport.go

Fixes https://github.com/grpc/grpc-go/issues/3237

internal: Improve documentation around buffer.Unbounded

---

benchmark/benchresult/main.go
benchmark/stats/stats.go

Closes https://github.com/grpc/grpc-go/issues/3235

benchmark: include go and grpc version in result files

---

internal/resolver/dns/dns_resolver_test.go

Also, changed the test to make it run in less time and perform more iterations.
Ran 1500 times locally without seeing any failures.

dns: fix timing-based test to be more reliable

---

xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
xds/internal/testutils/fakexds/client.go

* Use the fakexds.Client object instead of defining a new one
* Add CDS watch functionality to the fakexds.Client object

xds: Improve cdsbalancer_test.go

---

credentials/alts/utils.go
credentials/alts/utils_test.go

Add a simple client authorization utility API to be used by servers.

credentials/alts: Add Client Authorization Utility API

---

Documentation/benchmark.md
benchmark/benchmain/main.go
benchmark/flags/flags.go
benchmark/flags/flags_test.go
benchmark/stats/curve.go
benchmark/stats/stats.go
vet.sh

Closes https://github.com/grpc/grpc-go/issues/3236

benchmark: add support for payload size curves

---

security/advancedtls/advancedtls_test.go
security/advancedtls/testdata/testdata.go

advancedtls: add package for testdata

---

security/advancedtls/testdata/testdata.go

security: Add a package level comment to testdata package in advancedtls

---

xds/internal/client/client.go

We are using some sane defaults for now:
```
KeepaliveTime: 5 minutes
KeepaliveTimeout: 20 seconds
PermitWithoutStream: false
```
This does differ with the defaults used internally, but we are OK with
it, because it is more important to have a reasonable value here than
having one that works for all deployments or even making this
configurable through the bootstrap file.

xds: Enable keepalives on the xds client channel.

---

README.md

README: update SupportPackageIsVersion help in FAQ section

---

balancer/grpclb/grpclb_remote_balancer.go
balancer/grpclb/grpclb_test.go

grpclb: support explicit fallback signal

---

balancer/base/balancer.go
clientconn.go

Fixes #3339
cc @ejona86 @markdroth as FYI

balancer/base: keep bad SubConns in TransientFailure until Ready

---

internal/transport/handler_server.go
internal/wrr/edf.go
profiling/cmd/remote.go
xds/internal/balancer/edsbalancer/balancergroup.go

Fixes issues reported from go vet.
https://github.com/grpc/grpc-go/pull/3395 re-enables go vet.

Fix vet issues

---

go.mod
go.sum
xds/internal/client/bootstrap/bootstrap.go
xds/internal/client/bootstrap/bootstrap_test.go

Also set the new user-agent fields.

xds: set no_overprovisioning in request Node

---

xds/internal/balancer/edsbalancer/test_util_test.go
xds/internal/balancer/lrs/lrs.go
xds/internal/balancer/lrs/lrs_test.go
xds/internal/client/client.go
xds/internal/client/client_loadreport.go
xds/internal/resolver/xds_resolver.go

- The first LRS req will send hostname in metadata
- With key "PROXYLESS_CLIENT_HOSTNAME"

xds: LRS send hostname in metadata

---

xds/internal/client/rds.go
xds/internal/client/rds_test.go
xds/internal/client/v2client_test.go

This matches envoy's behavior. See also https://github.com/grpc/grpc/pull/22204

xds: include port in VirtualHost domain matching

---

test/channelz_test.go

Fixed a test that was flaky in channelz_test.go.
Fixes #3383

test: Fix flaky channelz test

---

xds/internal/balancer/edsbalancer/eds_impl.go
xds/internal/balancer/edsbalancer/eds_impl_test.go

This is a cherry-pick of #3433 into the 1.28 release branch

xds: handle removing drops

---

test/kokoro/README.md
test/kokoro/xds.cfg
test/kokoro/xds.sh

This is a cherry-pick of https://github.com/grpc/grpc-go/pull/3448 into the 1.28.x branch
cc @menghanl

kokoro: add xds job (#3448)

---

test/kokoro/xds.sh

This is a cherry-pick of https://github.com/grpc/grpc-go/pull/3456
cc @menghanl

kokora: checkout matching grpc/grpc branch for xds test

---

vet.sh

vet: Get it to work on Darwin.

---

internal/wrr/random.go
internal/wrr/wrr.go

wrr: make random wrr thread safe

---

internal/serviceconfig/serviceconfig.go
internal/serviceconfig/serviceconfig_test.go
service_config.go

And make it a json unmarshaller, easy to use.

service config: move balancer config parsing to internal

---

xds/internal/balancer/balancergroup/balancergroup.go
xds/internal/balancer/balancergroup/balancergroup_test.go
xds/internal/balancer/edsbalancer/eds_impl.go

And make balancergroup stop load reporting is load store is not set

balancergroup: update methods to V2balancer

---

vet.sh
xds/internal/testutils/balancer.go

And add a vet check to enforce it.

internal: rename proto import to end with pb

---

xds/internal/balancer/balancergroup/balancergroup.go
xds/internal/balancer/balancergroup/balancergroup_test.go
xds/internal/balancer/edsbalancer/eds_impl.go
xds/internal/balancer/edsbalancer/eds_impl_test.go
xds/internal/balancer/lrs/lrs.go
xds/internal/balancer/lrs/lrs_test.go
xds/internal/client/eds.go
xds/internal/client/eds_test.go
xds/internal/internal.go
xds/internal/internal_test.go
xds/internal/testutils/balancer.go

rename to LocalityID
Signed-off-by: Zou Nengren <zouyee1989@gmail.com>

xds/internal: rename to LocalityID

---

README.md

README: add link to Go releases

---

xds/internal/client/v2client_rds.go
xds/internal/client/v2client_rds_test.go

modify the return of getClusterFromRouteConfiguration

modify the return of getClusterFromRouteConfiguration

---

xds/internal/balancer/edsbalancer/eds.go
xds/internal/balancer/edsbalancer/eds_impl.go
xds/internal/balancer/edsbalancer/eds_impl_priority_test.go
xds/internal/balancer/edsbalancer/eds_impl_test.go
xds/internal/balancer/edsbalancer/eds_test.go

Signed-off-by: Zou Nengren <zouyee1989@gmail.com>

xds: unexport edsBalancerImplInterface's function

---

xds/internal/client/v2client_ack_test.go

Signed-off-by: zounengren <zounengren@cmss.chinamobile.com>

make helper function return error

---

security/advancedtls/advancedtls.go
security/advancedtls/advancedtls_test.go

This PR aims to add another field, `Leaf` certificate, to the `VerificationFuncParams` that users could see when implementing custom server authorization functions.
This `Leaf` field could be derived from an existing field `RawCerts`, but we could further reduce users' burdens of parsing the raw certs by directly providing the leaf certificate, if users choose to verify the peer certs. Users could get identity information from `RawCerts`, such as URIs or IPAddresses, about the peer.
This PR also adds tests that check if we could get the correct values of fields in `VerificationFuncParams`, both in `clientVerifyFunc` and `serverVerifyFunc`.

advancedtls: add leaf cert in verify params

---

xds/internal/balancer/balancergroup/balancergroup.go
xds/internal/balancer/weightedtarget/logging.go
xds/internal/balancer/weightedtarget/weightedtarget.go
xds/internal/balancer/weightedtarget/weightedtarget_config.go
xds/internal/balancer/weightedtarget/weightedtarget_config_test.go
xds/internal/balancer/weightedtarget/weightedtarget_test.go

It's a thin wrapper on balancer group.

xds: add weighted_target balancer

---

internal/status/status.go

fix https://github.com/grpc/grpc-go/issues/3536
Signed-off-by: Zou Nengren <zouyee1989@gmail.com>

status: wrap status proto in a struct

---

examples/features/xds/README.md
examples/features/xds/client/main.go
test/kokoro/xds.sh
xds/internal/resolver/xds_resolver.go
xds/internal/resolver/xds_resolver_test.go

Also keeping "-experimental" for one more release

xds: rename resolver scheme to xds

---

dialoptions.go
server.go

Signed-off-by: IceberGu wei.cai-nat@daocloud.io

internal: fix typos

---

xds/internal/balancer/balancergroup/balancergroup.go

Signed-off-by: Zou Nengren <zouyee1989@gmail.com>

xds: rename subBalancerWithConfig to subBalancerWrapper

---

examples/features/xds/README.md
examples/features/xds/client/main.go
interop/xds/client/client.go
xds/xds.go

Instead of package "xds/experimental".

xds: move balancer/resolver registation to package xds

---

xds/internal/balancer/cdsbalancer/cdsbalancer.go
xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
xds/internal/testutils/channel.go

This is similar to the EDS error handling: https://github.com/grpc/grpc-go/pull/3645

xds: handle errors in cds balancer

---

internal/transport/http2_client.go
stream.go

Cherry pick of #3691 to branch v1.30.x

retry: re-enable retrying on non-IO transport errors (#3691)

---

credentials/tls/certprovider/distributor.go
credentials/tls/certprovider/distributor_test.go
credentials/tls/certprovider/provider.go
credentials/tls/certprovider/store.go
credentials/tls/certprovider/store_test.go

* Also add an implementation for the `Distributor` type which makes it easier to implement new `Provider` types.

credentials: Add certificate provider plugin APIs.

---

credentials/alts/internal/authinfo/authinfo.go
credentials/alts/internal/authinfo/authinfo_test.go

@ZhenLian for code review
Added accessor function for the authinfo for ALTS context. Integrated handshaker result as well as added testing unit for new method.

alts: Added peer attributes accessor for alts context and updated test method

---

balancer/grpclb/grpclb_test.go
balancer/roundrobin/roundrobin_test.go
balancer_switching_test.go
clientconn_test.go
examples/features/debugging/client/main.go
examples/features/health/client/main.go
pickfirst_test.go
resolver_conn_wrapper_test.go
test/balancer_test.go
test/channelz_test.go
test/creds_test.go
test/end2end_test.go
test/healthcheck_test.go

test: replace manual.GenerateAndRegisterManualResolver with grpc.WithResolvers

---

xds/internal/balancer/xdsrouting/doc.go
xds/internal/balancer/xdsrouting/matcher.go
xds/internal/balancer/xdsrouting/matcher_header.go
xds/internal/balancer/xdsrouting/matcher_header_test.go
xds/internal/balancer/xdsrouting/matcher_path.go
xds/internal/balancer/xdsrouting/matcher_path_test.go
xds/internal/balancer/xdsrouting/matcher_test.go

- path matchers
- header matchers
- fraction
- helpers: "and"/invert
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3733)

xdsrouting: all matchers

---

xds/internal/balancer/xdsrouting/routing_config.go
xds/internal/balancer/xdsrouting/routing_config_test.go
xds/internal/client/client_watchers_rds.go

JSON unmarshal and field checks (e.g. only one of `oneof` is set).

xdsrouting: balancer config parsing

---

server.go

* More descriptive names for certain identifiers.

grpc: Minor refactor in server code.

---

xds/internal/balancer/edsbalancer/xds_client_wrapper_test.go
xds/internal/client/transport_helper.go
xds/internal/client/v2/client.go
xds/internal/client/v3/client.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3778)

xds: Support xDS v3 transport protocol.

---

internal/wrr/edf.go
internal/wrr/edf_test.go

internal/wrr: introduce order offset to edf scheduler as a tiebreaker for entries with same deadline

---

xds/internal/balancer/edsbalancer/eds_impl_priority.go
xds/internal/balancer/edsbalancer/eds_impl_priority_test.go

Without this fix, when the EDS response removes all priorities, after the timeout, the priority check panics because priority is unset.

eds: fix priority timeout failure when EDS removes all priorities (cherry pick of #3830)

---

xds/internal/balancer/balancergroup/balancergroup.go
xds/internal/balancer/balancergroup/balancergroup_test.go
xds/internal/balancer/balancergroup/balancerstateaggregator.go
xds/internal/balancer/edsbalancer/eds_impl.go
xds/internal/balancer/weightedtarget/weightedaggregator/aggregator.go
xds/internal/balancer/weightedtarget/weightedtarget.go
xds/internal/balancer/xdsrouting/balancerstateaggregator.go
xds/internal/balancer/xdsrouting/routing.go
xds/internal/balancer/xdsrouting/routing_picker.go
xds/internal/balancer/xdsrouting/routing_picker_test.go

Instead of internal.LocalityID

xds: update balancer group ID type to string

---

xds/internal/client/tests/client_test.go

internal: rename package for test alone file

---

internal/grpctest/tlogger.go

* Simplify the logic to get the file and line number or call site
* Add a monotonic clock value as a suffix. This helps with debugging of test failures due to timing issues.

grpctest: Minor improvements to tlogger.

---

xds/internal/balancer/cdsbalancer/cdsbalancer_test.go

Instead of defining a new `testClientConn` type here, make use of the existing `TestClientConn` type from `testutils` package.

xds/cdsbalancer: Use testutils.TestClientConn.

---

version.go

Revert "Change version to 1.33.0"

---

resolver/manual/manual.go

Tests should use WithResolver dial option.

manual resolver: delete GenerateAndRegisterManualResolver

---

xds/internal/test/xds_server_integration_test.go

Fixes https://github.com/grpc/grpc-go/issues/4022

xds: Deflake xds_server_integration_test.go

---

.github/workflows/testing.yml

Even for version.go and doc changes. Otherwise the PRs with only those changes will be waiting for the tests to pass.

github acitons: always run

---

test/kokoro/xds.sh

Also need to set server image to version 3, so that the server blocks the
pending RPCs

xds interop: turn on circuit breaking test

---

interop/xds/client/client.go

Plus a few small go style changes & refactors.

interop/xds: implement new stats response field

---

test/kokoro/xds.sh
test/kokoro/xds_v3.cfg
test/kokoro/xds_v3.sh

This is go counterpart of grpc/grpc-java#7809

xds interop: add xds v3 kokoro tests

---

interop/grpc_testing/messages.pb.go
regenerate.sh

- Pull in protobuf repo since one of our protos pulls in duration.proto
- Update grpc_testing/messages.pb.go to pull in a recent change

regenerate.sh: include standard protos; update generated files

---

xds/internal/balancer/cdsbalancer/cdsbalancer.go
xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
xds/internal/testutils/balancer.go

Fixes https://github.com/grpc/grpc-go/issues/4000

xds/cdsbalancer: Override UpdateAddresses()

---

xds/internal/client/lds_test.go
xds/internal/client/xds.go

Addresses https://github.com/grpc/grpc-go/issues/4208

xds: validate 'listener_filters' and 'use_original_dst' fields

---

xds/internal/client/cds_test.go
xds/internal/client/xds.go
xds/internal/env/env.go

This is a cherry pick of 
- xds: add env var protection for client-side security (#4247)

cherry-pick commits to 1.36.x

---

xds/internal/client/cds_test.go
xds/internal/client/client.go
xds/internal/client/xds.go

Added fields to cluster update for direct path project.

xds: Add fields to cluster update

---

xds/internal/client/requests_counter.go
xds/internal/client/requests_counter_test.go

xds: fix service request counter flaky test

---

interop/xds/client/client.go

This is a cherry pick of https://github.com/grpc/grpc-go/pull/4307

xds/interop: register admin services and reflection (#4307)

---

test/kokoro/xds.sh

Depends on https://github.com/grpc/grpc/pull/25892

xds/interop: move header/path matching to all

---

xds/internal/balancer/clusterimpl/balancer_test.go

internal: fix symbol undefined build failure

---

test/kokoro/xds.sh

As title.
https://fusion2.corp.google.com/invocations/52d6253f-797f-4490-8100-030b3bddee97/targets
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/4354)

test: enable xDS CSDS test

---

balancer_conn_wrappers.go

Currently, `ccBalancerWrapper.close()` fires the `done` event and returns. `ccBalanacerWrapper.watcher()` has a `select` on the channel exposed by `done`. And when it sees that `done` has fired, it goes ahead and closes the balancer and also closes the subConns.
We want the balancer to be closed by the time `ccBalancerWrapper.close()` returns. In our xDS implementation, there is state shared across balancers (specifically, the `xdsClient` is shared across balancers and resolvers). When a balancer is switched out for another one, `ccBalancerWrapper.close()` will be called on the old balancer, and we want all of its state to be cleaned up before the new one is created, and this PR addresses that.

grpc: call balancer.Close() before returning from ccBalancerWrapper.close()

---

xds/internal/httpfilter/fault/fault_test.go
xds/internal/testutils/e2e/clientresources.go

xds: work around xdsclient race in fault injection test

---

xds/internal/test/xds_server_serving_mode_test.go

Fixes https://github.com/grpc/grpc-go/issues/4369
#fixit

xds: use SendContext() to fail in time when the channel is full

---

internal/resolver/dns/dns_resolver.go
internal/resolver/dns/dns_resolver_test.go

dns: fix flaky TestRateLimitedResolve

---

test/end2end_test.go

In this `GoAwayThenClose` test, we
1. make a streaming RPC on a connection
1. graceful stop the connection from the server, to send a GOAWAY
1. hard stop the server, so the client will create a new connection to another server
1. wait for the streaming RPC to fail
1. make unary RPC and expect them to connect to the second server
Before this fix, 2 and 3 can happen too soon, so the RPC in 1 would fail
and then transparent retry (because the stream is unprocessed by the
server in that case).
This retry attempt could pick the new connection, and then the RPC would
block until timeout.
After this streaming RPC fails, we make unary RPCs with the same
deadline (**note:** deadline not timeout) as the streaming RPC and expect
them to succeed. But they will also fail due to timeout.
The fix is to …

test: fix flaky GoAwayThenClose

---

interop/client/client.go

Fixes: https://github.com/grpc/grpc-go/issues/2743
#fixit

interop: use credentials.NewTLS() when possible

---

internal/pretty/pretty.go
xds/internal/balancer/cdsbalancer/cdsbalancer.go
xds/internal/balancer/clusterimpl/clusterimpl.go
xds/internal/balancer/clustermanager/clustermanager.go
xds/internal/balancer/edsbalancer/eds.go
xds/internal/balancer/lrs/balancer.go
xds/internal/balancer/priority/balancer.go
xds/internal/balancer/weightedtarget/weightedtarget.go
xds/internal/client/bootstrap/bootstrap.go
xds/internal/client/callback.go
xds/internal/client/v2/client.go
xds/internal/client/v2/loadreport.go
xds/internal/client/v3/client.go
xds/internal/client/v3/loadreport.go
xds/internal/client/watchers.go
xds/internal/client/xds.go
xds/internal/resolver/serviceconfig.go
xds/internal/resolver/watch_service.go
xds/internal/resolver/xds_resolver.go

xds: pretty print xDS updates and service config

---

benchmark/stats/histogram.go

Fixes #4158 
Also fixes wrong printing of upper bound for the last bucket in histogram.

benchmark: do not allow addition of values lower than the minimum allowed in histogram stats

---

xds/internal/test/xds_integration_test.go

xds: revert a workaround made in #4413

---

interop/xds/server/Dockerfile
interop/xds/server/server.go

Also add a Dockerfile for the interop server.

interop/xds: support xds security on interop server

---

.github/workflows/codeql-analysis.yml
.github/workflows/testing.yml

github: limit repo access of testing workflows

---

.github/workflows/stale.yml

github: increase stale bot ops per run to process everything

---

.github/lock.yml
.github/workflows/lock.yml

github: update lock bot to github actions

---

internal/xds/matcher/matcher_header.go
internal/xds/rbac/matchers.go
internal/xds/rbac/rbac_engine.go
internal/xds/rbac/rbac_engine_test.go

xds: add RBAC Engine

---

interop/xds/client/Dockerfile
interop/xds/server/Dockerfile
test/kokoro/xds_k8s.cfg
test/kokoro/xds_k8s.sh
test/kokoro/xds_k8s_install_test_driver.sh

Backport PSM Security interop test changes to v1.38.x

---

test/kokoro/xds_k8s.cfg

kokoro: Specify the correct path to the build config

---

interop/xds/client/client.go

- interop/xds: support xds credentials in interop client (#4436)

Backport xds interop client changes

---

internal/transport/networktype/networktype.go

doc: fix typo in package networktype

---

xds/internal/balancer/cdsbalancer/cdsbalancer.go
xds/internal/balancer/clusterimpl/clusterimpl.go
xds/internal/balancer/clustermanager/clustermanager.go
xds/internal/balancer/edsbalancer/eds.go
xds/internal/balancer/edsbalancer/eds_test.go
xds/internal/balancer/edsbalancer/xds_old.go
xds/internal/balancer/lrs/balancer.go
xds/internal/balancer/priority/balancer.go
xds/internal/balancer/weightedtarget/weightedtarget.go

xds: standardize builder type names (bb) and balancer receiver names (b)

---

xds/internal/balancer/clusterimpl/clusterimpl.go
xds/internal/balancer/lrs/balancer.go

 xds: standardize xds client field name (xdsClient)

---

version.go

Change version to 1.40.0-dev

---

xds/internal/balancer/clusterimpl/clusterimpl.go

xds/clusterimpl: fix race between picker update and ClientConn state update

---

internal/transport/http2_client.go

Cherry pick #4561 to v1.38.x branch

---

xds/internal/xdsclient/bootstrap/bootstrap.go

Fixes https://github.com/grpc/grpc-go/issues/4544

Fix bootstrap format in comment

---

internal/binarylog/sink.go

internal/binarylog: Use defer to unlock mutexes

---

internal/binarylog/sink.go

... to start the flusher thread
Given that we pick up the mutex on the line below, we can simply use that for concurrency control.
This removes an atomic read from the hot path.

binarylog: Use a simple boolean rather than a sync.Once

---

version.go

Change version to 1.41.0-dev

---

internal/xds/env/env.go

xds: fix a typo

---

version.go

Change version to 1.39.1

---

version.go

Change version to 1.39.2-dev

---

xds/internal/server/listener_wrapper_test.go
xds/internal/testutils/e2e/clientresources.go
xds/internal/xdsclient/client.go
xds/internal/xdsclient/filter_chain.go
xds/internal/xdsclient/filter_chain_test.go
xds/internal/xdsclient/lds_test.go
xds/internal/xdsclient/rds_test.go
xds/internal/xdsclient/v2/rds_test.go
xds/internal/xdsclient/xds.go
xds/server_test.go

This PR adds the route to FilterChain.

xds: Add route to filterchain

---

xds/internal/balancer/clusterimpl/balancer_test.go

Fixes https://github.com/grpc/grpc-go/issues/4646

xds: fix flaky test (TestPickerUpdateAfterClose)

---

test/kokoro/xds_k8s.sh

Related grpc/grpc#26955 cl/389407788
https://fusion2.corp.google.com/invocations/7c2feebf-c1de-4526-a952-8013438b6adc/targets

Update xDS client/server image per-branch tag after build

---

authz/rbac_translator.go
balancer/rls/internal/keys/builder.go
balancer/roundrobin/roundrobin.go
channelz/service/service.go
cmd/protoc-gen-go-grpc/grpc.go
internal/channelz/funcs.go
internal/resolver/dns/dns_resolver.go
internal/resolver/dns/dns_resolver_test.go
internal/xds/rbac/rbac_engine.go
interop/xds/client/client.go
xds/csds/csds.go
xds/internal/balancer/clusterresolver/configbuilder.go
xds/internal/resolver/matcher.go
xds/internal/testutils/protos.go
xds/internal/xdsclient/filter_chain.go
xds/internal/xdsclient/transport_helper.go
xds/internal/xdsclient/v2/loadreport.go
xds/internal/xdsclient/v3/loadreport.go
xds/internal/xdsclient/xds.go

I'd spotted few places in xds client code where slices could be preallocated to avoid extra allocations, but then I simply used https://github.com/alexkohler/prealloc to track down similar issues throughout the codebase.

all: preallocate slices where possible

---

internal/resolver/config_selector.go
xds/internal/resolver/serviceconfig.go
xds/internal/resolver/xds_resolver_test.go
xds/internal/server/conn_wrapper.go
xds/internal/server/listener_wrapper.go
xds/internal/xdsclient/filter_chain.go
xds/internal/xdsclient/filter_chain_test.go
xds/internal/xdsclient/matcher.go
xds/internal/xdsclient/matcher_path.go
xds/internal/xdsclient/matcher_path_test.go
xds/internal/xdsclient/matcher_test.go

This PR instantiates HTTP Filters on server side and converts route to something usable, which get put into wrapped conn which eventually will make its way to xds(Unary|Stream)Interceptors for routing.

xds: Instantiated HTTP Filters on Server Side

---

xds/internal/test/xds_client_integration_test.go
xds/internal/test/xds_integration_test.go
xds/internal/test/xds_server_integration_test.go
xds/internal/test/xds_server_serving_mode_test.go

Fixes https://github.com/grpc/grpc-go/issues/4704.

xds: start a management server per test

---

internal/xds/env/env.go
xds/internal/test/xds_integration_test.go
xds/internal/xdsclient/cds_test.go
xds/internal/xdsclient/xds.go

xds: remove env var protection for security on client

---

credentials/alts/internal/conn/record_test.go

credentials/ALTS: Ensure ALTS record protocol names are consistent

---

clientconn.go
test/end2end_test.go

This is a regression on master, not in the latest release.

client: fix case where GOAWAY would leak connections and memory

---

clientconn.go

grpc: clarify the use of transport.ErrConnClosing from createTransport()

---

NOTICE.txt

license: add NOTICE.txt file

---

test/kokoro/xds_url_map.sh

grpc/grpc#27373 
Fixes b/200220655
Test run:
- https://fusion2.corp.google.com/invocations/d050855d-c8fb-4811-9c93-ad9104794d85
@menghanl

[Backport grpc#27373] add testing_version flag

---

version.go

Change version to 1.41.0

---

version.go

Change version to 1.42.0-dev

---

internal/transport/http2_server.go

transport: fix a typo in http2_server.go

---

.github/workflows/codeql-analysis.yml
.github/workflows/testing.yml

github: set a shorter timeout on testing jobs

---

xds/internal/test/xds_server_integration_test.go

Fixes https://github.com/grpc/grpc-go/issues/4802

xds: have separate tests for RBAC on and off

---

xds/internal/balancer/clustermanager/balancerstateaggregator.go
xds/internal/balancer/clustermanager/clustermanager_test.go
xds/internal/balancer/weightedtarget/weightedaggregator/aggregator.go
xds/internal/balancer/weightedtarget/weightedtarget_test.go

xds: fix parent balancers to handle Idle children (backport of #4801)

---

version.go

Change version to 1.41.1-dev

---

internal/transport/http2_client.go
internal/transport/http2_server.go
test/end2end_test.go
test/retry_test.go

test: add option to make httpServer wait for END_STREAM; fix RetryStats race

---

picker_wrapper.go

internal: log SubConn type if it's not the expected type

---

xds/internal/test/xds_security_config_nack_test.go

Fixes https://github.com/grpc/grpc-go/issues/4834

xds: remove race in TestUnmarshalCluster_WithUpdateValidatorFunc

---

test/kokoro/xds.sh

kokoro: remove expired letsencrypt.org cert and update

---

xds/internal/test/xds_server_serving_mode_test.go
xds/internal/xdsclient/callback.go
xds/internal/xdsclient/client_test.go
xds/internal/xdsclient/watchers_cluster_test.go
xds/internal/xdsclient/watchers_endpoints_test.go
xds/internal/xdsclient/watchers_listener_test.go
xds/internal/xdsclient/watchers_route_test.go

Fixes https://github.com/grpc/grpc-go/issues/4695

xds: suppress redundant resource updates using proto.Equal

---

balancer/rls/internal/proto/grpc_lookup_v1/rls_config.pb.go

internal: update rls.pb.go

---

version.go

Change version to 1.43.0-dev

---

channelz/grpc_channelz_v1/channelz.pb.go

internal: update pb.go

---

internal/transport/http2_client.go
internal/transport/transport_test.go

Currently the handshake info is passed as part of connect context after the dial, this change moves the context creation before the dial.
This allows the resolver for example to information to custom dialers which previously would not have been possible. 

transport: pass handshake info with attributes to custom dialers

---

xds/internal/clusterspecifier/cluster_specifier.go
xds/internal/xdsclient/xdsresource/type_rds.go
xds/internal/xdsclient/xdsresource/unmarshal_rds.go
xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go

This PR defines the Cluster Specifier API, and also adds support for parsing Cluster Specifier Plugins in the xdsclient.

xds: Add Cluster Specifier Plugin to xdsclient

---

version.go

Change version to 1.44.0-dev

---

xds/internal/xdsclient/xdsresource/name.go
xds/internal/xdsclient/xdsresource/name_test.go

xds/federation: resource name parsing

---

internal/transport/http2_client.go
xds/internal/xdsclient/controller/transport.go
xds/internal/xdsclient/pubsub/update.go

This cherrypick includes the following:
- #5054
- #5033
- #5032

cherrypick: v1.43.x

---

version.go

Change version to 1.43.0

---

version.go

Change version to 1.43.1-dev

---

version.go

Change version to 1.45.0-dev

---

xds/internal/xdsclient/controller/controller_test.go

xds/controller: fix test nil panic on stream errors

---

CONTRIBUTING.md

recommend the use `go test` commands instead of `make test`

---

benchmark/worker/benchmark_client.go

benchmark: update client to include xds library

---

interop/grpclb_fallback/client_linux.go

xds/interop: update RPC timeout in blackhole after fallback case

---

internal/envconfig/xds.go
xds/internal/xdsclient/xdsresource/type_cds.go
xds/internal/xdsclient/xdsresource/unmarshal_cds.go
xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go

This PR adds support for Outlier Detection configuration parsing in CDS. It implements the validations specified in A50: https://github.com/grpc/proposal/blob/32a84955b90552ccae3bc355fb9f336882348e13/A50-xds-outlier-detection.md#validation.

xds: Add support for Outlier Detection configuration in xdsclient

---

xds/internal/balancer/priority/balancer_priority.go

Those are not error logs, and can happen in races. They could confuse the users.

xds/priority: log warnings instead of errors

---

channelz/service/service_sktopt_test.go
channelz/service/service_test.go
internal/channelz/funcs.go
test/channelz_linux_test.go
test/channelz_test.go

channelz: rename NewChannelzStorage to NewChannelzStorageForTesting

---

version.go

Change version to 1.46.0-dev

---

clientconn.go

grpc: document ClientConn fields

---

version.go

Change version to 1.45.0

---

version.go

Change version to 1.45.1-dev

---

xds/internal/xdsclient/controller/transport.go

xds/client: reset backoff when a message is received, even when the message is invalid

---

xds/internal/xdsclient/authority.go
xds/internal/xdsclient/client_test.go
xds/internal/xdsclient/pubsub/pubsub.go
xds/internal/xdsclient/pubsub/watch.go

xds/client: include Node ID in error messages from the XdsClient

---

clientconn_authority_test.go
clientconn_parsed_target_test.go
dialoptions.go
pickfirst_test.go
resolver_conn_wrapper_test.go

grpc: remove remaining usages of grpc.WithInsecure()

---

xds/internal/xdsclient/bootstrap/bootstrap.go
xds/internal/xdsclient/bootstrap/bootstrap_test.go
xds/internal/xdsclient/xdsresource/type.go
xds/internal/xdsclient/xdsresource/unmarshal_cds.go
xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
xds/internal/xdsclient/xdsresource/unmarshal_eds.go
xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
xds/internal/xdsclient/xdsresource/unmarshal_lds.go
xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
xds/internal/xdsclient/xdsresource/unmarshal_rds.go
xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
xds/internal/xdsclient/xdsresource/version/version.go

xds/client: accept resources wrapped in discoverypb.Resource message

---

.github/workflows/testing.yml

github: update to test with Go 1.18

---

.github/workflows/testing.yml

github: run all testing jobs to completion even if one fails

---

version.go

Change version to 1.47.0-dev

---

internal/testutils/balancer.go
xds/internal/balancer/priority/balancer_test.go

xds/priority: clean up tests

---

test/kokoro/xds.sh
test/kokoro/xds_k8s_lb.cfg
test/kokoro/xds_k8s_lb.sh

```
git cherry-pick 939e0489
```

test/kokoro: apply xDS interop best practice (backport v1.43.x)

---

test/kokoro/xds.sh
test/kokoro/xds_k8s_lb.cfg
test/kokoro/xds_k8s_lb.sh

```
git cherry-pick 939e0489
```

test/kokoro: apply xDS interop best practice (backport v1.44.x)

---

gcp/observability/exporting.go

Context: [this](https://docs.google.com/document/d/13vUtM_x9Lhq3hHAl15uyy7Y7MGOJ4JDm5Tk5quhVz_8/edit#)
The Java effort: https://github.com/grpc/grpc-java/pull/9145
Manual test: https://screenshot.googleplex.com/AMnvgoDcwFZF34C

gcp/observability: update log name

---

test/kokoro/xds.sh
test/kokoro/xds_k8s_lb.cfg
test/kokoro/xds_k8s_lb.sh
test/kokoro/xds_url_map.sh

```
git cherry-pick a58adb03
```

test/kokoro: apply xDS interop best practice (backport v1.39.x)

---

test/kokoro/xds.sh
test/kokoro/xds_k8s_lb.cfg
test/kokoro/xds_k8s_lb.sh

```
git cherry-pick a58adb03
```

test/kokoro: apply xDS interop best practice (backport v1.40.x)

---

balancer/weightedroundrobin/weightedroundrobin.go

As part of https://github.com/grpc/grpc-go/issues/5420

weightedroundrobin: update comments to indicate where addrInfo is stored

---

resolver/map.go
resolver/map_test.go
resolver/resolver.go

As part of https://github.com/grpc/grpc-go/issues/5420

resolver: minor improvements to AddressMap

---

internal/binarylog/binarylog.go

fix typo in the binary log

---

version.go

Change version to 1.49.0-dev

---

xds/internal/xdsclient/attributes.go
xds/internal/xdsclient/client.go

Part of https://github.com/grpc/grpc-go/issues/5478.

xdsclient: move XDSClient interface definition to client.go

---

internal/envconfig/xds.go

RELEASE NOTES:
xds: fix errors caused by enabling Outlier Detection

Backport Outlier Detection Fix to 1.48

---

test/roundrobin_test.go

Fixes https://github.com/grpc/grpc-go/issues/5497
Fixes https://github.com/grpc/grpc-go/issues/5490

test: improve the logic for checking round_robin

---

clientconn.go

Switched mutex unlock to defer in newAddrConn

---

internal/transport/controlbuf.go

internal/transport: fix typo

---

internal/testutils/fakegrpclb/server.go

internal/fakegrpclb: don't listen on all adapters

---

balancer/rls/balancer_test.go
credentials/alts/internal/conn/record_test.go
internal/testutils/balancer.go
internal/testutils/roundrobin/roundrobin.go
xds/internal/balancer/clusterimpl/balancer_test.go
xds/internal/balancer/priority/balancer_test.go

cleanup: fixes for issues surfaced by vet

---

Documentation/proxy.md

Documentation/proxy: update due to Go 1.16 behavior change

---

orca/service.go

orca: fix package used to reference service to use pb suffix instead of grpc

---

test/metadata_test.go

test: loosen metadata error check to reduce dependence on exact library errors

---

test/kokoro/xds_k8s_lb.sh

This PR enabled Outlier Detection interop tests

xds: Enable Outlier Detection interop tests

---

version.go

Change version to 1.51.0-dev

---

xds/internal/testutils/fakeserver/server.go

This is required by tests which use the xDS fakeserver with a v3 xDS transport.

fakeserver: add v3 support to the xDS fakeserver implementation

---

xds/googledirectpath/googlec2p.go

Similar C++ PR in https://github.com/grpc/grpc/pull/31471
Along with https://github.com/grpc/grpc-go/pull/5743, this will allow us to start integration testing the bootstrap + federation use case.
cc @easwars 

google-c2p: include federation env var in the logic which determines when to use directpath

---

version.go

Change version to 1.52.0-dev

---

internal/resolver/dns/dns_resolver.go
internal/resolver/dns/dns_resolver_test.go
internal/resolver/unix/unix.go
stream.go

see https://github.com/grpc/grpc-go/issues/5754

Cleanup usages of resolver.Target's Scheme and Authority

---

reflection/serverreflection.go
reflection/serverreflection_test.go

reflection: split grpc and pb imports

---

interop/xds/client/Dockerfile
interop/xds/server/Dockerfile

interop: update Go version in docker container used for psm interop

---

dialoptions.go
server.go

Fixes #5798 
Quick doc fix. Includes formatting changes to wrap lines. No release notes.

grpc: Improve documentation of read/write buffer size server and dial options

---

internal/transport/transport_test.go

Fixes #5283
It seems the tests were always making progress, and were mostly nearly done after 10s.  Most test runs finished in 2-3s, so 10s is a bit of an outlier, but I think it's more important to fix the flaky test at this point than identify the cause of the long tail and potentially redesign the transport to mitigate it.

transport: limit AccountCheck tests to fewer streams and iterations to avoid flakes

---

xds/internal/xdsclient/transport/transport_ack_nack_test.go

The go-control-plane server continuously resends resources which are nacked. This means that tests which push received resources on to a channel to be read by some other goroutine will have to ensure that they are not blocked trying to write on the channel (when no one else is reading from it). One way to ensure this is to select on the context deadline as well.
With these changes, these tests pass without any flakes on google3 after 100K runs.

xdsclient: deflake new transport ack/nack tests

---

balancer/rls/control_channel_test.go

This PR fixes a regex in rls test, which will unblock import and make the regex correct.

rls: Fix regex in rls test

---

examples/examples_test.sh

Add  feature/cancellation and feature/retry to example_test script
RELEASE NOTES:
* N/A

examples: add feature/cancellation retry to example test script

---

benchmark/stats/stats.go

benchmark: fix typo in ClientReadBufferSize feature name

---

version.go

Change version to 1.53.0-dev

---

.github/workflows/testing.yml
vet.sh

vet & github: run vet separately from tests; make vet-proto only check protos

---

internal/envconfig/envconfig.go
internal/envconfig/envconfig_test.go
internal/envconfig/xds.go

internal/envconfig: add convenience boolFromEnv to improve readability

---

xds/internal/resolver/xds_resolver_test.go

xds/resolver: cleanup tests to use real xDS client

---

internal/testutils/parse_url.go
xds/internal/resolver/xds_resolver_test.go

xds/resolver: cleanup tests to use real xDS client 4/n

---

gcp/observability/observability.go

This PR cleans up any resources allocated in the observability module's Start function. As per Eric, this cleanup should happen automatically, which is normal API expectations.
I didn't add a unit test for a few reasons:
1. I didn't want to add more hook points into the codebase, making it harder to read.
2. The scenario that this wraps with respect to automatic cleanup is extremely specific and a not thought implementation detail of the ordering of the creation of the resources required for the observability module to function, making a test which verifies this extremely brittle and tied heavily to implementation. The scenario here is a stackdriver exporter is created and either view registration or cloud logging exporter creation fails.

gcp/observability: Cleanup resources allocated if Start errors

---

version.go

Change version to 1.52.1

---

version.go

Change version to 1.52.2-dev

---

version.go

Change version to 1.52.2

---

version.go

Change version to 1.52.3

---

version.go

Change version to 1.52.4-dev

---

version.go

Change version to 1.54.0-dev

---

xds/csds/csds_e2e_test.go

xds/csds: switch tests to use the new generic xdsclient API

---

internal/transport/http2_server.go
metadata/metadata.go

metadata: slightly improve operateHeaders

---

clientconn_test.go
internal/transport/http2_client.go
internal/transport/keepalive_test.go
test/goaway_test.go

internal/transport: fix severity of log when receiving a GOAWAY with error code ENHANCE_YOUR_CALM

---

xds/internal/xdsclient/xdsresource/unmarshal_cds.go
xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go

xds/internal/xdsclient: NACK empty clusters in aggregate clusters

---

xds/internal/xdsclient/xdsresource/unmarshal_eds.go

xdsclient: minor cleanup in eds parsing

---

channelz/service/func_linux.go

Addresses https://github.com/grpc/grpc-go/issues/6015

channelz: remove dependency on testing package

---

admin/test/utils.go

admin/test: split channelz imports

---

xds/internal/testutils/fakeserver/server.go

fakeserver: remove ADS and LRS v2 support

---

xds/internal/resolver/xds_resolver_test.go

Fixes https://github.com/grpc/grpc-go/issues/6081

xds/resolver/test: use a non-blocking send instead of closing the channel

---

xds/internal/xdsclient/authority.go

This PR handles a race wrt to timer expiry which can occur if the management server responds to a resource (for which a watch has been registered), but a request has not yet been sent.
Release notes are not required for this, since the A57 changes have not yet made it to any release.
Fixes https://github.com/grpc/grpc-go/issues/6069.

xdsclient: handle race with watch timer handling

---

internal/transport/controlbuf.go

transport: stop returning errors that are always nil

---

examples/README.md
examples/helloworld/README.md

examples: organize READMEs better

---

version.go

Change version to 1.54.0

---

version.go

Change version to 1.54.1-dev

---

version.go

Change version to 1.56.0-dev

---

xds/internal/testutils/resource_watcher.go
xds/internal/xdsclient/authority_test.go

fixes: #6075 
should also potentially fix: #6070 

tests: defalke TestTimerAndWatchStateOnSendCallback

---

gcp/observability/logging.go

gcp/observability: remove redundant import

---

authz/audit/audit_logger.go

Cherry picking this change to the new audit package to the v1.55.x branch cut

authz: Move audit package (#6218)

---

test/end2end_test.go

We have been seeing quite a few timeouts in the `test` package and this test seems to the the longest runner. 
TestClientDoesntDeadlockWhileWritingErroneousLargeMessages is a stress test on the control buf. This test sets the maxServerReceivedMsgSize to a small window size and asserts that UnaryRPCs fail with a ResourceExhausted error. 
This test was added as part of #1859 -- which fixed a race when we were not adding flow control quota back when there was a write error (like in the test with writing a larger than window size message). 
However now it seems like we get writeQuota before checking the transport flow control. I think we can nix this test 
Testing results on forge
```
Stats over 10000 runs: max = 104.2s, min = 17.3s, avg = 33.7s, dev = 7.8s
```
```
Stats over 10000 runs: max …
```

tests: nix TestClientDoesntDeadlockWhileWritingErroneousLargeMessages

---

internal/stubserver/stubserver.go

stubserver: add option for allowing more services to be registered

---

balancer_conn_wrappers.go

grpc: handle RemoveSubConn inline in balancerWrapper

---

balancer_conn_wrappers.go
clientconn.go
orca/producer.go
test/balancer_test.go

balancer: make producer RPCs block until the SubConn is READY

---

version.go

Change version to 1.55.0

---

version.go

Change version to 1.55.1-dev

---

stream.go

Relates to https://github.com/grpc/grpc-go/issues/5857 and https://github.com/grpc/grpc-go/pull/5894#issuecomment-1530947302.
PTAL @easwars

Update ClientStream.SendMsg doc

---

version.go

Update version to 1.54.1

---

version.go

Update version.go to 1.54.2-dev

---

interop/client/client.go
interop/observability/go.mod
interop/observability/go.sum
interop/orcalb.go
interop/server/server.go
interop/test_utils.go

interop: add ORCA test cases and functionality

---

balancer/weightedroundrobin/balancer_test.go

weightedroundrobin: fix test race accessing timeNow

---

service_config.go
service_config_test.go

cleanup: use new Duration type in base ServiceConfig

---

credentials/alts/alts_test.go
credentials/alts/internal/testutil/testutil.go

This fixes the flaky test identified in #6294.

alts: Fix flaky ALTS TestFullHandshake test.

---

dialoptions.go

client: disable channel idleness by default

---

version.go

Change version to 1.57.0-dev

---

balancer/grpclb/grpclb_test.go

grpclb: fix typo

---

internal/balancer/nop/nop.go
test/xds/xds_client_outlier_detection_test.go
xds/internal/balancer/cdsbalancer/cdsbalancer.go
xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
xds/internal/balancer/clusterresolver/clusterresolver.go
xds/internal/balancer/clusterresolver/clusterresolver_test.go
xds/internal/balancer/clusterresolver/config.go
xds/internal/balancer/clusterresolver/config_test.go
xds/internal/balancer/clusterresolver/configbuilder.go
xds/internal/balancer/clusterresolver/configbuilder_test.go
xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
xds/internal/balancer/clusterresolver/priority_test.go
xds/internal/balancer/outlierdetection/balancer.go
xds/internal/balancer/outlierdetection/balancer_test.go
xds/internal/balancer/outlierdetection/config.go
xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
xds/internal/xdsclient/xdsresource/type_cds.go
xds/internal/xdsclient/xdsresource/unmarshal_cds.go
xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go

RELEASE NOTES:
* xds/internal/xdsclient/xdsresource: Fix Outlier Detection Config Handling and correctly set xDS Defaults
* xds/internal/balancer/outlierdetection: Fix Outlier Detection Config Handling by setting defaults in ParseConfig()

xds/outlierdetection: Cherry pick 1 commit from master.

---

version.go

Change version to 1.56.0

---

clientconn.go
test/subconn_test.go

RELEASE NOTES:
* handle empty address lists correctly in addrConn.updateAddrs

client: cherry-pick 1 commit from master

---

version.go

Update version.go to v1.56.1

---

version.go

Update version.go to v1.56.2-dev

---

xds/internal/xdsclient/clientimpl_authority.go
xds/internal/xdsclient/logging.go

xdsclient: indicate authority serverURI in authority + transport logs

---

orca/orca.go

orca: remove useless log statement

---

version.go

Update version.go to v1.56.2

---

version.go

Upgrade version.go to v1.55.1

---

version.go

Upgrade version.go to 1.55.2-dev

---

version.go

Change version to 1.58.0-dev

---

balancer/weightedroundrobin/balancer.go
test/xds/xds_client_custom_lb_test.go

Cherry-pick #6477 to v1.57.x

---

xds/internal/balancer/clusterimpl/balancer_test.go
xds/internal/balancer/clusterimpl/clusterimpl.go

All children use `StateListener` so this is unnecessary now.

xds/clusterimpl: stop forwarding UpdateSubConnState calls

---

test/creds_test.go

test: speed up test that was taking 10 seconds to timeout

---

vet.sh

vet.sh: fix interface{} check for macos

---

interop/xds/custom_lb_test.go

Fixes [this issue](https://github.com/grpc/grpc-go/pull/6575#discussion_r1316508128) discussed in PR #6575 

interop/xds: improve error message

---

health/grpc_health_v1/health_grpc.pb.go

health/grpc_health_v1: update pb.go

---

version.go

update version to 1.58.1

---

version.go

update version to 1.58.2-dev

---

version.go

Change version to 1.58.2

---

version.go

update version to 1.58.3-dev

---

test/xds/xds_client_custom_lb_test.go

Fix: testing parameter in xds_client_custom_lb_test

---

version.go

Change version to 1.60.0-dev

---

version.go

Change version.go to 1.58.4-dev

---

version.go

Change version to 1.57.2-dev

---

version.go

Change version to 1.59.0

---

version.go

Change version.go to 1.59.1-dev

---

version.go

Change version to 1.61.0-dev

---

security/advancedtls/crl_provider_test.go

Fix for broken import

---

internal/tcp_keepalive_nonunix.go
internal/tcp_keepalive_unix.go

Cherry-pick #6841 to v1.60.x release branch

---

server.go
server_ext_test.go

RELEASE NOTES:
- server: fix two bugs that could lead to panics at shutdown when using [NumStreamWorkers](https://pkg.go.dev/google.golang.org/grpc#NumStreamWorkers) (experimental feature).

Cherry-pick #6856 to v1.60.x release branch

---

version.go

Update version.go to v1.60.1

---

version.go

Update version.go to 1.60.2-dev

---

credentials/alts/alts_test.go
credentials/alts/internal/handshaker/handshaker.go
credentials/alts/internal/handshaker/handshaker_test.go

alts: Queue ALTS handshakes once limit is reached rather than dropping.

---

binarylog/grpc_binarylog_v1/binarylog.pb.go

deps: apply `make proto` changes

---

encoding/proto/proto_benchmark_test.go
encoding/proto/proto_test.go

encoding/proto: make sure proto imports are renamed

---

version.go

Change version to 1.63.0-dev

---

examples/features/stats_monitoring/README.md

examples: fix typo in url

---

version.go

Change version to 1.62.0

---

version.go

Switch version to 1.62.1-dev

---

server.go
test/channelz_test.go

Cherry-pick bug fix PR #7062 to v1.63.x

channelz: add LocalAddr to listen sockets and test (#7062)

---

cmd/protoc-gen-go-grpc/grpc.go

cmd/protoc-gen-go-grpc: replace usages of deprecated API

---

channelz/service/service_test.go
clientconn.go
internal/channelz/funcs.go
internal/transport/keepalive_test.go
internal/transport/transport_test.go
test/channelz_test.go

v1.63.x: grpc: un-deprecate Dial and DialContext and cherry-pick #7101

---

Makefile

add deps、testsubmodule、testdeps to PHONY

Makefile: perfect PHONY

---

xds/internal/test/e2e/run.sh

xds: remove -v when running xds e2e tests

---

channelz/grpc_channelz_v1/channelz.pb.go

pb.go: regenerate

---

default_dial_option_server_option_test.go
dialoptions.go

grpc: fix function names in comments

---

MAINTAINERS.md

As discussed offline with @dfawley and @ginayeh.

Add atollena to MAINTAINERS.md

---

version.go

Change version to 1.65.0-dev

---

test/kokoro/psm-csm.cfg

test/kokoro: Add psm-csm build config

---

version.go

Change version to 1.66.0-dev

---

xds/internal/balancer/cdsbalancer/aggregate_cluster_test.go
xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
xds/internal/internal.go
xds/internal/xdsclient/tests/cds_watchers_test.go
xds/internal/xdsclient/tests/resource_update_test.go
xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
xds/internal/xdsclient/xdsresource/unmarshal_cds.go
xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go

xds/internal/xdsclient: Emit unknown for CSM Labels if not present in CDS (#7309)

---

stats/opentelemetry/e2e_test.go

stats/opentelemetry: Fix protobuf import

---

xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go

fix testclient type in ringhash_balancer_test checkRPCSendOK

---

test/pickfirst_test.go

test: fix typo in pickfirst_test.go

---

.github/workflows/coverage.yml

github: update codecov with token and fail_ci_if_error

---

balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
channelz/grpc_channelz_v1/channelz_grpc.pb.go
health/grpc_health_v1/health_grpc.pb.go
profiling/proto/service_grpc.pb.go
reflection/grpc_reflection_v1/reflection_grpc.pb.go
reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go

*.pb.go: regenerate

---

xds/bootstrap/credentials.go
xds/csds/csds_e2e_test.go
xds/googledirectpath/googlec2p_test.go

xds: fix typos

---

balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
channelz/grpc_channelz_v1/channelz_grpc.pb.go
cmd/protoc-gen-go-grpc/grpc.go
credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
examples/features/proto/echo/echo_grpc.pb.go
examples/helloworld/helloworld/helloworld_grpc.pb.go
examples/route_guide/routeguide/route_guide_grpc.pb.go
health/grpc_health_v1/health_grpc.pb.go
internal/proto/grpc_lookup_v1/rls_grpc.pb.go
interop/grpc_testing/benchmark_service_grpc.pb.go
interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
interop/grpc_testing/test_grpc.pb.go
interop/grpc_testing/worker_service_grpc.pb.go
interop/stress/grpc_testing/metrics_grpc.pb.go
profiling/proto/service_grpc.pb.go
reflection/grpc_reflection_v1/reflection_grpc.pb.go
reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
reflection/grpc_testing/test_grpc.pb.go

cmd/protoc-gen-go-grpc: fix typo pancis -> panics

---

channelz/grpc_channelz_v1/channelz.pb.go
credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go
reflection/grpc_reflection_v1alpha/reflection.pb.go

*.pb.go: regenerate protos

---

version.go

Change version to 1.67.0-dev

---

balancer_wrapper.go
clientconn.go
producer_ext_test.go
resolver_balancer_ext_test.go

cherry-pick #7523 to v1.66.x branch

---

version.go

Change version to 1.66.0

---

version.go

Change to patch release 1.66.1

---

version.go

Change version to 1.68.0-dev

---

version.go

Change to version 1.66.2-dev

---

version.go

Change version to 1.66.2

---

mem/buffer_slice.go

cherry-pick #7595 to v1.67.x branch

---

Documentation/encoding.md
examples/gotutorial.md

* : Replace tab with spaces in text files

---

version.go

Change version to 1.67.0

---

xds/internal/server/conn_wrapper.go
xds/internal/server/listener_wrapper.go
xds/internal/server/listener_wrapper_test.go

Original PR: #7664 
Addresses: #7657
RELEASE NOTES:
* transport: Fix a bug causing stream failures due miscalculation of the flow control window in both clients and servers.

cherry-pick #7664 to v1.67.x branch

---

version.go

Change version to 1.67.1

---

version.go

Change version to 1.66.3

---

version.go

Change version to 1.66.4-dev

---

version.go

Change version to 1.65.1

---

version.go

Change version to 1.65.2-dev

---

xds/internal/xdsclient/transport/transport_test.go

xdsclient: fix test build breakage

---

version.go

Change version to 1.69.0-dev

---

internal/transport/flowcontrol.go

transport: refactor `trInFlow.onData` to eliminate redundant logic

---

balancer/rls/config.go
balancer/rls/control_channel.go
balancer/weightedtarget/weightedtarget.go
xds/internal/balancer/clustermanager/clustermanager.go
xds/internal/balancer/clusterresolver/clusterresolver.go
xds/internal/balancer/ringhash/ringhash.go

multiple: add verbosity checks to logs that use pretty.JSON

---

server.go

Skip calling metadata.FromIncomingContext if there are no stats hnadlers. This function is relatively expensive because it makes a copy of the map of gRPC headers. For our production services that use tracing libraries, this means there are typically about ~10 headers on every call. For services with cheap gRPC calls, this can use nearly 1% of CPU.
There are unit tests that cover this code path in the stats package but sadly I did not find any existing microbenchmarks that we could easily use to verify this improvement.

server: Only call FromIncomingContext with stats handlers

---

balancer/endpointsharding/endpointsharding.go

This PR adds the functionality of calling ExitIdle on any child that reports IDLE, to automatically retrigger the child to try and start connecting.
In the future, we could make this configurable through a config (which we will also need to add), but for all the use cases of this endpoint sharding policy the desired behavior is to trigger ExitIdle on the child so we can leave default for now.
This is because petiole policies used to be able to call Connect() on SubConns, but now that pick_first is the universal leaf, that will be the only balancer that will contain the logic for SubConn management, so petioles have no way of triggering this reconnection, as previously present in the system.
RELEASE NOTES:
* balancer/endpointsharding: Call ExitIdle() on child if child reports IDLE

balancer/endpointsharding: Call ExitIdle() on child if child reports IDLE

---

balancer/grpclb/grpclb_test.go

cleanup: replace grpc.Dial with grpc.NewClient in grpclb test

---

internal/xds/matcher/matcher_header.go

xds: rename helper to remove mention of OutgoingCtx

---

version.go

Change version to 1.67.2

---

version.go

Change version to 1.68.1

---

version.go

Change version to 1.67.3-dev

---

test/kokoro/psm-fallback.cfg

test/kokoro: Add psm-fallback build config

---

version.go

Change version to 1.69.1

---

examples/features/csm_observability/server/main.go

Cherry-pick #7933 into v1.69.x

---

version.go

Change version to 1.69.2-dev

---

version.go

Change version to 1.68.2

---

experimental/stats/metrics.go

Cherry-pick #7929

---

version.go

Change version to 1.68.3-dev

---

version.go

Change version to 1.69.2

---

version.go

Change version to 1.69.3-dev

---

version.go

Change version to 1.71.0-dev

---

version.go

Change version to 1.69.3

---

version.go

Change version to 1.69.4-dev

---

version.go

Change version to 1.69.4

---

version.go

Change version to 1.69.5-dev

---

version.go

Change version to 1.70.0

---

version.go

Change version to 1.70.1-dev

---

internal/transport/proxy_ext_test.go

transport_test: change testgrpc.Emtpy to testpb.Empty

---

scripts/vet.sh
security/advancedtls/advancedtls_integration_test.go

Fixes https://github.com/grpc/grpc-go/issues/8021

vet: make revive check submodules for lint errors

---

xds/internal/balancer/ringhash/ringhash.go

ringhash: Sort endpoints to prevent unnecessary connection attempts

---

version.go

Change version to 1.72.0-dev

---

version.go

Change version to 1.71.0

---

internal/proto/grpc_lookup_v1/rls_config.pb.go

*: Regenerate protos

---

xds/internal/balancer/cdsbalancer/cdsbalancer.go
xds/internal/balancer/clusterresolver/resource_resolver_eds.go
xds/internal/resolver/xds_resolver.go
xds/internal/server/listener_wrapper.go
xds/internal/server/rds_handler.go

Fixes https://github.com/grpc/grpc-go/issues/7931

xds: emit resource-not-found logs at Warning level

---

examples/features/retry/README.md

example/features/retry: fix grpc.NewClient call in documentation

---

xds/internal/balancer/clusterimpl/tests/balancer_test.go

internal/balancer/clusterimpl: replace testpb with testgrpc

---

version.go

Change version to v1.71.1

---

version.go

Change version 1.71.2-dev

---

version.go

Change version to 1.73.0-dev

---

credentials/alts/internal/conn/common.go
credentials/alts/internal/conn/record.go
credentials/alts/internal/conn/record_test.go
credentials/alts/internal/handshaker/handshaker.go

These changes are causing integration issues with an internal cipher implementation, see cl/745109957. The changes will be rolled forward when the cipher implementation is fixed.

Rollback #8232 and #8204

---

xds/internal/resolver/serviceconfig.go
xds/server_test.go

cleanup: status formatting bug and comment grammar fix

---

version.go

Change version to v1.72.0

---

version.go

Change version to v1.72.1-dev

---

stats/opentelemetry/e2e_test.go

Fixes: https://github.com/grpc/grpc-go/issues/8240

otel: Test streaming rpc sequence numbers

---

stream.go

Fixes: https://github.com/grpc/grpc-go/issues/8288

grpc: Update ClientStream.CloseSend docs

---

xds/internal/clients/grpctransport/examples_test.go
xds/internal/clients/grpctransport/grpc_transport.go
xds/internal/clients/grpctransport/grpc_transport_ext_test.go
xds/internal/clients/grpctransport/grpc_transport_test.go
xds/internal/clients/lrsclient/loadreport_test.go
xds/internal/clients/xdsclient/channel_test.go
xds/internal/clients/xdsclient/test/authority_test.go
xds/internal/clients/xdsclient/test/dump_test.go
xds/internal/clients/xdsclient/test/lds_watchers_test.go
xds/internal/clients/xdsclient/test/misc_watchers_test.go
xds/internal/clients/xdsclient/xdsclient_test.go

xds: modify generic clients grpctransport to accept optional custom grpc new client function

---

internal/resolver/delegatingresolver/delegatingresolver_ext_test.go

resolver/delegatingresolver: wait for proxy resolver to be built in test

---

version.go

Change version to 1.72.1

---

balancer/rls/control_channel.go

rls: removing unused channel

---

version.go

Change version to v1.71.2

---

version.go

Change version to v1.72.2-dev

---

version.go

Change version to v1.71.3-dev

---

version.go

Change version to v1.71.3

---

version.go

Change version to v1.72.2

---

version.go

Update version to 1.71.4-dev

---

version.go

Update version to 1.72.3-dev

---

version.go

Change version to 1.73.0

---

version.go

Change version to 1.73.1-dev

---

balancer/endpointsharding/endpointsharding_test.go
balancer/lazy/lazy_ext_test.go
balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
balancer/rls/balancer_test.go
internal/balancer/stub/stub.go
internal/balancergroup/balancergroup_test.go
internal/idle/idle_e2e_test.go
test/balancer_switching_test.go
test/balancer_test.go
test/healthcheck_test.go
test/resolver_update_test.go
xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
xds/internal/balancer/clustermanager/clustermanager_test.go
xds/internal/balancer/clustermanager/e2e_test/clustermanager_test.go
xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
xds/internal/balancer/outlierdetection/balancer_test.go
xds/internal/balancer/priority/balancer_test.go

Fixes https://github.com/grpc/grpc-go/issues/8371

cleanup: Add child balancer in stub.BalancerData

---

Documentation/grpc-auth-support.md
internal/envconfig/envconfig.go
internal/transport/http2_client.go
test/creds_test.go

Revert "credentials: allow audience to be configured (#8421)"

---

internal/transport/http2_server.go
internal/xds/bootstrap/bootstrap.go
internal/xds/bootstrap/bootstrap_test.go
xds/internal/clients/xdsclient/channel.go
xds/internal/clients/xdsclient/helpers_test.go
xds/internal/clients/xdsclient/resource_type.go
xds/internal/clients/xdsclient/test/helpers_test.go
xds/internal/xdsclient/pool.go
xds/internal/xdsclient/pool/pool_test.go
xds/internal/xdsclient/xdsresource/resource_type.go

Original PRs: #8411, #8419, #8422, #8445 and #8451

Cherry-pick #8411, #8419, #8422, #8445 and #8451 to v1.74.x

---

version.go

Change version to 1.74.1-dev

---

go.mod

Retract v1.74.0 and v1.74.1

---

go.mod

Cherry-pick #8456 into v1.74.x release branch

---

version.go

Change version to 1.74.2-dev

---

version.go

Change version to 1.74.2

---

version.go

Change version to 1.74.3-dev

---

version.go

Change version to 1.76.0-dev

---

version.go

Change version to 1.75.1

---

version.go

Change version to v1.74.3

---

version.go

Change version to v1.73.1

---

version.go

Change version to v1.75.2-dev

---

version.go

Change version to 1.72.4-dev

---

version.go

Change version to 1.77.0-dev

---

internal/xds/xdsclient/tests/fallback/fallback_test.go

Currently, tests in the `internal/xds/xdsclient/tests` package can take close to a minute to run. Almost half of that time is taken by the fallback tests which actually have to run longer because they have to wait for connections to go down and come up and for these events to be detected by the code (before fallback is triggered).
Splitting the fallback tests into a separate directory almost reduces the time by half since tests from these two packages can now run in parallel. 
We *could* possibly add a way for tests to add some dial options (to be used when dialing the management server), and thereby reduce the time spent in exponential backoff before connections are reattempted (during the fallback process). But this would require non-trivial amount of work, and could make the code more …

xdsclient/tests: move fallback tests to separate directory

---

internal/xds/balancer/clusterimpl/clusterimpl.go
internal/xds/clients/xdsclient/ads_stream.go

xds: Fix log level and message

---

internal/xds/balancer/clusterimpl/balancer_test.go
internal/xds/xdsclient/requests_counter.go

clusterimpl: remove unused code in tests
