- xds/internal/client/client.go
- xds/internal/client/client_callback.go
- xds/internal/client/client_test.go
- xds/internal/client/client_watchers.go
- xds/internal/client/client_watchers_cluster_test.go
- xds/internal/client/client_watchers_endpoints_test.go
- xds/internal/client/client_watchers_lds_test.go
- xds/internal/client/client_watchers_rds_test.go
- xds/internal/client/client_watchers_service_test.go
- xds/internal/client/client_xds.go
- xds/internal/client/transport_helper.go
- xds/internal/client/v2/client.go
- xds/internal/client/v2/client_ack_test.go
- xds/internal/client/v2/client_cds_test.go
- xds/internal/client/v2/client_eds_test.go
- xds/internal/client/v2/client_lds_test.go
- xds/internal/client/v2/client_rds_test.go
- xds/internal/client/v2/client_test.go
- xds/internal/client/v3/client.go
- xds/xds.go
* This will be used from the xdsServer.
* Also fix one thing which was missed out in the xDS v3 support PR:
* Watches registered on the xdsClient should end up sending out
requests whose resource URL matches the transport version being
used.
* Blank import the v3 client package from xds package. Without this,
attempts to use v3 transport will fail.
> xds: Export a WatchListener() method on the xdsClient.

- security/authorization/engine/engine.go
- security/authorization/util/util.go
- security/authorization/util/util_test.go
This is a fork for #3805.
This PR aims to add a util function to convert a CEL expression string to the complied format(cel.CheckedExpr).
> security/authorization: util function for converting CEL expression string

- xds/internal/balancer/edsbalancer/eds_impl_priority.go
- xds/internal/balancer/edsbalancer/eds_impl_priority_test.go
Without this fix, when the EDS response removes all priorities, after the timeout, the priority check panics because priority is unset.
> eds: fix priority timeout failure when EDS removes all priorities

- xds/internal/balancer/edsbalancer/eds_impl_priority.go
- xds/internal/balancer/edsbalancer/eds_impl_priority_test.go
Without this fix, when the EDS response removes all priorities, after the timeout, the priority check panics because priority is unset.
> eds: fix priority timeout failure when EDS removes all priorities (cherry pick of #3830)

- balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
- balancer/rls/internal/proto/grpc_lookup_v1/rls_grpc.pb.go
- benchmark/grpc_testing/services_grpc.pb.go
- channelz/grpc_channelz_v1/channelz_grpc.pb.go
- cmd/protoc-gen-go-grpc/grpc.go
- credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
- credentials/tls/certprovider/meshca/internal/v1/meshca_grpc.pb.go
- examples/features/proto/echo/echo_grpc.pb.go
- examples/helloworld/helloworld/helloworld_grpc.pb.go
- examples/route_guide/routeguide/route_guide_grpc.pb.go
- health/grpc_health_v1/health_grpc.pb.go
- interop/grpc_testing/test_grpc.pb.go
- profiling/proto/service_grpc.pb.go
- reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
- reflection/grpc_testing/test_grpc.pb.go
- stats/grpc_testing/test_grpc.pb.go
- stress/grpc_testing/metrics_grpc.pb.go
- test/grpc_testing/test_grpc.pb.go
This ensures all service handlers are non-nil when the service is registered, such that they can be called safely (after an interceptor in the case of unary RPCs).
Fixes #3847
> cmd/protoc-gen-go-grpc: call interceptor even if handler is unset

- credentials/alts/utils.go
- credentials/alts/utils_test.go
`expectedServiceAccounts` are commonly mixed-case, while the `PeerServiceAccount` is lowel-case.
The discrepancy can be error-prone, recommendation is to use Unicode case-folding comparison.
Nit: change `status.Newf(...).Err()` to the semantically equal `status.Errorf(...)`.
> credentials/alts: ClientAuthorizationCheck to case-fold compare of peer SA

- credentials/alts/alts_test.go
- credentials/alts/utils_test.go
Anyways, only linux and windows are supported platforms. Running these
tests on darwin causes a top level `make test` to fail, and one has to
scroll all the way up to realize that it is only these alts tests which
have failed, and not something that one is actively working on.
> credentials/alts: Skip ALTS tests on darwin.

- benchmark/worker/benchmark_client.go
- benchmark/worker/benchmark_server.go
Other language client and servers still use the old certs.
> benchmark: Revert to use old certs.

- security/advancedtls/pemfile_provider.go
- security/advancedtls/pemfile_provider_test.go
This is fork of work https://github.com/grpc/grpc-go/pull/3785.
This PR added implementation and unit tests of PemFileProvider. It will fetch identity certificate updates and root certificate updates from the identity PEM file and the root PEM file specified by users via PemFileProviderOptions periodically.
> advancedtls: add PEMFileProvider implementation for on-file-change credential reloading

- Documentation/server-reflection-tutorial.md
The instructions didn't work, as the build process has changed a bit. It's probably best to just link to the official build instructions to avoid future skew.
> Remove grpc_cli build instructions

- credentials/alts/alts_test.go
- credentials/alts/utils_test.go
From the official docs:
```
A build constraint is evaluated as the OR of space-separated options.
Each option evaluates as the AND of its comma-separated terms.
```
> alts: Specify the build constraints correctly.

- xds/internal/resolver/xds_resolver.go
- xds/internal/resolver/xds_resolver_test.go
Also switch the resolver tests to use the leakchecker.
Fixes https://github.com/grpc/grpc-go/issues/3873.
> xds: Exit from run() goroutine when resolver is closed.

- internal/transport/http2_client.go
- internal/transport/http2_server.go
- internal/transport/http_util.go
- internal/transport/http_util_test.go
Handles HTTP2 error code when malformed request/response
header appears.
Fixes: #3819
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3872)
> internal/transport: handle h2 errcode on header decoding

- xds/internal/balancer/edsbalancer/xds_client_wrapper.go
- xds/internal/client/bootstrap/bootstrap.go
- xds/internal/client/bootstrap/bootstrap_test.go
- xds/internal/resolver/xds_resolver.go
- xds/internal/resolver/xds_resolver_test.go
https://github.com/grpc/proposal/pull/204
> xds bootstrap: support insecure and make Creds required

- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/edsbalancer/eds_impl.go
- xds/internal/balancer/edsbalancer/eds_impl_test.go
- xds/internal/balancer/edsbalancer/eds_test.go
- xds/internal/balancer/edsbalancer/xds_client_wrapper.go
The latter seems to be the correct camel case representation.
> xds: Rename xdsclientWrapper type to xdsClientWrapper in EDS.

- binarylog/binarylog_end2end_test.go
- binarylog/sink.go
- internal/binarylog/method_logger.go
- internal/binarylog/method_logger_test.go
- internal/binarylog/sink.go
So the sink can be updated (instead of only being noop)
fixes #3878
> binarylog: export Sink

- xds/internal/balancer/balancergroup/balancergroup.go
- xds/internal/balancer/balancergroup/balancergroup_test.go
- xds/internal/balancer/edsbalancer/eds_impl.go
- xds/internal/balancer/edsbalancer/eds_impl_test.go
- xds/internal/balancer/edsbalancer/xds_client_wrapper.go
- xds/internal/balancer/edsbalancer/xds_client_wrapper_test.go
- xds/internal/balancer/edsbalancer/xds_lrs_test.go
- xds/internal/balancer/lrs/balancer.go
- xds/internal/balancer/lrs/balancer_test.go
- xds/internal/client/client.go
- xds/internal/client/load/reporter.go
- xds/internal/client/load/store.go
- xds/internal/client/load/store_test.go
- xds/internal/client/v2/loadreport.go
- xds/internal/client/v3/loadreport.go
- xds/internal/testutils/fakeclient/client.go
- The original Store is renamed to PerClusterStore. The new Store has a method
to get PerClusterStore.
- All usages of old Store are updated to PerClusterStore
- In EDS and LRS, where the load reporting is happening (by wrapping the
picker), a closure is created with the store and clusterName, serviceName, so
loads will be associated with the right cluster.
- This also means when cluster/service is changed, the closure needs to
update as well.
- TODO: there's no correct timing for this update. The update in this change
is happening too early. The fix would be to do a graceful switch of EDS
when the cluster/service name is changed. That will happen in a later fix.
- When reporting loads (to LRS stream), the lrs client gets the PerClusterStore,
and reports its data.
---
This change is [<img …
> lrs: add a layer for clusters in load store

- xds/internal/testutils/balancer.go
- xds/internal/testutils/wrr.go
Changes include the following:
- Define a `testingLogger` interface instead of directly using `testing.T` here. This make sure that we don't call `t.Error` or `t.Fatal` from here because there could be no guarantee that such a call would actually fail the running test (since we could be on a different goroutine here).
- Get rid of the `TestLoadStore` type. It is not used anymore.
- Move `testWRR` to its own file.
> xds/testutils: Minor cleanup.

- credentials/tls/certprovider/provider.go
- credentials/tls/certprovider/store.go
- internal/internal.go
- xds/internal/client/bootstrap/bootstrap.go
- xds/internal/client/bootstrap/bootstrap_test.go
Changes include:
- Exporting the `GetBuilder` function from `certprovider` package.
- Add a `CertProviderConfigs` field in the `Config` type exported by the `bootstrap` package. This will contain the parsed certprovider configs.
> xds: Add bootstrap support for certificate providers.

- rpc_util.go
- server.go
- stream.go
Currently, the `stats.InPayload.WireLength` actually under-reports the true WireSize of each received message by 5 bytes (`headerLen`), as it does not include the size of the header going over the wire.
However, `stats.OutPayload.WireLength` *does* include the size of the 5 byte header in `WireLength`. 
This leads to the `InPayload.WireLength` not being equal to the `OutPayload.WireLength` for the same underlying payload, which further leads to many weird accounting errors.
> stats: include message header in stats.InPayload.WireLength

- cmd/protoc-gen-go-grpc/main.go
> cmd/protoc-gen-go-grpc: re-add proto3 'optional' support

- attributes/attributes.go
- backoff.go
- balancer/weightedroundrobin/weightedroundrobin.go
- clientconn.go
- credentials/local/local.go
- credentials/tls.go
- dialoptions.go
- encoding/encoding.go
- encoding/gzip/gzip.go
- grpclog/loggerv2.go
- interceptor.go
- internal/grpclog/grpclog.go
- preloader.go
- profiling/profiling.go
- profiling/service/service.go
- resolver/resolver.go
- rpc_util.go
- server.go
- serviceconfig/serviceconfig.go
- tap/tap.go
Signed-off-by: Gaurav Gahlot <gauravgahlot0107@gmail.com>
Fixes: #3605
> cleanup: standardize "experimental" warnings across all packages

- cmd/protoc-gen-go-grpc/main.go
This replaces #3720.  There are two differences:
- Prints to stdout instead of stderr, which is more standard.
- Prints the version of protoc-gen-go-grpc instead of grpc's version, which would be coincidental.
v1.0 will be tagged and released after this PR is merged.
> cmd/protoc-gen-go-grpc: add --version flag support

- xds/internal/client/bootstrap/bootstrap.go
- xds/internal/client/bootstrap/bootstrap_test.go
The expected format for the `certificate_providers` field was wrong:
```
"certificate_providers" : {
"default": { 
"plugin_bar" : {bar plugin config in JSON }
},
"foo": {
"plugin_foo" : { foo plugin config in JSON }
}
}
```
The correct format is:
```
"certificate_providers" : {
"default": {
"plugin_name": "plugin_bar",
"config": { default plugin config in JSON }
},
"foo": {
"plugin_name": "plugin_foo",
"config": { foo plugin config in JSON }
}
}
```
> xds/bootstrap: Use correct format for "certificate_providers" field.

- .github/stale.yml
This will work better with our weekly triage workflow so that issues will be pinged before the following week's meeting.
> stalebot: send first ping after 6 days

- xds/internal/client/client_cds_test.go
- xds/internal/client/client_test.go
- xds/internal/client/client_watchers_cluster_test.go
- xds/internal/client/client_watchers_endpoints_test.go
- xds/internal/client/client_watchers_lds_test.go
- xds/internal/client/client_watchers_rds_test.go
- xds/internal/client/client_watchers_service_test.go
- Cleanup includes the following:
- Split `TestValidateCluster` into failure and success cases. I will adding more cases here as part of other PR which adds support to process security configuration at the `xdsClient`.
- Use a `testutils.Channel` to push the fake API client. This allows tests to block on this with a deadline. This addresses a TODO in the code.
- Add `verify*Update` functions to test successfully received updates. 
- Push the different updates directly on the `xds.Client` object instead of going through the `fakeAPIClient`. This addresses a TODO in the code.
- Rename variables: `c` -> `client`, `v2Client` -> `apiClient`, `v2ClientCh` -> `apiClientCh`
- Use short timeouts when blocking for events which are expected to *not* happen
`go test …
> xds: Refactor/cleanup xds client tests.

- internal/transport/http2_client.go
http2.Framer ErrorDetail() might return nil even in case of http2.StreamError, as documented.
----
(Note: This problem was initially reported to grpc-security@ just in case, but they assessed this segfault isn't a security issue.)
Wrote a gRPC server may send an invalid HEADERS frame to a gRPC client process written with grpc-go. The frame is set length to 0. https://img.sorah.jp/x/20200917_185642_kdwgHWb8KG.png
(a server is written using our original protocol implementation, which is I'm maintaining and sending an invalid HEADERS frame is a different bug. Found during investigation of server process crash)
HTTP/2 session would properly shut down with PROTOCOL_ERROR.
a client process would crash with SEGV (segmentation fault).
```
panic: runtime error: invalid memory address or nil …
```
> http2_client: fix reader segfault on PROTOCOL_ERRORs

- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- Code cleanup:
- Move comments from function top to near the actual code
- Setup a no-op`cancelWatch` so that we don't need nil checks before invoking it
- Tests cleanup:
- Pass `ctx` with deadline to functions which wait for certain events. This way callers control the deadline.
- Add more comments in every test to make them more readable on their own.
- Add more tests for `Close`
- Use a shorter deadline for events which are expected to *not* happen
- With this change:
- Test times reduce by 10x
- Code coverage increases by 5%
> xds: Cleanup CDS balancer code and tests.

- channelz/service/service_test.go
- clientconn.go
- internal/channelz/funcs.go
- internal/channelz/logging.go
- internal/channelz/types.go
- resolver_conn_wrapper.go
This PR is introducing the following minor changes:
- Remove a redundant case from the switch-case that exists in `channelz.AddTraceEvent` - Unknown and Info severities have the same behaviour.
- Rename severities Unknown and Info - change caps to lowercase letters.
> channelz: remove redundant case from AddTraceEvent and remove caps from severities

- xds/internal/balancer/balancergroup/balancergroup_test.go
- xds/internal/balancer/edsbalancer/eds_impl_test.go
- xds/internal/balancer/edsbalancer/xds_client_wrapper.go
- xds/internal/balancer/lrs/balancer.go
- xds/internal/balancer/lrs/balancer_test.go
- xds/internal/client/load/store.go
- xds/internal/client/load/store_test.go
- xds/internal/client/v2/client.go
- xds/internal/client/v2/loadreport.go
- xds/internal/client/v3/client.go
- xds/internal/client/v3/loadreport.go
- unexport `perClusterStore` and it's `stats()`
- add `Store.Stats(clusterNames)` to report loads for the given clusters
- refactor store's map to a two layer map
- move `lastLoadReportAt` from client ton the load store, because a client can now have multiple clusters, each with a different `lastLoadReportAt`
- all tests will ignore `ReportInterval` when comparing Data
> lrs: add Store.Stats() to report loads for multiple clusters

- cmd/protoc-gen-go-grpc/grpc.go
Go Method name might not be the same as the one defined in the protobuf file.
This PR fixes the URL passed to interceptors.
> cmd/protoc-gen-go-grpc: fix method name in interceptor info

- security/advancedtls/advancedtls.go
- security/advancedtls/advancedtls_integration_test.go
- security/advancedtls/advancedtls_test.go
- security/advancedtls/internal/testutils.go
- security/advancedtls/internal/testutils/testutils.go
- security/advancedtls/pemfile_provider_test.go
This PR does two following things:
1. clean up the test files, and make the way to load file credentials consistent across all the tests
2. remove the duplicate dependency of advancedtls. There were some shared code in `credentials/` which can't be used by advancedtls before, so in advancedtls we just duplicated the code. Now the shared part was moved to `internal/credentials/` which can be used by advancedtls, so we removed the previous duplicate code.
> advancedtls: clean up test files and shared code

- encoding/proto/proto.go
Adopt recommendation in #3400 to simplify the proto codec; it seems the buffer pool is no longer buying us any performance wins.
Performance #s:
First run:
```
unary-networkMode_Local-bufConn_false-keepalive_false-benchTime_1m0s-trace_false-latency_0s-kbps_0-MTU_0-maxConcurrentCalls_4-reqSize_1B-respSize_1B-compressor_off-channelz_false-preloader_false
Title       Before        After Percentage
TotalOps      1258048      1246113    -0.95%
Bytes/op      9041.12      9030.22    -0.12%
unary-networkMode_Local-bufConn_false-keepalive_false-benchTime_1m0s-trace_false-latency_0s-kbps_0-MTU_0-maxConcurrentCalls_4-reqSize_1B-respSize_1048576B-compressor_off-channelz_false-preloader_false
Title       Before        After Percentage
TotalOps        79675        78736    -1.18%
Bytes/op   4544492.46 …
```
> encoding/proto: simplify & optimize proto codec

- security/advancedtls/pemfile_provider.go
This is to fix a bug in advancedtls that the credential updates won't get updated immediately when the application starts. Under current implementation, once the user set the polling interval, it will wait that amount of time and then begin the first loading. It will cause problems if the client rpc context duration is shorter than the polling interval.
This PR is to fix this problem.
> advancedtls: Get Instant Updates Before Ticker Runs

- xds/internal/client/client.go
- xds/internal/client/client_rds_test.go
- xds/internal/client/client_watchers.go
- xds/internal/client/client_watchers_rds_test.go
- xds/internal/client/client_watchers_service_test.go
- xds/internal/client/client_xds.go
- xds/internal/client/v2/client.go
- xds/internal/client/v2/client_rds_test.go
- xds/internal/client/v2/client_test.go
- xds/internal/client/v3/client.go
Instead of finding the best matching domain for the service, and return only
that one virtual host's routes.
This removes the lds request name from the xds client, and makes it xds client
handle multiple RDS watches, so one xds client can be shared by multiple
ClientConns.
This also removes some response validation from the client (e.g. if no virtual
host matches what the client is asking for, the response won't be nack'ed).
> xdsClient: change WatchRDS to return all virtual hosts

- security/advancedtls/advancedtls_integration_test.go
This PR adds the end2end tests for advancedtls using Provider interface.
The provider will watches the changes of a bunch of temporary files, and we will change their watching contents by copying the certs under testdata/ to  these temporary files.
> advancedtls: add PemFileProvider integration tests

- balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
- balancer/rls/internal/proto/grpc_lookup_v1/rls_grpc.pb.go
- benchmark/grpc_testing/services_grpc.pb.go
- channelz/grpc_channelz_v1/channelz_grpc.pb.go
- cmd/protoc-gen-go-grpc/grpc.go
- credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
- credentials/tls/certprovider/meshca/internal/v1/meshca_grpc.pb.go
- examples/features/proto/echo/echo_grpc.pb.go
- examples/helloworld/helloworld/helloworld_grpc.pb.go
- examples/route_guide/routeguide/route_guide_grpc.pb.go
- health/grpc_health_v1/health_grpc.pb.go
- interop/grpc_testing/test_grpc.pb.go
- profiling/proto/service_grpc.pb.go
- reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
- reflection/grpc_testing/test_grpc.pb.go
- stats/grpc_testing/test_grpc.pb.go
- stress/grpc_testing/metrics_grpc.pb.go
- test/grpc_testing/test_grpc.pb.go
> cmd/protoc-gen-go-grpc: use grpc.ServiceRegistrar instead of *grpc.Server

- xds/internal/client/client_xds.go
- xds/internal/client/transport_helper.go
- xds/internal/client/v2/client.go
- xds/internal/client/v2/client_ack_test.go
- xds/internal/client/v3/client.go
> xdsclient: populate error details for NACK

- credentials/xds/xds.go
- credentials/xds/xds_test.go
Earlier the behavior was that if no accepted SANs were specified, no connection would go through. But clearly the Envoy docs indicate the behavior should be the other way around.
> credentials/xds: Handle unspecified acceptedSANs correctly.

- .github/workflows/release.yml
This PR adds a GitHub action workflow that is triggered when a tag matching `cmd/protoc-gen-go-grpc/v[0-9]+.[0-9]+.[0-9]+` is pushed.
The workflow creates a draft release for the tag and uploads build artifacts to it as discussed in #3924. The release follows [protobuf-go](https://github.com/protocolbuffers/protobuf-go) conventions for release name assets.
An example for the created draft can be found here: https://github.com/sagikazarmark/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.2.0
(Published, so others can see it)
Fixes #3924
> Add GitHub release action

- interceptor.go
As proposed per https://github.com/grpc/grpc-go/issues/3693, this change removes comments stating that client interceptors API are still experimental.
I added additional commentary on parameters and return values etc. as far as I understand them. Please let me know if we need to rephrase/add/remove those comments.
> Remove experimental comment from client interceptors

- go.sum
- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/edsbalancer/eds_impl_test.go
- xds/internal/balancer/edsbalancer/xds_client_wrapper.go
- xds/internal/balancer/edsbalancer/xds_lrs_test.go
- xds/internal/balancer/lrs/balancer.go
- xds/internal/balancer/lrs/balancer_test.go
- xds/internal/client/client.go
- xds/internal/client/client_loadreport.go
- xds/internal/client/client_loadreport_test.go
- xds/internal/client/client_test.go
- xds/internal/client/transport_helper.go
- xds/internal/client/v2/client.go
- xds/internal/client/v2/loadreport.go
- xds/internal/client/v3/client.go
- xds/internal/client/v3/loadreport.go
- xds/internal/testutils/fakeclient/client.go
- xds/internal/testutils/fakeserver/server.go
- xdsclient.ReportLoad
- create one LRS stream and one load.Store for each server address
- to take just the server address, and return the load.Store
- update EDS and LRS balancing policy to recreate LRS stream only when server address changes
- LRS stream (v2 and v3)
- set feature `send_all_clusters` in `node`
- handle `resp.Clusters` and only send load for those clusters
- handle `resp.SendAllClusters` and send load for all clusters
> lrs: handle multiple clusters in LRS stream

- xds/internal/client/v2/client_ack_test.go
- xds/internal/client/v2/client_rds_test.go
- xds/internal/client/v2/client_test.go
Reduces test run time from ~20s to ~2s.
> xds: Minor cleanup in client/v2 tests.

- Documentation/keepalive.md
> doc: update keepalive.md to add why

- internal/transport/http2_client.go
Most interfaces for adding metadata to a context downcase keys, except metadata.AppendToOutgoingContext (presumably for performance reasons).  Documentation for metadata.AppendToOutgoingContext, referring to that of metadata.Pairs, states that metadata keys are downcased.
The bug is manifest if you use metadata.AppendToOutgoingContext to add metadata with a non-downcased `-Bin` suffix.  http2Client will not encode such metadata, as encodeMetadataHeader just performs a lower suffix check.
> internal/transport: fix a bug causing -bin metadata to be incorrectly encoded

- credentials/tls/certprovider/store.go
- credentials/xds/xds.go
- credentials/xds/xds_test.go
- internal/internal.go
- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/client/client.go
- xds/internal/testutils/balancer.go
- xds/internal/testutils/fakeclient/client.go
- Summary of changes:
- CDS LB changes to act on the security configuration received as part of the `Cluster` resource.
- Export a `CertProviderConfigs` method on the `xds.Client` to return the parsed certificate provider configs.
- Fix the `certprovider.store` to accept configs which have already been parsed. With the change to sourcing the configs from the bootstrap file, the bootstrap processing will parse the config and make it available from the `xds.Client`. So, the CDS balancer will use the parsed configs instead of raw JSON configs.
- Export `getHandshakeInfo` from `credentials/xds` to make it possible to test whether the `HandshakeInfo` type was added as an `Attribute` to the `resolver.Address`. Also export a `CredentialsUsesXDS` function from this package to return if a given …
> xds: CDS balancer security integration.

- xds/internal/client/v2/client_test.go
This check is not expecting a deadline exceeded error, but it's using a short timeout. It should use the long timeout.
> internal: increase timeout non timeout test in xds/client/v2

- xds/internal/balancer/edsbalancer/config.go
- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/edsbalancer/eds_test.go
- xds/internal/balancer/edsbalancer/xds_client_wrapper.go
- xds/internal/balancer/edsbalancer/xds_client_wrapper_test.go
EDS balancer should only get the xdsClient from attributes.
This is part of making xds_client shared by multiple clients.
> xds: remove xdsclient.New from EDS balancer

- examples/features/interceptor/README.md
This is a trivial change fixing a typo in the interceptor example's documentation.
> Fix a typo in interceptor example's README.md

- balancer/grpclb/grpclb_test.go
- balancer_switching_test.go
- benchmark/primitives/context_test.go
- call_test.go
- channelz/service/service_sktopt_test.go
- channelz/service/service_test.go
- credentials/alts/internal/handshaker/handshaker_test.go
- credentials/alts/utils_test.go
- credentials/credentials_test.go
- credentials/local/local_test.go
- credentials/sts/sts_test.go
- health/client_test.go
- internal/transport/keepalive_test.go
- internal/transport/proxy_test.go
- internal/transport/transport_test.go
- metadata/metadata_test.go
- reflection/serverreflection_test.go
- stats/stats_test.go
- test/channelz_test.go
- test/creds_test.go
- test/end2end_test.go
- test/healthcheck_test.go
- test/server_test.go
- test/stream_cleanup_test.go
> testing: Avoid using context.Background

- xds/internal/balancer/xdsrouting/matcher_path.go
- xds/internal/balancer/xdsrouting/matcher_path_test.go
- xds/internal/balancer/xdsrouting/matcher_test.go
- xds/internal/balancer/xdsrouting/routing.go
- xds/internal/balancer/xdsrouting/routing_config.go
- xds/internal/balancer/xdsrouting/routing_picker_test.go
- xds/internal/client/client.go
- xds/internal/client/client_rds_test.go
- xds/internal/client/client_xds.go
- xds/internal/resolver/serviceconfig.go
- xds/internal/resolver/serviceconfig_test.go
- in xds_client, accept (not NACK) RDS resp with case_insensitive=true
- pass case_insensitive to xds resolver and routing balancer
- Note that after the config selector change, the routing balancer will be removed, and
this will be handled in the resolver config selector
> rds: allow case_insensitive path matching

- credentials/tls/certprovider/meshca/builder.go
- credentials/tls/certprovider/meshca/builder_test.go
- credentials/tls/certprovider/meshca/config.go
- credentials/tls/certprovider/meshca/config_test.go
- credentials/tls/certprovider/meshca/plugin.go
- credentials/tls/certprovider/meshca/plugin_test.go
- credentials/tls/certprovider/provider.go
- credentials/tls/certprovider/store.go
- credentials/tls/certprovider/store_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
- xds/internal/client/bootstrap/bootstrap.go
- xds/internal/client/bootstrap/bootstrap_test.go
- xds/internal/client/client.go
- xds/internal/testutils/fakeclient/client.go
We recently decided to move the plugin configuration to be read and parsed from the bootstrap file instead of receiving it from the control plane. This has necessitated a few changes to the API:
- `ParseConfig()` method will return a concrete type, `BuildableConfig`.
- `BuildableConfig` has a `Build()` method which returns instances of `Provider`.
- `certprovider.GetProvider` which contained the store functionality has been removed, and is folded inside the concrete type, `BuildableConfig`.
As part of this PR, the existing MeshCA plugin implementation is also updated to comply with the new API.
> certprovider: API tweaks.

- xds/internal/test/xds_server_integration_test.go
- xds/server.go
- xds/server_test.go
- xds/xds.go
- Contains the initial implementation which defines the server side xDS API.
- Does not contain much xDS specific functionality. This will be added in subsequent PRs.
- Also contains an e2e test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3999)
> xds: Server implementation

- xds/internal/test/xds_server_integration_test.go
- xds/internal/testutils/local_address.go
- xds/server.go
- xds/server_test.go
Changes include the following:
- Remove the `Network` field from `ServeOptions` and hardcode it to `tcp` for now. This was decided in a previous PR.
- Enhance `ServeOptions.validate()` method to do the following:
- accept only literal IPs, not even localhost
- accept only valid port numbers
- Add a function in `xds/testutils` package named `ListenerHostPort` which will return the `IP:Port` as required by the `Serve()` method. This can be swapped out in google3 to work with restrictions there.
- Update the tests to comply with the above changes.
> xds: Minor improvements to xDS server API and test.

- xds/internal/client/bootstrap/bootstrap.go
- xds/internal/client/client.go
- xds/internal/client/client_callback.go
- xds/internal/client/client_loadreport.go
- xds/internal/client/client_loadreport_test.go
- xds/internal/client/client_logging.go
- xds/internal/client/client_singleton.go
- xds/internal/client/client_test.go
- xds/internal/client/client_watchers.go
- xds/internal/client/client_watchers_cluster_test.go
- xds/internal/client/client_watchers_endpoints_test.go
- xds/internal/client/client_watchers_listener_test.go
- xds/internal/client/client_watchers_route_test.go
- xds/internal/client/tests/client_test.go
- xds/internal/client/v2/client.go
- xds/internal/client/v3/client.go
- xds/internal/resolver/xds_resolver.go
- xds/internal/resolver/xds_resolver_test.go
- xds/internal/testutils/fakeserver/server.go
- xds/server.go
- xds/server_test.go
- xdsclient.New() no longer takes any input, all configs are from bootstrap file
- added a NewForTesting()
- The returned *Client is a wrapper of the underlying client implementation, for ref-couting
- xds-resolver and xds-server no longer calls bootstrap.NewConfig. It only calls xdsclient.New()
> xds: make xds client a singleton

- xds/internal/client/bootstrap/bootstrap.go
- xds/internal/client/bootstrap/bootstrap_test.go
See
https://github.com/GoogleCloudPlatform/traffic-director-grpc-bootstrap/pull/6
for more info on this field.
A follow-up PR will update the `xds.GRPCServer` code to read from this field instead of hardcoding to `grpc/server`.
> xds/bootstrap: Add support for `grpc_server_resource_name_id`.

- balancer/grpclb/grpclb.go
- balancer/grpclb/grpclb_test.go
Otherwise, when the first response is received from the grpclb server, the
parent ClientConn enters TransientFailure, and the first several
non-wait-for-ready RPCs will fail.
fixes #4029
> grpclb: consider IDLE SubConns as connecting

- test/authority_test.go
`net.Dial` on some platforms (e.g. IPv6 only) doesn't work well for addresses without the IP.
> internal: fix net.Dial fail without IP

- balancer/grpclb/grpclb_remote_balancer.go
- balancer/grpclb/grpclb_test.go
- balancer/grpclb/grpclb_util.go
- internal/hierarchy/hierarchy.go
- internal/metadata/metadata.go
- internal/metadata/metadata_test.go
- internal/transport/http2_client.go
- test/balancer_test.go
This metadata will be sent with all RPCs on the created SubConn
> balancer: set RPC metadata in address attributes, instead of Metadata field

- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/edsbalancer/eds_test.go
- xds/internal/balancer/edsbalancer/xds_client_wrapper.go
- xds/internal/balancer/edsbalancer/xds_client_wrapper_test.go
- xds/internal/balancer/edsbalancer/xds_lrs_test.go
- xds/internal/balancer/lrs/balancer.go
- xds/internal/balancer/lrs/balancer_test.go
- xds/internal/internal.go
- xds/internal/resolver/xds_resolver.go
- xds/internal/resolver/xds_resolver_test.go
This is done in all xds resolver/balancers.
And each balancer needs to call client.Close on Close(), to refcount--.
> xds: call xdsclient.New instead of getting xds_client from attributes

- Makefile
Remove sections which deal with `deps`. These are not required with the
move to Go modules, and create unnecessary diffs in go.mod and go.sum
files.
Left the rest as is, as some are used from `testing.yaml` and others
serve as a handy reference when one wants to build/test something
specific.
> trim the Makefile

- balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
- balancer/rls/internal/proto/grpc_lookup_v1/rls_grpc.pb.go
- benchmark/grpc_testing/services_grpc.pb.go
- channelz/grpc_channelz_v1/channelz_grpc.pb.go
- cmd/protoc-gen-go-grpc/grpc.go
- credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
- credentials/tls/certprovider/meshca/internal/v1/meshca_grpc.pb.go
- examples/features/proto/echo/echo_grpc.pb.go
- examples/helloworld/helloworld/helloworld_grpc.pb.go
- examples/route_guide/routeguide/route_guide_grpc.pb.go
- health/grpc_health_v1/health_grpc.pb.go
- interop/grpc_testing/test_grpc.pb.go
- profiling/proto/service_grpc.pb.go
- reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
- reflection/grpc_testing/test_grpc.pb.go
- stats/grpc_testing/test_grpc.pb.go
- stress/grpc_testing/metrics_grpc.pb.go
- test/grpc_testing/test_grpc.pb.go
Resolve #3762.
- Exported the `ServiceDesc`, (e.g. FooService_ServiceDesc)
- The `_serviceDesc` is changed to `_ServiceDesc` because grpc.ServiceDesc is public.
- Added the disclaimer about the exported field. The content is mainly copied from the issue.
Thanks.
> protoc-gen-go-grpc: export grpc.ServiceDesc

- xds/server.go
- xds/server_test.go
- Use `grpc/server` if bootstrap does not have this field.
- Also get rid of `newXDSConfig` which is no longer used after the xdsClient singleton changes.
> xds: Read server_resource_name_id from bootstrap config

- attributes/attributes_test.go
- balancer/base/balancer.go
- balancer/base/balancer_test.go
- balancer/roundrobin/roundrobin_test.go
- xds/internal/testutils/balancer.go
`attributes` is stripped from addresses before they are used as map keys.
SubConns are still created with the original addresses (with attributes).
> roundrobin: strip attributes from addresses

- internal/stubserver/stubserver.go
- test/authority_test.go
- test/balancer_test.go
- test/channelz_test.go
- test/context_canceled_test.go
- test/end2end_test.go
- test/goaway_test.go
- test/gracefulstop_test.go
- test/insecure_creds_test.go
- test/local_creds_test.go
- test/resolver_test.go
- test/retry_test.go
- test/server_test.go
- test/stream_cleanup_test.go
I would like to use the stub server in some upcoming xds end-to-end tests, so this moves it to a new package and exports it.
> test: move stubServer to separate package in internal

- xds/internal/balancer/edsbalancer/eds_impl_test.go
- xds/internal/balancer/edsbalancer/load_store_wrapper.go
- xds/internal/balancer/lrs/balancer.go
Checking `nil` before calling the methods. Even though the implementation's receiver checks for nil, the interface `nil` doesn't have the implementation type, and won't call the implementation's receiver.
https://play.golang.org/p/LilYpHAr84j
> eds/lrs: handle nil when LRS is disabled

- xds/internal/client/bootstrap/bootstrap.go
- xds/internal/client/bootstrap/bootstrap_test.go
- xds/internal/testutils/e2e/bootstrap.go
Fixes: https://github.com/grpc/grpc-go/issues/4072
> xds: `server_features` should be a child of `xds_servers` and not a sibling

- xds/internal/client/client.go
- xds/internal/client/client_lds_test.go
- xds/internal/client/client_xds.go
The processing of this field was missed out earlier.
> xds: Process `require_client_cert` field in security config

- internal/syscall/syscall_linux.go
- internal/syscall/syscall_nonlinux.go
Making Rusage a type alias rather than a type definition allows to avoid
type conversions in several places.
Type aliases are supported since Go 1.9, go.mod states Go 1.11 to be the
minimum supported version.
> internal/syscall: make Rusage a type alias

- .github/workflows/testing.yml
- Looks like https://github.com/grpc/grpc-go/pull/4102 did not achieve what it set out to because of a typo. Fixed that `s/test111/tests111`.
- There were two `grep -v ^./security`. Deleted one of them.
- Added an print of the actual tests being run to aid with any debugging in the future.
> github: Get tests111 to actually run subset of tests

- credentials/xds/xds.go
- credentials/xds/xds_client_test.go
- credentials/xds/xds_server_test.go
- go.sum
- `NewServerCredentials()` which returns a `TransportCredentials` implementation for use on the server-side.
- `ServerHandshake()` implementation which does the following:
- Expects the passed in `net.Conn` to implement `XDSHandshakeInfo()`, and if so, gets the certificate providers from the returned `HandshakeInfo`. If not, uses `fallback` credentials.
- Expects the passed in `net.Conn` to implement a `GetDeadline()`, which is used to create the `context` passed to `certprovider.KeyMaterial()`.
The corresponding server-side changes will be sent out in a separate PR since this is big enough and separate enough to be considered on its own.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> credentials/xds: ServerHandshake() implementation

- xds/internal/resolver/xds_resolver.go
- xds/internal/resolver/xds_resolver_test.go
If xds credentials were specified by the user, but bootstrap configs do 
not contain any certificate provider configuration, it is better to fail
the `resolver.Build()` and hence `grpc.Dial() instead of failing when attempting to create certificate
providers after receiving a CDS response with security configuration.
> xds: Expect certprovider bootstrap configs when xdsCreds are in use

- xds/internal/client/client_cds_test.go
- xds/internal/client/client_lds_test.go
- xds/internal/client/client_xds.go
- On the client side, we always expect a root provider.
- On the server side, we always expect an identity provider. If the
`require_client_cert` field is set, a root provider is also expected.
This simplifies the upper layers which can now expect a security config
to be populated correctly, the cds balancer on the client-side and the
xds.GRPCServer on the server-side. And this is what the other languages
are doing as well.
> xds: NACK resource when security config is not as expected

- credentials/tls/certprovider/pemfile/watcher.go
The `run()` method had changed a little over time and it looks like we are calling
`update*Distributor()` once from outside the `for` and then immediately at the top
of the `for` loop.
Even though the `update*Distributor()` methods check if the file contents have changed
before updating the distributor with new key material, the current state is suboptimal.
This seems to be fix: https://github.com/grpc/grpc-go/issues/4048
I don't understand why it fixes it though. I have run the test a few hundred times on GA with this fix
and it never failed. Without this fix though, it would fail around once every hundred times. I have never been
able to repro this locally though.
> pemfile: Update distributor only inside of the for loop

- internal/internal.go
- server.go
- xds/internal/client/client.go
- xds/internal/test/xds_server_integration_test.go
- xds/internal/testutils/e2e/bootstrap.go
- xds/server.go
- xds/server_test.go
- Add security integration to `xds.GRPCServer`:
- Retrieve configured transport credentials from the underlying `grpc.Server`
- Handle security configuration in received `Listener` resource
- create appropriate certificate providers
- setup `HandshakeInfo` to be passed to `xds.Credentials`
- wrap the underlying `net.Conn`
- support for setting and getting deadline
- support for retrieving the `HandshakeInfo`
- e2e test which exercises xDS security with a file watcher plugin.
- A way to retrieve the transport credentials configured on a `grpc.Server` through the `internal` package.
> xds: Implement server-side security

- internal/wrr/random.go
- xds/internal/client/client.go
- xds/internal/client/client_rds_test.go
- xds/internal/client/client_xds.go
- xds/internal/env/env.go
- xds/internal/resolver/serviceconfig.go
- xds/internal/resolver/xds_resolver_test.go
- xds/internal/testutils/wrr.go
This is missing one last piece from A31: reading the HTTP connection manager default max_stream_duration.  I'll add that in a follow-on PR.
> xds: implement RouteAction timeout support

- xds/internal/client/client_rds_test.go
- xds/internal/client/client_xds.go
- unrecognized path specifier
- including Regex (not SafeRegex) from xds v2
- unrecognized header matcher specifier
- empty action weighted clusters
fixes #4093
> xds: NACK more invalid RDS responses

- xds/internal/client/client_lds_test.go
- xds/internal/version/version.go
Fix for Issue #4136 
I am unable to validate the failure running unit tests for `client_lds_tests.go`
> xds client: Updated v3 type for http connection manager

- xds/internal/client/bootstrap/bootstrap.go
- xds/internal/client/bootstrap/bootstrap_test.go
- xds/internal/env/env.go
1. If `GRPC_XDS_BOOTSTRAP` exists then use its value as the name of the bootstrap file. If the file is missing or the contents of the file are malformed, return an error.
1. Else, if `GRPC_XDS_BOOTSTRAP_CONFIG` exists then use its value as the bootstrap config. If the value is malformed, return an error.
fixes #4127
> xds bootstrap: support config content in env variable

- test/authority_test.go
Although darwin supports UDS, these tests need some non-trivial amount
of work to get them to pass on darwin. This build constraint will make a
top-level `go test` happy on darwin.
> test: Run e2e authority tests only on linux.

- credentials/tls/certprovider/pemfile/watcher_test.go
Go1.16 adds a new unexported field to x509.CertPool which causes our
tests to fail because cmp.Equal() isn't happy. This change introduces a
helper function which compares certprovider.KeyMaterial in a way that
makes the test happy with the new Go version.
Fixes https://github.com/grpc/grpc-go/issues/4162
> pemfile: Make test happy with Go1.16

- xds/internal/balancer/edsbalancer/eds_impl.go
- xds/internal/balancer/edsbalancer/eds_impl_test.go
- xds/internal/client/client_requests_counter.go
- xds/internal/client/load/store.go
- xds/internal/client/load/store_test.go
- xds/internal/testutils/protos.go
Those drops will be reported to store with category "".  When reported via LRS,
they will only be counted in total_drops, but not in per category.
fixes #4138
> xds: report drops by circuit breaking

- test/kokoro/xds.cfg
- test/kokoro/xds_v3.cfg
This is the timeout for all the tests, after which the kokoro VM will be killed.
Since now we have more tests, we need more time.
The current average is around 85-90 minutes. The extra 30 minutes should be
enough for several new tests.
> xds testing: increase timeout from 90 minutes to 120 minutes

- xds/internal/balancer/balancergroup/balancergroup.go
- xds/internal/balancer/balancergroup/balancergroup_test.go
- xds/internal/balancer/clustermanager/clustermanager.go
- xds/internal/balancer/clustermanager/clustermanager_test.go
- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/edsbalancer/eds_impl.go
- xds/internal/balancer/edsbalancer/eds_impl_priority_test.go
- xds/internal/balancer/edsbalancer/eds_impl_test.go
- xds/internal/balancer/edsbalancer/eds_test.go
- xds/internal/balancer/weightedtarget/weightedtarget.go
- xds/internal/client/v3/client.go
- xds/internal/testutils/balancer.go
API changes:
- `balancergroup.New()` is modified to take `balancer.BuildOptions` as its second argument.
- This `balancer.BuildOptions` is passed to child policies when they are constructed. 
- Since a single parent balancer uses the `balancergroup`, it is better to take the `balancer.BuildOptions` as part of `New()` instead of as part of `Add()`.
Other changes:
- Update `clustermanager`, `eds` and `weightedtarget` LB policies to pass `balancer.BuildOptions` to the `balancergroup`.
- Add unit tests to make sure the `balancer.BuildOptions` are propagated properly.
- Get rid of `testutils.TestConstBalancerBuilder` and use `stub.Balancer` instead.
Fixes https://github.com/grpc/grpc-go/issues/4185
> balancergroup: Propagate balancer.BuildOptions to child policies

- status/status.go
> status: document nil error handling of FromError

- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/clusterimpl/balancer_test.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/balancer/clusterimpl/picker.go
- xds/internal/balancer/edsbalancer/config.go
- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/edsbalancer/eds_impl.go
- xds/internal/balancer/edsbalancer/eds_impl_test.go
- xds/internal/balancer/edsbalancer/eds_test.go
- xds/internal/client/requests_counter.go
- xds/internal/client/requests_counter_test.go
Also changed circuit breaking counter implementation to move max_count into the
picker, because this is how cluster_impl is designed. Implementation in EDS is
also modified to keep max_count in picker.
> circuit breaking: keep max_count per picker, instead of globally, and add support in cluster_impl balancer

- xds/internal/balancer/edsbalancer/eds_impl.go
- xds/internal/balancer/edsbalancer/eds_impl_test.go
Otherwise, if there's no further picker update, the new counter will never be used.
Regression caused by #4203
This is handled in `cluster_impl`, but missed in `eds`.
> circuit breaking: update picker inline when there's a counter update

- encoding/proto/proto.go
fixes #4213
The type mismatch can happen if
1. user is using a non-proto generated code, so the message is not `proto.Message`
2. the proto codec is picked (e.g. on receiving side, by content-type `application/grpc+subtype`)
> encoding/proto: do not panic when types do not match

- encoding/proto/proto.go
This is a cherry-pick of #4218
> encoding/proto: do not panic when types do not match (#4218)

- xds/internal/client/callback.go
- xds/internal/client/cds_test.go
- xds/internal/client/client.go
- xds/internal/client/client_test.go
- xds/internal/client/dump.go
- xds/internal/client/dump_test.go
- xds/internal/client/eds_test.go
- xds/internal/client/lds_test.go
- xds/internal/client/rds_test.go
- xds/internal/client/v2/ack_test.go
- xds/internal/client/v2/cds_test.go
- xds/internal/client/v2/client.go
- xds/internal/client/v2/client_test.go
- xds/internal/client/v2/eds_test.go
- xds/internal/client/v2/lds_test.go
- xds/internal/client/v2/rds_test.go
- xds/internal/client/v3/client.go
- xds/internal/client/watchers.go
- xds/internal/client/watchers_cluster_test.go
- xds/internal/client/watchers_endpoints_test.go
- xds/internal/client/watchers_listener_test.go
- xds/internal/client/watchers_route_test.go
- xds/internal/client/xds.go
Metadata includs timestamp, status, raw message, error details.
Before, it only keeps parsed resources.
- Change `UnmarshalXXX()` functions (e.g. `UnmarshalListener()` to return metadata)
- Metadata is not populated yet. Will be done in the next PR.
- Change `NewXXX()` functions (e.g. `NewListener()` to handle the metadata)
- Add `Dump()` functions to dump message and metadata
Most of the test changes are boilerplate changes due to the function signature change.
The real tests are in `dump_test.go`
> csds: update client resource cache to keep and dump metadata

- internal/resolver/config_selector.go
- internal/transport/http2_client.go
- internal/transport/transport.go
- stream.go
- xds/internal/client/client.go
- xds/internal/client/lds_test.go
- xds/internal/client/rds_test.go
- xds/internal/client/v2/rds_test.go
- xds/internal/client/watchers_route_test.go
- xds/internal/client/xds.go
- xds/internal/env/env.go
- xds/internal/httpfilter/httpfilter.go
- xds/internal/httpfilter/router/router.go
- xds/internal/resolver/serviceconfig.go
- xds/internal/resolver/watch_service.go
- xds/internal/resolver/watch_service_test.go
- xds/internal/resolver/xds_resolver.go
- xds/internal/resolver/xds_resolver_test.go
This is a fairly large PR, so apologies for that up-front.
I would recommend reviewing in this order:
1. `httpfilter.go` and `config_selector.go` - main interface definitions
2. `xds/internal/client` - parsing/validation of xds data
3. `xds/internal/resolver` - usage of the parsed HTTP filter config
4. leftovers: router plugin (a fancy nop), `stream.go`/`transport` code to signal interceptors when RPC is completed (done with connection; needed for fault injection functionality - coming soon)
> xds: add support for HTTP filters (gRFC A39)

- balancer/balancer.go
- balancer/base/balancer.go
- balancer/grpclb/grpclb_remote_balancer.go
- balancer_conn_wrappers.go
- pickfirst.go
- xds/internal/testutils/balancer.go
This is the first PR for the set of API changes outlined in https://github.com/grpc/grpc-go/issues/4207.
This PR adds the `UpdateAddresses()` method to the `balancer.ClientConn` interface and changes gRPC code to use the new method instead of similarly named method on the `SubConn` interface.
> balancer: Add UpdateAddresses() to balancer.ClientConn interface

- xds/internal/test/xds_client_integration_test.go
- xds/internal/test/xds_server_integration_test.go
- xds/internal/testutils/e2e/clientresources.go
- xds/internal/testutils/e2e/server.go
FWIW, I may refactor & move this `clientSetup` to `testUtils` instead, to allow for easier writing of e2e tests in other packages.  E.g. I want to test fault injection *inside* the fault injection package so I can stub out the randomness and time-based functionality, but I want it to be in an end-to-end style.
> xds: add support for more resources to e2e server

- examples/go.sum
- go.mod
- go.sum
- security/advancedtls/examples/go.sum
- security/advancedtls/go.sum
- xds/internal/client/lds_test.go
- xds/internal/client/rds_test.go
- xds/internal/client/xds.go
This PR contains all of #4206, with the is_optional support as a separate, following commit.
> xds: add HTTP filter is_optional support (gRFC A39)

- xds/internal/client/client_test.go
- xds/internal/client/tests/README.md
- xds/internal/client/tests/dump_test.go
- xds/internal/client/tests/loadreport_test.go
This is required for this week's import.
> xds: Move tests requiring API client to `tests` directory

- xds/internal/client/cds_test.go
- xds/internal/client/client_test.go
- xds/internal/client/eds_test.go
- xds/internal/client/lds_test.go
- xds/internal/client/rds_test.go
- xds/internal/client/v2/cds_test.go
- xds/internal/client/v2/client.go
- xds/internal/client/v2/client_test.go
- xds/internal/client/v2/eds_test.go
- xds/internal/client/v2/lds_test.go
- xds/internal/client/v2/rds_test.go
- xds/internal/client/v3/client.go
- xds/internal/client/xds.go
- xds_client.go
- populate Metadata for the update
- When unmarshalling responses, DON'T stop at the first error. Keep processing
all the resources, so we know which resources are NACKed.
- v2/v3 client.go
- Send the updates to client_callback.go even when response is NACKed. This is
necessary for CSDS's purpose, and also necessary when we later call user's
callback with the NACK errors.
- Test changes
> csds: update xds_client to populate update metadata

- internal/transport/http2_server.go
- internal/transport/http_util.go
- internal/transport/transport_test.go
Fixes issue #2881.
Added check to after HTTP/2 stream logic checks in order for the precedence of error checking to account for HTTP/2 first, as gRPC rests on top of HTTP/2.
> Added check for POST method in http2_server

- xds/internal/client/cds_test.go
- xds/internal/client/xds.go
- xds/internal/env/env.go
We never got around to protecting client-side security configuration parsing with an env var in gRPC-Go. Better late than never.
Addresses https://github.com/grpc/grpc-go/issues/4245
#grpc-psm-security-client-side
> xds: add env var protection for client-side security

- examples/features/interceptor/README.md
Just fixing a typo in the Interceptor README.
> cleanup: fix typo in Interceptor README

- .github/workflows/testing.yml
- vet.sh
Setting PATH to GOPATH caused failures with older go: https://github.com/grpc/grpc-go/runs/2069166312
> vet: set PATH to HOME/go/bin, and print go version

- xds/internal/client/bootstrap/bootstrap.go
- xds/internal/client/bootstrap/bootstrap_test.go
- xds/internal/client/client.go
- xds/internal/client/lds_test.go
- xds/internal/client/xds.go
- xds/internal/test/xds_client_integration_test.go
- xds/internal/test/xds_server_integration_test.go
- xds/internal/testutils/e2e/bootstrap.go
- xds/server.go
- xds/server_test.go
Summary of changes
- Update `bootstrap` package to process `server_listener_resource_name_template`
- Update `client` package to do the following:
- Do not match socket address in `Listener` resource with address from resource `name`
- Populate the `host` and `port` from `sockaddr` in `ListenerUpdate` sent to upper layers
- Update `xdsServer` to do the following:
- Use the `server_listener_resource_name_template` field and replace token (`%s`) if present when generating the `Listener` resource name
- Make sure the `host:port` received in the `ListenerUpdate` matches the actual listening address
- Update e2e tests
> xds: Support server_listener_resource_name_template 

- encoding/proto/proto.go
- vet.sh
- xds/internal/client/client_cds_test.go
- xds/internal/client/client_xds.go
- xds/internal/env/env.go
This is a cherry pick of 
- encoding/proto: do not panic when types do not match (#4218)
- xds: add env var protection for client-side security (#4247)
> cherry-pick commits to 1.34.x

- encoding/proto/proto.go
- vet.sh
- xds/internal/client/client_cds_test.go
- xds/internal/client/client_xds.go
- xds/internal/env/env.go
This is a cherry pick of 
- encoding/proto: do not panic when types do not match (#4218)
- xds: add env var protection for client-side security (#4247)
> cherry-pick commits to 1.35.x

- xds/internal/httpfilter/fault/fault_test.go
This test is flaky on GOARCH=386; disabling for now to remove flakiness, and I will investigate further.
> xds: disable fault injection test on 386

- credentials/xds/xds_client_test.go
- internal/credentials/xds/handshake_info.go
- internal/credentials/xds/handshake_info_test.go
- internal/xds/string_matcher.go
- internal/xds/string_matcher_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
- xds/internal/client/cds_test.go
- xds/internal/client/client.go
- xds/internal/client/xds.go
We had initially decided only to support `exact` matches on SANs. But now, we have decided to support all matchers.
The list of matchers is specified in the [match_subject_alt_names](https://github.com/envoyproxy/envoy/blob/d17b0e5/api/envoy/api/v2/auth/common.proto#L306) field. And the `StringMatcher` proto is defined [here](https://github.com/envoyproxy/envoy/blob/main/api/envoy/type/matcher/v3/string.proto#L20)
Fixes https://github.com/grpc/grpc-go/issues/4232
#grpc-psm-security-client-side
> xds: support all matchers for SANs

- xds/internal/balancer/cdsbalancer/cdsbalancer.go
Otherwise client may be used by run() after closed.
> xds/cdsbalancer: move xds client close to run()

- xds/server.go
- xds/server_test.go
`strings.ReplaceAll` is only available after go 1.12. We still support go 1.11.
> internal: use strings.Replace instead strings.ReplaceAll

- interop/client/client.go
This is needed to allow the interop client to be used with Traffic Director load balancing
The behavior of allowing a server_port of zero to mean "no port" was added to the C++ interop client in https://github.com/grpc/grpc/pull/25550 and to the Java interop client in https://github.com/grpc/grpc-java/pull/7994
> Allow using interop client for making Traffic Director RPCs

- interop/client/client.go
This is a go analogue of https://github.com/grpc/grpc-java/pull/7957 - https://github.com/grpc/grpc-java/pull/7957#issue-590133307 for more context
> interop: add a flag to clients to statically configure grpclb

- xds/internal/client/client.go
- xds/internal/client/lds_test.go
- xds/internal/client/xds.go
- xds/internal/resolver/watch_service.go
- xds/internal/resolver/watch_service_test.go
> xds/resolver: support inline RDS resource from LDS response

- xds/internal/client/client.go
- xds/internal/client/filter_chain.go
- xds/internal/client/filter_chain_test.go
- xds/internal/client/lds_test.go
- xds/internal/client/xds.go
- xds/internal/server/conn_wrapper.go
- xds/internal/server/listener_wrapper.go
- xds/internal/server/listener_wrapper_test.go
- xds/internal/test/xds_server_integration_test.go
- xds/server_test.go
`xds/internal/client` changes
- Implement a `FilterChainManager` type which provides functionality to parse filter chains from incoming `Listener` resources, and lookup matching filter chains at connection time.
- `ListenerUpdate` will no longer carry the filter chain match criteria. It will carry the above `FilterChainManager` whose `Lookup()` method will be used at connection time to match filter chains.
- Logic to identify filter chains which contain overlapping match criteria and NACK such resources.
`xds/internal/server` changes:
- Check whether the address specified in a `ListenerUpdate` matches the one to which the underlying `net.Listener` is bound to.
- Teach `Accept()` to handle certain classes of errors, and drop connections on filter chain match failures.
- …
> xds: filter chain matching logic for server-side

- xds/internal/balancer/balancergroup/balancergroup.go
- xds/internal/balancer/balancergroup/balancergroup_test.go
Child policies in balancergroup are put into a cache when they are removed (and will be closed later after a timeout).
When balancergroup is closed, we clear the cache, so that child policies will be immediately closed.
Before this change, we first mark balancergroup as closed (`bg.outgoingStarted = false`), then clear the cache (`bg.balancerCache.Clear(true)`). This makes the cache clear a noop, so the child in cache will be leaked.
This change moves `cache.Clear` before marking balancergroup as closed.
> balancergroup: fix leak child balancer not closed

- xds/internal/resolver/watch_service.go
- xds/internal/resolver/xds_resolver_test.go
Also confirmed that the LDS updates shouldn't trigger state update without the
RDS.
> xds/resolver: fix panic when two LDS updates are receives without RDS in between

- examples/features/xds/client/main.go
- examples/features/xds/server/main.go
- Use explicit flags instead of positional arguments
- Add support for xDS credentials
- Use xDS server API on the server-side
- Remove reflection service on the server-side (we need to fix the reflection service implementation to work with `xds.GRPCServer`).
> examples: update xds examples for PSM security

- xds/internal/balancer/weightedtarget/weightedtarget.go
- xds/internal/balancer/weightedtarget/weightedtarget_config_test.go
- xds/internal/balancer/weightedtarget/weightedtarget_test.go
Also remove dependency on cds from the tests, otherwise later it will cause cycular dependency: weightedtarget -> cds -> eds -> weightedtarget
> weightedtarget: handle updating child policy name

- internal/testutils/marshal_any.go
- xds/internal/client/filter_chain_test.go
- xds/internal/client/lds_test.go
- xds/internal/client/xds.go
- xds/internal/httpfilter/httpfilter.go
- xds/internal/httpfilter/router/router.go
- xds/internal/test/xds_server_integration_test.go
- xds/internal/testutils/marshal_any.go
- Main filter validation change is in the `validateNetworkFilterChains()` function in `xds/internal/client/xds.go`
- it uses the `processHTTPFilters()` which validates `http_filters` on the client-side
- server-side placeholder support for the `Router` filter
- reduce test bloat
#psm-security-server-side-filter-support
> xds: server-side listener network filter validation

- credentials/google/google.go
- credentials/google/google_test.go
- credentials/google/xds.go
- internal/credentials/xds/handshake_cluster.go
- xds/internal/balancer/clusterimpl/balancer_test.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/edsbalancer/eds_impl.go
- xds/internal/balancer/edsbalancer/eds_impl_test.go
- xds/internal/balancer/edsbalancer/eds_test.go
- set cluster name in address's attributes
- done in both EDS and cluster_impl
- update google creds to read cluster name
- in default mode, handshake will be either TLS or ALTS based on the cluster name
- other modes are not affected
> xds/google_default_creds: handshake based on cluster name in address attributes

- clientconn.go
- internal/transport/http2_client.go
- internal/transport/keepalive_test.go
- internal/transport/transport.go
- internal/transport/transport_test.go
- test/end2end_test.go
Motivated mainly to debug internal issue: b/182572215
This PR is a replacement for a subset of the behavior added in https://github.com/grpc/grpc-go/pull/4190. In particular, note that this follows the first idea described in the design in https://github.com/grpc/grpc-go/issues/4163#issuecomment-763784410 about passing connection close errors to the transport's `Close` method. However, this PR doesn't try to propagate errors up further to the LB policy or ClientConn. My thinking is that the error propagation added here (for RPCs that have picked connections) is still useful on its own, and we can save further plumbing for followup changes, but please let me know.
> client: propagate connection error causes to RPC statuses

- go.sum
- xds/internal/client/filter_chain.go
- xds/internal/client/filter_chain_test.go
- xds/internal/client/lds_test.go
- xds/internal/test/xds_server_integration_test.go
- Differentiate between unspecified and wildcard prefixes.
- unspecified prefixes match both v4 and v6 addresses, while wildcard prefixes are network specific
- unspecified prefix match is considered less specific than a wildcard prefix match
- Test for v4 and v6 wildcards
In a follow-up PR, I will change `testutils.LocalListener()` to accept a network type, and change the tests to run for both v4 and v6, and skip tests in unsupported environments.
> xds: support unspecified and wildcard filter chain prefixes

- xds/internal/balancer/clusterimpl/balancer_test.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/testutils/balancer.go
This will be triggered for both DNS and EDS children, and the parent priority policy will choose to ignore re-resolution from EDS children. Related to #4275
> xds/clusterimpl: trigger re-resolution on subconn transient_failure

- xds/internal/balancer/clusterimpl/balancer_test.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/balancer/clusterimpl/config.go
- xds/internal/balancer/clusterimpl/config_test.go
- xds/internal/balancer/clusterimpl/picker.go
- xds/internal/balancer/edsbalancer/eds_test.go
- xds/internal/balancer/lrs/balancer.go
- xds/internal/balancer/lrs/balancer_test.go
- xds/internal/balancer/lrs/config.go
- xds/internal/balancer/lrs/config_test.go
- xds/internal/balancer/priority/balancer.go
- xds/internal/balancer/priority/balancer_test.go
- xds/internal/balancer/priority/config.go
- xds/internal/balancer/priority/config_test.go
- xds/internal/balancer/weightedtarget/weightedtarget.go
- xds/internal/balancer/weightedtarget/weightedtarget_config.go
- xds/internal/balancer/weightedtarget/weightedtarget_config_test.go
- xds/internal/balancer/weightedtarget/weightedtarget_test.go
This PR exports `Name` and `LBConfig` from the balancers that will be used as children by `cluster_impl`. The configs are also made json-ready.
> xds/balancers: export balancer names and config structs

- .github/workflows/testing.yml
Part of go/grpc-on-arm effort.
- add arm64 target to github actions
- use https://github.com/multiarch/qemu-user-static to register the emulator with binfmt_misc
> Run emulated linux arm64 tests

- balancer_conn_wrappers.go
- clientconn.go
This happens when `UpdateAddress()` is called with a different set of addresses. The underlying TCP connection is closed, but the `addrConn` struct will leak.
The leaked memory can increase rapidly if `UpdateAddress()` is called frequently, this usually doesn't happen with `DNS + pick_first`, but can happen with `grpclb`.
> client: fix leaked addrConn struct when addresses are updated

- internal/credentials/xds/handshake_info.go
While testing intetop between Java and Go when using xDS credentials, I was seeing that the protocol negotiation was failing because Go was not sending "h2". Adding this makes things work across Java and Go.
#psm-security-interop-bugs
> xds: specify "h2" as the alpn in xds creds

- xds/internal/balancer/lrs/balancer.go
- xds/internal/balancer/lrs/config.go
- xds/internal/balancer/lrs/config_test.go
It's valid for `LoadReportingServerName` to be an empty string in LRS's balancer config. It means the loads will be sent to the xDS server.
If LRS is disabled, the parent balancer will not include lrs as a child policy (it will use e.g. round_robin directly, instead of LRS and then round_robin).
> xds/lrs: server name is not required to be non-empty

- reflection/serverreflection.go
Recently-ish (~6 months ago) a new `grpc.ServiceRegistrar` interface was added, which allows generated code to interact with service registries other than the concrete `*grpc.Server`. Awesome!
But now I need to use the reflection service with something other than a concrete `*grpc.Server`. So this PR enables it. You can provide a different type of registrar but must also provide an accessor for the actual services exposed, so it can compute the reflection info/descriptors.
Hopefully this is a non-controversial addition. Without this, I'm having to resort to reflection+unsafe, to access unexported fields in the `*grpc.Server`, to dig out a reflection server impl registered in there 🤮.
> reflection: accept interface instead of grpc.Server struct in Register()

- xds/internal/balancer/priority/balancer.go
- xds/internal/balancer/priority/balancer_child.go
- xds/internal/balancer/priority/balancer_test.go
- xds/internal/balancer/priority/config.go
- xds/internal/balancer/priority/config_test.go
- xds/internal/balancer/priority/ignore_resolve_now.go
- xds/internal/balancer/priority/ignore_resolve_now_test.go
`ResolveNow()` from children with `ignore reresolution` set to true will all be ignored.
Priority will be used with Children EDS and DNS, where DNS is a lower priority fallback. When higher priority EDS is disconnected, DNS will be used.
But EDS will keep retrying, causing SubConn reconnections, and will trigger re-resolutions. We don't want DNS to re-resolve for those, so we want to ignore re-resolution requests from the EDS child.
> xds/priority: add ignore reresolution boolean to config

- metadata/metadata.go
When Looking at memory profiles for cockroachdb/cockroach, we observed
that the intermediate metadata.MD array constructed to iterate over
appended metadata escaped to the heap. Fortunately, this is easily
rectifiable.
```
go build -gcflags '-m' google.golang.org/grpc/metadata
...
google.golang.org/grpc/metadata/metadata.go:198:13: make([]MD, 0, len(raw.added) + 1) escapes to heap
```
> metadata: reduce memory footprint in FromOutgoingContext

- internal/serviceconfig/serviceconfig.go
- internal/serviceconfig/serviceconfig_test.go
For balancer config with `{name: "abc", config: ...}`, the marshal result will be `[{"abc": ...}]`.
The result is a slice (`[]map[string]config`) of length 1.
The result can be unmarshalled back to a BalancerConfig (by the already defined `UnmarshalJSON()`).
> serviceconfig: support marshalling BalancerConfig to JSON

- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/edsbalancer/eds_test.go
This is a regression caused by #4352, caught by integration tests.
This will fix the failed tests, but still isn't the right behavior.
I will make another PR to fix:
The counter should use both ClusterName and EDSServiceName as key.
So instead of `map[ClusterName]counter` (the current behavior),
it should be `map[{ClusterName, EDSServiceName}]counter`.
> xds/circuit_breaking: use cluster name as key, not EDS service name

- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/edsbalancer/eds_test.go
This is a regression caused by #4352.
The real change is
```diff
- x.edsServiceName = ""
+ x.edsToWatch = ""
```
Setting a wrong value caused the EDS to not restart watch after the previous one was canceled.
> xds/eds: restart EDS watch after previous was canceled

- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/edsbalancer/config.go
- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/edsbalancer/eds_impl_test.go
- xds/internal/balancer/edsbalancer/eds_test.go
- xds/internal/balancer/edsbalancer/load_store_wrapper.go
- xds/internal/client/cds_test.go
- xds/internal/client/client.go
- xds/internal/client/client_test.go
- xds/internal/client/v2/cds_test.go
- xds/internal/client/watchers_cluster_test.go
- xds/internal/client/xds.go
This reverts PRs #4352 (and two follow up fixes #4372 #4378).
Because the xds interop tests were flaky.
Revert before the branch cut.
> Revert "xds/cds: add separate fields for cluster name and eds service name"

- test/kokoro/xds.cfg
- test/kokoro/xds_v3.cfg
Related https://github.com/grpc/grpc/pull/26090
With config update timeout pushed to 600s, we might need longer Kokoro build timeout as well.
> test: extend the xDS interop tests timeout to 360 mins

- rpc_util.go
- server.go
- test/end2end_test.go
Fixes https://github.com/grpc/grpc-go/issues/3694.
> server: add ForceServerCodec() to set a custom encoding.Codec on the server

- balancer_conn_wrappers.go
Reverts grpc/grpc-go#4364
The reverted PR moved `balancer.Close()` to `balancer_wrapper.close()`, which can cause a deadlock if `balancer.Close()` also `RemoveSubConn()`.
The failure was caught by xds interop tests, when the `xds_resolver` sends an empty service config, causing switching balancer (from `cluster_manager` to `pick_first`):
```go
cc_resolver_wrapper.UpdateState()
cc.updateResolverState()
cc.mu.Lock() // this hold cc.mu
cc.applyServiceConfigAndBalancer()
cc.switchBalancer() // this is to switch to pick_first
cc.balancerWrapper.close() // this is to close cluster_manager
ccb.balancerMu.Lock() // _this is not important_
clusterManager.Close()
balancergroup.Close()
bg.incomingMu.Lock() // _this is not important_
bg.cc.RemoveSubConn()
ccBalancerWrapper.RemoveSubConn()
ccb.mu.Lock …
```
> Revert "grpc: call balancer.Close() before returning from ccBalancerWrapper.close()"

- stream.go
> grpc: improve docs on StreamDesc

- internal/transport/controlbuf.go
- internal/transport/http2_server.go
- server.go
- tap/tap.go
- test/end2end_test.go
> transport: allow InTapHandle to return status errors

- clientconn.go
Fixes #4343 
I have identified a race that can happen during initialization time:
1. ClientConn created
2. Stream is created
3. Resolver calls into the ClientConn
4. During a small window of time here, if the ClientConn is closed, no config selector will be applied due to https://github.com/grpc/grpc-go/blob/c7ea734087dbbcdb22137ab3b7d8b16842b080bf/clientconn.go#L607-L616
This will perform the `defer cc.firstResolveEvent.Fire()` a few lines up.
5. The stream from step 2 is blocked at https://github.com/grpc/grpc-go/blob/c7ea734087dbbcdb22137ab3b7d8b16842b080bf/stream.go#L171
6. If the `firstResolveEvent` case of https://github.com/grpc/grpc-go/blob/c7ea734087dbbcdb22137ab3b7d8b16842b080bf/clientconn.go#L575-L582
wins over the `cc.ctx.Done()` case, `nil` will be returned and …
> client: initialize safe config selector when creating ClientConn

- xds/internal/client/client.go
- xds/internal/client/rds_test.go
- xds/internal/client/xds.go
- xds/internal/resolver/matcher.go
Fixes: https://github.com/grpc/grpc-go/issues/4240
#fixit
> xds: nack route configuration with regexes that don't compile

- rpc_util.go
- stream.go
- test/end2end_test.go
> client: fix ForceCodec to set content-type header appropriately

- internal/transport/keepalive_test.go
Server should allow `NoStream`, otherwise there's a small chance (5/1000) the connection will be closed due to `too many pings`.
fixes #4424
> internal: fix flaky test KeepaliveClientStaysHealthyWithResponsiveServer

- credentials/xds/xds_client_test.go
- internal/credentials/xds/handshake_info.go
- internal/credentials/xds/handshake_info_test.go
- internal/xds/bootstrap.go
- internal/xds/matcher/matcher_header.go
- internal/xds/matcher/matcher_header_test.go
- internal/xds/matcher/string_matcher.go
- internal/xds/matcher/string_matcher_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
- xds/internal/client/cds_test.go
- xds/internal/client/client.go
- xds/internal/client/xds.go
- xds/internal/resolver/matcher.go
- xds/internal/resolver/matcher_test.go
This PR moves the header matcher previously present in xds_resolver to internal/xds/matchers. It also moves the string matcher previously present as a file in internal/xds to this new package internal/xds/matchers.
> xds: moved shared matchers to internal/xds

- examples/features/encryption/README.md
- examples/route_guide/client/client.go
Fixes: #4396
The SAN of the test certificate is changed from `*.test.youtube.com` to `*.test.example.com` in #3786, most of the parts are updated accordingly, but a few places are omitted.
> example: correct the default value for server_host_override

- internal/xds/env/env.go
- xds/internal/client/cds_test.go
- xds/internal/client/xds.go
Add an env var "GRPC_XDS_EXPERIMENTAL_ENABLE_AGGREGATE_AND_LOGICAL_DNS_CLUSTER"
> xds/cds: add env var for aggregated and DNS cluster

- xds/internal/test/xds_server_serving_mode_test.go
- xds/internal/testutils/e2e/server.go
- Using depth logging will ensure that the actual file generating the log line will be printed instead of simply `server.go`.
- Couple of other minor cleanups.
Addresses https://github.com/grpc/grpc-go/issues/4403.
> use depth logging from the e2e package

- internal/xds/env/env.go
- interop/xds/client/Dockerfile
- interop/xds/server/Dockerfile
- interop/xds/server/server.go
- rpc_util.go
- test/end2end_test.go
- xds/internal/client/cds_test.go
- xds/internal/client/xds.go
- xds/internal/testutils/e2e/clientresources.go
* interop/xds: support xds security on interop server (#4444)
* interop/xds: dockerfile for the xds interop client (#4443)
* xds/cds: add env var for aggregated and DNS cluster (#4440)
* xds: use same format while registering and watching resources (#4422)
* client: fix ForceCodec to set content-type header appropriately (#4401)
> v1.38.x: backport

- xds/internal/balancer/clusterimpl/balancer_test.go
- xds/internal/balancer/clusterimpl/picker.go
- xds/internal/balancer/priority/balancer_priority.go
- xds/internal/balancer/priority/balancer_test.go
- xds/internal/balancer/weightedtarget/weightedtarget.go
The exported variables will be used by tests (to be added in a future
PR, in another package) that use these balancers as child balancer.
> xds/testing: export variables for testing

- xds/internal/client/cds_test.go
- xds/internal/client/client.go
- xds/internal/client/xds.go
The dns host name to be resolved is encoded in the CDS response's load assignments.
This change adds a field in CDS update for it.
https://github.com/grpc/proposal/pull/236
https://github.com/grpc/grpc/pull/26147
> xds/cds: fix LOGICAL_DNS cluster semantics

- xds/internal/client/cds_test.go
Found when backporting to v1.38.x
> internal: fix test unset env var AggregateAndDNSSupportEnv

- internal/transport/controlbuf.go
- internal/transport/handler_server.go
- internal/transport/http2_client.go
- internal/transport/http2_server.go
- internal/transport/transport.go
I cleaned up a few minor things I noticed along the way that should all be nops from #4447:
- remove the return value from `http2Server.Close()` as it was unused (and unreliable if it had been)
- remove `http2Server.drain()` as it was unnecessary
- re-type the throttle channel so it's not a pointer to a chan (which is already a pointer)
- unconditionally close the conn when `loopyWriter.run()` exits in the client (there is no harm in doing it if a conn error was encountered and the server already did this)
> transport: various simplifications noticed during #4447

- internal/transport/controlbuf.go
- internal/transport/http2_client.go
- internal/transport/http2_server.go
- test/end2end_test.go
If the transport reader is blocked due to throttling caused by a backlog of pending transport response frames, it is possible it could never unblock in the event the `loopyWriter` encounters an error and exits.  This PR fixes that race and adds a test.
Also, now that we are calling `finish` when `run` returns, we don't need to call `finish()` in `get` in one random specific case.
> transport: unblock read throttling when controlbuf exits

- xds/internal/client/rds_test.go
- xds/internal/client/xds.go
Signed-off-by: alpha-baby <fujianhao1997@qq.com>
fixes #4432
> xds_client/rds: weighted_cluster totalWeight default to 100

- balancer_conn_wrappers.go
- clientconn.go
This is a slightly different approach to #4364.
> client: ensure LB policy is closed before closing resolver

- server.go
- test/end2end_test.go
Using `PreparedMsg` in `ServerStream` to fix #3489.
> server: allow PreparedMsgs to work for server streams

- internal/transport/handler_server_test.go
`serverHandlerTransport` uses the parsed request line from the URL field
of the request. This is exactly what is recommended in the comments in
the `http` package.
> transport: remove RequestURI field from requests in transport test

- server.go
- test/end2end_test.go
Fixes https://github.com/grpc/grpc-go/issues/4456.
> server: return UNIMPLEMENTED on receipt of malformed method name

- test/kokoro/xds_k8s.cfg
- test/kokoro/xds_k8s.sh
- test/kokoro/xds_k8s_install_test_driver.sh
The build scripts are a copy of the ones present in other grpc repos. The only function which has any meaningful change is `build_test_app_docker_images`.
> Kokoro build configs for PSM security interop tests

- .github/mergeable.yml
Tested using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/multiline demo w/input:
```
const regex = new RegExp('^RELEASE NOTES:\\s*([Nn][Oo][Nn][Ee]|[Nn]/[Aa]|\n\\*\\s*.+)$', 'm');
console.log(regex.test('fixes #4400\nRELEASE NOTES:\n* admin: skip CSDS if xDS bootstrap config isn\'t set'));
console.log(regex.test('RELEASE NOTES: none'));
console.log(regex.test('RELEASE NOTES:  n/a'));
console.log(regex.test('RELEASE NOTES: nope'));
console.log(regex.test('here are the RELEASE NOTES: none'));
console.log(regex.test('here are the RELEASE NOTES:\n* stuff'));
console.log(regex.test('also bad\nRELEASE NOTES:'));
```
```
> true
> true
> true
> false
> false
> false
> false
```
> mergeable: update relnotes regex

- examples/helloworld/greeter_server/main.go
Same as the other examples in `examples/features`, it is preferable to display the server starting message. When I ran the hello world server, I got the impression that the server was stuck on network connection or initialization.
RELEASE NOTES:
* examples: print message when hello world server starts
> example: improve hello world server with starting msg

- rpc_util.go
The WaitForReady option documentation was not clear to me, until I
read the linked documentation [1]. Include the channel state names
that cause an RPC to fail immediately to attempt to clarify how this
works.
[1] https://github.com/grpc/grpc/blob/master/doc/wait-for-ready.md
Feel free to reject this: I just found this confusing, and had to read it multiple times. I'm attempting to clarify it so others don't make the same mistake I did. Thanks!
RELEASE NOTES:
* client: Clarify that WaitForReady will block for CONNECTING channels
> client: Clarify that WaitForReady will block for CONNECTING channels

- internal/xds/bootstrap.go
- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/lrs/balancer.go
- xds/internal/client/attributes.go
- xds/internal/client/bootstrap/bootstrap.go
- xds/internal/client/singleton.go
- xds/internal/resolver/xds_resolver.go
- xds/internal/test/xds_client_integration_test.go
- xds/internal/test/xds_integration_test.go
- xds/internal/test/xds_server_integration_test.go
- xds/internal/test/xds_server_serving_mode_test.go
- xds/server.go
- xds/server_options.go
- xds/xds.go
Fixes #4124
RELEASE NOTES:
* xds: add `NewXDSResolverWithConfigForTesting` and `BootstrapContentsForTesting` to inject xds config
> xds: add test-only injection of xds config to client and server

- call_test.go
- internal/transport/http2_server.go
- internal/transport/transport.go
- internal/transport/transport_test.go
- server.go
Fixes https://github.com/grpc/grpc-go/issues/4234.
> internal/transport: skip log on EOF when reading client preface

- balancer_conn_wrappers.go
- balancer_switching_test.go
Deadlock can happen when switching balancer, and if the old balancer calls `RemoveSubConn()` in its `Close()`.
For example, found in xds interop test:
- cc_resolver_wrapper.UpdateState()
- cc.updateResolverState()
- cc.mu.Lock() **this hold cc.mu**
- cc.applyServiceConfigAndBalancer()
- cc.switchBalancer() this is to switch to pick_first
- cc.balancerWrapper.close() this is to close the cluster_manager
- ccb.balancerMu.Lock() _this is not important_
- clusterManager.Close()
- balancergroup.Close()
- bg.incomingMu.Lock() _this is not important_
- bg.cc.RemoveSubConn()
- ccBalancerWrapper.RemoveSubConn()
- ccb.mu.Lock _this is not important_
- ccb.cc.removeAddrConn()
- cc.mu.Lock() **this is trying to take cc.mu again, causing a deadlock**
Related: #4478
> client: handle RemoveSubConn in goroutine to avoid deadlock

- xds/csds/csds.go
- xds/csds/csds_test.go
fixes #4400
RELEASE NOTES:
- make CSDS service return an empty response when xDS client is not set, instead of failing at initialization
> csds: return empty response if xds client is not set

- metadata/metadata.go
fixes #4323
It's easier to use if all keys in the returned MD from `FromXXXContext()` are lowercase.
The only way to ensure it is to explicitly convert.
Even for the extreme case `FromIncomingContext()`, it's not guaranteed that keys in the returned MD are lowercase.
- all keys received from the wire are guaranteed to be lower case, that's the HTTP/2 spec.
- but, interceptors can append kv to the metadata, and there's no guarantee of these
RELEASE NOTES:
- metadata: ensure metadata keys returned from FromContext() are all lowercase
> metadata: convert keys to lowercase in FromContext()

- internal/xds/matcher/matcher_header.go
- internal/xds/matcher/matcher_header_test.go
- internal/xds/rbac/matchers.go
- xds/csds/csds.go
- xds/csds/csds_test.go
- xds/googledirectpath/googlec2p.go
- xds/googledirectpath/googlec2p_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/cdsbalancer/cluster_handler.go
- xds/internal/balancer/clusterimpl/balancer_test.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/edsbalancer/eds_impl_test.go
- xds/internal/balancer/edsbalancer/eds_test.go
- xds/internal/balancer/edsbalancer/xds_lrs_test.go
- xds/internal/balancer/lrs/balancer.go
- xds/internal/balancer/lrs/balancer_test.go
- xds/internal/resolver/matcher.go
- xds/internal/resolver/matcher_path.go
- xds/internal/resolver/matcher_test.go
- xds/internal/resolver/watch_service.go
- xds/internal/resolver/xds_resolver.go
- xds/internal/resolver/xds_resolver_test.go
- xds/internal/server/conn_wrapper.go
- xds/internal/server/listener_wrapper.go
- xds/internal/server/listener_wrapper_test.go
- xds/server.go
- xds/server_test.go
Types aren't supposed to be named by their types, generally.  From #4479.
Should I revert `xds/internal/balancer/eds/**` to avoid conflicting with your other PR?
> cleanup: remove "Interface" as suffix of (almost all) interface names

- xds/internal/resolver/xds_resolver_test.go
- xds/internal/testutils/fakeclient/client.go
Includes #4479 which noticed this missing test case.
> xds/resolver: test xds client closed by resolver Close

- internal/grpcrand/grpcrand.go
- xds/googledirectpath/googlec2p.go
- xds/googledirectpath/googlec2p_test.go
See https://github.com/grpc/grpc/pull/26433 and internal bug http://b/183237952
> c2p: add random number to xDS node ID in google-c2p resolver

- xds/csds/csds.go
- xds/csds/csds_test.go
- xds/googledirectpath/googlec2p.go
- xds/googledirectpath/googlec2p_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/cdsbalancer/cluster_handler.go
- xds/internal/balancer/clusterimpl/balancer_test.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/balancer/edsbalancer/eds.go
- xds/internal/balancer/edsbalancer/eds_test.go
- xds/internal/balancer/edsbalancer/xds_lrs_test.go
- xds/internal/balancer/lrs/balancer.go
- xds/internal/balancer/lrs/balancer_test.go
- xds/internal/resolver/watch_service.go
- xds/internal/resolver/xds_resolver.go
- xds/internal/resolver/xds_resolver_test.go
- xds/internal/testutils/fakeclient/client.go
- xds/internal/xdsclient/attributes.go
- xds/internal/xdsclient/client.go
- xds/internal/xdsclient/client_test.go
- xds/internal/xdsclient/singleton.go
- xds/internal/xdsclient/tests/dump_test.go
- xds/server.go
- xds/server_test.go
- xdsclient.New returns the interface now
- xdsclient.SetClient and xdsclient.FromResolverState take and return the interface now
- cleanup xds balancer tests to pass xds_client in resolver state
> xds: export XDSClient interface and use it in balancer tests

- vet.sh
> vet: remove support for non-module-aware Go versions

- xds/server.go
- xds/server_test.go
`xds.GRPCServer` is missing now `GetServiceInfo` and this is vital for [registering metrics for example](https://github.com/grpc-ecosystem/go-grpc-prometheus/pull/102/files)
RELEASE NOTES:
* xds: Add GetServiceInfo() to xds.GRPCServer
> Add GetServiceInfo to xds.GRPCServer

- internal/xds/env/env.go
- xds/internal/balancer/edsbalancer/eds_impl.go
- xds/internal/balancer/edsbalancer/eds_impl_test.go
- xds/internal/httpfilter/fault/fault.go
- xds/internal/httpfilter/fault/fault_test.go
- xds/internal/resolver/serviceconfig.go
- xds/internal/resolver/xds_resolver_test.go
- xds/internal/xdsclient/cds_test.go
- xds/internal/xdsclient/lds_test.go
- xds/internal/xdsclient/rds_test.go
- xds/internal/xdsclient/xds.go
Fault Injection, Timeout, and Circuit Breaking.  One release has been done with these enabled by default, so now we will remove the environment variables entirely.
> xds: remove env var protetion of advanced routing features

- clientconn_test.go
In cases where `t.Fatalf()` doesn't completely end the program, a `ctx.Err()` will cause the program to wait on a mutex indefinitely. 
Forcing the test to enter this specific `if` condition should reproduce the issue.
Adding an unlock before reporting the error allows the program to fail the test as intended when a network error occurs.
Fixes #4537
> grpc: prevent deadlock in Test/ClientUpdatesParamsAfterGoAway on failure

- clientconn.go
- resolver_conn_wrapper.go
- release cc.mu before closing cc_balancer_wrapper
- synchronize all resolver incoming calls.
This is what I think the cause of the xds interop failures. It's similar to #4478 (+#4504).
> internal: fix deadlock during switch_balancer and NewSubConn()

- xds/internal/balancer/balancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/clusterresolver/clusterresolver.go
- xds/internal/balancer/clusterresolver/clusterresolver_test.go
- xds/internal/balancer/clusterresolver/config.go
- xds/internal/balancer/clusterresolver/configbuilder.go
- xds/internal/balancer/clusterresolver/configbuilder_test.go
- xds/internal/balancer/clusterresolver/eds_impl_test.go
- xds/internal/balancer/clusterresolver/eds_watcher.go
- xds/internal/balancer/clusterresolver/logging.go
- xds/internal/balancer/clusterresolver/priority_test.go
- xds/internal/balancer/clusterresolver/testutil_test.go
This PR moves EDS from the eds package to the new cluster_resolver package. The new policy doesn't have the new features yet, those will be added later.
This PR is part of #4546. It's a renaming only change, that doesn't touch any behavior.
> xds: move eds package to cluster_resolver

- metadata/metadata.go
- metadata/metadata_test.go
Since `MD` wraps the map type it is possible to call
```go
delete(md, "An-uppercase-key")
```
and it will faily silently since the contract of this data type is to lowercase the key first. I propose a `Delete` method is added too allowing users to remove keys without the need to lowercase them before.
RELEASE NOTES:
- metadata: add Delete method to MD to encapsulate lowercasing
> metadata: add Delete method to MD

- xds/internal/resolver/serviceconfig.go
- xds/internal/resolver/xds_resolver_test.go
Fixes #4547 
RELEASE NOTES:
- xds: always require a router HTTP filter
> xds: require router filter when filters are empty

- xds/internal/balancer/clusterresolver/eds_impl_test.go
- xds/internal/balancer/clusterresolver/priority_test.go
There's a race between update sub-balancer and the first EDS resp. If
sub-balancer is updated after the first EDS resp, the old balancers
(round_robin) will create two lingering SubConns that are not handled,
which will mess up the following SubConn state updates.
fixes #4554
> xds: fix test race in cluster_resolver

- xds/internal/resolver/serviceconfig.go
- xds/internal/resolver/xds_resolver_test.go
Reverts grpc/grpc-go#4553
xdsclient for v2 will not produce any HTTP filters, so this will cause all RPCs to fail with xds v2.
> Revert "xds: require router filter when filters are empty"

- server.go
- stats/stats.go
- stats/stats_test.go
- stream.go
Fixes #4526
RELEASE NOTES:
- stats: add stats.Begin.IsClientStream and IsServerStream to indicate the type of RPC invoked
> stats: add stream info inside stats.Begin

- test/kokoro/xds_k8s_install_test_driver.sh
Makes it possible to use `TEST_DRIVER_REPO_OWNER` to clone test driver from a fork,  for debug purposes.
Simplifies dev workflow, so it's not necessary to make temporary "DO NOT MERGE" changes, [example](https://github.com/grpc/grpc/pull/26367/files#diff-b26061c1806481e73239048351181cd23e70fb1d3b29571113c8ad6501ac93c1L22-R24).
Related changes:
- https://github.com/grpc/grpc-java/pull/8265
- https://github.com/grpc/grpc/pull/26490
- https://github.com/grpc/grpc-go/pull/4548
- cl/379765815
> buildscripts: add option to use xds-k8s test driver from a fork

- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/clusterimpl/balancer_test.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/balancer/clusterimpl/picker.go
- xds/internal/xdsclient/requests_counter.go
- xds/internal/xdsclient/requests_counter_test.go
Per spec: https://github.com/grpc/proposal/blob/master/A32-xds-circuit-breaking.md#globally-shared-atomics-for-outstanding-requests
> xds/circuit_breaking: counters should be keyed by {cluster, EDS service name} pair

- xds/internal/balancer/clusterresolver/balancerconfig/type.go
- xds/internal/balancer/clusterresolver/balancerconfig/type_test.go
The method needs to be implemented on the type, not the pointer.
Otherwise only the pointer will marshal to the string, the type itself
will marshal to int.
> cluster_resolver: fix DiscoveryMechanismType marshal JSON

- internal/transport/http2_client.go
- test/end2end_test.go
Fixes issue #4492.
RELEASE NOTES:
- client: add deadline to connection when calling TransportCredentials handshaker
> client: add deadline for TransportCredentials handshaker

- xds/internal/xdsclient/dump_test.go
- xds/internal/xdsclient/loadreport_test.go
- xds/internal/xdsclient/tests/README.md
- xds/internal/xdsclient/xdsclient_test.go
Tests can exist in a different package from implementation while still residing in the same directory.  This PR moves `xdsclient/tests/*.go` into `xdsclient/` to avoid an unnecessary separate directory for some of the tests.
> xdsclient: move tests out of tests directory

- server.go
- server_test.go
This improves performance of chained interceptors by removing need to call `getChain(Unary|Stream)Handler` each request. It affects only servers with more than one interceptor.
Here's small benchmark and its result:
```
benchmark                              old ns/op     new ns/op     delta
BenchmarkChainUnaryInterceptor-12      372           209           -43.97%
BenchmarkChainStreamInterceptor-12     404           271           -32.98%
benchmark                              old allocs     new allocs     delta
BenchmarkChainUnaryInterceptor-12      4              4              +0.00%
BenchmarkChainStreamInterceptor-12     4              4              +0.00%
benchmark                              old bytes     new bytes     delta
BenchmarkChainUnaryInterceptor-12      256           128 …
```
> server: improve chained interceptors performance

- internal/transport/http2_client.go
Hi everyone! PR #4316 introduces a serious breaking change that is not listed in the 1.38.0 release notes: it is no longer possible to gather meaningful information from the errors returned by the client whenever a `GOAWAY` message has been previously received, because the original `ConnectionError` is wrapped with a `fmt.Errorf` that discards all this information. This is, again, a breaking change that affects projects like the Vitess tablet RPC among others.
This PR contains a potential fix for the issue. The commit message is inlined for your convenience:
```
PR #4316 updates the http2Client `Close` method so it can append
additional debug information about prior GOAWAY messages before this
connection was closed.
However, it is not safe to do this in the general case, as the original …
```
> internal/transport: do not mask ConnectionError

- internal/transport/http2_client.go
RELEASE NOTES:
* client: fix status code to return Unavailable for servers shutting down instead of Unknown
> internal/transport: do not mask ConnectionError (#4561)

- xds/internal/balancer/clusterimpl/balancer_test.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/testutils/fakeclient/client.go
This was not as big a problem before, because the LRS policy will start the load report stream (it is still a bug, because the drops will not be reported).
This is a more obvious bug after #4528, and was caught by the interop tests.
> xds/cluster_impl: fix cluster_impl not correctly starting LoadReport stream

- clientconn.go
- picker_wrapper.go
RELEASE NOTES:
- balancer: client channel no longer connects to idle subchannels that are returned by the pickers; LB policy should call SubConn.Connect instead.
> clientconn: stop automatically connecting to idle subchannels returned by picker

- internal/binarylog/sink.go
time.Ticker.Stop() doesn't close the ticker channel, so we need to signal the goroutine to die some other way
RELEASE NOTES:
- binarylog: exit the flusher goroutine upon closing the `bufferedSink`
> binarylog: Don't leak the flusher goroutine when closing a Sink

- internal/binarylog/sink.go
RELEASE NOTES:
- binarylog: fail the `Write()` method if proto marshaling fails
> binarylog: Don't continue after failing to marshal the proto

- resolver/manual/manual.go
- xds/internal/balancer/clusterresolver/balancerconfig/type.go
- xds/internal/balancer/clusterresolver/clusterresolver_test.go
- xds/internal/balancer/clusterresolver/eds_impl_test.go
- xds/internal/balancer/clusterresolver/priority_test.go
- xds/internal/balancer/clusterresolver/resource_resolver.go
- xds/internal/balancer/clusterresolver/resource_resolver_dns.go
- xds/internal/balancer/clusterresolver/resource_resolver_test.go
- xds/internal/testutils/fakeclient/client.go
This is what the cluster_resolver policy will use to resolve the resources. It includes
- an EDS watcher, as the old one
- a DNS resolver wrapper, that implements resolver.ClientConn, and calls
the default DNS resolver to resolver DNS hostname
- a top level resolver that combines EDS and DNS
~This PR also includes necessary test variables that are defined in other
files, so the tests can work.~
> cluster_resolver: implement resource resolver to resolve EDS and DNS

- internal/transport/http2_client.go
- test/end2end_test.go
Builds on
https://github.com/grpc/grpc-go/commit/c229922995e2c1af095282ef4d17abcd7300ecaf
Currently we get logs like `closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data:`
which is confusing since there is no debug data. This just cleans it up a bit.
> client: improve GOAWAY debug messages

- internal/binarylog/sink.go
They both touch bufferedSink.writeTicker
> internal/binarylog: Fix data race when calling Write() and Close() in parallel

- internal/resolver/config_selector_test.go
- xds/internal/httpfilter/fault/fault_test.go
- xds/internal/server/listener_wrapper_test.go
***Description***
This pull request fixes a few goroutine leak problems when unit tests fail. 
When `t.Fatal()` is called, only the goroutine calling it will be killed, which may leave other goroutines in these three unit tests blocking and occupying additional resources.
***The fix in internal/resolver/config_selector_test.go***
This unit test contains four channels that are used in another child goroutine running `cs1` or `cs2`.
If the unit test calls `t.Fatal()`, the child goroutine will be blocked at an operation of one of the four channels.
Since the child goroutine only uses receive of `retChan1` and `retChan2`, we defer the close of them in main goroutine.
Since the child goroutine only uses send of `cs1Called` and `cs2Called` for one time, we add 1 buffer to them.
***The fix in …
> test: fix possible goroutine leaks in unit tests

- balancer/grpclb/grpclb.go
- balancer/grpclb/grpclb_test.go
There's an internal test (b/192668900), where we've seen the clients are using grpclb LB policies, and we've occasionally seen some errors of the form "all SubConns are in TransientFailure".
This error message lacks some details which would help to debug. For example: how did the most recent connection fail, and what was the address.
So this plumbs the potentially more detailed error from `UpdateSubconnState` through the grpclb policy to the `ClientConn`, when grpclb enters transient failure.
> grpclb: propagate the most recent connection error when grpclb enters transient failure

- internal/transport/http2_client.go
- internal/transport/transport_test.go
- rpc_util.go
- stream.go
Also allow non-WFR RPCs to retry indefinitely on errors that resulted in no I/O; IIRC the spec used to forbid it, but it no longer does.
> client: fix detection of whether IO was performed in NewStream

- test/kokoro/xds_k8s.sh
- test/kokoro/xds_url_map.cfg
- test/kokoro/xds_url_map.sh
Related PR grpc/grpc#26764
Related CL cl/386366746
This test suite will be run every 6 hours, and takes around 30 minutes. The script is copied from `xds-k8s.sh`, and removed the generation of server image.
> Add xDS k8s url-map test Kokoro job

- security/advancedtls/crl.go
Fix a typo in crl.go.
This was detected while I was trying to do the import of the recently added CRL code.
> advancedtls: fix a typo in crl.go

- server.go
This happens when NewServerTransport() returns nil, nil. The rawConn is
closed when the transport is closed, which will never happen in this
case (since the returned transport is nil).
Fixes #4632
Introduced in #4458. Needs to be backported to **1.39.x** and **1.40.x**.
RELEASE NOTES:
- server: fix bug that net.Conn is leaked if the connection is closed (io.EOF) immediately with no traffic
> server: fix leaked net.Conn

- .github/workflows/stale.yml
The v4 release of the stale bot fixes a bug that makes the bot ignore updates by the user that created the stale bot workflow (me).  This release also fixes the `operations-per-run` option so it will work as intended.  Unfortunately, that means low values will limit the number of issues it can inspect, so this PR also increases the operations per run to something much larger than we should need (I'd expect us to need at most 100-200 per run).
> github: update stale bot to v4

- internal/transport/http2_client.go
issue #4626
Regression caused by #3313
RELEASE NOTES:
- transport: fix race in transport stream accessing s.recvCompress
> transport: fix race accessing s.recvCompress

- internal/serviceconfig/serviceconfig.go
- xds/internal/balancer/clusterresolver/clusterresolver.go
- xds/internal/balancer/clusterresolver/config.go
- xds/internal/balancer/clusterresolver/config_test.go
- xds/internal/balancer/clusterresolver/configbuilder.go
- xds/internal/balancer/clusterresolver/configbuilder_test.go
- xds/internal/balancer/clusterresolver/eds_impl_test.go
- xds/internal/balancer/ringhash/config.go
- xds/internal/balancer/ringhash/config_test.go
1. merge endpoint picking and localility picking policy to one field in cluster_resolver's balancer config
- This field only supports ROUND_ROBIN or RING_HASH.
- This is to support RING_HASH policy, which is responsible both endpoint picking and locality picking.
- If policy is RING_HASH, endpoints in localities will be flattened to a list of endpoints, and passed to the policy.
1. support building policy config with RING_HASH as a child
- The config tree has one less layer comparing with ROUND_ROBIN
- This also need to define RING_HASH's balancer config config
1. Deleted test `TestEDS_UpdateSubBalancerName` because now the balancer doesn't support updating child to a custom policy.
> xds/cluster_resolver: support RING_HASH as a child of cluster_resolver balancer

- balancer/balancer.go
- balancer_conn_wrappers.go
- clientconn.go
- clientconn_state_transition_test.go
- clientconn_test.go
- pickfirst.go
- test/channelz_test.go
- test/creds_test.go
- test/end2end_test.go
RELEASE NOTES:
- Balancer API: SubConns no longer automatically reconnect after READY; instead they transition to IDLE on connection loss.
> clientconn: do not automatically reconnect addrConns; go idle instead

- test/kokoro/xds_k8s.sh
- test/kokoro/xds_k8s_install_test_driver.sh
Related https://github.com/grpc/grpc-go/pull/4661 b/196202377
Somehow, the Kokoro script failed to pick up the checked-in function for tag_and_push_docker_image in grpc/grpc master. So, this PR uses Docker command directly.
https://fusion2.corp.google.com/invocations/f198d36f-5def-4296-b76a-387993b6d941/targets
> Copy the tag_and_push_docker_image method to grpc-go

- xds/internal/resolver/watch_service_test.go
- xds/internal/resolver/xds_resolver_test.go
- xds/internal/server/listener_wrapper.go
- xds/internal/server/listener_wrapper_test.go
- xds/internal/server/rds_handler.go
- xds/internal/server/rds_handler_test.go
- xds/internal/testutils/fakeclient/client.go
- xds/internal/xdsclient/client.go
- xds/internal/xdsclient/filter_chain.go
- xds/server.go
- xds/server_test.go
Continuation of #4629, expect rebased and cleaner commit history.
This PR adds RDS to Listener Wrapper. This is for any Filter Chains which specify dynamic RDS Responses. This PR is scoped only to Persisting RDS Configuration/Dynamic logic, and only the persistence in Listener Wrapper. Future functionality involves actually instantiating filters using this configuration, and matching (routing) + running through HTTP Filters in xds(Unary|Stream)Interceptor.
> xds: Add support for Dynamic RDS in listener wrapper

- internal/transport/http2_client.go
This is a backport of #4641
RELEASE NOTES:
- transport: fix race in transport stream accessing s.recvCompress
> server: fix leaked net.Conn (#4644)

- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/cdsbalancer/cluster_handler.go
- xds/internal/balancer/cdsbalancer/cluster_handler_test.go
- xds/internal/xdsclient/cds_test.go
- xds/internal/xdsclient/client.go
- xds/internal/xdsclient/xds.go
- xdsclient: read lb policy from the CDS response, and parse ringhash config
- cdsbalancer: set cluster_resolver's child policy to ringhash with config
> xds: support picking ringhash in xds client and cds policy

- server.go
closed twice for conn.net when NewServerTransport() returns nil, err.
whether ServerTransport returns nil or err returns not nil，we only need to call close once .
Related PR:
[4661](https://github.com/grpc/grpc-go/pull/4644)
> server: fix net.conn closed twice

- balancer/balancer.go
- balancer/base/balancer.go
- balancer/grpclb/grpclb.go
- balancer/rls/internal/balancer.go
- balancer_conn_wrappers.go
- balancer_switching_test.go
- clientconn.go
- internal/balancer/stub/stub.go
- pickfirst.go
- test/balancer_test.go
- xds/internal/balancer/balancergroup/balancergroup.go
- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/balancer/clustermanager/clustermanager.go
- xds/internal/balancer/clusterresolver/clusterresolver.go
- xds/internal/balancer/clusterresolver/clusterresolver_test.go
- xds/internal/balancer/priority/balancer.go
- xds/internal/balancer/weightedtarget/weightedtarget.go
RELEASE NOTES:
- balancer: add ExitIdle interface to instruct the balancer to attempt to leave the IDLE state by connecting SubConns if appropriate.  The method will be required by the Balancer interface in the future.
> balancer: add ExitIdle optional interface

- internal/transport/http2_server.go
- internal/transport/transport.go
- server.go
This PR moves the Server Credentials Handshake from Server to Transport. This accomplishes a few things. One, it starts moving functionality best handled by the transport level from the server (grpc layer). Two, it makes this consistent with client side. Three, it allows the rawconn (and not a potentially returned authenticated conn) to be piped into the transports context, which will be used for xds routing.
> Move Server Credentials Handshake to transport

- test/balancer_test.go
- test/creds_test.go
- test/end2end_test.go
- test/insecure_creds_test.go
end2end_tests are frequently causing the overall 7m timeout to fire as they wait in their blocking `Dial()` calls. 
A blocking `Dial()` should hardly ever be used, especially in tests. This PR switches most of these calls to non blocking `Dial()`s and adds a `WaitForReady` call option wherever appropriate.
> test: use non blocking dials in end2end_test

- xds/internal/test/xds_server_serving_mode_test.go
The test creates two listeners, and both are in `serving` mode initially. We also have two clientConns to the two servers (backed by those two listeners), and these are initially in `READY` state and are able to make a successful RPC. 
Then we remove one of the listener resources, which gets one of the servers into `not-serving` mode. At this point, we check if one of the clientConns has moved out of `READY` (because the server is not serving anymore) and the other one remains in `READY` (since this server is not affected and is still serving).
Currently, grpc-go does not suppress xds resource updates which change only in the *version* number. Therefore, the test receives a `Listener` update even for the resource which has not been updated, and since we updated the A36 spec recently to …
> xds: deflake Test/ServerSideXDS_ServingModeChanges

- xds/internal/xdsclient/v2/client_test.go
Fixes https://github.com/grpc/grpc-go/issues/4452
In google3, without the fix, the test failed 8/10000 times, and with the fix, it passed all the time.
> xds: use the defaultTestTimeout instead of the short one in TestV2ClientBackoffAfterRecvError

- clientconn_test.go
Fixes #4698
If `stayConnected` was called while the `ClientConn` was in IDLE already, it would never call `Connect`, and stay stuck in that state.  This change ensures `cc.Connect` is always called at least once.
> grpc: fix stayConnected function to connect upon entry

- xds/internal/httpfilter/fault/fault.go
- xds/internal/httpfilter/httpfilter.go
- xds/internal/httpfilter/router/router.go
- xds/internal/server/listener_wrapper_test.go
- xds/internal/testutils/e2e/clientresources.go
- xds/internal/xdsclient/filter_chain.go
- xds/internal/xdsclient/filter_chain_test.go
- xds/internal/xdsclient/lds_test.go
- xds/internal/xdsclient/xds.go
- xds/server_test.go
This PR adds a requirement for Router Filter for both Client and Server Side. This is done through adding an API you can call to see if an HTTP Filter is terminal.
> xds: Required Router Filter for both Client and Server side

- test/kokoro/xds_url_map.sh
Part of https://github.com/grpc/grpc/pull/27189 and b/198291728.
By disabling the workload identity, we should be able to run tests faster and avoid future IAM policy size issue.
@menghanl PTAL.
Kokoro run: https://fusion2.corp.google.com/invocations/03bca679-8e60-408b-bb0f-161e82d6d09a/targets
> Change to a non-workload-identity GKE cluster

- test/kokoro/xds_url_map.sh
Part of grpc/grpc#27189 and b/198291728.
By disabling the workload identity, we should be able to run tests faster and avoid future IAM policy size issue.
@menghanl PTAL.
Kokoro run: https://fusion2.corp.google.com/invocations/b61ca6a7-a99c-43f6-9740-00c8bf592a6f
> [Backport v1.40.x] Change to a non-workload-identity GKE cluster

- examples/go.sum
- go.mod
- go.sum
- security/advancedtls/examples/go.sum
- security/advancedtls/go.sum
- xds/internal/resolver/serviceconfig.go
- xds/internal/resolver/serviceconfig_test.go
- xds/internal/resolver/xds_resolver_test.go
github.com/cespare/xxhash/v2 supports Go ≥ 1.11 and this package states
1.11 in its go.mod file. The only symbol used from the xxhash package is the
Sum64String func which still exists and works the same in v2.
This gets rid of two indirect dependencies.
> xds/internal/resolver: update github.com/cespare/xxhash to v2

- xds/internal/balancer/ringhash/ring.go
- xds/internal/balancer/ringhash/ring_test.go
This is the ring that will be used by the ring_hash policy.
An example ring with {item:weight} {a:3,b:3,c:4} is
```
// - {idx:0 hash:3689675255460411075  b}
// - {idx:1 hash:4262906501694543955  c}
// - {idx:2 hash:5712155492001633497  c}
// - {idx:3 hash:8050519350657643659  b}
// - {idx:4 hash:8723022065838381142  b}
// - {idx:5 hash:11532782514799973195 a}
// - {idx:6 hash:13157034721563383607 c}
// - {idx:7 hash:14468677667651225770 c}
// - {idx:8 hash:17336016884672388720 a}
// - {idx:9 hash:18151002094784932496 a}
```
> ringhash: the ring

- xds/internal/server/listener_wrapper.go
- xds/internal/xdsclient/filter_chain.go
- xds/internal/xdsclient/filter_chain_test.go
This PR fixes a race condition in Filter Chain. Instead of persisting the route table in the filter chain, which is then read to be put into connection, the function instead returns the route table.
> xds: Fix race in Filter Chain

- xds/internal/test/xds_server_serving_mode_test.go
- Use separate update channels for listeners in test. This makes the test a little bit more verbose, but it gets rid of the flakes.
- While waiting for RPCs to start failing after the listener moves to "not-serving", reduce the frequency of trying.
With these two fixes, I was able to run the test 100k times without a single flake.
> xds: use separate update channels for listeners in test

- credentials/oauth/oauth.go
- credentials/oauth/oauth_test.go
- internal/credentials/util.go
- internal/credentials/util_test.go
The self-signed JWT used to access Google API regional endpoints do not have a correct audience format dictated in https://google.aip.dev/auth/4111. That is, it includes a trailing RPC service name while the spec requires only the presence of hostname (or endpoint).
RELEASE NOTES:
* oauth: Allow access to Google API regional endpoints via Google Default Credentials
> oauth: Allow access to Google API regional endpoints via Google Default Credentials

- xds/internal/balancer/priority/balancer_priority.go
- xds/internal/balancer/priority/balancer_test.go
This is needed so that balancers start with an IDLE picker (like
ring_hash) will get picks.
> priority: forward the first IDLE state and picker

- xds/internal/balancer/ringhash/config.go
- xds/internal/balancer/ringhash/picker.go
- xds/internal/balancer/ringhash/picker_test.go
- xds/internal/balancer/ringhash/ring.go
- xds/internal/balancer/ringhash/ringhash.go
- xds/internal/balancer/ringhash/ringhash_test.go
- xds/internal/testutils/balancer.go
A picker has a ring. It retrieves the hash from the context, and find the SubConn from the ring.
The picker also handles the situation where the first picked SubConn isn't ready, by falling back to other available SubConns in the ring.
> ringhash: the picker

- .github/workflows/testing.yml
- internal/envconfig/envconfig.go
- internal/xds/env/env.go
- test/retry_test.go
- xds/internal/resolver/serviceconfig.go
- xds/internal/test/xds_client_integration_test.go
- xds/internal/xdsclient/client.go
- xds/internal/xdsclient/rds_test.go
- xds/internal/xdsclient/xds.go
RELEASE NOTES:
- xds: add support for retry policy in VirtualHosts and Routes
> xds: add retry support

- interop/client/client.go
- interop/test_utils.go
This is a Go analogue of Java PR: https://github.com/grpc/grpc-java/pull/8407
Documentation PR: https://github.com/grpc/grpc/pull/27030 adds cross language documentation for this test
FWIW, C++  [channel_soak test case is here](https://github.com/grpc/grpc/blob/3e34e3aac790a256943b4b7dada269209c60fe44/test/cpp/interop/client.cc#L55) and [rpc_soak test case is here](https://github.com/grpc/grpc/blob/3e34e3aac790a256943b4b7dada269209c60fe44/test/cpp/interop/client.cc#L72) (for which the code is mainly in https://github.com/grpc/grpc/blob/3e34e3aac790a256943b4b7dada269209c60fe44/test/cpp/interop/interop_client.cc#L1120).
> interop-testing: add soak test cases to interop client

- xds/internal/xdsclient/cds_test.go
- xds/internal/xdsclient/client.go
- xds/internal/xdsclient/filter_chain.go
- xds/internal/xdsclient/lds_test.go
- xds/internal/xdsclient/xds.go
The new method is documented at https://github.com/grpc/proposal/blob/master/A29-xds-tls-security.md and based on envoyproxy/envoy#17201. The old fields are still supported and are used as fallback when the new fields don't provide the required data.
TL;dr
- Identity certs used to be fetched from the `tls_certificate_certificate_provider_instance` field [here](https://github.com/envoyproxy/envoy/blob/ff68b337d038acccb770fcceec57441cf0c740e2/api/envoy/extensions/transport_sockets/tls/v3/tls.proto#L256).
- Going forward, they will be fetched from the `tls_certificate_provider_instance` field [here](https://github.com/envoyproxy/envoy/blob/ff68b337d038acccb770fcceec57441cf0c740e2/api/envoy/extensions/transport_sockets/tls/v3/tls.proto#L247).
- Validation context used to be fetched from …
> xds: support new fields to fetch security configuration

- internal/xds/env/env.go
- xds/internal/xdsclient/cds_test.go
- xds/internal/xdsclient/xds.go
Set the value to true by default, and remove it one release later.
https://github.com/grpc/grpc-go/pull/4735 removed the env var. The general process is that we set the env var's value to `true` by default and completely remove it only after a release.
> xds: don't remove env var protection for security on the client yet

- clientconn.go
Fixes https://github.com/grpc/grpc-go/issues/4725
Issue:
When a subConn in `Connecting` state is removed by the load balancer, there is a race between handling the close of the subConn and a possible receipt of a http/2 preface (which will move the subConn to `Ready`). The underlying transport, which was not ready when the subConn close was called but becomes ready before the close is completely handled, was getting leaked in this case.
Fix:
- Check for subConn state upon receipt of the http/2 preface and if the subConn is in `Connecting`, close the underlying transport
- Use the `connectCtx` in the `select` in `createTransport` to avoid creating a new timer
RELEASE NOTES:
- Fix possible transport leak when a subConn is closed when in `Connecting` state
> grpc: close underlying transport when subConn is closed when in connecting state

- balancer/balancer.go
- balancer/base/balancer.go
- balancer/roundrobin/roundrobin.go
Generally, channels with zero subconns are not usable and should report `TransientFailure`.  This matches previous behavior before Idle support.
Also fix a bug that the base balancer was not accounting for newly created subchannels' idleness.  When the first subchannel transitioned from Idle to Connecting, the number of idle subconns would become `MaxUInt64` due to underflow.
Finally, fix another idleness bug that broke the logic of "stick transient failure" where a subconn that goes to TransientFailure should stay in that state until it goes Ready or Shutdown.
Fixes #4740
(No release notes since this fixes a regression introduced after the last release.)
> balancer: fix aggregated state to not report idle with zero subconns

- stats/stats.go
- stream.go
- test/end2end_test.go
- test/retry_test.go
RELEASE NOTES:
- stats: support stats for all retry attempts; support transparent retry
> stats: support stats for all retry attempts; support transparent retry

- xds/internal/balancer/clusterresolver/config.go
- xds/internal/balancer/clusterresolver/config_test.go
- xds/internal/resolver/serviceconfig.go
- xds/internal/resolver/serviceconfig_test.go
- xds/internal/resolver/xds_resolver_test.go
Found by interop tests.
clusterresolver
- use real balancer names
xds-resolver
- s/`FromIncomingContext`/`FromOutgoingContext`
> xds/affinity: fix bugs in clusterresolver and xds-resolver

- xds/internal/balancer/priority/balancer_priority.go
Previously, Idle won't stop lower priorities (#4731). Now it will.
> priority: handle Idle children the same way as Ready

- binarylog/binarylog_end2end_test.go
- internal/transport/http2_server.go
- test/end2end_test.go
This PR adds a hardcoded :method POST to Server's metadata as per A41 in support of the RBAC HTTP Filter.
The transport verifies and makes sure the only accepted :method is POST.
> transport/server: add :method POST to incoming metadata

- connectivity/connectivity.go
- credentials/xds/xds.go
- xds/internal/server/listener_wrapper.go
- xds/internal/test/xds_server_serving_mode_test.go
- xds/server.go
- xds/server_options.go
- xds/server_test.go
- xds/xds.go
RELEASE NOTES:
- Mark xDS server and creds API as stable
> xds: de-experimentalize xDS apis required for psm security

- xds/internal/xdsclient/cds_test.go
- xds/internal/xdsclient/filter_chain.go
- xds/internal/xdsclient/filter_chain_test.go
- xds/internal/xdsclient/xds.go
This PR adds the following validations, as specified in A29:
- `transport_socket_matches` field in `Cluster` message is not supported
- Following fields of `CommonTlsContext` are not supported:
- `tls_params`
- `custom_handshaker`
- `validation_context_sds_secret_config` field inside `validation_context_type` is not supported
- `tls_certificates` or `tls_certificate_sds_secret_configs` fields are set and `tls_certificate_provider_instance` field is unset
- Following fields of `DownstreamTlsContext` are not supported:
- `require_sni`
- Only allowed value for `ocsp_staple_policy` field is `LENIENT_STAPLING`
- `match_subject_alt_names` is not supported on the server
- Following fields of `CertificateValidationContext` are not supported:
- `verify_certificate_spki`
- `verify_certificate_hash` …
> xds: validations for security config, as specified in A29

- test/bufconn/bufconn.go
for use with grpc.WithContextDialer DialOption
RELEASE NOTES:
* test/bufconn: add Listener.DialContext(context.Context)
> test/bufconn: add Listener.DialContext(context.Context)

- .github/workflows/testing.yml
- internal/xds/env/env.go
- test/retry_test.go
And change how it's done for the security env var.
> xds: enable ringhash and retry by default

- internal/grpctest/tlogger.go
Error logs cause tests to fail. This makes it easier (AKA possible) to find the error log
> tlogger: print log type

- internal/xds/env/env.go
- xds/internal/httpfilter/httpfilter.go
- xds/internal/httpfilter/rbac/rbac.go
- xds/internal/server/listener_wrapper.go
- xds/internal/server/listener_wrapper_test.go
- xds/internal/test/xds_server_integration_test.go
- xds/internal/xdsclient/filter_chain.go
- xds/internal/xdsclient/filter_chain_test.go
- xds/internal/xdsclient/lds_test.go
- xds/server.go
This PR adds an environment variable which must be explicitly set to true in order for RBAC to be enabled. This protects all logic added to xDS in grpc-go added due to RBAC, including all usages of routing on server side.
> xds: Add env var protection for RBAC HTTP Filter

- test/kokoro/xds_url_map.sh
grpc/grpc#27373
@menghanl 
Ah, you were mentioning master branch in grpc-go, I thought you meant master branch in grpc/grpc. Yes, we need this flag for all testing branches...
> [Backport grpc#27373] add testing_version flag

- internal/xds/matcher/string_matcher_test.go
- xds/internal/xdsclient/rds_test.go
They were deprecated, and removed later.
> xds/test: delete use of removed types

- internal/transport/http2_client.go
- stream.go
Fixes a regression caused by #3677 
RELEASE NOTES:
* transport: fix transparent retries when per-RPC credentials are in use
> transport: fix transparent retries when per-RPC credentials are in use

- internal/transport/http2_server.go
- server.go
This PR fixes log spam, which was introduced by #4692. This PR didn't prevent logging on errConnDispatched and io.EOF, which this PR adds.
> transport: fix log spam from Server Authentication Handshake errors

- internal/xds/rbac/matchers.go
- xds/internal/xdsclient/filter_chain.go
- xds/internal/xdsclient/lds_test.go
- xds/internal/xdsclient/xds.go
This implements the paragraph in A41: "New validation should occur for HttpConnectionManager to allow equating direct_remote_ip and remote_ip. If the implementation does not distinguish between these fields, then xff_num_trusted_hops must be unset or zero and original_ip_detection_extensions must be empty. If either field has an incorrect value, the Listener must be NACKed. For simplicity, this behavior applies independent of the Listener type (both client-side and server-side)."
> xds: Added validations for HCM to support xDS RBAC Filter

- server.go
Removes one allocation from the unary and stream chained interceptors
by combining them into a struct. This saves about 10% time/call on
the microbenchmark (see below).
The unary and stream chain interceptors must allocate on each call to
track the current position in the interceptor stack, and to create
the closure. By default, Go allocates each variable in a closure in a
separate heap allocation, so they can be garbage collected
independently. However, we know the index and next handler callbacks
should be garbage collected together, so we can force them to be
allocated together by combining them in a struct.
The benchmark results on my laptop are below:
BEFORE
```
$ go test . -bench=BenchmarkChain -benchtime=10s -benchmem -run=none
goos: darwin
goarch: amd64
pkg: google.golang.org/grpc …
```
> server: optimize chain interceptors (-1 allocation, -10% time/call)

- xds/internal/balancer/clustermanager/balancerstateaggregator.go
- xds/internal/balancer/clustermanager/clustermanager_test.go
- xds/internal/balancer/weightedtarget/weightedaggregator/aggregator.go
- xds/internal/balancer/weightedtarget/weightedtarget_test.go
Without this, the parent balancers report transient_failure when the child reports Idle
> xds: fix parent balancers to handle Idle children

- interop/client/client.go
This is mainly needed to use the interop client in scenarios where it uses an XDS ring hash LB policy - which won't become "Ready" unless an RPC is started. This was originally added in https://github.com/grpc/grpc-go/pull/1559 but shouldn't be needed now.
> interop: don't use WithBlock dial option in the client

- internal/transport/http2_server.go
- server.go
- xds/internal/balancer/clustermanager/balancerstateaggregator.go
- xds/internal/balancer/clustermanager/clustermanager_test.go
- xds/internal/balancer/weightedtarget/weightedaggregator/aggregator.go
- xds/internal/balancer/weightedtarget/weightedtarget_test.go
* xds: fix parent balancers to handle Idle children (#4801)
* transport: fix log spam from Server Authentication Handshake errors (#4798)
> backport PRs to v1.41.x

- admin/admin.go
- channelz/service/service.go
Is it also time to remove "Experimental" from the admin API?
> channelz: recommend using admin.Register instead

- internal/transport/controlbuf.go
- internal/transport/http2_server.go
- internal/transport/transport_test.go
- test/end2end_test.go
This PR adds logic to support xDS Configured HTTP Filter, as per A41.
> transport: logic specified in A41 to support RBAC xDS HTTP Filter

- internal/xds/rbac/rbac_engine.go
- metadata/metadata.go
- xds/internal/httpfilter/rbac/rbac.go
- xds/internal/test/xds_server_integration_test.go
This PR implements these lines from A41:
1. "As documented for HeaderMatcher, Envoy aliases :authority and Host in its header map implementation, so they should be treated equivalent for the RBAC matchers; there must be no behavior change depending on which of the two header names is used in the RBAC policy."
2. ":method can be hard-coded to POST if unavailable and a code audit confirms the server denies requests for all other method types."
3. "If the transport exposes te: trailers in Metadata, then RBAC must special-case the header to treat it as not present."
> xds: Small changes at xDS RBAC Layer

- security/advancedtls/advancedtls.go
- security/advancedtls/advancedtls_integration_test.go
- security/advancedtls/advancedtls_test.go
This PR adds the revocation configs to the client/server options, and enables the checks if they are specified.
With the revocation check, advanced TLS users can detect if the certs sent from the peer are in a good state or not.The revocation information is very useful when certain certificates are revoked by the CA.
> advancedtls: add revocation support to client/server options

- xds/internal/test/xds_server_integration_test.go
- xds/internal/xdsclient/rds_test.go
- xds/internal/xdsclient/xds.go
Before this, the response is ACKed, but the unknown cluster specifier is ignored. The RPCs picking this route will fail because there's no valid action to take.
RELEASE NOTES:
* xds/rds: NACK the RDS response if it contains unknown cluster specifier
> xds/rds: NACK unknown route action cluster specifier

- internal/transport/http2_client.go
Fixes #4808 (the second race).
By calling `closeStream` first, it was possible to end up calling the stats handler with the `End` stat before the `InTrailer` stat.  While this is valid, it does not seem desirable, and this change makes it so that is no longer possible.
This also corrects a very minor bug where the stats handler would receive the contents of `s.trailer`, which _might_ not be the same as `mdata` if a race led to `closeStream` being called on that stream before `operateHeaders` was able to call `closeStream`.
> transport: call stats handler for trailers before closeStream

- internal/xds/rbac/matchers.go
- internal/xds/rbac/rbac_engine.go
- internal/xds/rbac/rbac_engine_test.go
- xds/internal/httpfilter/rbac/rbac.go
- xds/internal/test/xds_server_integration_test.go
This PR implements these three lines from A41:
"to allow equating RBAC's direct_remote_ip and remote_ip."
"At this time, if the RBAC.action is Action.LOG then the policy will be completely ignored, as if RBAC was not configurated."
"If there is no client certificate (thus no SAN nor Subject), check if "" (empty string) matches. If it matches, the principal_name is said to match"
> xds: Small RBAC Changes defined in A41

- balancer/rls/internal/config.go
- balancer/rls/internal/config_test.go
- rename child policy name, config and target field variables with longer variable names
- change the child policy field to be of type `map[string]json.RawMessage`. This is better because when we actually build the child policy, we need to add the `target_field_name` to it.
- clean up tests
#RouteLookupService
> rls: improve config parsing

- clientconn_test.go
Fixes #4729 (I hope)
I noticed a potential race:
1. `stayConnected` calls `cc.Connect()`
1. `cc` is not `IDLE` so does nothing
1. `ac` goes `IDLE` for any reason
1. `cc.GetState()` reports `IDLE`
1. `stayConnected` waits for the state to change from `IDLE`, which will never happen
1. `<not reached>`
The fix is to call `cc.GetState()` first, then call `cc.Connect()` if `IDLE`, and then wait for the state to change before doing anything else otherwise.
> test: fix stayConnected to call Connect after state reports IDLE

- internal/transport/http2_server.go
- server.go
- test/end2end_test.go
Fixes #4833
RELEASE NOTES:
* server: add missing conn.Close if the connection dies before reading the HTTP/2 preface
> server: add missing conn.Close if the connection dies before reading the HTTP/2 preface

- .github/workflows/codeql-analysis.yml
It seems 20 minutes is not always enough, as I've seen some runs report "canceled".
> github: increase timeout for codeql and disable for PRs

- test/kokoro/xds.sh
> [Backport v1.41.x] kokoro: remove expired letsencrypt.org cert and update

- test/kokoro/xds.sh
> [Backport v1.40.x] kokoro: remove expired letsencrypt.org cert and update

- test/kokoro/xds.sh
> [Backport v1.39.x] kokoro: remove expired letsencrypt.org cert and update

- test/kokoro/xds.sh
> [Backport v1.38.x] kokoro: remove expired letsencrypt.org cert and update

- test/kokoro/xds.sh
> [Backport v1.37.x] kokoro: remove expired letsencrypt.org cert and update

- credentials/google/google.go
- credentials/google/google_test.go
The new bundle built with options not only works on GCE.
See #4767 for the previous change
RELEASE NOTES:
* creds/google: add NewDefaultCredentialsWithOptions() to support custom per-RPC creds
> creds/google: replace NewComputeEngineCredsWithOptions with NewDefaultCredentialsWithOptions

- xds/internal/xdsclient/client.go
- xds/internal/xdsclient/filter_chain.go
- xds/internal/xdsclient/filter_chain_test.go
This PR NACKs a missing route specifier server side, as it is required in Envoy. https://github.com/envoyproxy/envoy/blob/56e8c45b1b340c4a4f8f02ec2488354c31806d59/api/envoy/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#L317. A nil route specifier actually caused a bug, as my RBAC HTTP Filter addition didn't have the correct logic when Route Specifier was nil (see #4924). Luckily, this situation is gatekeeped by the requirement that RouteSpecifier be present.
cc: @ejona86, @lidizheng
> xds: NACK missing route specifier server side

- dialoptions.go
As proposed per #4461, this change removes comments stating that WithConnectParams API is still experimental.
Please let me know if we need to adjust any commentary for this function or change anything else.
Closes #4461 
RELEASE NOTES:
- Remove experimental notice around the `WithConnectParams` DialOption
> grpc: stabilize WithConnectParams DialOption

- test/kokoro/xds_k8s.cfg
- test/kokoro/xds_k8s.sh
It is successfully passing against prod:
https://source.cloud.google.com/results/invocations/afd2ba0d-657d-4277-bc1d-43fc27a1af3a/targets
> kokoro: Enable xds authz_test

- test/kokoro/xds_k8s.cfg
- test/kokoro/xds_k8s.sh
* kokoro: Enable xds authz_test
Backport of #4954
> kokoro: Enable xds authz_test (#4954) (v1.42.x backport)

- xds/internal/resolver/xds_resolver.go
- xds/internal/resolver/xds_resolver_test.go
- xds/internal/testutils/fakeclient/client.go
- xds/internal/xdsclient/bootstrap/template.go
- xds/internal/xdsclient/bootstrap/template_test.go
- xds/server.go
And also handle percent encoding for new style resource names.
RELEASE NOTES:
* [bug]xds/resolver: release leaked ClientConn if resolver initialization fails
> xds/federation: support populating resource template in xds-resolver

- internal/xds/env/env.go
- xds/internal/xdsclient/bootstrap/bootstrap.go
- xds/internal/xdsclient/bootstrap/bootstrap_test.go
> xds/federation: support new bootstrap fields and protect them by an env var

- authz/rbac_translator.go
- balancer/rls/internal/adaptive/adaptive_test.go
- balancer/rls/internal/client.go
- balancer/rls/internal/client_test.go
- benchmark/benchmain/main.go
- benchmark/latency/latency_test.go
- binarylog/binarylog_end2end_test.go
- internal/channelz/funcs.go
- internal/profiling/buffer/buffer.go
- internal/serviceconfig/serviceconfig_test.go
- internal/transport/flowcontrol.go
- internal/transport/http2_client.go
- internal/transport/proxy.go
- internal/transport/proxy_test.go
- internal/transport/transport_test.go
- stats/stats_test.go
- test/balancer_test.go
- xds/internal/balancer/cdsbalancer/cluster_handler_test.go
- xds/internal/test/e2e/controlplane.go
- xds/internal/test/e2e/e2e.go
- xds/internal/test/e2e/e2e_test.go
Remove some unused parameters.
> lint: fix some unused parameter issues

- dialoptions.go
- internal/envconfig/envconfig.go
- internal/xds/env/env.go
- test/retry_test.go
- xds/internal/test/xds_client_integration_test.go
- xds/internal/xdsclient/xdsresource/unmarshal_rds.go
- xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
RELEASE NOTES:
* config: remove retry disable via environment variable
> config: remove retry disable via environment variable

- clientconn.go
- clientconn_test.go
- credentials/credentials.go
- credentials/insecure/insecure.go
- dialoptions.go
- test/creds_test.go
- test/insecure_creds_test.go
We have an insecure transport credentials implementation in the `insecure` package. This PR changes the implementation of `WithInsecure()` to use that instead of setting a different field inside of `dialOptions`.
RELEASE NOTES:
* Implement `grpc.WithInsecure` using `insecure.NewCredentials` * Mark `grpc.WithInsecure` as deprecated * Make it mandatory for `credentials.Bundle` to return non-nil `TransportCredentials`
> grpc: implement WithInsecure() using the insecure package

- internal/xds/rbac/rbac_engine.go
- xds/internal/httpfilter/rbac/rbac.go
- xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
- xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
This PR moves the validation and construction of the RBAC Matcher engine to ParseConfig. This makes it so that if a xds resource is received with some invalid RBAC matcher, the resource gets explicitly NACKed. Previously, the server would continue to serve, and then fail on a connection accept as the filter chain that the accepted connection matched to attempted to be constructed.
cc @ejona86
> xds: Added validation and construction of RBAC matcher engine to ParseConfig

- pickfirst.go
Fixes #4965
RELEASE NOTES:
* client: fix nil panic in rare race conditions with the pick first LB policy
> pickfirst: check b.sc before calling Connect

- internal/envconfig/xds.go
- internal/xds/bootstrap.go
- xds/googledirectpath/googlec2p.go
- xds/googledirectpath/googlec2p_test.go
- xds/internal/httpfilter/rbac/rbac.go
- xds/internal/resolver/serviceconfig.go
- xds/internal/resolver/xds_resolver_test.go
- xds/internal/server/listener_wrapper.go
- xds/internal/server/listener_wrapper_test.go
- xds/internal/test/xds_client_affinity_test.go
- xds/internal/test/xds_server_integration_test.go
- xds/internal/xdsclient/bootstrap/bootstrap.go
- xds/internal/xdsclient/bootstrap/bootstrap_test.go
- xds/internal/xdsclient/xdsresource/filter_chain.go
- xds/internal/xdsclient/xdsresource/filter_chain_test.go
- xds/internal/xdsclient/xdsresource/unmarshal_cds.go
- xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
- xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
- xds/internal/xdsclient/xdsresource/unmarshal_rds.go
- xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
- xds/server.go
> internal: merge xds/envconfig into env package

- balancer/balancer.go
- clientconn.go
- test/balancer_test.go
- This field will be required in RLS.
- Also, cleaned up docstrings around other fields in `balancer.BuildOptions`.
RELEASE NOTES:
- A new field `Authority` is added to `balancer.BuildOptions` to specify the server name to use in the authentication handshake with a remote load balancer.
> balancer: add Authority field to balancer.BuildOptions

- clientconn.go
Without this, it's confusing when the service config is sent by the
resolver, but not used by the ClientConn (in cases like xDS resolver).
> internal: add log when service config is disabled

- xds/csds/csds.go
- xds/internal/xdsclient/attributes.go
- xds/internal/xdsclient/dump.go
- xds/internal/xdsclient/dump_test.go
- xds/internal/xdsclient/pubsub/dump.go
- xds/internal/xdsclient/pubsub/pubsub.go
- xds/internal/xdsclient/pubsub/update.go
Version is not used by anyone (not even in the CSDS responses).
And version doesn't make sense in federation (when there are multiple control plane servers)
> xds/client: cleanup Dump to remove unnecessary version field

- examples/route_guide/client/client.go
- examples/route_guide/server/server.go
Currently the example doesn't work following the `README.md` since the server port should be `10000`.
This fixes the following error:
```
2021/11/11 21:52:52 Getting feature for point (409146138, -746188906)
2021/11/11 21:52:52 &{0x140001c0a80}.GetFeatures(_) = _, rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:50051: connect: connection refused": 
exit status 1
```
> examples: Fix server port in route_guide example to work with client

- internal/grpctest/grpctest.go
> internal: move leakcheck to t.Cleanup

- status/status.go
- status/status_test.go
Return an appropriate Status from status.FromContext error if either the supplied error or an error in its chain is one of the context sentinel error values.
Closes #4976 
- status: support wrapped errors in FromContextError
> status: support wrapped errors in FromContextError

- balancer/rls/internal/client.go
Use `rlspb` for messages and `rlsgrpc` for services
> rls: double import rls protos

- internal/balancergroup/balancergroup.go
- internal/balancergroup/balancergroup_test.go
This is required for the RLS LB policy. At pick time, if the RLS picker
finds one of its child policies in IDLE, it needs to be able to ask it
to exit idle.
> balancergroup: add method to exitIdle a sub-balancer

- xds/googledirectpath/googlec2p.go
- xds/googledirectpath/googlec2p_test.go
Default client resource scheme should be %s, otherwise the client will watch an empty string LDS resource.
> xds/c2p: fix default client resource template, and xds-client target scheme

- test/kokoro/xds.sh
> xds/kokoro: install go 1.17, and retry go build

- credentials/google/google.go
- credentials/google/google_test.go
- creds/google: add NewDefaultCredentialsWithOptions() to support custom per-RPC creds (#4767, #4830)
> backport PRs to v1.40.x

- xds/internal/balancer/clustermanager/clustermanager_test.go
This PR aims to fix a possible nil before casting to error.
```
--- FAIL: TestClusterManagerForwardsBalancerBuildOptions (1.00s)
panic: interface conversion: interface is nil, not error [recovered]
panic: interface conversion: interface is nil, not error
goroutine 93 [running]:
testing.tRunner.func1.2(0xceec40, 0xc00020f230)
/usr/local/go/src/testing/testing.go:1143 +0x335
testing.tRunner.func1(0xc0003be280)
/usr/local/go/src/testing/testing.go:1146 +0x4c2
panic(0xceec40, 0xc00020f230)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
google.golang.org/grpc/xds/internal/balancer/clustermanager.TestClusterManagerForwardsBalancerBuildOptions(0xc0003be280)
/fuzz/target/xds/internal/balancer/clustermanager/clustermanager_test.go:635 +0x68f
testing.tRunner(0xc0003be280, 0xe8bbb0) …
```
> fix possible nil before casting

- xds/internal/xdsclient/bootstrap/bootstrap.go
- xds/internal/xdsclient/bootstrap/bootstrap_test.go
This string representation of the server config will be used as map
keys, so that xds client can be shared by authorities with the same
config.
Also exported a field so it can be set by tests.
> xds/bootstrap_config: add a string function to server config

- balancer/rls/internal/keys/builder.go
- balancer/rls/internal/keys/builder_test.go
- balancer/rls/internal/picker.go
https://github.com/grpc/grpc-proto/pull/92 added new fields `extra_keys` (to include `host`, `service` and `method` keys) and `constant_keys` (which are added to every request). This PR adds supports for those fields in our keyBuilder implementation.
The changes in `picker` in this PR are the ones minimally required to get things to build and are only a subset of the upcoming changes. 
> rls: support extra_keys and constant_keys

- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/resolver/cluster_specifier_plugin_test.go
- xds/internal/resolver/serviceconfig.go
- xds/internal/resolver/watch_service.go
- xds/internal/resolver/xds_resolver.go
- xds/internal/resolver/xds_resolver_test.go
This PR adds support for cluster specifier specifier plugins in the xds resolver/config selector, as per RLS in xDS design. The functionality still left to implement is the RLS Cluster Specifier Plugin.
> xds/resolver: Add support for cluster specifier plugins

- internal/balancergroup/balancergroup.go
`incomingMu` needs to be taken before accessing `scToSubBalancer` map as part of `exitIdle`
> internal/balancergroup: eliminate race in exitIdle

- test/kokoro/xds_v3.cfg
For the past few weeks three failures due to 120 min test timeout, and nearly every run successful was close to 120 min.
> [v1.37.x] Increase xDS v3 interop Kokoro timeout

- grpclog/loggerv2.go
- internal/grpclog/grpclog.go
The documentation comments stated that arguments were handled like
fmt.Print, when they are actually handled like fmt.Println. For
example, the "fallback" implementation in
internal/grpclog/grpclog.go for InfoDepth calls Logger.Infoln.
> grpclog.DepthLoggerV2: Correct comment: formats like fmt.Println

- internal/envconfig/xds.go
- xds/googledirectpath/googlec2p.go
> Backport "xds/c2p: replace C2P resolver env var with experimental scheme suffix #5044" to 1.43.x

- xds/internal/xdsclient/controller/transport.go
fixes #5020
RELEASE NOTES:
* xds/client:notify watchers of errors creating new xDS stream
> xds/client: send NewStream errors to the watchers

- internal/transport/http2_client.go
> transport: better error message when per-RPC creds fail

- xds/internal/xdsclient/controller/controller_test.go
- xds/internal/xdsclient/xdsclient_test.go
These tests covers that `New()` verifies the input `ServerConfig` is
valid. This is actually done by `controller.New` not `xdsclient.New`.
Also, with federation, `xdsclient.New` will not create the controllers
immediately (it will wait for a watch to create the corresponding
controller).
> xds/client: move xdsclient.New tests to controller.New

- balancer/roundrobin/roundrobin_test.go
* replace deprecated grpc.WithInsecure with insecure.NewCredentials
* replace deprecated grpc.WithBalancerName with grpc.WithDefaultServiceConfig
* remove redundant err nil checking
> test: cleanup roundrobin_test

- internal/envconfig/xds.go
- xds/internal/xdsclient/xdsresource/unmarshal_rds.go
- xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
This PR adds an env var for RLS in xDS, protecting the cluster specifier plugin parsing functionality in xdsclient and also the RLS Cluster Specifier Plugin itself.
> xds: Added env var for RLS in xDS

- authz/rbac_translator.go
- authz/rbac_translator_test.go
- authz/sdk_end2end_test.go
- internal/grpcutil/regex.go
- internal/grpcutil/regex_test.go
In SDK authorization policy, "*" value represents presence match i.e. it will match when the value is not empty. This PR fixes presence match. Additionally, it updates underlying regex code to correctly handle match with empty string values.
RELEASE NOTES:
- authz: fixes regex expression match
> authz: fix regex expression match

- xds/internal/xdsclient/pubsub/update.go
#5020
RELEASE NOTES:
* xds/client: notify all resource watchers of connection errors
> xds/client: send connection errors to all watchers

- clientconn_test.go
If test failed at log like following:
```
clientconn_test.go:xxx: Dial(127.0.0.1:34491, _) = _, context deadline exceeded, want _, <nil>
```
goroutine will be blocked at 
```go
go func() {
...
<-connected
...
}
```
```
goroutine 8 [chan receive]:
google.golang.org/grpc.TestClientUpdatesParamsAfterGoAway.func1(0xab6d80, 0xc00000c8b8, 0xc0002c0a00, 0xc000028900)
/fuzz/target/clientconn_test.go:978 +0x30f
created by google.golang.org/grpc.TestClientUpdatesParamsAfterGoAway
/fuzz/target/clientconn_test.go:956 +0x212
--- FAIL: TestClientUpdatesParamsAfterGoAway (5.00s)
FAIL
```
> testing: fix goroutine leak in TestClientUpdatesParamsAfterGoAway

- balancer/rls/rls.go
- xds/internal/clusterspecifier/rls/rls.go
- xds/internal/clusterspecifier/rls/rls_test.go
This PR adds the RLS Cluster Specifier Plugin. This is branched off #4987. The RLS Cluster Specifier Plugin will not be functional until the RLS LB Policy itself gets completed, as right now the call into the RLS LB Policies ParseConfig() for validation purposes is commented out.
> xds: Add RLS Cluster Specifier Plugin

- interop/grpclb_fallback/client_linux.go
We are setting up fallback test based on TD, and we need to add xds dependency to the fallback test client.
> xds: Add xds dependency to the fallback test client

- interop/grpclb_fallback/client_linux.go
Remove "WithBlock" from the fallback test client as it is not compatible with RING_HASH policy used by XDS.
> xds: Remove WithBlock option from the fallback test client

- balancer/rls/internal/builder.go
- balancer/rls/internal/config.go
- balancer/rls/internal/config_test.go
- enforce a max cache size of 5MB
- 64-bit align the cacheSizeBytes field in the lbConfig struct
- minor changes to comments and error messages
> rls: minor config processing changes

- internal/resolver/config_selector_test.go
If line 121 timeout happened first, there is no receiver for this channel. Thus, the goroutine created at line 116 blocks at the last send operation. 
> internal/resolver: fix possible goroutine leak in TestSafeConfigSelector

- dialoptions.go
Current document asks to replace `WithInsecure()` with `insecure.NewCredentials()`.
But it causes confusion because function signatures for `WithInsecure()` and `insecure.NewCredentials()` are different.
Instead, using `insecure.NewCredentials()` as a parameter for `WithTransportCredentials` replicate the deprecated `WithInsecure` function.
So I propose a minor improvement to mention `WithTransportCredentials` in the comment.
> grpc: minor improvement on WithInsecure() document

- balancer/grpclb/grpclb_test.go
If previous testC.EmptyCall failed, which caused error like
```
EmptyCall(_, _) = _, rpc error: code = DeadlineExceeded desc = context deadline exceeded, want _, <nil>
```
Next p.Addr could be nil.
--- FAIL: TestDropRequest (11.01s)
panic: interface conversion: net.Addr is nil, not *net.TCPAddr [recovered]
panic: interface conversion: net.Addr is nil, not *net.TCPAddr
goroutine 21 [running]:
testing.tRunner.func1.2(0x8ff3c0, 0xc000282660)
/usr/local/go/src/testing/testing.go:1143 +0x335
testing.tRunner.func1(0xc000276c80)
/usr/local/go/src/testing/testing.go:1146 +0x4c2
panic(0x8ff3c0, 0xc000282660)
/usr/local/go/src/runtime/panic.go:965 +0x1b9
google.golang.org/grpc/balancer/grpclb.TestDropRequest(0xc000276c80)
/fuzz/target/balancer/grpclb/grpclb_test.go:831 +0x23dc …
> grpclb: fix possible nil before conversion in TestDropRequest

- credentials/insecure/insecure.go
In https://github.com/grpc/grpc-go/pull/4718, the `insecure` package was used to implement `WithInsecure()` among others and it was suggested that `insecure.NewCredentials()` should be used instead. However, the `insecure` package still contains a notice that its status is experimental. I believe that notice can be deleted now.
RELEASE NOTES:
* credentials/insecure: remove experimental status of package
> insecure: remove experimental notice

- test/kokoro/xds.sh
> test/kokoro: Use xds-test-server-5 as the GCE interop server

- dialoptions.go
This is a trivial PR to fix a typo in the godoc for the `WithBlock()` dialoption.
> dialoptions.go: Fix WithBlock godoc

- test/kokoro/xds.sh
> test/kokoro: use xds-test-server-5 as GCE interop image (backport v1.36.x)

- test/kokoro/xds.sh
> test/kokoro: use xds-test-server-5 as GCE interop image (backport v1.34.x)

- test/kokoro/xds.sh
> test/kokoro: use xds-test-server-5 as GCE interop image (backport v1.35.x)

- test/kokoro/xds.sh
> test/kokoro: use xds-test-server-5 as GCE interop image (backport v1.37.x)

- test/kokoro/xds.sh
> test/kokoro: use xds-test-server-5 as GCE interop image (backport v1.38.x)

- test/kokoro/xds.sh
> test/kokoro: use xds-test-server-5 as GCE interop image (backport v1.39.x)

- test/kokoro/xds.sh
> test/kokoro: use xds-test-server-5 as GCE interop image (backport v1.40.x)

- test/kokoro/xds.sh
> test/kokoro: use xds-test-server-5 as GCE interop image (backport v1.41.x)

- test/kokoro/xds.sh
> test/kokoro: use xds-test-server-5 as GCE interop image (backport v1.42.x)

- authz/rbac_translator.go
- authz/rbac_translator_test.go
- authz/sdk_end2end_test.go
With the changes in this PR, allow authenticated can be represented using `principals: ["*", ""]` instead of `principals: []`.
This way we can avoid special semantics.
Related discussion
https://github.com/grpc/proposal/pull/246#discussion_r756496245
RELEASE NOTES:
- authz: update representation of allow authenticated in SDK
> authz: update representation of allow authenticated in SDK

- test/kokoro/xds.sh
> test/kokoro: use xds-test-server-5 as GCE interop image (backport v1.43.x)

- credentials/google/google_test.go
> credentials/google: use grpctest.Tester for tests in this package

- clientconn_test.go
This PR aims to fix possible goroutine leak in TestUpdateAddresses_RetryFromFirstAddr.
=== RUN   TestUpdateAddresses_RetryFromFirstAddr
clientconn_test.go:xxxx: timed out waiting for server1 to be contacted
clientconn_test.go:xxxx: accept tcp 127.0.0.1:32795: use of closed network connection
```
goroutine 10 [chan receive]:
google.golang.org/grpc.TestUpdateAddresses_RetryFromFirstAddr.func1(0xab6d80, 0xc00000c888, 0xc0002c0a00, 0xc00002a880, 0xc00002a900)
/fuzz/target/clientconn_test.go:1309 +0x205
created by google.golang.org/grpc.TestUpdateAddresses_RetryFromFirstAddr
/fuzz/target/clientconn_test.go:1287 +0x60a
```
Any fatal happened later, like following example:
```
select {
case <-server1ContactedFirstTime:
case <-timeout:
t.Fatal("timed out waiting for server1 to be contacted")
} …
```
> test: fix potential goroutine leak in TestUpdateAddresses_RetryFromFirstAddr

- attributes/attributes.go
fixes #5101
RELEASE NOTES:
* attributes: document that some value types (e.g. `map`s) must implement Equal
> attributes: document that some value types (e.g. `map`s) must implement Equal

- internal/xds/bootstrap.go
- xds/internal/test/xds_client_federation_test.go
- xds/internal/testutils/testutils.go
- xds/internal/xdsclient/authority_test.go
- xds/internal/xdsclient/watchers_federation_test.go
- xds/internal/xdsclient/watchers_test.go
Also moved func `BuildResourceName` to testutils to be shared
> xds/federation: e2e tests

- credentials/google/google.go
- credentials/google/google_test.go
Fixes https://github.com/grpc/grpc-go/issues/5091
The `oauth` package, as part of checking whether it is running on GCE,
creates a persistent connection to the metadata server. This persistent
connection spawns a couple of goroutines, one to read and one to write.
And these goroutines show up in our leakchecker.
We are not testing perRPC credentials in this test and can safely stub
out the `oauth` package to make the leakchecker happy.
> credentials/google: stub out the oauth package in test

- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/clusterresolver/clusterresolver_test.go
- xds/internal/balancer/clusterresolver/configbuilder.go
- xds/internal/balancer/clusterresolver/configbuilder_test.go
DNS child policies also need the cluster name, because the cluster name are attached to the addresses, which may affect creds handshake.
RELEASE NOTES:
* xds/clusterresolver: fix that DNS child does wrong creds handshake because ClusterName isn't set correctly.
> xds/clusterresolver: set ClusterName for DNS child

- examples/helloworld/greeter_client/main.go
- examples/route_guide/client/client.go
Current document asks to replace WithInsecure() with insecure.NewCredentials(), so I updated example code.
cf) https://github.com/grpc/grpc-go/pull/5068
> examples: use insecure.NewCredentials() instead of grpc.WithInsecure()

- internal/wrr/random.go
- internal/wrr/wrr_test.go
This PR improves `randomWRR.Next` performance by
1. using binary search when weights are not equal
2. picking item randomly when weights are equal
In general, this PR performs better than current implementation and has a more stable performance characteristics while the previous approach is more sensitive to weights distribution but it works better in some cases (i.e. small number of items with different weights)
> wrr:  improve randomWRR performance

- xds/internal/xdsclient/controller/controller.go
- xds/internal/xdsclient/controller/controller_test.go
This feature can be used control xDS client behavior through a Dial
interceptor set from users.
Users can SetDialInterceptor on the controller package to intercept the
grpc.Dial call and inject/modify the target or the options.
ResetDialInterceptor can be used to reset and set the dialler back to
grpc.Dial.
Both of these calls will only take affect if they are called before the
controller is created using New.
> xdsclient: allow overriding grpc.Dial function for the xDS controller.

- test/kokoro/psm-security.cfg
Backports #5132 
@easwars
---
Recent runs for the entire xds_k8s test suite takes
around 110 minutes, and one run exceeds the deadline.
No obvious regression was found.
Before we have more concrete improvement,
this PR increases the timeout to stop similar flakes.
> test/kokoro: set psm-security test timeout to 3h

- internal/transport/transport_test.go
This PR is mainly for 2 following issues:
1. concurrent map access
```
fatal error: concurrent map read and map write
goroutine 35 [running]:
runtime.throw(0x8bb64d, 0x21)
/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0003cf8f8 sp=0xc0003cf8c8 pc=0x441f12
runtime.mapaccess1_fast32(0x838d40, 0xc0000545a0, 0xc00000000d, 0xc0003cfe30)
/usr/local/go/src/runtime/map_fast32.go:21 +0x196 fp=0xc0003cf920 sp=0xc0003cf8f8 pc=0x414956
google.golang.org/grpc/internal/transport.testFlowControlAccountCheck(0xc0002a2000, 0x100000, 0xc0000000a00000, 0x80000000600000)
/repos/grpc-go/internal/transport/transport_test.go:2160 +0x954 fp=0xc0003cff38 sp=0xc0003cf920 pc=0x7ceeb4
google.golang.org/grpc/internal/transport.TestAccountCheckWindowSizeWithLargeWindow(0xc0002a2000) …
```
> testing: fix potential problems in testFlowControlAccountCheck

- balancer/rls/control_channel_test.go
Fixes https://github.com/grpc/grpc-go/issues/5145.
[UnaryHandler](https://pkg.go.dev/google.golang.org/grpc#UnaryHandler) says:
```
If a UnaryHandler returns an error, it should be produced by the status package, or else 
gRPC will use codes.Unknown as the status code and err.Error() as the status message of the RPC.
```
Since we were not returning an error produced by the `status` package, the test was sometimes seeing errors with `codes.Unknown` instead of the expected `codes.DeadlineExceeded`. This fix should take care of the flakiness.
> rls: return status error from server interceptor in test

- examples/helloworld/greeter_server/main.go
This PR changes the address that the helloworld greeter_server is
listening to from "localhost:<port>" to just ":<port>", thus enabling
the server to be used in setups where the request stem from another
host.
> Let helloworld example listen to all hosts 

- balancer/grpclb/grpclb.go
- balancer/grpclb/grpclb_config.go
- balancer/grpclb/grpclb_config_test.go
- balancer/grpclb/grpclb_test.go
- balancer/rls/config_test.go
The field in the LB policy config which identifies the target was initially named `targetName` in the design doc. But when the service config proto change was made, it was renamed to `serviceName`. This update wasn't propagated to the design doc at the time. Java/C have used `serviceName`.
> grpclb: rename LB policy config field to `serviceName`

- xds/internal/xdsclient/bootstrap/bootstrap.go
- xds/internal/xdsclient/bootstrap/bootstrap_test.go
> xds/bootstrap: escape authority when populating resource name template

- interceptor.go
- server.go
- stream.go
- test/server_test.go
fixes #5155
RELEASE NOTES:
* server: convert context errors returned by service handlers to status with the correct status code (`Canceled` or `DeadlineExceeded`), instead of `Unknown`
> server: handle context errors returned by service handler

- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/clusterimpl/balancer_test.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/balancer/clusterimpl/config.go
- xds/internal/balancer/clusterimpl/config_test.go
- xds/internal/balancer/clusterresolver/config.go
- xds/internal/balancer/clusterresolver/config_test.go
- xds/internal/balancer/clusterresolver/configbuilder.go
- xds/internal/balancer/clusterresolver/configbuilder_test.go
- xds/internal/testutils/fakeclient/client.go
- xds/internal/xdsclient/attributes.go
- xds/internal/xdsclient/authority.go
- xds/internal/xdsclient/bootstrap/bootstrap.go
- xds/internal/xdsclient/bootstrap/bootstrap_test.go
- xds/internal/xdsclient/controller/loadreport.go
- xds/internal/xdsclient/controller/v2_cds_test.go
- xds/internal/xdsclient/loadreport.go
- xds/internal/xdsclient/loadreport_test.go
- xds/internal/xdsclient/xdsresource/name.go
- xds/internal/xdsclient/xdsresource/type_cds.go
- xds/internal/xdsclient/xdsresource/unmarshal_cds.go
- xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
- update xdsclient's LoadReport method to take a ServerConfig instead of just a string
- update clusterresolver and clusterimpl balancer config to take a full ServerConfig as LRS server
- update CDS resource update LRS server field from a string to an enum (can be make an interface to support more types later)
- update CDS balancer to read ServerConfig from xdsclient bootstrap and populate child policy config
- cleanup bootstrap config json handling so the struct can be reused
- change json unmarshal from taking a list (this is what used in bootstrap json) to taking an item
RELEASE NOTES:
* xds: support federation
> xds/federation: support federation in LRS

- xds/internal/xdsclient/xdsresource/unmarshal_cds.go
- xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
- xds/internal/xdsclient/xdsresource/unmarshal_lds.go
- xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
RELEASE NOTES:
* xds/resource: accept Self as LDS's RDS config source and CDS's EDS config source
> xds/resource: accept Self as LDS's RDS config source and CDS's EDS config source

- balancer/rls/balancer.go
- balancer/rls/balancer_test.go
- balancer/rls/config.go
- balancer/rls/config_test.go
- balancer/rls/control_channel.go
- balancer/rls/control_channel_test.go
- balancer/rls/helpers_test.go
- balancer/rls/internal/test/e2e/rls_lb_config.go
- internal/internal.go
- service_config.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/resolver/cluster_specifier_plugin_test.go
- xds/internal/resolver/xds_resolver_test.go
- Add `routeLookupChannelServiceConfig` to RLS LB policy's service config to serve as the service config for the control channel
- This will make it possible for the control channel to be used in directpath deployments with grpclb and TD
- Unit tests for config validation
- E2E test to ensure that the injected service config gets used for the control channel
Also, renamed `internal.ParseServiceConfigForTesting` to `internal.ParseServiceConfig` so that it can be used to parse and validate the specified service config.
> rls: support `routeLookupChannelServiceConfig` field

- internal/leakcheck/leakcheck.go
> leakcheck: ignore http read/write goroutine

- cmd/protoc-gen-go-grpc/grpc.go
This PR adds a hook which users can implement and insert helper codes to the codegen, eg service renaming.
> cmd/protoc-gen-go-grpc: add hooks to allow overriding generated code

- examples/route_guide/README.md
> Format directory/file references

- internal/transport/transport.go
- internal/transport/transport_test.go
Adds an `Unwrap` method to enable error checking with `errors.Is`.
> transport: Add an Unwrap method to ConnectionError

- internal/envconfig/xds.go
- xds/internal/resolver/xds_resolver.go
- xds/internal/xdsclient/bootstrap/bootstrap.go
- xds/internal/xdsclient/singleton.go
- xds/server.go
- xds/server_options.go
- xds/xds.go
- Make testing only functions more explicit by using `ForTesting` suffix in their name
- Make a testing only server option explicit by using the `ForTesting` suffix in its name
- Clarify some comments, fix typos etc
> xds: minor cleanup in xdsclient bootstrap code

- reflection/serverreflection.go
- reflection/serverreflection_test.go
This updates the server reflection implementation in two key ways:
1. Support alternate source of descriptors, like for RPC servers that get their descriptors dynamically and are dynamic proxies.
* Instead of always getting descriptors from the set of global registered files (when generated code is linked into the calling program), this allows caller to supply custom resolvers.
* This also allows caller to supply a set of service names instead of supplying a `*grpc.Server`.
2. Use the new protobuf API v2 stuff to get the descriptors, which is much more sane than the old APIs.
* This allows much of the code to be eliminated since standard APIs now support symbol and descriptor lookup.
* The potential downside of this simplification is that encoded descriptors (pre-serialized to bytes) are …
> reflection: improve server implementation

- xds/internal/clusterspecifier/rls/rls.go
- xds/internal/clusterspecifier/rls/rls_test.go
This is required for copybara rules which will point to the canonical copy of the proto in google3.
> xds: rename rls proto import

- balancer/balancer.go
- balancer/grpclb/grpclb_remote_balancer.go
- balancer_conn_wrappers.go
- call_test.go
- channelz/channelz.go
- channelz/service/service_sktopt_test.go
- channelz/service/service_test.go
- clientconn.go
- dialoptions.go
- internal/balancergroup/balancergroup_test.go
- internal/channelz/funcs.go
- internal/channelz/id.go
- internal/channelz/logging.go
- internal/channelz/types.go
- internal/transport/http2_client.go
- internal/transport/http2_server.go
- internal/transport/keepalive_test.go
- internal/transport/transport.go
- internal/transport/transport_test.go
- resolver/resolver.go
- resolver_conn_wrapper.go
- server.go
- test/channelz_test.go
- xds/internal/balancer/clustermanager/clustermanager_test.go
- channelz package
- Define an opaque `Identifier` to uniquely identify entities in the channelz database.
- This type will be returned from `RegisterXxx` functions and will be accepted by log/trace functions.
- Make `RegisterXxx` and `RemoveEntry` functions work gracefully when channelz is not turned ON. 
- logging functions will prefix channel identifiers to all log messages
- Change the `WithChannelzParentID` dialoption to accept a `*channelz.Identifier`.
- Change `ChannelzParentID` field in balancer.BuildOptions to be of type `*channelz.Identifier`.
- Define a type alias in the external channelz package pointing to the identifier type defined in internal channelz package. This is required since the channelz identifier can be specified through a `DialOption` and …
> channelz: include channelz identifier in logs

- channelz/service/service_test.go
These were flagged in the latest import.
> channelz: replace deprecated timestamp API with recommended ones

- balancer_switching_test.go
- clientconn.go
- clientconn_state_transition_test.go
- clientconn_test.go
- dialoptions.go
- test/balancer_test.go
- test/end2end_test.go
- test/healthcheck_test.go
- Deleted the `WithBalancerName()` API which has been deprecated for ages now.
- This simplifies code in the `ClientConn` since we no longer need to handle special cases around balancer name being specified through a dial option
- Test cleanups
- Use `WithDefaultServiceConfig` instead of `WithBalancerName` wherever applicable
- Use `WithTransportCredentials(insecure.NewCredentials())` instead of `WithInsecure()` in tests already touched by the above change
- Use `defaultTestTimeout` wherever applicable
- Turn `setupClient` and `setupServer` functions into test helpers and significantly reduce boiler plate in individual tests in `healthcheck_test.go`
RELEASE NOTES:
- grpc: delete `WithBalancerName()` API, deprecated over 4 years ago in #1697
> grpc: delete deprecated API WithBalancerName()

- balancer_conn_wrappers.go
- clientconn.go
If the name resolver returns an invalid service config, and if there is no current service config on the channel, this PR attempts to apply the default service config, if one is available. 
This aligns grpc-go with https://github.com/grpc/proposal/blob/master/A21-service-config-error-handling.md, specifically [#4.2](https://github.com/grpc/proposal/blob/master/A21-service-config-error-handling.md)
This PR also makes the following changes:
- handle `nil` receiver in `ccBalancerWrapper`
- remove `cc.balancerWrapper != nil` checks before calling methods on the balancerWrapper
- use `cc.sc != nil` as the condition representing presence of current service config instead of `cc.balancerWrapper != nil`
RELEASE NOTES:
- handle invalid service configs by applying the default, if applicable
> grpc: handle invalid service configs by applying the default, if applicable

- interop/xds/server/server.go
- xds/internal/server/listener_wrapper.go
- xds/internal/test/xds_server_integration_test.go
- xds/internal/test/xds_server_serving_mode_test.go
- xds/server.go
- xds/server_test.go
- Suppress redundant mode changes in the `listenerWrapper`
- Throw a log entry from the xDS server *if and only if* a mode change callback is not registered
- Throw a single log entry from the mode change callback registered by the xDS interop server
Test changes:
- Register a mode change callback from integration tests to get around our testLogger failing the test
- Replace some calls to `t.Errorf()` with `t.Fatalf()`
Fixes https://github.com/grpc/grpc-go/issues/4939
> xds: avoid log spam during server mode switches (better A36 compliance)

- internal/balancergroup/balancergroup.go
- xds/internal/balancer/clusterresolver/priority_test.go
This PR is a logical no-op and doesn't change any current flow. However, this sets up my future PR with the blobs of functionality of a. the decision to make the graceful switch for a child (I think best to leave up to the caller) and b. the actual plumbing in the balancer group and subBalancerWrapper which would call SwitchTo a second time triggering the Graceful Switch.
> balancergroup: Switched subBalancerWrapper to wrap a gracefulswitch.Balancer

- interop/grpclb_fallback/client_linux.go
Similar to https://github.com/grpc/grpc-java/pull/8989 and https://github.com/grpc/grpc/pull/29126 but for Go
> interop/client: simplify fallback test client and parameterize fallback deadline

- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.cfg
This test is only enabled for C++ and Python for now: https://github.com/grpc/grpc/blob/master/tools/internal_ci/linux/grpc_xds_k8s_lb.sh
This PR enables it for grpc-go as well.
> xds/interop: add xds_k8s_lb test suite

- internal/binarylog/binarylog.go
- internal/binarylog/binarylog_test.go
- internal/binarylog/method_logger.go
- internal/binarylog/method_logger_test.go
- stream.go
As discussed offline, we want to utilize the pre-existing state-storing object `MethodLogger` for gRPC Observability. This object has the same life span as each RPC, and we can conveniently store extra context information about the RPC in it to generate better logs.
Child PR: https://github.com/grpc/grpc-go/pull/5196 
> binarylog: generalize binarylog's MethodLogger preparing for new observability features

- internal/googlecloud/googlecloud.go
- internal/googlecloud/googlecloud_test.go
- internal/googlecloud/manufacturer.go
- internal/googlecloud/manufacturer_linux.go
- internal/googlecloud/manufacturer_windows.go
The fact that the Powershell command for Windows was part of
googlecloud.go tripped up a Google-internal code scanner. Refactor the
logic into OS-specific files and simplify it. The tests no longer depend
on overwriting package-global variables.
> internal/googlecloud: refactor OS-dependent code

- balancer_conn_wrappers.go
This PR adds a comment explaining why `updateClientConnState` is handled inline in the `ccBalancerWrapper` while other methods from grpc are handled asynchronously by pushing them onto a channel.
> grpc: add a comment to balancer_conn_wrapper

- internal/transport/http2_server.go
- internal/transport/keepalive_test.go
Implements proposal A18 (https://github.com/grpc/proposal/blob/master/A18-tcp-user-timeout.md).
Currently, TCP_USER_TIMEOUT can only be set on gRPC golang client. 
The A18 proposal doesn't mention this should be restricted clients and the C-Core implementation does set TCP_USER_TIMEOUT on gRPC server (https://github.com/grpc/grpc/pull/16419/files#diff-b3242d6753e5e0f631f2aed3fc352e2f491696f5107ab2f1cc61d85b7926a192R169-R170)
So this PR adds the server part of https://github.com/grpc/grpc-go/pull/2307 and sets TCP_USER_TIMEOUT in the server transport.
RELEASE NOTES:
- Support setting `TCP_USER_TIMEOUT` on `grpc.Server` connections using `keepalive.ServerParameters.Time`
> server: set TCP_USER_TIMEOUT socket option for linux

- balancer/rls/balancer.go
- internal/internal.go
- xds/internal/clusterspecifier/rls/rls.go
- xds/internal/clusterspecifier/rls/rls_test.go
- xds/xds.go
- Introduce a const in the `internal` package to hold the name of the RLS LB policy
- Refer to this name from the actual package implementing the LB policy and from the xds cluster specifier package
Why do we need this?
- This change makes it clear/simple what needs to be imported:
- When one needs to use the RLS lb policy, they need to import the `balancer/rls` pacakge (whether they want to use RLS as a standalone LB policy or they want to use RLS in the context of xDS)
- Include the RLS cluster specifier in the list of packages imported by the externally visible `xds` package 
- The implementation of the cluster specifier for RLS imports the `rls` package solely for the purpose of referring to the name of the RLS LB policy. Putting the name in the `internal` package …
> make the RLS LB policy name available in the internal package

- xds/internal/server/listener_wrapper.go
#5215 made changes to avoid log spam as a result of changes to the xdsServer's serving mode. But it also suppressed more updates than it should have. This PR addresses the issue raised in https://github.com/grpc/grpc-go/pull/5215#issuecomment-1071555329.
Fixes https://github.com/grpc/grpc-go/issues/4939
> xds: suppress redundant updates only when we are SERVING

- metadata/metadata.go
https://github.com/grpc/grpc-go/commit/32d5490aee8dd29a6fbfe75dc8caade5b6aa5d87#commitcomment-69226467
RELEASE NOTES:
* metadata: make a copy of the value slices in FromContext() functions so that modifications won't be made to the original copy
> metadata: copy slices in FromContext() functions

- test/clientconn_test.go
Earlier, we had two tests for this same scenario:
- In the `round_robin` tests (removed in #5236) 
- In the `pick_first` tests (removed in #5263)
None of the above two tests were in the appropriate location because the functionality being tested here does not depend on what LB policy is configured on the channel.
Hence this test is being moved out into a standalone `ClientConn` test.
> test: add a test for clientConn close with pending RPC

- internal/testutils/lbcfg.go
- test/channelz_test.go
- test/config_selector_test.go
- test/end2end_test.go
- test/healthcheck_test.go
- test/parse_config.go
> test: use `t.Fatal` instead of `panic` for service config parsing errors

- internal/balancergroup/balancergroup.go
- internal/balancergroup/balancergroup_test.go
This PR adds the functionality of being able to start the Graceful Switch process for a child of the balancer group. This is branched off #5245.
> balancergroup: Add trigger point to gracefully switch a child

- security/advancedtls/crl.go
- security/advancedtls/crl_test.go
There was a recent discussion in removing the usage of CDP(CRL Distribution Points) in the gRPC CRL enforcement. We originally kept that variable for the purpose of keeping alignment with the RFC. The recent discussion pointed out that there was no need for doing that. Also, the current C++ implementation doesn't have that as well. We should keep the behavior consistent across languages. 
> advancedtls: remove the usage of CDP in CRL enforcement

- test/roundrobin_test.go
I had taken the stats handler approach when I first wrote this test. But after writing this test, I wrote two other tests where I've used channelz instead to determine RPC count. I like it better. Hence this change.
> test: use channelz instead of stats handler to determine RPC count

- clientconn_parsed_target_test.go
This test was actually validating `url.Parse`'s behavior to an extent, by explicitly checking the entire `URL` field.  With this change, we will instead fill in the expectation by calling `url.Parse` in the test.
This turned out to be a little trickier than I anticipated, because when there is a malformed target string or a target string without a registered scheme, we re-run `url.Parse` with the default scheme and `:///` prepended.
cc @ianlancetaylor FYI
> clientconn: fix target parsing tests to be tolerant to new url.URL field OmitHost

- picker_wrapper_test.go
- pickfirst.go
- test/balancer_test.go
- test/pickfirst_test.go
This behavior is in line with what other languages do and what we should have been doing all along.
- In the `pick_first` LB policy implementation, if a resolver address removes previously provided addresses, delete the existing subConn and move channel to `TransientFailure`. 
- Get rid of `TestEmptyAddrs`, which is no longer required because we have tests in `test/pickfirst_test.go` and `test/roundrobin_test.go` for this scenario. Also, `TestEmptyAddrs` was broken anyway.
- Add a test in `test/pibkfirst_test.go` to exercise this functionality.
RELEASE NOTES:
- Change connectivity state to `TransientFailure` in `pick_first` LB policy when all addresses are removed
> grpc: move to `TransientFailure` in `pick_first` LB policy when all addresses are removed

- xds/internal/balancer/clustermanager/clustermanager.go
- xds/internal/balancer/clustermanager/clustermanager_test.go
This PR adds the Graceful Switch functionality to Cluster Manager. This is branched off #5251.
> cluster manager: Add Graceful Switch functionality to Cluster Manager

- xds/internal/xdsclient/authority.go
- xds/internal/xdsclient/client_test.go
- xds/internal/xdsclient/controller.go
- xds/internal/xdsclient/controller/controller.go
- xds/internal/xdsclient/controller/controller_test.go
- xds/internal/xdsclient/controller/transport.go
- xds/internal/xdsclient/controller/v2_testutils_test.go
Also: receiving from a stopped timer channel is unnecessary unless the timer is going to be reused via `Reset`.
RELEASE NOTES:
* xds: the xds client will now apply a 1 second backoff before recreating ADS or LRS streams
> xdsclient: always backoff between new streams even after successful stream

- balancer_conn_wrappers.go
- clientconn.go
- clientconn_test.go
- internal/balancer/gracefulswitch/gracefulswitch.go
- internal/balancer/stub/stub.go
- test/balancer_switching_test.go
- test/resolver_update_test.go
- test/roundrobin_test.go
This PR changes the default behavior of `ClientConn` when it ends up switching the LB policy. 
- Earlier, it used to close the old policy and start the new one, when it received a service config update pointing to a new LB policy. 
- Now, it uses the [gracefulswitch.Balancer](https://github.com/grpc/grpc-go/blob/99aae3442dbe8495247dda07a6b1c8cda98accca/internal/balancer/gracefulswitch/gracefulswitch.go#L46) to gracefully switch from the old balancer to the new one.
Summary of code changes:
- Use a `gracefulswitch.Balancer` in `ccBalancerWrapper` instead of `balancer.Balancer`
- Add a `switchTo` method to the balancer wrapper which calls `SwitchTo` on the `gracefulswitch.Balancer` 
- Ensure calls from grpc to the underlying balancers are ordered
- For every type of update from grpc, we now …
> grpc: perform graceful switching of LB policies in the `ClientConn` by default

- test/kokoro/xds.sh
1.37 xds tests are failing with 
```
/home/kbuilder/gopath/pkg/mod/[golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/client_conn_pool.go:302:6](https://www.google.com/url?q=http://golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/client_conn_pool.go:302:6&sa=D): undefined: errors.Is
/home/kbuilder/gopath/pkg/mod/[golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/transport.go:417:30](https://www.google.com/url?q=http://golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/transport.go:417:30&sa=D): undefined: errors.Is
/home/kbuilder/gopath/pkg/mod/[golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/transport.go:417:45](https://www.google.com/url?q=http://golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/transport.go:417:45&sa=D): undefined: …
```
> [v1.37.x] xds/kokoro: install go 1.17, and retry go build (#5015)

- test/kokoro/xds.sh
1.38 xds tests are failing with 
```
/home/kbuilder/gopath/pkg/mod/[golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/client_conn_pool.go:302:6](https://www.google.com/url?q=http://golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/client_conn_pool.go:302:6&sa=D): undefined: errors.Is
/home/kbuilder/gopath/pkg/mod/[golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/transport.go:417:30](https://www.google.com/url?q=http://golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/transport.go:417:30&sa=D): undefined: errors.Is
/home/kbuilder/gopath/pkg/mod/[golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/transport.go:417:45](https://www.google.com/url?q=http://golang.org/x/net@v0.0.0-20220127200216-cd36cc0744dd/http2/transport.go:417:45&sa=D): undefined: …
```
> [v1.38.x] xds/kokoro: install go 1.17, and retry go build (#5015)

- .github/workflows/testing.yml
- interop/client/client.go
- interop/interop_test.sh
- interop/server/server.go
> interop: build client without timeout; add logs to help debug failures

- cmd/protoc-gen-go-grpc/grpc.go
We are supporting the service renaming by using a global variables which will cause issues in some scenarios.
This change allows us to modify the ClientConn interface and handlers, which allows us to store the renamed service name by each clientconn. This matches how the internal service renaming is implemented.
> cmd/protoc-gen-go-grpc: allow hooks to modify client structs and service handlers

- internal/transport/http2_server.go
- test/end2end_test.go
I think this closes https://github.com/grpc/grpc-go/issues/4696
It looks like `Write` unconditionally returns `status.Errorf(codes.Internal, "transport: %v", err)` when we see an error writing the headers. However, in certain cases we'll actually have an overriding context error here, like a cancellation. This PR changes the behavior to return that instead if it's present.
This matches the behavior in the other branch of the conditional (https://github.com/grpc/grpc-go/blob/1f12bf44284e6ba4be72cd028a2a1eb01c2d18bb/internal/transport/http2_server.go#L1028), where if the stream is in state `streamDone`, this either returns `ErrConnClosing` or the `s.ctx.Err()`. We already check for the stream being `streamDone` inside `WriteHeader`, so I opted not to duplicate that check and instead just …
> server: return better status for context err when writing header

- server.go
- stream.go
External documentation: please nit-pick.
RELEASE NOTES:
* server: clarify documentation around setting and sending headers and ServerStream errors
> server: clarify documentation around setting and sending headers and ServerStream errors

- xds/internal/xdsclient/xdsresource/unmarshal_eds.go
- xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
As per https://github.com/grpc/proposal/pull/295
RELEASE NOTES:
* xds/eds: resources containing duplicate localities with the same priority will be rejected
> xds/eds: reject EDS resources with multiple instances of the same locality in the same priority

- xds/internal/xdsclient/authority.go
- xds/internal/xdsclient/loadreport.go
fixes #5328
Caller must hold the mutex before calling `newAuthority`.
RELEASE NOTES:
* xds/client: fix a potential concurrent map read/write in load reporting
> xds/client: hold authority mutex before making a new authority

- clientconn.go
- internal/transport/http2_client.go
- picker_wrapper.go
- stream.go
- test/end2end_test.go
- test/retry_test.go
Fixes #5315
Before this change, there was a very narrow window where a stream could fail to be created on a retry attempt, and subsequent stream operations could panic when this occurred.  This change is a fairly substantial restructuring of the retry code in order to guarantee that for all clientStreams returned to the user, `cs.attempt.s` is always non-nil.  New attempts that don't yet have a stream are created in `cs.newAttempt` until they pick a transport and create a stream, at which time they are promoted to `cs.attempt`.
This also allows us to run balancer pick results through the retry code, meaning UNAVAILABLE errors can be retried by the retry policy, as intended.  It also handles drop results that should explicitly avoid the retry code.
RELEASE NOTES:
* client: fix potential …
> client: fix potential panic during RPC retries

- xds/internal/balancer/cdsbalancer/cluster_handler.go
- xds/internal/balancer/cdsbalancer/cluster_handler_test.go
This PR ignores duplicate clusters and also adds a maximum stack depth in aggregate cluster handling. This takes away the possibility of a stack overflow in aggregate cluster handling.
I'm still adding a few more test cases, but should be good to look at.
> xds: Handle loops and ignore duplicates in aggregated cluster handling

- xds/internal/xdsclient/pubsub/update.go
Fixed a typo. That causes a metadata to be written in a wrong map, thus will be leaked in CSDS
> xdsclient/csds: fix leaked metadata

- xds/internal/balancer/clusterresolver/eds_impl_test.go
- xds/internal/balancer/priority/balancer.go
- xds/internal/balancer/priority/balancer_child.go
- xds/internal/balancer/priority/balancer_priority.go
- xds/internal/balancer/priority/balancer_test.go
See grpc/proposal#296 for context.
After this change, priority will restart the failover timer when a child
reports Connecting, if that child hasn't reported TF more recently than
it reported Ready or Idle.
Also changed the priority policy to always call the centralized function
`syncPriority` to handle child switching.
RELEASE NOTES:
* xds/priority: start the init timer when a child switch to Connecting from non-failure states
> xds/priority: start the init timer when a child switch to Connecting from non-transient-failure state

- xds/internal/resolver/watch_service.go
- xds/internal/resolver/xds_resolver.go
With federation support, `resourceName` could be different from the user's dial target.
> xds/resolver: use correct resource name in log message

- internal/xds/rbac/matchers.go
- internal/xds/rbac/rbac_engine_test.go
This PR adds support for the metadata matcher invert field, which when set to true means that the metadata matcher always matches.
Fixes issue #5150.
RELEASE NOTES:
* Support metadataMatcher.invert for RBAC
> xds: Added support for metadataMatcher.invert

- xds/internal/balancer/ringhash/picker.go
- xds/internal/balancer/ringhash/ringhash.go
- xds/internal/balancer/ringhash/ringhash_test.go
https://github.com/grpc/proposal/pull/296
> xds/ringhash: update connectivity state aggregation, and make sure at least one SubConn is connecting in TF

- internal/transport/controlbuf.go
- internal/transport/http2_server.go
- internal/transport/transport_test.go
Fixes issue #2881. This switches what was originally there (RST Stream) to a full HTTP Response with desired HTTP and gRPC status. Both of these abide to language of issue "grpc-go should fail RPCs if the method is anything but POST". This also abides to Eric's point of reopening this issue, which is that the response should be "An HTTP response with HTTP status code".
RELEASE NOTES:
* Responded with HTTP Status 405 and gRPC status INTERNAL if the method sent to server is not POST
> Added HTTP status and grpc status to POST check

- xds/internal/balancer/priority/balancer.go
- xds/internal/balancer/priority/balancer_child.go
- xds/internal/balancer/priority/balancer_priority.go
- xds/internal/balancer/priority/balancer_test.go
Especially when syncPriority() is triggered by SubConn connectivity state updates.
> xds/priority: avoid sending duplicate updates to children

- clientconn.go
- clientconn_test.go
- pickfirst.go
Even if the SubConn is Connecting (there's no curAddr).
RELEASE NOTES:
* client/SubConn: do not recreate addrConn if UpdateAddresses is called with the same addresses
> client/SubConn: do not recreate addrConn if UpdateAddresses is called with the same addresses

- xds/internal/balancer/clusterresolver/config.go
- xds/internal/balancer/outlierdetection/config.go
- xds/internal/balancer/outlierdetection/config_test.go
Fixes issue #5353.
The config's Equal method is called by CDS to check the equality of discovery mechanisms. However, due to the fact that the Child Policy will not be prepared by the CDS Balancer, but will be prepared by the Cluster Resolver balancer, getting rid of the check is a logical no-op.
> Don't call cmp in non testing file

- xds/internal/balancer/clusterresolver/configbuilder.go
- xds/internal/balancer/clusterresolver/configbuilder_childname.go
- xds/internal/balancer/clusterresolver/configbuilder_childname_test.go
- xds/internal/balancer/clusterresolver/configbuilder_test.go
- xds/internal/balancer/clusterresolver/resource_resolver.go
- xds/internal/balancer/clusterresolver/resource_resolver_test.go
To avoid recreating SubConns if possible
fixes #5268
> xds/clusterresolver: reuse child policy names for the same locality

- test/xds/xds_client_affinity_test.go
- test/xds/xds_client_federation_test.go
- test/xds/xds_client_integration_test.go
- test/xds/xds_client_retry_test.go
- test/xds/xds_rls_clusterspecifier_plugin_test.go
- test/xds/xds_security_config_nack_test.go
- test/xds/xds_server_integration_test.go
- test/xds/xds_server_rbac_test.go
- test/xds/xds_server_serving_mode_test.go
The internal build environment is not happy with a package which contains only test files. The recommended approach is to add a `_test` suffix to the package name. See internal link: go/go-style/decisions#test-different-package
> test/xds: move tests to a package with _test suffix

- dialoptions.go
- internal/transport/handler_server.go
- internal/transport/http2_client.go
- internal/transport/http2_server.go
- internal/transport/transport.go
- server.go
- stats/stats_test.go
- stream.go
As title.
The user-facing interface is unchanged, but the behavior is slightly different. (We discussed this) If a user application intentionally sets StatsHandler repeatedly and only expects the last one to be effective, we will break them.
RELEASE NOTES:
* stats: add support for multiple stats handlers in a single client or server
> stats: add support for multiple stats handlers in a single client or server

- credentials/google/google_test.go
- credentials/google/xds.go
- credentials/google/xds_test.go
RELEASE NOTES:
* credentials/google (for xds): support xdstp C2P cluster names
> credentials/google: support new-style xDS cluster names

- test/kokoro/xds.sh
This PR removes the duplicated xDS tests in GCE (all except circuit_breaking). The ideal (complete coverage & faster & more reliable) set of tests for each branch will be:
- GCE xDS v2: ping_pong
- GCE xDS v3: ping_pong, circuit_breaking
- GKE UrlMap Tests: all
- GKE PSM Security: all
- GKE K8s LB: all
After this PR is merged, I will start to fix each release one by one.
The manual triggered runs for this PR:
* [xds](http://sponge/54dfe351-d40b-44c6-808c-bf12e44d907c)
* [xds_v3](http://sponge/462557d7-4d60-47f5-9672-fb7f6d27dc81)
---
Accidentally removed commits from https://github.com/grpc/grpc-go/pull/5015, took me a while to figure out.
> interop: remove duplicated xDS tests in GCE framework

- balancer/rls/picker.go
- balancer/rls/picker_test.go
RELEASE NOTES:
- RLS load balancer: don't propagate the status code returned on control plane RPCs to data plane RPCs
> rls: use UNAVAILABLE instead of status from control plane

- test/kokoro/xds.sh
```
git cherry-pick 939e0489
```
> test/kokoro: apply xDS interop best practice (backport v1.46.x)

- test/kokoro/xds.sh
```
git cherry-pick 939e0489
```
> test/kokoro: apply xDS interop best practice (backport v1.47.x)

- xds/internal/balancer/ringhash/config_test.go
- xds/internal/balancer/ringhash/picker_test.go
- xds/internal/balancer/ringhash/ring_test.go
- xds/internal/balancer/ringhash/ringhash_test.go
This change makes the actual balancer logs show up in tests.
> ringhash: use grpctest.Tester in unit tests

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.sh
> test/kokoro: use standard TESTING_VERSION in the new framework builds

- internal/internal.go
- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/clusterresolver/clusterresolver_test.go
- xds/internal/balancer/clusterresolver/config.go
- xds/internal/balancer/clusterresolver/configbuilder.go
- xds/internal/balancer/clusterresolver/configbuilder_test.go
- xds/internal/balancer/outlierdetection/balancer.go
- xds/internal/balancer/outlierdetection/balancer_test.go
This PR adds branching logic for constructing the Priority LB's config. In the case that Outlier Detection is configured on with the corresponding Environment variable, the top level balancer's configuration for each priority will be of type Outlier Detection with a Cluster Impl child rather than a Cluster Impl. This had to include the Outlier Detection's balancer to pass Cluster Resolver tests, as the Outlier Detection policy needed to be registered.
Branched off #5370.
> xds: Outlier Detection configuration in Cluster Resolver Balancer

- balancer/base/balancer.go
- internal/testutils/balancer.go
- xds/internal/balancer/clusterimpl/balancer_test.go
- xds/internal/balancer/clusterresolver/eds_impl_test.go
- xds/internal/balancer/clusterresolver/priority_test.go
- xds/internal/balancer/priority/balancer.go
- xds/internal/balancer/priority/balancer_child.go
- xds/internal/balancer/priority/balancer_priority.go
- xds/internal/balancer/priority/balancer_test.go
#5211
- Bug: push config updates to all child policies, not just the active one.
- Process all child picker updates before determining active priority.
Logic changes are all in `.../balancer/priority/*.go`; the other changes are tests that are too dependent on the priority balancer's behavior (not correctness related; just not allowing for the possibility of duplicate picker updates).
RELEASE NOTES:
* xds/priority: fix bug that could prevent higher priorities from receiving config updates
> xds/priority: bug fix and minor behavior change

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.sh
> test/kokoro: standard TESTING_VERSION in the new framework builds (1.41.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.sh
> test/kokoro: standard TESTING_VERSION in the new framework builds (1.42.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.sh
> test/kokoro: standard TESTING_VERSION in the new framework builds (1.43.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.sh
> test/kokoro: standard TESTING_VERSION in the new framework builds (1.44.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.sh
> test/kokoro: standard TESTING_VERSION in the new framework builds (1.45.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.sh
> test/kokoro: standard TESTING_VERSION in the new framework builds (1.46.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.sh
> test/kokoro: standard TESTING_VERSION in the new framework builds (1.47.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.sh
> test/kokoro: standard TESTING_VERSION in the new framework builds (1.40.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.sh
> test/kokoro: standard TESTING_VERSION in the new framework builds (1.39.x backport)

- test/kokoro/psm-security.sh
> test/kokoro: standard TESTING_VERSION in the new framework builds (1.38.x backport)

- test/kokoro/xds_url_map.cfg
This adds `xds_url_map.cfg`, which was missing from the https://github.com/grpc/grpc-go/pull/5411.
Fixes b/236335183.
> test/kokoro: add missing xds_url_map build config

- xds/internal/balancer/outlierdetection/balancer.go
- xds/internal/balancer/outlierdetection/config.go
`golint` was complaining as part of the weekly import because the package level comments were defined in more than one file.
> outlierdetection: fix package level comments

- xds/internal/xdsclient/authority.go
- xds/internal/xdsclient/pubsub/pubsub.go
- xds/internal/xdsclient/pubsub/watch.go
Fixes https://github.com/grpc/grpc-go/issues/5392
> xdsclient: only include nodeID in error strings, not the whole nodeProto

- test/xds/xds_server_serving_mode_test.go
`TestServerSideXDS_RedundantUpdateSuppression` sends a redundant LDS update to an xDS enabled grpc-server, which is currently in `SERVING` mode and ensures that client connections are not recycled. To accomplish this, it was blocking on connectivity state changes on the `ClientConn`, and was failing the test if the `ClientConn` moved away from `READY`. See: 
https://github.com/grpc/grpc-go/blob/5cdb09fa29c15f5490235e9c78f19640bf735d09/test/xds/xds_server_serving_mode_test.go#L115
The last few flakes have been because the `ClientConn` is transitioning to `IDLE`. This is expected behavior since we don't have an ongoing stream of RPCs from the test. Therefore we should not fail the test for this.
```
xds_server_serving_mode_test.go:149: unexpected connectivity state change {READY --> IDLE} …
```
> test/xds: fail only when state changes to something other than READY and IDLE

- xds/internal/balancer/clusterresolver/clusterresolver.go
- xds/internal/balancer/clusterresolver/config.go
- xds/internal/balancer/clusterresolver/config_test.go
- xds/internal/balancer/clusterresolver/configbuilder.go
- xds/internal/balancer/clusterresolver/configbuilder_test.go
Fixes https://github.com/grpc/grpc-go/issues/5369
Apart from fixing the problem mentioned in https://github.com/grpc/grpc-go/issues/5369, this PR also performs the following cleanup:
- remove const aliases for `roundrobin.Name` and `ringhash.Name` and use the actual consts themselves
- address a TODO calling for the registration of a stub balancer to be removed once `ring_hash` is implemented
> clusterresolver: merge P(p)arseConfig functions

- examples/features/health/server/main.go
- examples/features/xds/server/main.go
- interop/xds/server/server.go
- test/end2end_test.go
- test/healthcheck_test.go
Splitting the imports into pb and grpc is necessary to stop importing these generated files into google3.
> health: split imports into healthpb and healthgrpc

- internal/transport/http_util.go
The `bufWriter.onFlush()` feature was not used in the initial `bufWriter` PR https://github.com/grpc/grpc-go/pull/1962 from four years ago. It is unclear if there were future plans, but it is clearly not needed today.
> transport: remove unused `bufWriter.onFlush()`

- xds/internal/balancer/clusterresolver/configbuilder.go
- xds/internal/balancer/clusterresolver/eds_impl_test.go
- xds/internal/xdsclient/xdsresource/type_eds.go
- xds/internal/xdsclient/xdsresource/unmarshal_eds.go
- xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
Fixes https://github.com/grpc/grpc-go/issues/5453
This PR moves the logic of dropping localities, in a received EDS response with weight 0, to the `xdsClient`. This allows the LB policy implementations to function with the assumption that they would only receive localities with non-zero weights as part of any updates from the `xdsClient`. This mirrors C-core behavior.
> xds: drop localities with zero weight at the xdsClient layer

- internal/testutils/xds/e2e/logging.go
- internal/testutils/xds/e2e/server.go
- internal/testutils/xds/e2e/setup_management_server.go
- test/xds/xds_client_ack_nack_test.go
- test/xds/xds_client_affinity_test.go
- test/xds/xds_client_federation_test.go
- test/xds/xds_client_integration_test.go
- test/xds/xds_client_retry_test.go
- test/xds/xds_rls_clusterspecifier_plugin_test.go
- test/xds/xds_security_config_nack_test.go
- test/xds/xds_server_integration_test.go
- test/xds/xds_server_rbac_test.go
- test/xds/xds_server_serving_mode_test.go
- xds/csds/csds_test.go
- xds/internal/httpfilter/fault/fault_test.go
- xds/internal/test/e2e/controlplane.go
- xds/internal/xdsclient/controller/controller.go
- xds/internal/xdsclient/controller/transport.go
When resending resource names after an ADS stream failure, we were resetting the resource version information received on the previous stream. This was our behavior from day 1, but this was in conflict with that is specified in the spec.  This change brings the Go implementation to be in accordance with the spec.
- Fix the code in `xdsClient` to not reset version information about ADS stream restart
- Also, fix the code to not send empty version strings upon ADS stream restart. Instead, use the previously received version strings.
- The actual code changes are limited to `xdsclient/controller/controller.go` and `xdsclient/controller/transport/go`. The remaining changes are test related.
- Add a new e2e test to verify that version information is preserved across stream …
> xdsclient: don't reset version info after stream restart

- go.mod
- go.sum
Updating the 'go' directive to 'go 1.17' will enable module graph
pruning (https://go.dev/ref/mod#graph-pruning), which will allow users
who depend on this module to prune out irrelevant transitive
dependencies (compare #3701).
Note that updating to 'go 1.17' will not break existing users on
versions older than 1.17. (The 'go' version is the version required
for full fidelity — in this case, graph pruning — but older versions
of the Go toolchain will continue to make a best-effort attempt to
compile packages and will not report an error if that attempt
succeeds, as it will in this case.)
> all: update to 'go 1.17' to enable module graph pruning

- internal/xds/bootstrap.go
This is required for tests which use federation and use a resource with an empty authority.
> internal/xds: generate an entry in the authorities map with empty string key

- xds/internal/xdsclient/authority.go
Fixes: https://github.com/grpc/grpc-go/issues/5489
RELEASE NOTES:
- TBD
> xdsclient: use top-level server list if authority specific list is empty

- dialoptions.go
- examples/features/retry/README.md
The `WithDisableRetry()` dial option references the `GRPC_GO_RETRY` env var, but that was deleted in https://github.com/grpc/grpc-go/pull/4922.
> doc: remove comment about obsolete GRPC_GO_RETRY env var

- xds/internal/xdsclient/xdsresource/name.go
- xds/internal/xdsclient/xdsresource/name_test.go
Fixes https://github.com/grpc/grpc-go/issues/5487
RELEASE NOTES:
- xds: request correct resource name from management server when user specifies a new style resource name with empty authority
> xdsclient: handle empty authority in new style resource names

- internal/transport/http2_client.go
- test/end2end_test.go
Fixes #5358.
The test case I added based off the issue test would successfully fail unexpected.EOF. This was caused by a race between when a stream was created and when updateFlowControl() was called. This fix makes sure any created streams has the correct window size on creation.
RELEASE NOTES:
* Fixed dynamic BDP estimation causing unexpected EOF error by fixing race between activeStreams and bdp window size
> Fix race between activeStreams and bdp window size

- xds/xds.go
Fixes https://github.com/grpc/grpc-go/issues/5501
RELEASE NOTES:
- Re-add testing only API `NewXDSResolverWithConfigForTesting()`
> xds: re-add testing only NewXDSResolverWithConfigForTesting()

- stream.go
Note: I am fairly sure the comment formatting change is caused by using a preview version of Go 1.19, meaning we all will see that behavior forced by `gofmt` soon.
Fixes #5341
Description:
We need to create a brand new attempt _every time_ we retry the initial op that gets the transport and creates the stream.  Once that op is committed and added to the replay log, it is handled by the retry+replay logic, but until then, it currently does retries using the original attempt.  This was mostly OK, but leads to a potential infinite loop:
1. `getTransport()` - succeeds
2. `newStream()` - fails with a transparently retryable error, as the transport died at the exact right moment
3. Retry
4. `getTransport` - fails
5. `shouldRetry` should not allow transparent retry in this case, but it does …
> client: fix stream creation issue with transparent retry

- xds/internal/xdsclient/controller/transport.go
- xds/internal/xdsclient/controller/version/v2/loadreport.go
- xds/internal/xdsclient/controller/version/v3/loadreport.go
RELEASE NOTES:
* xdsclient: fix goroutine leaks when load reporting is enabled
> xdsclient: fix LRS stream leaks when errors are encountered

- test/kokoro/xds_k8s_lb.sh
> test/kokoro: Add missing secondary_kube_context to xds LB tests

- test/kokoro/xds_k8s_lb.sh
> test/kokoro: Add missing secondary_kube_context to xds LB tests (1.48.x backport)

- test/kokoro/xds_k8s_lb.sh
> test/kokoro: Add missing secondary_kube_context to xds LB tests (1.47.x backport)

- test/kokoro/xds_k8s_lb.sh
> test/kokoro: Add missing secondary_kube_context to xds LB tests (1.46.x backport)

- test/kokoro/xds_k8s_lb.sh
> test/kokoro: Add missing secondary_kube_context to xds LB tests (1.44.x backport)

- test/kokoro/xds_k8s_lb.sh
> test/kokoro: Add missing secondary_kube_context to xds LB tests (1.43.x backport)

- test/kokoro/xds_k8s_lb.sh
> test/kokoro: Add missing secondary_kube_context to xds LB tests (1.42.x backport)

- test/kokoro/xds_k8s_lb.sh
> test/kokoro: Add missing secondary_kube_context to xds LB tests (1.41.x backport)

- test/kokoro/xds_k8s_lb.sh
> test/kokoro: Add missing secondary_kube_context to xds LB tests (1.40.x backport)

- server.go
Fixes #5523
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
RELEASE NOTES:
* server: reduce log level from Warning to Info for early connection establishment errors
> grpc: change the log-level when a new ServerTransport cannot be created

- interop/test_utils.go
* Don't crash if we didn't fill in peer address
* Honor the min time ms between RPCs flag upon failures
> interop client: fixes for interop soak test

- gcp/observability/config.go
- gcp/observability/observability_test.go
This PR adds support for the Environment Variable GRPC_CONFIG_OBSERVABILITY_JSON, which configures observability through a file at a path specified by the value of this Environment Variable (see private preview 2 document: [go/grpc-observability-ug-2](http://go/grpc-observability-ug-2)). The precedence ordering of this environment variable taking precedence over GRPC_CONFIG_OBSERVABILITY is based on the grpc-java implementation to keep it consistent across languages, and not officially defined in the design document.
RELEASE NOTES:
* gcp/observability: Add support for Environment Variable GRPC_CONFIG_OBSERVABILITY_JSON
> gcp/observability: Add support for Environment Variable GRPC_CONFIG_OBSERVABILITY_JSON

- balancer/weightedtarget/weightedaggregator/aggregator.go
- balancer/weightedtarget/weightedtarget.go
- balancer/weightedtarget/weightedtarget_test.go
#5211
Even though the picker is updated synchronously in `UpdateClientConnState`, multiple updates could result in `UpdateState` calls to the parent if this is not done to suppress them.
> balancer/weightedtarget: pause picker updates during UpdateClientConnState

- xds/internal/balancer/clustermanager/balancerstateaggregator.go
- xds/internal/balancer/clustermanager/clustermanager.go
- xds/internal/balancer/clustermanager/clustermanager_test.go
#5211
Even though the picker is updated synchronously in `UpdateClientConnState`, multiple updates could result in `UpdateState` calls to the parent if this is not done to suppress them.
> xds/clustermanager: pause picker updates during UpdateClientConnState

- internal/envconfig/xds.go
This PR fixes a bug in Outlier Detection, when Outlier Detection was set to true the configuration would be prepared which would try and Build a placeholder balancer which would fail RPC's. This hardcodes the Environment Variable configuration to false, which will be changed when my full Outlier Detection PR gets merged. This will need to get backported to 1.48, as the bug is present in that branch too.
RELEASE NOTES:
* Fix bug when environment variable GRPC_EXPERIMENTAL_ENABLE_OUTLIER_DETECTION set to true
> xds: Fixed GoLang regression for Outlier Detection

- xds/internal/xdsclient/client.go
Part of https://github.com/grpc/grpc-go/issues/5478.
Also added a compile time check to ensure `clientImpl` satisfies the `XDSClient` interface.
> xdsclient: change receiver on BootstrapConfig() to be consistent

- interop/test_utils.go
Currently TD is migrating from legacy to xdstp, and RLS server will return both xdstp and legacy cluster. Since the resource watcher timeout is 15s, we need to increase the timeout to make the test pass during the xdstp migration.
> test/interop: increase pick_first timeout

- internal/transport/http2_server.go
- test/end2end_test.go
Fixes #5511
RELEASE NOTES:
* transport/server: fix race that could cause a stray header to be sent
> transport/server: fix race that could cause a stray header to be sent

- default_dial_option_server_option_test.go
- dialoptions.go
- server.go
- test/end2end_test.go
Fix #5512
RELEASE NOTES:
* Fix a panic caused by passing a `nil` stats handler to `grpc.WithStatsHandler` or `grpc.StatsHandler`
> grpc: prevent a nil stats handler from causing a panic

- balancer/rls/balancer.go
- balancer/rls/balancer_test.go
- balancer/rls/control_channel.go
- Use a single channel to process the different events handled by the `run()` goroutine.
- Handling config updates from parent: `UpdateClientConnState()`
- Handles config updates inline instead of pushing them on to a channel.
- Sets a flag to inhibit picker updates.
- After handling the config changes and pushing the required configs to child policies, queues an event to resume picker updates.
- Waits for the above event to be acted upon, and then returns a new picker.
- Handling state updates from child: `UpdateState()`
- Handled asynchronously as before. The only change is that message is pushed on the single channel used by `run()` goroutine.
- Pushing picker updates to the parent: `SendNewPickerLocked()`
- If picker updates are inhibited (by the flag set in …
> rls: suppress picker updates from children when handling config updates

- xds/internal/balancer/priority/balancer.go
- xds/internal/balancer/priority/balancer_priority.go
- xds/internal/balancer/priority/balancer_test.go
Recently, we added functionality to push config updates to all child policies (not just the active one) and process all child picker updates before determining active priority. See: https://github.com/grpc/grpc-go/pull/5417
As part of this change though, we were calling `syncPriority` with an empty child name at the end of the config processing pipeline. This sometimes could lead to the priority LB policy dropping picker updates which could lead to all RPCs getting blocked.
RELEASE NOTES:
- priority: fix bug which could cause priority LB from blocking all traffic after a config update
> priority: sync priority with child in use

- clientconn_test.go
- test/clientconn_state_transition_test.go
I'm making some other test changes which introduce a dependency on the `grpc` package for `internal/testutils`. Currently the clientconn state transition tests introduce a dependency from package `grpc` to `internal/testutils`. This leads to an import cycle. This PR removes the latter dependency by moving these tests out to the `test` directory. The added benefit of doing this is that we are forced to use the public API instead of relying on some internal APIs.
This also introduces a little bit of code duplication, as some of the test helper functions need to be repeated for tests in `grpc` package and for the `test` package. This can be removed in the future when we switch to using the public API  more frequently in our tests.
> test: move clientconn state transition test to test/ directory

- service_config.go
- test/channelz_test.go
- vet.sh
Fixes https://github.com/grpc/grpc-go/issues/5229
> grpc: remove mentions of deleted API, WithBalancerName, from comments

- xds/internal/xdsclient/e2e_test/lds_watchers_test.go
Fixes https://github.com/grpc/grpc-go/issues/5546
I've seen a couple of flakes in this test:
1. The `go-control-plane` server continuously resends the same resources if the client NACKs it. This means that our tests which verify some sort of NACKing behavior will continuously receive the same resources again and again. This means that the watch callback will be called an arbitrary number of times. This causes `testutils.Channel.Send()` to block because there is no buffer on the channel. Allocating a buffer for this channel is not an option since we do not know how big a buffer we would need. Instead using `SendContext()` would ensure that the call will return when the test's context is cancelled.
2.  `envconfig.XDSFederation` is to true at the top of every test and a function is deferred …
> xdsclient: deflake Test/LDSWatch_PartialValid

- internal/testutils/xds/e2e/clientresources.go
- xds/internal/testutils/protos.go
- xds/internal/xdsclient/controller/v2_eds_test.go
- xds/internal/xdsclient/xdsresource/unmarshal_eds.go
- xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
This is the existing behavior in other languages already (and Envoy), and we are late to the party.
Fixes: https://github.com/grpc/grpc-go/issues/5456
- Change the unmarshaling routine in `xdsclient` to error out if it sees an endpoint resource with zero weight
- Change test routines to insert a weight of 1 in all endpoint resources that they use
- Fix existing tests to expect endpoints with weight 1
- Add a test for the zero endpoint case
RELEASE NOTES:
- xds: NACK endpoint resources with zero weight
> xdsclient: NACK endpoint resources with zero weight

- xds/internal/balancer/ringhash/ring.go
- xds/internal/balancer/ringhash/ring_test.go
- xds/internal/balancer/ringhash/ringhash.go
- xds/internal/balancer/ringhash/ringhash_test.go
Fixes https://github.com/grpc/grpc-go/issues/5460
Fix a few things in the config handling routine of the ringhash LB policy:
- config changes in the ring size should result in a new picker with a new ring
- config changes should result in the internal copy of the config being updated
RELEASE NOTES:
- ringhash: fix config update processing to recreate ring and picker when min/max ring size changes
> ringhash: handle config updates properly

- internal/testutils/xds/e2e/clientresources.go
- xds/internal/testutils/protos.go
- xds/internal/xdsclient/xdsresource/unmarshal_eds.go
https://github.com/grpc/grpc-go/pull/5560 introduced the change to NACK EDS resources with endpoints whose `load_balancing_weight` field was set to zero. The correct fix though, is to NACK the resource only when the above field *is* specified and *is* set to zero.
RELEASE NOTES:
- covered by the one in https://github.com/grpc/grpc-go/pull/5560
> xdsclient: NACK endpoint resource if load_balancing_weight is specified and is zero

- test/kokoro/xds_url_map.sh
> test/kokoro: add missing image tagging to the xDS interop url map buildscript

- test/kokoro/xds_url_map.sh
> test/kokoro: add missing image tagging to the xDS interop url map buildscript (1.40.x backport)

- test/kokoro/xds_url_map.sh
> test/kokoro: add missing image tagging to the xDS interop url map buildscript (1.41.x backport)

- test/kokoro/xds_url_map.sh
> test/kokoro: add missing image tagging to the xDS interop url map buildscript (1.42.x backport)

- test/kokoro/xds_url_map.sh
> test/kokoro: add missing image tagging to the xDS interop url map buildscript (1.43.x backport)

- test/kokoro/xds_url_map.sh
> test/kokoro: add missing image tagging to the xDS interop url map buildscript (1.44.x backport)

- test/kokoro/xds_url_map.sh
> test/kokoro: add missing image tagging to the xDS interop url map buildscript (1.45.x backport)

- test/kokoro/xds_url_map.sh
> test/kokoro: add missing image tagging to the xDS interop url map buildscript (1.46.x backport)

- test/kokoro/xds_url_map.sh
> test/kokoro: add missing image tagging to the xDS interop url map buildscript (1.47.x backport)

- test/kokoro/xds_url_map.sh
> test/kokoro: add missing image tagging to the xDS interop url map buildscript (1.48.x backport)

- gcp/observability/logging.go
This PR stops logging calls proceeding from logging, tracing, and metrics API calls in observability.
> gcp/observability: Add logging filters for logging, tracing, and metrics API calls

- .github/workflows/release.yml
This updates the release workflow to build and publish arm64 binaries. `arm64` is already tested [here](https://github.com/grpc/grpc-go/blob/master/.github/workflows/testing.yml#L59).
Fixes #5544
> Publish arm64 binaries to GitHub releases

- xds/internal/balancer/clusterresolver/resource_resolver.go
An issue was discovered where, when shutting down, the cluster resolver balancer calls `stop`/`Close` on its DNS child with the lock held.  Meanwhile, the DNS resolver is in its polling loop and then calls `UpdateState` due to a recent update.  This then calls into the cluster resolver's CC wrapper and attempts to acquire the same lock in the cluster resolver.  However, the `Close` method in the DNS resolver blocks until the polling loop exits, but that can't happen because the lock needed to proceed is held by the caller of `Close`.
The solution in this PR is to call `stop`/`Close` on the children without the lock held.
In practice, we don't need to re-initialize the `childrenMap`, as done by this PR, because, when stopped, the parent CDS policy (and its clusterresolver child) is …
> xds/clusterresolver: prevent deadlock of concurrent Close and UpdateState calls

- xds/internal/resolver/serviceconfig.go
- xds/internal/resolver/serviceconfig_test.go
- xds/internal/resolver/xds_resolver.go
- xds/internal/xdsclient/xdsresource/type_rds.go
This change keeps our code in sync with the spec change at https://github.com/grpc/proposal/pull/320.  We would rather generate a purely random number for this identifier to ensure different clients are extremely unlikely to generate the same identifier.
cc @apolcyn
> xds/resolver: generate channel ID randomly

- internal/transport/http2_client.go
- internal/transport/http2_server.go
- internal/transport/transport_test.go
Motivation: https://github.com/grpc/grpc-go/issues/5586
Added peer to the http2server context to allow application to access this information when a connection is just established. This frees application from tracking this information on each and every rpc request.
RELEASE NOTES:
* stats: provide peer information in `HandleConn` context
> transport: add peer information to http2Server and http2Client context

- internal/transport/http_util.go
Spec is now available at https://httpwg.org/specs/rfc7540.html.
> Fix http2 spec document link

- xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
- xds/internal/balancer/ringhash/logging.go
- xds/internal/balancer/ringhash/ringhash.go
- Always send a picker update (even if the ring hasn't changed) when the LB policy receives a subConn update. 
- Earlier, we were only sending a picker update when the effective state of the subConn changed. Current change helps with re-queueing RPCs in cases where:
- there is a single subConn, and/or
- subConn move from TRANSIENT_FAILURE to a non READY state.
- Regenerate the picker when the subConn moves to READY. This is required when the aggregate state of the channel is changing from TRANSIENT_FAILURE to READY, and we need to overwrite the earlier error picker that we had pushed.
- Ensure that the LB policy is attempting to reconnect (when the aggregate state of the channel is TRANSIENT_FAILURE), even if there is a single subConn.
Fixes #5594
RELEASE NOTES:
- …
> xds/ringhash: make reconnection logic work for a single subConn

- xds/internal/balancer/ringhash/ringhash.go
Fixes https://github.com/grpc/grpc-go/issues/5602
RELEASE NOTES:
- ringhash: do nothing when asked to exit `IDLE` instead of falling back on the default channel behavior of connecting to all addresses
> ringhash: implement a no-op ExitIdle() method

- test/kokoro/psm-security.cfg
- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.cfg
- test/kokoro/xds_url_map.sh
> test/kokoro: enable pod log collection in the buildscripts

- balancer/rls/config.go
- credentials/sts/sts.go
- credentials/sts/sts_test.go
- credentials/tls/certprovider/store_test.go
- internal/balancergroup/balancerstateaggregator.go
- internal/testutils/roundrobin/roundrobin.go
- security/advancedtls/advancedtls_integration_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/resolver/watch_service.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
> cleanup: remove duplicate words in comments

- xds/internal/xdsclient/xdsresource/unmarshal_cds.go
- xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
https://github.com/grpc/grpc-go/issues/5612
RELEASE NOTES:
- xdsclient: NACK cluster resource if `config_source_specifier` in `lrs_server` is not `self`
> xdsclient: NACK cluster resource if config_source_specifier in lrs_server is not self

- credentials/alts/internal/handshaker/handshaker.go
RELEASE NOTES:
- alts: fix a bug which was setting `WaitForReady` on handshaker service RPCs, thereby delaying fallback when required
> alts: do not set WaitForReady on handshaker service RPCs

- internal/grpcrand/grpcrand.go
- test/xds/xds_client_outlier_detection_test.go
- xds/internal/balancer/outlierdetection/balancer.go
- xds/internal/balancer/outlierdetection/balancer_test.go
- xds/internal/balancer/outlierdetection/callcounter.go
- xds/internal/balancer/outlierdetection/callcounter_test.go
- xds/internal/balancer/outlierdetection/e2e_test/outlierdetection_test.go
- xds/internal/balancer/outlierdetection/logging.go
- xds/internal/balancer/outlierdetection/subconn_wrapper.go
This PR adds the Outlier Detection Balancer as part of the xDS configured tree of balancers (see https://github.com/grpc/proposal/blob/master/A50-xds-outlier-detection.md).
Contains https://github.com/grpc/grpc-go/pull/5371.
RELEASE NOTES:
* xDS: add support for Outlier Detection
> xds: add Outlier Detection Balancer

- .github/workflows/testing.yml
- gcp/observability/observability.go
- gcp/observability/observability_test.go
- gcp/observability/opencensus.go
Previously, our metrics and tracing calls would not have the buffer flushed in observability.End(), and also keep the exporters registered globally in another package. Thus, tracing and metrics data would possibly not get uploaded to a backend properly. Also, our tests would break when run more than once due to the trailing exporter.
Fixes https://github.com/grpc/grpc-go/issues/5423, https://github.com/grpc/grpc-go/issues/5558, https://github.com/grpc/grpc-go/issues/5559
RELEASE NOTES:
* gcp/observability: fix End() to cleanup global state correctly
> gcp/observability: fix End() to cleanup global state correctly

- metadata/metadata.go
- metadata/metadata_test.go
FromIncomingContext creates a copy of md every time.
So even if you need a single header value you will get a value and an overhead for this.
Many interceptors and user code doesn't need all values at a time.
I'd like also to add a helper to just check key existence.
RELEASE NOTES:
* metadata: add `ValueFromIncomingContext` to more efficiently retrieve a single value
> metadata: add ValueFromIncomingContext to more efficiently retrieve a single value

- orca/service.go
The import is broken because the wrong generated proto type is declared.
> orca: fix package used to reference service to use grpc suffix instead of pb

- test/kokoro/psm-security.cfg
- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.cfg
- test/kokoro/xds_url_map.sh
> test/kokoro: enable pod log collection in the buildscripts (v1.49.x backport)

- test/kokoro/psm-security.cfg
- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.cfg
- test/kokoro/xds_url_map.sh
> test/kokoro: enable pod log collection in the buildscripts (v1.46.x backport)

- test/kokoro/psm-security.cfg
- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.cfg
- test/kokoro/xds_url_map.sh
> test/kokoro: enable pod log collection in the buildscripts (v1.45.x backport)

- test/kokoro/psm-security.cfg
- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.cfg
- test/kokoro/xds_url_map.sh
> test/kokoro: enable pod log collection in the buildscripts (v1.40.x backport)

- test/kokoro/psm-security.cfg
- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.cfg
- test/kokoro/xds_url_map.sh
> test/kokoro: enable pod log collection in the buildscripts (v1.41.x backport)

- test/kokoro/psm-security.cfg
- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.cfg
- test/kokoro/xds_url_map.sh
> test/kokoro: enable pod log collection in the buildscripts (v1.43.x backport)

- test/kokoro/psm-security.cfg
- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.cfg
- test/kokoro/xds_url_map.sh
> test/kokoro: enable pod log collection in the buildscripts (v1.44.x backport)

- test/kokoro/psm-security.cfg
- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.cfg
- test/kokoro/xds_url_map.sh
> test/kokoro: enable pod log collection in the buildscripts (v1.47.x backport)

- test/kokoro/psm-security.cfg
- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.cfg
- test/kokoro/xds_url_map.sh
> test/kokoro: enable pod log collection in the buildscripts (v1.48.x backport)

- test/kokoro/psm-security.cfg
- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.cfg
- test/kokoro/xds_k8s_lb.sh
- test/kokoro/xds_url_map.cfg
- test/kokoro/xds_url_map.sh
> test/kokoro: enable pod log collection in the buildscripts (v1.42.x backport)

- balancer/rls/picker.go
- internal/testutils/xds/e2e/clientresources.go
- test/xds/xds_rls_clusterspecifier_plugin_test.go
Recently, we implemented a no-op `ExitIdle` method for the ringhash LB policy in https://github.com/grpc/grpc-go/pull/5614.
When RLS is used in conjunction with ringhash though, this causes the channel to never come out of `IDLE`, as ringhash starts in `IDLE` and any requests to exit idle from its parent results in a no-op.
The pick behavior in RLS though seems to be the root cause. Instead of delegating the picks to child policies which are not in `TransientFailure`, RLS was asking them to exit idle if they were in `IDLE`. This is in contrast to how things are implemented in c-core, which simply delegates the picks to the child policies as long as they are not in `TransientFailure`, and for a policy like `ringhash`, the pick ensures that it exits idle.
RELEASE NOTES:
- rls: fix a bug …
> rls: delegate pick to child policy as long as it is not in TransientFailure

- internal/envconfig/xds.go
Reverts #5537. The previous PR was needed since only the partial functionality of Outlier Detection was completed, which was failing interop tests. Now that the full functionality is merged, we can make this the normal env var.
> xDS: Outlier Detection Env Var not hardcoded to false

- xds/internal/xdsclient/xdsresource/unmarshal_rds.go
- xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
This PR implements changes mentioned in https://github.com/grpc/proposal/pull/292.
RELEASE NOTES:
- xdsclient: fix a bug which was causing routes with `cluster_specifier_plugin` set to be NACKed when GRPC_EXPERIMENTAL_XDS_RLS_LB was off
> xdsclient: ignore routes with cluster_specifier_plugin when GRPC_EXPERIMENTAL_XDS_RLS_LB is off

- .github/workflows/release.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub: restrict permissions in release workflow

- examples/features/unix_abstract/server/main.go
- internal/resolver/unix/unix.go
- test/authority_test.go
Trailing nul byte is added by golang Dial wrapper. To avoid that one should use '@socket' as address instead of '\0socket' (see [1]).
This change makes go-grpc behave like grpc/grpc (see [2]), making connecting to golang server with grpc_cli possible.
[1]: https://go.googlesource.com/sys/+/master/unix/syscall_linux.go#420
[2]: https://github.com/grpc/grpc/blob/d43511f4af992862ae17c6fce5caa3ab3ce60995/src/core/lib/address_utils/parse_address.cc#L109
RELEASE NOTES:
* client: use proper "@" semantics for connecting to abstract unix sockets.  This is technically a bug fix; the result is that the address used to include a trailing NUL byte, which it should not have.  This may break users creating the socket in Go by prefixing a NUL instead of an "@", though, so calling it out as a behavior …
> client: remove trailing null from unix abstract socket address

- internal/envconfig/xds.go
- internal/internal.go
- test/xds/xds_client_outlier_detection_test.go
- xds/internal/balancer/balancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/clusterresolver/clusterresolver_test.go
- xds/internal/balancer/clusterresolver/configbuilder_test.go
- xds/internal/balancer/outlierdetection/balancer.go
- xds/internal/balancer/outlierdetection/balancer_test.go
- xds/internal/balancer/outlierdetection/e2e_test/outlierdetection_test.go
- xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
RELEASE NOTES:
* xds: enable Outlier Detection by default
> xds: enable Outlier Detection by default

- internal/transport/http_util.go
- internal/transport/http_util_test.go
Use `strings.Builder` (introduced in Go 1.10) instead of `bytes.Buffer`. Also call `fmt.Fprintf` directly on the builder. This improves performance both in terms of CPU and memory consumption:
```
name                 old time/op    new time/op    delta
DecodeGrpcMessage-8     345ns ± 5%     225ns ± 4%  -34.56%  (p=0.000 n=20+20)
EncodeGrpcMessage-8    1.33µs ± 4%    1.26µs ± 3%   -5.76%  (p=0.000 n=20+20)
name                 old alloc/op   new alloc/op   delta
DecodeGrpcMessage-8     80.0B ± 0%     24.0B ± 0%  -70.00%  (p=0.000 n=20+20)
EncodeGrpcMessage-8      115B ± 0%       88B ± 0%  -23.48%  (p=0.000 n=20+20)
name                 old allocs/op  new allocs/op  delta
DecodeGrpcMessage-8      2.00 ± 0%      2.00 ± 0%     ~     (all equal)
EncodeGrpcMessage-8      8.00 ± 0%      4.00 ± …
```
> internal/transport: optimize grpc-message encoding/decoding

- credentials/credentials.go
- internal/status/status.go
- internal/transport/http2_client.go
- picker_wrapper.go
- stream.go
- test/control_plane_status_test.go
- test/creds_test.go
RELEASE NOTES:
* grpc: restrict status codes from control plane (gRFC A54)
> grpc: restrict status codes from control plane (gRFC A54)

- default_dial_option_server_option_test.go
- dialoptions.go
- gcp/observability/opencensus.go
- internal/internal.go
- server.go
- stream.go
- test/end2end_test.go
This PR adds a binary logger option for client and server. This is needed due to the observability config iteration of a partition between client and server events.
> Add binary logger option for client and server

- internal/balancergroup/balancergroup.go
- internal/balancergroup/balancergroup_test.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/balancer/clusterresolver/clusterresolver.go
- xds/internal/balancer/priority/balancer.go
- xds/internal/balancer/priority/balancer_child.go
- xds/internal/balancer/priority/balancer_priority.go
- xds/internal/balancer/priority/balancer_test.go
- xds/internal/balancer/priority/ignore_resolve_now.go
- xds/internal/balancer/priority/ignore_resolve_now_test.go
- xds/internal/balancer/ringhash/ringhash.go
- priority balancer
- remove child policy wrapper from the children map when the child is removed from the configuration
- stop caching balancer state from child policies which are not `started`
- store the balancer name in the child policy wrapper instead of the `balancer.Builder` and pass the former to the `balancergroup` when creating child policies
- wrap the `balancer.ClientConn` passed in from the parent before passing it to the children
- this wrapper ignores `ResolveNow()` calls from children who are configured with the `IgnoreReresolutionRequests` field set
- this wrapper also supports updating this field based on changes in configuration
- balancergroup:
- add a new API to add child policies to the group. Once other lb policies are updated to use this API, it …
> priority: release references to child policies which are removed

- encoding/encoding.go
- internal/envconfig/envconfig.go
- internal/grpcutil/compressor.go
- internal/grpcutil/compressor_test.go
- internal/transport/http2_client.go
- test/end2end_test.go
Part of #2786 (rest fixes in follow-up PRs)
Description:
In the current implementation, we forward `grpc-accept-encoding` only when the client sets compression on the outgoing RPCs. With this pull request, all the compressors registered with `encoding.RegisterCompressor` are added under the `grpc-accept-encoding` header for the outgoing RPCs. 
When the client enables compression using deprecated [`grpc.WithCompressor`](https://pkg.go.dev/google.golang.org/grpc#WithCompressor), stick to the old behaviour of setting the `grpc-accept-header` header to the outgoing compressor.
- client: set grpc-accept-encoding header with all registered compressors
> client: set grpc-accept-encoding to full list of registered compressors

- xds/internal/xdsclient/client_new.go
- xds/internal/xdsclient/dump_test.go
- xds/internal/xdsclient/e2e_test/lds_watchers_test.go
- xds/internal/xdsclient/loadreport_test.go
Improve the existing LDS watchers test:
- For tests which have subtests, move the creation of the xdsclient into `t.Run()`. This will remove the flakiness we have been observing on GitHub Actions.
- Add a couple of more tests. These scenarios were being tested for some of the other xDS watchers. So, I added them here as well.
- Change the `NewWithConfigForTesting` API to allow configuring the authority idle timeout. This will be used in upcoming PRs.
Fixes https://github.com/grpc/grpc-go/issues/5643
> xdsclient: improve LDS watchers test

- xds/googledirectpath/googlec2p.go
Integration tests are passing and known issues are fixed.
Note this PR keeps around the old "-experimental" scheme - the plan is to remove it after removing all usage of it (within the next release cycle or so).
Java PR: https://github.com/grpc/grpc-java/pull/9464
C++: https://github.com/grpc/grpc/pull/30653
RELEASE NOTES:
- xds: de-experimentalize the google-c2p-resolver
> xds: de-experimentalize google c2p resolver

- xds/internal/xdsclient/xdsresource/unmarshal_eds.go
- xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
This PR adds a check if EDS resource contains a duplicate endpoint with the same address.
Fixes https://github.com/grpc/grpc-go/issues/5710
RELEASE NOTES:
- xds: comply with recent change in xDS spec to NACK EDS resources with duplicate addresses
> xds/xdsclient: add EDS resource endpoint address duplication check

- gcp/observability/config.go
Stanley found a typo in my json annotations.
> Fix o11y typo

- server.go
This PR fixes an o11y bug which was preventing server side traces and metrics from being recorded due to the server option being overwritten by the binary logger global server option. It should append, not replace.
> o11y: Fixed o11y bug

- admin/test/utils.go
- internal/testutils/xds/bootstrap/bootstrap.go
- internal/testutils/xds/e2e/setup_management_server.go
- test/xds/xds_client_federation_test.go
- xds/csds/csds_test.go
- xds/internal/httpfilter/fault/fault_test.go
- xds/internal/test/e2e/controlplane.go
We have a utility package to generate bootstrap configuration. This is being used only by tests, and I don't see them being used by non-test code. This PR moves this package out of `internal/xds` to `internal/testutils/xds/bootstrap`.
> xds: move bootstrap config generating utility package to testutils

- balancer/weightedtarget/weightedaggregator/aggregator.go
- balancer/weightedtarget/weightedtarget_test.go
- xds/internal/balancer/clusterresolver/priority_test.go
When all the child policies are in `TRANSIENT_FAILURE`, the `weightedtarget` LB policy currently sends a picker which always returns `balancer.ErrTransientFailure` error message. This error does not provide any info to the user regarding the underlying issue for the failure. With this change we are surfacing the underlying error by sending back the error picker.
Fixes #5391 
RELEASE NOTES:
* xds/weightedtarget: return an error picker to surface a more meaningful error when all children are in transient failure
> weightedtarget: return a more meaningful error when no child policy is reporting READY (#5391)

- xds/internal/xdsclient/callback_serializer.go
- xds/internal/xdsclient/callback_serializer_test.go
We need to guarantee that callbacks scheduled by the xDS client are executed in the order in which they were scheduled. Currently, this is not exactly the case and is the reason for https://github.com/grpc/grpc-go/issues/5429.
This type will get used by the xDS client as part of the refactor effort to support a resource agnostic watch API.
> xdsclient: add a convenience type to synchronize execution of callbacks

- balancer/weightedtarget/weightedtarget_test.go
- internal/balancergroup/balancergroup_test.go
- internal/testutils/balancer.go
- xds/internal/balancer/clusterresolver/priority_test.go
- xds/internal/balancer/clusterresolver/testutil_test.go
As a reactive from a previous PR (#5711) we want to update certain tests to use helper functions from `internal/testutils/balancer.go`
> tests: refactor tests to use testutils helper functions

- xds/googledirectpath/googlec2p.go
- xds/googledirectpath/googlec2p_test.go
To properly use xds federation when the env var is set.
C++ PR: https://github.com/grpc/grpc/pull/29732
Java PR: https://github.com/grpc/grpc-java/pull/9576
> google-c2p resolver: add authority entry to bootstrap config

- stats/stats_test.go
In a normal situation, `h.gotConn` ends with:
```
stats.ConnBegin
stats.ConnBegin
stats.ConnEnd
stats.ConnEnd
```
But with the current waiting algorithm, this situation would be enough to stop waiting:
```
stats.ConnBegin
stats.ConnBegin
stats.ConnEnd
```
And the test fails with 
```
stats_test.go:1421: h.gotConn: unexpected amount of ConnStats: 3 != 4
```
I was able to reproduce this behavior with the following command. After the fix, the tests passed:
```
go test -count=10000  -run 'Test/MultipleClientStatsHandler' ./stats
```
Fixes #5695 
> Fix flaky test MultipleClientStatsHandler

- balancer/conn_state_evaluator.go
- balancer/weightedtarget/weightedaggregator/aggregator.go
- balancer/weightedtarget/weightedtarget.go
- balancer/weightedtarget/weightedtarget_test.go
- internal/balancergroup/balancergroup_test.go
use ConnectivityStateEvaluator in weighted target balancer to evaluate the aggregate state of a weighted target group. 
> balancer/weightedtarget: use ConnectivityStateEvaluator

- balancer/weightedtarget/weightedaggregator/aggregator.go
- balancer/weightedtarget/weightedtarget_test.go
#5734's diff works in way that ConnStateEvltr does not ignore transitions from TF to Connecting. This will fix it. Also adding a test to assert this.
> balancer/weightedtarget: fix ConnStateEvltr to ignore transition from TF to Connecting

- xds/googledirectpath/googlec2p.go
Similar to C++ PR: https://github.com/grpc/grpc/pull/29922
cc @easwars 
Tested manually that this works in an e2e test setup with `GRPC_EXPERIMENTAL_XDS_FEDERATION=true`
> google-c2p: use new-style resource name for LDS subscription

- internal/transport/transport_test.go
Reported by StaticCheck while importing into google3:
SA4006 - A value assigned to a variable is never read before being overwritten. Forgotten error check or dead code? 
> transport/test: implement staticcheck suggestion

- clientconn.go
`parsedTarget.Scheme` is marked as deprecated. Switch the code in clientconn.go to use `parsedTarget.URL.Scheme` instead.
> target: replace parsedTarget.Scheme to parsedTarget.URL.Scheme

- xds/internal/xdsclient/e2e_test/cds_watchers_test.go
This got missed in the previous PR somehow. We need to use `SendContext()` instead of `Send()` in cases where we expect the resource be NACK'ed because in these cases the management server will continuously keep resending the same resource again and again. Using `SendContext()` in the watch callback ensures that the send operation gets unblocked when the context is cancelled as part of test termination. If we use `Send()` instead, this could sometimes lead to a leaked goroutine as the watch callback is blocked on the send operation.
FWIW, this is already done in the `lds_watchers_test.go` which is merged.
> xdsclient/e2e_test: use SendContext() where appropriate

- xds/googledirectpath/googlec2p.go
- xds/googledirectpath/googlec2p_test.go
As per [gRPC DirectPath C2P Resolver](https://docs.google.com/document/d/1YpKFQHSzG7YoNHXbY74Xc_-oiSDJ3w7XH4WPNDKP9UQ/edit?resourcekey=0-JG5kLNkW3FVwY59_2HSZnA#) doc, The "google-c2p" URI scheme will not support authorities.
This diff will validate that 
RELEASE NOTES:
* xds/google-c2p: validate URI schema for no authorities
> xds/google-c2p: validate url for no authorities

- gcp/observability/logging_test.go
- internal/transport/transport.go
- stream.go
- test/end2end_test.go
Fixes #5706. Uses an invariant of the system, s.noHeaders, and propagates that signal to the client stream to gate the Server Header logging call. No explicit test, but have tests that test this at very specific granularity and you can see deleting the Server Header expectation for the want makes the tests pass.
RELEASE NOTES:
* client: fix binary logging bug which logs a server header on a trailers-only response
> client: fix binary logging bug which logs a server header on a trailers only response

- balancer/balancer.go
- balancer/base/balancer_test.go
- balancer_conn_wrappers.go
- internal/grpcsync/oncefunc.go
- internal/testutils/balancer.go
- orca/internal/internal.go
- orca/producer.go
- orca/producer_test.go
- xds/internal/balancer/clusterresolver/clusterresolver_test.go
RELEASE NOTES:
* balancer: add experimental Producer types and methods _and_ * orca: provide a way for LB policies to receive OOB load reports
> orca: create ORCA producer for LB policies to use to receive OOB load reports

- internal/testutils/xds/e2e/server.go
- xds/internal/xdsclient/client_test.go
- xds/internal/xdsclient/e2e_test/misc_watchers_test.go
Improve a test which verifies that the xdsclient does not deadlock if a new watch is called inline from a watch callback, by moving to an e2e style test which verifies functionality without relying on any internal state.
This PR is similar to how the LDS watchers test was cleaned up in https://github.com/grpc/grpc-go/pull/5506.
> xdsclient: switch xdsclient watch deadlock test to e2e style

- gcp/observability/logging.go
- gcp/observability/logging_test.go
The filtering of logging from the calls to cloud ops endpoints was missed in the new Observability config iteration. This adds it back. Decided not to info log in this scenario to avoid std out log spam.
> gcp/observability: filter logging from cloud ops endpoints calls

- benchmark/benchmark.go
The read and write buffer sizes are currently hardcoded to 128KB instead of the default 32KB. This can potentially lead to misleading benchmark results in the most common case, since most users presumably use the default value.
This change removes the custom value for read and write transport buffer sizes, both client and server side, so that benchmarks use the default values instead.
> benchmark: use default buffer sizes

- xds/internal/xdsclient/controller/controller.go
- xds/internal/xdsclient/controller/transport.go
- xds/internal/xdsclient/e2e_test/misc_watchers_test.go
Make the `Close()` method on the xDS client object to block until the underlying transport is closed. Without this, our tests are very flaky.
- Add a couple of fields to the `Controller` struct which contains all the logic and state required to communicate with a particular xDS management server. This holds the underlying transport to the management server.
- When `Controller.Close()` is called, we wait for the underlying transport to be closed before returning.
- If the `Close()` method is called multiple times, it will be a no-op except for the first time.
> xdsclient: wait for underlying transport to close

- clientconn_parsed_target_test.go
- internal/resolver/passthrough/passthrough.go
Empty string is clearly not a valid target when default scheme is passthrough and no custom dialer set. But grpc.Dial will not return error in this case until client starts making RPCs, user will get errors saying `transport: Error while dialing dial tcp: missing address.`
It would be better fail fast and notify user empty target is invalid before RPC calls.
This PR fixes this issue by checking 1. is endpoint empty 2. is there a custom dialer in `passthroughBuilder.Build`, if endpoint is empty and there is no custom dialer, an error will be returned.
RELEASE NOTES:
* client: return an error from `Dial` if an empty target is passed and no custom dialer is present; the ClientConn would otherwise be unable to connect and perform RPCs
> passthrough: return error if endpoint is empty and opt.Dialer is nil when building resolver

- xds/internal/balancer/clusterresolver/config_test.go
- xds/internal/balancer/ringhash/config.go
This follows the settings described in https://github.com/grpc/proposal/pull/338.
Note: a configuration option (preferable taking the form of a dial option, but possibly using a global) is left as a TODO.
Side note: this will mitigate internal issue b/255207468
cc @easwars 
RELEASE NOTES:
- ringhash: impose cap on `max_ring_size` to reduce possibility of OOMs
> Cap min and max ring size to 4K

- server.go
- server_test.go
Make it possible to retry UnaryServerInterceptor in chained UnaryInterceptors. 
RELEASE NOTES:
* server: fix ChainUnaryInterceptor and ChainStreamInterceptor to allow retrying handlers
> server: fix ChainUnaryInterceptor and ChainStreamInterceptor to allow retrying handlers

- internal/testutils/pickfirst/pickfirst.go
- test/balancer_switching_test.go
- test/pickfirst_test.go
In prep for the actual fix for https://github.com/grpc/grpc-go/issues/4392.
This PR moves a helper function out of `test/pickfirst_test.go` into a `pickfirst` package inside `internal/testutils`. This resembles the helper functions we have for checking roundrobin RPCs in `internal/testutils/roundrobin`. This function will be used by the grpclb tests and it seems to help with the flakiness.
> testutils/pickfirst: move helper function to testutils

- test/xds/xds_client_outlier_detection_test.go
- xds/internal/balancer/outlierdetection/e2e_test/outlierdetection_test.go
Fixes #5709. The test was flaking due to time.Sleep(ms), which wasn't really guaranteed to be exactly 1ms on certain systems. This would cause the test to timeout due to numerous time.Sleep(ms) calls exceeding the context deadline. I rewrote the test to verify expected Round Robin distribution instead for the verification step of the ejection, which simply expects calls to be routed across all upstreams and then eventually only round robined to the healthy upstreams.
Doesn't flake on google3/100k runs.
> xDS: Deflake Outlier Detection xDS e2e test

- benchmark/benchmain/main.go
- benchmark/stats/stats.go
The read and write buffer sizes have an impact on performance, but they are currently hard-coded.
This change adds command line flags for running the benchmarks with specific sizes for those buffers.
> benchmark: add a feature for read and write buffer sizes

- xds/internal/xdsclient/transport/loadreport.go
- xds/internal/xdsclient/transport/loadreport_test.go
- xds/internal/xdsclient/transport/transport.go
- xds/internal/xdsclient/transport/transport_ack_nack_test.go
- xds/internal/xdsclient/transport/transport_backoff_test.go
- xds/internal/xdsclient/transport/transport_new_test.go
- xds/internal/xdsclient/transport/transport_resource_test.go
- xds/internal/xdsclient/transport/transport_test.go
- xds/internal/xdsclient/xdsresource/errors.go
This PR is a full-fledged refactor of the transport layer implementation of the xdsclient. It does not touch the existing implementation, and therefore existing implementation will be used until subsequent refactors which will involve the authority/controller/pubsub components.
- New transport implementation in `xds/internal/xdsclient/transport` which supports only xDS v3 transport protocol. We are getting rid of v2 support. So, it does not make sense to add v2 support here. 
- Existing implementation is found in `xds/internal/xdsclient/controller/`.
- New implementation strictly deals only with transport protocol functionality.
- It exposes an API to send requests for xDS resources. Existing implementation exposes a watch style API. A watch should be a higher layer …
> xdsclient: resource-type-agnostic transport layer

- internal/transport/controlbuf.go
- internal/transport/http2_server.go
- test/goaway_test.go
Fixes #4859
By changing the grace period in the test, I was able to stimulate this bug much more reliably, and can confirm this fix makes it pass in 100% of subsequent runs.
~This PR currently includes a 5s sleep before an eventual hard close in case the TCP connection is completely stuck.  It's unclear to me whether this is necessary or desirable, or if it should be a shorter time.  (cc @ejona86)~
> transport/server: flush GOAWAY before closing conn due to max age

- balancer/grpclb/grpclb.go
- balancer/grpclb/grpclb_test.go
- balancer/grpclb/grpclbstate/state.go
- internal/resolver/dns/dns_resolver.go
- internal/resolver/dns/dns_resolver_test.go
There is more cleanup that *can* be done on these tests, but given that we don't care that much about grpclb, I had to stop here. I was able to get it down to `1` failure in `100K` across all tests in this package, and that too looked like some infra flake where a backend did not spin up properly.
Fixes https://github.com/grpc/grpc-go/issues/4392.
> grpclb: improve grpclb tests

- security/advancedtls/crl_test.go
This behavior should be covered by a combination of existing unit tests, but I wanted to add a more integration-style test where we test the codepath of the cache entry expiring a crl for which a cert is unrevoked, then fetching a new CRL where a cert in the chain is revoked.
> security/advancedtls: add test for crl cache expiration behavior

- balancer/rls/control_channel_test.go
Starting in Go1.20, the `tls` package also adds to the returned error when a handshake failure happens. So, while previously the returned error looked something like:
```
"transport: authentication handshake failed: x509: certificate is valid for *.test.example.com, not authority-mismatch"
```
Going forward it will look like:
```
"transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate is valid for *.test.example.com, not authority-mismatch"
```
This PR uses a regex for the expected error string. This way, it will continue to work with older Go versions.
> rls: use a regex for the expected error string

- test/authority_test.go
This got added in a recent commit and I did not notice it at that time. Noticed it only at the time of the import.
I don't know why `vet` didn't flag this though.
> test: remove use of deprecated WithInsecure() API

- xds/internal/balancer/ringhash/ring.go
- xds/internal/balancer/ringhash/ring_test.go
- xds/internal/balancer/ringhash/ringhash.go
The newly added logs like this:
```
ring.go:70 [xds] [ring-hash-lb 0xc000148080] newRing: number of subConns is 1, minRingSize is 1024, maxRingSize is 4096  (t=+3.468892ms)
ring.go:74 [xds] [ring-hash-lb 0xc000148080] newRing: normalized subConn weights is [{0xc0001145a0 1}]  (t=+3.485234ms)
ring.go:85 [xds] [ring-hash-lb 0xc000148080] newRing: creating new ring of size 1024  (t=+3.497625ms)
```
Fixes https://github.com/grpc/grpc-go/issues/5781
> ringhash: add logs to surface information about ring creation

- internal/testutils/xds/e2e/server.go
- internal/testutils/xds/e2e/setup_management_server.go
- test/xds/xds_client_ack_nack_test.go
- test/xds/xds_client_affinity_test.go
- test/xds/xds_client_federation_test.go
- test/xds/xds_client_integration_test.go
- test/xds/xds_client_outlier_detection_test.go
- test/xds/xds_client_retry_test.go
- test/xds/xds_rls_clusterspecifier_plugin_test.go
- test/xds/xds_security_config_nack_test.go
- test/xds/xds_server_integration_test.go
- test/xds/xds_server_rbac_test.go
- test/xds/xds_server_serving_mode_test.go
- xds/csds/csds_test.go
- xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
- xds/internal/httpfilter/fault/fault_test.go
- xds/internal/test/e2e/controlplane.go
- xds/internal/xdsclient/e2e_test/authority_test.go
- xds/internal/xdsclient/e2e_test/cds_watchers_test.go
- xds/internal/xdsclient/e2e_test/eds_watchers_test.go
- xds/internal/xdsclient/e2e_test/federation_watchers_test.go
- xds/internal/xdsclient/e2e_test/lds_watchers_test.go
- xds/internal/xdsclient/e2e_test/misc_watchers_test.go
- xds/internal/xdsclient/e2e_test/rds_watchers_test.go
- xds/internal/xdsclient/transport/transport_ack_nack_test.go
- xds/internal/xdsclient/transport/transport_backoff_test.go
Fixes https://github.com/grpc/grpc-go/issues/5770.
> xds: pass options by value to helper routines which setup the management server in tests

- clientconn.go
- internal/transport/controlbuf.go
- internal/transport/handler_server.go
- internal/transport/http2_client.go
- internal/transport/http2_server.go
- internal/transport/transport.go
- internal/transport/transport_test.go
- server.go
A flaky keepalive test is trying to read and write to a closed network connection. In some of the cases, the server was receiving too many pings, which led to one of the root causes of flakiness and the subsequent fix, but I couldn't figure out why the network connection was closing for any other case. Discussing this, the go team realized that the transport layer logs with respect to transport and connection closure were very sparse, and populating logs with information as to why transports and connections were triggered to close could help a user debug.
RELEASE NOTES:
* transport: Added logs for transport and connection closure
> Added logs for reasons causing connection and transport close

- test/xds/xds_security_config_nack_test.go
Addresses a test issue leading to some flakiness in https://github.com/grpc/grpc-go/issues/5231.
> test/xds: minor cleanup in xDS e2e test

- gcp/observability/logging_test.go
- internal/binarylog/method_logger.go
This PR adds accounting for the key bytes in metadata truncation, whereas previously it was not accounting for the key, just the value. This makes it consistent with other languages accounting, which is the length of key + value.
The added test fails on master (logs the metadata) but works (doesn't log the metadata) with my fix.
> binarylog: Account for key in metadata truncation

- internal/testutils/pickfirst/pickfirst.go
Fixes https://github.com/grpc/grpc-go/issues/5849.
> testutils: do a better job of verifying pick_first in tests

- internal/transport/handler_server.go
- internal/transport/handler_server_test.go
- server.go
Non-servicable HTTP requests from clients previously resulted in an HTTP 500 response, but no error exists within the server; the client simply sent a malformed request. Detect bad requests and return HTTP 400 Bad Request instead of HTTP 500 Internal Server Error.
fixes #5802
RELEASE NOTES:
* transport (net/http server handler): respond to bad HTTP requests with status 400 (Bad Request) instead of 500 (Internal Server Error).
> transport/http2: use HTTP 400 for bad requests instead of 500

- internal/transport/http2_server.go
- test/goaway_test.go
- test/servertester.go
Partially addresses #5786. Two GoAway pings were previously closing a closed channel, this PR adds protection with respect to the drainChan closing (used as a signal to write second GoAway frame). We still to derive the underlying root cause as to why two goaway ping acks are being sent from the Swift client.
RELEASE NOTES:
* transport: Fixed closing a closed channel panic in handlePing
> transport: Fix closing a closed channel panic in handlePing

- xds/internal/xdsclient/singleton.go
Log xDS bootstrap so that we can better debug DirectPath issues.
C++: https://github.com/grpc/grpc/pull/31797
Java: https://github.com/grpc/grpc-java/pull/9731
RELEASE NOTES:
* xdsclient: log node ID with verbosity INFO
> xdsclient: log node ID with verbosity INFO

- default_dial_option_server_option_test.go
- dialoptions.go
- internal/internal.go
This PR adds a join Dial Option. It also contains tests for this join Dial Option and the already present join Server Option.
> grpc: Add join Dial Option

- test/end2end_test.go
The precise behavior of the test https server is subject a raceyness around the timing of when TCP packets are sent from client to server, and when we tell the server to stop, so we need to account for both of possible error messages
1. If the call to ss.S.Stop() causes the server's sockets to close while there's still in-fight data from the client on the TCP connection, then the kernel can send an RST back to the client (also see https://stackoverflow.com/questions/33053507/econnreset-in-send-linux-c). Note that while this condition is expected to be rare due to the rpcStartedOnServer synchronization, in theory it should be possible, e.g. if the client sends a BDP ping at the right time.
2. If, for example, the call to ss.S.Stop() happens after the RPC headers have been received at the …
> test: fix raceyness check to deflake test http server

- balancer/balancer.go
- clientconn.go
- picker_wrapper.go
- stream.go
- test/balancer_test.go
- New field added to `balancer.PickResult`. LB policies can use this to inject per-call arbitrary metadata.
- Arbitrary metadata returned by LB policies is then plumbed all the way to the place where new streams are created, and these are sent out as part of the HEADERS frame.
RELEASE NOTES:
- balancer: support injection of per-call metadata from LB policies
> balancer: support injection of per-call metadata from LB policies

- interop/test_utils.go
- interop/xds_federation/client.go
We can use this test client to perform RPCs at some QPS to two different XDS based services, concurrently from the same process, to exercise the XDS federation logic.
cc @dfawley 
> interop: add test client for use in xDS federation e2e tests

- balancer/rls/picker.go
- balancer/rls/picker_test.go
Follow-up from https://github.com/grpc/grpc-go/pull/5853.
RELEASE NOTES:
- rls: propagate headers received in RLS response to backends
> rls: propagate headers received in RLS response to backends

- clientconn.go
- internal/transport/http2_client.go
- internal/transport/transport.go
- internal/transport/transport_test.go
This diff simplifies the transport code a little by removing onGoAway func and moving the logic into onClose. Updating tests to remove the onGoAway param
> transport: simplify httpClient by moving onGoAway func to onClose

- balancer/rls/balancer.go
- balancer/rls/balancer_test.go
- balancer/rls/helpers_test.go
- balancer/rls/picker_test.go
- internal/balancergroup/balancergroup.go
Fixes https://github.com/grpc/grpc-go/issues/5845.
- Split the close `called` and `done` events. This is required to ensure that all goroutines are shut down by the time `Close()` returns. This is pattern is followed in many other places in our codebase.
- Add a `dataCachePurgeHook` field to the `rlsBalancer` type, which is populated from the package global variable of the same name. This variable is overridden in tests to get notified when the data cache is purged. Without this change, the race detector was complaining of a data race.
- `TestUpdateStatePauses` uses a wrapped top-level LB policy which captures state updates returned by the RLS LB policy.  It was flaky because it was possible to miss the `READY` state update. The fix waits for the channel to be `READY` …
> rls: deflake tests

- internal/envconfig/envconfig.go
- internal/envconfig/envconfig_test.go
- internal/envconfig/xds.go
- xds/internal/balancer/ringhash/config.go
- xds/internal/balancer/ringhash/config_test.go
Implement the remaining part of https://github.com/grpc/proposal/pull/338 after #5801 (allowing the maximum size to be overridden).
RELEASE NOTES:
* xds/ringhash: introduce `GRPC_RING_HASH_CAP` environment variable to override the maximum ring size.
> ringhash: allow overriding max ringhash size via environment variable

- Documentation/grpc-auth-support.md
- credentials/oauth/oauth.go
- examples/features/authentication/README.md
- examples/features/authentication/client/main.go
- examples/features/interceptor/client/main.go
- interop/client/client.go
Fixes #5415
SUMMARY OF CHANGES
* Mark `oauth.NewOauthAccess` as deprecated, pointing to `oauth.TokenSource`
* Change authentication and interceptor example clients to use `oauth.TokenSource`
* Change interop to use `oauth.TokenSource`
RELEASE NOTES:
* Mark `oauth.NewOauthAccess` as deprecated
> oauth: mark `NewOauthAccess` as deprecated and update examples to use `TokenSource`

- stream.go
The caller should not modify the message after calling SendMsg, since the tracing library and stats.Handler handle the message lazily.
xref: #5857 
> stream: update ServerStream.SendMsg doc

- xds/internal/balancer/priority/balancer.go
- xds/internal/balancer/priority/balancer_child.go
- xds/internal/balancer/priority/balancer_priority.go
Minor improvements to priority LB policy's logging:
- Start log lines with upper case wherever possible
- Downgrade commonly occurring log lines from `Info` to `Debug`. The latter is nothing but `Info` at verbosity `2`.
- Change some `Warning` lines to `Debug`. These log lines were not pointing to any problem, but were occurring so frequently that they were causing log spam.
> priority: improve and reduce verbosity of logs

- xds/internal/xdsclient/authority.go
- xds/internal/xdsclient/clientimpl_watchers.go
- xds/internal/xdsclient/e2e_test/cds_watchers_test.go
- xds/internal/xdsclient/e2e_test/eds_watchers_test.go
- xds/internal/xdsclient/e2e_test/lds_watchers_test.go
- xds/internal/xdsclient/e2e_test/rds_watchers_test.go
- xds/internal/xdsclient/e2e_test/resource_update_test.go
This PR contains fixes to the following couple of issues:
- When an LDS/CDS response does not contain a requested resource, the xDS client should not throw the `resource-not-found` error unless the server had responded with that resource earlier (and therefore the resource can be found in the cache). In this scenario, the xDS client should wait for the resource watch timer to expire before throwing the `resource-not-found` error. 
- This handles the following scenario:
- xDS client requests resources `{A, B}` at time `T0`.
- xDS client requests resources `{A, B, C}` at time `T1`.
- Management server receives first request and responds with resources `{A, B}` at `T2`.
- Management server receives second request and responds with resources `{A, B, C}` at `T3`.
- With this fix, the xDS …
> xdsclient: handle resource not found errors correctly

- test/xds/xds_client_federation_test.go
- test/xds/xds_client_integration_test.go
https://github.com/grpc/grpc-go/issues/5429 was taken care of by https://github.com/grpc/grpc-go/pull/5776.
This PR one adds tests alone.
Fixes https://github.com/grpc/grpc-go/issues/5429
> test/xds: add tests for scenarios where authority in resource name is not specified in bootstrap config

- rpc_util.go
Document the defaults for MaxCallRecvMsgSize and MaxCallSendMsgSize similar to how it is documented in the server options:
https://pkg.go.dev/google.golang.org/grpc#MaxRecvMsgSize
https://pkg.go.dev/google.golang.org/grpc#MaxSendMsgSize
> grpc: document defaults in MaxCallMsgSize functions

- binarylog/binarylog_end2end_test.go
- binarylog/sink.go
- internal/binarylog/method_logger.go
- internal/binarylog/method_logger_test.go
- internal/binarylog/sink.go
The binarylog proto is currently used by the `binarylog` package and also by the `observability` module. The latter renames this import as `binlogpb`, while the former currently renames it as `pb`. Renaming it as `binlogpb` is more readable, and having it being consistently renamed will help us with import renaming in google3.
> binarylog: consistently rename imports for binarylog proto

- balancer/rls/balancer.go
- balancer/rls/cache.go
- balancer/rls/cache_test.go
- balancer/rls/picker.go
- The data cache and the pending request map were guarded by a `sync.RWMutex`. In the RPC path, the cache lookup was done under a read-lock, while most of the other operations were done under a write-lock. This was under the assumption that a cache lookup was a read operation. But as it turns out, the cache lookup modifies the LRU cache because it makes the matched entry the most-recently-used.
- With this change, we are getting rid of the `sync.RWMutex` and moving to a regular `sync.Mutex`.
- When handling a config update, the RLS policy could end up resizing the data cache. This was being done without holding the lock. This change brings the resize operation under the lock.
- Get rid of the `iterateAndRun` method on the `dataCache` type. 
- I'm still not sure whether …
> rls: fix a data race involving the LRU cache

- xds/internal/xdsclient/clientimpl_loadreport.go
In `clientImpl.ReportLoad()`, once we get a reference to the appropriate `authority` object, we are supposed to increment the reference count using a call to `authority.refLocked()`. 
The documentation on this function says:
```golang
// Increments the reference count. Caller must hold parent's authorityMu.
```
We were releasing the mutex right before incrementing the reference count, and this was not caught by any of our unit tests. It was only caught when I ran a prober binary with the race flag enabled.
RELEASE NOTES:
- xdsclient: fix race which can happen when multiple load reporting calls are made at the same time.
> xdsclient: fix race in load report implementation

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
Reverts grpc/grpc-go#5932.
Reverted in favor of better syntax suggested here: https://github.com/grpc/grpc-node/pull/2323#pullrequestreview-1248043432. This fix will be sent as another PR for the convenience of backporting.
> Revert "xds interop: Fix buildscripts not continuing on a failed test suite"

- balancer/grpclb/grpclb_remote_balancer.go
- benchmark/benchmain/main.go
- benchmark/benchmark.go
- benchmark/client/main.go
- benchmark/server/main.go
- benchmark/worker/benchmark_client.go
- benchmark/worker/benchmark_server.go
- clientconn.go
- examples/features/health/client/main.go
- examples/features/interceptor/server/main.go
- examples/features/metadata_interceptor/client/main.go
- examples/route_guide/client/client.go
- examples/route_guide/server/server.go
- internal/transport/http2_client.go
- interop/fake_grpclb/fake_grpclb.go
- interop/http2/negative_http2_client.go
- interop/server/server.go
- interop/xds/server/server.go
- pickfirst.go
- rpc_util.go
- security/advancedtls/crl.go
- server.go
- service_config.go
- stress/client/main.go
- stress/metrics_client/main.go
- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/clusterspecifier/rls/rls.go
- xds/internal/xdsclient/xdsresource/unmarshal_cds.go
- xds/internal/xdsclient/xdsresource/unmarshal_rds.go
Mostly add missing colons but also address few other minor issues.
It's confusing to read an error message without a colon for nesting, so that was the main motivation for the change. Happened to me couple of times and I couldn't find the whole string anywhere in code, wasted some time on it.
RELEASE NOTES:
* none
> *: add missing colon to errorf messages to improve readability

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
> xds interop: Fix buildscripts not continuing on a failed test suite

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
Backport of #5937 to v1.52.x.
---
> xds interop: Fix buildscripts not continuing on a failed test suite (v1.52.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
Backport of #5937 to v1.51.x.
---
> xds interop: Fix buildscripts not continuing on a failed test suite (v1.51.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
Backport of #5937 to v1.48.x.
---
> xds interop: Fix buildscripts not continuing on a failed test suite (v1.48.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
Backport of #5937 to v1.47.x.
---
> xds interop: Fix buildscripts not continuing on a failed test suite (v1.47.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
Backport of #5937 to v1.45.x.
---
> xds interop: Fix buildscripts not continuing on a failed test suite (v1.45.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
Backport of #5937 to v1.50.x.
---
> xds interop: Fix buildscripts not continuing on a failed test suite (v1.50.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
Backport of #5937 to v1.49.x.
---
> xds interop: Fix buildscripts not continuing on a failed test suite (v1.49.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
Backport of #5937 to v1.44.x.
---
> xds interop: Fix buildscripts not continuing on a failed test suite (v1.44.x backport)

- test/kokoro/psm-security.sh
- test/kokoro/xds_k8s_lb.sh
Backport of #5937 to v1.43.x.
---
> xds interop: Fix buildscripts not continuing on a failed test suite (v1.43.x backport)

- internal/transport/defaults.go
In [this](https://github.com/grpc/grpc-go/pull/5889) previous change, `maxStreamID` was set to 75% of uint32. But according to the http2 spec. Stream are identified with an unsigned 31-bit integer
This PR will fix it
> transport: fix maxStreamID to align with http2 spec

- internal/transport/handler_server.go
- internal/transport/handler_server_test.go
- internal/transport/http2_server.go
- internal/transport/transport_test.go
In addition to the 415 for an unsupported content-type, this also has the server respond with a 400 in the face of malformed application header values (invalid grpc-timeout, invalid base64-encoded binary header). The `NewServerHandlerTransport` function (for using the server with existing `net/http` server) already handled such requests this way. So now they behave consistently.
Fixes #5892
RELEASE NOTES:
- server: fix a few issues where grpc server uses RST_STREAM for non-HTTP/2 errors
> server: fix a few issues where grpc server uses RST_STREAM for non-HTTP/2 errors

- xds/internal/xdsclient/transport/loadreport.go
- xds/internal/xdsclient/transport/loadreport_test.go
- xds/internal/xdsclient/transport/transport.go
Existing code was using a single channel in the xDS `Transport` type to ensure that the LRS goroutine exited when closing LRS streams. This was leading to a double close of the associated channel when multiple streams were started and closed. This PR changes the logic such that a new channel is created every time a new stream is created. Since we know that there can be only one active stream per transport, this approach works perfectly.
Fixes [internal P1 issue](https://buganizer.corp.google.com/issues/266436373).
This also needs to be backported to `v1.52.x`.
RELEASE NOTES:
- xds: fix panic involving double close of channel in xDS transport
> xds: fix panic involving double close of channel in xDS transport

- gcp/observability/config.go
- gcp/observability/logging.go
- gcp/observability/logging_test.go
This PR iterates what a valid method name is in the observability config, according to offline discussions.
From Doug, this can be summarized as:
```
Allowed patterns:
- *
- service/*
- service/method
- service and method may not contain slash
```
RELEASE NOTES:
* gcp/observability: update method name validation
> gcp/observability: update method name validation

- encoding/encoding.go
- encoding/encoding_test.go
Previously, registering multiple compressors with the same name would append the name repeatedly in `RegisteredCompressorNames`. This PR fixes it.
> encoding: fix duplicate compressor names

- balancer/grpclb/grpclb.go
- balancer/rls/balancer.go
- clientconn.go
- clientconn_parsed_target_test.go
- examples/features/load_balancing/client/main.go
- examples/features/name_resolving/client/main.go
- internal/resolver/dns/dns_resolver.go
- internal/resolver/dns/dns_resolver_test.go
- internal/resolver/passthrough/passthrough.go
- resolver/resolver.go
- xds/internal/balancer/clusterresolver/priority_test.go
- xds/internal/balancer/clusterresolver/resource_resolver_dns.go
- xds/internal/balancer/clusterresolver/resource_resolver_test.go
- xds/internal/resolver/xds_resolver_test.go
Fixes #5796 
Summary of Changes
* resolver: deprecated field `resolver.Target.Endpoint` has been removed and replaced by `resolver.Target.Endpoint()`.
> resolver: replace resolver.Target.Endpoint field with Endpoint() method

- balancer/grpclb/grpclb.go
- balancer/grpclb/grpclb_test.go
- balancer/grpclb/state/state.go
- internal/resolver/dns/dns_resolver.go
- internal/resolver/dns/dns_resolver_test.go
RELEASE NOTES:
* grpclb: rename grpclbstate package back to state
> Cherry pick: grpclb: rename `grpclbstate` package back to `state` (#5962)

- internal/testutils/xds/e2e/clientresources.go
- xds/internal/resolver/xds_resolver_test.go
- xds/internal/xdsclient/e2e_test/federation_watchers_test.go
- xds/internal/xdsclient/e2e_test/misc_watchers_test.go
- xds/internal/xdsclient/e2e_test/rds_watchers_test.go
> xds/resolver: cleanup tests to use real xDS client 5/n

- xds/internal/resolver/xds_resolver_test.go
> xds/resolver: cleanup tests to use real xDS client 3/n

- xds/internal/xdsclient/transport/loadreport.go
- xds/internal/xdsclient/transport/loadreport_test.go
- xds/internal/xdsclient/transport/transport.go
> Cherrypick 5959: xds: fix panic involving double close of channel in xDS transport

- xds/internal/balancer/clusterresolver/clusterresolver_test.go
- xds/internal/balancer/clusterresolver/config_test.go
- xds/internal/balancer/clusterresolver/configbuilder_test.go
- xds/internal/balancer/clusterresolver/priority_test.go
- xds/internal/balancer/clusterresolver/resource_resolver_test.go
Addresses [this TODO comment](https://github.com/grpc/grpc-go/blob/3930549b38c0fc4cd94a95efccf7cef5f90515fd/xds/internal/balancer/clusterresolver/priority_test.go#L65) from https://github.com/grpc/grpc-go/pull/5852.
Summary of Changes
> tests: fix spelling of variable

- internal/transport/controlbuf.go
- test/gracefulstop_test.go
- test/servertester.go
- test/stream_cleanup_test.go
Fixes #5930 
RELEASE NOTES:
* server: after GracefulStop, ensure connections are closed when final RPC completes
> server: after GracefulStop, ensure connections are closed when final RPC completes

- clientconn.go
- default_dial_option_server_option_test.go
- dialoptions.go
- internal/internal.go
- server.go
This pr pulls out the logic for dialing into a new internal only dial function which takes a knob on whether to apply global dial options or not. This will be used by the observability module to prevent cyclic emissions of telemetry data due to the telemetry data being exported to a backend.
> client: add an option to disable global dial options

- xds/internal/xdsclient/bootstrap/bootstrap.go
This is the first in a set of PRs to reduce chattiness of xdsclient logs. Addresses https://github.com/grpc/grpc-go/issues/5839.
This PR addresses logs in the `xdsclient/bootstrap` package:
- Removes the `xds: ` prefix for log messages. These are used only for error strings in general.
- Bootstrap content was being logged two times. Removed the redundancy.
- Made bootstrap logs use the `Debugf()` method on the prefix logger which logs at severity `INFO` and verbosity `2`.
> xdsclient/bootstrap: reduce chattiness of logs

- xds/internal/server/listener_wrapper.go
- xds/server.go
- xds/xds.go
Addresses https://github.com/grpc/grpc-go/issues/5839
Minor log cleanup for xDS servers:
- Remove logs about registering and cancelling watches. These are anyways logged by the `authority` struct in the `xdsclient` package.
- Stop logging the update for the resource being watched. This is also logged at lower levels of the xDS stack.
> xds/server: reduce chattiness of logs

- balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
- channelz/grpc_channelz_v1/channelz_grpc.pb.go
- cmd/protoc-gen-go-grpc/grpc.go
- credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
- examples/features/proto/echo/echo_grpc.pb.go
- examples/helloworld/helloworld/helloworld_grpc.pb.go
- examples/route_guide/routeguide/route_guide_grpc.pb.go
- health/grpc_health_v1/health_grpc.pb.go
- internal/proto/grpc_lookup_v1/rls_grpc.pb.go
- interop/grpc_testing/benchmark_service_grpc.pb.go
- interop/grpc_testing/report_qps_scenario_service_grpc.pb.go
- interop/grpc_testing/test_grpc.pb.go
- interop/grpc_testing/worker_service_grpc.pb.go
- profiling/proto/service_grpc.pb.go
- reflection/grpc_reflection_v1/reflection_grpc.pb.go
- reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go
- reflection/grpc_testing/test_grpc.pb.go
- stress/grpc_testing/metrics_grpc.pb.go
- test/grpc_testing/test_grpc.pb.go
Original issue: https://github.com/grpc/grpc-go/issues/5876
- The principal change is an update to the `cmd/protoc-gen-go-grpc/grpc.go` command to export additional symbols for all full method paths. Existing behaviour is untouched beyond the additional symbols.
- Updated generated protos to include new symbols throughout the repo for all `*.pb.go`
- Assuming the proposed change is acceptable, should I put it behind a command option or leave it on by default?
All feedback welcome! :)
RELEASE NOTES:
- TBD
> cmd/protoc-gen-go-grpc: export consts for full method names

- codes/code_string.go
- codes/codes.go
- internal/internal.go
- stats/opencensus/client_metrics.go
- stats/opencensus/e2e_test.go
- stats/opencensus/go.mod
- stats/opencensus/opencensus.go
- stats/opencensus/server_metrics.go
- stats/opencensus/stats.go
This PR adds OpenCensus metrics to gRPC Go. The e2e tests all test at the exporter level and expect certain metrics emissions from RPC's being performed. Based on #5919.
RELEASE NOTES:
* stats/opencensus: Add OpenCensus metrics support
> stats/opencensus: Add OpenCensus metrics support

- .github/workflows/codeql-analysis.yml
I noticed that even though codeQL runs have green, there is an error in logs which is due to the usage of codeQL action v1 which is deprecated. [Here is an example of the error](https://github.com/grpc/grpc-go/actions/runs/4068816780).
This diff bumps up the version to v2 as per the instructions [here](https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/)
> github: update codeQL action to v2

- clientconn_test.go
- internal/transport/transport_test.go
We are noticing a timeout issue in tests. The degree of stress test on some of them can be reduced since 1. we haven't seen these tests fail in a long time. 2. Shortening them doesn't completely invalidate the test case. 
Here are some tests that are taking longer than expected
```
Test/PingPong1KB 5.00s
Test/PingPong64KB 5.00s
Test/PingPong1B 5.05s
Test/PingPong1MB 5.05s
Test/BackoffWhenNoServerPrefaceReceived 5.45s
Test/ClientMix 10.57s
```
After the modification here is the new time taken per tests
```
Test/PingPong1B (1.06s)
Test/PingPong1KB (1.05s)
Test/PingPong1MB (1.00s)
Test/PingPong64KB (1.00s)
Test/BackoffWhenNoServerPrefaceReceived (1.73s)
Test/ClientMix (1.14s)
```
So yay, this diff reduces 25 seconds in a test run. @dfawley let me know your thoughts. 
RELEASE NOTES:
* tests: …
> tests: reduce the degree of stress testing in long running tests

- clientconn.go
- default_dial_option_server_option_test.go
- dialoptions.go
- internal/internal.go
This PR reverts dialWithGlobalOption. We decided to do this with a dial option instead for seamless integration with gRPC-Go Client Libraries. This will be manually added to the import.
> client: Revert dialWithGlobalOption

- resolver/resolver.go
Extend the Godoc for resolver.ClientConn.UpdateState with a description of how resolvers should handle returned errors.
The description is based on the explanation of dfawley in https://github.com/grpc/grpc-go/issues/5048
RELEASE NOTES:
- resolver: document expected error handling of UpdateState errors
> resolver: document handling UpdateState errors by resolvers

- clientconn.go
- default_dial_option_server_option_test.go
- dialoptions.go
- internal/internal.go
This PR adds a dial option to disable global dial options. This will be used in the observability module only, thus it is kept internal. The intended use case is to replace the observability modules instrumentation components registered globally (binary logger, in future: interceptor, and stats handler) to new components (just the interceptor and stats handler) for certain Client Conns (disableGlobalDialOptions + opencensus.DialOption(disableTrace = true). This is to avoid a loop where exporters using grpc.ClientConns create their own telemetry data due to the global registration of instrumentation components.
> client: Add dial option to disable global dial options

- .github/workflows/testing.yml
The latest Go release, v 1.20, was released on Feb-01-2020. Modifying tests to support v1.20 and remove tests for v.17.
Note for GitHub Action users: the Go version must be quoted ('1.20') otherwise it is interpreted as a float (1.2).
Test with new version run on my fork: https://github.com/arvindbr8/grpc-go/actions/runs/4168025844
PS (+TIL): seems like GH picked up the new tests from the yml file. And did not run the old tests in this PR itself. 
RELEASE NOTES:
* github: update tests to use go latest release 1.20
> github: update tests to use go version 1.20

- stats/opencensus/e2e_test.go
- stats/opencensus/opencensus.go
- stats/opencensus/stats.go
- stats/opencensus/trace.go
This PR adds the instrumentation logic for collecting OpenCensus traces support.
RELEASE NOTES:
* stats/opencensus: Add OpenCensus traces support
> stats/opencensus: Add OpenCensus traces support

- clientconn.go
- resolver/resolver.go
- resolver_test.go
Also test the case-senstiveness of the checks.
Fixes https://github.com/grpc/grpc-go/issues/6011.
RELEASE NOTES:
* resolver: update Resolver.Scheme() docstring to mention requirement of lowercase scheme names
> resolver: update Resolver.Scheme() docstring to mention requirement of lowercase scheme names

- gcp/observability/go.mod
- gcp/observability/go.sum
- gcp/observability/opencensus.go
This PR switches the gcp/observability module to use the newly written opencensus instrumentation code rather than the instrumentation code in their respository.
> gcp/observability: Switch observability module to use new opencensus instrumentation code

- rpc_util.go
- stats/opencensus/client_metrics.go
- stats/opencensus/e2e_test.go
- stats/opencensus/opencensus.go
- stream.go
This PR adds per call latency metric in the open census interceptor.
RELEASE NOTES:
* stats/opencensus: Add per call latency metric
> stats/opencensus: Add per call latency metric

- gcp/observability/observability_test.go
- gcp/observability/opencensus.go
This PR switches the observability module to use the new views in the new instrumentation code rather than the old ones. It adds all the views that are currently present defined in Yashes list of metrics for GA. The views needed to still be added are the Compressed Sent/Recv for both client and server (we have uncompressed equivalents), and also per call latency, which is in flight in #6017.
> gcp/observability: Register new views

- stats/opencensus/e2e_test.go
- stats/opencensus/opencensus.go
- stats/opencensus/trace.go
This PR adds top level call span defined in A45. This is needed to correctly link logs and traces for observabliltiy GA. Note that this doesn't add the attributes defined in A45, as that is not important for observability GA. Also note that I couldn't avoid sticking span directly in context and use the shared wrapper data to avoid the o(n) search up the context tree as the span needs to be in the context for StartSpan() in TagRPC() called from the rpc attempt to work.
RELEASE NOTES:
* stats/opencensus: Add top level call span
> stats/opencensus: Add top level call span

- internal/testutils/xds/e2e/clientresources.go
- test/xds/xds_rls_clusterspecifier_plugin_test.go
- xds/internal/resolver/cluster_specifier_plugin_test.go
- xds/internal/resolver/xds_resolver_test.go
- Make it possible to configure the cluster specifier type in RouteConfiguration resources created by the `e2e` package. This is in the same style of how Cluster resources are configurable currently.
- Change test in `test/xds/xds_rls_clusterspecifier_plugin_test.go` to use the new helpers.
- Change tests in `xds/internal/resolver/cluster_specifier_plugin_test.go` to use the new helpers and thereby use a real management server and a real xDS client instead of fake ones.
- Also merge tests `TestXDSResolverClusterSpecifierPlugin` and `TestXDSResolverClusterSpecifierPluginConfigUpdate` into one, as the latter performs all steps in the former followed by an additional step.
- Change tests in `xds/internal/resolver/xds_resolver_test.go` to use the new helpers where …
> testing: add helpers to configure cluster specifier plugin type

- internal/grpclog/prefixLogger.go
- xds/internal/xdsclient/transport/loadreport.go
- xds/internal/xdsclient/transport/transport.go
This is one among a set of PRs to reduce chattiness of xdsclient logs. Addresses https://github.com/grpc/grpc-go/issues/5839.
This PR addresses logs in the `xdsclient/transport` package:
- Adds a `V` method to the `PrefixLogger` type to make it possible to log at specified verbosity.
- Transport logs which represent infrequent events like creating a transport, creating a stream, closing a stream etc are logged at `Info`.
- Transport logs which represent per request/response events take the following approach
- if the set verbosity level is less than `perRPCVerbosityLevel`, a terse message at `Debug` is logged
- otherwise, a detailed message containing the full request/response message is logged at `Debug`
With this change, if the user sets severity to `INFO` and does not set verbosity …
> xdsclient/transport: reduce chattiness of logs

- internal/transport/keepalive_test.go
This PR fixes the flaky keep alive test. This test would flake since the MinTime configuration set on the server used the default of 5 times, so it would count the client pings after the first (configured to send every second) as a ping strike, which once it hit 3 (why race was infrequent - right on the 4s line that time.Sleep is sleeping for in test) would cause a GO_AWAY to be sent, closing the connection.
Verified on google3 with 10k runs.
> internal/transport: Fix flaky keep alive test

- internal/transport/keepalive_test.go
> internal/transport: reduce running time of test from 5s to 1s

- internal/metadata/metadata.go
- internal/metadata/metadata_test.go
- stream.go
- test/metadata_test.go
fix: https://github.com/grpc/grpc-go/issues/5913
RELEASE NOTES:
* metadata: fix validation logic and properly validate metadata appended via AppendToOutgoingContext.
> metadata: fix validation issues

- channelz/service/service_sktopt_test.go
- channelz/service/service_test.go
Code in google3 panics when `cmpopts.IgnoreUnexported` is used for protos instead of `protocmp.Transform`. The internal version of the `cmp` package is smarter. See [here](https://g3doc.corp.google.com/third_party/golang/cmp/g3doc/protocmp.md?cl=head).
> channelz: use protocmp.Transform() to compare protos

- metadata/metadata.go
This PR lowercases appended metadata. This was causing errors in google3, as docstrings stated that we lowercase any characters which are uppercased.
RELEASE NOTES:
* metadata: Lowercase appended metadata
> metadata: Lowercase appended metadata

- xds/internal/balancer/clusterresolver/clusterresolver.go
- xds/internal/balancer/clusterresolver/resource_resolver.go
- xds/internal/balancer/clusterresolver/resource_resolver_dns.go
- xds/internal/balancer/clusterresolver/resource_resolver_eds.go
- Define a new `topLevelResolver` interface for the concrete resolver implementations to use
- This ensures that the resolver implementations don't have to grab locks on the top level resolver and access internal fields.
- Rename existing interface `discoveryMechanism` to `endpointsResolver`.
- The new name better describes the interface being implemented
- We currently have too many other names which contain some form of `discovery mechanism` in there. So, renaming this also helps with distinguishing existing types in a better way. 
- Rename existing type `resolverMechanismTuple` to `discoveryMechanismAndResolver`
- The new name is more descriptive and clearly indicates what it contains
- Remove the `dmKey` field from this type as this was unused.  
- Handle errors …
> clusterresolver: cleanup resource resolver implementation

- gcp/observability/exporting.go
- gcp/observability/go.mod
- gcp/observability/logging.go
- gcp/observability/logging_test.go
- gcp/observability/opencensus.go
This PR disables logging and traces on channels to cloud ops backends, preventing infinite recursive loops of logging and tracing if the probability sampler is 1.
> gcp/observability: Disable logging and traces on channels to cloud ops backends

- gcp/observability/go.mod
- gcp/observability/go.sum
- gcp/observability/observability_test.go
- gcp/observability/opencensus.go
This PR adds client api latency (full call latency) to o11y callsite and updates go.mod to point to latest commit of stats/opencensus.
RELEASE NOTES:
* gcp/observability: Add Client API Latency to registered views
> stats/opencensus: Add client api latency and upgrade go.mod

- xds/internal/xdsclient/tests/authority_test.go
- xds/internal/xdsclient/tests/cds_watchers_test.go
- xds/internal/xdsclient/tests/dump_test.go
- xds/internal/xdsclient/tests/eds_watchers_test.go
- xds/internal/xdsclient/tests/federation_watchers_test.go
- xds/internal/xdsclient/tests/lds_watchers_test.go
- xds/internal/xdsclient/tests/misc_watchers_test.go
- xds/internal/xdsclient/tests/rds_watchers_test.go
- xds/internal/xdsclient/tests/resource_update_test.go
Fixes https://github.com/grpc/grpc-go/issues/5771
This was raised during one of the code reviews when these tests were rewritten. The idea being, we should try to use the term `e2e_tests` for gRPC-level end to end tests, and not for package level end to end tests.
> xdsclient: move tests from `e2e_test` to `tests` directory

- xds/internal/balancer/ringhash/ring.go
This PR ensures that for every address `$addr`, the string used to compute the hash is `$addr_1`, `$addr_2` .. `$addr_n`. This aligns with implementations in the other languages.
RELEASE NOTES:
- ringhash: ensure addresses are consistenly hashed across updates
> ringhash: ensure addresses are consistenly hashed across updates

- xds/internal/testutils/fakeserver/server.go
- xds/internal/testutils/resource_watcher.go
- xds/internal/xdsclient/authority_test.go
- xds/internal/xdsclient/loadreport_test.go
- xds/internal/xdsclient/tests/misc_watchers_test.go
- xds/internal/xdsclient/tests/resource_update_test.go
- xds/internal/xdsclient/transport/transport.go
- xds/internal/xdsclient/transport/transport_resource_test.go
This PR adds functionality to the xdsclient transport to send the node proto only on the first request on the stream. If the stream breaks, the node proto will be sent on the first request of subsequent streams as well.
Other changes in this PR (mostly testing related)
- New tests to verify behavior added in this PR.
- Move the `testResourceWatcher` type from `authority_test.go` into `xds/internal/testutils` package, and export it.
- Update `authority_test.go` to use the new `TestResourceWatcher` type exported above.
- Enable the `fakeserver.Server` to be started with a `net.Listener` provided by the test.
Fixes https://github.com/grpc/grpc-go/issues/5668.
RELEASE NOTES:
- xdsclient: send Node proto only on first discovery request on ADS stream
> xdsclient: send Node proto only on first discovery request on ADS stream

- server.go
Fixes #5785
Fixes #5815
Before fix: Test/GlobalBinaryLoggingOptions failed 7/10k runs in forge. After fix: 0 failures. (observability test couldn't be reproduced in Forge as per Arvind, but the missing log entry in those tests is the ServerTrailer logging atom, so should be fixed as well).
This PR switches the binary logging call of the server trailer to occur before writing the status. This is to guarantee that when a server logs a server trailer it will happen before the RPC "completes" client side (i.e. returns).
> grpc: Log server trailers before writing status

- rpc_util.go
- server.go
- stats/opencensus/client_metrics.go
- stats/opencensus/e2e_test.go
- stats/opencensus/server_metrics.go
- stats/opencensus/stats.go
- stats/opencensus/trace.go
- stats/stats.go
- stats/stats_test.go
- stream.go
This PR does a few things:
* Fixes the docstrings (the docstrings for WireLength In and Out Payload were incorrect with respect to what they were recording) of InPayload and OutPayload
* Adds a new field (don't change WireLength to not break users) that records the compressed bytes of a message, not including gRPC framing bytes (1 byte compressed flag and 4 byte message length), and transport framing bytes (HTTP/2 framing headers and padding length byte if applicable and padding)
* Uses this new field to record new client and server uncompressed bytes sent/recv metrics
* Uses this new field instead of the previously used WireLength to align with the tracing specs language: "Compressed bytes: Total bytes (compressed) [sent/received] per message; does omit grpc and transport framing bytes." …
> stats/opencensus: New uncompressed metrics and align with tracing spec

- security/advancedtls/advancedtls_integration_test.go
I was wrong in #5368. The flakiness is not caused by the refresh interval. Instead, the short test timeout was causing the `DialContext()` to return an error even if it was non-blocking when a large number of tests are executed simultaneously. The way I think we should do is to stick with the normal time out but cancel the context promptly, instead of deferring it at the end to release resources.
This PR should eliminate the flakiness. Same code change internally [passes](http://sponge2/624273ee-c3ef-4bcc-932d-6962e2cb35b5) 10k runs with gotasn.
> Deflake the integration test.

- xds/internal/xdsclient/xdsresource/unmarshal_rds.go
- xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
fixes #6053 
* xds: NACK route configuration if sum of weights of weighted clusters exceeds uint32_max
> xds: NACK route configuration if sum of weights of weighted clusters exceeds uint32_max

- internal/testutils/xds/e2e/clientresources.go
- test/xds/xds_rls_clusterspecifier_plugin_test.go
Also, switch the previously existing `ClusterOptions` to be passed by value. Other options are passed by value, and switching this to be passed by value makes things consistent.
This PR is a prep PR for the actual changes to be made for https://github.com/grpc/grpc-go/issues/6097.
> testutils: add support for creating endpoint resources with options

- xds/internal/xdsclient/tests/misc_watchers_test.go
The fake xDS management server used in this test (not the go-control-plane) seems more likely to send out responses before being requested from the client. This means that if the test is expecting two requests to be sent by the client (one for the actual request, and one for the ACK), we will only see the actual request. Since the resource is already cached, the client will not send an ACK.
Therefore changing the order of events in the test seems to do the trick. Basically, ensure that the original request is sent out before configuring appropriate resources on the server. That way, we can sure that both the original request and the ACK will get sent out.
Fixes https://github.com/grpc/grpc-go/issues/6092
Ran 100K times on google3 with this fix, and it only flaked once and that too was for …
> xdsclient/tests: fix flaky test NodeProtoSentOnlyInFirstRequest

- interop/observability/run.sh
Each `run.sh` should just pass those parameters through to the interop client/server binaries as-is.
Corresponding framework PR: https://github.com/GoogleCloudPlatform/grpc-gcp-tools/pull/28
> interop/observability: Pass interop parameters to client/server as-is

- internal/transport/controlbuf.go
- internal/transport/http2_client.go
- internal/transport/http2_server.go
- internal/transport/http_util.go
Fixes #6019
As discovered in #6019, closing a connection upon encountering an I/O error can result in loss of data that was sent before the connection was closed.  We previously believed that any data in the TCP connection would still be available to the reader indefinitely, but it appears that is not the case.  This change makes it so we only close the connection from the loopy writer in non-I/O error situations.  If an I/O error causes the loopy writer to exit, we don't need to close the connection, as the reader goroutine will also encounter an I/O error once it is done consuming all the data.
RELEASE NOTES:
* transport: do not close connections when we encounter I/O errors until after all data is consumed
> transport: stop always closing connections when loopy returns

- gcp/observability/exporting.go
- gcp/observability/logging.go
- gcp/observability/logging_test.go
This PR implements Eric logging design changes needed for Observability GA. It a. iterates on the logging schema and b. sets the queueing limit for logs (which when exceeded, logs then write to standard output) and batching delay (how often the data is sent to the backend). This is nicely outlined in the "Changes Since Public Preview" section of Eric's design document.
RELEASE NOTES:
* gcp/observability: Change logging schema and set queue size limit for logs and batching delay
> gcp/observability: Change logging schema and set queue size limit for logs and batching delay

- xds/googledirectpath/googlec2p.go
- xds/googledirectpath/googlec2p_test.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/internal/balancer/clusterimpl/balancer_test.go
- xds/internal/balancer/clusterimpl/clusterimpl.go
- xds/internal/balancer/clusterimpl/tests/balancer_test.go
- xds/internal/balancer/clusterresolver/config_test.go
- xds/internal/resolver/xds_resolver_test.go
- xds/internal/testutils/testutils.go
- xds/internal/xdsclient/authority_test.go
- xds/internal/xdsclient/bootstrap/bootstrap.go
- xds/internal/xdsclient/bootstrap/bootstrap_test.go
- xds/internal/xdsclient/loadreport_test.go
- xds/internal/xdsclient/tests/authority_test.go
- xds/internal/xdsclient/tests/cds_watchers_test.go
- xds/internal/xdsclient/tests/eds_watchers_test.go
- xds/internal/xdsclient/tests/lds_watchers_test.go
- xds/internal/xdsclient/tests/rds_watchers_test.go
- xds/internal/xdsclient/tests/resource_update_test.go
- xds/internal/xdsclient/transport/loadreport_test.go
- xds/internal/xdsclient/transport/transport.go
- xds/internal/xdsclient/transport/transport_ack_nack_test.go
- xds/internal/xdsclient/transport/transport_backoff_test.go
- xds/internal/xdsclient/transport/transport_new_test.go
- xds/internal/xdsclient/transport/transport_resource_test.go
- xds/internal/xdsclient/transport/transport_test.go
- xds/server_test.go
When the `clusterimpl` LB policy receives a config update, it checks if the `load_reporting_server` configuration has changed. If so, it closes the existing LRS stream and creates a new one. 
Unfortunately this equality comparison was broken because the `bootstrap.ServerConfig` struct contains a `grpc.DialOption` to store the configured credentials. The implemention of this dial option (like many others) uses a function pointer which is not very amenable to comparisons. So, even if two configuration specify the same transport credentials, the equality comparison will fail. 
This PR addresses this issue and ensures that the LRS stream is not closed and re-created when the actual `load_reporting_server` config has not changed.
- Add a `ChannelCreds` type in the bootstrap …
> xds: make comparison of server configs in bootstrap more reliable

- gcp/observability/observability_test.go
- gcp/observability/opencensus.go
- stats/opencensus/server_metrics.go
This PR adds compressed metrics to observability module, and also unregisters the views on module closure, synchronizing any recorded data with any exporters registered. It also fixes a naming bug in stats/opencensus. This was not caught in unit tests, as the unit tests in stats/opencensus verified keyed on name. However, the compression/uncompressed bytes measurements are technically correct. After this is merged I will need to get rid of go.mod import directive in gcp/observability and stats/opencensus as this fixes bug in stats/opencensus, which will create new commit hash in that package.
RELEASE NOTES:
* gcp/observability: Add compressed metrics to observability module and synchronize View data with exporter
> gcp/observability: Add compressed metrics to observability module and synchronize View data with exporter

- clientconn.go
This PR partially fixes https://github.com/grpc/grpc-go/issues/5831 by logging the last error when a subchannel connectivity changes to TransientFailure.
Right now, if a grpc client uses healthchecks with misconfigured serviceName and `WithBlock()` dial option it simply gets a timeout error. The problem got much worse by the fact that even with the most verbose debug logs we don't get any useful information about why the connection failed. 
I understand the [reasons](https://github.com/grpc/grpc-go/issues/5831#issuecomment-1341855767) why we don't want to add the healthcheck error information to the actual error that is returned to the user code, but we can at least log this error. 
> client: log last error on subchannel connectivity change

- metadata/metadata_test.go
add benchmarktest for FromIncomingContext and ValueFromIncomingContext, and the result is:
```
goos: darwin
goarch: amd64
pkg: google.golang.org/grpc/metadata
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkFromIncomingContext-12                       4657538               260.4 ns/op           416 B/op          3 allocs/op
BenchmarkValueFromIncomingContext-12            28756804                38.28 ns/op           16 B/op          1 allocs/op
PASS
ok      google.golang.org/grpc/metadata 3.475s
```
> add benchmark test for FromIncomingContext and ValueFromIncomingContext

- credentials/alts/internal/handshaker/handshaker.go
- credentials/alts/internal/handshaker/handshaker_test.go
The existing code creates the stream to the ALTS handshaker service before checking that we are not exceeding the max number of concurrent connections, which defeats the purpose of having the max pending handshakes cap.
~While we're here, I also lower the `maxPendingHandshakes` cap to 40, to match up with the C-core code and with the current expectations of the ALTS handshaker service. (We will be lowering this cap again in the future.)~
> credentials/alts: defer ALTS stream creation until handshake time

- gcp/observability/observability_test.go
- gcp/observability/opencensus.go
- stats/opencensus/client_metrics.go
- stats/opencensus/e2e_test.go
- stats/opencensus/server_metrics.go
This PR adds the message prefix to certain metrics, which was an inconsistency of our repository vs. the metrics spec.
> stats/opencensus: Add message prefix to metrics names

- status/status.go
- status/status_test.go
RELEASE NOTES:
- status: `status.Code` and `status.FromError` handle wrapped errors
> status: handle wrapped errors

- stats/opencensus/e2e_test.go
- stats/opencensus/opencensus.go
This PR adds the removal of the leading slash when taking per call metrics (api_latency). This was speced as a team in previous observability discussions. This was causing problems in tests, which expect the leading slash to be removed.
> stats/opencensus: remove leading slash for per call metrics

- CONTRIBUTING.md
The bullet point list of guidelines contained a duplicated bullet point regarding speculative changes. This removes the duplicated bullet point.
> CONTRIBUTING.md: remove duplicated bullet point

- xds/internal/balancer/cdsbalancer/cdsbalancer.go
- xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
We used to prefix the log messages with the name of the package before we implemented component and prefix logging. Now that we have those, there is no need to prefix log messages with the name of the package. In fact, doing so makes them harder to read.
Also, we used to log the pointer of the xDS client from which we got updates. But now, we have a singleton and it does not make any sense to log that pointer.
This PR removes the package prefix and makes the logs more readable wherever possible.
> cdsbalancer: improve log messages

- internal/envconfig/xds.go
- xds/internal/xdsclient/xdsresource/name_test.go
Integration tests have been green, so let's enable this (verification of recent test results in https://b.corp.google.com/issues/262593165#comment31).
cc @easwars 
RELEASE NOTES:
- federation: enable support variable by default
> xds: enable XDS federation by default

- status/status.go
- status/status_test.go
Many users would prefer to see the entire error message along with the wrapped status's code & details, so that data is not "lost".  This change implements that preference.
I'm not convinced this is "correct" or "better", but it may be, and I wanted to discuss.
cc @psyhatter 
RELEASE NOTES:
* status: FromError: return entire error message text for wrapped errors
> status: FromError: return entire error message text for wrapped errors

- gcp/observability/opencensus.go
Java and C++ only set this label for metrics, as this is what was causing the time series issue, which is how client libraries actually export data to backends. Go was setting it for logging, traces, and metrics.
> gcp/observability: Set the opencensus_task label only for metrics, not tracing and logging

- interop/observability/go.mod
- interop/observability/go.sum
- stats/opencensus/opencensus.go
This PR plumbs back if the span is sampled or not in the helper observability logging calls in stats/opencensus. This is needed to connect logs to traces in the cloud ops backend.
> stats/opencensus: Switch helper to return Span Context from context

- gcp/observability/go.mod
- gcp/observability/go.sum
- gcp/observability/logging.go
- gcp/observability/logging_test.go
- gcp/observability/observability_test.go
- interop/observability/go.mod
- interop/observability/go.sum
This PR adds the isSampled bool to log entries. This information is pulled from the Span Context both client and server side. This entry is needed to link logs to traces on the LogsExplorer Google Cloud Platform front end.
> gcp/observability: Add isSampled bool to log entries

- examples/features/observability/go.mod
- examples/features/observability/go.sum
Point the observability example to the latest observability module to have the example get some cleanups I recently added.
> examples/features/observability: Point o11y example to latest gcp/observability module

- xds/server_test.go
This pr fix a small problem in `TestServeWithStop`. 
There is a leak at this test when there is any error occurs calling `clientCh.Receive`
https://github.com/grpc/grpc-go/blob/a51779dfbf331faa37864cd80fa2166dbc102dfc/xds/server_test.go#L523-L529
which causes a hanging at `handleServingModeChanges` around server.go:296
https://github.com/grpc/grpc-go/blob/a51779dfbf331faa37864cd80fa2166dbc102dfc/xds/server.go#L293-L324
The fix add a `serve.Stop` before `t.Fatal`  as `Fatal` only terminates current routine but the hanging is at another. 
It can be repro by leak check in grpc with a small modification to trigger the error. 
```
=== RUN   TestServeWithStop
server_test.go:530: error when waiting for new xdsClient to be created: <nil>
leakcheck.go:115: Leaked goroutine: goroutine 18 [select]: …
```
> xds: add stop to avoid hanging in TestServeWithStop

- xds/internal/testutils/testutils.go
- xds/internal/xdsclient/authority.go
- xds/internal/xdsclient/clientimpl_watchers.go
- xds/internal/xdsclient/tests/authority_test.go
- xds/internal/xdsclient/xdsresource/cluster_resource_type.go
- xds/internal/xdsclient/xdsresource/endpoints_resource_type.go
- xds/internal/xdsclient/xdsresource/listener_resource_type.go
- xds/internal/xdsclient/xdsresource/resource_type.go
- xds/internal/xdsclient/xdsresource/route_config_resource_type.go
- xds/internal/xdsclient/xdsresource/type.go
Currently the xdsresource interface defines a function to get an enum associated with the resource. But as the enum is defined in xdsresource package it is not easy to extend it for custom xds resources.
The type enum is mostly utilized for coming up a version agnostic name for a type and so using a string is cleaner and allows custom xds resources to specify their own names. 
cc: @easwars 
> Use string instead of enum for xds resource type

- xds/internal/testutils/resource_watcher.go
- xds/internal/xdsclient/authority_test.go
We have been having frequent flakes for this test [TestWatchResourceTimerCanRestartOnIgnoredADSRecvError](https://github.com/grpc/grpc-go/blob/master/xds/internal/xdsclient/authority_test.go#L184). 
The test is trying to do the following:
1. setup mgmt server + update for resource A on server
2. create watch for resource A and verify that the watcher got an successful update
3. create watch for resource B
4. Stop the mgmt server 
5. Verify that resource B's watcher only gets a connection error (which is the error when trying to reconnect to the mgmt server)
6. verify that the watch timer for resource B is in  WatchStateStarted state.
But step 6 is causes a race. This is because the underlying transport only sends a conn err when send() or recv() fails. This means the watch state for …
> xdsclient/test: deflake TestWatchResourceTimerCanRestartOnIgnoredADSRecvError

- credentials/alts/alts_test.go
- credentials/alts/internal/handshaker/service/service.go
- credentials/alts/internal/handshaker/service/service_test.go
- credentials/alts/internal/testutil/testutil.go
The ALTS tests in this repo do not perform full ALTS handshakes against a fake handshaker service. This leads to changes in this repo breaking e2e/interop tests once the change is imported internally. This PR will (hopefully) reduce the frequency with which that happens.
> alts: Perform full handshake in ALTS tests.

- security/advancedtls/advancedtls.go
- security/advancedtls/advancedtls_integration_test.go
- security/advancedtls/advancedtls_test.go
(Continuation of #5797 cc @ZhenLian)
Adding an "TlsVersionOption" for users to select their desired min/max TLS versions, if advanced TLS is used, per request by https://github.com/grpc/grpc-go/issues/5667
RELEASE NOTES:
* security/advancedtls: add min/max TLS version selection options
> security/advancedtls: add TlsVersionOption to select desired min/max TLS versions

- xds/internal/xdsclient/xdsresource/type.go
- xds/internal/xdsclient/xdsresource/unmarshal_cds.go
- xds/internal/xdsclient/xdsresource/unmarshal_eds.go
- xds/internal/xdsclient/xdsresource/unmarshal_lds.go
- xds/internal/xdsclient/xdsresource/unmarshal_rds.go
The unwrap resource method will be called by internal packages to unwrap resources, so exporting this allows reuse.
@easwars 
> Export the unwrapResource method, to allow callers outside of the package

- credentials/alts/alts_test.go
This fixes the flaky test introduced in #6177 and flagged in #6182. Before this PR, I could reproduce the flake ~1.7% of time on local runs. With this PR, I cannot reproduce the flake locally.
Fixes https://github.com/grpc/grpc-go/issues/6182
> alts: Add retry loop when making RPC in ALTS's TestFullHandshake.

- internal/stubserver/stubserver.go
This pr fixes a small blocking problem related to tests that use `stubserver.Start`. This function doesn't close the server/client when error ocurres, which causes some blocking routines.
It can be repro with leakcheck and  some delay to trigger the timeout in `waitForReady`
These tests below are influenced
```
--- FAIL: TestInvoke (26.84s)
--- FAIL: TestRetryTransparentWhenCommitted (26.88s)
--- FAIL: TestUnaryClientInterceptor_ContextValuePropagation (26.87s)
--- FAIL: TestDetailedConnectionCloseErrorPropagatesToRpcError (26.88s)
--- FAIL: TestNilStatsHandler (26.88s)
--- FAIL: TestClientCancellationPropagatesUnary (26.86s)
--- FAIL: TestInvokeCancelClosedNonFailFast (26.87s)
--- FAIL: TestServerReturningContextError (26.89s)
--- FAIL: TestChainStreamServerInterceptor (26.82s)
--- FAIL: …
```
> internal/stubserver: Close Client Conn in error handling of Start

- credentials/alts/internal/handshaker/handshaker.go
- credentials/alts/internal/handshaker/handshaker_test.go
Reverts grpc/grpc-go#6148.
In #6177, we added new tests that would have caught a bug like the one that forced #6077 to be reverted.
> Revert "Revert "credentials/alts: defer ALTS stream creation until handshake …"

- test/kokoro/psm-security.cfg
> test/kokoro: increase PSM Security test timeout to 4h

- test/kokoro/psm-security.cfg
Backport of #6193 to v1.51.x.
---
> test/kokoro: increase PSM Security test timeout to 4h (v1.51.x backport)

- test/kokoro/psm-security.cfg
Backport of #6193 to v1.49.x.
---
> test/kokoro: increase PSM Security test timeout to 4h (v1.49.x backport)

- test/kokoro/psm-security.cfg
Backport of #6193 to v1.53.x.
---
> test/kokoro: increase PSM Security test timeout to 4h (v1.53.x backport)

- test/kokoro/psm-security.cfg
Backport of #6193 to v1.50.x.
---
> test/kokoro: increase PSM Security test timeout to 4h (v1.50.x backport)

- test/kokoro/psm-security.cfg
Backport of #6193 to v1.54.x.
---
> test/kokoro: increase PSM Security test timeout to 4h (v1.54.x backport)

- test/kokoro/psm-security.cfg
Backport of #6193 to v1.52.x.
---
> test/kokoro: increase PSM Security test timeout to 4h (v1.52.x backport)

- test/kokoro/psm-security.cfg
Backport of #6193 to v1.48.x.
---
> test/kokoro: increase PSM Security test timeout to 4h (v1.48.x backport)

- test/kokoro/psm-security.cfg
Backport of #6193 to v1.46.x.
---
> test/kokoro: increase PSM Security test timeout to 4h (v1.46.x backport)

- test/kokoro/psm-security.cfg
Backport of #6193 to v1.47.x.
---
> test/kokoro: increase PSM Security test timeout to 4h (v1.47.x backport)

- test/kokoro/psm-security.cfg
Backport of #6193 to v1.45.x.
---
> test/kokoro: increase PSM Security test timeout to 4h (v1.45.x backport)

- authz/audit_logger.go
Implements interfaces for pending gRFC A59: https://github.com/grpc/proposal/pull/346/files
> authz: add audit logging APIs

- internal/stubserver/stubserver.go
In the code below, it seems the error of `StartServer` and `StartClient` can not be simply distinguished from caller of `Start`
https://github.com/grpc/grpc-go/blob/fe72db9589696a625af72117a600ba191227b7c5/internal/stubserver/stubserver.go#L85-L90
It is used in project as:
https://github.com/grpc/grpc-go/blob/fe72db9589696a625af72117a600ba191227b7c5/stats/opencensus/e2e_test.go#L294-L297
There is a problem that,  we should call `ss.Stop` when `StartServer` success but `StartClient` failed in the error handling branch, which is not easy to handle in caller. So close it in `Start` when it occurs to avoid leak.
> stubserver: Stop server when StartClient failed

- clientconn.go
- resolver_conn_wrapper.go
Minor cleanup in the ClientConn code:
- add well documented helper methods that enable hiding complexity from `Dial`
- a method to perform channelz registration
- a method to validate transport credentials configuration
- modify existing `parseTargetAndFindResolver` and `determineAuthority` to directly set fields in the `ClientConn` instead of returning them and having `Dial` set appropriate fields
- refactor the `ccResolverWrapper` type and incorporate the principle of least privilege
- the `ccResolverWrapper` is now passed all the arguments that it needs instead of reaching over and getting them from the parent `ClientConn`
- the `ccResolverWrapper` now defines an interface that contains a single method that it calls on the `ClientConn`, thereby it need not hold on to a `ClientConn`
- …
> grpc: ClientConn cleanup in prep for channel idleness

- authz/audit/audit_logger.go
Make the audit logger interfaces their own package inside of `authz`. Since the package is named `audit`, I changed all instance of `AuditLogger` to just `Logger`.
This is necessary to avoid a circular dependency. `rbac_engine.go` needs to import this `audit` package so it can manage the logger interfaces and call them during the authorization decision. On the master branch, adding an import for the `authz` package causes the following import cycle error:
```
package google.golang.org/grpc/internal/xds/rbac
imports google.golang.org/grpc/authz
imports google.golang.org/grpc/internal/xds/rbac: import cycle not allowed
```
While technically a breaking change, this is both experimental and merged a few days ago.
> authz: Move audit package

- xds/internal/balancer/outlierdetection/balancer.go
- xds/internal/balancer/outlierdetection/subconn_wrapper.go
This PR changes string() helper methods to String(), thus implementing a fmt.Stringer() interface and automatically being called by the format package.
> xds/internal/balancer/outlierdetection: Change string to String

- internal/binarylog/binarylog.go
- internal/binarylog/method_logger.go
- internal/envconfig/observability.go
- internal/internal.go
We recently release gcp/observability as 1.0, with a dependency on grpc. However, this release used internal symbols which are not guaranteed to be stable over time. However, in order not to break users of gcp/observability 1.0 in the future (they can use any version of grpc >= the grpc version specified in go.mod) we need to explicitly document this in internal symbols and behaviors being depended upon.
> internal: Document gcp/observability 1.0 dependencies in /internal

- xds/internal/xdsclient/xdslbregistry/tests/converter_test.go
- xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
When running the import, I figured out that `glaze` doesn't like packages named `test`. The suggestion is to call it `tests_test`.
> xds: make glaze happy for test packages
