grpc/grpc-go

orca/call_metric_recorder_test.go, orca/internal/internal.go, orca/orca.go, orca/orca_test.go, orca/service.go
* Move `ToReportProto` to `internal` - it was never meant to be exported / part of the ORCA API, but it is tested from another package (`orca_test`) so it still needs to be exported.  (This is also done in #6223, so they will technically conflict but both are ~the same.)
* Don't error in `ToReportProto` if there is no load report present.  This will prevent error log spam which occurs whenever the ORCA package is imported and a `Done` callback is set by a picker.
* Minor log line fix to remove unused %-format item.
* Downgrade error log to info for ORCA parse error.
=> orca: minor cleanups

authz/rbac_translator.go, authz/rbac_translator_test.go, xds/internal/xdsclient/xdslbregistry/converter.go, xds/internal/xdsclient/xdslbregistry/tests/converter_test.go, xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go, xds/internal/xdsclient/xdsresource/unmarshal_lds.go, xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
We have a bunch of imports that need to be standardized so that we can rename them appropriately at import time.
- github.com/cncf/udpa/go/udpa/type/v1: v1udpaudpatypepb
- github.com/cncf/xds/go/udpa/type/v1: v1xdsudpatypepb
- github.com/cncf/xds/go/xds/type/v3: v3xdsxdstypepb
This change needs to be followed up by a change to our import configuration.
=> multiple: standardize import renaming for typed structs

xds/googledirectpath/googlec2p.go, xds/googledirectpath/googlec2p_test.go
This will need to be cherry-picked to the release branch before performing the release.
CC @veblush, @apolcyn, @mohanli-ml
RELEASE NOTES:
* googledirectpath: enable `ignore_resource_deletion` server feature in bootstrap
=> googledirectpatph: enable ignore_resource_deletion in bootstrap

xds/googledirectpath/googlec2p.go, xds/googledirectpath/googlec2p_test.go
Cherry-pick of #6243 to v1.55.x release branch.
=> googledirectpatph: enable ignore_resource_deletion in bootstrap (#6243)

orca/producer.go, orca/producer_test.go, orca/service_test.go
With #6236, an existing race was discovered (exposed in some new situations):
1. `orca.RegisterOOBListener` is called for a SubChannel.
2. The ORCA producer is created, an its `run` goroutine is started.
3. `run()` could start the OOB stream with the server at any moment now, despite no registered listeners.
4. Back in `orca.RegisterOOBListener`, the listener is registered.
Between 3 and 4, we could start the stream with a request interval of 0.  The server's lower bound would apply to protect it from aggressive clients, but this causes at least some tests to fail.  (Note that a similar race can theoretically happen between unregistering the final listener in a producer & registering a new one, but that would require the two operations to happen at the same time, which is unusual.)
The …
=> orca: fix race at producer startup

internal/grpcsync/callback_serializer.go, internal/grpcsync/callback_serializer_test.go, resolver_conn_wrapper.go, test/service_config_deprecated_test.go
- Use a `CallbackSerializer` to synchronize incoming and outgoing calls in the `ccResolverWrapper`.  This approach provides the following code simplifications:
- Get rid of the two mutexes currently used to synchronize each direction.
- Avoid grabbing the mutex at creation time (used currently to prevent to corner deadlock case).
- Since the `UpdateState` API has to return an `error` value to the caller, we need an extra dance to make it work with the above approach.
- Rename field `done` to `closed`.
- Fix a couple of tests to fail early instead of using the full `-timeout` value supplied to `go test` under failure conditions
This PR is also in preparation for idleness support where we would have a couple of methods on the `ccResolverWrapper` to enter and exit idle …
=> grpc: use CallbackSerializer in resolver_wrapper

credentials/alts/internal/handshaker/handshaker.go, credentials/alts/internal/handshaker/handshaker_test.go
See: https://github.com/grpc/grpc-go/issues/6252
RELEASE NOTES:
* credentials/alts: revert a change that causes a crash on Google Cloud Run
=> alts: Revert #6077

test/balancer_test.go
In this test, it's possible a connection could complete before the context was canceled.  The fix is to never connect the subconn in this scenario by plumbing in a boolean to prevent the connection from occuring.
=> test: deflake TestBalancerProducerHonorsContext

orca/producer.go
Blocking on `p.stopped` while holding `p.mu` can race if the `run` goroutine had just received a report and is trying to acquire `p.mu` in order to call the listeners.
Waiting for the run goroutine to exit before starting a new one is not necessary.  This change will start a new one without waiting, and only wait during producer shutdown (which is also not strictly necessary, but is a good idea to ensure all resources are cleaned up).
=> orca: fix race when calling listeners coincides with updating the run goroutine

balancer_conn_wrappers.go
Following up from https://github.com/grpc/grpc-go/pull/6234, this PR changes the balancer wrapper to use the callback serializer. This resulted in a whole bunch of deleted code and a much simpler balancer wrapper.
=> grpc: use CallbackSerializer in balancer wrapper

xds/internal/xdsclient/xdslbregistry/converter.go, xds/internal/xdsclient/xdslbregistry/tests/converter_test.go
Previously, the converter would simply prepare the JSON if a TypedStruct was encountered. However, we want to look at the gRPC name within the TypedStruct, and if the balancer type specified is not found in the gRPC registry, it continues onto the next one in the list. This makes the interop test case for Custom LBs work correctly against our repo.
=> xds/internal/xdsclient/xdslbregistry: Continue in converter if type not found

balancer/balancer.go, balancer/rls/picker.go, interop/xds/client/client.go, interop/xds/custom_lb.go, interop/xds/custom_lb_test.go, stream.go, test/balancer_test.go
This PR adds the Custom LB needed for the interop test for Custom Load Balancers. The test does all the assertions, but it does need a balancer with name "test.RpcBehaviorLoadBalancer" in each languages registry.
Interop test: https://github.com/grpc/grpc/blob/9f00eda536b89713f182598653058ab840aad79c/tools/run_tests/xds_k8s_test_driver/tests/custom_lb_test.py#L40
C++ PR which added (see file diff for implementation): https://github.com/grpc/grpc/pull/32757
Java file with Custom LB: https://github.com/grpc/grpc-java/blob/master/interop-testing/src/main/java/io/grpc/testing/integration/RpcBehaviorLoadBalancerProvider.java
=> interop/xds: Add Custom LB needed for interop test

balancer/weightedroundrobin/balancer.go, balancer/weightedroundrobin/balancer_test.go, balancer/weightedroundrobin/config.go, balancer/weightedroundrobin/internal/internal.go, internal/serviceconfig/duration.go, internal/serviceconfig/duration_test.go
Another option for `Duration` is to make it a struct with a `time.Duration` field (e.g. named `D`) and the "conversion" would be `x.myDurationField.D` instead of `time.Duration(x.myDurationField)`.  I'm not sure which is better, but this is unfortunately somewhat cumbersome because Go won't coerce your types automatically even though they are the same underlying type; it requires a cast.
=> weightedroundrobin: fix duration format in lb config

test/channelz_test.go, test/clientconn_state_transition_test.go, test/creds_test.go, test/end2end_test.go, test/goaway_test.go, test/healthcheck_test.go, test/pickfirst_test.go, test/roundrobin_test.go
Fixes #4766
- Wait for READY before stopping the server: the picker is updated before the state, so we can race and complete the RPC AND still see a not-yet-READY state from the CC even after the server is stopped.
- Add helpers for waiting for state changes.
- Employ them in all existing uses.
- Remove log noise declarations that don't even exist anymore.
- Use standardized timeouts in more places.
=> test: fix flaky TimeoutOnDeadServer test; some cleanups

interop/interop_test.sh, interop/test_utils.go
Per the [interop test spec](https://github.com/grpc/grpc/blob/e97f632886918a5cc603e8a510dd2d6ee4858e01/doc/interop-test-descriptions.md#backend-metrics-report):
> The server implementation should use a lock or similar mechanism to allow only one client to control the server's out-of-band reports until the end of the RPC.
This is needed to allow concurrent tests to run without ruining each others' values.  At the same time, if multiple tests are running, 5 seconds may not be long enough to wait, so share the 30s timeout throughout the test case instead of requiring ORCA reports to be updated in 5s.
Also, remove the OOB report handling from the unary RPC.  This doesn't work (due to similar issues) and isn't used and will be removed from the protobuf per @yifeizhuang.
=> interop: hold lock on server for OOB metrics updates; share 30s timeout

interop/interop_test.sh
Before this change, if we were shutting down and one of these "killer" threads was still running, but finished on its own _right before_ the `clean` function tried to kill it, `xargs pkill` would exit with an error and make the whole test exit with an error.
This will kill the killer job right after the worker job completes, ensuring this race doesn't happen.
=> interop: fix interop_test.sh shutdown

xds/internal/xdsclient/xdslbregistry/converter/converter.go, xds/internal/xdsclient/xdslbregistry/xdslbregistry.go, xds/internal/xdsclient/xdslbregistry/xdslbregistry_test.go, xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go, xds/internal/xdsclient/xdsresource/unmarshal_cds.go, xds/xds.go
This PR splits the xDS LB policy registry into two separate packages to get rid of a circular dependency.
=> xds/internal/xdsclient: Split registry up and two separate packages

.github/workflows/testing.yml
The old versions are deprecated and show warnings on the actions page.
=> github: upgrade to v3 of checkout & setup-go

xds/internal/balancer/outlierdetection/balancer.go
This PR has the Outlier Detection balancer account for Metadata received in it's child picker. This was causing the custom lb interop test, which deploys a custom lb below this balancer that attaches metadata to lose it's metadata.
=> xds/outlierdetection: forward metadata from child picker

test/kokoro/xds_k8s_lb.sh
Minor: split and sort the list of test suites.
=> test/kokoro: Add custom_lb_test to the xds_k8s_lb job

balancer_conn_wrappers.go, call.go, clientconn.go, clientconn_test.go, dialoptions.go, idle.go, idle_test.go, internal/grpcsync/callback_serializer.go, internal/grpcsync/callback_serializer_test.go, picker_wrapper.go, resolver_conn_wrapper.go, stream.go, test/clientconn_state_transition_test.go, test/idleness_test.go
This PR adds support for channel idleness. Summary of changes:
- Added a new component `idlenessManager` that
- keeps track of RPC activity on the channel, and
- instructs the channel to enter or exit idle mode
- ClientConn
- methods to enter and exit idle mode
- these are invoked by the newly added `idlenessManager`
- these take care of shutting down and recreating the name resolver, load balancer, and blocking picker
- these also set connectivity state appropriately
- call into the `idlenessManager` from `Invoke()` and `NewStream()`
- these are the RPC entry points
- refactor `DialContext` a little bit for better code flow
- `addTraceEvent` helper to emit channelz trace events
- Add a `WithIdleTimeout` dial option to set `idle_timeout`
- Defaults to `30m` if unset (current default used …
=> grpc: support channel idleness

interop/client/client.go
This is a Go analogue of an old PR in C++: https://github.com/grpc/grpc/pull/18156 
This is needed for RLS integration tests, where we sometimes need to set custom headers for routing purposes.
cc @easwars 
=> [interop client] let the interop client send additional arbitrary metadata, controlled by a flag

authz/rbac_translator.go, authz/rbac_translator_test.go
GoProtoAPI tricorder reported this issue in our weekly import CL. Using the value as is in the struct's type field is discouraged because they inherently lend themselves to shallow copies of messages later on. This diff addresses that, and also needs additional logic to check for nil struct Config.
=> authz: use pointer to to structpb.Struct instead of value

xds/internal/xdsclient/xdsresource/cluster_resource_type.go, xds/internal/xdsclient/xdsresource/endpoints_resource_type.go, xds/internal/xdsclient/xdsresource/listener_resource_type.go, xds/internal/xdsclient/xdsresource/route_config_resource_type.go
The interface checks are unnecessary as the structs ListenerResourceData, RouteConfigResourceData, ClusterResourceData and EndpointsResourceData explicitly embed ResourceData.
@dfawley 
=> Remove interface check related to ResourceData 

pickfirst.go, test/pickfirst_test.go
This is WIP. We need another test where the channel moves to READY and then to TF and then we test sticky TF behavior.
RELEASE NOTES:
- client: when using pickfirst, keep channel state in TRANSIENT_FAILURE until it becomes READY (gRFC A62)
=> grpc: support sticky TF in pick_first LB policy

balancer_conn_wrappers.go, internal/grpcrand/grpcrand.go, pickfirst.go, test/pickfirst_test.go, test/resolver_update_test.go
RELEASE NOTES:
- client: add support for pickfirst address shuffling from gRFC A62
=> client: add support for pickfirst address shuffling from gRFC A62

stats/opencensus/e2e_test.go, stats/opencensus/trace.go
Fixes #6143.
The server side span has no happens before relationship with the RPC Finishing, and thus can come at any time and in any index. The Attempt Span and Server Span are guaranteed to be emitted in that order during the RPC. Thus, add a sync point in the test after the RPC completes to wait for the server span, and then sort the seen spans into server, attempt, then call span to then make assertions on.
=> stats/opencensus: Fix flaky test span

internal/xds/matcher/matcher_header.go, internal/xds/matcher/matcher_header_test.go, xds/internal/xdsclient/xdsresource/matcher.go, xds/internal/xdsclient/xdsresource/type_rds.go, xds/internal/xdsclient/xdsresource/unmarshal_rds.go, xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
Fixes #6226. This PR adds support for String Matching in Header Matching for routes. It converts and validates the proto StringMatcher received from the control plane in the xDS Client, then creates a HeaderMatcher for it in ServiceConfig. Tests at xDS Client layer and header matcher layer, anything further will be too specific for an e2e test (as discussed about testing Philosophy with Eric and Doug, leave more specific behavior checks to unit tests and e2e tests as sanity checks to not bloat number and time of e2e tests).
RELEASE NOTES:
* xds/internal/xdsclient: Add support for String Matcher Header Matcher in RDS
=> xds/internal/xdsclient: Add support for String Matcher Header Matcher in RDS

clientconn.go, test/idleness_test.go
`ClientConn.Connect()` needs to fully exit idle mode, not just awaken the balancer wrapper.  Before channel idleness, the LB policy was the only thing that needed to be notified, since the name resolver was never stopped.
=> client: fix Connect to handle channel idleness properly

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh
=> [PSM interop] Don't fail target if sub-target already failed

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh
Backport of #6332 to v1.55.x.
---
=> [PSM interop] Don't fail target if sub-target already failed (v1.55.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh
Backport of #6332 to v1.53.x.
---
=> [PSM interop] Don't fail target if sub-target already failed (v1.53.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh
Backport of #6332 to v1.52.x.
---
=> [PSM interop] Don't fail target if sub-target already failed (v1.52.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh
Backport of #6332 to v1.50.x.
---
=> [PSM interop] Don't fail target if sub-target already failed (v1.50.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh
Backport of #6332 to v1.49.x.
---
=> [PSM interop] Don't fail target if sub-target already failed (v1.49.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh
Backport of #6332 to v1.48.x.
---
=> [PSM interop] Don't fail target if sub-target already failed (v1.48.x backport)

internal/envconfig/xds.go, xds/internal/xdsclient/xdsresource/unmarshal_rds_test.go
RELEASE NOTES:
* xds: enable RLS in xDS by default
=> xds: enable RLS in xDS by default

xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go, xds/internal/balancer/ringhash/picker.go, xds/internal/balancer/ringhash/picker_test.go, xds/internal/balancer/ringhash/ringhash.go
I did not add a new test for this.  The sequence of operations required here is fairly long and specific and requires races that are too difficult to reliably stimulate.  Corresponding change in C++: [grpc/grpc@`98cdac3` (#32326)](https://github.com/grpc/grpc/pull/32326/commits/98cdac31a0196d23a972acd3de027a645daf66ce).  (gRPC-Java always kept a copy of the states in the picker.)
RELEASE NOTES:
* xds/ringhash: cache connectivity state of subchannels inside picker to avoid rare races
=> xds/ringhash: cache connectivity state of subchannels inside picker

balancer/weightedroundrobin/balancer.go, balancer/weightedroundrobin/balancer_test.go
Also includes #6357 as the first commit.
Implements the changes from https://github.com/grpc/proposal/pull/373.
RELEASE NOTES:
* balancer/weightedroundrobin: if the ORCA application_utilization field is set, prefer it over cpu_utilization
=> weightedroundrobin: prefer application_utilization to cpu_utilization

balancer/weightedroundrobin/balancer.go, balancer/weightedroundrobin/balancer_test.go, examples/go.mod, examples/go.sum, gcp/observability/go.sum, go.mod, go.sum, interop/observability/go.mod, interop/observability/go.sum, orca/call_metrics_test.go, orca/orca_test.go, orca/producer_test.go, orca/server_metrics.go, orca/server_metrics_test.go, orca/service_test.go, stats/opencensus/go.sum
RELEASE NOTES:
* orca: add support for application_utilization field and missing range checks on several metrics setters _and_ * balancer/weightedroundrobin: if the ORCA application_utilization field is set, prefer it over cpu_utilization
=> weightedroundrobin: cherry-pick 2 commits from master

cmd/protoc-gen-go-grpc/README.md
I have found these two previous PRs (https://github.com/grpc/grpc-go/pull/4538 https://github.com/grpc/grpc-go/pull/5158) and have also confirmed that the following code actually works.
```
protoc --go-grpc_out=require_unimplemented_servers=false:. \ foo.proto
```
However, since `go-grpc_out` and `go-grpc_opt` are written separately as the protoc command options on the [quick start
guide](https://grpc.io/docs/languages/go/quickstart/#regenerate-grpc-code), isn't this easier to understand?
=> protoc-gen-go-grpc: Update README.md file

benchmark/benchmain/main.go
The import is broken because the wrong generated proto type is declared.
=> benchmark: fix package used to reference service to use grpc suffix instead of pb

clientconn.go, test/authority_test.go
This reverts commit 68576b3c42bbecacfeba3bee89f509f1bb7b0072.
=> Revert "client: encode the authority by default (#6318)"

internal/balancer/nop/nop.go, test/xds/xds_client_outlier_detection_test.go, xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go, xds/internal/balancer/cdsbalancer/cdsbalancer_test.go, xds/internal/balancer/clusterresolver/clusterresolver.go, xds/internal/balancer/clusterresolver/clusterresolver_test.go, xds/internal/balancer/clusterresolver/config.go, xds/internal/balancer/clusterresolver/config_test.go, xds/internal/balancer/clusterresolver/configbuilder.go, xds/internal/balancer/clusterresolver/configbuilder_test.go, xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go, xds/internal/balancer/clusterresolver/priority_test.go, xds/internal/balancer/outlierdetection/balancer.go, xds/internal/balancer/outlierdetection/balancer_test.go, xds/internal/balancer/outlierdetection/config.go, xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go, xds/internal/xdsclient/xdsresource/type_cds.go, xds/internal/xdsclient/xdsresource/unmarshal_cds.go, xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
This PR fixes Outlier Detection configuration across the xDS System and the Outlier Detection ParseConfig.
This PR touches multiple components:
* xDS Client: Switch to emit Outlier Detection configuration into JSON, and also handle xDS Defaults (proto -> layered gRPC JSON structure). The handling of xDS Defaults used to be handled in cds_balancer, and was incorrect, as it did not contain a distinction between unset and set and 0 for fields, causing the first bug listed below.
* cds_balancer: Take Outlier Detection JSON and Endpoint + Locality Picking JSON, prepare a Cluster Resolver configuration in JSON. Call ParseConfig() on cluster_resolver child to receive cluster resolver configuration to send downward.
* cluster_resolver: Accept Outlier Detection JSON and Endpoint + Locality Picking …
=> xds/outlierdetection: fix config handling

reflection/adapt.go, reflection/serverreflection.go, reflection/serverreflection_test.go
Resolves #5684.
This adds `RegisterV1` and `RegisterV1Alpha` to provide control over the versions registered. The existing `Register` function registers both versions.
This also adds `NewServerV1` to return a server that implements the new version. `NewServer` continues to return the v1alpha version of the interface.
All of the _core_ logic and types have been updated to refer to the newer definitions in v1. Adapters have been added, to convert between v1 and v1alpha, to provide the v1alpha server. The adapters are also used in tests, so that the end-to-end tests now go through both v1 and v1alpha stubs, to verify both versions work correctly.
RELEASE NOTES:
* reflection: support the v1 reflection service and update Register to register both v1alpha and v1.
=> reflection: expose both v1 and v1alpha reflection services

stats/opencensus/e2e_test.go
Fixes #6231.
This adds a sync point between Unary and Streaming RPCs recording completed RPC's Server Side and the test. The test simply waits for the RPC to finish client side, but stats.End is recorded in a defer for the Unary and Streaming RPC case after status is written to the wire. Thus, previously there was no sync point between the test and this metric being recorded. Sync at the view global level, as that is synced with exporter by Unregistering views, and will stop recording metrics after, thus has to wait for the two row emissions for Unary and Streaming RPCs at the view global level, not at the exporter level.
Verified passes over 10k runs on Forge. Previously was failing 18/10k times on Forge.
=> stats/opencensus: Fix flaky metrics test

test/kokoro/xds_url_map.sh
Backport of #6390 to v1.56.x.
---
We don't want file multiple bugs if any of the sub-tests of the `url_map` test fails.
The same change in core: https://github.com/grpc/grpc/pull/33520.
=> [PSM interop] Don't fail target if sub-target already failed (v1.56.x backport)

internal/testutils/xds/e2e/clientresources.go, test/xds/xds_client_custom_lb_test.go, xds/internal/balancer/clusterimpl/tests/balancer_test.go, xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
Added better support for locality and backend options in the `e2e` package, and cleaned up custom endpoint resource creation logic in `xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go`.
=> xds: clusterresolver e2e test cleanup

test/kokoro/xds_url_map.sh
Backport of #6390 to v1.47.x.
---
We don't want file multiple bugs if any of the sub-tests of the `url_map` test fails.
The same change in core: https://github.com/grpc/grpc/pull/33520.
=> [PSM interop] Don't fail target if sub-target already failed (v1.47.x backport)

test/kokoro/xds_url_map.sh
Backport of #6390 to v1.51.x.
---
We don't want file multiple bugs if any of the sub-tests of the `url_map` test fails.
The same change in core: https://github.com/grpc/grpc/pull/33520.
=> [PSM interop] Don't fail target if sub-target already failed (v1.51.x backport)

test/kokoro/xds_url_map.sh
Backport of #6390 to v1.54.x.
---
We don't want file multiple bugs if any of the sub-tests of the `url_map` test fails.
The same change in core: https://github.com/grpc/grpc/pull/33520.
=> [PSM interop] Don't fail target if sub-target already failed (v1.54.x backport)

reflection/adapt.go, reflection/serverreflection.go, reflection/serverreflection_test.go
The current import renames `v1grpc`, `v1pb`, `v1alphagrpc` and `v1alphapb` are not distinct enough and can cause trouble in the copybara import script. This change disambiguates them.
=> reflection: rename proto imports for disambiguation in import script

internal/transport/http2_server.go, internal/transport/keepalive_test.go, internal/transport/transport_test.go
With TLS, set TCP user timeout on the underlying raw connection, and validate in tests. 
Fixes https://github.com/grpc/grpc-go/issues/5646
RELEASE NOTES:
* server: fix bug preventing TCP user timeout from being set on the connection when TLS is used
=> server: with TLS, set TCP user timeout on the underlying raw connection (#5646)

xds/internal/balancer/clusterresolver/resource_resolver_eds.go, xds/internal/xdsclient/client.go, xds/internal/xdsclient/clientimpl_watchers.go, xds/internal/xdsclient/tests/dump_test.go, xds/internal/xdsclient/tests/eds_watchers_test.go, xds/internal/xdsclient/tests/federation_watchers_test.go, xds/internal/xdsclient/tests/resource_update_test.go, xds/internal/xdsclient/xdsresource/type_eds.go
- Switch the `clusterresolver` LB policy to use the resource agnostic `WatchResource` API instead of `WatchEndpoints`
- Since `clusterresolver` tests were recently fixed to not rely on internal details, the tests needed no change for this PR
- Remove all references to `WatchEndpoints` in the `xdsClient` codebase
- Remove the method from the `XDSClient` interface
- Update EDS tests to call the `WatchResource` API instead
=> xds: switch EDS watch to new generic xdsClient API

xds/server.go, xds/server_test.go
Fixes #5838.
This PR fails Serve() if called after Stop() or GracefulStop(). This is important because Serve() eventually increments the global singleton xDS Client Ref, and thus if called without a corresponding cleanup, Stop() or GracefulStop(), the singleton xDS Client will eventually leak.
=> xds: Fail xDS Server Serve() if called after Stop() or GracefulStop()

internal/xds/rbac/matchers.go, internal/xds/rbac/rbac_engine_test.go
Fixes #6369. This PR adds support for string matcher in RBAC header matching. This was added to the RDS flow in PR https://github.com/grpc/grpc-go/pull/6313, and a user requested symmetry in issue #6226. StringMatcher as HeaderMatch is already unit tested, so just added a test that a HeaderMatcher that specifies StringMatcher is good RBAC configuration.
RELEASE NOTES:
* Add support for string matcher in RBAC header matching
=> internal/xds/rbac: Add support for string matcher in RBAC header matching

test/xds/xds_server_rbac_test.go
This PR adds testing for audit logging logic to the existing RBAC tests. It very closely matches the tests for the authz path - https://github.com/grpc/grpc-go/pull/6304
I've currently only added a very basic test of the audit logger - the purpose here is to make sure that we can construct an audit logger through the xds path and it works.
I'm open to adding test cases for the various combinations of audit logging and authorization policies, but I think that's not really what we are testing here, and it's a pretty explosive combination and pollutes the test (if it's not necessary). All these cases should be covered in other tests like the unit tests and the authz path tests. @dfawley @easwars what do you think? I see compelling reasons for either choice.
=> xds: E2E Test for Audit Logging

xds/internal/balancer/clusterimpl/clusterimpl.go
Fixes #6170. Cluster Impl was implemented before there was a graceful switch balancer object, and thus did not have it's child as a Graceful Switch. The child of cluster impl can be dynamic over the lifetime of the xDS tree based off locality + endpoint picking configuration for a priority, so this is a fairly common use case that will be better served with graceful switch functionality present.
=> xds/internal/balancer/clusterimpl: Switch cluster impl child to graceful switch

internal/grpcsync/pubsub_test.go
=> internal/grpcsync: refactor test

status/status.go, status/status_test.go
When wrapping an error that has a gRPC status, we reuse the underlying status message field and put the error message in there. If the returned gRPC status is nil, then there is a nil dereference of the status Message field, causing panic.
This change fixes this behavior by returning an Unknown status code and the error message whenever the wrapped error
has status OK.
RELEASE NOTES:
- status: `status.FromError` now returns an error with `codes.Unknown` when the error implements the `GRPCStatus()` method, and calling `GRPCStatus()` returns nil.
- status: fix nil dereference when `status.FromError` wraps an error that implements `GRPCStatus()`, and `GRPCStatus()` returns nil.
=> Fix panic when servers return a wrapped error with status OK

clientconn.go, clientconn_parsed_target_test.go, internal/resolver/dns/dns_resolver.go, internal/resolver/dns/dns_resolver_test.go, resolver/resolver.go, xds/googledirectpath/googlec2p.go, xds/internal/balancer/clusterresolver/resource_resolver_dns.go
Fixes #5795
RELEASE NOTES:
- resolver: remove deprecated Target.Scheme and Target.Authority.  Use URL.Scheme and URL.Host instead, respectively
=> resolver: delete Target.Scheme and Target.Authority

status/status.go, status/status_test.go
Backport of nil panic fix.
RELEASE NOTES:
* status: status.FromError now returns an error with codes.Unknown when the error implements the GRPCStatus() method, and calling GRPCStatus() returns nil.
=> status: fix panic when servers return a wrapped error with status OK (#6374)

xds/internal/balancer/clusterresolver/clusterresolver.go, xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go, xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go, xds/internal/balancer/clusterresolver/resource_resolver.go, xds/internal/balancer/clusterresolver/resource_resolver_eds.go
EDS nacks and resource-not-found errors are to be treated by the cluster_resolver LB policy as though it received an EDS update with no endpoints. This would mean that for aggregate clusters, it would result in fallback (if appropriate), and non-aggregate clusters, it would result in the channel moving to `TRANSIENT_FAILURE` (because the child policy, priority LB, will put the channel in `TRANSIENT_FAILURE` when there are no priorities in its configuration).
The only difference between how a NACK error and a resource-not-found error is handled by the cluster_resolver LB policy is that in the NACK case, the LB policy ignores the error if there was a previous result. The resource-not-found error is received by the cluster_resolver LB policy *only* when it does not have a previously received …
=> clusterresolver: handle EDS nacks and resource-not-found errors correctly

xds/internal/xdsclient/xdsresource/unmarshal_cds.go, xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
This PR implements the changes described by https://github.com/grpc/proposal/pull/377
RELEASE NOTES:
* xds: require EDS service name to be set in a CDS cluster with an 'xdstp' resource name (gRFC A47)
=> xds: require EDS service name in new-style CDS clusters (gRFC A47)

attributes/attributes.go, clientconn.go, internal/stubserver/stubserver.go, resolver/resolver.go, test/pickfirst_test.go
- Make of copy of received addresses in the clientconn code during subchannel creation and address update operation
- clear out the balancer attributes field in this address list, thereby ensuring that changes in balancer attributes don't lead to connection churn
- Minor improvements to rendering of attributes in logs
- Make it possible to pass a `net.Listener` to the `stubserver`
- this allows tests to use a wrapped listener that notifies the test upon connection establishment
Fixes internal issue: b/290272899
RELEASE NOTES:
- grpc: eliminate connection churn during an address update that differs only in balancer attributes
=> grpc: do not use balancer attributes during address comparison

xds/internal/balancer/clusterresolver/resource_resolver.go, xds/internal/balancer/clusterresolver/resource_resolver_dns.go
Ran into the absence of these logs when debugging a directpath issue. We currently have such logs for the EDS discovery mechanism which were recently added.
=> clusterresolver: add logs for dns discovery mechanism error cases

.github/workflows/release.yml
Resolve  #6416 
Update `.github/workflows/release.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo ::set-output name=name::${PACKAGE_NAME}
```
**TO-BE**
```yaml
echo "name=${PACKAGE_NAME}" >> $GITHUB_OUTPUT
```
=> github: replace deprecated command with environment file

clientconn.go, picker_wrapper.go, picker_wrapper_test.go, stats/opencensus/trace.go, stats/stats.go, test/end2end_test.go, test/retry_test.go
This PR adds stats events representing blocking resolver resolve and blocking picker pick. The OpenCensus stats handler uses these callouts to add trace annotations, which provide a timestamp for debugging purposes.
Fixes https://github.com/grpc/grpc-go/issues/6418.
RELEASE NOTES:
* stats: Add an RPC event for blocking caused by the LB policy's picker
=> stats: Add RPC event for blocking for a picker update

clientconn.go
While debugging an issue, I saw the following log:
```
2023/07/19 01:01:23 INFO: [core] ClientConn asked to exit idle mode when not in idle mode
```
And in this application, there are multiple gRPC channels and without the channel ID, this log is not very useful. I also added the current state to the log line.
=> clientconn: add channel ID to some idleness logs

examples/features/xds/server/main.go, internal/testutils/xds/e2e/setup_management_server.go, interop/xds/server/server.go, test/xds/xds_client_ignore_resource_deletion_test.go, test/xds/xds_server_integration_test.go, test/xds/xds_server_serving_mode_test.go, xds/server.go, xds/server_test.go
Currently we create the xDS client when `Serve()` is called for the first time. This leads to unnecessary code complexity since we have to synchronize access to the xDS client and its close function inside the server. The following code paths touch the xDS client:
- In `Serve` to see if one has been created, and create a new one if none exists
- In `Stop` and `GracefulStop` to closed the client
- In the `ListenerWrapper` to register LDS and RDS watches using it
This PR changes the code such that the xDS client is created when the xDS enabled gRPC server is created. Certain bootstrap configuration validation is also moved to here. Therefore we can fail the server creation when appropriate.
Note that with this change, since the mutex has been eliminated, `Serve` and `Stop` can race in the …
=> xds/server: create the xDS client when the xDS enabled gRPC server is created

xds/internal/balancer/clusterresolver/configbuilder.go, xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go, xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go, xds/internal/balancer/clusterresolver/resource_resolver.go, xds/internal/balancer/clusterresolver/resource_resolver_dns.go
Fixes #6462. This PR fixes cluster_resolver error handing. The desired behavior as per gRFC A37 is to create a priority and send down an empty address list if an EDS Discovery Mechanism or DNS Discovery Mechanism errors before a first good update, triggering Transient Failure for that priority and causing fallback if another lower level priority. In master, we simply don't create the priority child in the EDS case and send down a resolver error in the DNS case.
=> clusterresolver: comply with A37 for handling errors from discovery mechanisms

balancer/weightedroundrobin/balancer.go, test/xds/xds_client_custom_lb_test.go
=> resolver/weighted_round_robin: remove experimental suffix from name

pickfirst.go, test/pickfirst_test.go
Fixes https://github.com/grpc/grpc-go/issues/6469.
RELEASE NOTES:
- pickfirst: guard config parsing on GRPC_EXPERIMENTAL_PICKFIRST_LB_CONFIG
=> pickfirst: guard config parsing on GRPC_EXPERIMENTAL_PICKFIRST_LB_CONFIG

pickfirst.go
Also includes some minor improvements to existing logs and error strings.
Fixes https://github.com/grpc/grpc-go/issues/6467
=> pickfirst: add prefix logging

test/pickfirst_test.go
Fixes https://github.com/grpc/grpc-go/issues/6468
=> pickfirst: add tests for resolver error scenarios

balancer/balancer.go, internal/internal.go, resolver/resolver.go, resolver_conn_wrapper.go, resolver_test.go, stream.go, test/balancer_test.go, xds/googledirectpath/googlec2p_test.go, xds/internal/balancer/clusterresolver/clusterresolver.go, xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go, xds/internal/balancer/clusterresolver/resource_resolver_dns.go
Also:
* Removed `resolver.UnregisterForTesting`, which we didn't need.
* Created `internal.GRPCResolverSchemeExtraMetadata` to control the behavior of setting additional metadata in the context for the user agent string, which is needed by xDS routing code.
Even though this is backward compatible and removes nothing, we should probably wait until several LB policies have been converted over to read `Endpoints` instead of `Addresses` before merging this PR.  I'll be working on that in the meantime.
RELEASE NOTES:
* resolver: State: add Endpoints and deprecate Addresses
=> resolver: State: add Endpoints and deprecate Addresses

balancer/balancer.go, balancer/weightedtarget/weightedtarget_test.go, balancer_conn_wrappers.go, internal/balancer/gracefulswitch/gracefulswitch.go, internal/balancer/gracefulswitch/gracefulswitch_test.go, internal/balancergroup/balancergroup.go, internal/balancergroup/balancergroup_test.go, internal/testutils/balancer.go, xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/clusterimpl/balancer_test.go, xds/internal/balancer/clusterimpl/clusterimpl.go, xds/internal/balancer/clustermanager/clustermanager_test.go, xds/internal/balancer/clusterresolver/clusterresolver.go, xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go, xds/internal/balancer/outlierdetection/balancer.go, xds/internal/balancer/outlierdetection/balancer_test.go, xds/internal/balancer/outlierdetection/e2e_test/outlierdetection_test.go, xds/internal/balancer/priority/balancer_test.go, xds/internal/balancer/ringhash/ringhash_test.go
This change is backward-compatible.  However I've labeled it as "API Change" since we are deprecating `Balancer.UpdateSubConnState`.
This also does not fully migrate all our code to stop using `UpdateSubConnState`.  In particular, many tests still invoke this method, and will need to be migrated over slowly.  However, it is the minimal amount of changes required to keep everything working while providing support for this optional feature throughout.  It also shows an example of how the other tests can be updated for this transition in `gracefulswitch_test.go` and `weightedtarget_test.go`, which now calls the `SubConn`s directly to update their state.  Future PRs will migrate _all_ our balancers to use this functionality.
#6472
RELEASE NOTES:
* balancer: add `StateListener` to …
=> balancer: add StateListener to NewSubConnOptions for SubConn state updates

internal/testutils/balancer.go, xds/internal/balancer/ringhash/picker_test.go, xds/internal/testutils/balancer_test.go
When adding methods to `TestSubConn` (matching new APIs planned in #6472), I found that this global was not necessary and was making it harder to do so.  So this PR removes that global and uses more local things in the two places it is used instead.
=> testutils: remove TestSubConns for future extensibility

test/kokoro/xds_k8s_lb.sh
This PR adds the bootstrap generator test into Go kokoro script.
=> test/kokoro: Add bootstrap generator test into Go Kokoro script

test/xds/xds_client_integration_test.go
As part of some other testing, I noticed that one of the custom LB policy tests which verifies RR behavior was quite flaky on google3. The reason being the `5s` default test timeout that we use. The test verifies that the RPC distribution reaches expected value within this timeout. Increasing the timeout to `10s` fixes the issue.
=> test/xds: increase default test timeout

clientconn.go
This is something I noticed when adding the `SubConn.Shutdown` method in #6493, but never observed.  If we fail to check `ac.ctx` while holding `ac.mu`, then the following race is technically possible:
1. In `resetTransport`, `tryAllAddrs` is called and returns an error.  `acCtx` (AKA `ac.ctx`) `.Err() == nil` as the `addrConn` is still in use.
2. From the LB policy, `RemoveSubConn` (or `SubConn.Shutdown`) is called. This sets the state to `Shutdown` and cancels `ac.ctx`.
3. Back in `resetTransport`, we grab `ac.mu` and update the state to `TransientFailure`.
The net result is the LB policy's state listener (or `UpdateSubConnState`) will receive `Shutdown` followed by `TransientFailure`.  All LB policies should be ignoring updates after `Shutdown` anyway, but this is still an incorrect …
=> client: fix race between connection error and subconn shutdown

xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
In one of the `clusterresolver` tests, we remove the EDS resource from the management server and expect RPCs to fail *and then* verify that the connectivity state of the channel is `TRANSIENT_FAILURE`.
When the LB policy reports a state update with a new picker and new connectivity state, the picker is first applied. This is by design. See: https://github.com/grpc/grpc-go/blob/master/balancer_conn_wrappers.go#L351-L357
This means that in the above test, when the `clusterresolver` reports a new picker and a state of `TRANSIENT_FAILURE`, the picker is first applied, thereby causing RPCs to fail. The channel state is yet to be updated though, and in this tiny time window, the test reads the current connectivity state of the channel and expects it to be `TRANSIENT_FAILURE`. Changing the test …
=> clusterresolver: fix a flaky test

balancer_conn_wrappers.go, test/idleness_test.go
This PR fixes the following issue:
- Channel is `READY` and things are good
- After a period of inactivity, channel moves to `IDLE`
- As part of this the LB policy is shutdown. But currently a goroutine is spawned to shutdown the LB policy.
- At the same time, an RPC is initiated
- This brings the channel out of `IDLE` and a new LB policy is created
- New policy moves channel to `READY`
- Still, the old policy hasn't been completely shutdown because the goroutine did not get a change to run
- The connections belonging to the old policy and shutdown, and the old policy receives state updates on these subConns
- The old policy updates channel with `TRANSIENT_FAILURE` 
This whole scenario can be prevented if the old policy was shutdown inline when the channel entered `IDLE`.
This PR also …
=> grpc: perform a blocking close of the balancer in ccb

balancer/weightedtarget/weightedtarget_test.go, internal/balancer/gracefulswitch/gracefulswitch_test.go, internal/testutils/balancer.go, xds/internal/balancer/clusterimpl/balancer_test.go, xds/internal/balancer/clustermanager/clustermanager_test.go, xds/internal/balancer/priority/balancer_test.go, xds/internal/balancer/ringhash/picker_test.go, xds/internal/balancer/ringhash/ringhash_test.go
Simple cleanup using `sed` to rewrite `UpdateSubConnState` into `TestSubConn.UpdateState` calls, which will ensure the `StateListener` is called if one is registered.
=> balancer: fix tests not properly updating subconn states

balancer/balancer.go, balancer/base/balancer_test.go, balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_remote_balancer.go, balancer/grpclb/grpclb_util.go, balancer/grpclb/grpclb_util_test.go, balancer_conn_wrappers.go, internal/balancer/gracefulswitch/gracefulswitch.go, internal/testutils/balancer.go, test/balancer_test.go, test/roundrobin_test.go, xds/internal/balancer/clusterimpl/clusterimpl.go, xds/internal/balancer/outlierdetection/balancer.go, xds/internal/balancer/ringhash/ringhash_test.go
Part 3 of #6472
RELEASE NOTES:
* balancer: add SubConn.Shutdown and deprecate Balancer.RemoveSubConn
=> balancer: add SubConn.Shutdown; deprecate Balancer.RemoveSubConn

clientconn_test.go, pickfirst.go, test/clientconn_state_transition_test.go, xds/internal/balancer/clustermanager/clustermanager_test.go
Part of #6472 
This is a minimal change to migrate `pick_first` to the `StateNotifier`.  Since PF is slated to become a lot more complex, I didn't want to do any significant refactoring here.
=> pickfirst: receive state updates via callback instead of UpdateSubConnState

xds/internal/xdsclient/authority.go
This fixes a test flake where the timer fires after the authority is closed and the test is done, and leads to a log message being thrown after the test completes. And this races with the test logger being set on the top-level test object.
=> xdsclient: make watch timer a no-op if authority is closed

balancer/balancer.go, balancer/base/balancer.go, balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_remote_balancer.go, balancer/grpclb/grpclb_util.go, balancer/grpclb/grpclb_util_test.go, balancer/weightedroundrobin/balancer.go, balancer/weightedtarget/weightedtarget_test.go, balancer_conn_wrappers.go, internal/balancer/gracefulswitch/gracefulswitch.go, internal/balancer/gracefulswitch/gracefulswitch_test.go, internal/balancergroup/balancergroup.go, internal/balancergroup/balancergroup_test.go, internal/testutils/balancer.go, pickfirst.go, test/balancer_switching_test.go, test/balancer_test.go, xds/internal/balancer/clusterimpl/clusterimpl.go, xds/internal/balancer/clustermanager/clustermanager_test.go, xds/internal/balancer/outlierdetection/balancer.go, xds/internal/balancer/outlierdetection/balancer_test.go, xds/internal/balancer/priority/balancer_test.go, xds/internal/balancer/ringhash/ringhash.go
This is a cleanup to finish the work started in #6493.
=> all: replace RemoveSubConn with Shutdown as much as possible

balancer/base/balancer.go, balancer/base/balancer_test.go
This change updates `base`, used by the round robin policy, to the new `StateListener` and `SubConn.Shutdown` APIs.  It requires #6493 for the `Shutdown` API, #6500 to fix outlierdetection to properly call child listeners in all cases, and #6501 for some test fixes (all included as separate commits in this PR).
=> base: update base balancer for new APIs

xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
Because its child, `clusterresolver`, uses `StateListener` always (https://github.com/grpc/grpc-go/blob/e9a4e942b10030c6dc487b2ebf396bf6dfa9d465/xds/internal/balancer/clusterresolver/clusterresolver.go#L424-L429), this change is safe to make in isolation now.
=> xds/cdsbalancer: stop handling subconn state updates

test/authority_test.go, test/balancer_test.go, test/channelz_test.go, test/compressor_test.go, test/config_selector_test.go, test/context_canceled_test.go, test/end2end_test.go, test/goaway_test.go, test/gracefulstop_test.go, test/healthcheck_test.go, test/invoke_test.go, test/local_creds_test.go, test/metadata_test.go, test/recv_buffer_pool_test.go, test/retry_test.go, test/roundrobin_test.go, test/service_config_deprecated_test.go, test/stream_cleanup_test.go, test/subconn_test.go
A straw finally broke the camel's back.  Many of our tests don't set timeouts and hang for minutes.  This change fixes them, and also standardizes on the use of `defaultTest[Short]Timeout` everywhere.  My goal is to eventually put something like this into `vet.sh` to make it never happen again:
```sh
$ find . -name '*_test.go' | xargs grep -n context\.Background | grep -v context.WithTimeout
$ find . -name '*_test.go' | xargs grep -n context\.WithTimeout\(context.Background | grep -v defaultTest.*Timeout
```
There are currently 130 left in our entire tree.  Some of these will need to be exempted somehow, or reworked a little to first create a `ctx` with a timeout and then shorten it from there.
We probably also should look out for `select`s without a context, bare reads from channels, and …
=> test: clean up deadlines set in tests

clientconn.go, clientconn_test.go, internal/internal.go, test/connectivity_state_updates_test.go
This PR adds a logic to report connectivity state changes on the ClientConn for Subscribers.
Please refer to https://github.com/grpc/grpc-go/pull/6036#issuecomment-1488895547 in https://github.com/grpc/grpc-go/pull/6036 . Original issue is https://github.com/grpc/grpc-go/issues/5818.
=> grpc: report connectivity state changes on the ClientConn for Subscribers

benchmark/client/main.go, benchmark/server/main.go
In #5762, the default values used by our benchmarks was changed to be the same as the default gRPC values.  However, I was unaware that we were publishing these benchmarks at http://grpc.io.  That led to [this regression](https://grafana-dot-grpc-testing.appspot.com/?viewPanel=21&orgId=1&from=1667333818308&to=1668946615952) :+1: 
This change restores the values that were in use before the change, which should lower CPU usage by using bigger buffers.  It does this in the client and server used by the benchmark framework, but not for our local benchmarks that we occasionally run to evaluate the performance impact of changes.
=> benchmark: restore old buffer size values for published benchmarks

xds/internal/balancer/outlierdetection/balancer.go, xds/internal/balancer/outlierdetection/balancer_test.go
All children use `StateListener`, so this fallback path is no longer needed.  Update tests accordingly, too.
=> xds/outlierdetection: Stop handling UpdateSubConnState forwarding

xds/internal/balancer/priority/balancer.go, xds/internal/balancer/priority/balancer_test.go
balancergroup installs its own StateListener, so this is unnecessary.
=> xds/priority: stop forwarding UpdateSubConnState calls

xds/internal/balancer/clustermanager/clustermanager.go, xds/internal/balancer/clustermanager/clustermanager_test.go
balancergroup installs its own StateListener, so this is unnecessary.
=> xds/clustermanager: stop forwarding UpdateSubConnState calls

clientconn_test.go, test/balancer_switching_test.go, test/balancer_test.go, test/resolver_update_test.go, test/subconn_test.go
A future change will delete `stub.BalancerFuncs.UpdateSubConnState`... This prepares for that and uses `StateListener` instead.
=> tests: stop using UpdateSubConnState

xds/internal/balancer/clusterresolver/clusterresolver.go, xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go
All children use `StateListener` so this is unnecessary now.  Also, delete associated test.
=> xds/clusterresolver: stop forwarding UpdateSubConnState calls

xds/internal/balancer/ringhash/ringhash.go, xds/internal/balancer/ringhash/ringhash_test.go
=> xds/ringhash: use StateListener instead of UpdateSubConnState

balancer/weightedroundrobin/balancer.go
=> balancer/weightedroundrobin: migrate to StateListener

balancer/rls/balancer_test.go
https://github.com/grpc/grpc-go/pull/6514 changed some tests to use the `stub` balancer package instead of defining custom test balancers, but it introduced a bug which made one of the tests flaky.
The bug was that a `testCCWrapper` was being passed as the `balancer.ClientConn` for the child policies of RLS. This meant that any state change reported by the child policy ended up changing the state of the main channel. This is not how it is supposed to work. The way it works is that the RLS LB policy intercepts state updates from the child policies, aggregates them and pushes a final state to the parent ClientConn.
The fix for this PR ensures that the `balancer.ClientConn` passed by RLS LB policy (when it creates a child policy) is the one which gets passed to the child policy in the test …
=> rls: fix flaky test introduced by #6514 

internal/balancergroup/balancergroup.go
All of balancergroup's children use `StateListener`, so we can delete the fallback code that handles ones that don't.
=> internal/balancergroup: remove usage of UpdateSubConnState

balancer/rls/balancer.go, xds/internal/balancer/wrrlocality/balancer.go
Everything else uses `StateListener`s now.
=> balancer/rls, xds/wrrlocality: stop forwarding UpdateSubConnState calls

balancer/weightedtarget/weightedtarget.go, balancer/weightedtarget/weightedtarget_test.go, internal/balancer/gracefulswitch/gracefulswitch_test.go, internal/balancer/stub/stub.go
- gracefulswitch_test: make `UpdateSubConnState` error if called, and do that behavior directly in the `StateListener`s
- stub: delete `UpdateSubConnState` field, which requires all tests that use it to use `StateListener`s now (all migrated before this PR; requires #6525, included here as a separate commit).
=> gracefulswitch, stub: remove last UpdateSubConnState references

balancer/rls/balancer.go, balancer/rls/helpers_test.go, balancer/weightedtarget/weightedtarget.go, balancer/weightedtarget/weightedtarget_test.go, internal/balancergroup/balancergroup.go, internal/balancergroup/balancergroup_test.go, xds/internal/balancer/clustermanager/clustermanager.go, xds/internal/balancer/clustermanager/clustermanager_test.go, xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go, xds/internal/balancer/priority/balancer.go, xds/internal/balancer/priority/balancer_test.go
Internal tracking issue: b/291228739
This PR changes the behavior of the `balancergroup` package to only cache deleted sub-balancers when a cache timeout is specified explicitly by the caller. This caching feature was supposed to be only used by the `priority` balancer, but inadvertently has been used by other LB policies that manage child policies. 
Fixes https://github.com/grpc/grpc-go/issues/6515
RELEASE NOTES:
- balancergroup: do not cache closed sub-balancers by default; affects `rls`, `weightedtarget` and `clustermanager` LB policies
=> balancergroup: do not cache closed sub-balancers by default

xds/internal/httpfilter/fault/fault_test.go, xds/internal/resolver/serviceconfig.go, xds/internal/resolver/xds_resolver_test.go
=> xds: improve error message when matched route on client is not of type RouteActionRoute

.github/workflows/testing.yml
=> testing: update Go versions tested to 1.19-1.21

examples/features/orca/client/main.go, interop/orcalb.go
=> orca: update example and interop to use StateListener

Documentation/proxy.md, README.md, internal/channelz/util_test.go, internal/transport/handler_server_test.go, interop/observability/Dockerfile, interop/xds/client/Dockerfile, interop/xds/server/Dockerfile, test/channelz_linux_test.go, test/kokoro/xds.sh, vet.sh
=> *: remove references to old versions of go

balancer/leastrequest/balancer_test.go, balancer/leastrequest/leastrequest.go
This PR adds the least request load balancer, speced in https://github.com/grpc/proposal/blob/master/A48-xds-least-request-lb-policy.md.
RELEASE NOTES:
* balancer/leastrequest: Add least request balancer
=> balancer/leastrequest: Add least request balancer

clientconn.go
Mutex must be unlocked on return from function.
=> clientconn: release lock when returning from enterIdleMode()

benchmark/worker/benchmark_client.go, benchmark/worker/benchmark_server.go
#6516 updated the wrong binary, and had no effect on our results.  This package appears to be what is actually run in our published benchmarks ([ref](https://github.com/grpc/grpc/blob/master/tools/run_tests/performance/run_worker_go.sh)).
=> benchmark: update proper benchmark binary to use larger buffers

resolver/resolver.go
This PR aims to resolve https://github.com/grpc/grpc-go/issues/6496, in which an outdated Godoc was noticed. In the past the `resolver.Target` struct contained three different fields, but nowadays it's only `URL`, but the examples in the Godoc still referenced the old fields.
As the `Target` doesn't seem to be usually created directly by a user of grpc-go, but instead through `Dial` or `DialContext`, it seems reasonable to just remove the examples instead of replacing them with an example where a target string is manually parsed with `url.Parse`.
=> resolver: remove outdated Target examples

internal/envconfig/envconfig.go, xds/internal/xdsclient/xdslbregistry/xdslbregistry_test.go
De-experiment pick first since we have both affinity and randomness E2E test running successfully.
@apolcyn @easwars 
=> pick_first: de-experiment pick first

status/status.go
=> status: optimize GRPCStatus() calls

internal/grpctest/grpctest.go, internal/grpctest/grpctest_test.go
I was originally going to try to see if I could use generics to set a `context.Context` field in the `Tester` embedded in the struct so that every test case could automatically get our default deadline (and we could even forbid `context.Background()` from being called from tests).  But, in practice we declare test methods without receivers, e.g.:
```go
func (s) TestFoo(t *testing.T)
```
So the only way to do that would require a change to:
```go
func (s s) TestFoo(t *testing.T) {
// access s.Ctx here
}
```
At which point, we might just be better off doing:
```go
func (s) TestFoo(ctx context.Context, t *testing.T)
```
But regardless of any of that, I found a simple cleanup to use an interface instead of reflection to find the `Setup` and `Teardown` methods, which at one point (before we …
=> grpctest: use an interface instead of reflection

idle_test.go
Before this change, test iterations would last 500ms (* 10 iterations = 5s total).  With this change, test iterations happen in 50ms (*20 iterations = 1s).
Not super significant in and of itself, but it was a very simple change that cuts several seconds off per run (and we run each test 6 times in GA).
=> idle: speed up test by 5x even while running 2x more iterations

internal/internal.go, server.go, test/channelz_test.go
=> test: improve and speed up channelz keepalive test

test/channelz_test.go, test/end2end_test.go
- `TestFlowControlLogicalRace`: reduce some of the stressiness of this test to make it run in ~1s vs. ~4s before.  Also make some minor simplifications to remove 10 lines of code and have the same logic.
- `TestCZClientSocketMetricsKeepAlive`: make the keepalive pings happen at a much higher rate to enable two pings to happen in 100ms vs. 2s.  Update test condition to pass even if `verifyResultWithDelay` needs to sleep a few times (this shouldn't happen, but could in theory).
=> test: speed up two tests

internal/testutils/xds/e2e/clientresources.go, resolver/manual/manual.go, xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/cdsbalancer/cdsbalancer_test.go, xds/internal/xdsclient/tests/resource_update_test.go, xds/internal/xdsclient/xdsresource/tests/unmarshal_cds_test.go
This PR is the first in a set of test cleanups for the tests in the cds balancer. This is a pre-requisite for switching the cds balancer to use the generic xdsClient watch API.
- Cleanup of tests in `cdsbalancer_test.go` to use a real management server and rely on behavior instead of internal implementation details
- Add support for LRS config in the `e2e` package
- Switch some usages of handcrafting the `Cluster` resource to use the utilities provided by the `e2e` package
-  Add an `UpdateStateCallback` to the `manual` resolver
=> cdsbalancer: test cleanup part 1/N

internal/credentials/xds/handshake_info.go, internal/stubserver/stubserver.go, xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go, xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
This PR cleanup us tests in the cds balancer relating to security configuration. This is a pre-requisite for switching the cds balancer to use the generic xdsClient watch API.
=> cdsbalancer: test cleanup part 2/N

binarylog/binarylog_end2end_test.go, internal/transport/http2_client.go, internal/transport/transport.go, rpc_util.go, stream.go, test/end2end_test.go, test/retry_test.go
This fixes a regression introduced in #5763.  Fixes #6524
This change causes us to reliably report the stream status from `ClientStream.Header()`, including `io.EOF` in case the stream ended successfully with a trailers-only response.  To do this required moving the binary logging of trailers into `clientStream.finish()`.
By doing this, retry is also fixed in cases where an error is encountered on the stream before calling `Header()`.  Previously, if `Header()` was called first, we would report `ErrNoHeaders` from the transport which would be converted into a non-error by `clientStream.Header()`, which would then commit the RPC and prevent retries.  A test case was added to cover this scenario.
RELEASE NOTES:
* client: fix a bug that prevented `ClientStream.Header` from returning an error …
=> client: fix ClientStream.Header() behavior

test/service_config_deprecated_test.go
I made this test significantly slower by changing 1ns into 100ms when I made #6506.  And 100ms*2 doesn't seem to bad, but this is multiplied by the number of "test environments" we have (6), so it does add up quickly.
=> test: speed up TestServiceConfigTimeoutTD from 1.8s to 0.03s

balancer/rls/balancer_test.go, call.go, channelz/service/service_sktopt_test.go, channelz/service/service_test.go, clientconn.go, internal/channelz/funcs.go, internal/channelz/types.go, internal/idle/idle.go, internal/idle/idle_e2e_test.go, internal/idle/idle_test.go, internal/testutils/state.go, internal/testutils/wrappers.go, stream.go, test/balancer_switching_test.go, test/channelz_linux_test.go, test/channelz_test.go, test/clientconn_state_transition_test.go, test/clientconn_test.go, test/creds_test.go, test/end2end_test.go, test/goaway_test.go, test/healthcheck_test.go, test/pickfirst_test.go, test/roundrobin_test.go, test/subconn_test.go, xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go, xds/internal/balancer/cdsbalancer/cdsbalancer_test.go, xds/internal/balancer/clusterresolver/e2e_test/balancer_test.go, xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
Also: pull out some shared testing code to make it easier to use in other packages than `test/`.
Before:
```
$ time go test -count=1 ./...
<snip>
real	0m47.221s
user	1m31.381s
sys	0m30.061s
```
After:
```
$ time go test -count=1 ./...
<snip>
real	0m38.994s
user	1m30.279s
sys	0m29.964s
```
For reference:
```
$ go test -count=1 ./internal/idle
ok  	google.golang.org/grpc/internal/idle	12.739s
```
=> idle: move idleness manager to separate package and ~13s of tests into it

internal/testutils/xds/e2e/clientresources.go, xds/internal/balancer/cdsbalancer/cdsbalancer_test.go, xds/internal/balancer/cdsbalancer/cluster_handler_test.go, xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go, xds/internal/balancer/clusterresolver/resource_resolver.go
This PR cleans up aggregate cluster tests in the cds LB policy. It makes the tests verify behavior rather than internal state. Cleaning up these tests helped identify the issue described in https://github.com/grpc/grpc-go/issues/6562.
=> cdsbalancer: test cleanup part 3/N

stream.go, stream_test.go
Fixes #6524 
This reverts the behavior change part of #6557 but allows retry to keep working, because the transport still returns the error through `withRetry()` via the attempt stream's `Header()` method.
This will need to be backported to 1.58.x.
=> stream: swallow Header errors as we used to; RecvMsg can still return it

dialoptions.go
The plan was always to enable this by default. But we hit a bug right after making the changes, and had to disable it. We have since fixed the underlying bug.
Fixes https://github.com/grpc/grpc-go/issues/6559
RELEASE NOTES:
- grpc: channel idleness enabled by default with an `idle_timeout` of `30m`
=> grpc: re-enable channel idleness by default

stream_test.go
This is required for this week's import, and the import script relies on this being renamed.
=> grpc_test: rename import for grpc_testing

vet.sh
=> vet: ensure all usages of grpc_testing package are renamed when importing

internal/balancergroup/balancergroup.go, internal/cache/timeoutCache.go, internal/cache/timeoutCache_test.go
=> balancergroup: improve observability around balancer cache behavior

balancer/leastrequest/leastrequest.go
This PR fixes a data race in least request picker which will make race detector happy by using atomic type.
Note: Even after this PR merged, there is still some raciness in this implementation, but as section Outstanding request counter raciness in [A48](https://github.com/grpc/proposal/blob/master/A48-xds-least-request-lb-policy.md#outstanding-request-counter-raciness) points out, it's on purpose for performance reason.
=> leastrequest: fix data race in leastrequest picker

internal/transport/handler_server.go, internal/transport/handler_server_test.go, internal/transport/http2_server.go, internal/transport/transport.go, internal/transport/transport_test.go, server.go, stats/stats_test.go
This PR changes some plumbing with respect to the server streams context once HandleStream() called. These changes are logical no-ops. First, it gets rid of the old trace info plumbing into context, since it's just used to read out trace info at a later point, and now I construct trace info inline. Second, it reads stream.Context() at the beginning of HandleStream(). This is to help the future changes.
The next steps are to:
1. Move all stats handler callouts (now in http/2 transport and server stream) to server.go
2. Pass a pointer to grpc.Server inside the context, and add a method to server for if a method is registered or not. Stats handler will call this to determine if method is registered or not.
=> grpc: Change server stream context handling

balancer/leastrequest/balancer_test.go, balancer/leastrequest/leastrequest.go
This PR caches the atomic load of the picked SubConn in the picker algorithm in least request picker for efficiency reasons, rather than doing it per iteration. It also adds an e2e test which performs concurrent RPCs to check for a race condition.
Continuation of #6587. Needs to be backported to 1.58 alongside that bug fix PR.
=> balancer/leastrequest: Cache atomic load and also add concurrent rpc test

balancer/leastrequest/leastrequest.go
Cherry pick #6587 to v1.58.x branch
RELEASE NOTES: NA
=> leastrequest: fix data race in leastrequest picker 

balancer/leastrequest/balancer_test.go, balancer/leastrequest/leastrequest.go
Back port https://github.com/grpc/grpc-go/pull/6602 to v1.58.x branch
=> balancer/leastrequest: Cache atomic load and also add concurrent rpc test 

xds/internal/resolver/serviceconfig.go, xds/internal/resolver/serviceconfig_test.go
A42 update PR: https://github.com/grpc/proposal/pull/392
Also a minor performance optimization to not read metadata from context more than once if not required, as this operation allocates a map (https://github.com/grpc/grpc-go/blob/c2b0797a5353b29ca02869629c83151c980a6e31/metadata/metadata.go#L271).
RELEASE NOTES:
* xds: fix hash policy header to skip "-bin" headers and read content-type header as expected
=> xds: fix hash policy header to skip bin headers and use extra metadata

call.go, internal/idle/idle_e2e_test.go, stream.go
RELEASE NOTES:
- idle: fix a bug that was decrementing active RPC count too early for streaming RPCs; leading to channel moving to IDLE even though it had open streams
=> idle: decrement active call count for streaming RPCs only when the call completes

clientconn.go, internal/idle/idle_e2e_test.go
Prior to channel idleness, sub-channels would be closed either because:
- the LB policy shuts it down (or the LB policy is being switched)
- in this case, the underlying transport is gracefully closed
- the channel is being shutdown
- in this case, `cc.ctx` is canceled
- this context is passed to the transport, and leads to the transport shutting down
In the case of the channel moving to IDLE though, we were calling `ac.tearDown`, but this was not actually closing the transport because the passed in error was not `errConnDrain`.
With this PR, we will always close the underlying transport from `ac.tearDown`, either gracefully or forcefully. 
RELEASE NOTES:
- grpc: fix a bug where transports were not being closed upon channel entering IDLE
=> grpc: ensure transports are closed when the channel enters IDLE

internal/idle/idle_e2e_test.go
Existing tests were using the absence of a certain log message in channelz to verify that the channel did not enter IDLE (apart from checking the channel connectivity state). But these checks aren't great because if we decided to change the string we log, then the test case will no longer be valid but will continue to pass. 
This PR uses the closing of the LB policy as a proxy for channel entering IDLE mode instead.
Fixes https://github.com/grpc/grpc-go/issues/6612
=> idle: use LB policy close event as a proxy for channel idleness

clientconn_test.go, resolver/manual/manual.go
=> resolver/manual: support restarts, required for channel idleness

balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_picker.go, balancer/grpclb/grpclb_remote_balancer.go, interop/observability/go.mod
- use `base.NewErrPicker` instead of implementing an error picker
- use `proto.Equal` directly without using `cmp.Equal`
- use a prefix logger and cleanup log statements
=> grpclb: some minor cleanups

xds/internal/testutils/fakeclient/client.go, xds/internal/xdsclient/client.go, xds/internal/xdsclient/clientimpl_watchers.go, xds/internal/xdsclient/tests/authority_test.go, xds/internal/xdsclient/tests/cds_watchers_test.go, xds/internal/xdsclient/tests/dump_test.go, xds/internal/xdsclient/tests/eds_watchers_test.go, xds/internal/xdsclient/tests/federation_watchers_test.go, xds/internal/xdsclient/tests/resource_update_test.go
https://github.com/grpc/grpc-go/pull/6600 switched the CDS LB policy to use the new API to watch a cluster. This PR:
- Removes the old API from the `xdsclient.XDSClient` interface 
- Removes the old API from the `fakeclient` package
- Removes the old API from the `xdsclient.clientImpl` type
- Switches over remaining tests to the new API
=> xdsclient: completely remove the old WatchCluster API

balancer/weightedroundrobin/balancer.go
The code that regenerate the picker, called on every conn update, does creates ticker to update weights but does not properly close it. This causes resource leaks.
Fix this by properly stopping the ticker.
RELEASE NOTES:
- balancer/weightedroundrobin: fix a memory leak caused by not stopping a `time.Ticker`
=> balancer/weightedroundrobin: fix ticker leak on update

balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_util.go
An instance of `lbManualResolver` is created when the `grpclb` policy is built. After this, every time the LB policy receives new balancer addresses as part of its configuration, it pushes those addresses to the `grpclb` channel via this manual resolver.
If the `grpclb` channel goes `IDLE`, which it technically should *never* because it always has a stream open to the remote balancer, grpc shuts down the manual name resolver and when it exits `IDLE`, grpc recreates the name resolver. But at this point, there is no configuration update on the parent `grpclb` LB policy. So, the `grpclb` channel is stuck forever waiting for addresses.
This PR caches the most recent list of addresses received in the manual resolver, and replays the same when it is recreated (when exiting IDLE).
RELEASE NOTES: …
=> grpclb: teach the manual resolver to handle restarts

attributes/attributes.go, attributes/attributes_test.go, resolver_test.go
This fixes a panic caused by typed nil, introduced in https://github.com/grpc/grpc-go/pull/6224. 
`String()` should catch panics when formatting by using the `fmt` package. 
=> attributes: print typed nil values instead of panic

xds/googledirectpath/googlec2p_test.go
Fixes #6572
It looks like this test was originally written assuming that federation was default off.
When federation was defaulted on, the expectations changed. Update to fix expectations and make the test behave the ~same whether it's ran on GCE or not.
cc @easwars 
=> xds/googledirectpath: fix google-c2p resolver test case involving bootstrap env config

xds/googledirectpath/googlec2p.go
=> googlec2p: remove support for the experimental scheme

balancer/balancer.go, xds/internal/balancer/clusterresolver/config_test.go
After the next release (v1.59), we can switch over to having a case sensitive balancer registry.
This PR also fixes a test which would be broken once we switch to a case sensitive balancer registry.
https://github.com/grpc/grpc-go/issues/5288
RELEASE NOTES:
- balancer: grpc will switch to case sensitive balancer names soon
=> balancer: add a warning for balancer names that contain upper case letters

attributes/attributes.go, attributes/attributes_test.go
The `%#v` formatting verb looks deep into structs which are passed by pointer as well. This means that if a struct contains a `sync.Mutex` and is a key or value in the `attributes`, then printing the `attributes` with the `%#v` verb will result in the fields of this struct being accessed without holding the mutex.
While this does not introduce correctness issues in the code (we might end up with inconsistent data in the log messages where the `attributes` are printed), this causes our tests to be super flaky when run with the go race detector. And it wasn't straight-forward to figure out why the race was happening when looking at the stack traces reported by the race detector.
This PR eliminates this race by using the `%p` verb that we were using earlier. While this results in some …
=> attributes: avoid the use of %#v formatting verb

internal/backoff/backoff.go, orca/producer.go, xds/internal/xdsclient/transport/loadreport.go, xds/internal/xdsclient/transport/transport.go
Fixes https://github.com/grpc/grpc-go/issues/5813
=> internal/backoff: add a helper to run a function with backoff

encoding/encoding.go
Fixes https://github.com/grpc/grpc-go/issues/6618
=> encoding: fix mention of DecompressedSize in docstring

interop/xds/custom_lb.go, interop/xds/custom_lb_test.go, interop/xds/server/server.go
Implements the spec found at: https://github.com/grpc/grpc/blob/master/doc/xds-test-descriptions.md#server
Fixes #6288 
=> interop: implement rpc-behavior for UnaryCall()

clientconn.go, internal/idle/idle_e2e_test.go, internal/internal.go
PR adds a test where the ClientConn methods to enter and exit idle and invoked concurrently. Helps ensure that there is no data race in the idleness code in the ClientConn.
Also includes a minor cleanup in `cc.enterIdleMode` to `defer` the unlock.
Fixes https://github.com/grpc/grpc-go/issues/6560
=> internal/idle: add a test that invokes ClientConn methods concurrently

internal/status/status.go, internal/stubserver/stubserver.go, internal/transport/handler_server.go, internal/transport/http2_client.go, internal/transport/http2_server.go, internal/transport/http_util.go, status/status_ext_test.go, status/status_test.go, test/balancer_test.go
Fixes #5485
cc @ejona86 @markdroth FYI / to review the behavior to confirm it conforms to the grpc spec or the intentions of the spec, since there is unfortunately no written spec for `grpc-status-details-bin`.
If the user sets a status code outside the bounds defined in the `codes` package 0-16 (inclusive), set the status code to `codes.Unknown`.  This impacts statuses created locally as well as statuses received in RPC response trailers.  See https://github.com/grpc/grpc-java/issues/10568 for evidence this may be happening in the wild.
_Previous behavior_: allowed any value to be used and set on the wire (server) or read from the wire (client).
When receiving a `grpc-status-details-bin` trailer:
- If there is 1 value and it deserializes into a `google.rpc.Status`, ensure the code field …
=> status: fix/improve status handling

internal/status/status.go, internal/stubserver/stubserver.go, internal/transport/handler_server.go, internal/transport/http2_client.go, internal/transport/http2_server.go, internal/transport/http_util.go, status/status_ext_test.go, status/status_test.go, test/balancer_test.go
This reverts commit 0772ed7355afec5b78ba2433174930d7a11a0bd1.
We found some usages that were relying on the illegal behavior we had before.  We'll work to get those resolved then roll this forward again.
=> Revert "status: fix/improve status handling (#6662)"

authz/audit/audit_logger.go
No functional change at all. Simply cleaning up the TODOs by replacing the gRFC link.
=> authz: Replace the gRFC pull request with the permanent link.

.github/workflows/testing.yml
Updating github actions 
+ actions/setup-go to v4.1.0 [Release Notes](https://github.com/marketplace/actions/setup-go-environment#v4)
+ actions/checkout to v4.1.0 [Release Notes](https://github.com/marketplace/actions/checkout#checkout-v4)
=> github: update actions/setup-go and actions/checkout

xds/internal/resolver/watch_service_test.go, xds/internal/xdsclient/xdsresource/matcher_test.go
=> xds: move virtual host matcher test to the xdsresource package

balancer_conn_wrappers_test.go
=> client: add a test for NewSubConn / StateListener / cc.Close racing

internal/status/status.go, internal/stubserver/stubserver.go, internal/transport/handler_server.go, internal/transport/http2_client.go, internal/transport/http2_server.go, internal/transport/http_util.go, status/status_ext_test.go, test/balancer_test.go
This reverts commit 9e1fc3e9c088387890f5a303b805d320f11cc6dd.
It removes the part of the commit that forces status codes out of range to be converted to UNKNOWN, however.
(relnotes from previous PR)
=> Reapply "status: fix/improve status handling (#6662)" (#6673)

internal/transport/http2_server.go, tap/tap.go, test/end2end_test.go
This PR extends `tap.Info` struct with metadata, and modifies `http2_server.go` to pass available metadata to `ServerInHandle` function.
This gives tap handle more details that it can use to reject request early.
RELEASE NOTES:
* tap (experimental): Add Header metadata to tap handler
=> transport: Pass Header metadata to tap handle.

xds/internal/server/listener_wrapper_test.go, xds/internal/server/rds_handler_test.go
This is in prep for xDS generic API changes for the server side.
=> xds/internal/server: stop using a fake xDS client in rds handler tests

benchmark/primitives/primitives_test.go, internal/transport/http2_server.go, internal/transport/transport_test.go, server.go, server_ext_test.go
This addresses CVE-2023-44487 by not allowing more server handlers to be running than the HTTP/2 MAX_CONCURRENT_STREAMS setting.
This will need to be backported to the last 3 releases.
RELEASE NOTES:
* server: prohibit more than MaxConcurrentStreams handlers from running at once (CVE-2023-44487) -- in addition to this change, applications should ensure they do not leave running tasks behind related to the RPC before returning from method handlers, or should enforce appropriate limits on any such work.
=> server: prohibit more than MaxConcurrentStreams handlers from running at once

benchmark/primitives/primitives_test.go, internal/transport/http2_server.go, internal/transport/transport_test.go, server.go, server_ext_test.go
RELEASE NOTES:
* server: prohibit more than MaxConcurrentStreams handlers from running at once
=> server: prohibit more than MaxConcurrentStreams handlers from running at once (#6703)

codes/codes.go
Related to https://github.com/grpc/grpc/pull/34588; specifically document that users should use ONLY the values defined by us.
RELEASE NOTES:
* codes: clarify that only codes defined by this package are valid and that users should not cast other values to `codes.Code`
=> codes: update docstring to indicate expected usage

credentials/tls.go
Replaces the map of cipher suite IDs with lookups in the globally known cipher suites. Fixes #5075 
=> Use Go cipher suites to find TLS suite string name

resolver/resolver.go, xds/internal/resolver/cluster_specifier_plugin_test.go, xds/internal/resolver/xds_resolver.go, xds/internal/resolver/xds_resolver_test.go
- Moves the tests in `xds/internal/resolver/cluster_specifier_plugin_test.go` to `resolver_test` package, thereby making them not rely on any internal details
- Adds some helper functions (more to come in other PRs) that are used to make tests shorter and will be used in other tests as well
- Export scheme from the `resolver` package
- Add a `String()` method on the `resolver.Target` type for better logging output
=> xds/resolver: move cluster specifier plugin tests to test only package

xds/internal/resolver/cluster_specifier_plugin_test.go, xds/internal/resolver/helpers_test.go, xds/internal/resolver/watch_service_test.go, xds/internal/resolver/xds_resolver_test.go
The `testutils.ResolverClientConn` found in `internal/testutils/resolver.go` is part of an in-progress PR: https://github.com/grpc/grpc-go/pull/6668. So, you can skip reviewing it here unless we get done here first before the other PR.
- Moves the tests in `xds/internal/resolver/watch_service_test.go` to `resolver_test` package, thereby making them not rely on any internal details
- Also removes the following two tests:
- `TestServiceWatchLDSUpdateMaxStreamDuration`: This will already tested in one of the config selector tests, and the same test will be enhanced to also verify the service config pushed to the channel
- `TestServiceNotCancelRDSOnSameLDSUpdate`
- This is not worth testing because the go-control-plane sends both the LDS and RDS resource even when we …
=> xds/resolver: move service watching tests to resolver_test package

internal/testutils/xds/e2e/clientresources.go, test/xds/xds_client_ignore_resource_deletion_test.go, test/xds/xds_security_config_nack_test.go, test/xds/xds_server_integration_test.go, test/xds/xds_server_serving_mode_test.go, xds/internal/server/listener_wrapper_test.go, xds/internal/server/rds_handler_test.go, xds/server_test.go
This is in prep for xDS generic API changes for the server side.
=> xds/internal/server: stop using a fake xDS client in listenerWrapper tests

server.go
RELEASE NOTES:
- grpc: add a warning message for unsupported codecs; will stop defaulting to `proto` codec in a future release
=> grpc: add a warning for unsupported codec

benchmark/benchmain/main.go, dialoptions.go, experimental/experimental.go, experimental/shared_buffer_pool_test.go, internal/experimental.go, server.go
=> experimental: add package and move recv buffer pool APIs into it

xds/internal/server/listener_wrapper.go, xds/internal/server/rds_handler.go, xds/internal/server/rds_handler_test.go
The changes to switch to the generic xDS API on the server ended up being simple:
- `OnUpdate` callback calls existing methods that handle updates
- the error handling logic from the existing handler methods were removed
- `OnError` and `OnResourceDoesNotExist` handle the errors inline
=> xds/internal/server: switch to generic xDS API for LDS/RDS

xds/internal/resolver/helpers_test.go, xds/internal/resolver/internal/internal.go, xds/internal/resolver/serviceconfig.go, xds/internal/resolver/serviceconfig_test.go, xds/internal/resolver/xds_resolver.go, xds/internal/resolver/xds_resolver_test.go
- Move the remaining xds resolver tests to `resolver_test` package
- Remove previously used helpers defined here since they are no longer required
- Modify existing tests to use new helpers defined in previous test cleanup PRs
-  Split `TestXDSResolverHTTPFilters` into two
- One tests config selector failure cases
- The other tests HTTP filters
- This is simplified to use a slice of `paths` instead of using a channel
- Add a helper to verify error received from resolver
- Create an internal package within `xds/internal/resolver` and move things to be overridden in tests to that package
=> xds/internal/resolver: final bit of test cleanup

resolver/map.go, resolver/map_test.go
This PR adds an endpoint map type for use by Petiole policies for pick first children and also balancers like Outlier Detection which store state unique to individual endpoints. The endpoints are unique based off the unordered set of address string counts within an endpoint.
RELEASE NOTES:
* resolver: Add an endpoint map type
=> resolver: Add an endpoint map type

server.go
This is to fix a bug in v1.57.1 where servers will run very sluggishly, and also take ages to shut down.
The acquire and release functions should have opposite impacts on the count.
Credit to @colega who spotted the diff.
This was introduced in #6706, a backport of #6703, where the line is correct.
https://github.com/grpc/grpc-go/pull/6703/files#diff-366e46a40f6f60b4f7614eb0976bb51820364bf5ca6ccc4787eb49d7bdbef3e6R2098
Also correct in the 1.56 backport: https://github.com/grpc/grpc-go/pull/6708/files#diff-366e46a40f6f60b4f7614eb0976bb51820364bf5ca6ccc4787eb49d7bdbef3e6R2073
=> server: fix semaphore release

balancer/rls/picker.go, balancer/rls/picker_test.go
Fixes #6719. Previously, the RLS Balancer would not treat an RLS response with no targets as an error. This PR makes it treat an RLS response with no targets as an error.
The relevant language from the RLS LB Design document: "An RLS request is considered to have failed if it returns a non-OK status or the RLS response's targets list is non-empty."
RELEASE NOTES:
* balancer/rls: Fix RLS failure mode by treating response with no targets as an error
=> balancer/rls: Fix RLS failure mode by treating response with no targets as an error

internal/internal.go, internal/stubstatshandler/stubstatshandler.go, internal/testutils/stubstatshandler.go, server.go, stats/stats_test.go
This PR adds a pointer to the grpc.Server into the context passed into the stats handler. It also adds an internal only helper on the server that returns whether a given method is registered or not. This will be used in OpenTelemetry instrumentation for security purposes with respect to the cardinality of the method attribute. The next step after these two PRs is to move the rest of the stats handler callouts to the gRPC layer, get registered methods plumbed client side, canoncalize Target() without breaking it and then the OpenTelemetry instrumentation itself :).
=> grpc: Add a pointer of server to ctx passed into stats handler

metadata/metadata.go, metadata/metadata_test.go
This is approximately 30% faster in a microbenchmark I added. The previous version using strings.ToLower() looks at every key byte. This version will typically evaluate "not equal" on the first byte.
The test and benchmark had no coverage for this loop, so I added it. I also revised the comments in FromIncomingContext and ValueFromIncomingContext. The problem is not that the MD is created using the helper functions. The MD must be attached to the context using NewIncomingContext, which could lower case the keys. The problem is that NewIncomingContext does not make a copy of its argument, so callers can mutate it after.
This change adds a test for FromIncomingContext that tests this case, and modifies the existing TestValueFromIncomingContext to test it.
Benchstat output from 10 runs of …
=> metadata: Use strings.EqualFold for ValueFromIncomingContext

internal/envconfig/envconfig.go, internal/grpcutil/compressor.go
This is needed to unblock an internal usage that will be removed ASAP.
=> envconfig: re-add AdvertiseCompressors temporarily

xds/internal/resolver/xds_resolver_test.go
This is just for peace of mind since a similar situation came up in interop tests, and I wanted to make sure it was handled correctly.
=> xds/resolver: extend test to re-add listener

stress/client/main.go
Needed for an internal, DirectPath related, stress test.
=> stress: client logs total num of calls made

resolver/manual/manual.go, resolver/manual/manual_test.go
Add panic message when manual resolver crashes if `grpc.Dial()` isn't called before setting ClientConn
=> resolver: manual resolver crashes if grpc.Dial isn't called before some methods

.github/codecov.yml
A few improvements to codecov settings
+ Change checks to be non-blocking: https://docs.codecov.com/docs/common-recipe-list#set-non-blocking-status-checks
+ Ignore paths explicitly [avoiding globs as much as possible]
+ add `diff` and `files` to PR comment: https://docs.codecov.com/docs/pull-request-comments#layout
=> github: modify codecov.yml

benchmark/benchmain/main.go, dialoptions.go, examples/helloworld/greeter_server/main.go, internal/transport/http2_client.go, internal/transport/proxy.go, server.go
Pertaining to #6250 
Summary of Changes made (as suggested by @easwars):
- `transport/http2_client.go`: Disable Go's override of OS default TCP keepalive interval (currently 15s) on the client-side
- Add documentation to retain OS defaults on server-side and example to implement it within `helloworld/greeter_server`
I am still unable to replicate the bug mentioned originally in the issue and test whether my changes on client-side will fix it. 
grpc version: v1.58.2
go version: go1.20.4 darwin/arm64
OS: macOS Ventura 13.4
at packet 3773, I applied the rule to `pftcl`:
```
block drop in on lo0 proto tcp from any to any port = 8080
```
but my server does not reset the connection after a single lost keepalive packet (I am using the default keepalive settings on both client and server side). …
=> grpc: disable and document overrides of OS default TCP keepalive by Go

interop/stress/client/main.go
This was needed in the past to work around a bug that has since been fixed.
=> interop/stress: Remove wait-for-ready

security/advancedtls/crl_provider.go, security/advancedtls/crl_provider_test.go
Part of CRL Provider effort. The functionality in this PR includes enhancement for FileWatcher provider initialization logic. It also adds minor godoc improvements.
=> security/advancedtls: FileWatcher CRL provider initialization enhancement

.github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/lock.yml, .github/workflows/release.yml, .github/workflows/stale.yml
Fixes #6774.
As mentioned in the issue, this PR adds top-level read-only permissions to `coverage.yml`, ensuring it can't be used for supply-chain attacks on the repo.
I've also made a few similar changes to the other workflows, mostly just setting `write` permissions at job-level instead of top-level. This serves to future-proof the workflows in case new jobs (that don't need those permissions) are added to the workflows. However, this change has no immediate impact to those workflows' security: the tokens effectively used in those jobs are unchanged.
=> Set top-level read-only workflow permissions

internal/transport/http2_client.go
Fixes #6577.
Followup to #6716 that exposes `LocalAddr` also to grpc clients (#6716 only exposed it to servers). Release note in #6716 encapsulates this logic as well.
=> Add LocalAddr to http2Client.getPeer()

resolver/resolver.go, resolver_conn_wrapper.go, xds/internal/balancer/clusterresolver/resource_resolver_dns.go
cc #6472
All dependencies checked do not use this method any longer.  It has been deprecated for sufficient time.
RELEASE NOTES:
* resolver: remove deprecated and experimental `ClientConn.NewServiceConfig`
=> resolver: remove ClientConn.NewServiceConfig

reflection/serverreflection.go, reflection/serverreflection_test.go
Resolves #6770.
On a related note, I'm also trying to land a patch to the protobuf runtime:
https://go-review.googlesource.com/c/protobuf/+/540455
I think both that and this fix are useful. This one is likely more useful since a "not found" error for a particular file will be a better error message to users, given that the issue is in fact that an imported file is missing from the global registry.
RELEASE NOTES:
* reflection: do not send invalid descriptors to clients for files that cannot be fully resolved
=> reflection: don't serialize placeholders

credentials/tls.go, credentials/tls_ext_test.go
Fixes #6758
cc @ejona86 FYI
RELEASE NOTES:
* credentials: if not set, set TLS `MinVersion` to 1.2 and `CipherSuites` according to supported suites not forbidden by RFC7540.  This is a behavior change to bring us into better alignment with RFC 7540.
=> credentials: if not set, restrict to TLS v1.2+ and CipherSuites per RFC7540

internal/buffer/unbounded.go, internal/buffer/unbounded_test.go, internal/grpcsync/callback_serializer.go
* buffer: follow channel semantics for buffer closure
* notably: closing a channel still results in existing entries being delivered)
* grpcsync: simplifications in CallbackSerializer
* esp. with being able to expect channel semantics, the code gets a good bit simpler
=> buffer & grpcsync: various cleanups and improvements

balancer_conn_wrappers.go, clientconn.go
- Unconditionally initialize blockingpicker (renamed to pickerWrapper) and balancerWrapper to simplify cleanup.
- Rearrange things in DialContext a bit further to facilitate the above
- Access mutex-protected fields in Close after Unlock directly, as it is safe.
=> client: simplify initialization and cleanup a bit

credentials/xds/xds.go, credentials/xds/xds_client_test.go, credentials/xds/xds_server_test.go, internal/credentials/xds/handshake_info.go, internal/credentials/xds/handshake_info_test.go, internal/internal.go, xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go, xds/internal/server/conn_wrapper.go
This PR does a few things:
* Makes handshake info fields set at init time and read only after that, eliminating need for mutex
* Scale up newHandshakeInfo() constructor to all fields
* Atomically write and read handshake info for cds
This eliminates acting on partial updates due to synchronization only between setters on individual fields, so reads and writes (within the context of one Handshake and one new update) could arbitrarily intersplice and cause correctness issues due to partial reads of handshake info configuration. Security configuration still needs to be per cluster and not set by the top level cluster, but this fixes the race.
RELEASE NOTES:
* xDS: Atomically read and write xDS security configuration client side
=> xDS: Atomically read and write xDS security configuration client side

balancer_wrapper.go, clientconn.go, dialoptions.go
* Add newClient method that starts a client in idle mode.
* Use newClient in DialContext.
* Use default dial options as appropriate.
* Stop cloning credentials unnecessarily.  We never mutate them ourselves and a single copy is insufficient if some other LB policy ever mutates them.
=> client: further streamlining of Dial

resolver_wrapper.go
=> resolver_wrapper: remove serializerScheduleLocked; the lock is unnecessary

security/advancedtls/crl.go
With the addition of the CRL Provider interface and implementations, these old CRL APIs should not be used anymore.
=> Mark old CRL APIs as deprecated

interop/stress/client/main.go
Allows custom, Google specific credentials to be specified from the command line.
Also adds a final printout to stdout with the total amount of calls made. Stress tests can use that to determine the average QPS of a run.
=> interop: Custom creds for stress test client

xds/internal/server/listener_wrapper.go
One of these came up in the review of PR 6726 after it was merged. I made a pass through the file and cleaned up all the logs that I thought deserved a cleanup.
=> xds/internal/server: cleanup formatting directives in some logs

reflection/README.md
Accurately, grpc-go implements both v1 and v1alpha. But, it seems that v1alpha is deprecated. So I just changed the link to the v1 proto.
=> doc: fix link to the reflection protocol

balancer_wrapper.go, balancer_wrapper_test.go, clientconn.go, internal/channelz/funcs.go, internal/idle/idle.go, internal/idle/idle_e2e_test.go, internal/idle/idle_test.go, internal/internal.go, picker_wrapper.go, resolver_balancer_ext_test.go, resolver_wrapper.go
- Balancer wrapper is now recreated for each trip out of idle mode (instead of supporting its own idle mode).
- Removed mutexes or limited as much as possible.
- All calls into resolver/balancer are done in serializer, with no mutexes held.
- Calls from old resolver instances are ignored.
- ExitIdleCond is no longer needed by closing the idlenessMgr at the start of Close.
- Constructors figure out their own parameters from cc instead of being passed in.
- Handle resolver.Build->cc.updateResolverState->balancer.UpdateState->resolver.ResolveNow properly
- Idle Manager starts in idle state.
- All channel idleness management goes through idle manager -- e.g. Connect().
- Add lock and closed state to balancer_wrapper to prevent a race where the
balancer creates a subchannel and we enter idle …
=> client: rework resolver and balancer wrappers to avoid deadlock

clientconn.go, internal/resolver/unix/unix.go, resolver/resolver.go
Also implements the same for unix resolver's builder
Fixes #5360 
RELEASE NOTES:
* resolver: provide method for resolver to implement to override default channel authority (EXPERIMENTAL).
=> grpc: optional interface to provide channel authority

.github/dependabot.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/lock.yml, .github/workflows/release.yml, .github/workflows/stale.yml, .github/workflows/testing.yml
Fixes #6814.
This PR hash-pins all GitHub Actions to increase the workflows' resilience to broken or malicious workflows.
It also sets up dependabot to send a single monthly PR updating all Actions with new versions.
=> [infra] Hash-pin GitHub Actions, keep them updated with dependabot

benchmark/benchmain/main.go, dialoptions.go, internal/tcp_keepalive.go, internal/transport/http2_client.go, internal/transport/proxy.go, server.go
In https://github.com/grpc/grpc-go/pull/6672, we attempted to configure OS defaults for TCP keepalive parameters (keepalive time and interval). But this had the unintended consequence of disabling TCP keepalives completely because of the way things are implemented in the Go stdlib. In this PR, we attempt to do the following:
- Always enable TCP keepalives on client connections 
- This has been the behavior for a while because the Go stdlib enables TCP keepalives as long as the `net.Dialer.KeepAlive` field is not set to a negative value. 
- Explicitly setting the socket option ensures the old behavior persists.
- Use OS defaults for TCP keepalive interval and time
- We do this by setting the `net.Dialer.KeepAlive` field to a negative value, thereby disabling the Go …
=> client: always enable TCP keepalives with OS defaults

test/xds/xds_client_federation_test.go, xds/internal/resolver/serviceconfig.go, xds/internal/resolver/watch_service.go, xds/internal/resolver/xds_resolver.go, xds/internal/resolver/xds_resolver_test.go
=> xds/internal/resolver: switch to generic xDS API for LDS/RDS

internal/tcp_keepalive_nonunix.go, internal/tcp_keepalive_unix.go
In https://github.com/grpc/grpc-go/pull/6834, we made a change to ensure that OS defaults for TCP keepalive params are used. But, that change failed to compile on windows. This fix addresses it.
=> internal: use OS defaults for TCP keepalive params only on unix

security/advancedtls/advancedtls_test.go
Go 1.22 changed the default TLS minimum version. Toolchains which do not respect go.mod 'go' version directives will break when executing the Test/GetCertificatesSNI/Select_serverCert3 test, since it relies on the private tls.ClientHelloInfo.config fields minimum version matching the configured tls.ClientHelloInfo.SupportedVersions field. This change just bumps the version in tls.ClientHelloInfo.SupportedVersions to tls.VersionTLS12.
With Go 1.22, gRPC users will still be able to use TLS versions VersionTLS10, VersionTLS11 by utilizing MinVersion and MaxVersion parameters of ClientOptions struct.
b/315783527
=> security/advancedtls: fix test that relies on min TLS version

.github/dependabot.yml
As requested in https://github.com/grpc/grpc-go/pull/6835#issuecomment-1846253818, this PR configures dependabot to ignore major version bumps, reducing the risk of breaking changes.
If you wish, I can instead configure dependabot to send separate PRs with major version bumps. This way, you can easily identify and merge the "easy" minor/patch bumps, but also be notified of major version bumps that may require a bit more attention.
=>  Forbid dependabot from performing major version bumps

xds/internal/testutils/fakeclient/client.go, xds/internal/testutils/resource_watcher.go, xds/internal/xdsclient/client.go, xds/internal/xdsclient/clientimpl_watchers.go, xds/internal/xdsclient/tests/authority_test.go, xds/internal/xdsclient/tests/cds_watchers_test.go, xds/internal/xdsclient/tests/dump_test.go, xds/internal/xdsclient/tests/eds_watchers_test.go, xds/internal/xdsclient/tests/federation_watchers_test.go, xds/internal/xdsclient/tests/lds_watchers_test.go, xds/internal/xdsclient/tests/misc_watchers_test.go, xds/internal/xdsclient/tests/rds_watchers_test.go, xds/internal/xdsclient/tests/resource_update_test.go, xds/internal/xdsclient/xdsresource/type_cds.go, xds/internal/xdsclient/xdsresource/type_lds.go, xds/internal/xdsclient/xdsresource/type_rds.go
This PR gets rid of the old `WatchListener` and `WatchRouteConfig` APIs. This should be the last PR to call time on the old APIs.
=> completely delete WatchListener and WatchRouteConfig APIs

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
=> test/kokoro: Use the Kokoro shared install lib from the new repo

orca/call_metrics.go, orca/server_metrics.go
PR included:
- Use atomic pointers instead of mutex to improve performance.
- When the server metrics recorder is modified/written (e.g. `SetCPUUtilization`) create a new snapshot and atomically store it. When the server metrics recorder is read, return the reference to the latest snapshot. Similar in implementation to C++.
Motivation:
- See internal email thread and benchmarks regarding performance
Tested:
- `go test -cpu 1,4 -timeout 7m ./...`
- `go test -race -cpu 1,4 -timeout 7m ./...`
- Verified new implementation improved internal benchmark performance
RELEASE NOTES:
- orca: use atomic pointer to improve performance in server metrics recorder
=> orca: use atomic pointer instead of mutex in server metrics recorder to improve performance

interop/xds/client/Dockerfile, interop/xds/server/Dockerfile
=> interop/xds: Increase go log verbosity to 99 so that EDS is logged

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #6859 to v1.60.x.
---
=> test/kokoro: Use the Kokoro shared install lib from the new repo (v1.60.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #6859 to v1.59.x.
---
=> test/kokoro: Use the Kokoro shared install lib from the new repo (v1.59.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #6859 to v1.58.x.
---
=> test/kokoro: Use the Kokoro shared install lib from the new repo (v1.58.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #6859 to v1.57.x.
---
=> test/kokoro: Use the Kokoro shared install lib from the new repo (v1.57.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #6859 to v1.56.x.
---
=> test/kokoro: Use the Kokoro shared install lib from the new repo (v1.56.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #6859 to v1.55.x.
---
=> test/kokoro: Use the Kokoro shared install lib from the new repo (v1.55.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #6859 to v1.54.x.
---
=> test/kokoro: Use the Kokoro shared install lib from the new repo (v1.54.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #6859 to v1.53.x.
---
=> test/kokoro: Use the Kokoro shared install lib from the new repo (v1.53.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #6859 to v1.52.x.
---
Source: h[183/20479]thub.com/grpc/grpc/blob/4f7ead2c7b7b82ad80799bbfa482184991dcd346/tools/internal_ci/linux/grpc_xds_k8s_install_test_driver.sh
=> test/kokoro: Use the Kokoro shared install lib from the new repo (v1.52.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #6859 to v1.51.x.
---
=> test/kokoro: Use the Kokoro shared install lib from the new repo (v1.51.x backport)

internal/tcp_keepalive_others.go, internal/tcp_keepalive_windows.go
This is a followup to https://github.com/grpc/grpc-go/pull/6841.
This patch adds Windows support, alongside UNIX, to set TCP keepalives with OS defaults #6834.
RELEASE NOTES:
- client: correctly enable TCP keepalives with OS defaults on windows
=> internal: use OS defaults for TCP keepalive params in Windows

interop/xds/client/Dockerfile, interop/xds/server/Dockerfile
Backport of #6860 to v1.57.x.
---
=> interop/xds: Increase go log verbosity to 99 so that EDS is logged (v1.57.x backport)

interop/xds/client/Dockerfile, interop/xds/server/Dockerfile
Backport of #6860 to v1.56.x.
---
=> interop/xds: Increase go log verbosity to 99 so that EDS is logged (v1.56.x backport)

interop/xds/client/Dockerfile, interop/xds/server/Dockerfile
Backport of #6860 to v1.55.x.
---
=> interop/xds: Increase go log verbosity to 99 so that EDS is logged (v1.55.x backport)

interop/xds/client/Dockerfile, interop/xds/server/Dockerfile
Backport of #6860 to v1.54.x.
---
=> interop/xds: Increase go log verbosity to 99 so that EDS is logged (v1.54.x backport)

interop/xds/client/Dockerfile, interop/xds/server/Dockerfile
Backport of #6860 to v1.58.x.
---
=> interop/xds: Increase go log verbosity to 99 so that EDS is logged (v1.58.x backport)

interop/xds/client/Dockerfile, interop/xds/server/Dockerfile
Backport of #6860 to v1.59.x.
---
=> interop/xds: Increase go log verbosity to 99 so that EDS is logged (v1.59.x backport)

interop/xds/client/Dockerfile, interop/xds/server/Dockerfile
Backport of #6860 to v1.60.x.
---
=> interop/xds: Increase go log verbosity to 99 so that EDS is logged (v1.60.x backport)

internal/testutils/xds/e2e/setup_certs.go, test/xds/xds_client_certificate_providers_test.go, test/xds/xds_server_certificate_providers_test.go, test/xds/xds_server_integration_test.go, xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/resolver/xds_resolver.go, xds/internal/resolver/xds_resolver_test.go, xds/internal/server/conn_wrapper.go, xds/internal/server/listener_wrapper.go, xds/server.go, xds/server_test.go
We currently have checks in the xDS resolver and xDS-enabled gRPC server that verify that *if* xDS credentials are specified by the user, then the associated certificate providers configuration in the bootstrap is non-empty. If the check fails, then channel/server start-up fails. This is broken for a number of reasons:
- On the client, we could have multiple clusters, some of which specify valid security configuration (i.e certificate provider instance name that is present in the bootstrap) and some of which specify invalid security configuration (i.e certificate provider instance name that is not present in the bootstrap). In this scenario, the clusters with valid security configuration need to work and the ones with invalid security configuration should fail with TRANSIENT_FAILURE. The …
=> xds: don't fail channel/server startup when xds creds is specified, but bootstrap is missing certificate providers

internal/transport/handler_server_test.go
Regarding this little issue with deprecated function http.CloseNotify, 
https://github.com/grpc/grpc-go/issues/6782
I have decided to add just small pr for http.CloseNotify deprecated 
In this pull request, I have just removed the implementation, tests are going well, 
my other approach was this: 
to add and update `onlyCloseNotifier` interface, by doing this: 
```
type onlyContext {
http.ResponseWriter
context.Context
}
```
then to update whole `testHandlerResponseWriter` with corresponding context.Context methods, like these: 
```
type testHandlerResponseWriter struct {
*httptest.ResponseRecorder
done chan struct{}
err error
value any
deadline time.Time
ok bool
}
func (w testHandlerResponseWriter) Deadline() (deadline time.Time, ok bool) {return time.Time{}, false}
func (w …
```
=> removing deprecated http closenotifier function

credentials/alts/alts_test.go, credentials/alts/internal/handshaker/handshaker.go, credentials/alts/internal/handshaker/handshaker_test.go
Reverts grpc/grpc-go#6884, due to flakiness introduced in the e2e tests (https://github.com/grpc/grpc-go/issues/6890). I think (but am not 100% sure) that these failures are due to the test setup, but reverting the PR to be safe while I investigate.
=> Revert "alts: Queue ALTS handshakes once limit is reached rather than dropping."

test/xds/xds_client_certificate_providers_test.go, xds/internal/xdsclient/xdsresource/listener_resource_type.go
=> fix 'identitiy' typo in error message  

binarylog/grpc_binarylog_v1/binarylog.pb.go, vet.sh
- #6886 removed the usage of the deprecated function. However we need to remove the ignore of the usage from vet.sh as well. 
=> vet: remove ignore of CloseNotifier

rpc_util.go, test/compressor_test.go
Fixes #6831.
This avoids compressing messages that are empty, since you can't compress zero bytes to anything smaller than zero bytes, and most compression algorithms output headers and trailers which means the resulting message will be non-zero bytes.
RELEASE NOTES:
- grpc: skip compression of empty messages (as an optimization)
=> grpc: skip compression of empty messages

examples/features/authentication/README.md
Previously the <token-type> and <token> elements were invisible in GitHub because it treated them as HTML tags.
=> examples: Fixed the formatting in the Authentication README.md

internal/transport/http2_server.go, internal/transport/transport_test.go
The current behavior when server sees a connection failure, when trying to write headers, is to return `UNKNOWN` status code. This PR changes the behavior to instead return `UNAVAILABLE` in this case, which is what would be generated by the client if it saw the connection failure when making the RPC.
Fixes https://github.com/grpc/grpc-go/issues/6845
RELEASE NOTES:
- server: change some stream operations to return `UNAVAILABLE` instead of `UNKNOWN` when underlying connection is broken
=> internal/transport: convert `ConnectionError` to `Unavailable` status when writing headers

credentials/alts/alts_test.go, credentials/alts/internal/handshaker/handshaker.go, credentials/alts/internal/handshaker/handshaker_test.go
This PR builds on #6884, which was reverted in #6903 because of flakiness in `alts_test.go`. It turned out that this flakiness  was just due to the test occasionally bumping up on the timeout, so we've fixed this in this PR by increasing the timeout.
=> alts: Forward-fix of ALTS queuing of handshake requests.

credentials/tls/certprovider/pemfile/watcher_test.go, credentials/tls/certprovider/store_test.go, vet.sh
Regarding this issue, https://github.com/grpc/grpc-go/issues/6782
one of the goals was to remove usage of deprecated field `Subjects`, which is not being returned by `SystemCertPool` anymore, more details here https://pkg.go.dev/crypto/x509#CertPool.Subjects
also I have updated these tests so we compare got and wanted CertPool structs, by using https://pkg.go.dev/crypto/x509#CertPool.Equal
=> removing Roots deprecated Subjects field in tests

credentials/alts/alts_test.go
=> alts: Extract AuthInfo after handshake in ALTS e2e test.

internal/transport/http2_client.go
This PR fixes a typo in http2Client, removing the redundant checks in the `handleGoAway`
=> transport: Remove redundant if in handleGoAway

test/xds/xds_server_test.go
This PR correctly differentiates messages and services as, they come in distinct imports.
=> test/xds: Use different import path for gRPC Messages

internal/transport/http2_server.go
In internal/transport/http2_server.go, around line 640, the if-else branches contain the identical code, and should be combined:
```go
if err == io.EOF || err == io.ErrUnexpectedEOF {
t.Close(err)
return
}
t.Close(err)
return
```
=> internal/transport: Remove redundant if conditional in http2_server

xds/googledirectpath/googlec2p.go, xds/googledirectpath/googlec2p_test.go
As title.
Integration tests passing.
*  xds/googlec2p: use xdstp names for LDS
=> xds/googlec2p: use xdstp names for LDS

interop/client/client.go, interop/http2/negative_http2_client.go, interop/observability/client/client.go, interop/stress/client/main.go, interop/test_utils.go, interop/xds_federation/client.go
=> interop: Replace context.Background() with passed ctx

status/status_test.go
The protoimpl package is being currently used in a test (which got introduced in #6919). But this package cannot be accessed directly in google3, hence we need a different way of testing the case. 
=> status: modify TestStatus_ErrorDetails_Fail to replace protoimpl package

interop/client/client.go, interop/test_utils.go, vet.sh
golint in google3 caught these linter issues + 1 typo during the weekly import
=> .*: fix minor linter issues

internal/grpcrand/grpcrand.go, internal/grpcrand/grpcrand_go1.21.go
This PR closes issue #6650.
**What I did**
I duplicated all functions in `grpcrand` package into another file, changing the implementation to call top-level functions of Go `math/rand` package internally, adding the `_go1.21` suffix to new file name and build comments to both files, to instruct the Go compiler to compile the new file instead of the original one for Go 1.21 or higher.
**Why**
As described in the related issue, apart from reducing complexity, it is concurrent safe as of Go 1.21, and also significantly faster. I ran a benchmark to demonstrate the difference.
```go
import (
"math/rand"
"sync"
"testing"
"time"
)
var (
r  = rand.New(rand.NewSource(time.Now().UnixNano()))
mu sync.Mutex
)
func BenchmarkIntMutex(b *testing.B) {
for i := 0; i < b.N; i++ {
IntMutex()
}
}
func …
```
=> internal/grpcrand: use Go top-level random functions for go1.21+

xds/googledirectpath/utils.go
This PR checks if the returned ipv6 address is non empty when queried in the google direct path resolver.
=> xds/googledirectpath: Check if ipv6 address is non empty

server.go, stream.go, trace.go, trace_notrace.go, trace_withtrace.go
golang.org/x/net/trace is the only dependency of gRPC Go that depends -- through html/template and text/template -- on reflect's MethodByName. Binaries with MethodByName are not eligible for Go dead code elimination.
As of protobuf v1.32.0 combined with Go 1.22, Go protobufs support compilation with dead code elimination. This commit allows users of gRPC Go to also make use of dead code elimination for smaller binary sizes.
---
What's the best place to insert a build test to make sure that `go build -tags=grpcnotrace ./...` still builds?
RELEASE NOTES:
* *: Allow building without `x/net/trace` by using `grpcnotrace` to enable dead code elimination
=> grpc: add ability to compile with or without tracing

xds/googledirectpath/googlec2p.go, xds/googledirectpath/googlec2p_test.go
This reverts commit 3aafa84f176227b9ba75240cdd41918d305f066d.
As described in https://github.com/grpc/proposal/blob/master/A47-xds-federation.md#bootstrap-config-changes, `client_listener_resource_name_template` *inside the authority map* should default to `xdstp://<authority_name>/envoy.config.listener.v3.Listener/%s`, so #6949 shouldn't be necessary.
cc @arvindbr8 
=> Revert "xds/googlec2p: use xdstp names for LDS (#6949)"

encoding/proto/proto.go
In `encoding/proto.go` when Marshal() and Unmarshal() we should be able to handle both v1 and v2 of proto messages. But in #6919 we broke backwards compatibility of able to handle v1 proto messages. This change fixes that. 
cc: @Clement-Jean 
=> deps: fix backwards compatibility with encoding

encoding/proto/proto.go
=> encoding: fix typo

internal/internal.go, xds/internal/xdsclient/xdsresource/filter_chain.go
=> xds/internal/xdsclient: Add comments for exported types

internal/transport/controlbuf.go, internal/transport/http2_client.go, internal/transport/http2_server.go
Replaces #6957
Fixes #5358 (A modified version of the test in that issue runs for 5+ minutes without failing with these changes.  On a broken branch it fails reliably within 30s, and often much faster.)
See also https://github.com/grpc/grpc-java/issues/9566 and https://github.com/golang/net/commit/cd69bc3fc700721b709c3a59e16e24c67b58f6ff / https://github.com/golang/go/issues/18701
This change also adjusts the ping timer after sending the initial GOAWAY from 1 minute to 5 seconds at @ejona86's recommendation.
RELEASE NOTES:
* server: wait to close connection until incoming socket is drained (with timeout) to prevent data loss on client-side
=> server: wait to close connection until incoming socket is drained (with timeout)

credentials/local/local.go
Communication over named pipes on Windows is local IPC.
RELEASE NOTES:
- Set the security level of Windows named pipes to NoSecurity
=> Set the security level of Windows named pipes to NoSecurity

internal/transport/http2_server.go, vet.sh
This particular use seems pretty harmless, but I think we might as well forbid this problematic function that can leak timers as a rule.
=> *: forbid the use of time.After

rpc_util.go
This PR adds a call option that specifies whether a method is static. This is intended to be used by generated code and users to get a method attribute within OpenTelemetry while protecting the cardinality of OpenTelemetry timeseries.
RELEASE NOTES:
* grpc: Add StaticMethod CallOption as a signal to stats handler that a method is safe to use as an instrument key.
=> grpc: Add StaticMethod CallOption

clientconn.go, clientconn_test.go, resolver/resolver.go
This PR canoncializes the string returned from Target() on the ClientConn. This is a behavior change, but ok because API is marked experimental.
RELEASE NOTES:
* grpc: Canonicalize string returned by ClientConn.Target() and resolver.Address.String()
=> grpc: Canonicalize string returned by ClientConn.Target() and resolver.Address.String()

dialoptions.go, internal/transport/http_util.go, server.go
This is a minor change to fix an inconsistency in #6309 
It seems in the past, for unknown reasons (see [comment](https://github.com/grpc/grpc-go/pull/6309/files#r1490181244)), the write buffer would be [allocated to 2x the input size](https://github.com/grpc/grpc-go/blame/d524b409462c601ef3f05a7e1fba19755a337c77/internal/transport/http_util.go#L321). It's been [fixed since](https://github.com/grpc/grpc-go/blob/408139acc3066657dbe63938447a10af64d79347/internal/transport/http_util.go#L314-L316), but is still 2x the size for the shared buffer. 
Edit: it seems like the reasons aren't really unknown, the buffer allocation was 2x the size to [keep syscalls low](https://github.com/grpc/grpc-go/blob/d524b409462c601ef3f05a7e1fba19755a337c77/server.go#L239-L240). If syscalls become a performance …
=> transport: when using write buffer pooling, use input size instead of size*2

internal/transport/handler_server.go, internal/transport/handler_server_test.go
This tweaks `transport.NewServerHandlerTransport` so that it behaves more like the normal HTTP/2 transport returned by `transport.NewServerTransport` with regard to requests with the wrong HTTP method. In particular, it now sends back a _405 Method Not Allowed_ status code and correctly sets an `Allow` response header.
I've also moved the HTTP version check to after we've confirmed that this is a gRPC request (via content-type check) and changed that to also use a more appropriate HTTP status code: _505 HTTP Version Not Supported_. (This is not really related to consistency since the other transport never has to worry about HTTP 1.1 requests. But it makes the checks a little more coherent since IMO it seems more appropriate to reject the HTTP version only once we've confirmed that it's a …
=> transport: Make error-handling for bad HTTP method consistent between HTTP/2 server transport and handler server transport

internal/transport/transport.go, server.go, test/compressor_test.go
=> fix enabling compression by trimming whitespaces in accept encoding header

experimental/shared_buffer_pool_test.go, rpc_util.go, server.go
Fixes #6578
- Resolved unintended deactivation scenarios:
- During unary RPC calls.
- When compression is enabled.
- Also corrected missing `payInfo.uncompressedBytes` in `Server.processUnaryRPC`.
RELEASE NOTES:
- rpc_util: The `RecvBufferPool` option is now active during unary RPC and in compression is enabled.
- stats: The stats handler now accurately tracks `uncompressedBytes` during unary RPC calls.
=> rpc_util: Fix `RecvBufferPool` deactivation issues

.github/workflows/testing.yml
=> github: add Go 1.22 testing

clientconn.go, internal/testutils/xds/e2e/clientresources.go, resolver/resolver.go, resolver_wrapper.go, test/xds/xds_client_federation_test.go, xds/internal/resolver/helpers_test.go, xds/internal/resolver/xds_resolver.go, xds/internal/resolver/xds_resolver_test.go
Fixes #6996 
A new field `Authority` is added to `resolver.BuildOptions` to pass the effective authority of clientconn for which the resolver was built. 
Testing:
I have verified that this diff works with the bootstrap generator @ https://github.com/GoogleCloudPlatform/traffic-director-grpc-bootstrap/pull/57. 
<details>
<summary>Test logs</summary>
```
2024/02/22 00:39:20 INFO: [core] [Channel #1] Channel created
2024/02/22 00:39:20 INFO: [core] [Channel #1] original dial target is: "xds:///helloworld-gke:8000"
2024/02/22 00:39:20 INFO: [core] [Channel #1] parsed dial target is: resolver.Target{URL:url.URL{Scheme:"xds", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"/helloworld-gke:8000", RawPath:"", OmitHost:false, ForceQuery:false, RawQuery:"", Fragment:"", RawFragment:""}} …
```
=> xdsclient: use dataplane authority for virtualhost lookup

experimental/shared_buffer_pool_test.go
In https://github.com/grpc/grpc-go/pull/6766, the double import was removed. This PR adds that back.
=> experimental: re-split message/service pb imports

clientconn.go, internal/testutils/xds/e2e/clientresources.go, resolver/resolver.go, resolver_wrapper.go, test/xds/xds_client_federation_test.go, xds/internal/resolver/helpers_test.go, xds/internal/resolver/xds_resolver.go
RELEASE NOTES:
* resolver: Add `Authority` to `resolver.BuildOptions` pass the effective authority of clientconn for which the resolver was built
=> cherry-pick #6997 to 1.62.x release branch (#6979)

experimental/shared_buffer_pool_test.go, internal/transport/transport.go, rpc_util.go, server.go, test/compressor_test.go
Cherry-pick #6766 and #6952 
RELEASE NOTES:
- rpc_util: The `RecvBufferPool` option is now active during unary RPC and in compression is enabled.
- stats: The stats handler now accurately tracks `uncompressedBytes` during unary RPC calls.
=> Cherry pick #6766 and #6952 to v1.62.x release branch

internal/resolver/dns/dns_resolver.go, internal/resolver/dns/dns_resolver_test.go, internal/resolver/dns/fake_net_resolver_test.go, resolver/dns/dns_resolver.go
Currently, the DNS resolver does not have a timeout mechanism for DNS resolution. In some edge cases, where the DNS server is slow to respond, this can lead to stale records being used, resulting in failed connections or other issues.
This pull request adds a configurable timeout for DNS resolution, which can be set by the user to a value that suits their needs. The default value is set to 5 seconds, which should be sufficient for most cases. If the DNS server does not respond within the specified time, the resolver will cancel the request and move on to the next available server.
Please review and let me know if you have any questions or concerns.
Thanks!
RELEASE NOTES:
* resolver/dns: add SetResolvingTimeout to allow configuring the DNS resolver's timeout globally.
=> DNS resolving with timeout

xds/internal/xdsclient/transport/transport.go, xds/internal/xdsclient/transport/transport_resource_test.go
Fixes #7013
RELEASE NOTES:
* xds: fix an issue that would cause the client to send an empty list of resources for LDS/CDS upon reconnecting with the management server
=> xdsclient: correct logic used to suppress empty ADS requests on new streams

clientconn.go, clientconn_parsed_target_test.go, dialoptions.go
Also added a test and removed an unused parameter from a function and call sites.  (The reason it was needed in the past is to auto-detect the gRPCLB LB policy, which is functionality we no longer support.)
=> grpc: clean up doc strings and some code around Dial vs NewClient

balancer/leastrequest/balancer_test.go, balancer/weightedroundrobin/scheduler.go, clientconn.go, examples/features/observability/client/main.go, examples/features/observability/server/main.go, test/authority_test.go, test/xds/xds_client_outlier_detection_test.go, xds/internal/balancer/outlierdetection/e2e_test/outlierdetection_test.go
=> chore: remove repetitive words

xds/internal/balancer/clusterimpl/balancer_test.go, xds/internal/balancer/clusterimpl/picker.go, xds/internal/xdsclient/transport/loadreport_test.go
Design:
* go/grpc-xds-lrs-named-metrics
* go/lrs-named-metrics-design-review-slides
* Implements gRFC A64 https://github.com/grpc/proposal/blob/master/A64-lrs-custom-metrics.md
* Only include named metrics from `OrcaLoadReport` and remove all previous fields (e.g. CPU utilization, memory utilization, etc.) as they are unused
* Added  xDS clusterImpl balancer tests to verify named metrics aggregation logic
* Added completely missing tests for `UpstreamLocalityStats` to verify aggregation logic
Tested:
* `VET_SKIP_PROTO=1 ./vet.sh`
* `go test -cpu 1,4 -timeout 7m ./...`
* `go test -race -cpu 1,4 -timeout 7m ./...`
* Tested end-to-end by spinning up test client/server  and verified named metrics from the `OrcaLoadReport` are aggregated and send in LRS load reports
RELEASE NOTES:
* xds: …
=> xds: add LRS named metrics support

clientconn.go, internal/channelz/funcs.go, test/channelz_test.go
=> channelz: re-add target and state

clientconn.go, test/channelz_test.go
=> channelz: re-add state for subchannels

xds/googledirectpath/googlec2p.go, xds/googledirectpath/googlec2p_test.go
The google c2p resolver should be using the new xdstp style names for LDS resource names. Also adds "xds.config.resource-in-sotw" to `server_features` which is also required by the google c2p resolver. 
=> googlec2p: use xdstp style template for client LDS resource name

cmd/protoc-gen-go-grpc/grpc.go
Closes #7054
With proto of
```proto
syntax = "proto3";
package foobar;
option go_package = "github.com/foobar";
service Foobar {}
```
you get
```go
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: service-foobar.proto
package popsa
import (
grpc "google.golang.org/grpc"
)
// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7
const ()
// FoobarClient is the client API for Foobar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStr …
```
=> cmd/protoc-gen-go-grpc: don't emit const blocks for services with no methods

server.go, test/channelz_test.go
=> channelz: add LocalAddr to listen sockets and test

examples/features/encryption/README.md
When I read the above document, I found several small mistakes. In order to prevent misunderstandings among newcomers while reading. I fix those mistakes and add instructions for key files in the mTLS example.
=> examples: Update features/encryption/README.md file

default_dial_option_server_option_test.go, dialoptions.go, server.go
Similar to https://github.com/grpc/grpc-go/pull/1902, it is good to export the header list sizes for users to know what is the existing metadata size limit.
=> grpc: Export header list sizes in DialOption and ServerOption

internal/channelz/funcs.go
=> channelz: fix race accessing channelMap without lock

internal/channelz/funcs.go
=> cherry-pick: channelz: fix race accessing channelMap without lock (#7079)

internal/transport/http2_server.go
`kpTimeoutLeft` is calculated from `kp.Timeout`, but the error message implies it's based on `kp.Time`.
RELEASE NOTES:
- transport/server: use the proper timeout value when keepalive pings are not ack'd in time
=> Fix: error message using correct keepalive config value

clientconn.go, dialoptions.go
Fixes https://github.com/grpc/grpc-go/issues/7095
Notice in `NewClient` GoDoc comment that `FailOnNonTempDialError` dial option is ignored.
Deprecate options that are ignored by `NewClient` function.
These options are only supported by deprecated `Dial` and `DialContext` functions.
RELEASE NOTES:
- grpc: Deprecate WithBlock, WithReturnConnectionError, FailOnNonTempDialError which are ignored by NewClient
=> grpc: Deprecate WithBlock, WithReturnConnectionError, FailOnNonTempDialError

internal/resolver/dns/dns_resolver.go, internal/resolver/dns/dns_resolver_test.go, internal/resolver/dns/internal/internal.go, resolver/dns/dns_resolver.go
In this merge request I tried to make `SetMinResolutionInterval` which is currently a constant duration variable by providing options. SetMinResolutionInterval sets the default minimum interval at which DNS re-resolutions are allowed. This helps to prevent excessive re-resolution.
RELEASE NOTES:
- resolver/dns: Add SetMinResolutionInterval sets the default minimum interval at which DNS re-resolutions are allowed.
=> resolver/dns: Add SetMinResolutionInterval Option

channelz/service/service_test.go, clientconn.go, internal/channelz/funcs.go, internal/transport/keepalive_test.go, internal/transport/transport_test.go, test/channelz_test.go
This fixes logging that, with channelz off, would omit the channel ID in subchannel logs.
=> channelz: pass parent pointer instead of parent ID to RegisterSubChannel

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
=> test/kokoro: Migrate PSM Interop to Artifact Registry

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #7102 to v1.54.x.
---
=> test/kokoro: Migrate PSM Interop to Artifact Registry (v1.54.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #7102 to v1.55.x.
---
=> test/kokoro: Migrate PSM Interop to Artifact Registry (v1.55.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #7102 to v1.58.x.
---
=> test/kokoro: Migrate PSM Interop to Artifact Registry (v1.58.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #7102 to v1.57.x.
---
=> test/kokoro: Migrate PSM Interop to Artifact Registry (v1.57.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #7102 to v1.60.x.
---
=> test/kokoro: Migrate PSM Interop to Artifact Registry (v1.60.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #7102 to v1.59.x.
---
=> test/kokoro: Migrate PSM Interop to Artifact Registry (v1.59.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #7102 to v1.62.x.
---
=> test/kokoro: Migrate PSM Interop to Artifact Registry (v1.62.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #7102 to v1.61.x.
---
=> test/kokoro: Migrate PSM Interop to Artifact Registry (v1.61.x backport)

test/kokoro/psm-security.sh, test/kokoro/xds_k8s_lb.sh, test/kokoro/xds_url_map.sh
Backport of #7102 to v1.63.x.
---
=> test/kokoro: Migrate PSM Interop to Artifact Registry (v1.63.x backport)

xds/internal/xdsclient/xdsresource/type_cds.go, xds/internal/xdsclient/xdsresource/unmarshal_cds.go, xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
This PR adds processing in CDS for string telemetry labels with filter_metadata string "com.google.csm.telemetry_labels". Other value types and filter_metadata identifiers are ignored. This also does not introduce NACK's. This is based off the C-Core implementation, which I disagree with technically but understand there were good reasons for the decisions made. See discussion in xDS Chat room for context as to why C-Core did it this way and why I followed it.
The relevant language in the CSM Observability Design is "The above key_value pairs from `com.google.csm.telemetry_labels` are going to be parsed by xDS Client from the CDS Resource and propagated to the watcher on this resource in the “cds” load balancing policy."
=> xds/internal/xdsclient: Process string metadata in CDS for com.google.csm.telemetry_labels

stats/stats.go
cc @papacharlie
RELEASE NOTES:
* stats: deprecate `InPayload.Data` and `OutPayload.Data`; they were experimental and will be deleted in the next release
=> stats: mark InPayload.Data and OutPayload.Data for deletion (experimental)

internal/stats/labels.go, test/xds/xds_telemetry_labels_test.go, xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/clusterimpl/clusterimpl.go, xds/internal/balancer/clusterimpl/config.go, xds/internal/balancer/clusterimpl/picker.go, xds/internal/balancer/clusterresolver/config.go, xds/internal/balancer/clusterresolver/configbuilder.go
This PR plumbs the Telemetry Labels from CDS through our xDS Balancer tree through the context that eventually get passed to stats handler.
=> xds: Process telemetry labels from CDS in xDS Balancers

clientconn.go
RELEASE NOTES:
* client: improve RPC performance by reducing work while holding a lock
=> client: Drop two calls to `pretty.ToJSON` and move code outside of lock

security/advancedtls/advancedtls.go, security/advancedtls/advancedtls_test.go, security/advancedtls/crl.go, security/advancedtls/crl_test.go
ServerNameOverride is test-only
RevocationStatus, CheckRevocation, and CheckChainRevocation are not used externally and should not be exported
=> advancedtls: unexport parts of API not meant to be public

internal/transport/controlbuf.go, internal/transport/http2_client.go, internal/transport/http2_server.go, internal/transport/transport_test.go, test/goaway_test.go
Fixes #460 
RELEASE NOTES:
* client: client sends GOAWAY to server on graceful shutdown
=> Send GOAWAY to server on Client Transport Shutdown

xds/internal/xdsclient/xdslbregistry/xdslbregistry.go
I was reading through the implementation for custom lb polices and noticed a call to the policy type URL wasn't being used
=> xds/internal/xdsclient/xdslbregistry: remove unused call to type url

internal/transport/controlbuf.go, internal/transport/http2_client.go, internal/transport/http2_server.go, internal/transport/transport_test.go
=> transport: misc cleanups

internal/transport/http2_client.go
This is on top of #7147, and the incremental part fixes any potential race from accessing t.nextID
=> transport: make nextID accessed inside t.mu only

channelz/internal/protoconv/sockopt_linux.go, channelz/internal/protoconv/sockopt_nonlinux.go, channelz/internal/protoconv/util.go, reflection/test/grpc_testing_not_regenerate/dynamic.proto, reflection/test/grpc_testing_not_regenerate/testv3.proto, regenerate.sh, scripts/vet.sh
`vet.sh` was failing in macOS. The logger defined in channelz/internal/protoconv package was not used when build on non_linux machines, which caused staticcheck to output this: 
```
channelz/internal/protoconv/util.go:27:5: var logger is unused (U1000)
```
also fixes the go_package for grpc_testing_not_regenerate proto
=> *: fix regenerate.sh

security/advancedtls/advancedtls.go, security/advancedtls/advancedtls_integration_test.go, security/advancedtls/advancedtls_test.go, security/advancedtls/examples/credential_reloading_from_files/client/main.go, security/advancedtls/examples/credential_reloading_from_files/server/main.go
This PR renames `VType` to `VerificationType` for clarity.
It marks `VType` as deprecated. For now, if `VType` is explicitly set (does not have the default value) then we set `VerificationType` to `VType` so that user behavior doesn't break.
=> advancedtls: Rename VType

stats/opencensus/stats.go
=> stats/opencensus: Handle `PickerUpdated` to avoid "Received unexpected stats" error

xds/internal/xdsclient/xdsresource/filter_chain.go
when I want to add feature for linter [makezero](https://github.com/ashanbrown/makezero) in PR https://github.com/ashanbrown/makezero/pull/15 , I run a github action for real world repos, and the action result report this bug.
=> xds/internal/xdsclient/xdsresource: Preallocate VirtualHost slice correctly

examples/gotutorial.md
Point to the Go quickstart link which has the instructions for installing protoc and the required plugins.
=> examples: fix the quickstart link in the routeguide example

security/advancedtls/crl_provider.go
Clear up required vs. optional fields in FileWatcherOptions
=> advancedtls: Add notes about required vs. optional for FileWatcherOptions

xds/internal/balancer/priority/balancer.go, xds/internal/xdsclient/authority.go, xds/internal/xdsclient/bootstrap/bootstrap.go
… to limit calls to `pretty.ToJSON`
=> xds/internal: Replace calls to `Debugf` with `V(2)` checks and `Infof`

clientconn.go, test/channelz_test.go
Fixes #7187 
RELEASE NOTES:
- channelz: fix bug that was causing the subchannel's target to be unset
=> channelz: fix missing Target on SubChannel type

test/end2end_test.go
While working on another PR leak checker found this when this test failed
=> test: fix possible leaked goroutine in TestDetailedConnectionCloseErrorPropagatesToRpcError

security/advancedtls/advancedtls.go, security/advancedtls/advancedtls_integration_test.go, security/advancedtls/advancedtls_test.go
This PR renames the `MinVersion` and `MaxVersion` on `ClientOptions` and `ServerOptions` to `MinTLSVersion` and `MaxTLSVersion` to make it clear that this field represents the TLS version.
It also adds logic to set the default min and max to TLS12 and TLS13 respectively, and a tests for that logic.
Previously our code comments indicated this was the default, but we really just delegated to the defaults of the crypto/tls package (which are currently the same). Now we explicitly set to the defaults that we say we do, rather than depending on a dependency's defaults to match ours.
=> advancedTLS: Rename {Min/Max}Version to {Min/Max}TLSVersion

security/advancedtls/advancedtls_test.go, security/advancedtls/crl.go, security/advancedtls/crl_test.go
Swap `AllowUndetermined` to `DenyUndetermined` in our revocation settings.
We want the default for this setting to be to allow `RevocationUndetermined` to pass revocation checks, so the boolean needs to be `DenyUndetermined` (default false) for this behavior.
=> advancedTLS: Swap to DenyUndetermined from AllowUndetermined in revocation settings

security/advancedtls/advancedtls.go, security/advancedtls/advancedtls_integration_test.go, security/advancedtls/advancedtls_test.go, security/advancedtls/sni.go
`ClientOptions` and `ServerOptions` were basically identical minus a few fields. Duplicating so much code and documentation is messy. Given both have a single field each that are not relevant to the other, I think that we can just combine them and document that.
=> advancedTLS: Combine `ClientOptions` and `ServerOptions` to just `Options`

balancer_wrapper.go, metadata/metadata.go, metadata/metadata_test.go, peer/peer.go, peer/peer_test.go
Effectively allowing to print contextes containing a `Peer` properly.
Instead of printing with `%v` as:
```
context.Background.WithValue(type peer.peerKey, val <not Stringer>)
```
contexts containing a peer will now print as:
```
context.Background.WithValue(type peer.peerKey, val Peer{Addr: '1.2.3.4:1234', AuthInfo: 'testAuthInfo'})
```
This is also satisfying Stringer interface for `Metadata`, allowing to print them easily too. Since `Metadata` are basically a map, notice that `String` output is not stable. I could change it to print it in alphabetical order if you prefer.
RELEASE NOTES:
- peer/peer: implement the Stringer interface for pretty printing Peer
- metadata/metadata: implement the Stringer interface for pretty printing MD
=> peer and metadata: Implement the Stringer interface for Peer and Metadata

peer/peer_test.go
This change detector test seems asserts for an exact match and relies on the go std library print statements which can be subjected to change. 
=> peer: remove change detector test

picker_wrapper.go, picker_wrapper_test.go
Fixes #7135
add user-friendly error message of LB policy update timed out.
refer to PR https://github.com/grpc/grpc-go/pull/7143
=> client: add user-friendly error message of LB policy update timed out

internal/envconfig/envconfig.go, internal/grpcutil/compressor.go
RELEASE NOTES:
- codec: remove handling of environment variable `GRPC_GO_ADVERTISE_COMPRESSORS` to suppress setting supported compressors in `grpc-accept-encoding` header.  Compressors will always be advertised, as they have been by default for some time.
=> codec: remove option to suppress setting supported compressors in headers

security/advancedtls/advancedtls.go, security/advancedtls/advancedtls_integration_test.go, security/advancedtls/advancedtls_test.go
This PR renames `GetRootCAsParams` to `ConnectionInfo` and `GetRootCAsResults` to `RootCertificates` to better name what these structs actually represent.
=> advancedTLS: Rename get root certs related pieces

resolver/dns/dns_resolver.go
SetMinResolutionInterval was added as part of https://github.com/grpc/grpc-go/pull/6962. We need talk about calling the method only during init time, since modifying this value afterwards is not thread-safe. 
Also marking resolver/dns package as not deprecated. The reason for marking this deprecated is to limit the usage to gRPC and discourage users from using this.
=> resolver/dns: Add docstring to SetMinResolutionInterval

xds/internal/balancer/clusterimpl/clusterimpl.go, xds/internal/balancer/clusterresolver/clusterresolver.go
=> xds: Surround two `Infof` calls that use `pretty.ToJSON` with `V(2)` checks

security/advancedtls/advancedtls.go
I changed `RevocationConfig` to `RevocationOptions` in https://github.com/grpc/grpc-go/pull/7151 and missed leaving the old name as a deprecated option so that migrating is easier. This PR adds it back so that we shouldn't be actively breaking code.
=> advancedTLS: Add in deprecated name for transitionary period

security/advancedtls/advancedtls.go
Add documentation to the main package, the `RootCertificateOptions` struct, and the `IdentityCertificateOptions` struct.
=> advancedTLS: Documentation

balancer_wrapper.go, picker_wrapper.go
=> pickerwrapper: use atomic instead of locks

Documentation/anti-patterns.md
Add the missing "\`" for `FailOnNonTempDialError` in anti-patterns.md.
=> documentation: fix typo in anti-patterns.md

security/advancedtls/advancedtls.go, security/advancedtls/advancedtls_test.go
There is a check to make sure that only one field of `RootOptions` is set. In copying the value of a deprecated field, there was a potential for multiple to be set. This PR sets the old field to nil after copying it.
=> advancedTLS: unset a deprecated field after copying it

clientconn.go, default_dial_option_server_option_test.go, dialoptions.go, internal/internal.go
This PR adds an internal only (exported, but can only set through internal/) LateApplyDialOption type. This will be used in CSM Observability.
=> grpc: Add perTargetDialOption type and global list

credentials/tls.go, credentials/tls_ext_test.go, internal/envconfig/envconfig.go
Fixes https://github.com/grpc/grpc-go/issues/434
Since HTTP/2 mandates the use of ALPN during the TLS handshake to establish connections, gRPC clients will reject connections to servers that don't have ALPN enabled. gRPC servers will also reject TLS connections from clients with ALPN disabled.
As this change can break existing clients, this behaviour is guarded by an environment variable flag. The error message returned is similar to the [message returned by the C++ implementation](https://github.com/grpc/grpc/blob/master/src/core/lib/security/security_connector/ssl_utils.cc#L138).
- credentials/tls: clients and servers will reject connections that don't support ALPN when environment variable "GRPC_ENFORCE_ALPN_ENABLED" is set to "true" (case insensitive).  This behavior …
=> credentials/tls: reject connections with ALPN disabled

xds/csds/csds.go, xds/internal/xdsclient/authority.go, xds/internal/xdsclient/client.go, xds/internal/xdsclient/clientimpl_dump.go, xds/internal/xdsclient/tests/dump_test.go, xds/internal/xdsclient/tests/resource_update_test.go
Addresses https://github.com/grpc/grpc-go/issues/6898
This PR does not cover all changes required to support A71 in CSDS. It changes the `DumpResources` API on the `XDSclient` interface to return the actual proto message for the CSDS response. The eventual goal is as follows:
- remove the `DumpResources` method from the `XDSClient` interface
- unexport the `DumpResources` method on the `clientImpl` type which is the implementation of the `XDSClient` interface
- have a package level function `xdsclient.DumpResources()` with returns the CSDS response proto
- this function would go through the list of available xDS clients, and invoke their `dumpResources()` method and collate all the responses and return one
- CSDS service implementation would call the above package level function
I'm …
=> xds: change the DumpResources API to return proto message containing the resource dump

internal/balancergroup/balancergroup.go, internal/balancergroup/balancergroup_test.go, xds/internal/balancer/clustermanager/balancerstateaggregator.go, xds/internal/balancer/clustermanager/clustermanager.go, xds/internal/balancer/clustermanager/clustermanager_test.go, xds/internal/balancer/clustermanager/e2e_test/clustermanager_test.go
This PR makes the following API change to the `balancergroup` package:
- Adds a `ParseConfig` method
- Removes the `UpdateBuilder` method
- The above closely aligns with the approach taken by the `gracefulswitch` balancer
- Users of the `balancergroup` that want to change the child policy for a particular child, should call `ParseConfig` with the new configuration, and call `UpdateClientConnState`. This will result in graceful switchover to the new child policy.
This PR also has a bunch of cleanup in the `clustermanager` LB policy:
- Use the `balancer.ConnectivityStateManager` instead of manually computing aggregate connectivity state
- Use the newly added `balancergroup` API described above
- A bunch of code in the `StateAggregator` implementation in `clustermanager` seems obsolete (like …
=> balancergroup: add a `ParseConfig` API and remove the `UpdateBuilder` API

test/goaway_test.go
Fixes #7160 
fix: `goaway_test/TestClientSendsAGoAway` didn't use to wait for channels to be ready and which is why sometimes it was not able to read the frame and eventually result in test failure. This PR change make sure we read the frame only when the channel's state becomes READY.
=> test: fix flaky test ClientSendsAGoAway

channelz/grpc_channelz_v1/channelz_grpc.pb.go, cmd/protoc-gen-go-grpc/grpc.go, examples/features/proto/echo/echo_grpc.pb.go, examples/helloworld/helloworld/helloworld_grpc.pb.go, examples/route_guide/routeguide/route_guide_grpc.pb.go, health/grpc_health_v1/health_grpc.pb.go, interop/grpc_testing/test_grpc.pb.go, profiling/proto/service_grpc.pb.go
This PR to fix Bug #7233 , copy proto comment to pb.go file
I am very interested in this project. If there are any problems with the code I mentioned, please point it out and I will modify it immediately and submit it again. Thanks!
This PR adds an internal only (exported, but can only set through internal/) LateApplyDialOption type. This will be used in CSM Observability.
=> protoc-gen-go-grpc: copy service comment to interfaces

balancer/grpclb/grpclb_config.go, balancer/pickfirst/pickfirst.go, balancer/rls/balancer_test.go, balancer/rls/internal/test/e2e/rls_child_policy.go, clientconn.go, internal/balancergroup/balancergroup_test.go, service_config.go, test/balancer_switching_test.go, test/balancer_test.go, test/resolver_update_test.go, xds/internal/balancer/clustermanager/clustermanager_test.go, xds/internal/balancer/clustermanager/e2e_test/clustermanager_test.go, xds/internal/xdsclient/xdslbregistry/converter/converter.go
Fixes https://github.com/grpc/grpc-go/issues/7138.
This PR moves the Pick First Balancer to be in it's own package.
=>  grpc: Move Pick First Balancer to separate package

security/advancedtls/advancedtls.go, security/advancedtls/advancedtls_test.go
This request is to address the issue opened https://github.com/grpc/grpc-go/issues/7176
Basically this patch will set the verifiedChains correctly when advancedtls package is used with buildVerifyFunc() and applications need to access TLSInfo.State.VerifiedChains in their logic.
=> advancedtls: populate verified chains when using custom buildVerifyFunc

stats/opentelemetry/client_metrics.go, stats/opentelemetry/opentelemetry.go, stats/opentelemetry/server_metrics.go
This PR adds the CSM Observability logic for the client side of the OpenTelemetry component.
=> stats/opentelemetry: CSM Observability client side component changes

.github/workflows/testing.yml, README.md
Fixes #7249
We should leave this PR open for at least a few days to solicit feedback on the change.
RELEASE NOTES:
* ALL: Change support policy to only cover the latest two releases of Go.  See #7249 for more information.
=> *: end support for Go v1.20

security/advancedtls/advancedtls_test.go
Instead of 3DES, something which should basically never be used in production. Go is removing default support for 3DES is Go 1.24, requiring new modules to opt into support for this cipher.
This fixes an internal Google test failure, see b/343028077.
=> advancedtls: use realistic ciphersuite in test

security/advancedtls/advancedtls.go, security/advancedtls/advancedtls_test.go
Plumb the ciphersuites through the advanced TLS stack's options struct down to the tls.Config. This is only relevant for TLS < 1.3.
This was a recent request from #5667.
=> advancedtls: add CipherSuites to Options

stats/opentelemetry/client_metrics.go, stats/opentelemetry/opentelemetry.go, stats/opentelemetry/server_metrics.go
=> stats/opentelemetry: CSM Observability server side component changes

stats/opentelemetry/csm/observability.go, stats/opentelemetry/csm/pluginoption.go, stats/opentelemetry/internal/pluginoption.go, stats/opentelemetry/opentelemetry.go
=> stats/opentelemetry: Add CSM Observability API

stats/opentelemetry/client_metrics.go, stats/opentelemetry/opentelemetry.go, stats/opentelemetry/server_metrics.go, test/xds/xds_telemetry_labels_test.go, xds/internal/xdsclient/xdsresource/unmarshal_cds.go, xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
This PR fixes various bugs I found while interop testing CSM Observability.
1. "service_namespace" -> "service_namespace_name
2. OpenTelemetry component default metrics were not working properly
3. Have a version as a separate call
=> stats: Various CSM Observability bug fixes

xds/internal/balancer/ringhash/ring.go, xds/internal/balancer/ringhash/ring_test.go, xds/internal/balancer/ringhash/ringhash_test.go
RELEASE NOTES:
* ringhash: fix normalizeWeights in the event of just a weight update
=> ringhash: fix normalizeWeights

credentials/tls/certprovider/store.go
`wrappedProvider` add refcounter to `certprovider.Provider`, but there no guards to prevent multiple `Close()` call after single `Build()` call.
The situation is complicated by:
- the error does not appear where there was a double closure;
- before the rotation of certificates, the problem may not manifest itself (that is, the effect is greatly delayed in time);
- `certprovider.Provider` implementation don't panic/error on multiple `Close()` calls.
Fix errors like:
```
[core][Channel #39 SubChannel #941] grpc: addrConn.createTransport failed to connect to ...
Err: connection error: desc = "transport: authentication handshake failed:
xds: fetching trusted roots from CertificateProvider failed: provider instance is closed"
```
RELEASE NOTES:
- Fix `xds: fetching trusted roots from …
=> Fix close in use certificate providers after double `Close()` method call on wrapper object

Documentation/grpc-metadata.md, examples/features/metadata_interceptor/client/main.go, examples/features/metadata_interceptor/server/main.go
Fixes: #7215. It was opened while addressing the question #7125 in order to make it more clear for sending metadata from server to client. The [sending metadata documentation section](https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md#sending-metadata-1) specifies it clearly in grpc-metadata.md to use `grpc.SetTrailer`
However, we should make it more explicit to use `FromIncomingContext` on server as original issue was using `OutgoingContext` in server interceptor. Moreover, we should replace `SendHeader` to `SetHeader` in documentation as `SendHeader` is used to send the headers immediately to the client where as `SetHeader` is used to set headers that will be sent with the gRPC response, which is a more common use case.
=> documentation: on server, use FromIncomingContext  for retrieving context and `SetHeader`, `SetTrailer` to send metadata to client

internal/resolver/dns/dns_resolver.go, internal/resolver/dns/dns_resolver_test.go, internal/resolver/dns/internal/internal.go
Fixes #7186 with a test
RELEASE NOTES:
- dns: fix bug that was causing constant 30s backoff between every resolution request
=> dns: fix constant 30s backoff for re-resolution

scripts/vet.sh
We pass `--quiet` to git grep in places where we re-grep the output, which never yields any result because `--quiet` suppresses all output from stdout, even when -l is passed.
Remove `--quiet` from all grep in vet.
=> vet: remove --quiet from git grep when output is expected

security/advancedtls/advancedtls.go, security/advancedtls/advancedtls_test.go, security/advancedtls/crl.go, security/advancedtls/crl_test.go, security/advancedtls/examples/credential_reloading_from_files/client/main.go, security/advancedtls/examples/credential_reloading_from_files/server/main.go, security/advancedtls/examples/go.sum, security/advancedtls/go.mod, security/advancedtls/go.sum
This PR removes the following deprecated APIs in preparation for a 1.0 release of advancedTLS:
The first list were simply renamed
```
RootCertificateOptions.RootCACerts
GetRootCAsParams
GetRootCAsResults
ClientOptions
ServerOptions
Options.MinVersion
Options.MaxVersion
RevocationConfig
Options.RevocationConfig
AllowUndetermined
CustomVerificationFunc
Options.VType
Options.VerifyPeer
```
The second list are fully deprecated features in the CRL stack - use CRL providers instead. For reading a directory, the `FileWatcherCRLProvider` should be a relatively simple replacement.
```
Cache
RevocationOptions.RootDir
RevocationOptions.Cache
```
=> [advancedTLS] Removed deprecated APIs in advancedTLS

stats/opentelemetry/client_metrics.go, stats/opentelemetry/csm/observability_test.go, stats/opentelemetry/e2e_test.go, stats/opentelemetry/example_test.go, stats/opentelemetry/internal/testingutils/testingutils.go, stats/opentelemetry/internal/testutils/testutils.go, stats/opentelemetry/opentelemetry.go
This PR adds the e2e testing for CSM Observability. It refactors common logic shared with OpenTelemetry e2e tests into internal/testingutils.
Alongside this, this PR deletes the Target Attribute filter and adds a unit test for the method attribute filter. The target attribute filter used to be part of the OTel API, but was deleted as it was realized it was too much complexity for a use case we don't even know if users want: https://github.com/grpc/proposal/pull/431. The method attribute filter I simply forgot to unit test.
RELEASE NOTES:
* stats/opentelemetry/csm: Add CSM Observability.
=> stats/opentelemetry: Add e2e testing for CSM Observability

stats/opentelemetry/client_metrics.go, stats/opentelemetry/csm/observability_test.go, stats/opentelemetry/e2e_test.go, stats/opentelemetry/example_test.go, stats/opentelemetry/internal/testutils/testutils.go, stats/opentelemetry/opentelemetry.go
Cherry pick of #7279.
RELEASE NOTES:
* stats/opentelemetry/csm: Add CSM Observability.
=> stats/opentelemetry: Add e2e testing for CSM Observability (#7279)

credentials/alts/internal/handshaker/service/service.go, credentials/alts/internal/handshaker/service/service_test.go
fix: second call in the defer isn't executing, which prevents the hsDialer restore and hence it was never getting updated. This PR fixes the ```TestDial```.
=> credentials/alts: fix defer in TestDial

.github/workflows/testing.yml
Fixes: https://github.com/grpc/grpc-go/issues/7287
Also, checkout of the codebase needs to happen before setup-go so that the action can find the dep refs
=> github: add cache-dependency-path to setup-go

internal/transport/controlbuf.go, internal/transport/http2_server.go, internal/transport/transport_test.go
This PR makes a few minor cleanups to the `controlBuffer` code with the aim of making it more readable.
- Rename `ch` to `wakeupCh`
- This channel is used to wake up readers blocked waiting for something to read out of the control buffer, and `ch` simply isn't descriptive enough, since the scope of this field is reasonable large.
- Got rid of the `err` field with a `closed` boolean
- The only time when the control buffer returns error is when it is closed and the error value returned in this case is always `ErrConnClosing`. Using a `closed` boolean and explicitly returning `ErrConnClosing` makes this explicit, instead of making the reader wonder what possible error values could be returned. 	
- Changed the type of `trfChan` from `atomic.Value` to `atomic.Pointer`
- The …
=> internal/transport: minor cleanup of controlBuffer code

.github/workflows/testing.yml
Fixes broken GH Action runs: https://github.com/grpc/grpc-go/actions/runs/9605093608/job/26492012175?pr=7326
=> github: use latest release of qemu emulator

examples/features/retry/client/main.go
This issue #7275 talks about the example where the service config is being passed to the NewClient, but ideally the retry config should be accessed via the name resolver instead of defining it from client side. This PR adds the recommended approach.
=> examples/features/retry: Improve docstring

xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
Fixes golint error in `xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go`.
=> golint fix: context.Context should be the first parameter of a function

clientconn.go
This PR adds the exported PickFirstBalancerName symbol to not break users. This will need to be backported onto the 1.65 release branch.
=> grpc: Readd pick first name

internal/grpclog/prefixLogger.go, internal/xds/bootstrap/bootstrap.go, xds/internal/balancer/priority/balancer_priority.go, xds/internal/balancer/ringhash/ring.go, xds/internal/xdsclient/authority.go, xds/internal/xdsclient/transport/transport.go
Fixes: https://github.com/grpc/grpc-go/issues/7154
=> grpclog: remove Debugf method to avoid unnecessary evaluation

MAINTAINERS.md
[vote] Added Arvind, Arjan, Abhishek, Purnesh, Gregory Cooke, Andrey Ermolov, Zach Reyes into grpc-go active maintainers list.
Removed @cesarghali, @menghanl, @srini100 from active maintainers list and moved them to emeritus. Updated GitHub handle of @jeanbza . Removed org for emeritus list.
Please comment as "Agree" if you agree to the change, if not please comment as "Disagree". Your comment will be counted as a vote.
The PR needs to stay open for 14 days, I.e. till 14th June 2024 as per governance guidelines
=> MAINTAINERS.md: add new members and move ex-members to emeritus

Documentation/rpc-errors.md
The previously linked example was called errors, but got renamed after the addition of the error_handling example. (see #6293)
=> doc: fix link to error_details example

metadata/metadata.go, metadata/metadata_test.go
Please see the following kubernetes/etcd test scenario failure:
https://github.com/kubernetes/kubernetes/issues/125688
and notes from @serathius here on why this is important for etcd watches to work:
https://github.com/grpc/grpc-go/pull/7137#issuecomment-2192423620
RELEASE NOTES:
- metadata/metadata: ensure the String interface for pretty printing MD is deterministic
=> metadata: make Stringer implementation consistent

internal/stubserver/stubserver.go, xds/internal/balancer/clusterimpl/tests/balancer_test.go, xds/internal/xdsclient/transport/loadreport.go
This PR addressed the first task for https://github.com/grpc/grpc-go/issues/7339, adding a unit test that fails. The test presently asserts that the incorrect region received the load until the bug has been fixed:
The test asserts the following after sending 1 rpc:
1. Server 1 received the rpc
1. region-2 receives the load (wrong, but represents the current behaviour)
Then we stop server 1, send another rpc and assert the following:
1. Server 2 received the rpc
1. region-2 receives the load
Issue: https://github.com/grpc/grpc-go/issues/7339
=> xds: Add a test for incorrect load reporting when using pickfirst with servers in multiple localities

metadata/metadata.go, metadata/metadata_test.go
=> metadata: remove String method

metadata/metadata.go
ValueFromIncomingContext is an API available in metadata package which can be used to fetch single key from grpc metadata with lower memory footprint and cpu time. This PR stabilises the API after which this can be used safely
Fixes: https://github.com/grpc/grpc-go/issues/7298
RELEASE NOTES:
* metadata: stabilize ValueFromIncomingContext
=> metadata: stabilize ValueFromIncomingContext

Documentation/proxy.md
=> documentation: Update proxy docs to point to `WithContextDialer`

cmd/protoc-gen-go-grpc/main.go
relnotes for cmd/protoc-gen-go-grpc:
* Generated code for services will produce streaming method definitions using one of six different generic types (e.g. `BidiStreamingServer` or `ClientStreamingClient`) instead of producing complete interfaces and implementations for the streaming methods.  This can be disabled by setting `use_generic_streams_experimental=false`.  Please file a bug if you encounter any issues with this behavior.  This will become the default behavior in an upcoming release.
=> cmd/protoc-gen-go-grpc: default use_generic_streams_experimental to true

examples/features/opentelemetry/README.md, examples/features/opentelemetry/client/main.go, examples/features/opentelemetry/server/main.go
This PR adds an OpenTelemetry instrumentation example.
The example is not tested (I have a commit that does have the test, but deleted it, so the diff can be seen). This is due to our examples test expecting the client to exit, which in this case the client cannot exit for the sake of the example, as it is exporting Prometheus metrics on a port. Let me know if you would prefer changing our examples test. Note that a CSM Observability example with exact same behavior expect configure OpenTelemetry through CSM Package will be coming right after this.
=> examples: Add OpenTelemetry example

test/channelz_test.go, test/rawConnWrapper.go
Remove the call to `WriteRawFrame` in order to remove that method from the new Framer API.
This particular test was calling `WriteRawFrame` to write a Data Frame, which could be replaced by `WriteData` method provided by the x/net/http2 framer.
=> test/channelz: change channelz_test to use write data

clientconn.go
This change ensures that caller of `resetTransport()` keep holding the mutex instead of releasing it and having `resetTransport()` re-acquire it. This ensures that no concurrent requests are able to start once caller of `resetTransport` does some validation and calls `resetTransport`.
See https://github.com/grpc/grpc-go/issues/7365#issuecomment-2208258873 for more details.
Verified that Test/AuthorityRevive no longer flakes for 100000 attempts with the change.
Fixes: https://github.com/grpc/grpc-go/issues/7365
RELEASE NOTES:
- client: fix race that could lead to orphaned connections and associated resources.
=> grpc: hold ac.mu while calling resetTransport to prevent concurrent connection attempts

balancer/balancer.go, balancer_wrapper.go, clientconn.go, internal/internal.go, internal/testutils/balancer.go, xds/internal/balancer/clusterimpl/balancer_test.go, xds/internal/balancer/clusterimpl/clusterimpl.go, xds/internal/balancer/clusterimpl/tests/balancer_test.go, xds/internal/balancer/outlierdetection/balancer_test.go, xds/internal/internal.go
* Add `SubConnState.connectedAddress` field.
* Add `internal.GetConnectedAddress` and `internal.SetConnectedAddress` accessor function `var`s to get and set `SubConnState.connectedAddress`.
* Set the connected address in `acBalancerWrapper.updateState` when connectivity state is `Ready`.
* Read the connected address in the subconn `StateListener` and call `updateLocalityID()` based on that address's locality.
* Modify `addrConn` to store the full `resolver.Address` rather than one with `BalancerAttributes` removed.
* Modify a test to check for the new correct behavior.
Fixes #7339
RELEASE NOTES:
- TBD
=> xds: use locality from the connected address for load reporting

internal/testutils/xds/e2e/bootstrap.go, internal/xds/bootstrap/bootstrap.go, internal/xds/bootstrap/bootstrap_test.go, stats/opentelemetry/csm/pluginoption.go, test/xds/xds_client_certificate_providers_test.go, test/xds/xds_client_federation_test.go, test/xds/xds_client_ignore_resource_deletion_test.go, test/xds/xds_server_certificate_providers_test.go, xds/googledirectpath/googlec2p.go, xds/googledirectpath/googlec2p_test.go, xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go, xds/internal/resolver/xds_resolver_test.go, xds/internal/xdsclient/authority_test.go, xds/internal/xdsclient/client_new.go, xds/internal/xdsclient/client_refcounted.go, xds/internal/xdsclient/tests/authority_test.go, xds/internal/xdsclient/tests/cds_watchers_test.go, xds/internal/xdsclient/tests/dump_test.go, xds/internal/xdsclient/tests/eds_watchers_test.go, xds/internal/xdsclient/tests/federation_watchers_test.go, xds/internal/xdsclient/tests/lds_watchers_test.go, xds/internal/xdsclient/tests/misc_watchers_test.go, xds/internal/xdsclient/tests/rds_watchers_test.go, xds/server_test.go
This PR makes fallback bootstrap configuration to be a per-process configuration. This means that it applies to all xDS clients created by the process when the bootstrap environment variables are unset. This switches us to the model used in C-core.
- `internal/xds/bootstrap`
- Added a package global variable to store the fallback bootstrap configuration. 
- Added methods to set and get fallback bootstrap configuration.
- Replaced `NewConfig` with `GetConfiguration`. The latter retrieves bootstrap configuration from the ordered list of sources.
- Added `NewConfigForTesting` to create bootstrap configuration for testing purposes.
- In the `ConfigOptionsForTesting` struct, replaced the `NodeID` field with a `Node` field that supports node information specified as JSON. …
=> xds: make fallback bootstrap configuration per-process

balancer_wrapper.go, internal/grpcsync/callback_serializer.go, internal/grpcsync/callback_serializer_test.go, internal/grpcsync/pubsub.go, resolver_wrapper.go, xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/cdsbalancer/cluster_watcher.go, xds/internal/balancer/clusterresolver/resource_resolver.go, xds/internal/resolver/serviceconfig.go, xds/internal/resolver/watch_service.go, xds/internal/xdsclient/authority.go, xds/internal/xdsclient/clientimpl_watchers.go
The earlier API to add callbacks to the serializer, `Schedule`, was returning a `bool` to indicate whether or not the callback was added to the serializer. This had the following problems:
- No way to mandate that callers actually look at the return value
- Downstream errors because of the failure to schedule a callback (and the failure to look at the return value) can be very hard to debug
- Very *few* callers need to take specific action when the call to `Schedule` fails, while for most of the others, it is totally OK for the call to `Schedule` to fail.
This PR splits the API into two:
- `MaybeSchedule`: A best effort API that fails silently if the serializer is closed
- `ScheduleOr`: An API which runs an `onFailure` func if the callback cannot be scheduled
=> internal/grpcsync: support two ways to schedule a callback with the serializer

xds/internal/balancer/priority/balancer.go
Release the mutex that is locked a couple of lines above.
https://github.com/grpc/grpc-go/blob/d27ddb5eb5940c949f88bc2cb21eed9254f8be75/xds/internal/balancer/priority/balancer.go#L271-L274
This could subsequent calls to `UpdateClientConnState` to get stuck.
=> xds/balancer/priority: Unlock mutex before returning

scripts/vet.sh
This came up during the weekly import and was caught by the linter, and blocked the import.
=> vet: remove trailing whitespace

scripts/vet.sh
vet.sh is currently calling `grep -ev expr`. This is being interpreted as "grep pattern 'v' in file 'expr'", instead of the intended "invert grep for pattern 'expr' in standard input". As a result:
- Most of the time we see a line as follows on standard output:
```
+ noret_grep '(SA4000)' /tmp/tmp.xKUnikWsnw
+ grep '(SA4000)' /tmp/tmp.xKUnikWsnw
+ not grep -ev 'crl.go:\d*:\d*: identical expressions on the left and right side of the '\''||'\'' operator (SA4000)'
+ grep -ev 'crl.go:\d*:\d*: identical expressions on the left and right side of the '\''||'\'' operator (SA4000)'
+ [[ 1 == 1 ]]
grep: crl.go:\d*:\d*: identical expressions on the left and right side of the '||' operator (SA4000): No such file or directory
```
and the process continues without error, but doesn't do what we want it …
=> vet: fix option order when invoking grep

scripts/install-protoc.sh, scripts/regenerate.sh
Fixes #7400 
@dfawley I went with something that's more along the lines of option no.3 in the issue.  Now the deps are installed in a 
"well-known" directory which is `/tmp/grpc-go-tools`.  This will ensure not requiring to re-download all deps when running regenerate.
Changes: 
install-protoc.sh
1. Now requires an INSTALL_PATH to be specified
- This is a behavior change.  Previously INSTALL_PATH was optional and would put it in your GOBIN/GOPATH.  We dont want to be polluting the users GO dir with non-golang binaries.
2. Now checks if `protoc` in the required version is present in INSTALL_PATH and not $PATH
regenerate.sh
1. Installs everything to `/tmp/grpc-go-tools` instead of mktmp
2. Only download deps if not present
3. Other shell linter changes
cc: @aranjans 
=> scripts: regenerate pbs with caching deps to a fixed tmp folder

experimental/stats/metricregistry.go, internal/internal.go, stats/opentelemetry/client_metrics.go, stats/opentelemetry/csm/observability_test.go, stats/opentelemetry/e2e_test.go, stats/opentelemetry/example_test.go, stats/opentelemetry/metricsregistry_test.go, stats/opentelemetry/opentelemetry.go, stats/opentelemetry/server_metrics.go
This PR adds the OpenTelemetry usage of the metrics registry. It creates OpenTelemetry instruments and now implements the MetricsRecorder interface to record on those instruments.
=> stats/opentelemetry: Add usage of metrics registry

test/xds/xds_server_certificate_providers_test.go
In the logs of failing runs for `TestServerSideXDS_WithValidAndInvalidSecurityConfiguration`, we see that the resource snapshot update request is sent to the xds management server before the xds client is able to connect to it. Every time a gRPC server receives the updated snapshot resource from the xds server, it sends a NACK as the configuration is invalid. When the server receives more than one NACK, it gets stuck while writing to a buffered channel here:
https://github.com/grpc/grpc-go/blob/d27ddb5eb5940c949f88bc2cb21eed9254f8be75/test/xds/xds_server_certificate_providers_test.go#L249
This results in the gRPC server timing out while getting the new configuration.
This change ensures that the server writes to the buffered channel at most once and doesn't get stuck.
Example failure: …
=> xds: Fix flaky test Test/ServerSideXDS_WithValidAndInvalidSecurityConfiguration

Documentation/anti-patterns.md
The previous sentence was a bit confusing since `State` does not exist. I think it was a typo for `GetState` or `Connect`.
=> docs: fix and improve anti-patterns.md

balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go, channelz/grpc_channelz_v1/channelz_grpc.pb.go, cmd/protoc-gen-go-grpc/README.md, cmd/protoc-gen-go-grpc/go.mod, cmd/protoc-gen-go-grpc/go.sum, cmd/protoc-gen-go-grpc/grpc.go, cmd/protoc-gen-go-grpc/unimpl_test.go, credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go, examples/features/proto/echo/echo_grpc.pb.go, examples/helloworld/helloworld/helloworld_grpc.pb.go, examples/route_guide/routeguide/route_guide_grpc.pb.go, health/grpc_health_v1/health_grpc.pb.go, internal/proto/grpc_lookup_v1/rls_grpc.pb.go, interop/grpc_testing/benchmark_service_grpc.pb.go, interop/grpc_testing/report_qps_scenario_service_grpc.pb.go, interop/grpc_testing/test_grpc.pb.go, interop/grpc_testing/worker_service_grpc.pb.go, interop/stress/grpc_testing/metrics_grpc.pb.go, profiling/proto/service_grpc.pb.go, reflection/grpc_reflection_v1/reflection_grpc.pb.go, reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go, reflection/grpc_testing/test_grpc.pb.go
=> cmd/protoc-gen-go-grpc: test the embedded struct at registration time for proper usage

stats/opentelemetry/client_metrics.go, stats/opentelemetry/csm/observability.go, stats/opentelemetry/csm/observability_test.go, test/xds/xds_telemetry_labels_test.go, xds/internal/balancer/clusterimpl/picker.go
This PR adds the setting of the optional locality label in the cluster_impl picker for per call metrics. It also sets the default of "" for this label in OpenTelemetry.
=> stats: Add optional locality label in cluster_impl picker

scripts/vet-proto.sh, scripts/vet.sh
=> scripts/vet: remove trailing spaces

balancer/weightedroundrobin/balancer.go, balancer/weightedroundrobin/scheduler.go, balancer/weightedtarget/weightedtarget.go
This PR adds emissions of weighted round robin metrics defined in A78.
=> balancer/weightedroundrobin: Add emissions of metrics through metrics registry

cmd/protoc-gen-go-grpc/go.mod, cmd/protoc-gen-go-grpc/go.sum, cmd/protoc-gen-go-grpc/unimpl_test.go
=> cmd/protoc-gen-go-grpc: remove replace and skip test that requires it for now

examples/features/retry/README.md, examples/features/retry/client/main.go, rpc_util.go
This setting is irrelevant, so remove it to avoid any confusion.
Fixes #7440 
=> examples/retry: remove waitForReady from service config

internal/transport/proxy.go, internal/transport/proxy_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7327
The buffer used to read the http connect response could contain extra bytes from the target server, so we can't discard it. However, in many cases where the server waits for the client to send the first message (e.g. when TLS is being used), the buffer will be empty, so we can avoid the overhead of reading through this buffer.
This PR also adds a unit test to ensure the buffer is not discarded when it has unread data.
RELEASE NOTES:
* Double buffering is avoided when using an http connect proxy and the target server waits for client to send the first message.
=> transport: Discard the buffer when empty after http connect handshake

experimental/stats/metricregistry.go
The PR fixes a linter in Google 3.
=> experimental/stats/metricregistry: Add comments on enum consts for Metrics Type

resolver_wrapper.go
Note: this is a degradation introduced in this PR: https://github.com/grpc/grpc-go/pull/5192
Which [used to wrap calls](https://github.com/grpc/grpc-go/commit/a73725f42db97964eb538a5cf4d302f760357dbe#diff-f328282147b29224bf45cfe72630d84fa5d9b43b3b976ebb82077b3a322daa53L101) to `addChannelzTraceEvent` in a `if channelz.IsOn() {`
Large and frequent calls to this method in UpdateState can cause an extremely high usage of CPU time and Memory due to underlying json.Marshal calls that are not used or needed if were not Info level logging as it is.
Alternative approach to: https://github.com/grpc/grpc-go/pull/7436
=> resolver_wrapper: add early return in addChannelzTraceEvent

internal/transport/grpchttp2/errors.go, internal/transport/grpchttp2/framer.go
Add documentation to all exported methods and values.
=> transport/grpchttp2: add doc to methods and values

balancer/leastrequest/leastrequest.go
=> balancer/leastrequest: Add verbosity check around build log

mem/buffer_pool.go
=> mem: fix comment typo

internal/balancergroup/balancergroup.go
The balancergroup was initially implemented inside the priority LB policy, before being moved out to be a separate utility. Mentions of `locality` are from that day and age.
=> balancergroup: remove mentions of locality from comments

internal/transport/grpchttp2/framer.go
Revert #7477 in order to pursue a implementation with standard types
=> transport/grpchttp2: revert #7477 usage of mem package

internal/transport/http_util.go, internal/transport/http_util_test.go
fixes https://github.com/grpc/grpc-go/issues/7389
RELEASE NOTES:
- fast-fail Write() on error returned from underlying network connection
=> transport/bufWriter: fast-fail on error returned from flushKeepBuffer()

internal/envconfig/envconfig.go, internal/xds/bootstrap/bootstrap.go, internal/xds/bootstrap/bootstrap_test.go
Fixes https://github.com/grpc/grpc-go/issues/7479
=> xds: env var protection for xds fallback

internal/transport/handler_server.go
1. Panic will not actively release the lock.
2. This function is called by a goroutine, if panic occurs, the lock will be held until the entire program exits.
```
s.hdrMu.Lock()
if p := st.Proto(); p != nil && len(p.Details) > 0 {
delete(s.trailer, grpcStatusDetailsBinHeader)
stBytes, err := proto.Marshal(p)
if err != nil {
// TODO: return error instead, when callers are able to handle it.
panic(err)
}
h.Set(grpcStatusDetailsBinHeader, encodeBinHeader(stBytes))
}
```
=> internal/transport: Unlock mutex before panic

balancer/rls/balancer.go, balancer/rls/cache.go, balancer/rls/picker.go
This PR adds the implementation for RLS metrics.
RELEASE NOTES:
* balancer/rls: Add picker Pick information metrics
=> balancer/rls: Add picker metrics

balancer/weightedroundrobin/balancer.go, balancer/weightedroundrobin/balancer_test.go, balancer/weightedroundrobin/metrics_test.go, balancer/weightedroundrobin/scheduler.go, internal/stats/metrics_recorder_list_test.go, internal/testutils/stats/test_metrics_recorder.go, internal/testutils/xds/e2e/setup/setup.go, stats/opentelemetry/e2e_test.go, stats/opentelemetry/go.mod, stats/opentelemetry/go.sum, test/xds/xds_client_affinity_test.go, test/xds/xds_client_certificate_providers_test.go, test/xds/xds_client_custom_lb_test.go, test/xds/xds_client_federation_test.go, test/xds/xds_client_integration_test.go, test/xds/xds_client_outlier_detection_test.go, test/xds/xds_client_retry_test.go, test/xds/xds_rls_clusterspecifier_plugin_test.go, test/xds/xds_security_config_nack_test.go, test/xds/xds_server_certificate_providers_test.go, test/xds/xds_server_integration_test.go, test/xds/xds_server_rbac_test.go, test/xds/xds_server_serving_mode_test.go, test/xds/xds_server_test.go, test/xds/xds_telemetry_labels_test.go
This PR adds unit test assertions for Weighted Roudn Robin Metrics and an e2e test with exact OpenTelemetry metrics atoms expected.
It also fixes the "startup" case for WeightedSubConns when a WeightedSubConn has not received a load report yet. Previously, it would record an endpoint weight stale metric, but I added logic to make this case record on endpoint weight not yet usable instead.
=> balancer/weightedroundrobin: Add recording point for endpoint weight not yet usable and add metrics tests

benchmark/benchmain/main.go
Without this change, the benchmarks did not actually include executions with the new gzip compressor from the `encoding/gzip` package. This adds the option to run the suite with said new compressor and adds it to the "all" suite as well.
=> benchmark: wire in new gzip compressor

stream.go
When I was reviewing https://github.com/grpc/grpc-go/pull/7461, I made a comment to replace some lines which read as:
```golang
err = foo()
if err == nil { ... }
```
to be replaced as:
```golang
if err := foo(); err == nil { ... }
```
Little did I realize that the `err` value was being used below. Luckily this did not make it into the release, which we haven't yet cut. So, no release notes required.
This wasn't caught as a compile error, because `err` was a named return parameter. I'm not making the changes in this PR to not have `err` as a named return parameter though.
=> grpc: fix a bug introduced in #7461

benchmark/latency/latency.go
When using "local" mode, the latency package adds some significant allocations into our benchmarks and doesn't even attempt to do anything.
=> latency: don't wrap when all the latencies are zero

server.go, stream.go
=> .*: fix comments

balancer/rls/balancer.go, balancer/rls/cache.go, balancer/rls/cache_test.go, internal/testutils/stats/test_metrics_recorder.go
After some discussion, decided to just emit gauge metrics inline using synchronous gauges with cache mutex held. OpenTelemetry just copies this data over to another store for exporters to use, so this shouldn't introduce a performance hit/lock contention, especially since the accesses cache creates lock contention on the operations even before metrics.
As suggested in https://github.com/grpc/grpc-go/pull/7484#discussion_r1707624645.
RELEASE NOTES:
* balancer/rls: Add cache metrics
=> balancer/rls: Add cache metrics

examples/features/customloadbalancer/client/main.go, internal/transport/transport_test.go, test/bufconn/bufconn_test.go, test/tools/go.mod, test/tools/go.sum
=> test/tools: update staticcheck version to latest

balancer/rls/cache.go
This PR fixes the RLS Cache metrics. I accidentally deleted the wrong recording point in my final commit on #7495.
=> balancer/rls: Fix RLS Cache metrics

grpclog/component.go, grpclog/grpclog.go, grpclog/internal/grpclog.go, grpclog/internal/logger.go, grpclog/internal/loggerv2.go, grpclog/internal/loggerv2_test.go, grpclog/logger.go, grpclog/loggerv2.go, internal/grpclog/prefix_logger.go, internal/grpctest/tlogger_test.go, scripts/vet.sh
Idea behind the refactor:
- Public API for logging should be provided by the `grpclog` package
- Implementation should mostly reside in `grpclog/internal` package
- Any functionality that is not exposed externally, but is available to grpc packages should be in `internal/grpclog`
- Package `grpclog` will take a dependency on `grpclog/internal`
- Package `internal/grpclog` will take a dependency on `grpclog`
Also introduces a few methods for depth logging to the external `grpclog` package.
=> grpclog: refactor to move implementation to grpclog/internal

internal/transport/transport.go
Change `transport.Stream` to reference the generic interface `ClientTransport` instead of the specific `*http2Client`.
=> transport: change `*http2Client` to interface `ClientTransport`

xds/csds/csds_e2e_test.go
This PR unskips a test which was previously failing on `arm64` because the xDS client was being overwhelmed by the go-control-plane management server, because the latter was continuously resending NACKed resources. This PR uses the ADS stream level flow control mechanism from the resource watchers used in the test, and thereby will be able to throttle receipt of messages from the management server.
Fixes https://github.com/grpc/grpc-go/issues/7383
=> csds: unskip e2e test

internal/transport/http2_client.go, internal/transport/transport_test.go
fixes [#7314](https://github.com/grpc/grpc-go/issues/7314)
In gRPC 1.64, we released a [feature](https://github.com/grpc/grpc-go/pull/7015) "Send GOAWAY to server on Client Transport Shutdown", post which in case of network hang when we are not able to write GOAWAY frame from client, closing connections will take a very long time.
This PR fixes this issue by having a timeout for loopyWriter to write GOAWAY so that http2Client.Close() doesn't wait for too long.
- transport/http2_client: fix waiting on http2Client.Close() in case of network hang for writing GOAWAY.
=> transport: add timeout for writing GOAWAY on http2Client.Close()

internal/xds/rbac/rbac_engine.go
This could actually lead to a panic if the auth type reports "tls" but the `AuthInfo` is not a `credentials.TLSInfo`.  There is no evidence this is happening and has been this way for a long time.
=> rbac: fix usage of AuthInfo

balancer/rls/internal/adaptive/lookback.go, benchmark/stats/stats.go, credentials/alts/internal/conn/record.go, internal/channelz/channelmap.go, internal/transport/controlbuf.go, internal/transport/http2_client.go, internal/transport/http2_server.go, test/end2end_test.go, xds/internal/balancer/outlierdetection/balancer.go
With the upgrade to Go 1.21 (#7282), grpc-go can use the new builtin [min](https://pkg.go.dev/builtin#min) and [max](https://pkg.go.dev/builtin#max) functions. This commit removes existing functions and uses the built-ins instead.
=> Use builtin min and max functions

internal/transport/http2_client.go, internal/transport/transport_test.go
fixes https://github.com/grpc/grpc-go/issues/7314
Problem
In gRPC 1.64, we released a https://github.com/grpc/grpc-go/pull/7015 "Send GOAWAY to server on Client Transport Shutdown", post which in case of network hang when we are not able to write GOAWAY frame from client, closing connections will take a very long time.
What does this PR fix
This PR fixes this issue by having a timeout for loopyWriter to write GOAWAY so that http2Client.Close() doesn't wait for too long.
RELEASE NOTES:
- transport/http2_client: fix waiting on http2Client.Close() in case of network hang for writing GOAWAY.
=> cherry-pick: transport: add timeout for writing GOAWAY on http2Client.Close() #7371

dialoptions.go, keepalive/keepalive.go
Add to the godoc the behavior that the client doubles the keepalive ping interval when GOAWAY is received due to too-many-pings.
And link to the design doc.
=> doc: update keepalive ClientParameters doc about doubling the interval upon GOAWAY

internal/testutils/xds/e2e/bootstrap.go, internal/xds/bootstrap/bootstrap.go, test/xds/xds_client_certificate_providers_test.go, test/xds/xds_client_federation_test.go, test/xds/xds_client_ignore_resource_deletion_test.go, test/xds/xds_server_certificate_providers_test.go, xds/googledirectpath/googlec2p_test.go, xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go, xds/internal/resolver/xds_resolver_test.go, xds/internal/xdsclient/tests/authority_test.go, xds/internal/xdsclient/tests/cds_watchers_test.go, xds/internal/xdsclient/tests/dump_test.go, xds/internal/xdsclient/tests/eds_watchers_test.go, xds/internal/xdsclient/tests/federation_watchers_test.go, xds/internal/xdsclient/tests/lds_watchers_test.go, xds/internal/xdsclient/tests/misc_watchers_test.go, xds/internal/xdsclient/tests/rds_watchers_test.go, xds/server_test.go
=> bootstrap: add `String` method to ServerConfigs type

balancer_wrapper.go, clientconn.go, producer_ext_test.go, resolver_balancer_ext_test.go
This should fix the flaky WRR test which is failing due to receiving an ORCA load report before the subconn reports as READY.
=> balancer: disallow producer streams until SubConn has reported READY

.github/workflows/testing.yml
=> testing: Remove trailing whitespace in testing.yml

xds/internal/xdsclient/loadreport_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7241
The test is sometimes getting a second load report before the client closes the stream. The test is setting the load report interval to 50 ms here: https://github.com/grpc/grpc-go/blob/cfd14baa8264cbeebf6308a7b68333c8c2fc6e86/xds/internal/xdsclient/loadreport_test.go#L106-L109
In the final assertion of the test, the test is checking that the very next request present in the fake server's request channel is the client cancellation: https://github.com/grpc/grpc-go/blob/cfd14baa8264cbeebf6308a7b68333c8c2fc6e86/xds/internal/xdsclient/loadreport_test.go#L136-L138
When the the test takes more than 50 ms b/w sending the first LRS response with the load report interval and this final assertion, another load report can be sent by the client here: …
=> xds/xdsclient: Fix flaky test TestLRSClient

internal/googlecloud/googlecloud.go, internal/xds/bootstrap/template.go, resolver_balancer_ext_test.go, stats/opencensus/opencensus.go, stats/opencensus/trace.go, xds/server_test.go
`string.ReplaceAll()` is equivalent to  `string.Replace()` with a limit of -1
=> .*: Use `strings.ReplaceAll(.....)`

balancer/weightedroundrobin/balancer.go, benchmark/latency/latency.go, test/config_selector_test.go
Prefer calling Equal() method of time.Time over direct comparision.
=> balancer/wrr: prefer calling Equal() method of time.Time

picker_wrapper_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7521
The tests call picker_wrapper.pick() in 5 go routines. The go routines are blocked on either the context getting cancelled or the picker being updated. https://github.com/grpc/grpc-go/blob/cfd14baa8264cbeebf6308a7b68333c8c2fc6e86/picker_wrapper.go#L120-L134
The context is cancelled through a deferred statement when the test function exits. The test function updates the picker in the last line before exiting: https://github.com/grpc/grpc-go/blob/cfd14baa8264cbeebf6308a7b68333c8c2fc6e86/picker_wrapper_test.go#L162
When the picker go routines see the context getting cancelled before the picker update, they log an error causing the test to fail.
Add a `time.Sleep(100 * time.Milliseconds)` just before waiting on the picker update / context …
=> grpc: Fix flaky picker_wrapper tests

xds/internal/balancer/clusterimpl/balancer_test.go, xds/internal/xdsclient/load/store.go, xds/internal/xdsclient/load/store_test.go, xds/internal/xdsclient/transport/loadreport.go, xds/internal/xdsclient/transport/loadreport_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7538
This PR populates the [total issued request count](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/endpoint/v3/load_report.proto#envoy-v3-api-msg-config-endpoint-v3-clusterstats:~:text=in%20the%20locality.-,total_issued_requests,-(uint64)%20The) which is already being added by Java and c-core clients.
The `issued request` counter is incremented when a new request is started. The counter is reset when a load report is sent to the LRS server
RELEASE NOTES:
* LRS load reports contain the `total_issued_requests` field.
=> xdsclient: Populate total_issued_requests count in LRS load report

resolver/manual/manual.go, xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
The test is presently making a real DNS request for a non existing domain `bad.ip.v4.address`. This makes the test non-hermitic and could potentially be the cause of the test flaking. This change makes the test use a fake resolver to avoid making DNS requests.
Related issue: https://github.com/grpc/grpc-go/issues/7354
=> clusterresolver/e2e_test: Avoid making DNS requests

examples/go.mod, interop/xds/go.mod, security/advancedtls/examples/go.mod, security/advancedtls/go.mod, stats/opentelemetry/go.mod
Building stats/otel was broken on its own because this package depends on `grpc/experimental/stats` which is not released yet. Our tests passed because of the replace directive magic.
=> stats/otel: upgrade grpc version that contains the experimental/stats package

mem/buffer_slice.go, server.go
I was excited to see recycled buffers be released (#6619), and wanted to gauge performance before putting into production. It was surprising to see that the default codec in `v1.65.0` performed better than the new one in `v1.66.0`.
There was a missed `(mem.BufferSlice).Free()` in the server during `processUnaryRPC`, leaving the incoming request bytes hanging around while still paying the added allocations that comes with managing the buffers.
I'm not super attached to the added `BufferSlice` docs, but it would have saved me a lot of time trying to figure out what was wrong with my interaction code. It wasn't clear to me that sometimes the provided slice kept a reference to the buffer, and would be released by SDK logic.
This is far from a pure benchmark (bufconn, client, etc contributing …
=> grpc: fix regression by freeing request bufferslice after processing unary

xds/internal/balancer/clusterimpl/clusterimpl.go
Part of #7210.
`UpdateClientConnState` now handles updates in a blocking fashion. 
To simplify the code, this PR replaces the existing `run` goroutine inside `clusterimpl` lb policy and instead handles calls from gRPC and from the child policy (to update state) in a `grpcsync.CallbackSerializer`. This approach simplifies things by removing the need for synchronization using locks and other grpcsync.Event fields. 
=> xds/clusterimpl: update UpdateClientConnState to handle updates synchronously  

examples/features/csm_observability/client/main.go, examples/features/csm_observability/server/main.go, examples/features/customloadbalancer/client/main.go, examples/features/customloadbalancer/server/main.go, examples/features/opentelemetry/client/main.go, examples/features/opentelemetry/server/main.go, interop/observability/client/client.go, interop/observability/server/server.go
=> .*: fix revive package-comments lint issues

stats/opentelemetry/client_metrics.go, stats/opentelemetry/opentelemetry.go, stats/opentelemetry/server_metrics.go
First commit moves attribute construction under `if` to only construct them when they are used.
Second commit uses `WithAttributeSet()` instead of `WithAttributes()`. This avoids copying the slice, which is not necessary for this code. See https://github.com/open-telemetry/opentelemetry-go/blob/metric/v1.28.0/metric/instrument.go#L349-L368.
Also, a bit of allocations can be removed by constructing the vararg slice one time vs when calling `Record()` each time.
```go
var sink []string
func abc(vals ...string) {
sink = vals
}
func BenchmarkFuncCall(b *testing.B) {
b.ReportAllocs()
b.ResetTimer()
arg := []string{"a", "b", "c"}
for i := 0; i < b.N; i++ {
abc(arg...)
}
}
```
The above benchmark gives me these results:
```
// Pass "a", "b", "c"
BenchmarkFuncCall-10    	43171615	        27.14 …
```
=> stats/opentelemetry: Optimize slice allocations

experimental/stats/metricregistry.go, experimental/stats/metricregistry_test.go, internal/internal.go, internal/stats/metrics_recorder_list_test.go, stats/opentelemetry/metricsregistry_test.go
Addresses https://github.com/grpc/grpc-go/issues/7568
- experimental/stats: remove dependency on `testing` package
=> estats: remove dependency on testing package

credentials/credentials_test.go, credentials/xds/xds_client_test.go, credentials/xds/xds_server_test.go, internal/envconfig/envconfig.go
Related issue: https://github.com/grpc/grpc-go/issues/434
RELEASE NOTES:
* Clients and servers will reject TLS connections that don't support ALPN. This can be disabled by setting environment variable `GRPC_ENFORCE_ALPN_ENABLED` to `false` (case insensitive). Please file a bug if you encounter any issues with this behaviour. This will become the default behaviour in an upcoming release.
=> credentials/tls: default GRPC_ENFORCE_ALPN_ENABLED to true

experimental/stats/metricregistry.go, experimental/stats/metricregistry_test.go, internal/internal.go, internal/stats/metrics_recorder_list_test.go, mem/buffer_slice.go, server.go, stats/opentelemetry/metricsregistry_test.go
Cherry-pick https://github.com/grpc/grpc-go/pull/7571 and https://github.com/grpc/grpc-go/pull/7579
RELEASE NOTES:
- mem: Fix minor server-side regression when pooling large (>1KiB) incoming request buffers
- experimental/stats: Remove dependency on testing package
=> Cherry pick #7571 and #7579 to v1.66.x release branch

mem/buffer_slice.go
This interface has nothing to do with compression and there are no other references to that package in the codebase. If we remove the reference we same compiler and linker some work - no need to parse, compile, link that package just to use one interface from it (assuming no other references from the codebase).
RELEASE NOTES:
- mem: remove dependency on `compress/flate` package
=> mem: replace flate.Reader reference

CONTRIBUTING.md, Documentation/server-reflection-tutorial.md, authz/grpc_authz_end2end_test.go, authz/grpc_authz_server_interceptors_test.go, cmd/protoc-gen-go-grpc/protoc-gen-go-grpc_test.sh, examples/features/advancedtls/README.md, examples/features/advancedtls/creds/client_cert.pem, examples/features/advancedtls/creds/client_cert_revoked.pem, examples/features/advancedtls/creds/server_cert.pem, examples/features/advancedtls/creds/server_cert_revoked.pem, examples/features/debugging/README.md, examples/features/encryption/README.md, examples/features/health/README.md, examples/features/metadata_interceptor/README.md, examples/features/stats_monitoring/README.md, scripts/vet.sh, security/advancedtls/examples/credential_reloading_from_files/README.md, security/advancedtls/testdata/README.md, security/advancedtls/testdata/another_client_cert_1.pem, security/advancedtls/testdata/client_cert_1.pem, security/advancedtls/testdata/client_cert_2.pem, security/advancedtls/testdata/crl/README.md, security/advancedtls/testdata/server_cert_1.pem, security/advancedtls/testdata/server_cert_1.txt, security/advancedtls/testdata/server_cert_2.pem, security/advancedtls/testdata/server_cert_2.txt, security/advancedtls/testdata/server_cert_3.txt, security/advancedtls/testdata/server_cert_localhost_1.pem, xds/internal/test/e2e/run.sh
=> vet: add check for trailing spaces

balancer/weightedroundrobin/balancer_test.go, internal/stubserver/stubserver.go, orca/service.go
Addresses https://github.com/grpc/grpc-go/issues/7291
=> stubserver: support xds-enabled grpc server

examples/features/csm_observability/client/Dockerfile, examples/features/csm_observability/server/Dockerfile, interop/observability/Dockerfile, interop/xds/client/Dockerfile, interop/xds/server/Dockerfile, test/kokoro/xds.sh
Since the minimum supported Go version was bumped in https://github.com/grpc/grpc-go/pull/7624, the Docker build for the psm interop client and server has been failing with the following error:
```
#10 [build 4/4] RUN cd interop/xds/client && go build -tags osusergo,netgo .
#10 0.248 go: ../go.mod requires go >= 1.22.7 (running go 1.21.13; GOTOOLCHAIN=local)
#10 ERROR: process "/bin/sh -c cd interop/xds/client && go build -tags osusergo,netgo ." did not complete successfully: exit code: 1
------
> [build 4/4] RUN cd interop/xds/client && go build -tags osusergo,netgo .:
0.248 go: ../go.mod requires go >= 1.22.7 (running go 1.21.13; GOTOOLCHAIN=local)
------
```
Verified that the docker build succeeds with the change in base image version to 1.22.
```sh
docker build -f …
```
=> Deps: Bump Go version in Dockerfiles and test/kokoro/xds.sh

balancer/endpointsharding/endpointsharding.go, balancer/pickfirst/pickfirst.go, credentials/tls/certprovider/pemfile/builder.go, examples/features/advancedtls/client/main.go, examples/features/advancedtls/server/main.go, internal/balancer/gracefulswitch/config.go, internal/channelz/channel.go, internal/channelz/server.go, internal/channelz/socket.go, internal/channelz/subchannel.go, internal/channelz/trace.go, internal/idle/idle.go, internal/internal.go, internal/stats/metrics_recorder_list.go, internal/testutils/stats/test_metrics_recorder.go, internal/transport/transport.go, mem/buffers.go, rpc_util.go, scripts/revive.toml, security/advancedtls/advancedtls.go
=> .*: fix lint issues of not having comments for exported funcs and vars along with any remaining issues and enable remaining disabled rules

scripts/revive.toml
=> revive: add comment explaining reason for disabled linter rules

xds/internal/balancer/clusterimpl/balancer_test.go, xds/internal/balancer/clusterimpl/clusterimpl.go
#7210 talks about not using deprecated APIs in the `gracefulswitch.Balancer` while switching the child policy on reciept of configuration update of clusterimpl. This PR makes the required changes for the same.
RELEASE NOTES:
- clusterimpl: use `gsb.UpdateClientConnState` instead of `switchTo`, on receipt of config update
=> clusterimpl: use gsb.UpdateClientConnState instead of switchTo, on receipt of config update

internal/transport/transport.go, internal/transport/transport_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7641
The headers are being read incrementally here:
https://github.com/grpc/grpc-go/blob/8ea3460acace12cd1f2f0502784d42c21eeadf42/internal/transport/transport.go#L559-L579
We keep filling the underlying `header` slice until its full, but we do so by moving the start of the slice forward. In the following function that is called by the function above to perform reads and update the flow control window, we do `t.windowHandler(len(header))`.
https://github.com/grpc/grpc-go/blob/8ea3460acace12cd1f2f0502784d42c21eeadf42/internal/transport/transport.go#L622-L630
The code has read `n` bytes, but it says it read `len(header)` bytes. `len(header)` is the total number of bytes that remain to be read, which is not always equal the the bytes there were …
=> transport: Fix reporting of bytes read while reading headers

internal/transport/transport.go, internal/transport/transport_test.go
Addresses: https://github.com/grpc/grpc-go/issues/7641
Original PR: https://github.com/grpc/grpc-go/pull/7660
RELEASE NOTES:
* transport: Fix bug causing stream failures due miscalculation of the flow control window in both clients and servers.
=> cherry-pick #7660 to v1.67.x branch

balancer/endpointsharding/endpointsharding_test.go, balancer/rls/balancer_test.go, balancer/rls/picker_test.go, xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go, xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
Partially address: https://github.com/grpc/grpc-go/issues/7049
Update tests where only direct replacement is enough to replace grpc.Dial with grpc.NewClient in test files
=> cleanup: replace grpc.Dial with grpc.NewClient in tests

xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7354
The test is presently making a real DNS request for a non existing domain `bad.ip.v4.address`. This makes the test non-hermitic and could be the cause of the test flaking. This change makes the test use a fake resolver to avoid making real DNS requests.
A similar fix was made for TestAggregateCluster_BadDNS_GoodEDS in https://github.com/grpc/grpc-go/pull/7561 after which there were no more failures reported.
=> clusterresolver/e2e_test: Avoid making real DNS requests in TestAggregateCluster_BadEDS_BadDNS

internal/transport/transport.go, internal/transport/transport_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7641
Original PR: https://github.com/grpc/grpc-go/pull/7660
RELEASE NOTES:
* transport: Fix a bug causing stream failures due miscalculation of the flow control window in both clients and servers.
=> cherry-pick #7660 to v1.66.x branch

balancer/rls/cache_test.go, balancer/rls/picker_test.go, balancer/weightedroundrobin/balancer_test.go, balancer/weightedroundrobin/metrics_test.go, internal/stats/metrics_recorder_list_test.go, internal/testutils/stats/test_metrics_recorder.go
This PR adds picker and cache unit tests to test RLS Metrics.
=> balancer/rls: Add picker and cache unit tests for RLS Metrics

cmd/protoc-gen-go-grpc/grpc.go, cmd/protoc-gen-go-grpc/main.go, cmd/protoc-gen-go-grpc/protoc-gen-go-grpc_test.sh
Fixes task 2 : #1894 - Delete the code to generate stream interfaces for client and server.
Deletes the unused code to make stream generics default.
=> protoc-gen-go-grpc: remove `use_generic_streams_experimental` flag (defaults to true)

internal/credentials/xds/handshake_info_test.go
Addresses: https://github.com/grpc/grpc-go/issues/6568
=> internal/credentials/xds: add unit tests for `HandshakeInfo.Equal`

internal/xds/bootstrap/bootstrap.go, test/xds/xds_client_custom_dialer_test.go, xds/internal/xdsclient/transport/transport.go, xds/internal/xdsclient/transport/transport_test.go
Design:
* go/grpc-go-corp-to-prod-td-doc
* Add a custom `Dialer` method that specifies how to dial the xDS server via the credentials bundle without introducing new public APIs.
* No code change for existing users that do not need a custom Dialer for the xDS transport.
Tested:
* `./scripts/vet.sh`
* `go test -cpu 1,4 -timeout 7m ./...`
* `go test -race -cpu 1,4 -timeout 7m ./...`
* Verified end-to-end by running a test gRPC client with a xDS client that used the custom Dialer for the xDS transport to successfully communicate with the xDS server and fetch configs.
RELEASE NOTES:
* xds: add experimental feature to customize the Dialer used by the xDS transport
=> xds: add xDS transport custom Dialer support

xds/internal/server/conn_wrapper.go, xds/internal/server/listener_wrapper.go, xds/internal/server/listener_wrapper_test.go
Discovered in #7657.
My Dynamic RDS fix added a ref to the server transport in the wrapped connection: https://github.com/grpc/grpc-go/pull/6915/files#diff-dd56a1b7688625b5b70cd616b08c301d12f7f01edbd9be95c506743fd58a6155R140 to Drain correctly even right after Accepting the connection. It also added a ref to wrapped connection, which only gets cleared on the xDS Server's Serving State changing to Not Serving and filter chain updates: https://github.com/grpc/grpc-go/pull/6915/files#diff-e4706c72ae912399b7f8ee6f04cec2374ef7a7679b12358f201ddb0b45e34146R344. In the production environment/test case the connection closes but the listener continues to listen and the server continues to serve in a state that is not NOT_SERVING thus keeping a ref to the wrapped connection around. The solution is …
=> xds/server: Fix xDS Server leak

test/xds/xds_server_integration_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7599
This change ensures that the server has started listening for requests by wrapping the listener passed to `server.Serve()`
Verified that the test no longer flakes in 100000 runs on forge.
=> xds: Fix flaky test TestUnmarshalListener_WithUpdateValidatorFunc

Documentation/benchmark.md, scripts/vet.sh
- Added check for tabs in text files
- Replaced tabs with spaces in the following file :
- Documentation/benchmark.md
=> vet : add check for tabs in text files

cmd/protoc-gen-go-grpc/grpc.go, cmd/protoc-gen-go-grpc/main.go, cmd/protoc-gen-go-grpc/protoc-gen-go-grpc_test.sh
This PR reverts #7654  which attempted to:
- Remove the use_generic_streams_experimental flag.
- Make the use of generics mandatory for stream methods.
This revert is necessary because the previous changes caused compatibility issues with existing usages of client and server stream methods within internal google3.
We will revisit this change once the affected usages in google3 have been migrated.
=> Revert "protoc-gen-go-grpc: remove `use_generic_streams_experimental`  flag (defaults to true) (#7654)

internal/testutils/channel.go, test/xds/xds_client_federation_test.go, xds/internal/xdsclient/tests/cds_watchers_test.go, xds/server_test.go
=> xds: misc test cleanup (4/N)

xds/internal/xdsclient/tests/ads_stream_restart_test.go
=> xdsclient: e2e style tests for ads stream restart (5/N)

internal/transport/http2_client.go
Fixes #7606.
Couple of recent changes worth noting here:
- https://github.com/grpc/grpc-go/pull/7015 added logic to send a GOAWAY frame on client transport shutdown. Unfortunately the handler responsible for writing the GOAWAY frame was holding on to the client transport mutex when attempting to write the GOAWAY frame.
- https://github.com/grpc/grpc-go/pull/7371  introduced a timeout in the client transport shutdown handler to wait for `loopyWriter` to exit (after enqueueing the above GOAWAY frame on the `controlbuf`). This was done to ensure that the client transport shutdown can complete in the face of a hanging network connection that blocks forever when attempting to write the above GOAWAY frame
Description of the deadlock:
- During client transport shutdown, after enqueueing the …
=> transport: prevent deadlock in transport Close when GoAway write hangs

xds/internal/xdsclient/tests/ads_stream_ack_nack_test.go, xds/internal/xdsclient/tests/ads_stream_restart_test.go
=> xds: address merge conflict gotcha and missed review comment from previous PRs

internal/xds/bootstrap/bootstrap.go, xds/internal/xdsclient/transport/transport.go, xds/internal/xdsclient/transport/transport_test.go
Fixes : #7661 
Added a single `DialOptions()` method that returns a slice of all dial options for the type `ServerConfig` instead of individual methods to get all dial options.
=> xds: return all ServerConfig dial options together

internal/xds/bootstrap/bootstrap.go, xds/internal/xdsclient/transport/transport.go, xds/internal/xdsclient/transport/transport_test.go
This revert #7680 which : 
- Added a single DialOptions() method that returns a slice of all dial options for the type ServerConfig instead of individual methods to get all dial options.
- Changed the test to wait for the custom dialer to be called.
Also reverts #7710 which :
- Added `defaultTestTimeout` variable which is now unused.
Reverting this is necessary because the wait for dialer is failing in google3.
=> revert xds: return all ServerConfig dial options together

xds/internal/xdsclient/tests/ads_stream_backoff_test.go, xds/internal/xdsclient/tests/ads_stream_restart_test.go
Reasons for the flake:
- The resource names requested from the management server were written on to a channel in a non-blocking fashion. This meant that the most recently requested names were not always available.
- A goroutine leak was also happening in some cases because the test was not reading the updates delivered to the resource watcher.
The fix addresses both of the above issues. It also improves the error message when the test times out waiting for a response that matches expectation.
Fixes https://github.com/grpc/grpc-go/issues/7714
=> xdsclient: deflake TestADS_ResourcesAreRequestedAfterStreamRestart

internal/testutils/restartable_listener.go
=> testutils: add couple of log statements to the restartable listener type

balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
This PR adds a minor simplification to the `reconcileSubConnsLocked` method
- Instead of building a new map for the existing subchannels with the key being the address and the value being a boolean (which is always set to true), we can instead use the existing map.
This PR also adds a docstring to the method instead of inline comments, some of which were a little stale.
=> pickfirstleaf: minor simplification to reconcileSubConnsLocked method

stats/opentelemetry/csm/observability_test.go, stats/opentelemetry/csm/pluginoption.go, stats/opentelemetry/csm/pluginoption_test.go
This PR switches the mesh_id local label to get set from the CSM_MESH_ID environment variable, with the same logic as other labels set from the environment. It no longer comes from the bootstrap, or needs to be parsed from the node_id of the bootstrap.
RELEASE NOTES:
* stats/opentelemetry/csm: Get mesh_id local label from "CSM_MESH_ID" environment variable, rather than parsing from bootstrap file
=> stats/opentelemetry/csm: Get mesh_id local label from "CSM_MESH_ID" environment variable, rather than parsing from bootstrap file

scripts/vet.sh
grpc-go requires go version >= 1.22. This change bumps the Go version used in vet.sh to 1.22. This fixes error similar to the following:
```
Error: -: /opt/hostedtoolcache/go/1.23.2/x64/src/runtime/time.go:204:17: cannot range over 3 (untyped int constant): requires go1.22 or later (compile)
```
=> vet: Use go1.22 instead of go1.21 for tidy and staticcheck

xds/internal/xdsclient/internal/internal.go, xds/internal/xdsclient/transport/grpctransport/grpctransport.go, xds/internal/xdsclient/transport/grpctransport/grpctransport_ext_test.go, xds/internal/xdsclient/transport/lrs/lrs_stream.go, xds/internal/xdsclient/transport/transport_interface.go
The existing structure of the xDS client is as follows:
- the xDS client has an `authority` type for each authority configuration in the bootstrap (ignoring authority sharing)
- each `authority` has a `Transport` which contains a `grpc.ClientConn` to the xDS management server
- the `Transport` type provides the following functionality
- runs an ADS stream, and allows the authority to trigger a `DiscoveryRequest` to be sent
- runs an LRS stream, and allows the authority to start the load reporting
The new structure for the xDS client will be as follows:
- the xDS client will have one `authority` type for each authority configuration in the bootstrap (even if the authority configuration are the same or have the same server configuration)
- the xDS …
=> xdsclient: new Transport interface and LRS stream implementation

xds/internal/xdsclient/internal/internal.go, xds/internal/xdsclient/transport/ads/ads_stream.go, xds/internal/xdsclient/transport/grpctransport/grpctransport_ext_test.go, xds/internal/xdsclient/transport/transport_interface.go
The existing structure of the xDS client is as follows:
- the xDS client has an `authority` type for each authority configuration in the bootstrap (ignoring authority sharing)
- each `authority` has a `Transport` which contains a `grpc.ClientConn` to the xDS management server
- the `Transport` type provides the following functionality
- runs an ADS stream, and allows the authority to trigger a `DiscoveryRequest` to be sent
- runs an LRS stream, and allows the authority to start the load reporting
The new structure for the xDS client will be as follows:
- the xDS client will have one `authority` type for each authority configuration in the bootstrap (even if the authority configuration are the same or have the same server configuration)
- the xDS …
=> xdsclient: new Transport interface and ADS stream implementation

resolver/resolver.go
Addresses: https://github.com/grpc/grpc-go/issues/7729
=> resolver: update ReportError() docstring

scripts/vet.sh
The runner is installing go1.22, but starts using go1.23 when running vet:
```
PATH=/home/runner/go/bin:/bin:/home/runner/go/bin:/opt/hostedtoolcache/go/1.22.8/x64/bin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+ go version
go version go1.23.2 linux/amd64
```
I added logs to debug the go version before vet.sh updates the PATH
```
+ go version
go version go1.22.8 linux/amd64
+ which go
/opt/hostedtoolcache/go/1.22.8/x64/bin/go
+ trap cleanup EXIT
+ PATH=/home/runner/go/bin:/bin:/home/runner/go/bin:/opt/hostedtoolcache/go/1.22.8/x64/bin:/snap/bin:/home/runner/.local/bin:/opt/pi …
```
=> vet: Don't use GOROOT to set PATH if GOROOT is unset

xds/internal/xdsclient/authority.go, xds/internal/xdsclient/channel.go, xds/internal/xdsclient/channel_test.go, xds/internal/xdsclient/transport/ads/ads_stream.go, xds/internal/xdsclient/xdsresource/cluster_resource_type.go, xds/internal/xdsclient/xdsresource/endpoints_resource_type.go, xds/internal/xdsclient/xdsresource/listener_resource_type.go, xds/internal/xdsclient/xdsresource/resource_type.go, xds/internal/xdsclient/xdsresource/route_config_resource_type.go
- An `xdsChannel` represents a client channel to the management server, and it builds on top of recently merged PRs that added functionality for an xDS transport and ADS/LRS streams.
- An `xdsChannel` will own a `transport.Interface`, an `ads.Stream` and an `lrs.Stream`.
- `xdsChannel`s will be owned by the xDS client and `authority` instances will acquire references to the `xdsChannel`.
- An `xdsChannel` might be shared across `authority` instances.
- An `xdsChannel` will communicate events to the xDS client (like ADS responses, ADS stream failures etc), which will propagate them to all interested `authority` instances.
- This PR only adds the `xdsChannel` functionality.
- A subsequent PR will …
=> xdsclient: implementation of the xdsChannel

internal/internal.go, xds/internal/resolver/xds_resolver.go
This PR adds a way to specify the exact xDS client to be used by the xDS resolver. Currently we only have a way of specifying the bootstrap configuration to use.
This change is required for fallback tests where we need to be able to configure xDS clients with options (like idle authority timeout) that are not part of the bootstrap configuration.
Subsequent PRs will use this functionality.
=> xds/resolver: add a way to specify the xDS client to use for testing purposes

mem/buffers.go, mem/buffers_test.go
Fixes #7631 
As the issue states, `mem.NewBuffer` would not pool buffers with a length below the pooling threshold but whose capacity is actually larger than the pooling threshold. This can lead to buffers being leaked.
RELEASE NOTES:
- mem: use slice capacity instead of length, to determine whether to pool buffers or directly allocate them
=> mem: use slice capacity instead of length, to determine whether to pool buffers or directly allocate them

xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
=> clusterresolver: fix a comment in a test

.github/workflows/deps.yml, scripts/gen-deps.sh
Fixes #7690
This change adds a new GA workflow to compare dependencies before and after a PR.  If they change, it will report a red X.  We will not require this check to pass for merging, but it should be inspected to see if the change in dependencies is reasonable and expected.
=> vet: add dependency checks

xds/internal/xdsclient/transport/ads/ads_stream.go
This PR fixes a flaky test https://github.com/grpc/grpc-go/actions/runs/11499180098/job/32006581739?pr=7773, where the following happens:
- CDS LB policy requests for a cluster resource which turns out to be an aggregate cluster.
- CDS LB policy then requests for the child clusters, which turn out to leaf clusters of type EDS.
- CDS LB policy generates child policy config for cluster_resolver with discovery mechanisms for the above EDS clusters.
- cluster_resolver does not handle its config update inline. Instead it pushes the config update on to a channel which is then read by a goroutine.
- When the config update is eventually picked up the goroutine, the cluster_resolver LB policy ends up requesting for EDS resources corresponding to the discovery mechanisms in its config.
But the …
=> xdsclient: make sending requests more deterministic

xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
Fixes https://github.com/grpc/grpc-go/issues/7464
Fixes https://github.com/grpc/grpc-go/issues/7777
Summary of fixes:
- To simulate unresponsive backends, we used to create a listener and immediately close it. What was happening was that the port was being returned to the operating system and was getting used by some other test that was running in parallel. (FYI: even though we don't do `t.Parallel` in our tests, the `go test` command runs tests from different packages in parallel, and therefore the port could get picked by a test from a different package)
- To fix this, I switched to using a `RestartableListener` that holds on to the port, but closes the connection as soon as it accepts one.
- Some tests were calling `cc.GetState` to verify that the state of the grpc client. I switched …
=> ringhash: fix a couple of flakes in e2e style tests

mem/buffers.go, mem/buffers_test.go
Original PR (#7702)
RELEASE NOTES:
- mem: use slice capacity instead of length, to determine whether to pool buffers or directly allocate them
=> Cherry-pick #7702 to 1.68.x

clientconn.go, internal/transport/http2_client.go, internal/transport/transport.go, internal/transport/transport_test.go
I was never sure why this existed.  It's easy enough and risk-free to just delete it.
=> transport: remove useless trampoline function

xds/internal/resolver/xds_resolver_test.go
Fixes https://github.com/grpc/grpc-go/issues/7799
Once resources are removed from the management server (as part of this test), the xDS client used by the resolver will see discovery responses from the server with no resources. This will trigger a resource-not-found error on the resolver when the listener resource is missing in the response from the server. This will cause the resolver to stop watching the route configuration resource.
The test then re-adds these resources to the management server, and these two events can race and can lead to the management server sending the route configuration too early to the client (which at that point thinks that it has not requested for that resource, and hence drops it on the floor).
And later when the client requests for the same route …
=> xds/resolver: fix flaky test TestResolverRemovedWithRPCs with a workaround

xds/internal/xdsclient/transport/ads/ads_stream.go
Fixes https://github.com/grpc/grpc-go/issues/7805
The ADS stream flow control type has two fields:
- `pending`: boolean that indicates if there is a recent update that is pending consumption by all watchers. This is used to buffer subscriptions when the most recent update is pending consumption.
- `readyCh`: channel used to notify when all the watchers have consumed the most recent update
The ADS stream flow control has a `wait()` method that:
- checks the `pending` bit, and if it is `false`, it does not block. It drains the `readyCh` and returns immediately. 
- If the `pending` bit is true, it waits for a signal on the `readyCh`.
The ADS stream flow control has an `onDone` method which is invoked when all watchers have consumed the update, and it sets the `pending` bit to `false` and …
=> xdsclient/ads: reset the pending bit of ADS stream flow control at the end of the onDone method

xds/internal/resolver/xds_resolver_test.go, xds/internal/xdsclient/authority.go, xds/internal/xdsclient/client_new.go, xds/server_test.go
This PR addresses two issues:
- A bug in the code: 
- In `authority.watchResource`, the watch is handled by scheduling a callback on the serializer and waiting for the callback to be executed by blocking on a `done` channel that is closed when the callback has completed its work.
- In the event where we fail to schedule the callback on the serializer, we were not closing the `done` channel. This meant that the `authority.watchResource` call would block forever.
- The same bug existed in `autority.dumpResources` as well.
- A bug in the test:
- `xdsclient.NewForTesting` accepts a bootstrap configuration as one of its options and sets the fallback bootstrap configuration (i.e. the configuration that gets used when the bootstrap env vars are not set). As part of the cleanup function that is …
=> xdsclient: fix flaky test TestServeAndCloseDoNotRace

clientconn.go, dialoptions.go, internal/internal.go, test/healthcheck_test.go
This PR removes the private `withHealthCheckFunc` dialoption which is used only in the health check tests. The tests are able to replace the `HealthCheckFunc` var defined in the `internal` package directly and restore it as part of the test cleanup. 
While working on the health producer changes which are part of generic health checks, I needed to pass the dial option to the health producer while registering a health listener just to make the existing tests pass. The HealthCheckFunc would become a part of the producer's public API, even though it is required only for testing. I changed the tests to work without the dial option.
=> grpc: Remove health check func dial option used for testing

xds/internal/balancer/clusterimpl/balancer_test.go, xds/internal/balancer/clusterimpl/clusterimpl.go, xds/internal/balancer/clusterimpl/picker.go
#5469 recommends an audit of existing LB policies to ensure that they update their pickers synchronously upon receipt of a configuration update. clusterimpl does not update picker synchronously before because of multiple reasons, one is on reciept of configuration update, process of switching the child policies was aysnchronous, and second is it was not waiting for the child policy config to be update first, before returning from `UpdateClientConnState`.
What does this PR do?
This PR ensures that every time configuration update is triggered, picker is updated synchronously.
RELEASE NOTES:
- clusterimpl: update picker synchronously on receipt of configuration update.
=> clusterimpl: update picker synchronously on config update

balancer/weightedtarget/weightedtarget.go, internal/hierarchy/hierarchy.go, xds/internal/balancer/clustermanager/clustermanager.go, xds/internal/balancer/clusterresolver/clusterresolver.go, xds/internal/balancer/priority/balancer.go
This PR plumbs EDS endpoints through the xDS Balancer tree. This is done through the hierarchy package, which is how addresses were split to their respective children.
=> xds: Plumb EDS endpoints through xDS Balancer Tree

mem/buffer_slice.go, mem/buffer_slice_test.go, rpc_util.go
I moved my project to gRPC 1.66.2 and saw a good reduction in RAM consumption. Now the hot spot is `decompress()`, where `io.Copy()` allocates a temporary buffer, reads from the reader into it, copies the read data into another buffer it got from the pool. This is an unnecessary allocation, an unnecessary copy, and underutilized buffers from the pool.
This PR adds `mem.ReadAll()` (like `io.ReadAll()`) to efficiently consume a reader into buffers from the pool.
I found https://github.com/grpc/grpc-go/issues/7631 while working on this code (I have similar code in my project, but decided to contribute it upstream and replace this `io.Copy` with it).
RELEASE NOTES:
- mem: implement a `ReadAll()` method for more efficient `io.Reader` consumption
=> mem: implement `ReadAll()` for more efficient `io.Reader` consumption

cmd/protoc-gen-go-grpc/go.mod, examples/go.mod, gcp/observability/go.mod, go.mod, interop/observability/go.mod, interop/xds/go.mod, security/advancedtls/examples/go.mod, security/advancedtls/go.mod, stats/opencensus/go.mod, test/tools/go.mod
The Go minor versions were added when bumping the go major version from 1.21 to 1.22 by running `go get go@1.22 && go mod tidy`. Specifying the minor version is not necessary unless a dependency specifies a go minor version. This PR removes the minor version from all but one go.mod file which is used for testing.
As mentioned in [this thread](https://github.com/grpc/grpc-go/pull/7624#discussion_r1757159186), grpc-go being a library should not specify a patch version.
RELEASE NOTES:
* Relax minimum Go version requirement from go1.22.7 to go1.22.
=> deps: Remove Go minor version from go.mods

xds/internal/resolver/xds_resolver_test.go, xds/internal/xdsclient/client_new.go, xds/internal/xdsclient/client_refcounted.go, xds/server_test.go
Two ways of creating an xDS client:
- `xdsclient.New`
- `xdsclient.NewForTesting`
Both of these end up calling `newRefCounted` which reads the bootstrap configuration from one of the three supported places (in the given order)
- env var `GRPC_XDS_BOOTSTRAP`
- env var `GRPC_XDS_BOOTSTRAP_CONFIG`
- fallback bootstrap configuration set using `bootstrap.SetFallbackBootstrapConfig`
`xdsclient.NewForTesting` calls `bootstrap.SetFallbackBootstrapConfig` before calling `newRefCounted`, which meant that it was changing global state and thereby making the outcome of the tests dependent on the order in which they are executed.
- Changes `newRefCounted` to accept bootstrap configuration as a parameter instead of reading the configuration from one of the above mentioned places.
- Makes `xdsclient.New` …
=> xdsclient: don't change any global state in NewForTesting

xds/internal/xdsclient/client.go, xds/internal/xdsclient/clientimpl_watchers.go, xds/internal/xdsclient/xdsresource/resource_type.go
The resource type implementation does not determine how the xDS requests are sent out. It only controls how responses are deserialized and validated.
=> xdsclient: fix resource type documentation to only mention handling xds responses

xds/internal/httpfilter/fault/fault_test.go, xds/server_ext_test.go
Partially Addresses: https://github.com/grpc/grpc-go/issues/7291
=> xds: switching to stubserver in tests instead of testservice implementation

examples/features/debugging/client/main.go, examples/features/debugging/server/main.go
This addresses a comment in #7049.
The `manual` package's `UpdateState` method cannot be used until after a client attempts to connect.  Maybe that behavior should be change, but this example really wants to use `InitialState` anyway.  Also, make the client and server listen on different ports for channelz, so they can both run at the same time.
RELEASE NOTES:
* examples: fix the debugging example
=> examples: fix debugging example after Dial->NewClient migration

orca/service_test.go
Partially Addresses: https://github.com/grpc/grpc-go/issues/7291
=> orca: switching to stubserver in tests instead of testservice implementation

internal/testutils/xds/e2e/clientresources.go, test/xds/xds_client_priority_locality_test.go, xds/internal/balancer/clusterimpl/clusterimpl.go
https://github.com/grpc/grpc-go/pull/7652 made some changes to the way `clusterimpl` handles configuration update from its parent and in the way it handles state updates from its child. But it got one thing wrong:
- If `clusterimpl` received a configuration update that did not change any drop/request config, but resulted in the child sending a new picker, then `clusterimpl` was not forwarding the picker to the parent.
This PR fixes the issue by checking for two conditions before sending a picker update to the parent:
- if drop/request config changed *and* a picker from the child policy already exists
- there is a pending picker update from the child
The way this would manifest in production is as follows:
- client application receives an update from the control plane that removes a …
=> clusterimpl: propagate state update from child when drop/request config remains unchanged

xds/internal/xdsclient/channel.go, xds/internal/xdsclient/channel_test.go, xds/internal/xdsclient/transport/ads/ads_stream.go, xds/internal/xdsclient/transport/grpctransport/grpctransport.go, xds/internal/xdsclient/transport/lrs/lrs_stream.go, xds/internal/xdsclient/transport/transport_interface.go
This PR addresses a TODO that was missed at the end of the recent refactors.
=> xdsclient: rename the interface for the transport

xds/internal/xdsclient/xdsresource/resource_type.go
Having an unexported method in the `ResourceData` interface is not very useful since it has other exported methods. Implementations are currently forced to embed this interface to satisfy it. But if a breaking change is made to the interface, implementations will panic at runtime if the newly added method is called (since they embed the interface and therefore satisfy the interface, but don't have an implementation for the newly added method).
Removing the unexported interface results in implementations no longer having to embed this interface. Instead, they can rely on compile time type assertions to ensure that their implementation satisfies the interface, and therefore their build will fail at compile time if a breaking change is made to the interface (instead of a runtime panic). …
=> xdsclient: remove unexported method from ResourceData interface

codec.go, internal/transport/transport_test.go, preloader.go, rpc_util.go, rpc_util_test.go
As discussed in https://github.com/grpc/grpc-go/pull/7653#issuecomment-2445484589, this is a minor code simplification.
=> cleanup: use SliceBuffer directly where no pool is available

internal/transport/http2_client.go, internal/transport/http2_server.go, stats/opencensus/stats.go, stats/opencensus/trace.go, stats/stats.go, stats/stats_test.go, test/end2end_test.go
Addresses: #7836
RELEASE NOTES:
- stats: deprecated trace and tags methods and remove all usages from internal code
=> stats: deprecate trace and tags methods and remove all usages from internal code

test/clientconn_state_transition_test.go
=> test: Add unit test for channel state waiting for first resolver update

balancer/balancer.go, balancer/subconn.go, balancer_wrapper.go, internal/internal.go
I deleted the release notes from #7758 and updated them here.
RELEASE NOTES:
* balancer: An internal method is added to the `balancer.SubConn` interface to force implementors to embed a delegate implementation. This requirement is present in the interface documentation, but wasn't enforced earlier.
=> balancer: fix SubConn embedding requirement to not recommend a nil panic hazard

credentials/google/google.go, credentials/google/google_test.go
The `defer cancel()` is called when `NewDefaultCredentialsWithOptions` returns and this is definitely a problem. It means the context is done, but all non-GCE token sources will rely on it to make HTTP requests to the token endpoint.
Alternatively (or maybe preferably), `NewDefaultCredentialsWithOptions` should take a top-level context. Despite this being an experimental API, I don't think such a breaking change is easy.
=> credentials: remove the context timeout to fix token request failure with non-GCE ADC

rpc_util.go
This was taken care of in https://github.com/grpc/grpc-go/pull/7653
=> cleanup: remove a TODO that has been take care of

balancer/pickfirst/pickfirst_test.go
The tests in `pickfirst_test.go` are meant to test common behaviours of both the new and old pickfirst policies depending on which LB policy is registered under the `pick_first` name. The tests were only using the old policy due to the usage of the   `pickfirstBuilder{}`. This change uses the balancer registry to get the builder.
This change also removed the `Leaf` part in the test names, since these tests are not only for the the new pickfirst.
=> pickfirst: Ensure pickfirst_test.go runs against both new and old policies

internal/transport/client_stream.go, internal/transport/handler_server.go, internal/transport/handler_server_test.go, internal/transport/http2_client.go, internal/transport/http2_server.go, internal/transport/keepalive_test.go, internal/transport/server_stream.go, internal/transport/transport.go, internal/transport/transport_test.go, rpc_util.go, rpc_util_test.go, server.go, stream.go
More background refactoring work to potentially allow us to create an interceptor that can read raw bytes, and a couple very minor cleanups, too.
Next up I'm thinking of changing `ReadMessageHeader(buf)` (I found `ReadHeader` ambiguous and confusing) and `Read(n)` into a single `Read() (isCompressed bool, msgBytes mem.BufferSlice, err error)`.  This means the transport needs to understand the grpc header and max message size configuration instead of the grpc layer, but that actually seems pretty straightforward and also appropriate.
=> transport: add send operations to ClientStream and ServerStream

xds/internal/xdsclient/authority.go, xds/internal/xdsclient/tests/lds_watchers_test.go
Addresses: #7819
Right now if any new watcher try to register watcher for removed resource, it hangs as there is no update to be received. This fix adds a condition in xDS Client to trigger watch callback `OnResourceDoesNotExist()` to new watcher if its registering for a removed resource.
RELEASE NOTES:
- xds: fixed an edge-case issue where some clients or servers would not initialize correctly if another channel or server with the same target was already in use.
=> xdsclient: fix new watcher hang when registering for removed resource

xds/internal/xdsclient/authority.go, xds/internal/xdsclient/tests/lds_watchers_test.go
Addresses: #7819
If a watch is registered for a listener resource which is already present in the cache with an old good update as well latest NACK error, the new watcher should receive both good update and error, without a new resource request being sent to the management server.
- xds: fixed an edge-case issue where some clients or servers would not receive errors if another channel or server with the same target was already in use.
=> xdsclient: fix new watcher to get both old good update and nack error (if exist) from the cache 

balancer/endpointsharding/endpointsharding.go, balancer/weightedroundrobin/balancer.go, balancer/weightedroundrobin/balancer_test.go, balancer/weightedroundrobin/metrics_test.go, balancer/weightedroundrobin/scheduler.go
This PR switches weighted round robin to defer to pick first instead of creating and handling SubConns itself. This is part of DualStack, and makes this a petiole.
RELEASE NOTES:
* balancer/weightedroundrobin: Switch Weighted Round Robin to use pick first instead of SubConns
=> balancer/weightedroundrobin: Switch Weighted Round Robin to use pick first instead of SubConns

test/xds/xds_client_ignore_resource_deletion_test.go, test/xds/xds_server_certificate_providers_test.go, test/xds/xds_server_integration_test.go, test/xds/xds_server_serving_mode_test.go, test/xds/xds_server_test.go
Partially Addresses: https://github.com/grpc/grpc-go/issues/7291
=> test/xds: remove redundant server when using stubserver in tests

credentials/alts/internal/handshaker/service/service.go, internal/resolver/dns/dns_resolver.go
We will need a patch release for this.  Can you take care of that please @purnesh42H?
RELEASE NOTES:
* credentials/alts: disable SRV and TXT lookups for handshaker service to prevent timeouts when retrieving credentials on systems containing a known bug in `systemd-resolved`.
=> cherry-pick #7861 to 1.68.x

cmd/protoc-gen-go-grpc/go.mod, examples/go.mod, gcp/observability/go.mod, go.mod, interop/observability/go.mod, interop/xds/go.mod, security/advancedtls/examples/go.mod, security/advancedtls/go.mod, stats/opencensus/go.mod, stats/opentelemetry/go.mod, test/tools/go.mod
Original PR: #7831 
RELEASE NOTES:
* Relax minimum Go version requirement from go1.22.7 to go1.22.
=> cherry-pick #7831 to v1.68.x branch 

grpclog/internal/loggerv2.go, grpclog/internal/loggerv2_test.go
Changes the logger to not call Printf when the logger is io.Discard.
Also changes the logger constructor to use `io.Discard` instead of `io.MultiWriter(io.Discard, io.Discard)`, which is necessary to detect all levels being discarded.
This is a significant performance improvement for disabled logs, see https://github.com/grpc/grpc-go/issues/7463 for details.
Notes:
- This is similar to how the std does it, see [log.go](https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/log/log.go;l=203)
- I was hoping to use the std `log.Printf` itself, but I don't think that's possible, because the JSON option needs to Printf and then escape the result _after_ interpolating, which I don't think is possible with what's exposed by the std (possibly sans some overly complex io.Writer interceptors). …
=> grpclog: change logger to avoid Printf when the logger is io.Discard

service_config.go, stream.go
Update the delay calculation to reflect the updated gRFC
Address #7514 
RELEASE NOTES:
* client: update Retry backoff to apply jitter per updates to [gRFC A6](https://github.com/grpc/proposal/blob/master/A6-client-retries.md).
=> stream: add jitter to retry backoff in accordance with gRFC A6

credentials/alts/internal/handshaker/service/service.go, internal/resolver/dns/dns_resolver.go
Sorry, it turns out GCS needs a patch release of 1.67 for this.
Original PR: #7861
RELEASE NOTES:
* credentials/alts: disable SRV and TXT lookups for handshaker service to prevent timeouts when retrieving credentials on systems containing a known bug in systemd-resolved.
=> cherry-pick #7861 to 1.67.x

experimental/stats/metricregistry.go, experimental/stats/metrics.go, internal/testutils/stats/test_metrics_recorder.go, stats/metrics.go, stats/opentelemetry/client_metrics.go, stats/opentelemetry/example_test.go, stats/opentelemetry/opentelemetry.go, stats/opentelemetry/server_metrics.go
This PR cleans up some OpenTelemetry API's before stabilization.
RELEASE NOTES:
* stats/opentelemetry: Introduce new APIs to enable OpenTelemetry instrumentation for metrics on servers and clients
=> stats/opentelemetry: Cleanup OpenTelemetry API's before stabilization

credentials/google/google.go
Fixes #7886
* credentials/google: set scope for application default credentials
=> credentials/google: Add cloud-platform scope for ADC

scripts/common.sh, scripts/gen-deps.sh, scripts/vet.sh
Any of grpc's modules should be fine to use anywhere, unless they pull in unwanted dependencies from outside grpc.  Since the deps are generated with all transitive dependencies, simply filtering out all packages under `google.golang.org/grpc` should tell us what we want and not have red Xs on the presubmit statuses when nothing external changes.
=> scripts/gen-deps: filter out grpc modules

balancer/pickfirst/pickfirstleaf/pickfirstleaf.go, balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go, channelz/service/service_test.go, internal/credentials/xds/handshake_info_test.go, internal/resolver/dns/dns_resolver.go, internal/resolver/dns/dns_resolver_test.go, internal/testutils/fakegrpclb/server.go, internal/xds/rbac/matchers.go, scripts/vet.sh, security/advancedtls/crl_test.go, test/local_creds_test.go, xds/internal/xdsclient/xdsresource/filter_chain_test.go
Fixes: #7882 #3272
Link local IPv6 addresses have the format `[IPv6-address%interface]:port`, notice the extra `%interface` part which is called the `zone`. Unlike link local IPv4 addresses, link local IPv6 addresses are not globally unique, instead they can be re-used for each network interface. As a result, the interface is required to disambiguate link local IPv6 addresses (see [wikipedia](https://en.wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses_(with_zone_index))).
Since net.ParseIP doesn't support such addresses, the PR replaces usages of net.ParseIP with the new `ipnet.PareAddr` which support IPv6 addresses with zones and also returns parsing errors.
RELEASE NOTES:
* dns: Add support for link local IPv6 addresses.
=> dns: Support link local IPv6 addresses

balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7868
In the above issue, the test failed with the following error log:
```
pickfirstleaf_ext_test.go:700: Failed to start server: net.Listen("tcp", "127.0.0.1:39795") = listen tcp 127.0.0.1:39795: bind: address already in use
```
In the test, the server was shut down and it couldn't bind to the same port when it tried to start again. This PR uses restartable listeners for the test server and exposes a methods on the test server to stop and restart the servers without closing the listeners.
=> pickfirst: Stop test servers without closing listeners

test/clientconn_state_transition_test.go
This is required to make bazel/blaze build work.
=> test: Split import paths for message and service generated code

balancer/pickfirst/pickfirst_ext_test.go
replace grpc.Dial with grpc.NewClient in test files
Addresses: https://github.com/grpc/grpc-go/issues/7049
=> balancer/pickfirst: replace grpc.Dial with grpc.NewClient in tests

service_config.go, service_config_test.go
According to A21 and A6, an invalid retry policy should result in full service config rejection instead of just skipping the policy.  This is a behavior change but also a bug fix.
RELEASE NOTES:
* client: reject service configs containing an invalid retryPolicy in accordance with gRFCs [A21](https://github.com/grpc/proposal/blob/master/A21-service-config-error-handling.md) and [A6](https://github.com/grpc/proposal/blob/master/A6-client-retries.md).  Note that it is possible this is a breaking change for some users using an invalid configuration, but continuing to allow this behavior would violate our cross-language compatibility requirements.
=> serviceconfig: Return errors instead of skipping invalid retry policy config

examples/examples_test.sh, examples/features/gracefulstop/README.md, examples/features/gracefulstop/client/main.go, examples/features/gracefulstop/server/main.go
=> examples/features/gracefulstop: add example to demonstrate server graceful stop

internal/transport/http2_server.go
=> internal/transport: replace hardcoded status codes with http constants

examples/features/xds/README.md
typo in xds readme, changed `data plan` to `data plane`
=> examples/xds: Fix typo in README.md

balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go, balancer_wrapper.go, health/producer.go, internal/internal.go, test/healthcheck_test.go
As part of the [dualstack changes described in A61](https://github.com/grpc/proposal/blob/master/A61-IPv4-IPv6-dualstack-backends.md#generic-health-reporting-mechanism), client side health check updates need to be delivered through the health listener instead of the raw connectivity listener. This PR creates a `health producer` that manages the health service client and allows registration of a listener for receiving updates. The `RegisterHealthListener` method in `acBalancerWrapper` decides whether client side health checking is enabled, if it is, it registers the health listener with the health producer. `acBalancerWrapper` wraps the LB policy's listener to synchronize updates from the health producer.
Existing health check tests are run against the health producer when the …
=> health, grpc: Deliver health service updates through the health listener

experimental/stats/metrics.go
#7874 removed symbols without leaving behind type aliases, which we should not do.  This change re-adds the things removed and should be kept for several releases.
(No release notes since it will be in a patch release.)
=> experimental/stats: re-add type aliases for migration

internal/testutils/channel.go, xds/internal/balancer/cdsbalancer/cdsbalancer_test.go, xds/internal/xdsclient/authority.go, xds/internal/xdsclient/client_new.go, xds/internal/xdsclient/client_refcounted.go, xds/internal/xdsclient/clientimpl.go, xds/internal/xdsclient/tests/ads_stream_ack_nack_test.go, xds/internal/xdsclient/tests/ads_stream_restart_test.go, xds/internal/xdsclient/tests/authority_test.go, xds/internal/xdsclient/tests/fallback_test.go, xds/internal/xdsclient/tests/helpers_test.go, xds/internal/xdsclient/tests/lds_watchers_test.go
Prior to this PR, xdsChannels were cached for a configurable amount of time after all references to them were released. This was in the hope that an xdsChannel might get used again very soon.
But with fallback support, we want channels to lower priority servers to be closed as soon as a higher priority server comes up. If at all we want to bring back support to cache unused channels, this can be implemented in the transport builder when someone asks for it.
Link to internal discussion: https://chat.google.com/room/AAAAbkw9L3c/oa6GgM1MPlk
This change does lead to a minor behavior change. Earlier when the last watch on an xdsChannel was being canceled, we would see a discovery request with no resources specified in it. But with the current change, when the last watch on an xdsChannel is …
=> xdsclient: stop caching xdsChannels for potential reuse, after all references are released

examples/features/csm_observability/server/main.go
This PR makes the example server listen explicitly on IPV4. This was causing issues as sometimes the system would listen on IPV6 in previous state which would not align with the LDS Resource.
=> examples/features/csm_observability: Make CSM Observability example server listen on an IPV4 address

dialoptions.go
=> grpcs: update `WithContextDialer` documentation to include using passthrough resolver

test/balancer_test.go
=> test: switching to stubserver in tests instead of testservice 

balancer/grpclb/grpclb_test.go, balancer/rls/picker_test.go, resolver_balancer_ext_test.go, test/balancer_switching_test.go, test/creds_test.go, test/end2end_test.go
Partially address: https://github.com/grpc/grpc-go/issues/7049
=> cleanup: replace dial with newclient

test/creds_test.go
This test was migrated from `grpc.DialContext` to `grpc.NewClient` in https://github.com/grpc/grpc-go/pull/7920. This caused the resolver to change from passthrough to dns. The test started failing on Mac and flaking on debian systems (more than 1/100 runs fail). The test uses a short timeout and expects an RPC to fail due to a bad TLS certificate. When the test fails, the RPC failure cause is `DeadlineExceeded`. The SRV lookups for localhost and service `grpclb` are causing the timeouts. SRV lookup are disabled by default.
https://github.com/grpc/grpc-go/blob/e5a4eb091f41fa414c32c4a6c8f2ba8042cb5cb0/internal/resolver/dns/dns_resolver.go#L48
SRV lookups are enabled when grpclb is imported.
https://github.com/grpc/grpc-go/blob/e5a4eb091f41fa414c32c4a6c8f2ba8042cb5cb0/balancer/grpclb/grpclb. …
=> test: Workaround slow SRV lookups in flaking test

internal/envconfig/envconfig.go, internal/xds/bootstrap/bootstrap_test.go, xds/internal/xdsclient/tests/fallback_test.go
Interop tests are passing. Setting this to `true` now will ensure that xDS fallback is ON by default starting `v1.70.0`.
RELEASE NOTES:
- xdsclient: fallback to a secondary management server (if specified in the bootstrap configuration) when the primary is down is enabled by default. Can be disabled by setting the environment variable `GRPC_EXPERIMENTAL_XDS_FALLBACK` to `false`.
=> envconfig: enable xDS client fallback by default

test/compressor_test.go
During the review of https://github.com/grpc/grpc-go/pull/7918, it was seen that even if the sender/receiver returns a `status.Internal` error code instead of `status.ResourceExhausted` when decompression results in a message exceeding the configured max receive message size, no tests fail. This PR adds a test to catch such regressions in the future.
=> test: Add a test for decompression exceeding max receive message size

internal/testutils/blocking_context_dialer_test.go, internal/transport/handler_server.go, stream.go, test/creds_test.go, test/end2end_test.go, xds/internal/balancer/clusterimpl/picker.go, xds/internal/xdsclient/transport/ads/ads_stream.go
go 1.24 includes a vet rule that catches non-constant format strings: https://github.com/golang/go/issues/60529. This causes `go test` to fail unless vet is disabled when using go1.24.
=> cleanup: Fix usages of non-constant format strings

internal/xds/rbac/rbac_engine.go, test/xds/xds_server_rbac_test.go
RBAC header matchers should be able to work with `:path` headers, per [A41](https://github.com/grpc/proposal/blob/master/A41-xds-rbac.md):
> For this design, headers can include :method, :authority, and :path matchers and they should match the values received on-the-wire independent of whether they are stored in Metadata or in separate APIs. 
Because grpc-go removes this header from what's read on the wire to what is given to applications in the metadata, we need to add it back in like we do with `:method`.
RELEASE NOTES:
* rbac: fix support for `:path` header matchers, which would previously never successfully match.
=> rbac: add method name to :path in headers

xds/internal/balancer/clusterresolver/e2e_test/eds_impl_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7961
This test was added recent in #7858. In [this test failure](https://github.com/grpc/grpc-go/actions/runs/12370599541/job/34524912126?pr=7908), the stack trace indicates that a goroutine was blocked forever. There were no failure logs though. This change avoids writing to the resolver update channel if its buffer is full.
=> clusterresolver: Avoid blocking for subsequent resolver updates in test

examples/features/csm_observability/client/main.go, examples/features/csm_observability/server/main.go, internal/xds/rbac/rbac_engine.go, test/xds/xds_server_rbac_test.go
Original PRs
- #7965
- #7945
RELEASE NOTES:
- rbac: fix support for :path header matchers, which would previously never successfully match.
- examples/features/csm_observability: update example client and server to use the helloworld service instead of echo service.
=> Cherry pick #7965 #7945 to v1.69.x

xds/internal/balancer/clusterresolver/clusterresolver.go, xds/internal/balancer/clusterresolver/configbuilder.go
Fixes: https://github.com/grpc/grpc-go/issues/7982
`clusterresolver` uses the `lastUpate()` method in the resourceResolver interface that has implementations for both EDS and DNS.
https://github.com/grpc/grpc-go/blob/2d4daf3475905868585a914ab39fdc09618869dc/xds/internal/balancer/clusterresolver/resource_resolver.go#L60-L68
When the child balancer's state needs to be updated, `clusterresolver` calls `lastUpdate` on DNS and EDS. If there were no changes since the last time `lastUpdate` was called, the child resolver will return the same update object. In case of EDS, the update contains a list of xDS endpoints, while for DNS, since https://github.com/grpc/grpc-go/pull/7858 the update contains a list of `resolver.Endpoint` grouped by locality. 
In case of EDS, when the xDS endpoints are …
=> clustetresolver: Copy endpoints.Addresses slice from DNS updates to avoid data races

xds/internal/balancer/clusterresolver/configbuilder.go
=> Cherry pick #7991 to v1.70.x

balancer/endpointsharding/endpointsharding.go, balancer/endpointsharding/endpointsharding_test.go, balancer/weightedroundrobin/balancer.go, examples/features/customloadbalancer/client/customroundrobin/customroundrobin.go
All the users of `PickFirstConfig` needed to handle parsing errors while using the exported config. This PR exports the parsed config making the usage simpler for users.
RELEASE NOTES:
* balancer/endpointsharding: The parsed pickfirst load balancer config is exported instead of the load balancer config json.
=> endpointsharding: Export parsed pickfirst config instead of json string

credentials/tls.go, experimental/credentials/credentials_test.go, experimental/credentials/internal/spiffe.go, experimental/credentials/internal/spiffe_test.go, experimental/credentials/internal/syscallconn.go, experimental/credentials/internal/syscallconn_test.go, experimental/credentials/tls.go, experimental/credentials/tls_ext_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7922
Related Issue: https://github.com/grpc/grpc-go/issues/434
This change copies the existing TLS credentials, removing the code for ALPN enforcement. These credentials will be removed in a couple of releases and users who still need to disable ALPN can copy the credentials as is. Changes made:
* Copy `credentials/tls.go` to `experimental/credentials/tls.go`. Add suffix `WithALPNDisabled` to constructors.
* Copy required packages from `internal/credentials` to `experimental/credentials/internal`.
* Improve error message when connection fails due to ALPN.
RELEASE NOTES:
* experimental/credentials: Experimental transport credentials are added which don't enforce ALPN. These will be removed in upcoming grpc-go releases. Users must not rely on …
=> credentials: Add experimental credentials that don't enforce ALPN

xds/internal/xdsclient/client_refcounted.go
This PR fixes a rare deadlock where multiple channels are created and closed to the same target URI (with an xds scheme) at the same time. This deadlock leads to xDS client creation being stalled and therefore everything on the gRPC channel is stalled.
RELEASE NOTES:
- TBD
=> xdsclient: release lock before attempting to close underlying transport

credentials/tls.go, experimental/credentials/credentials_test.go, experimental/credentials/internal/spiffe.go, experimental/credentials/internal/spiffe_test.go, experimental/credentials/internal/syscallconn.go, experimental/credentials/internal/syscallconn_test.go, experimental/credentials/tls.go, experimental/credentials/tls_ext_test.go
Original PR: #7980
Related Issues: https://github.com/grpc/grpc-go/issues/434, https://github.com/grpc/grpc-go/issues/7922
RELEASE NOTES:
* experimental/credentials: Experimental transport credentials are added which don't enforce ALPN. These will be removed in upcoming grpc-go releases. Users must not rely on these credentials directly. Instead, they should either vendor a specific version of gRPC or copy the relevant credentials into their own codebase if absolutely necessary.
=> Cherry pick #7980 to v1.70.x 

.github/workflows/deps.yml
Running the test against the base branch (instead of master) ensures the tests don't fail unnecessarily for PRs raised against release branches. 
Env vars available in Github actions: [docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables)
=> github: Run deps workflow against base branch and add branch name suffixes for easier debuggability

server.go
Previously, the buffer `d` was held for the entire duration of the handler execution in `processUnaryRPC`, leading to unnecessary memory retention. This PR adjusts the code to release the buffer immediately after the decoding function `df` completes, ensuring memory is freed as soon as it is no longer needed.
As a result, the workaround in #7972 to adjust the buffer size is no longer required, as this fix resolves the underlying issue.
RELEASE NOTES:
* grpc: The buffer used for decoding messages in unary RPCs is released after decoding. Earlier it was held till RPC completion.
=> server: fix buffer release timing in processUnaryRPC

.github/workflows/deps.yml, server.go, xds/internal/xdsclient/client_refcounted.go
Original PRs:
* #7998
* #8011 
* #8010
RELEASE NOTES:
* server: Free buffers holding raw data of request message as soon as parsing is finished in unary RPCs instead waiting till the method handler returns. (#7998)
* TBD (#8011)
=> Cherrypick #7998,  #8011, #8010 into 1.70.x

interop/client/client.go, interop/interop_test.sh, interop/soak_tests.go, interop/test_utils.go, interop/xds_federation/client.go, scripts/vet.sh
RELEASE NOTES:
Improved the rpc_soak and channel_soak tests to support concurrency in Go. This change increases the test coverage of the C2P E2E load test and follows a similar approach used in the Java implementation.
This PR aims to enhance the test coverage of the C2P E2E load test by improving the rpc_soak and channel_soak tests to support concurrency in Go. The updated logic closely follows the approach used in the Java implementation, which has already been merged. 
Noted. The interop_test.sh has been updated to include tests for rpc_soak and channel_soak.
rpc_soak:
The client performs many large_unary RPCs in sequence over the same channel. The test can run in either a concurrent or non-concurrent mode, depending on the number of threads specified (soak_num_threads).
channel_soak: …
=> interop: improve rpc_soak and channel_soak test to cover concurrency in Go

rpc_util.go
This PR fixes two bugs in the encoded message size error message:
1. Using len(b) returns the number of buffers in a BufferSlice and not the number of bytes in the BufferSlice.
2. Finding the size after calling b.Free() would return 0 if there are no remaining references to the buffers within the slice.
RELEASE NOTES:
* grpc: Fix the number of bytes reported in the error message when encoded messages are larger than `math.MaxUint32`.
=> grpc: Fix encoded message size reported in error message

internal/envconfig/xds.go, internal/testutils/xds/e2e/clientresources.go, xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/cdsbalancer/cdsbalancer_security_test.go, xds/internal/xdsclient/xdsresource/filter_chain_test.go, xds/internal/xdsclient/xdsresource/type_cds.go, xds/internal/xdsclient/xdsresource/type_rds.go, xds/internal/xdsclient/xdsresource/unmarshal_cds.go, xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go, xds/internal/xdsclient/xdsresource/unmarshal_lds_test.go
As per [gRFC A82](https://github.com/grpc/proposal/blob/master/A82-xds-system-root-certs.md), xDS client should be able to use system root certificates to validate server identity if the use of system root certs is configured by the xDS management server. This is useful when the gRPC server is behind a reverse proxy. As per the gRFC, the feature is behind a feature flag till it is proven stable.
RELEASE NOTES:
* xds: Client can use system root certificates to validate server identity when configures by the xDS management server. To enabled this feature, set the environment variable `GRPC_EXPERIMENTAL_XDS_SYSTEM_ROOT_CERTS` to `true` (case insensitive). See gRFC A82 (https://github.com/grpc/proposal/pull/436) for details.
=> xds: Implement system root certs support

balancer/lazy/lazy.go, balancer/lazy/lazy_ext_test.go
This PR adds a lazy load balancer that starts in IDLE instead of CONNECTING. This load balancer initializes a child load balancer only when its parent calls `ExitIdle` or uses the its picker. This LB policy is similar to the [LazyLoadBalancer](https://github.com/grpc/grpc-java/blob/master/xds/src/main/java/io/grpc/xds/LazyLoadBalancer.java) in Java. This balancer will be used along with endpointsharding to enable the ringhash balance to lazily initialize child pickfirst balancers as part of adding Dualstack support.
=> balancer/lazy: Add a lazy balancer

balancer/endpointsharding/endpointsharding.go, balancer/endpointsharding/endpointsharding_test.go
This change allows the children of endpointsharding to remain in IDLE state. This allows lazy initialization of children and therefore lazy creation of subchannels for endpoints. This enables the usage of endpointsharding in the ringhash balancer for managing pickfirst children.
RELEASE NOTES:
* balancer/endpointsharding: Balancers created using the new `NewBalancerWithoutAutoReconnect` function will not attempt to call `ExitIdle` automatically on their children when the children report idle.
=> endpointsharding: Allow children to remain idle if configured

xds/internal/xdsclient/clientimpl.go
One of the test in google3 doesn't expect any error/warning logs. So, adding this workaround to log bootstrap config missing warning from env error only when debugging. At the time of creating the xds client, the error will anyway be returned if config wasn't provided to the xDS client pool.
=> xds: log bootstrap config missing warning from env var only when debugging

security/advancedtls/advancedtls_integration_test.go
A pre-release version of `vet -all` on my system is running into this, so I thought I'd fix it before the actual release occurs.  This is the only instance.
=> cleanup: fix new vet errors

xds/internal/balancer/outlierdetection/balancer.go, xds/internal/balancer/outlierdetection/balancer_test.go, xds/internal/balancer/outlierdetection/callcounter.go, xds/internal/balancer/outlierdetection/callcounter_test.go, xds/internal/balancer/outlierdetection/config.go, xds/internal/balancer/outlierdetection/subconn_wrapper.go
This PR implements changes to the `outlierdetection` balancer mentioned in [A61](https://github.com/grpc/proposal/blob/master/A61-IPv4-IPv6-dualstack-backends.md#outlier-detection). `outlierdetection` is now able to eject endpoints with multiple addresses. 
Additionally this PR also removed the `scWrappers` map stored in the balancer to map `*scWrapper`->`balancer.SubConn` objects. `scWrappers` are passed to the `updateSubConnState` method directly, avoid the need to lookup the map.
RELEASE NOTES:
* outlierdetection: Add support for ejecting endpoints with multiple addresses.
=> outlierdetection: Support ejection of endpoints 

balancer/endpointsharding/endpointsharding.go, balancer/endpointsharding/endpointsharding_test.go, balancer/lazy/lazy.go, balancer/lazy/lazy_ext_test.go, balancer/leastrequest/leastrequest.go, balancer/weightedroundrobin/balancer.go, examples/features/customloadbalancer/client/customroundrobin/customroundrobin.go
Presently both `lazy` and `endpointsharding` create `gracefulswtich` balancers to manage their children. The `gracefulswitch` balancer is unnecessary as the type of the child balancer in not expected to change in existing use cases.  Having the `gracefulswitch` child requires the child balancer's builder to be registered in the global LB registry. The `lazy` LB is not a complete LB policy and should not be registered globally.
This PR makes the constructors of `endpointpointsharding` and `lazy` accept the child balancer's builder to avoid using the global registry. This PR also removes the `ParseConfig` functions/methods in `lazy` and `endpointsharding` as they will simply forward the `LoadBalancingConfig`s to their children. The children are responsible to parse the `LoadBalancingConfig` …
=> endpointsharding, lazy: Remove intermediary gracefulswitch balancers

internal/resolver/dns/dns_resolver_test.go
Fixes: #7760 
The `TestDNSResolver_ExponentialBackoff` test verifies that the DNS resolver correctly implements exponential backoff when encountering errors. It simulates a failing resolver and forces it to retry 10 times. The test overrides the standard `time.After` function, used for backoff delays, with a custom implementation `overrideTimeAfterFuncWithChannel` which uses two channels: `durChan` to receive the intended backoff duration from the resolver, and `timeChan` to signal the resolver that the waiting period is over. In each iteration of the test loop (representing a retry attempt), the test first reads from `durChan` to verify if the back off happened. Because of the test setup, this read usually gets the backoff duration from the previous resolution attempt (including the …
=> internal/dns: update TestDNSResolver_ExponentialBackoff to not return error before last resolution attempt

internal/internal.go, internal/stats/metrics_recorder_list.go, resolver/resolver.go, resolver_wrapper.go, server.go, xds/internal/resolver/internal/internal.go, xds/internal/resolver/xds_resolver.go, xds/internal/resolver/xds_resolver_test.go, xds/internal/xdsclient/authority.go, xds/internal/xdsclient/client_refcounted_test.go, xds/internal/xdsclient/clientimpl.go, xds/internal/xdsclient/metrics_test.go, xds/internal/xdsclient/pool.go, xds/server.go
This PR adds counter metrics for the xDS Client, and unit tests. E2E tests still need to be written.
The gauge metrics are blocked on adding support for asynchronous gauges, and we also should move our synchronous gauges in RLS to asynchronous.
RELEASE NOTES:
* xds/internal/xdsclient: Add counter metrics for valid and invalid resource updates
=> xds/internal/xdsclient: Add counter metrics for valid and invalid resource updates

balancer/endpointsharding/endpointsharding.go, balancer/endpointsharding/endpointsharding_test.go
In https://github.com/grpc/grpc-go/pull/8031, the `balancer.Balancer` embedding in `balancerWrapper` was removed. This causes `endpointsharding` to panic when casting the `EndpointMap` value to a `balancer.Balancer`. This PR fixes the bug and adds a test.
=> endpointsharding: cast EndpointMap values to *balancerWrapper instead of Balancer

interop/soak_tests.go
Two issues handled here:
- Updated the logging print approach to fail the test rather than only print the information when soak test total failures exceed max failures threshold.
- Renamed the successfully run soak iterations and updated the total soak iteration calculations.
@dfawley 
=> interop: Fix logging and totalIterations issues in soak_tests.go

xds/internal/xdsclient/authority.go, xds/internal/xdsclient/tests/authority_test.go, xds/internal/xdsclient/tests/fallback_test.go
Implements the update to gRFC A71 made in https://github.com/grpc/proposal/pull/473.
RELEASE NOTES:
- xdsclient: Fixes a bug where connectivity failures were reported to resource watchers before trying all listed servers.
=> xdsclient: invoke connectivity failure callback only after all listed servers have failed

test/healthcheck_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7906
The `roundrobin` balancer is using leaf pickfirst balancers since https://github.com/grpc/grpc-go/pull/7966. The fake petiole policy is no longer needed to test the health producer.
=> test: Remove fake petiole in health tests

clientconn.go
RELEASE NOTES:
* client: improve documentation of NewClient and CanonicalTarget by providing examples.
=> client: improve documentation of target strings

xds/internal/xdsclient/authority.go, xds/internal/xdsclient/clientimpl.go, xds/internal/xdsclient/clientimpl_watchers.go, xds/internal/xdsclient/tests/misc_watchers_test.go
Addresses first bullet point in https://github.com/grpc/grpc-go/issues/7931
=> xdsclient: include xds node ID in errors from the WatchResource API

balancer/lazy/lazy_ext_test.go
The test verifies that lazy's child get the latest resolver state followed by the latest resolver error. The test waits for an RPC to succeed before verifying the child has received the resolver error. The RPC can complete before the child get the resolver error. This PR uses a `grpcsync.Event` to wait till the child receives the resolver error.
Failing test run: https://github.com/grpc/grpc-go/actions/runs/13314475263/attempts/2?pr=8086
<details>
<summary> Failure stack trace </summary>
```
WARNING: DATA RACE
Read at 0x00c00019c57f by goroutine 191:
google.golang.org/grpc/balancer/lazy_test.s.TestGoodUpdateThenResolverError()
/home/runner/work/grpc-go/grpc-go/balancer/lazy/lazy_ext_test.go:289 +0x13b7
google.golang.org/grpc/balancer/lazy_test.(*s).TestGoodUpdateThenResolverError() …
```
=> lazy: Fix data race in TestGoodUpdateThenResolverError

xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
Fixes: https://github.com/grpc/grpc-go/issues/7993
Updating the DNS resolver after sending the xDS update could result in clusterresolver using the real DNS resolver and timing out. This PR ensures the real DNS resolver is replaced before the xDS update with the logical DNS cluster is sent.
Verified the test no longer fails in 10^5 runs on forge.
=> ringhash: Replace DNS resolver before sending xDS Update in test

xds/internal/balancer/ringhash/ringhash.go
Fixes: https://github.com/grpc/grpc-go/issues/8085
A61 was updated in https://github.com/grpc/proposal/pull/475. Go already follows the latest proposal, so no changes are required. Tests for the two scenarios mentioned in the PR are present.
https://github.com/grpc/grpc-go/blob/59c84a951d9d180347cd8c6052e50e81b4a55168/xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go#L2216-L2542
=> ringhash: Remove TODO comment

xds/internal/xdsclient/tests/ads_stream_backoff_test.go, xds/internal/xdsclient/tests/lds_watchers_test.go
This PR modifies existing tests for NACK and connectivity errors, to ensure that the node ID is reported to the watcher in these cases.
Addresses bullet points 2 and 3 of https://github.com/grpc/grpc-go/issues/7931.
=> xdsclient: ensure xDS node ID in included in NACK and connectivity errors

clientconn.go, internal/stubserver/stubserver.go, internal/transport/http2_client.go, profiling/cmd/flags.go, scripts/revive.toml, test/bufconn/bufconn.go, test/end2end_test.go
This add early-return and unnecessary-stmt and useless-break rules and fix them as they were mostly applied.
It also provide "preserveScope" argument for indent-error-flow and superfluous-else rules to avoid suggestions of refactorings that would increase variable scope.
=> chore: enable early-return and unnecessary-stmt and useless-break from revive

balancer/rls/balancer.go, balancer/weightedtarget/weightedtarget.go, internal/balancergroup/balancergroup.go, internal/balancergroup/balancergroup_test.go, xds/internal/balancer/clustermanager/clustermanager.go, xds/internal/balancer/priority/balancer.go
Fixes: https://github.com/grpc/grpc-go/issues/7783
Holding the mutex while making calls into balancergroup avoid concurrent calls into `balancergroup` which can result in `bg.Close()` being called at the same time as `bg.Remove()` leading to a child balancer being leaked. See https://github.com/grpc/grpc-go/issues/7783#issuecomment-2661913376 for details about such a race. 
This PR makes `balancergroup` non-restartable, i.e. it can't be started again after calling `Close`. To fix the race, in `Close`, the `balancergroup` is marked as "closed" before releasing the mutex to clear the deletion cache. This ensures no further entries are added to the cache.
Verified no failures in 100k runs.
RELEASE NOTES:
* priority: Fix race that could leak balancers and goroutines during shutdown.
=> balancergroup: Make closing terminal

xds/internal/resolver/serviceconfig.go, xds/internal/resolver/xds_resolver.go, xds/internal/xdsclient/xdsresource/filter_chain.go, xds/internal/xdsclient/xdsresource/matcher.go
Simplifies error handling for a couple of cases:
- When constructing a matcher from a Route that has already gone through validation checks in the xDS client, we can ignore errors.
- When building service config for LB policy config that we construct by hand.
Simplifying the handling of these cases greatly simplifies the next task, which is to ensure that any error reported by the resolver to the channel must include the xDS node ID. That change will be made in a follow-up PR.
Addresses: https://github.com/grpc/grpc-go/issues/7931
=> xds: simplify code handling certain error conditions in the resolver

.github/workflows/testing.yml
https://github.com/grpc/grpc-go/pull/8126 toggled the default pickfirst to the new one. This PR ensures we still have coverage for the old pickfirst till it exists.
=> github/test: Run tests using the old pickfirst

xds/internal/clients/grpctransport/grpc_transport.go, xds/internal/clients/grpctransport/grpc_transport_test.go
This PR is adding a simple grpc-based transport implementation of generic xds clients transport builder which can be provided as transport builder in xDS and LRS client. 
The `build()` method currently creates a new grpc channel every time. However, in future we will incorporate reference count map for existing transports and deduplicate transports based on provided ServerConfig so that transport channel to same server can be shared among xDS and LRS client.
[POC](https://github.com/purnesh42H/grpc-go/pull/8)
[Internal Design](https://docs.google.com/document/d/11RtR8CDgBzhSHImgJda1AJxw6uUUW-2LA8HX0UPQmyE)
=> xds: introduce simple grpc transport for generic xds clients

xds/internal/balancer/clusterresolver/clusterresolver.go
Fixes: https://github.com/grpc/grpc-go/issues/8132
`ExitIdle` may be called on `clusterresolver` before it's child is built. `clusterresolver`'s child is built when a list of endpoints is produced by the resource resolver. Logging the message at the ERROR level incorrectly fails tests.
=> clusterresolver: Lower log level when ExitIdle is called with no child

test/xds/xds_client_ignore_resource_deletion_test.go, xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/cdsbalancer/cdsbalancer_test.go, xds/internal/balancer/priority/balancer.go, xds/internal/resolver/cluster_specifier_plugin_test.go, xds/internal/resolver/helpers_test.go, xds/internal/resolver/serviceconfig.go, xds/internal/resolver/watch_service_test.go, xds/internal/resolver/xds_resolver.go, xds/internal/resolver/xds_resolver_test.go, xds/internal/xdsclient/xdsresource/errors.go
Addresses https://github.com/grpc/grpc-go/issues/7931.
Previous PRs in #7931 ensure that errors from the xDS client contains the node ID. But only applies to connectivity and NACK errors. The current watch API does not allow the xDS client to report an error value when the watched resource is not found. This PR adds that functionality to errors reported by the xDS resolver and CDS lb policy.
- CDS lb policy
- returns an error picker when the watched cluster is not found *and* when a received cluster resource fails validation checks. Under both these circumstances, we ensure that the returned error contains the xDS node id.
- xDS resolver
- When a watched resource is not found, the xDS resolver used to push a `nil` config selector which would fail RPCs. This PR instead …
=> xds: ensure xDS node ID is populated in errors from xds resolver and cds lb policy

interop/alts/client/client.go
In #7970, the [alts client was changed](https://github.com/grpc/grpc-go/pull/7970/files#diff-7f71e4c7ed0cdd9defd79e0b7424066d90939c53063b5d413ed5aecb3e65e9b1) from using `grpc.Dial` with `grpc.WithBlock` to `grpc.NewClient` without `WithBlock`.  The tests that run in g3 don't wait for the server to start before starting the client. If WithBlock is not used, the client enters TRANSIENT_FAILURE after getting a `connection refused` error in the first connection attempt. This PR adds `grpc.WaitForReady` while making the RPC to restore the previous behaviour.
=> interop: Wait for server to become ready in alts tests

resolver_test.go, resolver_wrapper.go, scripts/vet.sh
Fixes: https://github.com/grpc/grpc-go/issues/8146
The resolver wrapper has code in the UpdateState method to convert Addresses to Endpoints, but this handling was missing in the NewAddresses API. This PR adds it.
* grpc: Fix bug causing failures with message "no children to pick from" with custom resolvers that use the deprecated [NewAddresses API](https://pkg.go.dev/google.golang.org/grpc@v1.71.0/resolver#ClientConn).
=> grpc: Add endpoints in resolverWrapper.NewAddresses

resolver_test.go, resolver_wrapper.go, scripts/vet.sh
Original PR: #8149 
Related issues: #8146
* grpc: Fix bug causing RPC failures with message "no children to pick from" when using a custom resolver that calls the deprecated [NewAddress API](https://pkg.go.dev/google.golang.org/grpc@v1.71.0/resolver#ClientConn).
=> Cherry pick #8149 to v1.71.x

balancer/endpointsharding/endpointsharding_test.go, balancer/grpclb/grpclb_test.go, balancer/lazy/lazy_ext_test.go, balancer/pickfirst/pickfirst_ext_test.go, balancer/weightedroundrobin/balancer_test.go, clientconn_test.go, internal/stubserver/stubserver.go, resolver/manual/manual.go, resolver/manual/manual_test.go, resolver_test.go, test/balancer_switching_test.go, test/balancer_test.go, test/parse_config.go, test/resolver_update_test.go, xds/internal/balancer/cdsbalancer/cdsbalancer_test.go, xds/internal/balancer/clusterresolver/e2e_test/aggregate_cluster_test.go
Also, unexport mutex-protected CC field, since it's impossible to safely access.  And delete ReportError since it's just passed through to CC.
=> resolver/manual: allow calling UpdateState with an un-Built resolver

balancer/rls/config.go, balancer/rls/config_test.go
Internal feature request: b/371591767
RELEASE NOTES:
- balancer/rls: allow `maxAge` to exceed `5m` if `staleAge` is set in the LB policy configuration
=> balancer/rls: allow maxAge to exceed 5m if staleAge is set

stats/opentelemetry/client_tracing.go, stats/opentelemetry/e2e_test.go, stats/opentelemetry/server_tracing.go
RELEASE NOTES:
- stats/opentelemetry: fix tracing to use `TextMapPropagator` and `TracerProvider` from `TraceOptions` instead of OpenTelemetry globals.
=> stats/opentelemetry: use TextMapProvider and TracerProvider from TraceOptions instead of otel global

clientconn_test.go, rpc_util.go, rpc_util_test.go
Fixes #8171
This is an alternate fix to the above issue as mentioned in #8172.
I'll add a test case that ensures Read is not called beyond io.EOF.  But it looks like there might be some other problems with the tests in `rpc_util_test.go`, as several test cases are not setting the decompressor field `dc`, and I want to look at that more closely, too.
cc @jhump
RELEASE NOTES:
* grpc: fix bug causing an extra Read if a compressed message is the same size as the limit
=> grpc: fix bug causing an extra Read if a compressed message is the same size as the limit

stats/stats.go, stats/stats_test.go
RELEASE NOTES:
- **Documentation Clarification**: Clarified the expected sequencing of stats events in the server-side stats.Handler.
- **New Test Cases**: Added tests to verify the event sequencing for various RPC types, ensuring consistency and accuracy in server-side stats handling.
=> stats: Improved sequencing documentation for server-side stats events and added tests.

resolver/map.go, resolver/map_test.go
Fixes: https://github.com/grpc/grpc-go/issues/8173
This PR changes only the internal implementation of `EndpointMap` to use a map keyed by an unordered list of addresses. This avoids the need to iterate over the entire map to check the existence of a single element. This brings down the average case time complexity for Get, Set and Delete from O(n) to O(1) per operation, where `n` is the number of endpoints in the map.
Code:
```go
func BenchmarkEndpointMap(b *testing.B) {
em := NewEndpointMap()
for i := range b.N {
em.Set(Endpoint{
Addresses: []Address{{Addr: fmt.Sprintf("%d.%d.%d.%d", i, i, i, i)}},
}, i)
}
for i := range b.N {
em.Get(Endpoint{
Addresses: []Address{{Addr: fmt.Sprintf("%d.%d.%d.%d", i, i, i, i)}},
})
}
for i := range b.N {
em.Delete(Endpoint{
Addresses: []Address{{Addr: …
```
=> resolver: Make EndpointMap's Get, Set and Delete operations O(1)

resolver/map.go, resolver/map_test.go
Original PR: #8179
Related issue: https://github.com/grpc/grpc-go/issues/8173
RELEASE NOTES:
* resolver: EndpointMap's Get, Set and Delete operations are now O(1) on average.
=> Cherry-pick #8179 into v1.71.x

clientconn_test.go, rpc_util.go, rpc_util_test.go
Original PR: #8178 
RELEASE NOTES:
* grpc: fix bug causing an extra Read if a compressed message is the same size as the limit
=> Cherry-pick #8178 to v1.71.x release branch

xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/clusterimpl/tests/balancer_test.go, xds/internal/balancer/clusterresolver/configbuilder.go
Previously this setting was only plumbed to EDS, which meant it didn't apply to LOGICAL_DNS, but it should apply to both.
RELEASE NOTES:
* xds: fix support for circuit breakers in LOGICAL_DNS clusters
=> xds: fix support for circuit breakers in LOGICAL_DNS clusters

xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/clusterimpl/tests/balancer_test.go, xds/internal/balancer/clusterresolver/configbuilder.go
(To avoid merge conflicts, this also contains #8169 as the first commit.)
While fixing #8169, we noticed that LRS was also not being plumbed to LOGICAL_DNS clusters.  This change adds support for it and an e2e test to ensure the LRS server is being used as intended.
RELEASE NOTES:
* xds: fix support for load reporting in LOGICAL_DNS clusters
=> xds: fix support for load reporting in LOGICAL_DNS clusters

stats/opentelemetry/client_tracing.go, stats/opentelemetry/e2e_test.go, stats/opentelemetry/server_metrics.go, stats/opentelemetry/server_tracing.go, xds/internal/xdsclient/clientimpl.go, xds/internal/xdsclient/pool.go, xds/internal/xdsclient/pool/pool_test.go, xds/server_test.go
Original PRs: https://github.com/grpc/grpc-go/pull/8164 https://github.com/grpc/grpc-go/pull/8166
RELEASE NOTES:
- xds: restore the behavior of reading bootstrap config before creating the first xDS client instead of package init time.
- stats/opentelemetry: fix tracing to use TextMapPropagator and TracerProvider from TraceOptions instead of OpenTelemetry globals.
=> Cherry-pick #8164 #8166 to v1.71.x

balancer/base/balancer.go, balancer/pickfirst/pickfirstleaf/pickfirstleaf.go, balancer/weightedroundrobin/balancer.go, resolver/map.go, resolver/map_test.go
RELEASE NOTES:
* resolver: Add experimental `AddressMapV2` with generics to ultimately replace `AddressMap`.  Deprecate `AddressMap` for deletion.
=> resolver: create AddressMapV2 with generics to replace AddressMap

balancer/endpointsharding/endpointsharding.go, balancer/leastrequest/leastrequest.go, balancer/weightedroundrobin/balancer.go, resolver/map.go, resolver/map_test.go, xds/internal/balancer/outlierdetection/balancer.go, xds/internal/balancer/ringhash/ring.go, xds/internal/balancer/ringhash/ring_test.go, xds/internal/balancer/ringhash/ringhash.go, xds/internal/balancer/ringhash/ringhash_test.go
This is #8187 but for EndpointMap.  In this case, I could find zero external usages of this type, since it is so new, so I thought it would be OK to just convert it in place.
RELEASE NOTES:
- resolver: convert EndpointMap to use generics
=> resolver: convert EndpointMap to use generics

internal/resolver/delegatingresolver/delegatingresolver.go, internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
Original PR: #8195
Related Issue: https://github.com/grpc/grpc-go/issues/8168
RELEASE NOTES:
* resolver/delegatingresolver: Avoid deadlocks when an http proxy is configured and a resolver calls `UpdateState` synchronously while handling a `ResolveNow` call.
* resolver/delegatingresolver: Fix race that may cause panics when an http proxy is configured and the resolver is closing.
=> Cherry-pick #8195 into v1.71.x

xds/internal/xdsclient/authority.go, xds/internal/xdsclient/clientimpl.go, xds/internal/xdsclient/metrics_test.go
Internal ticket b/401438450
RELEASE NOTES:
- xds: add `grpc.xds_client.server_failure` counter metric on xDS client to record connectivity errors.
=> xdsclient: add grpc.xds_client.server_failure counter mertric

xds/internal/xdsclient/metrics_test.go
Fixes: #8211
`TestServerFailureMetrics_BeforeResponseRecv` was flaking because of race between listener watch to start and closing the listener and if watch hasn't started the stream errors won't be received and server failure metric won't be emitted. Adding the hook to wait for stream to open before stopping the listener have fixed the race.
[Successful forge run](https://fusion2.corp.google.com/invocations/ab09a308-5ffe-414c-ba71-ee7fa07b5a1b/targets/%2F%2Fthird_party%2Fgolang%2Fgrpc%2Fxds%2Finternal%2Fxdsclient:xdsclient_test/log)
=> xdsclient: fix TestServerFailureMetrics_BeforeResponseRecv test to wait for watch to start before stopping the listener

credentials/alts/internal/conn/common.go, credentials/alts/internal/conn/record.go, credentials/alts/internal/conn/record_test.go, credentials/alts/internal/handshaker/handshaker.go
Internal issue: b/400312873
While benchmarking Google Cloud Storage read performance, the flame graphs showed significant time being spent in `google.golang.org/grpc/credentials/alts/internal/conn.(*conn).Read`.  These changes are done to reduce the time spent in this function. The following optimizations are done:
1. In the handshaker, allocate a buffer only once, outside the `for` loop.
2. Use 32KB (previously 4KB) buffers to read from the network.
3. When a complete ALTS frame doesn't fit into the buffer, directly expand the buffer to the required capacity instead of incrementing in steps of 4KB.
4. If the buffer passed to `Read()` is large enough, use it to store the decrypted message, avoiding an extra copy to `buf`. The default buffer size used by gRPC is 16KB, which also happens to …
=> credentials/alts: Optimize reads

credentials/alts/internal/conn/record.go
This addresses the following review  comment: https://github.com/grpc/grpc-go/pull/8204#discussion_r2031420639
=> credentials/alts: Add comments to clarify buffer sizing

testdata/spiffe_end2end/README.md
This fixes findings of an internal linter.
=> testdata: Wrap lines to 80 columns in markdown file

stats/opentelemetry/e2e_test.go, stats/opentelemetry/trace.go
As per https://github.com/grpc/proposal/blob/master/A72-open-telemetry-tracing.md `sequence-number` starts at 0.
RELEASE NOTES:
- stats/opentelemetry: fix trace attributes message sequence numbers to start from 0.
=> stats/opentelemetry: fix trace attributes message sequence numbers to start from 0

xds/internal/balancer/ringhash/config.go, xds/internal/balancer/ringhash/config_test.go
With gRFC A76 (#8159), when requestHashHeader is specified from the service config it fails the validation since MD keys with uppercase letters are normalized to lowercase. We should normalize the parsed value before validation.
=> ringhash: normalize uppercase in requestHashHeader from service config

xds/internal/xdsclient/transport/lrs/lrs_stream.go
the origin `err` has been checked in line 233.
it is nil now, and after check `CheckInvalid() != nil`,
here should use the check err
RELEASE NOTES:
* xds: Fix reported error string when LRS load reporting interval is invalid.
=> Update lrs_stream.go fix use of wrong err

stats/opentelemetry/e2e_test.go, stats/opentelemetry/trace.go
Original PR: #8237 
RELEASE NOTES:
- stats/opentelemetry: fix trace attributes message sequence numbers to start from 0.
=> Cherry-pick #8237 to v1.72.x

internal/envconfig/envconfig.go, internal/metadata/metadata.go, internal/testutils/envconfig.go, internal/testutils/xds/e2e/clientresources.go, resolver/ringhash/attr.go, xds/internal/balancer/clusterresolver/configbuilder.go, xds/internal/balancer/ringhash/config.go, xds/internal/balancer/ringhash/config_test.go, xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go, xds/internal/balancer/ringhash/picker.go, xds/internal/balancer/ringhash/picker_test.go, xds/internal/balancer/ringhash/ring.go, xds/internal/balancer/ringhash/ring_test.go, xds/internal/balancer/ringhash/ringhash.go, xds/internal/balancer/ringhash/ringhash_test.go, xds/internal/balancer/ringhash/util.go, xds/internal/resolver/serviceconfig.go, xds/internal/resolver/xds_resolver_test.go, xds/internal/xdsclient/xdsresource/type_eds.go, xds/internal/xdsclient/xdsresource/unmarshal_eds.go, xds/internal/xdsclient/xdsresource/unmarshal_eds_test.go
Original PRs: #8159 #8243
RELEASE NOTES:
- ringhash: implement gRFC A76
=> Cherry-pick #8159 and #8243 to v1.72.x

internal/xds/bootstrap/tlscreds/bundle_ext_test.go
We were checking a file that didn't exist and it was causing a rare race - https://github.com/grpc/grpc-go/issues/8246
This brings up another question that I've added to the bug, but this fix is needed regardless.
=> xds: fix test data file name

balancer/pickfirst/pickfirstleaf/pickfirstleaf.go, balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
Original PR: #8227 
Related Issue: #8225
RELEASE NOTES:
* balancer/pickfirstleaf: Ignore the deprecated `Address.Metadata` field.
=> Cherry-pick #8227 to v1.72.x

internal/envconfig/envconfig.go, xds/internal/xdsclient/xdslbregistry/xdslbregistry.go, xds/internal/xdsclient/xdslbregistry/xdslbregistry_test.go, xds/internal/xdsclient/xdsresource/unmarshal_cds_test.go
RELEASE NOTES:
* xds: enable least request LB policy by default. It can be disabled by setting `GRPC_EXPERIMENTAL_ENABLE_LEAST_REQUEST=false` in your environment.
=> xds: make least request available by default

stats/opentelemetry/e2e_test.go, test/xds/xds_telemetry_labels_test.go, xds/internal/balancer/clusterimpl/balancer_test.go, xds/internal/balancer/clusterimpl/picker.go, xds/internal/balancer/clusterresolver/configbuilder.go, xds/internal/balancer/clusterresolver/configbuilder_test.go, xds/internal/balancer/wrrlocality/balancer.go, xds/internal/balancer/wrrlocality/balancer_test.go, xds/internal/internal.go, xds/internal/internal_test.go, xds/internal/xdsclient/tests/loadreport_test.go, xds/internal/xdsclient/xdsresource/unmarshal_eds.go
Internal issue: b/397462082
The format of the locality ID used for reporting metrics is specified here: https://github.com/grpc/proposal/blob/master/A78-grpc-metrics-wrr-pf-xds.md#optional-xds-locality-label
gRPC Go uses JSON which is inconsistent with other gRPC implementations. This PR fixes this.
RELEASE NOTES:
* xds: Locality ID metric label is changed to make it consistent with [gRFC A78](https://github.com/grpc/proposal/blob/master/A78-grpc-metrics-wrr-pf-xds.md#optional-xds-locality-label).
=> xds: Make locality ID string representation consistent with A78

xds/internal/balancer/ringhash/e2e/ringhash_balancer_test.go
Fixes https://github.com/grpc/grpc-go/issues/8247.
1. Fix Test/RingHash_RequestHashKeyRandom by setting minRingSize to a higher value as we were doing in other tests. It lowers the skew that may occur from an imbalanced ring.
2. Fix Test/RingHash_RequestHashKeyConnecting by waiting for at least one connection attempt before proceeding to check for other connection attempts. That accounts for the unlikely case where the connection attempt has not been made by the time the channel transitions to CONNECTING state.
Testing done:
```
go test -run='Test/RingHash_RequestHashKey(Connecting|Random)' ./xds/internal/balancer/ringhash/e2e -count 10000
```
=> ringhash: fix flaky e2e tests

credentials/credentials.go, credentials/google/google_test.go, credentials/sts/sts_test.go, internal/credentials/credentials.go, internal/transport/http2_client.go
The primary use case is to allow testing PerRPCCredentials implementations that live outside of google.golang.org/grpc.
The secondary (somewhat weirder) use case is to allow reusing existing PerRPCCredentials implementations (as long as they don't depend on handshake details) outside of the standard gRPC client environment (i.e. with alternative implementations of grpc.ClientConnInterface that reuse gRPC code generator machinery and APIs, but don't use the actual implementations).
Fixes #8080.
- credentials: add NewRequestInfoContext to allow testing PerRPCCredentials implementations.
=> credentials: expose NewRequestInfoContext publicly

credentials/alts/internal/conn/record.go
This PR clarifies the usage of destination slices passed to crypto implementations.
=> atls: Clarify usage of dst in ALTSRecordCrypto interface docs

xds/server_ext_test.go, xds/server_security_ext_test.go
Fixes: #8268
[Successful Forge Run](https://fusion2.corp.google.com/invocations/5729c9d3-8b43-44ca-8ea7-aa65b2b75e6d)
=> xds: fix TestServer_Security_WithValidAndInvalidSecurityConfiguration data race

.github/workflows/release.yml
Fixes: [#6416](https://github.com/grpc/grpc-go/issues/6416#issuecomment-1634700290) 
This PR replaces the usage of `actions/upload-release-asset@v1` with gh 
An example of the release can be found [here](https://github.com/Sebas03446/grpc-go/releases/tag/cmd%2Fprotoc-gen-go-grpc%2Fv1.5.3)
=> github: replace actions/upload-release-asset@v1 with gh cli

xds/internal/clients/xdsclient/helpers_test.go, xds/internal/clients/xdsclient/test/helpers_test.go, xds/internal/xdsclient/xdsresource/unmarshal_lds.go
Fixing findings from internal analyzer: [go/gobugs-findings#protonil](http://go/gobugs-findings#protonil)
> The Go Proto API is nil safe: it is safe to call Has/Get-methods on nil messages. If a Has-method is called on a nil proto, it returns false. If a Get-method is called on a nil proto, it returns the field's default value. This nil safety makes it possible to chain Get-methods calls without intermediate nil checks.
=> xds: Remove redundant proto checks

stream_test.go, test/end2end_test.go
Fixes: #7570
Added the following tests for client streaming RPC : 
1. Client should ensure a status `internal` error is returned for client-streaming RPCs if the server doesn't send a message before returning status OK. This is a cardinality violation. Skipping this test for now till the issues are fixed: #8119 
2.   Server can continue to receive messages after calling SendAndClose.
3. Recv() on client streaming client blocks till the server handler returns even after calling SendAndClose from the server handler
4. Client receives nil message and non-nil error when server handler returns an error after calling SendAndClose.
=> grpc_test: add tests for cardinality violation

credentials/alts/internal/conn/common.go, credentials/alts/internal/conn/record.go, credentials/alts/internal/conn/record_test.go, credentials/alts/internal/handshaker/handshaker.go
This PR roll forwards #8204 and #8232 which were rolled back in #8236. The required fixes have been made in cl750069203 and cl/750076439.
RELEASE NOTES:
* credentials/alts: Improve read performance by optimizing buffer copies and allocations.
=> credentials/alts: Optimize Reads (Roll forward #8236)

credentials/alts/alts.go, credentials/alts/alts_test.go, credentials/alts/internal/handshaker/handshaker.go, credentials/alts/internal/testutil/testutil.go
At present, this field will only be exposed internally, it is not currently planned for wide usage.
=> alts: Add plumbing for the bound access token field in the ALTS StartClient request.

test/xds/xds_server_integration_test.go, test/xds/xds_server_rbac_test.go
Fixes: https://github.com/grpc/grpc-go/issues/8286
This PR makes the test wait for the xds server to enter SERVING mode, otherwise it closes the net.Conn without returning any error.
https://github.com/grpc/grpc-go/blob/763d093ac8109661f4b7a118ce740eccbd100fb4/xds/internal/server/listener_wrapper.go#L287-L297
Analysis: https://github.com/grpc/grpc-go/issues/8286#issuecomment-2850859357
Verified the test passes 10^5 runs on forge. 
=> xds_test: Wait for server to start serving in RBAC test

internal/resolver/delegatingresolver/delegatingresolver.go, internal/resolver/delegatingresolver/delegatingresolver_ext_test.go, internal/transport/http2_client.go, internal/transport/http_util.go, internal/transport/http_util_test.go
Fixes: https://github.com/grpc/grpc-go/issues/8207
Original PR: https://github.com/grpc/grpc-go/pull/8215
RELEASE NOTES:
- resolver/delegatingresolver: Proxy connections are no longer attempted for targets with non-TCP network types.
=> cherry-pick #8215 to v1.72.x branch

credentials/alts/internal/handshaker/service/service.go, internal/envconfig/envconfig.go
The most important number here is the 5 seconds timeout. It means the client will close the connection if there is no activity for 5 seconds. It helps with the situation when the connection is somehow broken.
=> [alts] add keepalive params to the alts handshaker client dial option

balancer/weightedroundrobin/balancer.go
The embedded `balancer.SubConn` is never assigned and only used in debug logs. The logs always show the SubConn as `nil`.
=> weightedroundrobin: Remove nil embedded SubConn from endpointWeight

credentials/credentials_ext_test.go, credentials/local/local.go
Add ValidateAuthority implementation to local credentials to allow authority override. It permits any authority override when using local credentials.
Addresses: #5361 
=> credentials/local: implement ValidateAuthority

internal/transport/http_util.go, internal/transport/http_util_test.go
Negative timeouts should be forbidden. The previous implementation called ParseInt and allowed negative timeouts. Change it to call ParseUint to reject these values. This is also slightly faster, since ParseInt eventually calles ParseUint. Extend the test to cover more cases.
RELEASE NOTES:
* transport: Non-positive `grpc-timeout` header values are now rejected by servers. This is consistent with the [gRPC protocol spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#requests).
=> transport: Reject non-positive timeout values in server

internal/resolver/delegatingresolver/delegatingresolver_ext_test.go
Since the proxy resolver is now initialized in a goroutine triggered by the target resolver's update, we need to ensure that it is fully constructed before allowing it to send updates in tests. This mirrors the real-world behavior, where the proxy resolver cannot send updates unless it has been built. In tests, if we don't wait for this initialization, it may lead to a panic.
=> resolver/delegatingresolver: wait for proxy resolver build before update in tests

internal/transport/http2_client.go, internal/transport/transport_test.go, stream.go, test/transport_test.go
Fixes: https://github.com/grpc/grpc-go/issues/8281
RCA: https://github.com/grpc/grpc-go/issues/8281#issuecomment-2848692246
This PR  uses a status error instead of an `io.UnexpectedEOF` to fail RPCs that have partially read a gRPC message.
RELEASE NOTES:
* grpc: Fix bug that causes RPCs to fail with status `INTERNAL` instead of `CANCELLED` or `DEADLINE_EXCEEDED` when the client receives an RST_STREAM frame while reading a gRPC message.
=> transport: Propagate status code on receiving RST_STREAM during message read

internal/grpcsync/event.go
This change avoids using `sync.Once` and reuses the existing atomic boolean to ensure an event is fired only once.
=> grpcsync/event: Simplify synchronization

internal/resolver/delegatingresolver/delegatingresolver.go, internal/resolver/delegatingresolver/delegatingresolver_ext_test.go, internal/transport/http2_client.go, internal/transport/http_util.go, internal/transport/http_util_test.go
Fixes: https://github.com/grpc/grpc-go/issues/8207
Original PR: https://github.com/grpc/grpc-go/pull/8215 , https://github.com/grpc/grpc-go/pull/8302 ,  https://github.com/grpc/grpc-go/pull/8304
RELEASE NOTES:
- resolver/delegatingresolver: Proxy connections are no longer attempted for targets with non-TCP network types.
=> cherry-pick #8215, #8302 and #8304 to v1.71.x branch

internal/leakcheck/leakcheck_test.go
Fixes #8276 
leakcheck.TestCheck and leakcheck.TestCheckRegisterIgnore is flaky due to a gouroutine leak caused by [context.WithTimeout()](https://github.com/grpc/grpc-go/blob/950a7cfdfd571b75f6b869ae0f625f9d65b19842/internal/leakcheck/leakcheck_test.go#L54C2-L55C16).
Flakiness was filed in  #8276.
=> leakcheck: Fix flaky test TestCheck

internal/transport/http2_client.go, internal/transport/transport_test.go, test/transport_test.go
Addresses: https://github.com/grpc/grpc-go/issues/8281
Original PR: #8289 
RELEASE NOTES:
* grpc: Fix bug that causes RPCs to fail with status `INTERNAL` instead of `CANCELLED` or `DEADLINE_EXCEEDED` when the client receives an RST_STREAM frame while reading a gRPC message.
=> Cherry-pick #8289 to v1.72.x

internal/transport/http2_client.go, test/end2end_test.go
After https://github.com/grpc/grpc-go/pull/8290 is merged, negative timeout values fail the request with an internal status instead of a deadline exceeded. This test uses negative deadlines and can fail if the server sends an internal error before the client sees the deadline expire.
Sample failure: https://github.com/grpc/grpc-go/actions/runs/14979137997/job/42078795928?pr=8308
The client checks the deadline expiry before creating a stream.
https://github.com/grpc/grpc-go/blob/709023de87a25ae63b000139295af10589edffee/stream.go#L410-L413
However, the deadline may expire after this check, but before the `grpc-timeout` header is created.
RELEASE NOTES:
* transport: Fail RPCs on the client when using extremely short contexts that expire before the `grpc-timeout` header is created.
=> transport: Prevent sending negative timeouts

CONTRIBUTING.md, xds/internal/clients/xdsclient/xdsclient.go
=> cleanup: remove unused constants in generic xdsclient

CONTRIBUTING.md
=> grpc: update contributing.md

xds/internal/clients/internal/testutils/channel.go, xds/internal/clients/xdsclient/ads_stream.go, xds/internal/clients/xdsclient/ads_stream_watch_test.go, xds/internal/clients/xdsclient/internal/internal.go, xds/internal/clients/xdsclient/internal/xdsresource/ads_stream.go, xds/internal/clients/xdsclient/test/ads_stream_ack_nack_test.go, xds/internal/clients/xdsclient/test/ads_stream_backoff_test.go, xds/internal/clients/xdsclient/test/ads_stream_flow_control_test.go, xds/internal/clients/xdsclient/test/ads_stream_restart_test.go, xds/internal/clients/xdsclient/test/ads_stream_watch_test.go, xds/internal/clients/xdsclient/test/authority_test.go, xds/internal/clients/xdsclient/test/lds_watchers_test.go, xds/internal/clients/xdsclient/xdsclient.go
=> xds: generic xds client ads stream tests

balancer/leastrequest/leastrequest.go, balancer/leastrequest/leastrequest_test.go
There was a leftover embedded balancer in least request that was never set in the code when it got refactored to pick first as leaf. As a result, method calls forwarded to the embedded balancer would panic.
Remove the embedded balance and properly forward the missing methods.
Fixes https://github.com/grpc/grpc-go/issues/8332
RELEASE NOTES:
- balancer/least_request: fix panic on resolver errors when using least_request.
=> balancer/least_request : Fix panic while handling resolver errors

internal/transport/transport_test.go
Internal bug: b/416700146
Presently the PingPong tests don't wait for server goroutines to finish work before the return. This causes data races when the next test tries to update the GRPCLogger. Closing the server isn't sufficient.
https://github.com/grpc/grpc-go/blob/950a7cfdfd571b75f6b869ae0f625f9d65b19842/internal/transport/http2_server.go#L1265-L1268
=> internal/transport: Wait for server goroutines to exit during shutdown in test

test/kokoro/psm-light.cfg
This is part of a cross-repository change to generalize the fallback test suite to support other tests, and to change the name for clarity. See also https://github.com/grpc/psm-interop/pull/179.
=> Rename PSM interop fallback test suite to light

internal/resolver/delegatingresolver/delegatingresolver.go, internal/resolver/delegatingresolver/delegatingresolver_ext_test.go, internal/transport/proxy_ext_test.go
Fixes: #8327
Add a check for resolved addresses to avoid proxy for addresses mentioned in NO_PROXY environment variable. We only had a check for unresolved addresses.
- client: fixed a bug that was attempting to use a proxy for addresses matching NO_PROXY environment variable
=> delegatingresolver: avoid proxy for resolved addresses in NO_PROXY env

internal/resolver/delegatingresolver/delegatingresolver.go, internal/resolver/delegatingresolver/delegatingresolver_ext_test.go, internal/transport/proxy_ext_test.go
Original PR: #8329 
Related Issue: https://github.com/grpc/grpc-go/issues/8327
RELEASE NOTES:
- client: restore support for `NO_PROXY` environment variable when connecting to locally-resolved addresses. This fixes a regression and restores historical grpc-go behavior (use case 2 from [gRFC A1](https://github.com/grpc/proposal/blob/master/A1-http-connect-proxy-support.md) ).
=> Cherry-pick #8329 to v1.71.x

internal/balancergroup/balancergroup.go
`exitIdle()` is called in both ExitIdle() and ExitIdleOne()
```go
func (bg *BalancerGroup) ExitIdle() {
bg.outgoingMu.Lock()
defer bg.outgoingMu.Unlock()
if bg.outgoingClosed {
return
}
for _, config := range bg.idToBalancerConfig {
if !config.exitIdle() { // here
bg.connect(config)
}
}
}
func (bg *BalancerGroup) ExitIdleOne(id string) {
bg.outgoingMu.Lock()
defer bg.outgoingMu.Unlock()
if bg.outgoingClosed {
return
}
if config := bg.idToBalancerConfig[id]; config != nil {
if !config.exitIdle() { // here
bg.connect(config)
}
}
}
```
it returns boolean value. if it returns false if-statement works.
But the current implementation of `exitIdle()` is returning only true.
`exitIdle` method returns boolean type but implementation returns only true. 
``` go
func (sbc *subBalancerWrapper) …
```
=> balacergroup: cleanup exitIdle()

xds/internal/clients/xdsclient/test/helpers_test.go, xds/internal/clients/xdsclient/test/metrics_test.go
Fixes: https://github.com/grpc/grpc-go/issues/8344
[Successful forge test](https://fusion2.corp.google.com/invocations/129660cb-0099-4802-b916-4d8db4f4a365/targets/%2F%2Fthird_party%2Fgolang%2Fgrpc%2Fxds%2Finternal%2Fclients%2Fxdsclient%2Ftest:xdsclient_test/tests)
In a rare case scenario of NACK, the xDS client can emit metrics in quick succession due to the interaction sequence between the xDS client (in grpc-go) and the test management server (using go-control-plane) after the initial invalid update. The test uses `testMetricsReporter ` for xdsclient to report metrics which calls `metricsReporter.ReportMetric()` to report invalid and valid xds resource updates. The flakiness is due to timeout in `r.metricsCh.Send(m)` in the case burst of redundant updates because the `metricsCh` in …
=> xdsclient: Fix flakyness in `TestResourceUpdateMetrics` in the case of repeated NACKs

internal/transport/controlbuf.go, internal/transport/http2_server.go
This change uses a sync pool to cache `itemNodes` used by `controlbuf` and stores a method as a closure to avoid a heap allocation while creating frames for the `controlbuf`. This brings down `allocs/op` by ~18%.
```go
❯ go run benchmark/benchresult/main.go before after
streaming-networkMode_Local-bufConn_false-keepalive_false-benchTime_30s-trace_false-latency_0s-kbps_0-MTU_0-maxConcurrentCalls_60-reqS
ize_32384B-respSize_32384B-compressor_off-channelz_false-preloader_false-clientReadBufferSize_-1-clientWriteBufferSize_-1-serverReadBu
fferSize_-1-serverWriteBufferSize_-1-sleepBetweenRPCs_0s-connections_1-recvBufferPool_simple-sharedWriteBuffer_false
Title       Before        After Percentage
TotalOps      1089062      1092837     0.35%
SendOps            0            0      NaN%
RecvOps …
```
=> transport: Optimize allocations

internal/transport/controlbuf.go, internal/transport/http2_client.go, internal/transport/http2_server.go, internal/transport/transport_test.go, mem/buffer_slice.go
This introduces a new method to reset the BufferSlice being used by a `mem.Reader`. The enables using a single `Reader` for an HTTP/2 stream instead of allocating one object per gRPC message. This reduces allocs/op, but doesn't have a noticable impact on qps or latency.
```
go run benchmark/benchresult/main.go before after
streaming-networkMode_Local-bufConn_false-keepalive_false-benchTime_30s-trace_false-latency_0s-kbps_0-MTU_0-maxConcurrentCalls_60-reqSi
ze_32384B-respSize_32384B-compressor_off-channelz_false-preloader_false-clientReadBufferSize_-1-clientWriteBufferSize_-1-serverReadBuff
erSize_-1-serverWriteBufferSize_-1-sleepBetweenRPCs_0s-connections_1-recvBufferPool_simple-sharedWriteBuffer_false
Title       Before        After Percentage
TotalOps      1089062      1096640     0.70% …
```
=> transport: Re-use slice buffer reader for a stream

xds/internal/clients/grpctransport/grpc_transport.go
=> xds/internal: update generic grpctransport codec name to  proto

balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go, channelz/grpc_channelz_v1/channelz_grpc.pb.go, cmd/protoc-gen-go-grpc/grpc.go, credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go, examples/features/proto/echo/echo_grpc.pb.go, examples/helloworld/helloworld/helloworld_grpc.pb.go, examples/route_guide/routeguide/route_guide_grpc.pb.go, health/grpc_health_v1/health_grpc.pb.go, internal/proto/grpc_lookup_v1/rls_grpc.pb.go, interop/grpc_testing/benchmark_service_grpc.pb.go, interop/grpc_testing/report_qps_scenario_service_grpc.pb.go, interop/grpc_testing/test_grpc.pb.go, interop/grpc_testing/worker_service_grpc.pb.go, interop/stress/grpc_testing/metrics_grpc.pb.go, profiling/proto/service_grpc.pb.go, reflection/grpc_reflection_v1/reflection_grpc.pb.go, reflection/grpc_reflection_v1alpha/reflection_grpc.pb.go, reflection/grpc_testing/test_grpc.pb.go
=> cmd/protoc-gen-go-grpc: use `Error()` since no formatting is performed

balancer/roundrobin/roundrobin.go
This override was introduced recently in https://github.com/grpc/grpc-go/pull/8367. It's not necessary.
=> roundrobin: Remove unnecessary ExitIdle override

balancer/pickfirst/pickfirstleaf/pickfirstleaf.go, xds/internal/balancer/outlierdetection/balancer.go, xds/internal/balancer/outlierdetection/balancer_test.go, xds/internal/balancer/outlierdetection/subconn_wrapper.go
Fixes: https://github.com/grpc/grpc-go/issues/7915
During the implementation of dualstack changes, OutlierDetection needed to handle ejection of subchannels using both the connectivity listener and the new health listener. Now that all Petiole LB policies used in xDS delegate to pick_first, OutlierDetection only needs to support ejection through the health listener. The old code for ejection via the connectivity listener has been cleaned up.
=> outlierdetection: cleanup temporary pickfirst health listener attribute

xds/internal/xdsclient/xdsresource/cluster_resource_type.go, xds/internal/xdsclient/xdsresource/endpoints_resource_type.go, xds/internal/xdsclient/xdsresource/listener_resource_type.go, xds/internal/xdsclient/xdsresource/resource_type.go, xds/internal/xdsclient/xdsresource/route_config_resource_type.go
This is a follow-up from https://github.com/grpc/grpc-go/pull/8405.
Exporting this type will allow the registration of other resource type implementations. Currently this is in an internal package, and we will anyway get rid of this code once we migrate all our resource type implementations to use the new generic client API directly. This is *only* a temporary hack.
=> xdsclient: export genericResourceTypeDecoder

xds/internal/clients/xdsclient/channel.go
Some resource types do not have a `name` field in them. They rely on being wrapped in a `discovery.Resource` proto to give them a name. So when the xdsClient unwraps such a resource for validation purposes, it still needs to send the wrapped message bytes to the decoder.
=> xdsclient: preserve original bytes for decoding when the resource is wrapped

.github/workflows/pr-validation.yml
=> github: Restrict repo contents permissions to read-only in pr-validation

internal/xds/bootstrap/bootstrap.go, internal/xds/bootstrap/bootstrap_test.go, xds/internal/xdsclient/pool.go, xds/internal/xdsclient/pool/pool_test.go
Initially, there was [no error log](https://github.com/grpc/grpc-go/blob/947e2a4be2bac21c84b99114c12c40bb74860afe/internal/xds/bootstrap/bootstrap.go#L819-L829) when setting the fallback bootstrap config. The [GetConfiguration](https://github.com/grpc/grpc-go/blob/947e2a4be2bac21c84b99114c12c40bb74860afe/internal/xds/bootstrap/bootstrap.go#L588-L618) function would first attempt to read the bootstrap configuration from environment variables and then fall back to the configuration provided by the c2p resolver.
A [subsequent change](https://github.com/grpc/grpc-go/pull/7898/files#diff-8c0a0efa1bb340ffe5846ebebb64f9182dcbb1218d0a51a6b3d6d340072ab07e), which added an xDS client pool, modified this behavior. It read the bootstrap config within an init() function in clientimpl.go, preventing …
=> xds: Avoid error logs when setting fallback bootstrap config

internal/envconfig/envconfig.go, internal/resolver/dns/dns_resolver.go, internal/resolver/dns/dns_resolver_test.go
Fixes #8356
Note that there is no way to force TXT lookups happen for a specific channel.  If someone requests this feature, we can consider it at that time, but I don't imagine there will be demand for it.
RELEASE NOTES:
* dns: add an environment variable (`GRPC_ENABLE_TXT_SERVICE_CONFIG`) to provide a way to disable TXT lookups in the DNS resolver (by setting it to `false`).  By default, TXT lookups are enabled, as they were before this change.
=> dns: add environment variable to disable TXT lookups in DNS resolver

xds/internal/balancer/cdsbalancer/aggregate_cluster_test.go, xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
- xds/cdsbalancer: Fixes panic in cdsBalancer by correctly removing cds watchers for clusters no longer in the cluster tree.
In the code for `onClusterUpdate` after the cluster tree has been updated, we want to remove the watchers for clusters that are not currently in the tree. The existing [code](https://github.com/grpc/grpc-go/blob/aa57e6af6cbc8e1285315b338b092420f014c732/xds/internal/balancer/cdsbalancer/cdsbalancer.go#L533C2-L540C3) will always panic because of the error in condition. This change fixes the removal of unwanted watchers.
=> xds/cdsbalancer: correctly remove the unwanted cds watchers

internal/transport/http2_server.go, internal/transport/http_util.go, internal/transport/http_util_test.go
RELEASE NOTES:
* server: allow 0s grpc-timeout header values, which older gRPC-Java versions could send
=> Cherry-pick #8439 to v1.74 release branch

Documentation/grpc-auth-support.md, internal/envconfig/envconfig.go, internal/transport/http2_client.go, test/creds_test.go
Fixes: https://github.com/grpc/grpc-go/issues/8421
There are competing specifications around whether a method should be included in a JWT audience or not.  For example #4713 specifically excluded the method referencing https://google.aip.dev/auth/4111 whereas GCE IAP requires the full URI https://cloud.google.com/iap/docs/authentication-howto.
In order to facilitate both methods, we introduce a new environment variable, namely GRPC_AUDIENCE_IS_FULL_PATH, to allow the method stripping to be disabled.  This defaults to the existing behaviour of stripping the method, but can be set to avoid this.
RELEASE NOTES:
* credentials: Add support to disable gRPC method name stripping for JWT audience calculation when the environment variable `GRPC_AUDIENCE_IS_FULL_PATH` is set to true.
=> credentials: allow audience to be configured (#8421)

xds/internal/xdsclient/pool/pool_ext_test.go, xds/internal/xdsclient/pool/pool_test.go
This PR adds a test to catch deadlocks when using xDS to resolve the address of the xDS management server, resulting in the creation of nested xDS channels. The fix for the bug was initially submitted in https://github.com/grpc/grpc-go/pull/8011 and later in https://github.com/grpc/grpc-go/pull/8445.
Verified that the deadlock can be reproduced in 2-3 runs when the fix in https://github.com/grpc/grpc-go/pull/8445 is not included. The deadlock is resolved after including https://github.com/grpc/grpc-go/pull/8445.
=> xds: add a test for deadlocks in nested xDS channels

internal/transport/http2_server.go
https://github.com/grpc/grpc-go/pull/8439 introduced the change to return early when the deadline has already expired. This causes the server mutex to be held forever. 
Example failure in CI: https://github.com/grpc/grpc-go/actions/runs/16282058322/job/45973508273?pr=8437
=> transport: release mutex before returning on expired deadlines in server streams

clientconn.go, picker_wrapper.go, picker_wrapper_test.go, scripts/vet.sh, stats/opentelemetry/trace.go, stats/stats.go, stream.go, test/end2end_test.go, test/retry_test.go, test/stats_test.go
Fixes: #8453
This is part of a two-step change to eliminate the potentially-multiple calls for `PickerUpdated` as we do today. Other languages only have a maximum of one event for this, when the pick finally completed, but in Go we implemented it as a call every time the picker was updated. The plan is to implement the full change as follows:
1. Add DelayedPickComplete and make PickerUpdated a type alias of it, and change the semantics to match other languages (v1.x).
2. Delete PickerUpdated (v1.x+1)
RELEASE NOTES:
* stats: introduce `DelayedPickComplete` event, a type alias of `PickerUpdated`. This (combined) event will now be emitted only once per call, when a transport is successfully selected for the attempt.  OpenTelemetry metrics will no longer have multiple "Delayed LB pick …
=> stats: add DelayedPickComplete and follow correct semantics

security/advancedtls/advancedtls_integration_test.go, security/advancedtls/crl_provider_test.go
Fixes: #8468
This PR disables service configs in a flaking test. Using service configs results in a DNS lookup which may be the reason the test occasionally times out in CI. The test uses the target "localhost" to verify the server's TLS certificate. This change also avoids using deprecated `grpc.WithBlock` which is a no-op with `grpc.NewClient` and `fmt.Println` for debug logs in tests.
=> advancedtls: avoid txt lookups in test and use test logger instead of Printf

xds/internal/clients/xdsclient/xdsclient.go, xds/internal/clients/xdsclient/xdsclient_test.go
Fixes #8473
Matches the implementation of [grpc C++](https://github.com/grpc/grpc/blob/2ca9ac63ced7b77cf0eb885276fbedec1ab0bd10/src/core/xds/grpc/xds_bootstrap_grpc.cc#L67) and Envoy that makes the node ID optional.
RELEASE NOTES:
- xds: Revert to allowing empty node ID in xDS bootstrap configuration
=> xds: allow empty nodeID in bootstrap configuration

balancer/pickfirst/pickfirstleaf/metrics_test.go, balancer/pickfirst/pickfirstleaf/pickfirstleaf.go, balancer/rls/balancer.go, balancer/rls/metrics_test.go, balancer/weightedroundrobin/balancer.go, experimental/stats/metricregistry_test.go, stats/opentelemetry/client_metrics.go, stats/opentelemetry/csm/observability_test.go, stats/opentelemetry/e2e_test.go, stats/opentelemetry/internal/testutils/testutils.go, stats/opentelemetry/server_metrics.go, xds/internal/xdsclient/clientimpl.go
gRPC Go has been specifying units as non-standard values such as `call` and `endpoint` instead of using annotations like `{call}`. Based on the [metric naming conventions](https://ucum.org/ucum#section-Grammar-of-Units-and-Unit-Terms:~:text=%C2%A76-,curly%20braces,-%E2%96%A01%20The%20full) anything enclosed in curly braces is an annotation and in the absence of a prefix, the unit is `1`. The gRPC docs also mention that non-standard units need to be enclosed in curly braces: https://grpc.io/docs/guides/opentelemetry-metrics/#per-call-metrics.
This bug was caught due to a regression in the otel prometheus exporter: https://github.com/grpc/grpc-go/pull/8479
RELEASE NOTES:
* stats: fixed metric unit formatting by enclosing non-standard units like `call` and `endpoint` in curly braces to …
=> stats: change non-standard units to annotations

clientconn.go, credentials/alts/alts_test.go, credentials/credentials.go, credentials/tls.go, credentials/xds/xds_client_test.go, dialoptions.go, experimental/credentials/tls.go, resolver/resolver.go, scripts/vet.sh, security/advancedtls/advancedtls.go, test/balancer_test.go, test/creds_test.go
Before this change, credentials would ignore the channel's understanding of the server name if the user configured them to do so.  This is a mistake.  The credentials should use the channel's setting.  The channel already reads the credentials' preference and includes that in its logic.
A summary of how this worked:
- User creates credentials, optionally configuring a server name override at configuration.
- Optionally, user calls `creds.OverrideServerName`, which can/should be implemented such that it affects the server name override.  It does this by setting the `ProtocolInfo.ServerName` field that is returned by its `Info` method.
- gRPC has a list of precedence for determining the authority of the channel: `grpc.WithAuthority`; credentials; name resolver; channel default based on …
=> credentials: fix behavior of grpc.WithAuthority and credential handshake precedence

.github/workflows/testing.yml, cmd/protoc-gen-go-grpc/go.mod, examples/go.mod, gcp/observability/go.mod, go.mod, interop/observability/go.mod, interop/xds/go.mod, scripts/vet.sh, security/advancedtls/examples/go.mod, security/advancedtls/go.mod, stats/opencensus/go.mod, test/tools/go.mod
It's generally useful to have new-and-improved Go. One specific useful feature is `b.Loop()`, which makes benchmarking easier.
Encountered while working on #8510, as I was using `b.Loop()` in my benchmarks.
RELEASE NOTES:
* Minimum supported Go version is now 1.24
=> deps: bump go version to 1.24

internal/transport/handler_server.go, internal/transport/handler_server_test.go
Fixes: https://github.com/grpc/grpc-go/issues/8514
The mutex that guards the trailers should be held while copying the trailers. We do lock the mutex in [the regular gRPC server transport](https://github.com/grpc/grpc-go/blob/9ac0ec87ca2ecc66b3c0c084708aef768637aef6/internal/transport/http2_server.go#L1140-L1142), but have missed it in the std lib http/2 transport. The only place where a write happens is `writeStatus()` is when the status contains a proto. 
https://github.com/grpc/grpc-go/blob/4375c784450aa7e43ff15b8b2879c896d0917130/internal/transport/handler_server.go#L251-L252
RELEASE NOTES:
* transport: Fix a data race while copying headers for stats handlers in the std lib http2 server transport.
=> transport: ensure header mutex is held while copying trailers in handler_server

CONTRIBUTING.md
=> CONTRIBUTING.md: minor text tweaks for linters

stream.go, test/end2end_test.go
Partially addresses: https://github.com/grpc/grpc-go/issues/7286
This reverts commit https://github.com/grpc/grpc-go/commit/20bd1e7dfad3535675e3dff3d73fa894256f1f79
Changes:
- Modifies client.RecvMsg() so that successive calls after stream ends return io.EOF.
- Adds extra state to track calls to client.recvmsg(required to return Cardinality Violation only in case zero response)
RELEASE NOTES:
* client: Return status code INTERNAL when a server sends 0 response messages for a unary or client streaming RPC.
=> client: Roll-forward PR #8278(with changes): Restore the existing behavior to return io.EOF on repeated RecvMsg() calls for client-streaming RPCs

xds/internal/clients/lrsclient/lrsclient.go, xds/internal/xdsclient/clientimpl.go, xds/internal/xdsclient/clientimpl_loadreport.go, xds/internal/xdsclient/tests/loadreport_test.go
Original PR: #8483 
Related issue: https://github.com/grpc/grpc-go/issues/8474 
RELEASE NOTES:
- lrsclient:
- Fix a race condition where the `LRSClient` was not initialized at
creation time but it was being initialized at the time of calling the
`ReportLoad` function.
- 	Creating an `LRSClient` no longer requires a node ID.
=> Cherry pick #8483 into v1.75.x

internal/transport/http2_server.go, test/transport_test.go
Fixes: #8517
This change allows `t.closeStream()` to be executed even if the stream state is `done`. This is required to allow streams to be cancelled to timed out. See issue for detailed root cause.
RELEASE NOTES:
* server: Fix bug preventing streams from being cancelled or timed out when blocked on flow control.
=> transport: allow stream cancellation on the server when blocked on flow control

.github/pull_request_template.md, test/transport_test.go
Fix the following errors:
* only use one space to separate words
* use service codedgen import name for stream type
=> github,test: fix internal CI build

internal/transport/http2_server.go, test/transport_test.go
Original PR: #8528
Related issue: https://github.com/grpc/grpc-go/issues/8517
RELEASE NOTES:
* server: Fix bug preventing streams from being cancelled or timed out when blocked on flow control.
=> Cherry-pick #8528 to v1.74.x

internal/transport/http2_client.go, internal/transport/transport_test.go
Fixes: https://github.com/grpc/grpc-go/issues/8485
RELEASE NOTES:
* client: Ignore http headers with status 1xx and `END_STREAM` flag unset.
* client: Fail RPCs with status `INTERNAL` instead of `UNKNOWN` on receiving http headers with status 1xx and  `END_STREAM` flag set.
=> transport: handle 1xx HTTP status HEADERS at the client side

internal/xds/balancer/priority/ignore_resolve_now.go
Use new-style atomic APIs instead of the old ones in the `ignoreResolveNowClientConn` type.
The changes made in this PR improve the code in the following ways:
* Ergonomics: Method-based API vs function-based, no pointer management needed
* Safety: Type safety prevents mixing atomic/non-atomic operations, eliminates pointer errors
* Clarity: The `atomic.Uint32` type makes atomic intent explicit from declaration
=> priority: use new-style atomic APIs

internal/xds/xdsclient/xdsresource/unmarshal_eds.go, internal/xds/xdsclient/xdsresource/unmarshal_eds_test.go
Currently, the env var check for parsing HTTP CONNECT metadata (A86) is inside the function that parses custom metadata, `validateAndConstructMetadata`.
This PR moves the check to the endpoint and locality parsing functions, `parseEndpoint` and the top-level `parseEDSRespProto` which is where localities are parsed. This allows multiple env vars to control different custom metadata keys. We already support two custom metadata keys (A76 and A86) and we plan to support more (A83).
This PR also ensures that the custom metadata used for ring_hash key (A76) uses the recently added `StructMetadataValue` type. This ensures that metadata parsing happens only once.
Since the location of the env var check is moved, the tests are also restructured a little. This PR groups the custom metadata parsing …
=> xds: move env var check for HTTP CONNECT metadata parsing to endpoint and locality parsing functions

stats/opentelemetry/client_tracing.go, stats/opentelemetry/e2e_test.go, stats/opentelemetry/opentelemetry.go, stats/opentelemetry/trace.go
This introduced flakiness in a test - Test/TraceSpan_WithRetriesAndNameResolutionDelay
Failure: https://github.com/grpc/grpc-go/actions/runs/17614152882/job/50042942932?pr=8547
Related issue: https://github.com/grpc/grpc-go/issues/8299
=> Revert "stats/opentelemetry: record retry attempts from clientStream (#8342)"

internal/buffer/unbounded.go
This PR fixes a bug in the `Unbounded.Load()` method where the `closed` flag was not being set to `true` when the channel was closed.
In the `Load()` method, when the condition `b.closing && !b.closed` is met, the code closes the channel but doesn't update the `closed` flag. This creates an inconsistent state where:
- The channel is closed (no more data can be sent)
- But `b.closed` remains `false`
This inconsistency could potentially cause issues in code that relies on the `closed` flag to determine the buffer's state.
Added `b.closed = true` before `close(b.c)` in the `else if` branch of the `Load()` method to ensure the closed flag accurately reflects the buffer's state.
- **File**: `internal/buffer/unbounded.go`
- **Method**: `Load()`
- **Line**: 86
- **Change**: Added `b.closed = …
=> internal/buffer: set closed flag when closing channel in the Load method

credentials/credentials.go
The TODO comment with a Github user's name shows up in the [public godoc](https://pkg.go.dev/google.golang.org/grpc@v1.75.1/credentials#PerRPCCredentials). Since this is a stable API, changing it now doesn't seem feasible, so this change removes it completely.
=> credentials: Remove TODO from public godoc

internal/transport/flowcontrol.go
This PR aims to improve some variable names for better understanding. Before the change, it took time for users to think about why there's a `b` variable.
=> flowcontrol: change variable names for better understanding

balancer/pickfirst/pickfirst.go, balancer/pickfirst/pickfirst_ext_test.go, balancer/pickfirst/pickfirstleaf/pickfirstleaf.go
The new `pick_first`, which is the default, doesn't shuffle the addresses at all for resolver updates that are missing the `Endpoints` field. This change fixes that. Since [gRPC automatically sets the the missing `Endpoints`](https://github.com/grpc/grpc-go/blob/1059e84f885bf7ed65b3b1a4fbe914360d8ab5b1/resolver_wrapper.go#L136-L138), occurrence of this bug should be uncommon in practice.
RELEASE NOTES:
* balancer/pick_first: When configured, shuffle addresses in resolver updates that lack endpoints. Since gRPC automatically adds endpoints to resolver updates, this bug should only affect implementers of custom LB policies that use pick_first for delegation but don't forward the endpoints.
=> pickfirstleaf: Fix shuffling of addresses in resolver updates without endpoints

balancer/pickfirst/pickfirstleaf/pickfirstleaf.go, balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
Related issue: b/415354418
On connection breakage, the pickfirst leaf balancer enters idle and returns an `Idle picker` that calls the balancer's `ExitIdle` method only the first time `Pick` is called. The following sequence of events will cause the balancer to get stuck in `Idle` state:
1. Existing connection breaks, SubConn [requests re-resolution and reports IDLE](https://github.com/grpc/grpc-go/blob/bb71072094cf533965450c44890f8f51c671c393/clientconn.go#L1388-L1393). In turn PF updates the ClientConn state to IDLE with an `Idle picker`.
1. An RPC is made, triggering `balancer.ExitIdle` through the idle picker. The balancer attempts to re-connect the failed SubConn.
1. The resolver produces a new endpoint list, removing the endpoint used by the existing SubConn. PF removes the existing …
=> pickfirstleaf: Avoid getting stuck in IDLE on connection breakage

internal/xds/resolver/serviceconfig.go, internal/xds/resolver/serviceconfig_test.go, internal/xds/resolver/xds_resolver.go
This PR injects the dependencies of `configSelector` at creation time, instead of passing a reference to the `xdsResolver` and having the former directly access fields from the latter.
=> xds/resolver: minor cleanup in the config selector implementation

internal/xds/balancer/cdsbalancer/aggregate_cluster_test.go, internal/xds/balancer/cdsbalancer/cdsbalancer_security_test.go, internal/xds/balancer/cdsbalancer/cdsbalancer_test.go
Change the tests in xds cds balancer to use xds resolver instead of manual resolver
This change is being done as part of gRFC [A74 : xDS Config tears](https://github.com/grpc/proposal/blob/master/A74-xds-config-tears.md). This is to make sure the tests pass after the change too.
=> xds/cdsbalancer: change tests to use xds resolver

examples/features/interceptor/README.md
This PR changes the existing example to use fenced code blocks instead of backticks to show the interceptor signatures. This greatly improves how the document is rendered. The PR also changes the word `overload` to `override` because it is the latter that we are showcasing here, and Go does not support overloading anyways.
=> examples: improve interceptor example with better markdown formatting

examples/features/health/README.md
This PR fixes some markdown formatting issues flagged by an internal tool (when attempting to import recent changes into google3). It also makes minor improvements to the content.
=> examples/health: fix markdown formatting and improve content

balancer/pickfirst/pickfirst.go, balancer/pickfirst/pickfirst_ext_test.go, balancer/pickfirst/pickfirstleaf/pickfirstleaf.go, balancer/pickfirst/pickfirstleaf/pickfirstleaf_ext_test.go
Original PRs: #8610, #8615
RELEASE NOTES:
* balancer/pick_first:
* Fix bug that can cause balancer to get stuck in `IDLE` state on backend address change.
* When configured, shuffle addresses in resolver updates that lack endpoints. Since gRPC automatically adds endpoints to resolver updates, this bug should only affect implementers of custom LB policies that use pick_first for delegation but don't forward the endpoints.
=> Cherry pick #8610, #8615 to v1.76.x

balancer_wrapper.go
Addresses: https://github.com/grpc/grpc-go/issues/8590
When using the health producer for health checks, and the health package is not imported by the application, a no op health producer is used without logging any errors. This PR adds an error log similar to the one for the old health checks started by the subchannel.
https://github.com/grpc/grpc-go/blob/e35080456c7071b6d55887080ef78809c163640c/clientconn.go#L1475-L1481
=> client: Add error log for missing health package import during health check
