.travis.yml
The `language: go` statement already selects the latest stable release of Go.
=> Remove explicit Go version from Travis config.

.travis.yml
Travis' Go setup already sets up a suitable `GOPATH`, so there's no need to do it manually.
=> Remove manual GOPATH manipulation.

transport/control.go, transport/http2_client.go, transport/http2_server.go, transport/http_util.go
i) reduce write syscalls
go test -bench=. -cpu 1 -benchtime=20s
benchmark                    old ns/op     new ns/op     delta
BenchmarkClientSmallc1       129295        113599        -12.14%
BenchmarkClientSmallc8       107566        95731         -11.00%
BenchmarkClientSmallc64      115366        102583        -11.08%
BenchmarkClientSmallc512     106814        103891        -2.74%
ii) batch writs from different Goroutines if possible
go test -bench=. -cpu 4 -benchtime=20s
benchmark                      old ns/op     new ns/op     delta
BenchmarkClientSmallc1-4       269609        293830        +8.98%
BenchmarkClientSmallc8-4       49062         39327         -19.84%
BenchmarkClientSmallc64-4      46062         32099         -30.31%
BenchmarkClientSmallc512-4     53862         37108 …
=> Performance Optimization part 1

transport/control.go
That change broke the interop tests with C++ and Java. Will take a look tomorrow.
=> revert the change of flow control window size

transport/http2_client.go
This fix uses the last value to overwrite the previous values if the key is same. will revisit whether this is the prosper behavior.
=> Fix an ordering issue of creds

transport/http2_client.go
This was discovered when running the interop test with java. But the failure is actually because java does not follow the http2 spec. will file an issue to grpc-java shortly.
=> send an empty settings frame instead of a default when there is no setting needed.

transport/http2_server.go
=> fix small typo in HandleStreams error messages

transport/control.go, transport/http2_client.go, transport/http2_server.go, transport/transport_test.go
Reverts grpc/grpc-go#160
It is still needed in some cases. But there is an issue here which will be fixed in another pull request shortly.
=> Revert "remove restoreConn because it is not needed"

credentials/credentials.go
=> Export a credentials.TokenSource type that wraps an oauth2.TokenSource as a credentials.Credentials.

benchmark/grpc_testing/test.pb.go, examples/route_guide/proto/route_guide.pb.go, interop/grpc_testing/test.pb.go, server.go, test/grpc_testing/test.pb.go
will merge after the grpc codegen plugin is pushed.
=> Eliminate proto.Unmarshal in the generated code

clientconn.go, credentials/credentials.go, examples/route_guide/server/server.go, grpc-auth-support.md, interop/server/server.go, server.go, test/end2end_test.go, transport/http2_client.go, transport/transport.go, transport/transport_test.go
i) reverted the previous handshaker change which is not well-shaped;
ii) separate connection setup and security handshake on server to bring more flexbility, leading to breaking credential API change.
=> separate connection setup and security handshake on server

benchmark/benchmark.go, benchmark/benchmark_test.go
Streams are not safe for concurrent use,
so start a new stream for each goroutine.
Fixes #213.
=> Fix data race in benchmark_test.go.

benchmark/benchmark.go, benchmark/benchmark_test.go, benchmark/server/main.go
This avoids triggering firewall warnings on OS X,
and it's generally safer too.
=> Run benchmark server on localhost interface only.

call.go, trace.go
This will make client (outgoing) traces appear on /debug/requests.
There's some information lacking, but it's enough for now.
=> Add gRPC client-side integration with golang.org/x/net/trace.

stream.go
The methodFamily func already chops up the string, and the title should be the full method string too.
This now matches the non-streaming client trace.
=> Use full method for trace construction.

transport/http2_client.go
Without this, "broken deployments" that do not send trailers after their
response will cause Go clients to hang indefinitely (until a client-side
timeout or server-side slowloris protection kills the connection).
See the diagram at https://httpwg.github.io/specs/rfc7540.html#StreamStates and
the Data frame specification at https://httpwg.github.io/specs/rfc7540.html#DATA
for the relevant HTTP/2 specification.  See
https://github.com/grpc/grpc-common/blob/master/PROTOCOL-HTTP2.md#responses
for the specification that clients must be prepared for servers to omit
the trailers.
=> Honor END_STREAM flags in HTTP/2 Data frames.

transport/http2_client.go
Previously client calls would block indefinitely on the header channel, until the context was cancelled or the connection was terminated.
Fixes #261.
=> Close the header channel if a stream is reset while waiting for headers.

benchmark/benchmark.go, clientconn.go, examples/route_guide/client/client.go, interop/client/client.go, test/end2end_test.go
users have to set grpc.WithInsecure() DialOption when they want an insecure ClientConn. Fixes #307
=> Insecure ClientConn made explicit

clientconn.go, credentials/credentials.go, credentials/oauth/oauth.go, test/end2end_test.go
i) If you send oauth2 token via the credentials defined in credentials/oauth/oauth.go on a insecure ClientConn, you will get the runtime error grpc.ErrCredentialsMisuse. This is misuse;
ii) If you wrote your own custom credentials impl, you will get compilation failure because a new RequireTransportSecurity is added in this PR.
=> [IMPORTANT] Fail ClientConn creation if users try to transmit oauth2 token on a insecure connection.

examples/README.md
Fixed the install instructions for README.md in examples as it was left unchanged after a folder restructuring, making installing not work with the given command.
=> Fixed README.md in examples

examples/README.md
The last command seems to reflect the path used on the first public commit (which the helloworld.proto file was under  examples/helloworld/proto directory and then it was moved to examples/helloworld/helloworld/helloworld.proto)
=> Updated the path on the last command

transport/control.go, transport/http2_client.go, transport/http2_server.go, transport/http_util.go, transport/transport_test.go
The latter is now the official HTTP2 package for Go.
@bradfitz
=> Switch from github.com/bradfitz/http2 to golang.org/x/net/http2.

server.go, stream.go, trace.go
Record the description of the status returned by server RPC
handlers in request traces, and mark the trace as an error if the
status is not OK.
Install the trace into the Context passed to server handlers using
trace.NewContext, so that code in the server handlers can annotate the
trace using trace.FromContext.
=> grpc: make trace.FromContext work, and record handler status in traces

benchmark/grpc_testing/test.pb.go, examples/helloworld/helloworld/helloworld.pb.go, examples/route_guide/routeguide/route_guide.pb.go, health/grpc_health_v1alpha/health.pb.go, interop/grpc_testing/test.pb.go, server.go, test/grpc_testing/test.pb.go
Will submit concurrently with a gRPC codegen plugin push.
NOTE: This may break your build if you use your own codegen. Sorry for the breakage.
=> Enable payload tracing for unary rpc

rpc_util.go
Fixes a discrepancy between how unitary-unitary and streaming RPCs handle `codec.Unmarshal` errors:
https://github.com/grpc/grpc-go/issues/371
=> fix difference between unitary and stream codec error handling

rpc_util.go
=> Revert "fix difference between unitary and stream codec error handling"

rpc_util.go
Reading the header by hand avoids some allocations and improves the
performance of recvMsg.
Updated benchmarks:
```
benchmark                              old ns/op     new ns/op     delta
BenchmarkClientStreamc1-8              121497        128525        +5.78%
BenchmarkClientStreamc8-8              20963         20454         -2.43%
BenchmarkClientStreamc64-8             12370         11980         -3.15%
BenchmarkClientStreamc512-8            13542         13152         -2.88%
BenchmarkClientUnaryc1-8               240343        237528        -1.17%
BenchmarkClientUnaryc8-8               46075         44415         -3.60%
BenchmarkClientUnaryc64-8              32634         33386         +2.30%
BenchmarkClientUnaryc512-8             33065         32732         -1.01% …
```
=> Avoid some allocations in recvMsg

rpc_util.go, rpc_util_test.go
recvMsg was interpreting buf[1] as the payload format instead of buf[0];
since compressionNone (the only thing supported) == 0, recvMsg got lucky
for message lengths under 2^24, which has buf[1] == 0.
Fix the error, and ditch the constants in recvMsg. I think they were the
cause of the bug.
Also make encode fail more clearly if someone tries to transmit a
message that exceeds 2^32 bytes.
Fixes #399.
=> Fix decoding of message headers for messages with lengths >= 2^24.

rpc_util.go
The old code for encode used a bytes.Buffer, causing an unnecessary allocation. The new code allocates a raw []byte with the proper length and writes directly into it.
```
benchmark                   old ns/op     new ns/op     delta
BenchmarkEncode1B-8         1119          1060          -5.27%
BenchmarkEncode1KiB-8       3455          2104          -39.10%
BenchmarkEncode8KiB-8       10986         10266         -6.55%
BenchmarkEncode64KiB-8      83889         76763         -8.49%
BenchmarkEncode512KiB-8     719323        656051        -8.80%
BenchmarkEncode1MiB-8       1499583       1466814       -2.19%
benchmark                   old MB/s     new MB/s     speedup
BenchmarkEncode1B-8         7.15         7.54         1.05x
BenchmarkEncode1KiB-8       298.63       490.41       1.64x …
```
=> Remove an allocation when encoding messages

coverage.sh
Push to coveralls should only happen if option --coveralls is set.
=> removed automatic push to coveralls fixes grpc/grpc-go#436

clientconn.go
Fix a race condition in which a Conn's state is set to TransientFailure after Close() has been invoked – Close() should irrevocably set state to Shutdown.
=> Fix cc.Close() state race

naming/naming.go
which has zero impact to the rest of lib because the hooks have not been placed yet.
=> revise naming package a bit

credentials/credentials.go, peer/peer.go, test/end2end_test.go, transport/http2_client.go, transport/http2_server.go
Note that this PR removes credentials.NewContext(...) and credentials.FromContext(...) by placing AuthInfo as a member of peer info. If you use these APIs, please switch to the new one (end2end test in this PR serves as an example.).
=> Expose peer info on server side

examples/README.md
To install protoc, users should follow instructions in the README.md
file (INSTALL.txt has been removed because it misses crucial info
and confuses users).
=> Fix the link to protoc installation instructions.

stream.go
to avoid goroutine leaking in some cases
=> Specialize connection error handling

call.go, call_test.go, clientconn.go, rpc_util.go, rpc_util_test.go, server.go, stream.go, test/end2end_test.go, transport/http2_client.go, transport/http2_server.go, transport/http_util.go, transport/transport.go
which applies compression to all the message on the connection.
per-rpc compression (overwriting the compression decision on the connection) is not in this PR.
=> Support connection level compression

grpclog/logger.go
grpc's pluggable logger is not mutex-protected: added comments that it
should be changed only in init() functions.
=> Comment: explain concurrent access to grpclog.logger

test/end2end_test.go, test/race_test.go
The go race detector has a limit on how many goroutines it can track.
This test is only barely acceptable and the presence of any new
goroutines push it over the edge. Shorten this test is race mode.
=> test: shorten goroutine-heavy test in race mode

transport/http_util.go, transport/transport_test.go
The grpc-http2 transport doesn't validate hpack-decoded field names to be
valid http2 field names before checking their first byte. Had it verified
first and found that the empty string is illegal, this crash wouldn't happen,
but currently a malicious request can crash a gRPC server by sending an empty
hpack string.
=> transport: don't crash if peer sends an empty header field name

test/end2end_test.go
* test header and metadata separately
* fix an incorrect error message
* ignore optional header fields in response (date, trailer)
=> test: misc cleanups

rpc_util.go, server.go, test/end2end_test.go, transport/handler_server.go, transport/handler_server_test.go
This adds new http.Handler-based ServerTransport in the process,
reusing the HTTP/2 server code in x/net/http2 or Go 1.6+.
All end2end tests pass with this new ServerTransport.
Fixes grpc/grpc-go#75
Also:
Updates grpc/grpc-go#495 (lets user fix it with middleware in front)
Updates grpc/grpc-go#468 (x/net/http2 validates)
Updates grpc/grpc-go#147 (possible with x/net/http2)
Updates grpc/grpc-go#104 (x/net/http2 does this)
=> Add a ServeHTTP method to *grpc.Server

test/end2end_test.go, transport/handler_server.go, transport/handler_server_test.go, transport/http2_server.go, transport/transport.go
This change also:
* adds a new test with concurrent server sends, which exposed the
race. (the test failed with the race detector before, but now
passes)
* starts a cleanup of the end2end testing code, to be continued later.
but the cleanup was necessary to enable this new test to be clean
and not add more positional parameters.
* documents the concurrency expectations of the ServerTransport
interface, cleaning up some other nearby documentation in the
process.
Fixes grpc/grpc-go#551
=> Fix flakiness of TestCancelNoIO with http.Handler-based server transport

test/end2end_test.go
Filter expected log output by default, unless a flag is provided, or a
test fails.
This makes it possible to see unexpected things. Having noisy tests
makes it too easy to miss actual problems.
=> test: reduce end2end log spam

server.go
I'm using gRPC with TLS Certificate Authentication.  The default log messages are very hard to understand what went wrong.  Currently, you get:
`2016/02/23 11:01:59 grpc: Server.Serve failed to complete security handshake.`
This PR changes the logged message to something like this:
`2016/02/23 11:08:57 grpc: Server.Serve failed to complete security handshake from "127.0.0.1:49423": tls: failed to verify client's certificate: x509: certificate signed by unknown authority`
Improving the interface with Context (#547) is nice and I would love structed logging (#289), today it is very difficult to debug basic TLS client authentication issues -- all the client sees is a TLS alert for `bad certificate` in this case, so having the server log anything more is very helpful.
=> log error message and source address in handshake error

call.go, call_test.go, rpc_util.go, rpc_util_test.go, server.go, stream.go, test/end2end_test.go, test/servertester_test.go, transport/handler_server.go, transport/http2_client.go, transport/http_util.go, transport/transport_test.go
The http.Handler-based transport body reader was returning error types
not understood by the recvMsg parser. See #557 for some background and
examples.
Fix the http.Handler transport and add tests. I copied in a subset of
the http2 package's serverTest type, adapted slightly to work with
grpc. In the process of adding tests, I discovered that
ErrUnexpectedEOF was also not handled by the regular server
transport. Document the rules and fix that crash as well.
Unrelated stuff in this CL:
* make tests listen on localhost:0 instead of :0, to avoid Mac firewall
pop-up dialogs.
* rename parser.s field to parser.r, to be more idiomatic that it's an
io.Reader and not anything fancier. (it's not acting like type
stream, even if that's the typical concrete type)
* move 5 byte temp buffer into …
=> Fix crashes where transports returned errors unhandled by the message parser

.travis.yml
It's too noisy and not worth it. I don't like encouraging the code
coverage game, wherein people write bad tests to get points.
It's annoying to get a red X in the PR status when coverage dropped
by 1 line or 0.4%.
Good code review should be sufficient to verify we have both tests
and good tests.
=> Disable the code coverage checker.

call_test.go, transport/http2_client.go, transport/http2_server.go, transport/http_util.go
The Framer now has support for merging HEADERS+CONTINUATION frames.
This remove the frame merging & hpack state machine from grpc.
In addition to being more compliant with the spec, this also means
gRPC enforces the header list size, removing a DoS vector.
=> transport: use http2.Framer's MetaHeadersFrame functionality

internal/internal.go, server.go, test/end2end_test.go
Move the test-only methods to a new internal package so as to not
pollute the godoc, and to prevent people from using them. (Packages
named internal or under internal are private, and enforced by the go
tool)
=> Remove test-only methods from grpc package.

server.go
This simplifies the code that's used for wiring up the http.Handler-based
transport for testing. It's not used outside of tests.
http2.Server.ServeConn was added somewhat recently for other reasons and
I just realized it would simplify this code as well.
=> Simplify server setup when testing the http.Handler-based server transport

rpc_util.go
This will assert at build time that the generated code is compatible
with the grpc package that it is linked to. A future change in the
grpc plugin for protoc-gen-go will generate a line like
const _ = grpc.SupportPackageIsVersion1
This constant will be renamed in the future when incompatible changes
are made that require synchronised updates to grpc and protoc-gen-go.
=> Prepare for adding a compatibility marker to proto generated code.

transport/http_util.go
This reduces the number of system calls for reading network data,
providing a nice speedup when there are concurrent RPCs.
```
name                       old time/op    new time/op    delta
ClientStreamc1-8             37.4µs ± 1%    35.6µs ± 1%   -4.75%         (p=0.000 n=10+9)
ClientStreamc8-8             16.2µs ± 8%    14.7µs ± 2%   -9.28%        (p=0.000 n=10+10)
ClientStreamc64-8            12.5µs ± 2%    12.4µs ± 2%     ~            (p=0.590 n=9+10)
ClientStreamc512-8           13.7µs ± 2%    13.4µs ± 3%   -2.40%        (p=0.011 n=10+10)
ClientUnaryc1-8              88.4µs ± 1%    86.9µs ± 0%   -1.71%         (p=0.000 n=9+10)
ClientUnaryc8-8              41.9µs ± 1%    36.7µs ± 2%  -12.44%        (p=0.000 n=10+10)
ClientUnaryc64-8             27.8µs ± 1%    23.9µs ± 2%  -14.02% …
```
=> Use a bufio.Reader for input.

transport/transport.go
Storing an integer in an interface requires an allocation. Storing an
empty struct does not. This matches the pattern used for peer.NewContext
and metadata.NewContext.
=> transport: remove unnecessary allocation

call.go, call_test.go, stream.go
For example, if the error message contains "%v", then passing
StatusDesc() as the format string to Errorf() will replace "%v" with
"%!v(MISSING)".
=> Don't treat StatusDesc() as a format string.

.travis.yml
Currently, grpc-go is only built against go 1.4.x.
=> travis: build against go1.5.3, go1.6

transport/transport.go
Like #587 but without the last commit.
Updates #586.
@bradfitz
=> transport: performance improvements

call.go, stream.go
Both Invoke and SendMsg are stable API. And users can call them directly for various reasons (bypass encoding by sending a []byte as interface for example).
The `x is called by the generated code` comment is kind of misleading. It makes users to feel these funcs are designed to be called by generated code only.
=> remove unnecessary comment on invoke/sendmsg

transport/handler_server.go
This provides a substantial speed improvement with large payloads.
```
name                 old time/op    new time/op    delta
GRPCServeHTTP_1K-4      178µs ± 2%     177µs ± 1%     ~     (p=1.000 n=5+5)
GRPCServeHTTP_64K-4    1.30ms ± 3%    1.09ms ± 4%  -16.82%  (p=0.008 n=5+5)
name                 old speed      new speed      delta
GRPCServeHTTP_1K-4   11.5MB/s ± 2%  11.6MB/s ± 1%     ~     (p=1.000 n=5+5)
GRPCServeHTTP_64K-4   100MB/s ± 2%   121MB/s ± 4%  +20.26%  (p=0.008 n=5+5)
name                 old alloc/op   new alloc/op   delta
GRPCServeHTTP_1K-4     88.5kB ± 0%    93.9kB ± 0%   +6.16%  (p=0.008 n=5+5)
GRPCServeHTTP_64K-4     801kB ± 0%     791kB ± 0%   -1.16%  (p=0.008 n=5+5)
name                 old allocs/op  new allocs/op  delta
GRPCServeHTTP_1K-4        162 ± 0%       156 …
```
=> transport: allocate bigger slabs and reuse

transport/control.go, transport/transport.go
Also changes the receivers to pointers because:
- Implementing an interface using value receivers causes both pointers
and values to implement that interface; implementing an interface using
pointer receivers causes only pointers to implement the interface,
thereby providing better type safety.
- Wrapping any value other than an empty struct in an interface causes
the value to be heap-allocated; no additional allocations are therefore
caused by this change.
=> transport: replace isItem with a marker method

test/end2end_test.go
=> Temporarily disable handler-tls for TestHealthCheckOff due to #619

backoff.go, clientconn.go, rpc_util.go
The backoff function and parameters have been pulled up into an
interface `backoffStrategy`. The default parameters are now part of a
package variable `DefaultBackoffConfig`. The strategy is then plumbed
through `dialOptions`. As a result of this PR, the
maximum backoff delay can now be set using the `WithBackoffConfig` dial
option.
While the addition of strategy may seem premature, this allows one to
simply export `BackoffStrategy` and `WithBackoff` to allow arbirarily
configurable backoff strategies.
Signed-off-by: Stephen J Day <stephen.day@docker.com>
Closes #585
Note: once we've verified the interface, unit tests will be added.
=> backoff: allow configuration of backoff strategy

call_test.go, transport/http2_client.go
Occasionally Invoke() would let a message slip through when the context
is already canceled.
=> transport: do not create a Stream on a canceled context

backoff.go, backoff_test.go, clientconn.go, clientconn_test.go
Because most of the fields on `BackoffConfig` are unexported, correctly using the config requires copying from the default. This sets the defaults appropriately and falls back to a default if `MaxDelay` is negative or zero.
Signed-off-by: Stephen J Day <stephen.day@docker.com>
=> backoff: set default values on BackoffConfig

backoff.go, backoff_test.go, clientconn.go, clientconn_test.go
so that we can keep the receiver consistency of method.
quoted from https://golang.org/doc/faq#methods_on_values_or_pointers
_"Next is consistency. If some of the methods of the type must have pointer receivers, the rest should too, so the method set is consistent regardless of how the type is used. See the section on method sets for details."_
=> make setDefault(...) non-member function

test/end2end_test.go, transport/http2_client.go
fixes a goroutine leak in that case.
=> Close errorChan even when there is no pending I/O

transport/http2_client.go
to avoid the deadlock on a synchronous net.Conn (e.g. net.Pipe()).
Fixes #639
=> Start reader Goroutine earlier

transport/http2_client.go, transport/http2_server.go
This fixes a race condition that the connection pendingData could be deducted twice if there is a concurrent resetPendingData call (in closeStream).
fixes #670 (need verify)
trying to add a test.
=> Fix a race of onRead couting

Documentation/grpc-metadata.md
metadata.FromContext returns additional boolean value.
This fixes the example in metadata documentation.
=> Documentation: fix metadata.FromContext example

clientconn.go
Otherwise transportMonitor hangs around long enough after Close() that it
looks like a goroutine leak.
/cc @gyuho @xiang90
=> Interrupt retry Sleep() on client connection shutdown

server.go, server_test.go
If server.Stop() and server.Serve() race, Serve() can return without
closing the listener. This in turn can lead to clients timing out trying
to connect to a server that is neither accepting nor rejecting
connections.
=> Fix a listener leak when a server is stopped before it starts

server.go, test/end2end_test.go, transport/handler_server.go, transport/http2_client.go, transport/http2_server.go, transport/http_util.go
Fixes https://github.com/grpc/grpc-go/issues/457
This is incredibly useful to decide, e.g. on what behaviour to have. E.g. you can enable certain features based on the domain used by the caller.
* Added tests asserting `:authority` is there.
* Fixed a problem where users could provide an HTTP restricted field (such as `:authority`) mid-way, causing the stream to fail. These are now filtered out.
* Fixed https://github.com/grpc/grpc-go/issues/686 along the way, since it couldn't deal with metadata.
=> make :authority propagate to MD

PATENTS, backoff.go, clientconn.go
According to http://www.grpc.io/faq/, the project is called gRPC. It's already referred by that name in most places, except a few instances where it's still "GRPC". Fix those to have consistency.
I'm not sure if it's worth touching PATENTS file. https://github.com/grpc/grpc/blob/master/PATENTS also has it all upper case. But maybe both should be updated. Either way, if you prefer me to leave PATENTS file alone, let me know and I'll update this PR. Thanks.
=> Fix remaining instances of gRPC spelling.

clientconn.go, clientconn_test.go, test/end2end_test.go, transport/transport.go
Currently a grpc.ClientConn may have multiple underlying connections, which makes the former timeout semantics undefined when reconnecting. This pull request changed the semantics by applying the timeout set by grpc.WithTimeout to the initial ClientConn dialing only.
fixes #694
=> [Notice] Change the semantics of grpc.WithTimeout DialOption

clientconn.go
Leaks a goroutine on dial timeout if unbuffered.
/cc @xiang90
=> clientconn: buffer waitC on Dial goroutine

clientconn.go, clientconn_test.go, credentials/credentials.go, credentials/oauth/oauth.go, examples/route_guide/client/client.go, interop/client/client.go, server.go, transport/http2_client.go, transport/transport.go
* PerRPCCredentials is used in each RPC
* TransportAuthenticator is used to setup connection
=> [API revision] Separate TransportAuthenticator and PerRPCCredentials

benchmark/grpc_testing/services.pb.go, examples/helloworld/helloworld/helloworld.pb.go, examples/route_guide/routeguide/route_guide.pb.go, health/grpc_health_v1/health.pb.go, interop/grpc_testing/test.pb.go, rpc_util.go, stress/grpc_testing/metrics.pb.go, test/grpc_testing/test.pb.go
This PR is to make the support package version consistent with `protoc-gen-go`.
It will be merged when `protoc-gen-go` gets updated, and may cause building error like:
```
undefined: grpc.SupportPackageIsVersion2
```
Please update `protoc-gen-go` and recompile proto files if building fails.
=> Change SupportPackageIsVersion, may cause building failure

server.go
The listener can be closed twice: in Close and in Serve. It might lead to
pretty bad things, for example, https://golang.org/src/net/unixsock_posix.go#L340
can delete a file which created by another listener.
=> server: close only non-closed listeners

credentials/credentials.go
The first endpoint will set the ServerName which will then be used by
the second endpoint, causing the transport to reject the second endpoint
since the server cert won't match the server name.
=> credentials: don't overwrite ServerName in given config

transport/http2_server.go
This error is just being swallowed currently.
=> transport: add missing log line

clientconn.go, test/end2end_test.go, transport/go16.go, transport/http2_client.go, transport/pre_go16.go, transport/transport.go, transport/transport_test.go
This sometimes manifests as a leaked goroutine when the network stack is stressed on OS X. See https://github.com/cockroachdb/cockroach/issues/7524.
cc @petermattis @bdarnell
=> cancel outgoing net.Dial when ClientConn is closed

clientconn.go, test/end2end_test.go
This maintains cancellation for the default dialer, but external users
will have to opt in via a future API.
@broady @iamqizhao
=> WithDialer doesn't support cancellation

transport/transport.go, transport/transport_test.go
- Add server.stop() to one transport test
- Prioritize ctx.Done() in wait() (so that canceled rpcs will show timeout errors)
=> fix some bugs

transport/transport.go, transport/transport_test.go
Reverts grpc/grpc-go#799
The change for prioritizing ctx.Done() in proceed is incorrect.  I will have a new PR to replace this one.
=> Revert "fix some bugs"

call.go, call_test.go, rpc_util.go, rpc_util_test.go, server.go, stream.go, test/end2end_test.go
Make it consistent with Java and C++ impl.
also fixes #785 
TODO: client side memory guard.
=> Limit the max request size to be accepted

clientconn.go, credentials/credentials.go, test/end2end_test.go, transport/go16.go, transport/go17.go, transport/http2_client.go, transport/transport.go, transport/transport_test.go
This is a minor breaking change to `TransportCredentials`, however
it should not be a problem in practice as not many users are using
custom implementations. In particular, users of `NewTLS` will not
be affected.
This change also replaces the earlier `Timeout` and` Cancel` fields
with a `context.Context`, which is plumbed all the way down from
`grpc.Dial`, laying the ground work for a user-provided context.
Originally motivated by https://github.com/cockroachdb/cockroach/issues/7793.
=> Plumb context into ClientConn dialing and ClientHandshake of credentials.

test/end2end_test.go
=> Temporarily disable handler-tls for TestClientStreamingError due to #619

call.go, clientconn.go, stream.go, test/end2end_test.go, transport/http2_client.go, transport/http2_server.go, transport/transport.go
fixes #622 
- `Dial()` with `withblock()` will return error.
- In the case of bad certificates, it will return the original error received from creds
- `FailFast` RPCs will return an RPC error (containing error string received from creds)
- `Non-FailFast` RPCs
- If balancer is not provided, will return an RPC error (containing error string received from creds)
- If balancer is provided, will block until timeout
=> Return error on bad certificates

credentials/credentials.go, transport/http2_client.go
Removes the responsibility of closing the underlying connection in tlsCreds.ClientHandshake().
=> Cleanup conn.Close() handling in newHTTP2Client()

transport/http2_client.go
I'm not sure if this fix is the right approach, but it fixes the issue we're seeing with our test. I'm happy to add a grpc-specific test if someone can point me towards similar tests that I can base a new one on.
=> Retry transport creation when ClientHandshake returns EOF

clientconn.go, clientconn_test.go
This change is motivated by work on CockroachDB – we need to have control of cancelation for dialing using `WithBlock`.
+cc @tamird
=> Implement DialContext to afford caller option of managing cancelation

clientconn.go, clientconn_test.go
fixes #856
@MakMukhi will add the tests in another pull request.
=> Detach user-passed context (via DialContext(...)) with the context of ClientConn

clientconn.go
Prior to this change, it was possible for `DialContext` to return
`(nil, err)` without properly closing the `ClientConn`, resulting in an
unavoidable leak of the `resetAddrConn` goroutine.
@iamqizhao another critical bug.
=> Avoid goroutine leak in clientconn

test/end2end_test.go
provide the info for debugging potential flakiness.
=> Add an err logging to testFailFast

test/end2end_test.go, transport/http2_client.go
A bit paranoid, but should help mitigate more issues like #859.
=> transport: robustly detect temporary errors

call.go, rpc_util.go, rpc_util_test.go, server.go, stream.go, test/end2end_test.go, transport/handler_server.go, transport/http2_client.go, transport/http2_server.go, transport/http_util.go, transport/transport.go, transport/transport_test.go
#873
* Service handler should get RPC errors rather than StreamError or ConnectionError
* When context timeout happens, service handler should get deadline exceeded error (not true if connection is disconnected before context timeout)
=> Fix server side errors

call.go, clientconn.go, interceptor.go, stream.go, test/end2end_test.go
=> Support client side interceptor

transport/http2_client.go, transport/transport_test.go
If a client receives an invalid header (invalid content-type for example), the client should fail immediately with an error (error code FailedPrecondition in the case of invalid content-type).
=> Close headerChan if processHeaderField sets error

balancer.go, clientconn.go, clientconn_test.go
So context cancel() also stops the balancer initialization.
=> Move balancer initialization into a goroutine

clientconn.go
Structs should use %v; %q only makes sense for strings, chars, etc.
=> Log grpc.Address objects with %v, not %q

metadata/metadata.go, metadata/metadata_test.go
Previously metadata.NewContext(ctx, md) replaces whatever metadata in
ctx with md.
This patch merges the old metadata with md before returning the new
context.
Fixes #902.
=> Add metadata.Join

credentials/credentials.go, credentials/credentials_test.go, test/end2end_test.go
Add two functions `Clone()` and `OverrideServerName()` to the interface `TransportCredentials`.
This change should have no influence if you don't implement your custom credentials.
This is in preparation for grpclb.
=> [API revision] Change TransportCredentials interface

transport/http_util.go, transport/http_util_test.go
=> Use strconv.ParseUint in decodeGrpcMessage to support non-ascii desc

.travis.yml
golint stopped supporting go1.5
https://github.com/golang/lint/issues/246
=> Skip golint in go 1.5

grpclb/grpclb_test.go
due to https://github.com/golang/go/issues/15976.
=> Fix a test flakiness in go1.7

backoff.go
Removed the unused named return parameter from `BackoffConfig`'s `backoff` method.
=> Removed the unused named return parameter from `BackoffConfig`'s `backoff` method

examples/helloworld/greeter_server/main.go
Added an error handling to `examples/helloworld/greeter_server/main.go` because `*grpc.Server`'s `Serve` method returns an error and it should be handled.
=> Add an error handling to "greeter_server"

server.go, stream.go, test/end2end_test.go, transport/http2_server.go, transport/transport.go
Add `grpc.SetHeader()` and `ServerStream.SetHeader()` so that server interceptors can set header metadata.
fixes #733
=> [API revision] Add SetHeader

server.go
The `Serve` exits when the listen queue is full in my case, and I don't think it's an expected behavior.
I copy the code from golang's [http Serve](https://github.com/golang/go/blob/214bf6809791170b88b41249850f2f01534725c4/src/net/http/server.go#L2273), which is more reasonable.
Any thoughts?
=> fix server exit due to a temporary network error

test/end2end_test.go
Some end2end tests using ServeHTTP failed with DATA RACE:
https://travis-ci.org/grpc/grpc-go/jobs/169080239
https://travis-ci.org/grpc/grpc-go/jobs/169080240
https://travis-ci.org/grpc/grpc-go/jobs/169080236
probably due to the recent change https://github.com/golang/net/commit/3bafa3320efdf0c95d056586aa9abdd05ad72ee1
It seems http2 package is not stable enough.
Disable tests for ServeHTTP in end2end tests until it's stable.
=> Disable handler-tls in end2end tests

call.go, test/end2end_test.go
This may lead to miscounting of the streams quota for unary rpcs.
=> Use the correct error in defer call

README.md
might be good to add a suggestion, with the differences seen in benchmarks
=> add note in readme pre-req section to get the latest go version

clientconn.go, clientconn_test.go, reflection/serverreflection.go, test/end2end_test.go, transport/http2_client.go, transport/transport.go
to control if gRPC should fail on non-temporary dial error
fixes #984
With #974, gRPC won't retry connection if dialer returns non-temporary error. So if a server is restarted, the client won't try to connect again. We think this is not friendly to most of users and bring them more burden to close and reopen client connections.
This pull request rolls the behavior back to the state before #974 and introduces a new dial option to fix #974 (which means the users need to explicitly specify this option to stop reconnecting on a non-temp dial error).
=> add FailOnNonTempDialError

clientconn_test.go
Caused by https://code.googlesource.com/gocloud/+/8503b8f3a332a79fad52ec608c6fab1dd10d963b
This commit makes cloud.google.com/go/internal depend on github.com/googleapis/gax-go, so we have:
```
package google.golang.org/grpc (test)
imports google.golang.org/grpc/credentials/oauth
imports golang.org/x/oauth2/google
imports cloud.google.com/go/compute/metadata
imports cloud.google.com/go/internal
imports github.com/googleapis/gax-go
imports google.golang.org/grpc
```
https://travis-ci.org/grpc/grpc-go/jobs/176575295
This PR removes the dependency of oauth from clientconn_test.
=> fix a circular dependency in clientconn_test

Documentation/grpc-auth-support.md
`WithPerRPCCredentials` returns DialOption, so I think it should be passed to `Dial` not `WithTransportCredentials`
this makes user confused, please merge this pr, thank you :)
=> correct errors in documentation

grpclog/glogger/glogger.go
This way, log messages will show the proper location where the log
statement originated, instead of "glogger.go:67" or something like that.
=> Use InfoDepth/FatalDepth in glogger.go

test/end2end_test.go, transport/control.go, transport/http2_client.go, transport/http2_server.go
Remove the add and cancel methods of quotaPool. Their use is not required, and
leads to logical races when used concurrently from multiple goroutines. Rename
the reset method to add.
The typical way that a goroutine claims quota is to call the add method and
then to select on the channel returned by the acquire method. If two
goroutines are both trying to claim quota from a single quotaPool, the second
call to the add method can happen before the first attempt to read from the
channel. When that happens the second goroutine to attempt the channel read
will end up waiting for a very long time, in spite of its efforts to prepare
the channel for reading.
The quotaPool will always behave correctly when any positive quota is on the
channel rather than stored in the struct field. In the …
=> transport: fix logical race in flow control

stress/client/main.go
The stress client can now run more of the test that the interop client has implemented. This standardizes it with the cpp stress client (minus the compression tests, which go still does not have)
=> Add Available Interop Tests to Stress Client

codegen.sh, coverage.sh
=> FIX: use /usr/bin/env bash in shebang

interop/test_utils.go, stress/client/main.go
=> Set failfast to false for stress tests. Also wait for all rpcs are done before ending the test.

credentials/credentials.go, credentials/credentials_test.go
=> ClientHandshake to return AuthInfo

interop/test_utils.go
During internal tests, some large message can be cut off. So rearranging message to show error string first.
=> Fix and modify logging.

benchmark/benchmark.go
after https://github.com/grpc/grpc-go/pull/940 and https://github.com/grpc/grpc-go/pull/1010
Protobuf streaming QPS test server's memory alloc profile looks like:
(showing functions that alloc a significant amount of flat memory)
(two 32-core master clients to one 32 core server with #940 and #1010 on top of latest master, QPS was 736K)  
```
6978.25MB of 7017.41MB total (99.44%)
Dropped 89 nodes (cum <= 35.09MB)
flat  flat%   sum%        cum   cum%
1208.06MB 17.22% 17.22%  1208.06MB 17.22%  golang.org/x/net/http2.parseDataFrame
1188.05MB 16.93% 34.15%  4376.64MB 62.37%  google.golang.org/grpc/benchmark.(*testServer).StreamingCall
1184.55MB 16.88% 51.03%  1184.55MB 16.88%  google.golang.org/grpc/transport.(*Stream).write
815.52MB 11.62% 62.65%  1628.05MB 23.20% …
```
=> remove proto object allocs on streaming benchmark server

interop/http2/negative_http2_client.go, interop/test_utils.go
These tests are for the new Http/2 test server (https://github.com/grpc/grpc/pull/8900/). They are designed to test client behavior when the server sends unexpected responses during rpcs.
cc @ericgribkoff @makdharma
=> Add Go Client to Test Negative HTTP2 Conditions

clientconn.go, clientconn_test.go, transport/transport.go
The :authority pseudo-header for a gRPC Client defaults to the host
portion of the dialed target and can only be overwritten by providing a
TransportCredentials. However, there are cases where setting this header
independent of any tranport security is valid. In my particular case,
in order to leverage Envoy for request routing, the cluster/service name
must be provided in the :authority header. This may also be useful in a
testing context.
This patch adds a DialOption to overwrite the authority header,
even if TransportCredentials are provided (I'd imagine you'd only ever
need to specify one or the other).
/cc @mattklein123
=> Add DialOption to overwrite :authority pseudo-header

credentials/credentials_util_go18.go, credentials/credentials_util_pre_go17.go
go1.8 now has native support for tls.Clone() so for 1.8+ use that for
credentials.cloneTLSConfig.
=> Use tls.Config.Clone() for go1.8

rpc_util.go, transport/handler_server_test.go, transport/transport.go
This produces better human-readable error messages.
=> Use codes.Code.String() rather than logging integers

clientconn.go
=> Add comment explaining why cancel is not called in success path after client transport is created

transport/http2_client.go, transport/http2_server.go
It looks like current transport doesn't account for padding when consuming/updating the flow control window. This accounts for it, maybe another option is to fail fast.
I'd like to add a large interop test for this situation. For now reproduced the sender deadlock locally by using `http2.Framer.WritePadded` on client, accounting for padding in client's send quota, and running a long-streaming benchmark which gets QPS 0.
cc @ejona86 @MakMukhi 
update: btw there's WIP for a generic interop test for this, but for the main grpc repo, separate from this pr
=> account for padding in flow control, when received frame uses it

call.go, clientconn.go, stream.go, test/end2end_test.go
=> Client should have a check on maximum size of received message size.

clientconn.go, rpc_util.go, transport/http2_client.go, transport/http_util.go
=> Add grpc.Version string and use it in the UA

grpclb/grpclb.go, grpclb/grpclb_test.go
- InitialLoadBalanceRequest
- Addresses in server list response are []byte in the format of net.IP, not string
=> grpclb initial request and server address format

test/end2end_test.go, transport/http_util.go
The user-agent returned to user will be `"user-custom-ua  grpc-go/<version>`".
The old behavior strips out `"grpc-go/<version>"` and only returns `"user-custom-ua"`.
=> Behavior change: do not strip out gRPC user-agent

benchmark/worker/benchmark_client.go, benchmark/worker/benchmark_server.go, benchmark/worker/main.go, benchmark/worker/util.go
Adds user and system cpu time to go benchmarks. A run that shows the number results is scheduled in https://grpc-testing.appspot.com/job/gRPC_performance_adhoc/
The results I got locally showed a lot more cpu spent on the client. cc @ctiller
=> get more metrics from go benchmark servers

rpc_util.go, test/end2end_test.go
=> Bug fix(Issue#1141): Check if peer is nil before trying to derefer it.

call.go, call_test.go, rpc_util.go, rpc_util_test.go, server.go, stats/stats.go, stats/stats_test.go, status/status.go, status/status_test.go, stream.go, test/end2end_test.go, transport/handler_server.go, transport/handler_server_test.go, transport/http2_client.go, transport/http2_server.go, transport/http_util.go, transport/transport.go, transport/transport_test.go
Fixes #1122 
If an error implemented by the status package is returned from a service
handler, the server will transmit a rich status message in the
"grpc-status-details-bin" trailing metadata field if any detailed data is
attached to the error.  Client-side, we will decode them if present in the
server's response and return them to the user code performing the RPC.
This is backward compatible with the existing errors supported by the grpc
package.  However, the grpc.Errorf, grpc.Code and grpc.ErrorDesc functions for
managing errors are now deprecated; status.Errorf and status.FromError should
be used instead on the server and client respectively.
=> Add status package for reporting gRPC status and errors

transport/transport.go
It is not thread-safe to call context.String() on any context with a
stream value since valueCtx will use %#v to access all of the Stream
fields without holding a lock. Instead, use "<nil>" as the GoString.
=> transport: hide Stream string when stored in context

Documentation/grpc-metadata.md, grpclb/grpclb_test.go, interop/test_utils.go, metadata/metadata.go, stats/stats_test.go, test/end2end_test.go, transport/handler_server.go, transport/http2_client.go, transport/http2_server.go
This will prevent the incoming RPCs' metadata from appearing in outgoing RPCs
unless it is explicitly copied, e.g.:
incomingMD, ok := metadata.FromContext(ctx)
if ok {
ctx = metadata.NewContext(ctx, incomingMD)
}
Fixes #1148
=> Separate incoming and outgoing metadata in context

transport/http_util.go
`DataFrame` structs account for slightly more than 1GB of allocs on the streaming QPS benchmark, but the framer can be configured to reuse them. Details in https://github.com/golang/go/issues/18502.
=> opt in to frame reuse on the framer to reduce garbage

stats/stats_test.go, stream.go
So that if user don't call streaming RPCs' last recv (which returns io.EOF), handling stats.End will still be called.
=> Move handling stats.End to clientStream.finish()

grpclb/grpclb.go, grpclb/grpclb_test.go
when the first balancer disconnects.
If grpclb gets 2 resolved addresses: balancer1 and balancer2. When balancer1 disconnects, grpclb should automatically start to use balancer2.
=> grpclb should connect to the second balancer

examples/gotutorial.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
=> Fix broken headings in Markdown files

stream.go, test/end2end_test.go
=> Make sure all in-flight streams close when ClientConn.Close() is called.

metadata/metadata.go, metadata/metadata_test.go, test/end2end_test.go, transport/handler_server.go, transport/http2_client.go, transport/http2_server.go, transport/http_util.go, transport/http_util_test.go
This change ensures consistency for the user when accessing metadata values: they are never encoded except when sent on the wire.  Previously, they would appear encoded to client code, but not to server code.  As such, this represents a behavior change, but one unlikely to affect user code, as it's unusual to inspect the metadata after setting it.
Fixes the remaining aspect of #1148 not fixed by #1157.
=> Never encode binary metadata within the metadata map

transport/http_util.go, transport/http_util_test.go
=> Use unpadded base64 encoding for binary metadata headers; handle padded or unpadded input

server.go
ServerOption panics when fields that have been manually set are
subsequently set again.  The message verbiage of `X has been set` is
unclear since `has been set` without an adverb like `already` does not
correctly convey that the fields are set-once and were previously set.
At the worst, the original verbiage `X has been set` could imply that
the new value would have been acceptable but another error occurred.
We discovered this while conducting a code survey for implementing
extensible stubs and uniform inbound interception API.
=> grpc: make ServerOption panic messages more clear.

transport/http2_server.go
There's currently a TODO instead of logging the error when calling `inTapHandle` fails in `http2Server.operateHeaders`. This PR logs the actual returned error.
=> Log the actual error when inTapHandle fails in http2Server

balancer.go, clientconn.go
This can only occur due to programmer error, but is quite confusing when it does.
Here's an example that triggers it:
```go
package main
import (
"google.golang.org/grpc"
"google.golang.org/grpc/naming"
)
type resolver struct {
}
// Resolve creates a Watcher for target.
func (resolver) Resolve(target string) (naming.Watcher, error) {
return &watcher{addr: target}, nil
}
type watcher struct {
addr string
}
func (w *watcher) Next() ([]*naming.Update, error) {
if w.addr == "" {
select {}
}
addr := w.addr
w.addr = ""
return []*naming.Update{{Addr: addr}}, nil
}
func (w *watcher) Close() {}
func main() {
balancer := grpc.RoundRobin(&resolver{})
_, err := grpc.Dial("127.0.0.1:1234", grpc.WithBalancer(balancer), grpc.WithInsecure())
if err != nil {
panic(err)
}
err = balancer.Close()
if err != …
```
=> Ensure that RoundRobin.Close() does not panic.

transport/http2_client.go, transport/http2_server.go
this is a follow-up to https://github.com/grpc/grpc-go/pull/1076 and a tentative bug fix
WIP on tests to show this, but I'm pretty certain there's room for an "over-read" of flow control right now, in the case that padding is used and a frame is received after stream state switches to "done" (connection 
then reads `(total_frame_size - data_length) + total_frame_size` (where `total_frame_size - data_length` is length of "padding section" in data frame
=> tentative fix to a possible over-read from flow control

rpc_util.go, rpc_util_test.go
This change saves a lot of memory by reusing the underlying
`gzip.{Writer,Reader}`, which allocates up to 1.4mb at every instanciation
according to [1]. This was fixed by adding a Reset method by to the
object at [2].
The amount of memory (and GC time) saved is pretty high, as reported by
`pprof` for the benchmarks below:
```
flat  flat%   sum%        cum   cum%
28.33GB 85.70% 85.70%    32.74GB 99.05%  compress/flate.NewWriter
flat  flat%   sum%        cum   cum%
19.39MB 16.74% 16.74%    22.07MB 19.05%  compress/flate.NewWriter
```
And the benchmarks:
```
benchmark                           old ns/op     new ns/op     delta
BenchmarkGZIPCompressor1B-4         215170        22291         -89.64%
BenchmarkGZIPCompressor1KiB-4       225971        27213         -87.96% …
```
=> Use pooled gzip.{Writer,Reader} in gzip{Compressor,Decompressor}

call.go, stats/handlers.go, stats/stats.go, stats/stats_test.go, stream.go, transport/http2_client.go, transport/transport.go
So that the context for stats handlers will have the other information as normal contexts.
Also added FailFast to TagInfo in case stats handlers care about FailFast but don't want to handle begin stats.
=> Calling handleRPC with context derived from the original

transport/transport.go
Addresses https://github.com/grpc/grpc-go/issues/1231
Perhaps encapsulating this behavior in a circular `queue` object and using that instead of direct slice manipulation would be the way to go in a future refactoring.
=> Eagerly set a pointer to nil to help GC

transport/handler_server.go
Proposed fix for #1111. I've already signed the CLA for another Google project (Camlistore).
I'm not aware of a golang construct which can completely guarantee the out chan won't be written to after the closed chan is closed but a nested select like this makes the window when that can happen way smaller. Specifically this change fixes the panic in #1111. Suggestions for improvements?
=> fix server panic sending to closed stream #1111

proxy_test.go, test/end2end_test.go
fixes #1058 
The reason for using "localhost" is #1067.
=> call listen with "localhost:port" instead of ":port" in tests

.travis.yml, benchmark/benchmark_test.go, clientconn_test.go, server.go, test/end2end_test.go
staticcheck is a powerful static linter. See https://github.com/dominikh/go-staticcheck.
@iamqizhao
=> travis: add staticcheck

credentials/oauth/oauth.go
jwt.Config.TokenSource returns a reusable TokenSource; we should re-use it to avoid sending a new request every time we need to use the token.
=> Reuse TokenSource

rpc_util.go, rpc_util_test.go
=> Implement `EmptyCallOption`

grpclb.go
=> grpclb balancer.Close() should not panic if called more than once

clientconn.go, server.go
When timeout is not hit `time.After` will leak unnecessary timer, so
it's better to stop timer explicitly.
=> clientconn, server: replace time.After with time.NewTimer

benchmark/benchmark_test.go
the default setting of MaxConcurrentStreams is 100
=> add MaxConcurrentStreams to benchmark_test when start the server

examples/route_guide/README.md, examples/route_guide/client/client.go, examples/route_guide/server/server.go
route_guide.proto used to be in a directory called proto. It was renamed
to routeguide but the code/README still referred to the previous
directory name.
=> Update references to route_guide.proto to use new directory name

call.go, rpc_util.go, server.go, stream.go, test/end2end_test.go
=> Server shouldn't Fatalf in case it fails to encode.

transport/http2_client.go, transport/http2_server.go
If `s.Val` is less than `t.streamSendQuota`, subtraction can result in a very big number due to overflow (both fields are `uint32`), effectively giving the stream a lot of quota to send data while its peer is expecting otherwise.
=> Avoid uint32 overflow when applying initial window size setting

transport/control.go, transport/http2_client.go, transport/http2_server.go
This is the last PR to further optimize for the benchmark simulating high latency networks and sending large messages. 
Note the original benchmark was flawed and has been revamped by @dfawley,
The final results are as follows:
```
Duration	Latency	Proto
6.970243ms	0s	GRPC
3.980085ms	0s	GRPC
4.13913ms	0s	GRPC
5.070389ms	0s	GRPC
3.96764ms	0s	GRPC
4.835682ms	0s	GRPC
5.500948ms	0s	GRPC
3.576878ms	0s	GRPC
4.252281ms	0s	GRPC
4.523893ms	0s	GRPC
17.831435ms	0s	HTTP/2.0
8.868534ms	0s	HTTP/2.0
8.8657ms	0s	HTTP/2.0
8.948182ms	0s	HTTP/2.0
7.335248ms	0s	HTTP/2.0
8.527652ms	0s	HTTP/2.0
8.085997ms	0s	HTTP/2.0
5.296444ms	0s	HTTP/2.0
7.930056ms	0s	HTTP/2.0
7.835599ms	0s	HTTP/2.0
16.513759ms	0s	HTTP/1.1
5.388497ms	0s	HTTP/1.1
6.687598ms	0s	HTTP/1.1
4.95173ms	0s	HTTP/1.1
4.838996ms	0s	HTTP/1.1
4.62064ms	0s …
```
=> Piggyback window updates for connection with those of a stream.

test/end2end_test.go
Parital fix for #1255. However, we still need to figure out why the 1 second wasn't enough.
=> Deflake TestFlowContolLogicalRace

transport/transport.go
Add additional nonblocking select clause that would
check if the header is available and return it if it is.
Current implementation of transport.go Stream Header often
doesn't return header, but a cancel error even though
the top level context is not canceled and the rpc
is successful and a header is actually available.
It's caused by the fact that select can choose any
"ready" channel.
Retrieving headers is flaky. With this fix, headers
are consistently retrieved for successful rpcs.
=> Return header in Stream.Header() if available

grpclb.go, grpclb/grpclb_test.go
Add square brackets to ipv6 addresses, otherwise net.Dial() and
net.SplitHostPort() will return too many colons error.
=> Support ipv6 addresses in grpclb

transport/http2_client.go, transport/transport_test.go
This patch writes client-side error before closing the active stream
to fix blocking `RecvMsg` issue on `grpc.ClientStream` [1].
Previous gRPC client stream just exits on `ClientTransport.Error` [2].
And latest gRPC added another select case on client connection context
cancel [3]. Now when client stream closes from client connection context
cancel, it calls `CloseStream` with `ErrClientConnClosing` error. And then
the stream gets deleted from `*http2Client.activeStreams`, without processing
the error [4]. Then in-flight `RecvMsg` call on this client will block on
`*parser.Reader.recvMsg` [5].
In short,
1. `ClientConn.Close`.
2. in-flight streams will receive case `<-cc.ctx.Done()` https://github.com/grpc/grpc-go/blob/master/stream.go#L253-L255.
3. …
=> transport: fix error handling on Stream deletion

transport/http2_client.go
=> Protect bytesSent and bytesReceived with mutex to avoid datarace

LICENSE
For consistency with our other repos (e.g. https://github.com/grpc/grpc/pull/11527) and automated check purposes, LICENSE (but not the headers in files) is preferably an exact match of Apache 2.0 (without specialization).
=> Make Apache 2.0 LICENSE file a verbatim copy

transport/transport.go
looking at the total memory allocated over the 30-second protobuf streaming benchmark period, we see that 15-16GB is allocated in total.
It seems simple to eliminate the 1GB of that within the `(*recvBufferReader).Read` method:
The current functions that allocate significant amount are:
```
4513.90MB 28.62% 28.62%  4681.40MB 29.68%  github.com/golang/protobuf/proto.Marshal
4419.88MB 28.02% 56.64%  5088.90MB 32.26%  github.com/golang/protobuf/proto.UnmarshalMerge
1066.05MB  6.76% 63.40%  1066.05MB  6.76%  google.golang.org/grpc/transport.(*recvBufferReader).Read
1041.55MB  6.60% 70.00%  1041.55MB  6.60%  golang.org/x/net/http2.parseDataFrame
1017.55MB  6.45% 76.45% 13544.44MB 85.87%  google.golang.org/grpc/benchmark.(*testServer).StreamingCall
994.05MB  6.30% 82.75%   994.05MB  6.30% …
```
=> dont create new reader in recvMsg

transport/handler_server.go, transport/http2_client.go, transport/http2_server.go, transport/transport.go
This removes the next largest remaining source of total allocs and appears to make a slight ~2.5-3% QPS improvement after #940, #1010, and #1028.
Based off of the server protobuf streaming QPS test memory profile with the combined changes, shown in #1028, the allocation in:
```
1342.06MB 35.49% 35.49%  1342.06MB 35.49%  google.golang.org/grpc/transport.(*Stream).write
```
looks to be from allocating recvMsg structs onto the heap and passing their reference onto the buffer in 
https://github.com/grpc/grpc-go/blob/master/transport/transport.go#L316
Changing the channel recvBuffer to pass by the struct onto the buffer by value, on top of the combined changes in #940, #1010, and #1028, memory profile looks like:
(same testing environment as in #1028)
```
2475.08MB of 2501.20MB total (98.96%) …
```
=> change objects in recvBuffer queue from interface to concrete type to reduce allocs

stream.go, transport/http2_client.go, transport/transport.go
If it's not client streaming, we should already have the request to be sent, so we don't flush the header.
If it is client streaming, the user may never send a request or send it any time soon, so we ask the transport to flush the header.
This change reduced one system call for flushing the headers.
Without the change:
```
Unary-Tracing-c_1-req_1B-resp_1B_noMD-12         	   10000	    103777 ns/op
Unary-Tracing-c_1-req_1B-resp_1B_withMD-12       	   10000	    115799 ns/op
Unary-Tracing-c_1-req_1B-resp_1B_withBinMD-12    	   10000	    117684 ns/op
```
With the change:
```
Unary-Tracing-c_1-req_1B-resp_1B_noMD-12         	   10000	    103641 ns/op
Unary-Tracing-c_1-req_1B-resp_1B_withMD-12       	   10000	    105663 ns/op
Unary-Tracing-c_1-req_1B-resp_1B_withBinMD-12    	   10000	    109140 …
```
=> Do not flush NewStream header on client side for unary RPCs and streaming RPCs with requests.

Documentation/grpc-auth-support.md, Documentation/grpc-metadata.md, README.md, doc.go, examples/gotutorial.md, examples/route_guide/README.md, metadata/metadata.go, rpc_util.go
https://github.com/grpc/grpc/pull/11738 for the Go repo
=> Canonicalize https://grpc.io as the preferred URL prefix

stream.go
This PR populates the `callInfo.peer` object in case of streaming RPCs similarly to what is done for [non-streaming RPCs](https://github.com/grpc/grpc-go/blob/41d9b6ea2a6335f3a22074ed35c0542c9da1baf4/call.go#L77).
Testing:
- `make`: all tests pass.
=> Populate callInfo.peer object for streaming RPCs

balancer.go
1. roundrobin: watchAddrUpdates adds a new addrs list to addCh (some addrs have been deleted from the previous list)
2. clientconn: lbWatcher calls tearDown to close the addrConn
3. clientconn: tearDown calls ac.down to notify the balancer that the connection has been closed
4. deadlock (we are making a lock from the first step and all steps are synchronous)
=> Fix mutex deadlock of roundrobin balancer

balancer.go, clientconn.go, grpclb.go, grpclog/glogger/glogger.go, grpclog/grpclog.go, grpclog/logger.go, grpclog/loggerv2.go, server.go, transport/http2_client.go, transport/http2_server.go, transport/http_util.go, transport/log.go
1. All logs use 1 severity level instead of `printf`
1. All transport logs only go to verbose level 2+
1. The default logger only log errors and verbosity level 1
1. Add environment variable `GRPC_GO_LOG_SEVERITY_LEVEL` and `GRPC_GO_LOG_VERBOSITY_LEVEL` to set severity or verbosity levels for the default logger
fixes #120
fixes #1044
fixes #1052
fixes #954
fixes #1059
=> Use log severity and verbosity level

examples/gotutorial.md
Diff:
```diff
-[protocol buffers] (https://developers.google.com/protocol-buffers/docs/overview).
+[protocol buffers](https://developers.google.com/protocol-buffers/docs/overview).
```
=> Fix a typo in examples/gotutorial.md

clientconn.go
Fixes badly formatted log records like: 
```14:26:07.0919 DEBUG -> Failed to dial %s: %v; please retry. peer0:7497 context canceled```
=> Fix logging method

clientconn.go
Just reset the underlying transport instead.
=> Do not create new addrConn when connection error happens

test/bufconn/bufconn.go, test/bufconn/bufconn_test.go
This should fix a race in the end to end tests where Close may be called while Dialing.
=> Fix bufconn.Close to not be blocking

grpclog/grpclog.go, grpclog/loggerv2.go
=> Add doc in default implementation fatal functions on os.Exit()

status/status.go, status/status_test.go
Adding WithDetails and Details to status package
These methods facilitate using google.rpc.error_details with grpc's status package.
bug: https://github.com/grpc/grpc-go/issues/1233
=> Adding WithDetails and Details to status

clientconn.go, clientconn_test.go, test/end2end_test.go
=> Expose ConnectivityState of a ClientConn.

transport/transport.go
based on https://github.com/grpc/grpc-go/pull/940 
this is also a minor improvement that seems visible on top of everything in #1029. 
appears to make ~5% further improvement on the protobuf streaming QPS test. (seeing QPS increase from ~840K to ~880K).
There's not seeing a dramatic change in the profile (multiple defers elsewhere), but the the cum cpu clock in `runtime.defferreturn` gets reduced from about ~4.5-5% to ~3.5-4%
seems easy to remove this in the `recvBuffer.read` since there's no locking involved.
=> Remove defer in recv msg reader

examples/route_guide/client/client.go, examples/route_guide/server/server.go, interop/server/server.go
So we could replace the testdata path with flags.
=> Do not call testdata.Path when defining flags

clientconn.go, transport/http2_client.go
=> Enabling client process multiple GoAways

benchmark/benchmark.go
Also, a minor change to reset the timer when the test is ready to begin instead of stopping/starting around initialization.
=> benchmark: don't stop timer until after workers are done

transport/http2_client.go, transport/http2_server.go
It it's possible we must avoid using 64-bit integers. If they have to be used then we must align them properly. See [this](https://golang.org/pkg/sync/atomic/#pkg-note-BUG) for more details:
=> Don't use 64-bit integers with atomic.

Documentation/grpc-metadata.md
Removed the deprecated `NewContext` from the metadata doc so that the
documentation would match example given in the doc
=> Have docs match given example

clientconn.go, clientconn_test.go
A leak happens when DialContext times out before a balancer returns any
addresses or before a successful connection is established.
The loop in ClientConn.lbWatcher breaks and doneChan never gets closed.
=> Fix a goroutine leak in DialContext

call.go, test/end2end_test.go
If a connection to the server exists but a request errors out due to context canceled or deadline exceeded, the peer information is not set. We can move setting the peer out of the recvResponse and before the sendRequest to get peer information for some failed RPCs. This addresses #1417
@MakMukhi @therc
=> Set peer before sending request

server.go
=> Document Server.ServeHTTP

transport/control.go, transport/http2_server.go
=> Server should send 2 goaway messages to gracefully shutdown the connection.

tap/tap.go, transport/http2_client.go
=> Update ServerInHandle comments

clientconn.go, server.go, stream.go, test/end2end_test.go, transport/handler_server.go
- Automatically sending final status if error occurred in RecvMsg/SendMsg on server side.
- Increasing defaultClientMaxSendMessageSize/defaultServerMaxSendMessageSize to math.MaxInt32 to be consistent with C++/Java.
should resolve #1334.
=> Automatic WriteStatus for RecvMsg/SendMsg error on server side

rpc_util.go
=> put *gzip.Writer back to pool

metadata/metadata.go, stats/stats_test.go
gRFC: https://github.com/grpc/proposal/pull/25
=> metadata: Remove NewContext and FromContext for gRFC L7

transport/http2_client.go
callHdr.Host already contains the port. So the behavior is broken that:
- when default port 443 is used, the audience string still contains a port
- when non-default port is used, the port number appears twice in the audience string
=> Fix host string passed to PerRPCCredentials

metadata/metadata.go, stats/stats.go, stats/stats_test.go, test/end2end_test.go, transport/http2_client.go, transport/http2_server.go, transport/http_util.go
Also, pick these up in grpc's transport when sending and fill them in when receiving.
=> stats: add methods to allow setting grpc-trace-bin and grpc-tags-bin headers

benchmark/benchmain/main.go, benchmark/benchmark.go, benchmark/benchmark16_test.go
1. Add a file benchmain/main.go to run the benchmark using `go run main.go -flag=xxx`. 
In benchmark17_test.go, it uses "b *testing.B" to calculate the allocations, and b.N to stop benchmarks. In main.go, it uses ReadMemStats and do the calculation by it's own and timeout to stop benchmarks.
An example of main.go is 
`go run benchmark/benchmain/main.go -kbps=0 -mtu=0 -maxConcurrentCalls=1 -reqSizeBytes=1,1048576 -reqspSizeBytes=1,1048576 -runUnary=true -runStream=true -traceMode=true  -latency=0s,5ms -timeout=10s`
Flags include
```
-runUnary                        =bool
-runStream                       =bool
-traceMode                       =bool
-compressionMode                 =bool
-readLatency                     =slice of time.Duration like 0s,10ms
-readKbps …
```
=> benchmark: add benchmain/main.go to run benchmark with flag set

transport/http2_client.go
When gRPC keepalives are enabled (which isn't the case by default at
this time) and PermitWithoutStream is false (the default), the client
can deadlock when transitioning between having no active stream and
having one active stream.  Subsequent attempts to create a new stream
or to close the client will hang on the transport's mutex, while the
keepalive goroutine is waiting indefinitely on a channel while holding
the transport's mutex.
This fixes #1459.
=> transport: Fix deadlock in client keepalive.

call.go, call_test.go, rpc_util.go, rpc_util_test.go, server.go, stream.go, test/end2end_test.go, transport/handler_server.go, transport/http2_client.go, transport/http2_server.go, transport/transport.go, transport/transport_test.go
Re-use the buffer used by compressor. Doesn't need to create new "buf" and copy the old data.
=> Remove buf copy when the compressor exist

test/end2end_test.go, transport/http2_server.go
- Latch this returned context in the stream's reader
- Don't block on the stream's context when writing status (always write status as long as the stream is valid)
Fixes #1386
=> transport: fix handling of InTapHandle's returned context

rpc_util.go
Tested with:
GOARCH=386 go test google.golang.org/grpc
Fixes #1469
=> Fix for 32-bit architectures

.travis.yml
=> Run Go1.9 and 386 on Travis

examples/gotutorial.md, examples/route_guide/server/server.go
macOS throws up an annoying firewall dialog with the following question every time you run the route_guide/server:
```sh
Do you want the application “server” to accept incoming network connections?
```
This simple fix of actually typing out `localhost` seems to fix this problem.
=> Fix to avoid annoying firewall dialog on macOS

trace.go
#695 
This change only truncate the output string for each payload, so the trace webpage won't print the full content of huge messages.
The message is still referenced un-truncated, because if we want to keep `LazyLog` lazy, we need to keep the message un-serialized until the webpage is rendered (see another attempt in #1508).
=> Truncate payload trace string, and turn trace off by default

vet.sh
I was running locally and unable to reproduce the golint errors.  I eventually realized I had another golint in my path before GOPATH or GOROOT.  Travis sets up the environment correctly for this, but a user may not.
=> vet.sh: set PATH to force downloaded binaries to be run

benchmark/primitives/primitives_test.go
Results:
```
$ go test -benchtime=3s -benchmem -bench=Defer benchmark/primitives/*.go
goos: linux
goarch: amd64
BenchmarkMutexWithDefer-12       	100000000	        50.2 ns/op	       0 B/op	       0 allocs/op
BenchmarkMutexWithoutDefer-12    	300000000	        16.3 ns/op	       0 B/op	       0 allocs/op
```
=> benchmark: add primivites benchmark for Unlocking via defer vs. inline

credentials/oauth/oauth.go, interop/test_utils.go
This covers the case where the TokenType field is empty, and thus
calling the Type() method will return "Bearer".
=> Use Type() method for OAuth tokens instead of accessing TokenType field.

Documentation/grpc-auth-support.md, benchmark/client/main.go, benchmark/latency/latency_test.go, benchmark/server/main.go, benchmark/worker/main.go, examples/helloworld/greeter_server/main.go, interop/server/server.go, stress/client/main.go
This is similar to #1499. But this fixes two cases of macOS firewall dialog when running `make all`, and probably other cases not tested with `make all`.
=> Added localhost to net.Listen() calls to avoid macOS firewall dialog.

Documentation/grpc-auth-support.md, benchmark/client/main.go, benchmark/latency/latency_test.go, benchmark/server/main.go, benchmark/worker/main.go, examples/helloworld/greeter_server/main.go, interop/server/server.go, stress/client/main.go
Reverts grpc/grpc-go#1539
This PR may have caused interop failures: https://github.com/grpc/grpc/issues/12723
All clients failed to create connection to go servers.
Could be `localhost` is not handled correctly.
=> Revert "Added localhost to net.Listen() calls to avoid macOS firewall dialog."

resolver/dns/dns_resolver.go, resolver/dns/dns_resolver_test.go, resolver/dns/go17.go, resolver/dns/go17_test.go, resolver/dns/go18.go, resolver/dns/go18_test.go
- Implement DNS resolver conforming to v2 resolver API. https://github.com/grpc/grpc-go/blob/master/resolver/resolver.go
- Add service config support as specified here https://github.com/grpc/proposal/blob/master/A2-service-configs-in-dns.md
=> DNS with new API

stats/stats.go, stats/stats_test.go, transport/control.go, transport/http2_client.go, transport/http2_server.go, transport/transport_test.go
hpack encoding will now happen in the loopy writer goroutine right before the header is written on the wire. This is a more efficient use of hpack encoder since it maintains state and can be more performant in subsequent call.
As a result, the stats handler call with OutHeader can not include the wire length of the header written since it's not yet calculated. We might add this field back in the future which would require changing the code quite a bit.
=> Use the same hpack encoder on a transport and share it between RPCs.

balancer.go, balancer/balancer.go, balancer/roundrobin/roundrobin.go, balancer/roundrobin/roundrobin_test.go, balancer_conn_wrappers.go, balancer_test.go, balancer_v1_wrapper.go, blockingpicker.go, blockingpicker_test.go, call.go, call_test.go, clientconn.go, grpclb.go, picker_wrapper.go, picker_wrapper_test.go, pickfirst.go, pickfirst_test.go, resolver/manual/manual.go, resolver/passthrough/passthrough.go, resolver/resolver.go, resolver_conn_wrapper.go, stream.go, test/end2end_test.go
ClientConn
- monitor resolver and balancer updates
- notify balancer of new updates
New implementations:
- roundrobin
- pickfirst
- testing resolvers (manual and passthrough)
Fixes #1504
=> New implementation of roundrobin and pickfirst

clientconn.go, transport/http2_client.go, transport/http2_server.go, transport/transport.go, transport/transport_test.go, vet.sh
- The transport is now responsible for closing its own connection when an error
occurs or when the context given to it in NewClientTransport() is canceled.
- Remove client/server shutdown channels -- add cancel function to allow
self-cancellation.
- Plumb the clientConn's context into the client transport to allow for the
transport to be canceled even after it has been removed from the ac (due to
graceful close) when the ClientConn is closed.
This is pre-work for fixing #1532 and implementing transparent retries.
=> transport: refactor of error/cancellation paths

benchmark/primitives/primitives_test.go
Results on my machine:
```
$ go test -benchtime=3s -bench=Assert benchmark/primitives/*.go
goos: linux
goarch: amd64
BenchmarkInterfaceTypeAssertion-12      500000000                9.05 ns/op
BenchmarkStructTypeAssertion-12         5000000000               0.52 ns/op
PASS
ok      command-line-arguments  8.102s
```
=> benchmark: add type assertion benchmarks

interop/client/client.go
This should not be necessary once #1551 get merged.
Currently interop clients don't use balancer. With a non-blocking dial, the first failfast RPC will fail because there's no connection available.
This is a known bug, and will be fixed by the new balancer APIs.
This is a temp fix to make interop tests pass.
=> Make interop client dial blocking

vet.sh
Because honnef.co is down.
This PR will be reverted when honnef.co is back up, or when we can get tool `staticcheck` somewhere else.
=> Temporary disable staticcheck

resolver/dns/dns_resolver.go, resolver/dns/dns_resolver_test.go, resolver/manual/manual.go, resolver/passthrough/passthrough.go, resolver/resolver.go, resolver_conn_wrapper.go, resolver_conn_wrapper_test.go
So builder doesn't need to parse the target string again.
=> Make resolver Build() take a target struct

Documentation/versioning.md
=> Create versioning and release policy document

server.go, server_test.go
As https://github.com/grpc/grpc-go/issues/1372 reported, currently `Serve()` function returns non-nil error when `Stop()` or `GracefulStop()` is called. 
This is because both `Stop` and `GracefulStop` close the listener (`net.Listener`) directly, which is still being blocked on the `Accept()` call in `Serve()`. We can use a `quit` channel to indicate that the grpc server is being stopped on demand and return `nil` instead of an error.
=> Serve() should not return error on Stop() or GracefulStop()

balancer/balancer.go, balancer/roundrobin/roundrobin_test.go, balancer_conn_wrappers.go, balancer_switching_test.go, balancer_test.go, balancer_v1_wrapper.go, clientconn.go, clientconn_test.go, pickfirst.go, resolver/passthrough/passthrough.go, resolver/resolver.go, resolver_conn_wrapper.go, test/end2end_test.go
The default balancer will be pickfirst if no balancer is specified.
And roundrobin is registered by default.
When switching balancer, the old balancer will be closed first, and a new balancer will start.
There's a gap between, where we will do optimization later.
Also removed two tests:
- TestDialWithBlockErrorOnBadCertificates
- TestDialWithBlockErrorOnNonTemporaryErrorDialer
=> Register and use default balancers and resolvers

clientconn.go, grpclb/grpclb_test.go
This leak is caused by the credentials handshaker blocking on a Read call past the context's expiration.
=> Fix goroutine leak in grpclb_test

clientconn.go, resolver/passthrough/passthrough.go, resolver/resolver.go
There are tests that depend on the behavior that target is not resolved, and is passed to the dialer directly. The recent change to make "dns" the default broke these tests.
=> Make passthrough resolver the default instead of dns

grpclb/grpc_lb_v1/messages/messages.proto, grpclb/grpc_lb_v1/service/service.proto, grpclb/grpclb_test.go
The expected contents of `go_package` has changed, see golang/protobuf#139
This is needed to build stuff with bazel - see bazelbuild/rules_go#836
=> Update go_package declarations

balancer/roundrobin/roundrobin_test.go, balancer_conn_wrappers.go, call_test.go, clientconn.go, pickfirst_test.go
The connectivity for addrConn goes from `Connection` to `TransientFailure` and back to `Connecting` when dialing. This causes the first RPC to fail if it's not wait-for-ready. This PR makes addrConn skip the first `TransientFailure` if it's dialing.
=> Fix connectivity state transitions when dialing

resolver_conn_wrapper.go, resolver_conn_wrapper_test.go
The leading `"/"` was mistakenly stripped by `parseTarget`.
=> Fix parseTarget for unix socket address without scheme

rpc_util.go, server.go, service_config.go
This reverts commit 5856538706dc3abc44dd5ba1a8bb19a0dfb1ab25.
=> Revert "cap max msg size to min(max_int, max_uint32) (#1598)"

balancer_conn_wrappers.go, balancer_v1_wrapper.go
Remove some log messages from balancer_conn_wrappers and
balancer_v1_wrapper which seem to be indented for debugging (one of them
was even logging a pointer address).
They can produce a lot of log messages which don't add value in a normal
scenario.
It might be better to change the log level to debug instead of removing them entirely. But grpclog does not have a debug log level
=> balancer: reduce chattiness

transport/http2_client.go, transport/http2_server.go, transport/transport_test.go
This is a small optimization upon which a follow optimization will be built to reduce lock contention.
Benchmarks: https://docs.google.com/a/google.com/spreadsheets/d/1G-p6-uTt8IHRLGXLuTR6TAxeL3I5krVf5r9C86cJPDc/edit?usp=sharing
=> Acquire all stream related quota and cache it locally since no more than one write can happen in parallel on stream

rpc_util.go, service_config.go
* Allow service config msg size field to be in range int64.
* On 32-bit machine, it will then be capped to int32
Value range:
32-bit system: User API: int32, Service Config: int32, Max allowed slice length: int32, Max by spec: uint32
64-bit system: User API: int64, Service Config: int64, Max allowed slice length: int64, Max by spec: uint32
=> fix max msg size type issues on different arch

transport/control.go, transport/http2_client.go, transport/http2_server.go, transport/transport.go, transport/transport_test.go
=> Fix settings ack race

benchmark/latency/latency_test.go
Errors are appearing from this test recently, with an error that shows an IPv6 address.  Travis does not support IPv6.  Using "localhost:0" seems to work for all our other tests, so let's go with that.
=> latency: Listen on localhost:0 instead of :0 in test

benchmark/stats/stats.go, transport/control.go, transport/http2_client.go, transport/http2_server.go, transport/transport.go, transport/transport_test.go
In the fast path instead of both acquiring a lock and writing on a channel, quota pool now only acquires the lock. In the slow path however, it needs to do both. 
Following are benchmark results:
Ran streaming ping pong benchmarks with 1000 concurrent streams and varied request-response sizes.
Before
```
50_Latency: 5852.5600 µs | 90_Latency: 8644.2170 µs | 99_Latency: 12326.9280 µs | Avg latency: 6096.6670 µs | Count: 9825882 | 835 Bytes/op | 31 Allocs/op |  
```
After
```
50_Latency: 2065.5250 µs | 90_Latency: 2782.8890 µs | 99_Latency: 5785.2260 µs | Avg latency: 2212.1370 µs | Count: 27098481 | 825 Bytes/op | 30 Allocs/op |  
```
Before
```
50_Latency: 6383.2990 µs | 90_Latency: 9348.2500 µs | 99_Latency: 13037.6390 µs | Avg latency: 6483.3020 µs | Count: 9242647 | 2490 Bytes/op | 31 …
```
=> Speed-up quota pools.

benchmark/worker/benchmark_client.go, benchmark/worker/benchmark_server.go, benchmark/worker/main.go, grpclb/grpclb_test.go, health/health.go, interop/test_utils.go, reflection/serverreflection.go, stats/stats_test.go, stress/client/main.go, test/end2end_test.go
`grpc.Errorf` has been deprecated.
=> *: replace deprecated grpc.Errorf calls with status.Errorf

server.go
I intended to add this along with the new option, as the name / approach has not been fully vetted yet, but forgot.
=> server: add EXPERIMENTAL tag to grpc.ConnectTimeout

call.go, clientconn.go, internal/internal.go, rpc_util.go, server.go, stream.go, test/end2end_test.go, transport/control.go, transport/http2_client.go, transport/transport.go, transport/transport_test.go
=> Implement transparent retries for gRFC A6

.travis.yml, transport/control.go, transport/http2_client.go, transport/transport_test.go, vet.sh
1. Define env variable `RUN386` and set `GOARCH` later, instead of assigning to `GOARCH` directly. Otherwise, `gimme` will override `GOARCH` back
2. Add `misspell` check
3. Disable `-race` on 386
=> travis: fix GOARCH=386 and add misspell check

balancer_conn_wrappers.go
fixes #1662
This change is same as #1666 but against `v1.7.x` branch.
=> Eliminate race on ac.acbw

clientconn.go, test/end2end_test.go
~~If connecting to an address returns a non-temporary error, this address will be removed from the list of addresses that will be retried on.
When there's no more address to retry, that addrConn will stay in TransientError until it's address list gets updated.~~ This will be done in another PR.
Failfast RPCs will fail with unavailable errors. Non-failfast RPCs will block until timeout.
#1656
=> addrConn: set ac.state to TransientFailure upon non-temporary errors

Documentation/compression.md, call.go, clientconn.go, encoding/encoding.go, rpc_util.go, server.go, service_config_test.go, stream.go, test/end2end_test.go, transport/transport.go, vet.sh
I also added a document to explain how this is supposed to work, and how it works if you use the legacy compressor/decompressor.
Fixes #1654
=> Add proper support for 'identity' encoding type

balancer/roundrobin/roundrobin.go, balancer/roundrobin/roundrobin_test.go, balancer_switching_test.go, clientconn.go, pickfirst.go, test/end2end_test.go
Update roundrobin balancer's name from `roundrobin` to `round_robin. To be consistent with service config [spec](https://github.com/grpc/grpc/blob/e7987f80c6139671b639cdbe0dd37000359869ab/doc/service_config.md#format).
=> switch balancer based on service config info

stream.go
Just to be consistent with call.go/invoke
=> set context timeout when Timeout value >= 0

balancer_conn_wrappers.go, clientconn.go, clientconn_test.go
- NewAddress with empty list (addrConn with an empty address list)
- NewServiceConfig to switch balancer before the first balancer is built
updates #1683
This makes NewSubConn() with empty list return an error, and makes UpdateAddress() with empty list tear the addrConn down. The SubConn won't be usable after this.
Eventually we want to make the SubConn with empty address list stay in TransientFailure but still usable, and balancer still can update this SubConn's address. This will be done in a follow-up PR.
=> Fix panics on balancer and resolver updates

balancer/balancer.go, call.go, clientconn.go, grpclb.go, grpclb/grpclb_test.go, grpclb_picker.go, grpclb_remote_balancer.go, picker_wrapper.go, resolver/manual/manual.go, resolver/resolver.go, resolver_conn_wrapper.go, rpc_util.go, stream.go
Also add new feature:
- Fallback to backends if remote balancer is unavailable
=> New grpclb implementation

clientconn.go, resolver/resolver.go, resolver_conn_wrapper.go
This allows ClientConn to get more up-to-date addresses from resolver.
ClientConn compares new addresses with the cached ones. So if resolver returns the same set of addresses, ClientConn will not notify balancer about it.
Also moved the initialization of resolver and balancer to avoid race. Balancer will only be started when ClientConn gets resolved addresses from balancer.
=> Re-resolve target when one connection becomes TransientFailure

resolver/resolver.go
Since a recent change, the default is `passthrough`, not `dns`.
=> Fix misleading default resolver scheme comments

transport/handler_server.go, transport/handler_server_test.go
Fix https://github.com/coreos/etcd/issues/8904.
To reproduce, run these tests without this patch to `transport/handler_server.go`:
```
go test -v -run TestHandlerTransport_HandleStreams_WriteStatusWrite
=== RUN   TestHandlerTransport_HandleStreams_WriteStatusWrite
--- PASS: TestHandlerTransport_HandleStreams_WriteStatusWrite (0.00s)
panic: send on closed channel
goroutine 8 [running]:
google.golang.org/grpc/transport.(*serverHandlerTransport).do(0xc420164230, 0xc42007e410, 0x1012a08, 0x10)
/Users/gyuho/go/src/google.golang.org/grpc/transport/handler_server.go:170 +0x115
google.golang.org/grpc/transport.(*serverHandlerTransport).Write(0xc420164230, 0xc420098640, 0xc420016760, 0x3, 0x8, 0xc420016768, 0x4, 0x8, 0xc420016770, 0x0, ...) …
```
=> transport: fix race sending RPC status that could lead to a panic

transport/go16.go, transport/go17.go, transport/handler_server.go
When the grpc server is used as a `net/http` handler the request context is being discarded. This breaks logging and other uses where grpc and http are served on the same port in a Go application. 
This PR adds the request context to the server transport. I see that grpc is maintaining compatibility down to 1.6 so I'm happy to make the context changes backwards compatible. Looking to get some initial feedback first.
=> use the request context with net/http handler

clientconn.go, clientconn_test.go, resolver/manual/manual.go, transport/http2_client.go, transport/transport.go, transport/transport_test.go, vet.sh
=> client: backoff before reconnecting if an HTTP2 server preface was not received

balancer/balancer.go, resolver/resolver.go
This forces users to not have a brand new implementation of the interfaces that are to be implemented by gRPC.
For testing, the new implementation can embed the interface.
This allows gRPC to extend those interfaces.
=> Add comments to ClientConn/SubConn interfaces to indicate new methods may be added

codec.go
If the object to marshal implements proto.Marshaler, delegate to that
immediately instead of pre-allocating a buffer. (*proto.Buffer).Marshal
has the same logic, so the []byte buffer we pre-allocate in codec.go
would never be used.
This is mainly for users of gogoproto. If you turn on the "marshaler"
and "sizer" gogoproto options, the generated Marshal() method already
pre-allocates a buffer of the appropriate size for marshaling the
entire object.
=> protoCodec: return early if proto.Marshaler

service_config.go, service_config_test.go, test/end2end_test.go
Also, rename to parseDuration since it will be used for things other than timeouts in the future.
=> Change parseTimeout to not handle non-second durations

examples/route_guide/README.md
=> Fix grpc basics link in route_guide example

clientconn.go, clientconn_test.go, resolver/resolver.go, resolver_conn_wrapper.go, resolver_test.go
=> Add WithResolverUserOptions for custom resolver build options

codes/codes.go, vet.sh
Travis cron tests are failing because the stringer generated file doesn't match the new code_string.go file.
=> remove stringer and go generate

naming/go17.go
"go1.6, !go1.8" constraints are interpreted as (version >= 1.6 AND ) OR version < 1.8, where (version >= 1.6 AND ) is always false,
so it matches all go versions before 1.8, not only 1.6 and 1.7.
Removed a space, so the constraints are now matches only go1.6 and go1.7 versions
=> naming: Fix build constraints for go1.6 and go1.7

balancer_switching_test.go, clientconn.go, grpclb.go, grpclb/grpclb_test.go, pickfirst.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/1692)
=> Switch balancer to grpclb when at least one address is grpclb address

balancer/roundrobin/roundrobin_test.go, balancer_test.go, pickfirst_test.go, test/end2end_test.go
Fixes #1700 
As discussed in https://github.com/golang/go/issues/10527, closing a listener can still result in connections being created by subsequent `net.Dial` calls.  The fix is to prevent the new connections from assuming they are good until the server sends its handshake, which will not happen after `Server.Stop` has returned.
Also, in roundrobin_test, we need to reset the targetsSeen counter to zero when there is any error in order to be sure the address is not only _down_ but also removed from the balancer's picker before continuing to the next part of the test.
These tests now fail 0/5000 (previously ~3/500).
=> Deflake tests that rely on Stop() then Dial() not reconnecting

transport/control.go, transport/http2_server.go
In GracefulStop, close server transport only after flushing status of the last stream.
fixes: #1681
=> transport: fix race to ensure stream status is written before transport is closed

transport/transport.go
While waiting for headers from the server, client should wait on error chans as well.
fixes: #1727
=> client: fix race between server response and stream context cancellation

clientconn_test.go
=> Make sure all goroutines have ended before restoring global vars.

balancer_v1_wrapper.go
TestPickfirstOneAddressRemoval timeout was ~2/1000.
Timeout is caused by the deadlock caused by race condition between: `bw.connSt[oldSC].addr = addrs[0]` and `oldSC.UpdateAddresses(newAddrs)` -> when current address is removed `ac.tearDown()`->`ac=newAddrConn()`->`ac.Connect()`->`HandleSubConnStateChange(...)`->`Up($bw.connSt[oldSC].addr)`
=> fix flaky TestPickfirstOneAddressRemoval

clientconn.go
avoid unnecessary calls to ac.transport.GracefulClose() in case of multiple goaways and concurrent address removals. Once is enough for gracefully closing the transport.
=> relocate GracefulClose() conditional in ac.tearDown()

stats/stats_test.go, transport/http2_server.go
1. Call transport Close if newHTTP2Server returns non-nil error.
Handle ConnBegin was called before this error, and handle ConnEnd is not called (because Close() is not called), which caused ConnStats check to fail.
2. Skip stats test in go1.6.
go1.6 doesn't have DialContext (we use Dialer(Cancel: ctx.Done()) instead). When the give context is canceled, this function sometimes returns canceled error, while the server side still gets the conn. This caused the server blocking on reading the preface (which will eventually timeout, but the tests are too short for that), and there will be a missing ConnEnd.
fixes #1615
=> fix stats flaky test

balancer.go, balancer/roundrobin/roundrobin_test.go, balancer_switching_test.go, balancer_test.go, balancer_v1_wrapper.go, call.go, call_test.go, grpclb/grpclb_test.go, internal/internal.go, interop/http2/negative_http2_client.go, interop/test_utils.go, pickfirst_test.go, rpc_util.go, server.go, server_test.go, stats/stats_test.go, stream.go, test/end2end_test.go
The golang [convention for deprecating functions](https://blog.golang.org/godoc-documenting-go-code) is to use `Deprecated:`. Most deprecated functions in this repo follow the convention, however a few in `rpc_util.go` use `Deprecated;` (semicolon). 
This PR fixes the comment string so that [staticcheck](https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck) will correctly recognize the function as deprecated.
=> Fix deprecation comments in rpc_util.go

grpclb/grpc_lb_v1/doc.go, vet.sh
Replaces https://github.com/grpc/grpc-go/pull/1743
=> Add doc.go to grpc_lb_v1 for 1.7.x branch

vet.sh
Because we no longer use stringer.
=> vet: run golint on _string files

clientconn_test.go
=> Fix test: Data race while resetting global var.

balancer/roundrobin/roundrobin.go, balancer/roundrobin/roundrobin_test.go, balancer_switching_test.go, clientconn.go, grpclb.go, grpclb/grpclb_test.go, grpclb_remote_balancer.go, pickfirst.go, pickfirst_test.go, test/end2end_test.go
WithBalancerName dial option specifies the name of the balancer to be used by the ClientConn. Service config updates can NOT override the balancer option.
#1694
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/1697)
=> Add dial option to set balancer

balancer/balancer.go, balancer_conn_wrappers.go, grpclb.go, grpclb/grpclb_test.go, grpclb_util.go
The parent ClientConn should re-resolve when grpclb loses connection to the
remote balancer.
When the `ClientConn` inside grpclb gets a `TransientFailure`, it calls
`lbManualResolver.ResolveNow()`, which calls parent ClientConn's `ResolveNow`, and
eventually results in re-resolve happening in parent ClientConn's resolver (DNS
for example).
This PR adds a method to `balancer.ClientConn` interface, so balancer can tell
parent ClientConn to re-resolve.
=> Notify parent ClientConn to re-resolve in grpclb

server.go, test/gracefulstop_test.go, transport/http2_client.go, transport/http2_server.go
=> server: fix race between GracefulStop and new incoming connections (#1745)

grpclb.go
The `init` block is duplicated (first occurrence in lines 85-87).
=> Remove duplicate init() from grpclb

clientconn_test.go
This flake was related to other keepalive flakes where the client would close the connection instead of the server as a result of a small timeout.
The failure rate was about 1 in 1000. This patch was tested to successfully pass 10000 runs with asan on.
fixes #1753
=> Fix flakey test TestClientUpdatesParamsAfterGoAway

benchmark/primitives/primitives_test.go
```
BenchmarkIncrInt64Atomics-12    	300000000	         5.59 ns/op
BenchmarkIncrInt64Mutex-12      	100000000	        15.8 ns/op
BenchmarkSetTimeAtomics-12      	20000000	       104 ns/op
BenchmarkSetTimeMutex-12        	100000000	        14.3 ns/op
```
=> compare atomic and mutex performance for incrementing one variable

call.go, rpc_util.go, stream.go
CPU profile shows that header copy takes a large proportion of CPU usage in a gRPC Call.
If the header is not needed, we don't need to pay the cost.
=> Avoid copying headers/trailers in unary RPCs unless requested by CallOptions

credentials/credentials.go, transport/http2_client.go
Referencing https://github.com/grpc/grpc-go/issues/1704.
I'm a little confused on the part, "The oauth implementation should return UNAVAILABLE if the oauth server cannot be reached.". Does that mean, all implementers of `TokenSource :: Token() (*Token, error)` should return `UNAVAILABLE` if the server cannot be reached? If so I'm happy to try and go through and add them either in this PR or a separate PR.
=> credentials: return Unavailable instead of Internal for per-RPC creds errors

clientconn.go
fixes #1772
Unfortunately, it is [not enough](https://travis-ci.org/MakMukhi/grpc-go/builds/324439341) to get rid of this workaround: https://github.com/grpc/grpc-go/blob/7aea499f9110a479b3777df064372f44188146aa/clientconn_test.go#L251
=> Don't set reconnect parameters when the server has already responded with preface.

call.go, stream.go
=> Document that all errors from RPCs are status errors

metadata/metadata.go
https://grpc.io/docs/guides/wire.html is no longer valid.
Looking at an archived version of that page
(https://web.archive.org/web/20171006045517/https://grpc.io/docs/guides/wire.html)
it looks equilavent to what is now posted at:
https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md.
The gRPC guide: https://grpc.io/docs/guides/ contains a link in the
sidebar navigation to the same page, so pretty sure it's correct.
=> Updating broken wire.html link.

test/end2end_test.go, transport/http2_client.go
=> Fix bug preventing stream.Send() from receiving io.EOF after end of stream

transport/http2_client.go
fix #1803 
Disallow assignment to s.recvCompress after header chan is closed.
=> Disallow assignment to s.recvCompress after header chan is closed.

examples/route_guide/client/client.go
=> Use keyed fields for struct initializers

test/end2end_test.go, transport/http2_client.go, transport/transport.go
fix #1809
Previously, we only send reset stream if the rpc error is originated on client side at transport layer, which leave the grpc layer case unhandled.
=> client: send RST_STREAM on client-side errors to prevent server from blocking

transport/http2_server.go
=> transport: remove redundant check of stream state in Write

transport/http2_client.go, transport/transport.go
When client receives RST_STREAM from server, `handleRSTStream` will call `s.finish` which will set `s.state = streamDone`. And when later `closeStream` gets called, it will return in the conditional checking for `s.state == streamDone` before reaching the code setting `rstStream = true`, and thus prevents sending a RST_STREAM back to server. 
> The RST_STREAM frame fully terminates the referenced stream and causes it to enter the "closed" state. After receiving a RST_STREAM on a stream, the receiver MUST NOT send additional frames for that stream, with the exception of PRIORITY. However, after sending the RST_STREAM, the sending endpoint MUST be prepared to receive and process additional frames sent on the stream that might have been sent by the peer prior to the arrival of the …
=> transport: remove unnecessary rstReceived

encoding/proto/proto.go, test/end2end_test.go
We should lint/vet/typo check stricter but make them optional.
=> Fix lint error and typo

stream.go, test/end2end_test.go
See #1818 for behavior before this fix.
Limitations of this solution: there's a possible context leak
- If no timeout was specified by service config, the child context won't be created. There's no context leak.
- If user provided context is not `Background` (is cancel-able), this ctx will be freed when the user ctx timeout/is canceled. There's no leak if user is  handling the ctx appropriately.
- If user's context is `Background`, this ctx will be leaked after the stream is done, until timeout.
fixes #1818
=> Stream: do not cancel ctx created with service config timeout

server.go, transport/handler_server.go, transport/handler_server_test.go
An attempt at addressing #1784.
There are a few problems that I ran into while looking at this, so I would appreciate some feedback:
NewServerHandlerTransport doesn't support passing through the server's statsHandler so I added a param which breaks the existing API. Is there a better way to approach this?
I'm not entirely sure the HandleRPC calls are in the correct location. The OutTrailer is at the end of the async func in WriteStatus, but there is a race between when that function is called and when the defer is executed in process{Unary,Streaming}RPC which calls HandleRPC with End stats. This could lead to the OutTrailer and End stats being called out of order.
Happy to make changes if there are better suggestions on how to solve this.
=> transport: support stats.Handler in serverHandlerTransport

status/status.go, status/status_test.go
This commit adds a function to convert between gRPC errors to
status.Status types without having to deal with an "ok" return value.
Fixes #1378.
@dfawley This work is almost an exact copy of what you proposed. I tried to closely follow the established style for the tests and will be happy to make changes.
=> Add status.Convert convenience function

Documentation/grpc-metadata.md, metadata/metadata.go, metadata/metadata_test.go, transport/http2_client.go
Fixes issue #1390, providing a way through call options to set header metadata instead of having to copy around contexts.
Btw, noticed that there's a metadata test for unary connections but couldn't find one for streams - let me know if I should add that.
=> Improve performance adding metadata to outgoing requests

interop/test_utils.go
With #1854, send will get `io.EOF` instead of `DeadlineExceeded`.
`Recv` should always get the expected `DeadlineExceeded` error.
=> interop test: Expect io.EOF from stream.Send()

test/end2end_test.go, transport/http2_client.go, transport/http2_server.go
fixes #1850 
Fix deadlock: In case of an error while writing, add transport quota back
=> transport: fix race causing flow control discrepancy when sending messages over server limit

clientconn.go, transport/http2_client.go
Retrying happens with exponential backoff, so the overhead should be tolerable.
We need this to trigger resolver re-resolve for new addresses.
Permanent errors are in general hard to deal with, and it's not support in other languages.
It's sometimes hard to tell the difference between temporary errors and non-temporary errors. Even for the typical "permanent" TLS handshake errors, it could be caused by a wrong setting on the server side, and a second retry could work.
We still need to way to let the user find out this kind of errors quickly.
With #1855, users should have enough information to decide what to do based on the returned RPC errors.
=> Keep retrying in addrConn even on non-temporary errors

clientconn.go, picker_wrapper.go, test/end2end_test.go
This only happens when the RPC failed because all addrConn was in TransientFailure. And this is best effort because the returned error might not be the real cause.
But it should be good enough to detect the reason when the ClientConn is "dead" (keep retrying but none of the connection works).
updates #1742 
fixes #1633
fixes #1656
=> addrConn: Report underlying connection error in RPC error

benchmark/benchmain/main.go, benchmark/benchmark.go, benchmark/server/main.go, benchmark/worker/benchmark_server.go
This will allow us to focus on grpc internals in profiling by excluding the cost of syscalls, which is a significant part of our time spent.
=> benchmarks: add flag to benchmain to use bufconn instead of network

clientconn.go
Title says it all, there was a typo in ClientConn.GetMethodConfig
documentation
=> clientconn: fix a typo in GetMethodConfig documentation

examples/gotutorial.md, examples/helloworld/greeter_client/main.go, examples/helloworld/mock_helloworld/hw_mock_test.go, examples/route_guide/client/client.go, examples/route_guide/mock_routeguide/rg_mock_test.go
=> examples: Replace context.Background with context.WithTimeout

credentials/alts/alts.go, credentials/alts/alts_test.go, interop/alts/client/client.go, interop/alts/server/server.go
ALTS `NewClientALTS` and `NewServerALTS` APIs are in the `grpc/credentials/alts` package. Having the term ALTS in the API names is redundant. This PR removes it.
Note that this is an API change but it should not break anything.
=> ALTS: Simplify "New" APIs

interop/client/client.go, interop/server/server.go
This change allows to use the same interop binaries/environment to test ALTS.
Please review #1895 first and I'll rebase this PR once that is merged.
=> interop: Add use_alts flag to client and server binaries

clientconn.go, clientconn_test.go
Atomically modify minConnecTimout in testing environment to avoid write-after-read detection.
=> Fix race in TestCloseConnectionWhenServerPrefaceNotReceived

credentials/alts/utils.go
I was trying to run tests locally, to see if another change I was making was good. And I encountered a stack overflow error. I am guessing that the tests for the `google.golang.org/grpc/credentials/alts` package are skipped during CI.
In any event, there was an `Error()` method that in turn called `fmt.Sprintf` and passed the receiver. This in turn resulted in the `fmt` package invoking the `Error()` method which then invoked `fmt.Sprintf`, and so on, ad infinitum.
=> credentials/alts: fix infinite recursion bug [in custom error type]

go16.go, go17.go, interceptor.go, server.go, stream.go
Was waffling on whether the `os.IsExist(err)` and `os.IsNotExist(err)` errors should be `Unknown`, but went with internal. Let me know if y'all think any of these could be amended
=> server: Convert all non-status errors to codes.Unknown

resolver_conn_wrapper.go, resolver_conn_wrapper_test.go
=> resolver: always fall back to default resolver when target does not follow URI scheme

transport/http2_server.go
fixes #1882 
Eliminate race which causes a ping to be scheduled between pingStrike counter being reset and data being scheduled.
=> transport: fix race that could lead to the server closing a connection due to too many pings

server.go, stats/stats.go, stats/stats_test.go, stream.go
This change allows `stats.Handler` implementations easily determine duration.
=> stats: add BeginTime to stats.End

call.go, rpc_util.go, stream.go
This is pre-work to implementing retry support.  Each retry attempt will have its own `csAttempt`.  The fields left in clientStream are the same across all attempts.
=> stream: split per-attempt data from clientStream

call.go, rpc_util.go, stream.go, test/end2end_test.go
This fixes #1495.
If I understood correctly, @dfawley, this is the approach you were suggesting. Can you take a look and let me know?
=> Call options provide methods so interceptors in other packages can recover settings

credentials/alts/alts.go, credentials/alts/alts_test.go, interop/alts/client/client.go, interop/alts/server/server.go, interop/client/client.go, interop/server/server.go
Change the `alts.NewClient` API to take a struct containing all client-side options instead of passing them using parameters. This allows adding more options in the future without breaking the existing API or having to create a new one.
This API also changes `alts.NewClient` and `alts.NewServer` to `alts.NewClientCreds` and `alts.NewServerCreds`, respectively.
This API is only used by the `interop/alts/client/client.go`.
=> credentials/alts: Update ALTS "New" APIs

rpc_util.go, test/end2end_test.go
Remove the code to test custom codec in TestInterceptorCanAccessCallOptions, as `grpc.Codec` is deprecated, and should only be used by those advanced users with special purpose, thus no need to test.
=> fix minor typos

metadata/metadata.go, metadata/metadata_test.go
Fixes #1925 
For 1-10 append operations, performance is slightly worse using this method, but it is correct and ~3x faster than the old method of copying the whole map.
Before:
```
BenchmarkAppendToOutgoingContext/1-12                          	10000000	       197 ns/op
BenchmarkAppendToOutgoingContext/10-12                         	 1000000	      2033 ns/op
BenchmarkAppendToOutgoingContext/100-12                        	  100000	     15497 ns/op
```
After:
```
BenchmarkAppendToOutgoingContext/1-12                          	10000000	       193 ns/op
BenchmarkAppendToOutgoingContext/10-12                         	  500000	      2513 ns/op
BenchmarkAppendToOutgoingContext/100-12                        	   30000	     51658 ns/op
```
The old method for reference:
``` …
```
=> metadata: Fix bug where AppendToOutgoingContext could modify another context's metadata

encoding/gzip/gzip.go, rpc_util.go, rpc_util_test.go
- BestSpeed compression level give 36% request throughput improvement over BestCompression with a slight compromise on network bandwidth
After this we can choose gzip compression level during server and client setup to level which suites our usecase
=> gzip: Add ability to set compression level

server.go, server_test.go, stream.go, transport/handler_server.go, transport/http2_server.go, transport/transport.go, transport/transport_test.go
Fixes #1802.
This allows handlers to be run from tests without requiring the entirety of the gRPC server machinery: a test can store a mock `transport.ServerStream` into the context and then call the handler.
It also enables alternate transport implementations.
=> allow storing alternate transport.ServerStream implementations in context

Documentation/rpc-errors.md
There's a broken link in the `rpc-errors.md` documentation. This commit repairs it.
=> Fix broken link in rpc-errors.md

reflection/grpc_testingv3/testv3.pb.go, reflection/grpc_testingv3/testv3.proto, reflection/serverreflection.go, reflection/serverreflection_test.go
Currently, find the file for a given symbol only works if the symbol is a message, service, or method. This extends that to enums, enum values, fields, extensions, and oneofs.
Since these symbols aren't registered by generated code, they must be indexed from the files referenced by the registered services. This also caches the file descriptor objects in the reflection service, instead of having to re-decompress them with every access.
=> service reflection can lookup enum, enum val, oneof, and field symbols

status/status.go, status/status_test.go
Embues the status package with the ability to create statuses
from generic errors that implement a special interface.
This was designed with the github.com/gogo/protobuf project in mind,
but is implemented in a fashion that makes it accessible to arbitrary
payloads.
Fixes #1885.
=> Allow statuses from compatible errors

status/status.go, status/status_test.go
@johanbrandhorst Sorry for the change here, but this should help avoid naming conflicts and make it possible for statuses to work with many types of status packages.
=> status: rename Status to GRPCStatus to avoid name conflicts

clientconn.go, resolver/resolver.go, resolver_conn_wrapper.go, resolver_conn_wrapper_test.go
For target `unix:///foo`:
**Before**:  it is parsed as `{scheme: "unix", authority: "", endpoint: "foo"}`, and the fallback resolver (`passthrough`) will get `"foo"` as the endpoint.
After: `{scheme: "", authority: "", endpoint: "unix:///foo"}`, the `passthrough` resolver will get `"unix:///foo"` as the endpoint.
fixes #1899
related to #1889
=> resolver: keep full unparsed target string if scheme in parsed target is not registered

call.go, stream.go
Caught by @euroelessar
https://github.com/grpc/grpc-go/pull/1902#discussion_r177673628
=> client: Fix race when using both client-side default CallOptions and per-call CallOptions

metadata/metadata.go, metadata/metadata_test.go
Addresses issue #1926 by adding a Get and Set method which performs the lowercase transformation.
I guess one question I had was on the semantics of the Set method. I made is to that Set replaces the old key-value pair. I suppose it could also have meant _append values to key_. Was this the way it should have been done?
=> metadata: Add Get, Set, and Append methods to metadata.MD

clientconn.go, test/end2end_test.go, transport/controlbuf.go, transport/flowcontrol.go, transport/handler_server.go, transport/http2_client.go, transport/http2_server.go, transport/http_util.go, transport/transport.go, transport/transport_test.go
Free stream (RPC) goroutines from the onus of checking transport level quotas like flow control and to remove all the global locks. The streams instead schedule their messages and headers by adding them to `controlBuf` which is read by a dedicated goroutine which takes care of checking these quotas and writes bytes on the wire. This eliminates friction in highly-concurrent environments.
Furthermore, this dedicated writing goroutine is tuned to maximise batch size for each syscall by yielding its processor (`runtime.Gosched()`) when there isn’t much data to write. This leads to stream goroutines getting scheduled and writing more data on `controlBuf` and eventually increasing the batch size per syscall. This also helps with improving QPS (benchmark not covered above) by about 20%. …
=> transport: refactor to reduce lock contention and improve performance

grpclb.go, grpclb_util.go, grpclb_util_test.go
10 seconds timeout is arbitrary. Could make it configurable in the future.
=> grpclb: cache SubConns for 10 seconds after it is removed from the backendlist

clientconn.go, rpc_util.go, rpc_util_test.go
DialContext only allows "tcp" network. for example.
``` go
addr := "unix://etcd:0"
grpc.DialContext(ctx, addr, opts...)
```
this will result in a dns resolution failure because tcp is assumed as it is hard coded in dialContext.
The patch will allow for unix socket `network` if unix scheme is passed . As tcp is still the default value this should be backward compatible. Thank you for your consideration.
ref: https://github.com/grpc/grpc-go/issues/1741
=>  clientconn: add support for unix network in DialContext.

transport/transport.go, transport/transport_test.go
With the transport refactoring (#1962),  the transport will now close the stream right way if the header received is invalid. Before, the error will be sent to the recv buffer, and wait until user read to detect the error and close the stream. Therefore, now there exist a race between receiving the invalid header thus closing stream and the write of request, and we may get `errStreamDone` error from `Write`, which causes test to fail.
=> Fix Test: race between t.Write() and t.closeStream()

test/end2end_test.go
for `TestFailFastRPCErrorOnBadCertificates`
We were getting `context deadline exceeded` from this dial, but the dial is not blocking.
updates #1968
=> cleanup: extend dial context for test to 10 seconds

clientconn.go
=> documentation: mention DialContext is non-blocking by default

reflection/grpc_reflection_v1alpha/reflection.pb.go
The typo in proto file was fixed, but not pb.go file. This was causing failures
in travis cron tests.
Fix for proto file: https://github.com/grpc/grpc-go/pull/1994/files#diff-46d5b9196e4de6acd555d67dde31211eR75
=> reflection: regenerate pb.go file after typo fix

resolver_conn_wrapper_test.go
For file `resolver_conn_wrapper_test.go`.
`go vet` on travis doesn't report this, but local `go vet` does. This will make it easier to use `./vet.sh` to detect errors before pushing.
related to: #2004
=> go vet: fix composite literal uses unkeyed fields

credentials/alts/alts.go, credentials/alts/alts_test.go, credentials/alts/core/handshaker/service/service.go, credentials/alts/core/handshaker/service/service_test.go, interop/alts/client/client.go, interop/alts/server/server.go, interop/client/client.go, interop/server/server.go
Move the `handshaker_service_address` flag from `credentials/alts/core/handshaker/service/` to the appropriate binaries.
This PR also adds a `ServerOptions` object to be passed to the `alts.NewServerCreds` API. However, this API change is safe since it's not used yet.
=> credentials/alts: Add ServiceOption for server-side ALTS creation

Documentation/stickiness.md, clientconn.go, envconfig.go, picker_wrapper.go, service_config.go, stickiness_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/1969)
=> stickiness: add stickiness support

picker_wrapper.go
App Engine doesn't allow use of unsafe
#2022
=> stickiness: avoid using unsafe

server.go, server_test.go
=> server: export ServerTransportStreamFromContext for unary interceptors to control headers/trailers

credentials/alts/core/handshaker/handshaker.go
This eases internal syncing of the proto file internally, where the packages may be different.
=> credentials/alts: Refer to ALTS gRPC types by a different package

call.go
This is a partial revert of #2027 which seems to have broken the ability
to inject payload inspecting client interceptors. Specifically it causes
this test to break:
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/eb0079f598a6640ecbb7a4d2d9dcb0278a320b61/bigtable/bigtable_test.go#L949-L971
With:
> panic: interface conversion: grpc.ClientStream is *bigtable.requestCountingInterceptor, not *grpc.clientStream [recovered]
> 	panic: interface conversion: grpc.ClientStream is *bigtable.requestCountingInterceptor, not *grpc.clientStream
> 
Which seems to be caused by invoke() expecting a clientStream from a
ClientConn:
https://github.com/grpc/grpc-go/blob/7c204fd174eaec3ef7de010a6673121d6625013e/call.go#L74
I'm not entirely sure if this is the correct solution, but figured I start …
=> client: fix interceptors after recent cleanup

status/go16.go, status/go17.go, status/go17_test.go, status/status_test.go
With the removal of auto-converting context (and other) errors from service handlers in #1881, the expected application code when checking context and returning status errors based on it is fairly verbose.  With this function, it is simplified to:
```go
if err := ctx.Err(); err != nil {
return status.FromContextError(err).Err()
}
```
=> status: Introduce FromContextError convenience function

Documentation/concurrency.md
Fixes #1345 
Note, this documentation is meant to be a starting point for more nuanced discussion of concurrency in the library.
=> Documentation: Add initial documentation on concurrency

stream.go
Making a similar change to protoc-gen-go
=> small documentation addition to NewStream

credentials/alts/utils.go, credentials/alts/utils_test.go
`alts.AuthInfoFromContext` is a useful API at for RPC service handlers at the server side to get information about the connecting ALTS peer.
=> credentials/alts: Add AuthInfoFromContext utility API

transport/controlbuf.go, transport/transport_test.go
=> Respect SETTINGS_HEADER_TABLE_SIZE http2 setting

benchmark/grpc_testing/services.pb.go, channelz/grpc_channelz_v1/channelz.pb.go, examples/helloworld/helloworld/helloworld.pb.go, examples/route_guide/routeguide/route_guide.pb.go, grpclb/grpc_lb_v1/service/service.pb.go, health/grpc_health_v1/health.pb.go, interop/grpc_testing/test.pb.go, reflection/grpc_reflection_v1alpha/reflection.pb.go, reflection/grpc_testing/test.pb.go, stats/grpc_testing/test.pb.go, stress/grpc_testing/metrics.pb.go, test/grpc_testing/test.pb.go
https://github.com/golang/protobuf/pull/592 is now merged, and we need to update the pb.go files in our repository.
=> regenerate *.pb.go files due to proto-gen-go update

benchmark/server/main.go, benchmark/worker/benchmark_server.go
Trying to fix: https://github.com/grpc/grpc/issues/15291.
The error message was:
`FATAL: 2018/05/06 22:51:16 &{0xc420206300}.StreamingCall(_) = _, rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = `**`"transport: Error while dialing dial tcp 10.240.0.251:38561: getsockopt: connection refused"`**
The failure might be caused by `Listen` only listens on ipv6 address, but client is trying to dialing to ipv4 addresses.
Possibly related golang issue: https://github.com/golang/go/issues/9334
=> benchmark: listen on all addresses in benchmark servers

rpc_util.go, version.go
So it's easier to update version when doing releases.
=> internal: move version to a separate file

grpclb.go, grpclb/grpclb_test.go
This reverts commit d24d0a4b993587a34ac7d09ac956b0375ee7d1fa.
=> Revert "Strip port from server name in grpclb (#2066)"

channelz/service/service.go, vet.sh
The proto files were removed. This `go generate` would fail because of missing files.
=> internal: remove redundant channelz service go generate

transport/http2_server.go, transport/transport.go
Since `RecvMsg` can lead to a `WriteStatus` call, it is possible that `WriteHeader` and `WriteStatus` are run in parallel. Thus we must synchronize on header and trailer metadata accessed by both.
This doesn't have significant performance impact; adds ~500ns to a 1 byte req/resp unary RPC.
Fixes #1972
=> Synchronize WriteStatus with WriteHeader on server.

benchmark/benchmark.go, benchmark/client/main.go, benchmark/run_bench.sh, benchmark/server/main.go
Also, 
* Record CPU utilization on both client and server.
* Profile CPU and Memory on both client and server.
* Do not record buckets.
* One stop shell script to run benchmarks.
Sample output:
```
$ ./run_bench.sh -r 1,10 -c 1,200 -req 1,100 -resp 1 -rpc_type unary,streaming
================================================================================
r_1_c_1_req_1_resp_1_unary_1522345524
qps: 9247.9
Latency: (50/90/99 %ile): 102.367µs/122.551µs/168.352µs
Client CPU utilization: 15.369409788s
Client CPU profile: /tmp/client_r_1_c_1_req_1_resp_1_unary_1522345524.cpu
Client Mem Profile: /tmp/client_r_1_c_1_req_1_resp_1_unary_1522345524.mem
Server CPU utilization: 17.173763239s
Server CPU profile: /tmp/Server_r_1_c_1_req_1_resp_1_unary_1522345524.cpu
Server Mem Profile: …
```
=> Benchmarks that runs server and client and separate processes.

resolver_conn_wrapper.go
I think the goroutine does not get started any more (this used to be the case in an earlier version).
=> Clarify newCCResolverWrapper documentation.

codes/codes.go, codes/codes_test.go
Marshalling a Code to JSON and unmarshalling it failed with an
"invalid code" error message.
Code is of type uint32. It has no custom MarshalJson() implemented
therefore it is marshalled into an JSON integer value.
The UnmarshalJSON() function expected that the marshalled Code is a
String type, unmarshalling failed.
Check in UnmarshalJSON() if the value is an uint32 in the range of the
defined Code values. If it is, unmarshal it.
This commit also adds an Marshal/Unmarshal testcase.
=> codes: fix: marshal/unmarshal a Code to JSON fails

resolver/dns/dns_resolver.go
The gRPC naming document at
https://github.com/grpc/grpc/blob/master/doc/naming.md says:
> for DNS, the authority may include the IP[:port] of the DNS server to use
However, grpc-go does not support configuring DNS servers. It will always use
Go's default DNS resolver.
=> Throw an error for non-default DNS authority.

balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_test.go, grpclb/noimport.go
* modify noimport.go panic message
* package level comments
* remove useless error check at grpclb_test.go:343
=> grpclb: minor fixes on comments and tests

test/end2end_test.go, transport/http2_server.go, transport/http_util.go, transport/http_util_test.go
fixes #2078
A status with invalid utf-8 characters could still be created, but invalid characters will be replaced with [Unicode replacement character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character) before being sent out. Those bytes will still be percent encoded.
All details added to this invalid status will be dropped.
=> status: handle invalid utf-8 characters

Documentation/log_levels.md
Once this is agreed upon, we should take a sweep through all our logging and make sure it is compliant.
related to #2025
=> Documentation: create doc describing grpc-go's log levels and their usages

balancer/grpclb/grpclb_remote_balancer.go
This is interesting info to check, but the [way that the proto is currently logged is a bit hard to read](https://github.com/grpc/grpc-go/blob/master/balancer/grpclb/grpclb_remote_balancer.go#L43).
=> Add a debug log to grpclb client

balancer/grpclb/grpclb_picker.go, balancer/grpclb/grpclb_test.go
Remove `rpcStatsForTest` and reuse `rpcStats` in tests.
Also fix races: https://travis-ci.org/grpc/grpc-go/jobs/388477002
=> grpclb: remove redundent testing struct

transport/http2_client.go
=> Don't do extra work for keepalive when it's disabled.

test/end2end_test.go, transport/http2_server.go, transport/http_util.go, transport/http_util_test.go
fixes #2078
A status with invalid utf-8 characters could still be created, but invalid characters will be replaced with [Unicode replacement character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character) before being sent out. Those bytes will still be percent encoded.
All details added to this invalid status will be dropped.
=> status: handle invalid utf-8 characters (#2109)

interop/client/client.go
This can allow the interop client to start running in scenarios in which the target is grpclb balanced.
cc @adelez
=> Import grpclb package in the interop client

balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_remote_balancer.go
Fixes https://github.com/grpc/grpc-go/issues/2161
I introduced `serverTerminatedConnectionErr `, because I wanted `callRemoteBalancer` to still returns error on a terminated connections. Its client, which is function `watchRemoteBalancer` can decide how to log this error.
When remote grpclb-server terminates the connection, don't log it as
error. Instead, log it as info.
It is natural for servers to terminate long lived grpc streaming
connections. Two sample reasons to do this are: load balancing and
deployment of a new version. Therefore client of grpclb-server shouldn't
recognise this situation as an error.
=> Don't log grpclb server ending connection as error

interop/client/client.go
cc @adelez 
this is to allow use of grpclb-in-DNS in the interop client
=> interop: set dns as default scheme in interop client

clientconn.go, server.go, test/end2end_test.go, transport/http2_client.go, transport/http2_server.go, transport/http_util.go, transport/transport_test.go
=> client, server: update dial/server buffer options to support a "disable" setting

stream.go
=> documentation: clarify SendMsg documentation

.travis.yml, call.go, clientconn.go, internal/envconfig/envconfig.go, rpc_util.go, service_config.go, stream.go, test/end2end_test.go, test/retry_test.go, transport/go16.go, transport/go17.go, transport/http2_client.go, transport/http_util.go, transport/transport.go, transport/transport_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/2111)
=> client: Implement gRFC A6: configurable client-side retry support

balancer/grpclb/grpclb.go
Given the discussion at https://github.com/golang/go/issues/17173, this is minor.  However, I do think `errors.New` is more preferable when there is nothing to format from go readability perspective.
=> grpclb: s/fmt.Errorf/errors.New/

stream.go, transport/transport.go
Also, return an error if SendMsg is called after CloseSend.
=> stream: in withRetry, block until Status is valid and check on io.EOF

.travis.yml, vet.sh
This PR removes race testing from all travis runs except go1.10 except during nightlies.
|                 | Before* | After** | % Change |
| --------------- | ------- | ------- | -------- |
| Total runtime   | 65m     | 45m     | -31%     |
| Wall-clock time | 21m     | 11.5m   | -45%     |
*: (one random sample I found in our PRs)
**: (latest run on this PR)
Also includes some organization changes (making proper use of `before_install` and `install`) / cleanups in `.travis.yml` to make it easier to understand.  As a result, we now stop unintentionally running `vet` on a second build by accident (go1.10 with retry enabled).
=> internal: changes to travis to make it do less work

clientconn.go
fix #2203
When connect timeout (preface not received within 20s) happens under waitForHandShake case, the transport should not go to ready stage when actually the transport has been closed already.
=> createTransport: timeout under waitForHandshake case should not have transport transferred to ready stage

transport/http2_client.go
Fixes https://github.com/grpc/grpc/issues/15745
=> transport: double-check deadline when processing server cancelation

balancer/balancer.go, clientconn.go, stream.go
Provide additional context to Pickers that wish to make decisions based on the RPC method.
Relevant issue: https://github.com/grpc/grpc-go/issues/2103
=> balancer: add rpc method to PickOptions

clientconn.go, dialoptions.go, internal/transport/handler_server.go, internal/transport/transport.go, internal/transport/transport_test.go, server.go, stream.go
- Flush and Authority are never read by the transport.
- Authority is used indirectly; move it to dialOptions.
- Delay is only set to false.
=> internal/transport: remove some unused fields from structs

resolver/dns/dns_resolver.go, resolver/dns/dns_resolver_test.go
=> dns resolver: exponential retry when getting empty address list

go16.go, go17.go, rpc_util_test.go
This is consistent with how io.ErrUnexpectedEOF is handled in a bunch of
other places (e.g. stream.go, server.go), and signals to
application-level code that the error is retryable.
=> Convert io.ErrUnexpectedEOF to a codes.Internal-marked status in toRPCerr.

.travis.yml
This can be reverted when https://github.com/golang/go/issues/26576 is resolved.
=> disable go1.6 travis tests

clientconn.go, internal/transport/http2_client.go, internal/transport/transport.go, internal/transport/transport_test.go, status/status.go
This is the latest (hopefully last?) incarnation of the transport monitor refactor, as last reviewed by @MakMukhi in https://github.com/grpc/grpc-go/pull/2032.
The code has not changed since his last review in that PR, except that I've rebased against master. A problem I found with the rebase was that the e2e test `TestFailFast` was failing. I solved that with 17d4a9029890b4f4fd114479d3c02e4525d362c3, but it's probably not the real solution - I suspect there may be an incorrect state transition. I'll look into that.
In the meantime, I wanted to submit this to start getting any preliminary review as well as to see whether tests would fail in CI: in https://github.com/grpc/grpc-go/pull/2032 tests were failing in CI but not locally.
=> internal: remove transportMonitor, replace with callbacks

clientconn.go, internal/transport/http2_client.go, internal/transport/transport.go, internal/transport/transport_test.go, status/status.go
Reverts grpc/grpc-go#2219 because of #2251
=> Revert "internal: remove transportMonitor, replace with callbacks"

internal/internal.go, internal/transport/handler_server.go, server.go, test/channelz_test.go, test/end2end_test.go
This facility isn't actually necessary if we start an `http.Server` the way a user would.  This exercise also led to a bug fix in the handler transport that results in a goroutine leak in some error + race conditions.
=> internal: remove TestingUseHandlerImpl

health/grpc_health_v1/health.pb.go, health/health.go, health/health_test.go
This PR fixes the failed build. The new `watch` method is not implemented.
=> health: update pb.go and add watch method

clientconn.go, clientconn_test.go, dialoptions.go
=> client: fix FailOnNonTempDialError and add a test for it

credentials/alts/utils.go, credentials/alts/utils_test.go
This API can be used by the client side after obtaining a peer object using `grpc.Peer` `CallOption`.
=> credentials/alts: add ALTS AuthInfoFromPeer API

rpc_util.go
Compress can return an error, which was not checked.
=> Check error when calling compressor.Compress

stream.go
The Write call returns a non-status-package error in the event of a race with the server ending the stream.  This is not allowed by our API or expected by our tests.  Returning a nil even in the event of an error is acceptable, and matches historical behavior.
=> stream: never return errors from CloseSend

clientconn.go, clientconn_test.go, internal/transport/transport_test.go, vet.sh
**Note**: Do not squash. There are two commits with very different fixes. They have to be applied at the same time, which is why they're in one PR. They should be merged as two commits.
- Fix race in ac.tearDown and ac.resetTransport
- Fix `transport_test.go` issues
See commits for extensive details.
=> internal: fix build

resolver_conn_wrapper_test.go
Do a non-blocking send so if dial is called again in a retry, it won't block forever.
=> tests: fix leak in TestDialParseTargetUnknownScheme

rpc_util.go, server.go
This change splits recv() into two functions so it can be used by processUnary.
=> server: reuse function recv() in processUnary

clientconn.go, clientconn_test.go, test/channelz_test.go
When onClose occurs during WaitForHandshake, it should immediately
exit createTransport instead of leaving CONNECTING and entering READY.
Furthermore, when any onClose happens, the state should change to
TRANSIENT FAILURE.
Fixes #2340
Fixes #2341
Also fixes an unreported bug in which entering READY causes a
Dial call to end prematurely, instead of blocking until a READY
transport is found.
=> Fix onclose state transition

health/health.go
Refactor `status` variable name to `servingStatus` to avoid the complaint from Goland IDE about name conflict from the `status` package.
=> refactor variable name

clientconn.go, clientconn_test.go
Closing `ClientConn` sets `balancerWrapper` to nil.
If service config switches balancer, the new balancer will be notified of the existing addresses.
When these two happens together, there's a chance that a method will be called on the nil `balancerWrapper`. This change adds a check to make sure that never happens. 
fixes #2367
=> clientconn: not panic when service config updated while closing

internal/channelz/types_nonlinux.go
=> channelz: remove init logging

balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_remote_balancer.go
Warning is more appropriate per: https://github.com/grpc/grpc-go/blob/master/Documentation/log_levels.md#warning
=> grpclb: downgrade error logs  to warning

clientconn.go, clientconn_state_transition_test.go, clientconn_test.go, internal/testutils/pipe_listener.go, internal/testutils/pipe_listener_test.go, test/end2end_test.go
This CL fixes three problems:
- In clientconn_state_transitions_test.go, each time we set up a server to send
SETTINGS, we should also set up the server to read. This allows the client
to successfully send its SETTINGS.
- In clientconn.go, we incorrectly transitioned into TRANSIENT FAILURE when
creating an http2client returned an error. This should be handled in the outer
resetTransport main reset loop. The reason this became a problem is that the
outer resetTransport has very specific conditions around when to transition
into TRANSIENT FAILURE that the egregious transition did not have. So, it
could transition into TRANSIENT FAILURE after failing to dial, even if it
was trying to connect to a non-final address in the list of addresses.
- In clientconn.go, we incorrectly stay in …
=> internal: fix client send preface problems

clientconn.go, test/end2end_test.go
A deadlock can occur when a GO_AWAY is followed by a connection closure. This
happens because onClose needlessly closes the current ac.transport: if a
GO_AWAY already occured, and the transport was already reset, then the later
closure (of the original address) sets ac.transport - which is now healthy -
to nil.
The manifestation of this problem is that picker_wrapper spins forever trying
to use a READY connection whose ac.transport is nil.
=> internal: fix GO_AWAY deadlock

clientconn.go
Seems to fix https://travis-ci.org/grpc/grpc-go/jobs/443409852, but regardless
it's a more correct place for it to happen.
=> internal: transport nil should happen before backoff

test/go_vet/vet.go, vet.sh
- Take advantage of `grep`'s status code, where possible
- Make the appengine check in vet.go exit with non-zero status if an error is encountered
- Add "fail_on_output" for the `tee|read` that we do when the status code cannot be used, to make it clear what it's for
- Document all our various checks
=> internal: vet cleanups

internal/binarylog/binarylog.go, internal/binarylog/binarylog_end2end_test.go, internal/binarylog/binarylog_test.go, internal/binarylog/binarylog_testutil.go, internal/binarylog/env_config.go, internal/binarylog/env_config_test.go, internal/binarylog/method_logger.go, internal/binarylog/method_logger_test.go, internal/binarylog/sink.go, internal/transport/transport.go, rpc_util.go, server.go, stream.go
Also includes:
- Export `NewLoggerFromConfigString` so it can be also used when config string is specified in another way (e.g. command line flag)
- Export `Logger` so user can install custom sink
- Add temp file sink implementation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/2388)
=> binarylog: call binary log in Client and Server

internal/binarylog/binarylog_end2end_test.go
Entry for `cancel` was not logged when the RPC finished. Retry will get the expected result.
=> binarylog: fix racy TestClientBinaryLogCancel

clientconn.go, internal/grpcsync/event.go, stream.go, test/end2end_test.go
This allows the initial RPC(s) an opportunity to apply settings from the service config; without this change we would still block, but only after observing the current service config settings.
=> client: block RPCs early until the resolver has returned addresses

clientconn.go, resolver_conn_wrapper.go
=>  resolverWrapper: remove the watcher goroutine

proxy.go, proxy_test.go
Proxy-Authorization: https://tools.ietf.org/html/rfc7235#section-4.4
The 'Basic' HTTP Authentication Scheme: https://tools.ietf.org/html/rfc7617
updates #2422
=> proxy: support basic authentication

internal/transport/bdp_estimator.go
=> transport: increase BDP limit to 16MB to improve performance for high latency networks

credentials/credentials.go, credentials/internal/syscallconn.go, credentials/internal/syscallconn_appengine.go, credentials/internal/syscallconn_nonappengine.go, credentials/internal/syscallconn_test.go
Also skip wrapping if `rawConn` doesn't implement `syscall.Conn`.
=> internal: move syscall.Conn wrapper into a separate package

clientconn.go, clientconn_test.go, dialoptions.go, internal/envconfig/envconfig.go, vet.sh
#2406
Possible settings of this environment variable:
- "hybrid" (default; removed after the 1.17 release): do not wait for handshake before considering a connection ready, but wait before considering successful.
- "on" (default after the 1.17 release): wait for handshake before considering a connection ready/successful.
- "off": do not wait for handshake before considering a connection ready/successful.
This setting will be completely removed after the 1.18 release, and "on" will be the only supported behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/2464)
=> client: add GRPC_GO_REQUIRE_HANDSHAKE options to control connection behavior

balancer/balancer.go, balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_test.go, balancer_conn_wrappers.go, balancer_switching_test.go, internal/internal.go
This can happen when resolved addresses contain grpclb address, but grpclb is
not registered.
=> grpclb: filter out grpclb addresses if balancer in use is not grpclb

clientconn.go, clientconn_state_transition_test.go, clientconn_test.go, internal/envconfig/envconfig.go, internal/transport/http2_client.go, internal/transport/transport.go
Previously, the transport was able to reset via the retry loop,
or via the event closures calling resetTransport. This meant
a very large amount of synchronization was necessary: one
reset meant the other had to not reset; state had to be kept
at the addrconn; and very subtle interactions were hard to
reason about.
This change removes the ability for event closures to directly
reset the transport. Instead, they signal to to the retry
loop about the event, and the retry loop is always the single
place that retries occur.
This also allows us to refactor the address switching logic
into a much simpler for loop inside the retry loop instead of
using addrConn state to keep track of an index.
=> internal: refactor transport to single retry mechanism

channelz/service/service.go, internal/channelz/funcs.go, test/channelz_linux_go110_test.go, test/channelz_test.go, test/healthcheck_test.go
GetTopChannels, GetServers and GetServerSockets have a max_results field to limit max length of response data, but server does not care the value.
=> Respect max_results in listing methods

examples/features/cancellation/README.md, examples/features/cancellation/client/main.go, examples/features/cancellation/server/main.go
=> example: cancellation

examples/helloworld/greeter_server/main.go
This PR adds a log to [`SayHello`](). This makes server logic be more clear.
=> enhance log for hello world SayHello

examples/features/debugging/README.md, examples/features/debugging/client/main.go, examples/features/debugging/server/main.go
=> example: debugging

examples/features/name_resolving/README.md, examples/features/name_resolving/client/main.go, examples/features/name_resolving/server/main.go
=> example: name_resolving

resolver_conn_wrapper.go
Hi, I find function split2 behavior is different with comment，fix it does not seem to have any effect with parseTarget function!
=> internal: change split2() comment to be consistent with behavior

rpc_util.go
The status package now has `Convert()` and `Code()` utilities.
This patch updates the deprecation description for `ErrorDesc()` and
`Code()` to recommend using those functions, and forward the deprecated
functions to use the `status.Code()` and `status.Convert()` functions.
=> rpc_util: update deprecated messages

channelz/service/service.go, internal/channelz/funcs.go, test/channelz_test.go
GetServer is not implemented for now.
And also fixes GetChannel, GetSubchannel, GetSocket response when requested id not found.
By gRFC spec, it should return NotFound status code, not empty message with OK.
=> Implement GetServer method for channelz

internal/grpctest/grpctest.go
Before:
> ![image](https://user-images.githubusercontent.com/26072277/50935544-39efbd80-1421-11e9-8e8f-9fd5948947a5.png)
After:
> ![image](https://user-images.githubusercontent.com/26072277/50935569-4bd16080-1421-11e9-8858-bc6510ca5d8c.png)
=> fix grpctest comments to be more readable

dialoptions.go, internal/envconfig/envconfig.go, test/channelz_test.go, test/end2end_test.go, test/gracefulstop_test.go, test/healthcheck_test.go
=> client: make handshake required 'on' by default, not 'hybrid'

interop/client/client.go, interop/test_utils.go
Implementing the [google default creds](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#google_default_credentials) interop test for go.
This test case was added in https://github.com/grpc/grpc/pull/17213. The existing OAuth creds test cases turned out to not be great first for google default creds testing, so https://github.com/grpc/grpc/pull/17213 got rid of those tests and created a new dedicated test for google default creds. This PR does that and also gets rid of the now-unneeded (we thought they would be needed earlier) OAuth test scenarios with plain ALTS.
=> Add google_default_credentials interop test case for go

internal/envconfig/envconfig.go
https://github.com/grpc/grpc-go/commit/6cc789b34b72d30116d6139ae4af87d5bfc91478 made `envconfig.RequireHandshakeOn` the default when unspecified by environment variable, but missed a fallthrough leading to `GRPC_GO_REQUIRE_HANDSHAKE=on` specifying `envconfig.RequireHandshakeHybrid`.  This change adds the missing fallthrough.
=> client: fix handling of GRPC_GO_REQUIRE_HANDSHAKE=on to not interpret as "hybrid"

balancer/balancer.go, balancer_v1_wrapper.go, picker_wrapper.go, test/end2end_test.go
- Remove unnecessary checks for `failfast`
- Call `put` reliably
- Document that `done` may not be called in the v2 balancer if it returns a `SubConn` that is not valid (`nil` or did not come from grpc)
- Add timeouts to RPCs in `TestServerGoAway`
- Minor code cleanups
=> client: minor v1 balancer wrapper fixes

rpc_util.go
=> grpc: limit reader with maxReceiveMessageSize

internal/transport/http2_server.go
to avoid leak at https://github.com/grpc/grpc-go/blob/2259ee6f1a16ff0bb8776e5d2476a2b12e8fda04/internal/transport/controlbuf.go#L648
Client transport already has the buffer: https://github.com/grpc/grpc-go/blob/2259ee6f1a16ff0bb8776e5d2476a2b12e8fda04/internal/transport/http2_client.go#L1368
=> internal: add buffer for channelz flowcontrol getter channel

internal/transport/http2_server.go, test/end2end_test.go, test/stream_cleanup_test.go
`RSTStreamFrame`s used to be ignored by the server transport, if a trailer had already been put into the transport's control buffer. If loopy writer couldn't write anything into a stream because of an error on the client side, then this trailer would never be sent. At that point, server would receive an `RSTStreamFrame` from client. But this `RSTStreamFrame` would be ignored because a trailer was already put into the control buffer. This would keep the stream open and in memory on the server side.
With this change, a `cleanupStream` item is put into the transport's control buffer, whenever an `RSTStreamFrame` is received by the server, even after a trailer has been put into the buffer. When loopy writer handles this `cleanupStream`, the stream will be closed and cleaned up.
=> Fixes established streams leak in the loopy writer.

clientconn.go
This log doesn't print useful information, and causes flooding
=> internal: delete an info log

examples/features/keepalive/server/main.go
Correct the max connection idle time comment from `10` to `15`
=> examples: correct typo in keepalive example

clientconn_test.go, dialoptions.go, internal/internal.go, keepalive/keepalive.go, server.go, test/channelz_test.go, test/end2end_test.go
Also fix tests that relied upon setting lower values.
This is in preparation for the fix to issue #2638
=> keepalive: apply minimum ping time of 10s to client and 1s to server

examples/features/name_resolving/README.md, examples/gotutorial.md
Correct spelling for documents.
=> examples: remove duplicated words

Documentation/gomock-example.md, examples/features/name_resolving/README.md
Correct some words spelling for reading more easily.
File changed:
* Documentation/gomock-example.md
* examples/features/name_resolving/README.md
=> doc: fix typos

internal/transport/http2_server.go
Solving #2593 
An easy solution might be to add one condition in `internal/transport/http_server2.go` to just return the `ErrConnClosing` as it is, and `toRPCError` will convert it to the said format. 
Better might be a function to handle it right there, but question is where should the function be kept?
=> transport: return ErrConnClosing for proper handling

clientconn.go, clientconn_test.go, internal/envconfig/envconfig.go, test/gracefulstop_test.go, vet.sh
This removes RequireHandshakeHybrid support and changes the default behavior
to RequireHandshakeOn. Dial calls will now block and wait for a successful
handshake before proceeding. Users relying on the old hybrid behavior (cmux
users) should consult https://github.com/soheilhy/cmux/issues/64.
Also, several tests have been updated to take this into consideration by
sending settings frames.
=> transport: remove RequireHandshakeHybrid support

balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_test.go
=> grpclb: drop only when at least one SubConn is ready

clientconn.go
=> client: reset backoff to 0 after a connection is established

balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_picker.go, balancer/grpclb/grpclb_remote_balancer.go, balancer/grpclb/grpclb_test.go
Keep the drop index from the previous picker when regenerating picker due to
subchannel state change. Only reset the drop index when picker is regenerated
because of a serverlist update.
fixes #2623
=> grpclb: keep drop index unless a new serverlist is received

stats/stats.go, stats/stats_test.go, stream.go
Currently, it is not possible to access trailers from within a
stats.Handler. The reason is that both stats.Handler and
ClientStream.Trailer require a lock on the ClientStream.
A workaround would be to start a separate goroutine that will call
ClientStream.Trailer asynchronously, but that requires careful
coordination and we can quite easily make the trailer metadata available
to the stats.Handler directly.
Use case: an interceptor that processes trailer metadata for each
streaming RPC after the stream has finished. Note that a
StreamClientInterceptor returns immediately, before the stream has
finished and before the trailer metadata is available.
=> Add Trailer to client-side stats.End

test/creds_test.go
Although it is spelling mistakes, it might make an effect while reading.
=> Trivial fix typo

internal/transport/http2_server.go
=> server: send RST_STREAM after trailers if client has not half-closed

balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_remote_balancer.go, balancer/grpclb/grpclb_test.go
Use pickfirst as balancing policy for backends. It can only set at init time.
Does not support changing with service config now.
=> grpclb: support pickfirst

internal/transport/handler_server.go
`Write` can be called concurrently, for which it calls the `do` function.
As `WriteStatus` can close the `ht.writes` in parallel as well the `Write`
will try to write into the `ht.writes` in the `do` function, this can
lead into a panic. As there is no real usability on closing this channel
we can simply leave it to the garbage collector so we can avoid panic
during an execution.
Signed-off-by: André Martins <aanm90@gmail.com>
=> transport: do not close channel that can lean to panic

balancer/balancer.go, picker_wrapper.go, test/balancer_test.go
Special case: when SubConn returned by Picker is not Ready, call done before
looping back to re-pick.
=> balancer: make sure non-nil done returned by Pick is called

test/balancer_test.go
The same test was changed by two PRs, merge didn't catch the conflict
=> internal: fix pickoptions in balancer_test

clientconn.go, clientconn_state_transition_test.go, clientconn_test.go, dialoptions.go
Adds a mutex around getMinConnectTimeout to guard against races. See
https://travis-ci.org/lyuxuan/grpc-go/jobs/505558388 for an example
race.
Fixes #2687.
=> internal: fix Dial_OneBackoffPerRetryGroup

encoding/encoding.go
Calling strings.ToLower with an empty value is a waste.
=> encoding: check whether encoding.Name() is empty before calling strings.ToLower

credentials/google/google.go, interop/client/client.go, interop/test_utils.go
This is the Go analogue of https://github.com/grpc/grpc-java/pull/5475.
Manually tested that the interop test works in all environments.
=> credentials: add compute engine channel creds

stream.go
=> stats: add WireLength to stats.InPayload

internal/transport/http2_client.go, internal/transport/transport.go, server.go, stream.go, trace.go
The client-side traces were otherwise only showing `RPC: to <nil>`,
which is not helpful.
Also clean up construction of traceInfo and firstLine in a few places.
=> Restore client-side remote address in traces.

server.go
Previously only `unknown service <x>` was returned, which is misleading
when the service is known but the method is unknown.
=> server: Improve error message when an unknown method is invoked.

internal/syscall/syscall_nonlinux.go
The same as https://github.com/grpc/grpc-go/pull/2373.
@dfawley Could you help review this? Thank you.
Signed-off-by: Yangmin Zhu <ymzhu@google.com>
=> syscall: remove logging in init().

balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_remote_balancer.go, balancer/grpclb/grpclb_test.go, balancer/grpclb/grpclb_test_util_test.go
When losing connection to remote balancer and no backend from remote balancer is Ready.
=> grpclb: fallback after init

clientconn.go, clientconn_test.go
=> Fix DialContext when using a timeout

balancer/balancer.go, balancer/xds/edsbalancer/balancergroup.go, balancer/xds/edsbalancer/balancergroup_test.go, balancer/xds/edsbalancer/edsbalancer.go, balancer/xds/edsbalancer/edsbalancer_test.go, balancer/xds/edsbalancer/test_util_test.go, balancer/xds/edsbalancer/util.go, balancer/xds/edsbalancer/util_test.go, balancer/xds/xds.go, balancer/xds/xds_client.go, balancer/xds/xds_client_test.go, balancer/xds/xds_test.go
Until https://github.com/envoyproxy/go-control-plane/issues/168 is fixed
=> internal: balancer/xds go1.12 only

credentials/credentials.go, credentials/credentials_test.go
=> tls: append h2 to tlsconfig.NextProtos

Documentation/rpc-errors.md
The link for example in the documentation for RPC errors redirects to the wrong URL.
This PR fixes that
Fixes #2752
=> fixing broken link in rpc-error doc

Documentation/keepalive.md
The link for enforcement policy in the keepalive docs is wrong.
fixes #2754
=> doc: fixing link in keepalive docs

interop/alts/server/server.go
=> credentials/alts: Support UDS addresses in ALTS interop test server

vet.sh
From [release notes](https://golang.org/doc/go1.12#vet):
The go vet command has been rewritten to serve as the
base for a range of different source code analysis tools. See
the golang.org/x/tools/go/analysis
package for details. A side-effect is that go tool vet
is no longer supported. External tools that use go tool vet must be
changed to use go vet. Using go vet instead of go tool vet should work
with all supported versions of Go.
=> Use 'go vet' and not 'go tool vet'.

internal/transport/transport.go
Clarifies that the method GracefulStop does not block, but instead will cause the transport to close after all RPCs are finished. (AFAICT)
=> internal: tweak ClientTransport.GracefulClose documentation

server.go
Instead of functions. So custom server options can be made by wrapping an
EmptyServerOption.
=> server: define ServerOption as interfaces

credentials/alts/alts.go
Using `defer` before checking `NewClientHandshake` and `NewServerHandshake` error can cause panic. If these two APIs failed, `chs` and `shs` will be `nil` when `Close` is called.
=> credentials/alts: Panic Bug Fix

balancer/balancer.go, balancer/grpclb/grpclb.go, balancer_v1_wrapper.go, clientconn.go, resolver/resolver.go
Right now balancer get the full dial target string through `cc.Target()`. However, some balancers(e.g. xds) want the endpoint part of the target and getting the endpoint part from the original string is not trivial. So this pr passes in the parsed target through `BuildOption` for balancer consumption.
=> balancer: provide parsed target through BuildOptions

balancer/xds/internal/const.go, balancer/xds/lrs/lrs.go, balancer/xds/lrs/lrs_test.go, balancer/xds/xds.go, balancer/xds/xds_client.go, balancer/xds/xds_client_test.go, balancer/xds/xds_lrs_test.go, balancer/xds/xds_test.go
cc.Target() returns the full target string which includes scheme, authority and endpoint, while xds should send the endpoint part of it for xDS requests. 
Also, cc.Target() has been deprecated and BuildOptions.Target field is being provided for parsed target info.
=> xds: use BuildOptions.Target.endpoint string instead of deprecated cc.Target

internal/transport/http2_client.go, internal/transport/transport.go, internal/transport/transport_test.go
=> transport: Fix the inconsistency between headerChan and headerDone

balancer_conn_wrappers.go
=> balancer: stop using picker from old balancer with switching balancers

balancer/balancer.go, balancer/base/balancer.go, balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_config.go, balancer/grpclb/grpclb_config_test.go, balancer/grpclb/grpclb_test.go, balancer/xds/edsbalancer/balancergroup.go, balancer/xds/xds.go, balancer/xds/xds_lrs_test.go, balancer/xds/xds_test.go, balancer_conn_wrappers.go, balancer_switching_test.go, clientconn.go, clientconn_test.go, internal/internal.go, resolver/resolver.go, resolver_conn_wrapper.go, service_config.go, service_config_test.go, serviceconfig/serviceconfig.go, test/channelz_test.go, test/end2end_test.go, test/healthcheck_test.go
This is still subject to change; pushing now to get initial round of feedback.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/2732)
=> balancer/resolver: add loadBalancingConfig and pre-parsing support

clientconn.go
=> addrConn: not reset backoff if update address in TransientFailure

balancer/grpclb/grpclb_remote_balancer.go
Only when sub-balancer is round-robin (not pick-first), subconns are cached.
The actual problem solved by this:
If pick-first is set as the sub-balancer, when switching sub-balancer from round-robin to pick-first, the first subconn creation will fail because no address is available (`grpclb: failed to create new SubConn: grpc: cannot create SubConn with empty address list`).
What should happen is, no picker is updated, and all RPCs block and wait. But because we will always regenerate and update picker, a TransientFailure error picker will be set and all RPCs will fail.
=> grpclb: only force update picker when cache is used

balancer/xds/edsbalancer/balancergroup.go, balancer/xds/edsbalancer/balancergroup_test.go, balancer/xds/edsbalancer/edsbalancer.go, balancer/xds/edsbalancer/edsbalancer_test.go, balancer/xds/edsbalancer/test_util_test.go, balancer/xds/internal/internal.go, balancer/xds/internal/internal_test.go, balancer/xds/lrs/lrs.go, balancer/xds/lrs/lrs_test.go
This PR also changed the balancer ID in balancer group from string to a struct, so we don't need to parse the string to build locality when reporting loads. But the struct is a new one instead of the locality proto type, because proto messages are not hashable, and cannot be used a map keys.
=> xds: rpc counts (start/end) per locality

balancer/xds/lrs/lrs.go, balancer/xds/lrs/lrs_test.go, balancer/xds/xds.go, balancer/xds/xds_client.go, balancer/xds/xds_client_test.go
1. Stop setting xds request.ResourceName, and always set metadata
- ResourceName is not the same format as user's dial target. (`test_service.test_namespace.traffic_director.com` vs `test_namespace:test_service`).
- The solution today is to always include `GrpcHostname` in metadata, with the value set to dial target.
1. Stop comparing xds response's Name with user's dial target
- Name doesn't match user's dial target for the same reason as above
1. Set lrs request.ClusterName to be the cluster name returned from first lrs response
- Root cause is also the same as above
=> xds: fix difference between user target name and resource name

internal/transport/http2_server.go, test/end2end_test.go, test/stream_cleanup_test.go
Before this fix, stream is removed from activeStreams in finishStream,
which happens when the service handler returns status, without waiting
for the status to be sent by loopyWriter. If GracefulStop() is called in
between, it will close the connection (because activeStreams is empty),
which causes the RPC to fail with "transport is closing". This change
moves the activeStreams cleanup into loopyWriter, after sending status
on wire.
fixes #2703
=> test: fix Test/GracefulStop by not removing activeStreams too aggresivelly

test/end2end_test.go
I was trying to run this test and I had copied the name of the function
from the comment, and it took a good while to figure out why
`go test -run` was returning `testing: warning: no tests to run`.
=> Fix a typo in the comment.

test/end2end_test.go
This test sometimes fails with `error creating stream due to
DeadlineExceeded`. It's very hard to reproduce (failed twice in 100000
runs). Extend the RPC timeout in case it's too short.
Also refactor the test a little bit so the error log shows where the
test actually fails.
=> test: extend RPC timeout for TestHTTPHeaderFrameErrorHandlingHTTPMode

test/end2end_test.go
In the end of the test, 10 RPCs are made to make sure data is sent to
the second server. The first RPC of these 10 is made right after the
second server's listener receives a connection. But at this time, the
connectivity state on the client side is not set to READY yet (though
ac's state should be either connecting or ready, the race between ac
and balancer could cause cc to still be in transient failure). So the
first RPC fails due to transient failure, but the following 9 will
succeed.
fixes #2822
=> test: fix GoAwayThenClose by wait for cc state change

examples/features/encryption/README.md
Currently, ALTS needs special permission to be used on GCP.
=> examples: note about ALTS special access permission on GCP

test/end2end_test.go
#2330 
- Removed some old code which has a TODO asking for it's removal once Go1.6 and Go1.7 support is gone.
- Cleaned up a couple of error messages along with it.
=> test: end2end test cleanup http handler server

balancer/grpclb/grpclb_test.go
By waiting for a more stable state before making the test RPCs.
=> test: fix flaky grpclb TestDropRequest

test/channelz_test.go, test/end2end_test.go
#2330
- Seperated and documented the options for client and server sides.
- Better support for multiple grpc.Servers. This will be used in other
improvements that I have in the works.
- Moved some common functionality from channelz_test.go to
end2end_test.go.
- Added an option to use the default health service implementation, instead
of each test creating a new health.Server and passing it in. The
individual tests have not been changed in this PR. I will do that in a
follow up PR to keep the changes to a reasonable size.
- Fixed one of the tests which had to be fixed because of the separation
of client and server configs.
=> test: end2end test improvements separate server and client configs.

clientconn.go, health/client.go, health/client_test.go, internal/internal.go, stream.go, test/healthcheck_test.go
1. Make newStream() take string (for method) so it can be used for out-of-band load reporting (which will also be a stream on an addrConn)
1. move healthcheck (streaming) related functions into a function
1. make ac.newClientStream not a method of addrConn
- so it's (should be) easier to merge with cc.newStream()
=> client: addrConn NewStream and health check cleanup

balancer/grpclb/grpclb_remote_balancer.go
With pickfirst, the same SubConn is reused, only addresses are updated.
But backends and fallbacks may need different credentials. This change
force-removes all SubConns when switching fallback.
=> grpclb: recreate SubConns when switching fallback

balancer.go, dialoptions.go, vet.sh
Also, deprecate WithBalancerName (was experimental).
The decision of whether something may be removed is based on if it was marked experimental as of v1.0/GA or upon its introduction, in accordance with https://github.com/grpc/grpc-go/blob/master/Documentation/versioning.md.
=> docs: clarify "deprecated" to indicate whether some features may be removed in 1.x

balancer/roundrobin/roundrobin_test.go, balancer_test.go, clientconn.go, clientconn_state_transition_test.go, clientconn_test.go, dialoptions.go, internal/envconfig/envconfig.go, pickfirst_test.go
This is a breaking change, made in accordance with our [versioning policy](https://github.com/grpc/grpc-go/blob/master/Documentation/versioning.md) and with notice provided in #2406.
Fixes #2406
=> client: remove option to send RPCs before HTTP/2 handshake is completed

internal/transport/http2_client.go
=> client: fix canceled vs deadline exceeded double-check logic

server.go
We have a stream-heavy workloud and this accounts for 2% of our allocations.
=> server: avoid an unnecessary allocation per-RPC for OK status

balancer/grpclb/grpclb_remote_balancer.go
So grpclb client will reconnect when the connection is down (e.g. proxy
drops the server side connection but keeps the client side).
=> grpclb: enable keepalive

balancer/grpclb/grpclb_test.go, clientconn.go, clientconn_state_transition_test.go, internal/transport/http2_client.go, stream.go, test/end2end_test.go, test/goaway_test.go
Fixes #2767
Before these fixes, it was possible to see errors on new RPCs after a
connection began draining, and before establishing a new connection.  There is
an inherent race between choosing a SubConn and attempting to creating a stream
on it.  We should be able to avoid application-visible RPC errors due to this
with transparent retry.  However, several bugs were preventing this from
working correctly:
1. Non-wait-for-ready RPCs were skipping transparent retry, though the retry
design calls for retrying them.
2. The transport closed itself (and would consequently error new RPCs) before
notifying the SubConn that it was draining.
3. The SubConn wasn't synchronously updating itself once it was notified about
the closing or draining state.
4. The SubConn would go into the …
=> client: fix race between transport draining and new RPCs

status/status.go
It's not expected for `FromError` to allocate when you have no error
=> status: avoid allocations when returning an OK status

status/status.go, status/status_ext_test.go
In the [go2 error proposal](https://go.googlesource.com/proposal/+/master/design/29934-error-values.md) the `Is` function adds matching of error targets.
[On this line](https://github.com/golang/exp/blob/sumdb/v0.0.2/errors/wrap.go#L58) of the proposal implementation, there is an interface check for Is, to provide
custom implementation of this matching.
gRPC status errors that are defined as a var, currently don't successfully work
with this function when crossing the gRPC boundary, as the pointer values will
not be equivalent.
Ideally, the following should work across gRPC boundaries:
```
var ErrAuthInvalidToken = status.Error(codes.Unauthenticated, "Invalid token")
_, err := grpcClient.Call(...) // Returns the above
errors.Is(err, ErrAuthInvalidToken) == true
```
=> status: Implement *statusError.Is

server.go, stats/stats_test.go
Fixes #2692 which was incompletely fixed by #2711.
Also adds a basic unit test which provides scaffolding for further testing of
the stats logic.
=> server: populate WireLength on stats.InPayload for unary RPCs

clientconn_test.go
Swap the `<-done` and `if numConns < 2` to make sure `numConns++` happens before reading
=> test: fix race reading while incrementing

balancer/base/balancer.go, pickfirst.go
The pickfirstbalancer and baseBalancer are logging a lot of  messages under normal operation.
Those messages can not be associated to a server connection because no connection address is part of the messages. They are messages that are only useful when debugging issues.
Only log them when the verbose level is at least 2, to reduce the amount
of log messages under normal operation.
=> Log pickFirstBalancer and baseBalancer log messages only for verbosity level >=2

server.go
Sadly trace.FromContext isn't cheap because it uses a string as the context key which leads to allocations. This patch makes the function a no-op when tracing is disabled, as it should be.
=> server: avoid call to trace.FromContext and resulting allocations when tracing is disabled

stream.go
To not set new attempt when newAttemptLocked fails to get a transport.
related to #2952 #2954
=> stream: fix panic caused by failing to get a transport for a retry attempt

internal/transport/flowcontrol.go
***Description***
Among 8 read/write operations to f.delta, 7 of them are protected by `f.mu.Lock()`, but the one at line 173 of file grpc/internal/transport/flowcontrol.go is not protected. In order to avoid potential data race here, I use `defer f.mu.Unlock()` to make sure that all usages of f.delta is in critical section.
***Buggy code***
The last read operation of f.delta happens after `f.mu.Unlock()`:
https://github.com/grpc/grpc-go/blob/92635fa6bffd9db9b2cca8ce8f978bfebabd9c29/internal/transport/flowcontrol.go#L162-L174
=> transport: Change Unlock to defer Unlock, to avoid data race

stream.go
This is a follow-up fix for #2958
=> stream: call stats handler if the attempt failed to get transport

internal/transport/controlbuf.go, internal/transport/http2_client.go, internal/transport/http2_server.go
Addresses CVE-2019-9512 (Ping Flood), CVE-2019-9514 (Reset Flood), and CVE-2019-9515 (Settings Flood).
=> transport: block reading frames when too many transport control frames are queued

internal/transport/http2_client.go
The code is simple enough, the defer is pure cost.
=> transport: remove defer in http2Client.getStream

internal/transport/http2_client.go
Suggested in https://github.com/grpc/grpc-go/pull/2980.
=> transport: make http2Client.getStream() only return a stream.

test/bufconn/bufconn.go, test/bufconn/bufconn_test.go
This PR adds implementations for the `Set(Read|Write)Deadline` functions of the [`net.Conn`](https://golang.org/pkg/net/#Conn) interface. This functionality can be useful when testing I/O edge-cases or unreliable network connections.
=> bufconn: Implement read/write deadlines

vet.sh, xds/experimental/xds_experimental.go, xds/internal/balancer/xds.go, xds/internal/balancer/xds_lrs_test.go, xds/internal/balancer/xds_test.go, xds/internal/internal.go, xds/internal/resolver/xds_resolver.go, xds/internal/resolver/xds_resolver_test.go
This resolver doesn't do much at this point, except returning an empty
address list and a hard-coded service config which picks the xds
balancer with a round_robin child policy.
Also moved the xdsConfig struct to the xds/internal package and exported
it as LBConfig, so that both the resolver and the balancer packages can
make use of this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/2967)
=> Implementation of the xds_experimental resolver.

examples/helloworld/greeter_client/main.go, examples/helloworld/greeter_server/main.go
Use the exported Get methods instead of directly accessing the data to safely return an empty string if the fields have a value of nil.
Submitted a pull request to update the documents as well.
https://github.com/grpc/grpc.io/pull/47
=> example: use proto message Get methods in helloworld

internal/transport/http2_server.go
Avoid lock contention by deriving the transport context from context.Background() (without wrapping in a Cancel/Deadline context). This will make canceling a child context not recurse into the parent.
https://github.com/grpc/grpc-go/issues/1918
=> transport: derive transport context from context.Background

benchmark/primitives/context_test.go
Add a micro benchmark for context.WithValue() to compare using local and global keys.
=> Add a micro benchmark for context.WithValue()

internal/transport/transport_test.go
* Added a test for keepalive dormancy.
* Added comments to all tests, explicitly stating their intention.
* Used the exported APIs wherever possible instead of relying on
internal state.
* Specifically checked for GoAway reason, instead of just relying on the
receipt of a goaway.
* Improved error messages printed upon test failures.
* Made the tests more consistent with each other in terms of variables
names, whitespace usage etc.
Once this PR is approved and merged, we can move all these tests to a
separate file.
=> Keepalive test improvements.

.github/stale.yml
...for automatically pinging and closing issues that require reporter clarification after 7 and 14 days, respectively.
=> github: add stalebot config

.github/mergeable.yml
This PR causes mergeable to enforce the following rules on PRs:
- must include a "Type:" label
- must include either the "no release notes" label or a Release milestone
=> github: add mergeable config

go.mod
https://golang.org/doc/go1.12#modules
With go 1.13, a go command will add `go 1.13` to `go.mod` if `go` directive doesn't already exist, potentially because of the language changes https://golang.org/doc/go1.13#language.
=> modules: add go 1.11 to go.mod

balancer/grpclb/grpclb_util.go, balancer/grpclb/grpclb_util_test.go
Before the fix, if the timer to remove a SubConn fires at the same time
NewSubConn cancels the timer, it caused a mutex leak and deadlock.
=> grpclb: fix deadlock in grpclb connection cache

test/channelz_test.go
- Send a message from the test server that the client can block on to know for sure the RPC's header was sent.
- Don't receive in the test server so we can violate flow control
- Set a deadline on the RPC so it can't hang forever.
=> test: fix channelz test for violating flow control

service_config.go, service_config_test.go
If `loadBalancingConfig` is not specified in the service config, this has no effect.
Relevant [part](https://github.com/grpc/proposal/blob/master/A24-lb-policy-config.md#proposal) of gRFC:
```proto
message ServiceConfig {
...
// Multiple LB policies can be specified; clients will iterate through
// the list in order and stop at the first policy that they support. If none
// are supported, the service config is considered invalid.
repeated LoadBalancingConfig load_balancing_config = 4;
}
```
=> client: consider service config invalid if loadBalancingConfig contains no supported policy

health/server.go
The `Check` method of the `Server` struct only reads some information from itself. And the other methods do both read and write operations.
In this case, many people usually use `sync.RWMutex` instead of `sync.Mutex`. It not only improves performance, but also clarifies what the method does.
This is not a necessary change, but I think it will help in many ways.
=> health: Use sync.RWMutex instead of sync.Mutex

internal/transport/transport.go
`headerChan` isn't necessarily closed when `closeStream` returns; block on it in `waitOnHeader`.
=> transport: fix race between operateHeaders and closeStream and reading headers

internal/transport/http2_server.go, internal/transport/transport.go
Previously this would fall into returning the same `s.header.Copy(), nil`
condition at the end of the function, returning an empty `MD`.  After a recent
change it would instead check `headerValid`, which is always false on servers,
and return `nil` and an error.  Callers were ignoring this error so no behavior
change was seen, but there is no need to check `s.headers` here.
=> transport: don't check s.header on the server side in Stream.Header

xds/internal/balancer/edsbalancer/balancergroup.go, xds/internal/balancer/edsbalancer/balancergroup_test.go, xds/internal/balancer/edsbalancer/edsbalancer.go, xds/internal/balancer/edsbalancer/test_util_test.go
This is a preparing change to support priority failover. It adds `start()` and `close()` to balancer group, so we can have a balancer group that's not in use, but has all the data and is ready to be started (think about a lower priority when the higher priority is in use).
A balancer group is split into two parts: static and dynamic:
- static: the data from EDS, and gets updated even if balancer group is closed
- balancer IDs and builders, addresses for each balancer
- dynamic: the sub-balancers
- These are only created when the balancer group is started. They are closed when the balancer group is closed.
- And only when the balancer group is started, the sub-balancers will get address updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> xds: make balancer group restartable

xds/internal/balancer/xds_client.go, xds/internal/client/helper.go, xds/internal/client/helper_test.go
The format of the bootstrap file will be as follows:
```
{
  "xds_server": {
    "server_uri": <string containing URI of xds server>,
    // List of channel creds; client will stop at the first type it
    // supports.
    "channel_creds": [
      {
        "type": <string containing channel cred type>,
        // The "config" field is optional; it may be missing if the
        // credential type does not require config parameters.
        "config": <JSON object containing config for the type>
      }
    ]
  },
  "node": <JSON form of Node proto>
}
```
Also, the bootstrap file will be read everytime a new xDS client is created.
=> xds: incorporate changes to bootstrap file format.

internal/transport/http2_server.go, internal/transport/transport.go, server.go
=> server: add ServerOption HeaderTableSize

backoff.go, backoff/backoff.go, balancer/grpclb/grpclb.go, clientconn.go, clientconn_test.go, dialoptions.go, health/client.go, internal/backoff/backoff.go, resolver/dns/dns_resolver.go, xds/internal/balancer/lrs/lrs.go, xds/internal/balancer/xds_client.go
Implement missing pieces for connection backoff.
Spec can be found here:
https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md
* Added a new type (marked experimental), ConnectParams, which contains
the knobs defined in the spec (except for minConnectTimeout).
* Added a new API (marked experimental), WithConnectParams() to return a
DialOption to dial with the provided parameters.
* Added new fields to the implementation of the exponential backoff in
internal/backoff which mirror the ones in ConnectParams.
* Marked existing APIs WithBackoffMaxDelay() and WithBackoffConfig() as
deprecated.
* Added a default exponential backoff implementation, for easy use of
internal callers.
Fixes #2724
=> client: add WithConnectParams to configure connection backoff and timeout

encoding/encoding.go, encoding/gzip/gzip.go, rpc_util.go
Fixes #2635 
For large messages this generates far less garbage than `ioutil.ReadAll()`.
Implement for gzip - RFC1952 requires it, and the Go implementation checks it already (modulo 2^32).
=> Use exact size, if known, to allocate decompression buffer

examples/features/authentication/server/main.go, examples/features/cancellation/server/main.go, examples/features/compression/server/main.go, examples/features/deadline/server/main.go, examples/features/debugging/server/main.go, examples/features/encryption/ALTS/server/main.go, examples/features/encryption/TLS/server/main.go, examples/features/errors/server/main.go, examples/features/interceptor/server/main.go, examples/features/keepalive/server/main.go, examples/features/load_balancing/server/main.go, examples/features/metadata/server/main.go, examples/features/multiplex/server/main.go, examples/features/name_resolving/server/main.go, examples/features/reflection/server/main.go, examples/features/retry/server/main.go, examples/features/wait_for_ready/main.go, examples/helloworld/greeter_server/main.go, examples/route_guide/server/server.go
=> examples: add Unimplemented___Server to all example servers

balancer/balancer.go, balancer/base/balancer.go, balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_test.go, balancer_conn_wrappers.go, balancer_conn_wrappers_test.go, balancer_switching_test.go, clientconn.go, clientconn_test.go, internal/internal.go, resolver/dns/dns_resolver_test.go, resolver/manual/manual.go, resolver/resolver.go, resolver_conn_wrapper.go, resolver_conn_wrapper_test.go, service_config.go, service_config_test.go, serviceconfig/serviceconfig.go, test/channelz_test.go, test/end2end_test.go, test/healthcheck_test.go, xds/internal/balancer/xds.go, xds/internal/resolver/xds_resolver.go, xds/internal/resolver/xds_resolver_test.go
Fixes #2102, #2856, #2727 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/2951)
=> resolver: add State fields to support error handling

balancer/grpclb/grpclb_test.go, balancer/roundrobin/roundrobin_test.go, internal/binarylog/binarylog_end2end_test.go, reflection/serverreflection_test.go, stats/stats_test.go, test/end2end_test.go, test/healthcheck_test.go
This omits xds for now, since those protos were not generated with the latest protoc-gen-go version in the repo.
#3069
=> test: embed Unimplemented___Server in every service

examples/features/debugging/server/main.go
This pr add missing UnimplementedGreeterServer in order to address this issue: https://github.com/grpc/grpc-go/issues/3069
=> examples: add UnimplementedGreeterServer in debugging example

clientconn.go, resolver/resolver.go, test/end2end_test.go
Fixes #3038
By default it is not set and the dialed target is used as the authority for all load balanced endpoints. This enables load balanced clients to use per-endpoint authorities when the address's ServerName is set.
=> clientconn: override authority with address's ServerName, if set

internal/binarylog/env_config.go
Detected by Debian Lintian tool while packaging Hugo.
Many thanks!
=> cleanup: fix typo in binarylog, "allowd" → "allowed"

proxy_test.go
**_Description_**
In google.golang.org/grpc/proxy_test.go, func testHTTPConnect, line 122, a local unbuffered channel `done` is created. `done` is only used two places: receive in main goroutine and close in a new goroutine. However, because `err != nil` may cause the new goroutine to return, the close instruction may never be reached,  making the receive in main goroutine be blocked forever.
**_How I fix this bug_**
I put `defer close(done)` at the beginning of the new goroutine, so `close(done)` will always be executed, no matter what branch is taken next.
=> proxy_test: Fix a goroutine-leak bug in testHTTPConnect

credentials/credentials.go, credentials/credentials_test.go
Correctly split authorities with IPv6 addresses and no port, e.g. `[::1]`.
=> credentials: Use net.SplitHostPort to safely parse IPv6 authorities in ClientHandshake

test/end2end_test.go
- Made these tests use the default health service implementation
wherever possible.
- Refactored some common code used in these tests into helper functions.
- Added function comments for all these tests to improve readability.
In a follow up PR, I will be moving all these tests into
healthcheck_test.go.
#2330
=> Make healthcheck tests in end2end_test.go more readable.

balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_remote_balancer.go
This PR fix typo for grpclb token key from `lbTokeyKey` to `lbTokenKey`.
=> fix typo for grpclb token key

dialoptions.go, resolver_conn_wrapper.go, resolver_conn_wrapper_test.go
Use separate mutexes to guard the underlying `resolver` and the `polling` channel in the `resolverWrapper`. 
The data race was happening between the write to `ccr.resolver` in `newCCResolverWrapper` using the result from the call to `rb.Build`, and the read of `ccr.resolver` in `ResolveNow` (which can be triggered through the following code path: `rb.Build-->ccr.ReportError-->ccr.poll-->ccr.resolveNow`.
After fixing the race in the code, I also figured that there was a race in the test code because the `resolverBackoff` package variable was modified in some tests, but not in some others, causing a weird data race. I added a `TestMain` to override that variable with an empty `backoff.Config`, so all calls to `Backoff` will return 0.
=> Fix a data race in resolver_conn_wrapper.go

clientconn.go
The newly added lines are mostly stolen from existing Java and C-core
documentation.
=> Add more details in ClientConn GoDoc.

internal/cache/timeoutCache.go, internal/cache/timeoutCache_test.go, xds/internal/balancer/edsbalancer/balancergroup.go, xds/internal/balancer/edsbalancer/balancergroup_test.go, xds/internal/balancer/edsbalancer/edsbalancer_test.go
When a locality is removed from EDS response, it's corresponding
sub-balancer will be removed from balancer group.
With this change, the sub-balancer won't be removed immediately. It will
be kept in a cache (for 15 minutes by default). If the locality is
re-added within the timeout, the sub-balancer in cache will be picked
and re-used.
=> xds: cache locality (sub-balancer)

internal/transport/http2_client.go, internal/transport/keepalive_test.go
This commit makes the following changes:
- Keep track of the time of the last read in the transport.
- Use this in the keepalive implementation to decide when to send out
keepalives.
- Address the issue of keepalives being sent every [Time+Timeout] period
instead of every [Time] period, as mandated by proposal A8.
Proposal A8 is here:
https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md
=> client: Keepalive pings should be sent every [Time] period

examples/route_guide/client/client.go, interop/http2/negative_http2_client.go
Made via:
```sh
grep -rl 127.0.0.1 | grep -v _test.go | xargs sed -i 's/127.0.0.1/localhost/g'
```
=> interop, examples: use localhost instead of 127.0.0.1

examples/features/debugging/client/main.go, examples/features/debugging/server/main.go, examples/helloworld/mock_helloworld/hw_mock.go, examples/route_guide/mock_routeguide/rg_mock.go, reflection/grpc_testingv3/README.md, reflection/grpc_testingv3/testv3.pb.go, vet.sh
Manual change + mockgen
Remaining `x/net/context` will be updated separate (to update xds protos)
```
xds/internal/proto/envoy/api/v2/eds/eds.pb.go
18:     context "golang.org/x/net/context"
xds/internal/proto/envoy/api/v2/cds/cds.pb.go
28:     context "golang.org/x/net/context"
xds/internal/proto/envoy/service/load_stats/v2/lrs/lrs.pb.go
15:     context "golang.org/x/net/context"
xds/internal/proto/envoy/service/discovery/v2/ads/ads.pb.go
12:     context "golang.org/x/net/context"
xds/internal/proto/udpa/service/orca/v1/orca/orca.pb.go
14:     context "golang.org/x/net/context"
```
=> cleanup: no x/net/context

balancer/grpclb/grpclb.go, balancer/grpclb/grpclb_remote_balancer.go, balancer/grpclb/grpclb_test.go, vet.sh
This is necessary because there's another way to select grpclb (by specifying grpclb in service config's balancing policy field). So it's possible that grpclb is picked, but resolver doesn't have any balancer addresses.
When an update without balancer address is received, grpclb closes the underlying ClientConn to remote balancer, and enters fallback mode.
Note that grpclb waits until the ClientConn and the RPC goroutines are actually closed to do the fallback work. This can avoid race caused by async close.
fixes #3064
=> grpclb: enter fallback if no balancer addresses are available

internal/testutils/pipe_listener_test.go, test/bufconn/bufconn_test.go, test/end2end_test.go
***Description***
The 4 test functions modified in this PR share a similar problem: some child goroutines will be leaked in certain cases (like timeout). The root cause is always a pair of send and receive of a channel. Normally they will synchronize, but when one goroutine is killed earlier, then another goroutine will be blocked.
Although `t.Fatal()` will shutdown the test goroutine, other blocking goroutines won't be released because ["Calling FailNow does not stop those other goroutines." ](https://golang.org/pkg/testing/#T.FailNow)
***How it is fixed***
Since in all these 4 functions, channel's send is in the child goroutines, then our fix is easy: we add buffer to the channel. In this way, send will not be blocked, while receive will still wait for send. 
***Example***
Take …
=> test & testutils: prevent goroutine leaks in test functions

Documentation/server-reflection-tutorial.md
added `git submodule update --init` to readme instructions to pull in missing dependencies.
=> docs: fix reflection doc

resolver/resolver.go, resolver_conn_wrapper.go
These fields will be used by resolver implementations which need to talk
to a remote name resolver.
=> resolver: Add new fields to resolver.BuildOption struct to support dialing a remote name resolver

balancer_conn_wrappers.go, internal/buffer/unbounded.go, internal/buffer/unbounded_test.go
This PR moves the unbounded buffer implementation found in
`scStateUpdateBuffer` to the internal package. It also makes the buffer
work with `interface{}` type.
This addresses a TODO in the existing code. This will also help with the
eventual `BalancerManager` implementation which will supersede the
`ccBalancerWrapper` implementation found in balancer_conn_wrappers.go.
This can also be used by the `xdsClient` to buffer different responses from
the `ADS` stream.
=> Add a general purpose unbounded buffer implementation

xds/internal/balancer/edsbalancer/balancergroup_test.go, xds/internal/balancer/edsbalancer/edsbalancer.go, xds/internal/balancer/edsbalancer/edsbalancer_test.go
Unknown and healthy are both considered healthy.
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/health_check.proto#envoy-api-enum-core-healthstatus
=> eds: skip unhealthy endpoints

.travis.yml
The example tests were causing travis timeout recently.
=> travis: move example tests to a separate run

test/end2end_test.go
Adds a regression test inspired by #3135.
Fixes #3135
=> test: add test of malformed gzip payload

xds/internal/balancer/edsbalancer/balancergroup.go, xds/internal/balancer/edsbalancer/edsbalancer.go, xds/internal/balancer/edsbalancer/edsbalancer_test.go, xds/internal/balancer/edsbalancer/priority.go, xds/internal/balancer/edsbalancer/priority_test.go, xds/internal/balancer/edsbalancer/test_util_test.go
Each priority maps to a balancer group.
When a priority is in use, its balancer group is started, and it will close the balancer groups with lower priorities. When a priority is down (no connection ready), it will start the next priority balancer group.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3066)
=> xds: support priority

status/status_test.go, test/end2end_test.go, test/retry_test.go, xds/internal/balancer/lrs/lrs_test.go
Generated protobuf messages contain internal data structures
that general purpose comparison functions (e.g., reflect.DeepEqual,
pretty.Compare, etc) do not properly compare. It is already the case
today that these functions may report a difference when two messages
are actually semantically equivalent.
Fix all usages by either calling proto.Equal directly if
the top-level types are themselves proto.Message, or by calling
cmp.Equal with the cmp.Comparer(proto.Equal) option specified.
This option teaches cmp to use proto.Equal anytime it encounters
proto.Message types.
=> cleanup: fix generic comparisons on protobuf messages

attributes/attributes.go, attributes/attributes_test.go, resolver/resolver.go, vet.sh
This change deprecates the `Type` and `Metadata` fields in `resolver.Address`.
=> resolver: introduce attributes package and use it for Address and State

resolver/dns/dns_resolver.go, resolver/passthrough/passthrough.go
=> resolver: re-add dns and passthrough packages as references to internal versions

clientconn.go, vet.sh
Contains all of #3151; will be merged only after that PR.
=> vet: revise staticcheck strategy

balancer/grpclb/grpclb.go, internal/resolver/dns/dns_resolver.go, internal/resolver/dns/dns_resolver_test.go
This implements part of https://github.com/grpc/proposal/pull/164, and should not be merged until November 8th, pending its approval.
=> dns: disable SRV record lookups unless grpclb is imported

xds/internal/balancer/xds_client.go, xds/internal/client/bootstrap/bootstrap.go, xds/internal/client/bootstrap/bootstrap_test.go
This will be useful for a few reasons:
- This package will expose a test-only function to build a good `Config` object which will be used by the `xdsResolver` while creating the `xdsClient`. We will have to change the `xdsClient` to have the `Config` dependency injected into it, instead of it being instantiated in the `NewClient` function.
- Other tests can also use this function and will not have to much around with setting the bootstrap file environment variable
=> xds: Move bootstrap functionality to a new package.

internal/transport/handler_server.go, internal/transport/http2_client.go, internal/transport/http2_server.go, stats/stats.go, stats/stats_test.go
This pull request originated with the discussion on https://github.com/grpc/grpc-go/issues/3132.
Per that conversation, currently, there isn't a good way to get at the header and trailer information in the stats handler. That information is valuable because it allows tagging telemetry (metrics, logs, and spans) by information container in the header. For example you might want to encode the peer service into a header field and then tag all metrics by peer service to allow slicing metrics by caller.
This pr attaches the header and trailer information to the `InHeader`, `InTrailer`, `OutHeader`, and `OutTrailer`, stats messages per @dfawley 's suggestion. That means that the trailer information is now attached to `InTrailer` and `End`, which is duplicate information, but I didn't want to …
=> stats: attach metadata to In/Out Headers/Trailers

internal/transport/http2_client.go
Apply this PR, the server will response with grpc-encoding whatever the client set. test via wireshark.
update #2786
=> client: set grpc-accept-encoding header based on outgoing compressor

xds/internal/balancer/xds_client.go, xds/internal/client/eds.go, xds/internal/client/eds_test.go, xds/internal/client/eds_testutil.go, xds/internal/client/lds_test.go, xds/internal/client/rds.go, xds/internal/client/rds_test.go, xds/internal/client/types.go, xds/internal/client/v2client.go, xds/internal/client/v2client_test.go
Similar to RDS handling.
Caching is not needed with the updated spec: https://github.com/envoyproxy/envoy/blob/master/api/xds_protocol.rst#resource-hints
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3181)
=> xds: handle EDS in xds client

internal/transport/http2_client.go, internal/transport/http2_server.go, test/channelz_test.go
This PR contains the server side changes corresponding to the client
side changes made in https://github.com/grpc/grpc-go/pull/3102.
Apart from the fix for the issue mentioned in
https://github.com/grpc/grpc-go/issues/2638, this PR also makes some
minor code cleanup and fixes the channelz test for keepalives count.
=> server: Keepalive pings should be sent every [Time] period

vet.sh, xds/internal/client/client.go, xds/internal/client/client_test.go, xds/internal/client/eds_test.go, xds/internal/client/fakexds/fakexds.go, xds/internal/client/lds_test.go, xds/internal/client/rds_test.go, xds/internal/client/v2client_test.go
* Add a helper to the fakexds package to return a ClientConn talking to
the fake server.
* Tests will make use of this ClientConn wherever required, or they will
directly pass the fake server's address as the balancerName to the
xdsclient.New() function, thus exercising that code path as well.
=> xds: Don't override dialFunc in xdsClient in tests.

benchmark/benchmain/main.go
I decided to reuse the same flag used to enable client-side keepalives for this one. Thought there wouldn't be a case where one would want to enable just the server side keepalives in benchmarks.
=> benchmark: Enable server keepalive in benchmarks

internal/resolver/dns/dns_resolver.go, internal/resolver/dns/dns_resolver_test.go, resolver_conn_wrapper.go
Also:
- Fully ignore `NewServiceConfig` calls in `resolver_conn_wrapper`
- Fix `dns_resolver_test` to actually test service configs, and a handful of cleanups
Fixes #3199
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3201)
=> dns: do not call NewServiceConfig when lookups are disabled

internal/resolver/dns/dns_resolver.go, internal/resolver/dns/dns_resolver_test.go
This cannot be merged until the pickfirst and round_robin balancers are updated to return an error from `UpdateState` when zero addresses are provided, as we currently rely upon the polling behavior of DNS to refresh on error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3165)
=> dns: stop polling for updates; use UpdateState API

xds/internal/client/cds.go, xds/internal/client/cds_test.go, xds/internal/client/client.go, xds/internal/client/types.go, xds/internal/client/v2client.go
Export the `cdsUpdate` struct and its fields so that the watch call in xdsClient can simply be a passthrough to the v2Client (the way EDS watch is implemented).
=> xds: Minor refactoring, prep for CDS LB policy

xds/internal/balancer/xds_client_test.go, xds/internal/balancer/xds_lrs_test.go, xds/internal/balancer/xds_test.go, xds/internal/client/fakexds/fakexds.go, xds/internal/client/fakexds/lrsserver.go
And move LRS test server to fakexds package.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3209)
=> xds: cleanup eds tests to use fakexds server

internal/resolver/dns/dns_resolver.go, internal/resolver/dns/dns_resolver_test.go
Reverts grpc/grpc-go#3165
The change breaks clients using DNS resolver, including all interop tests: https://github.com/grpc/grpc/issues/21301
=> Revert "dns: stop polling for updates; use UpdateState API"

internal/proto/grpc_service_config/example_test.go, xds/internal/balancer/config.go, xds/internal/balancer/xds.go, xds/internal/balancer/xds_client_test.go, xds/internal/balancer/xds_client_wrapper.go, xds/internal/balancer/xds_lrs_test.go, xds/internal/balancer/xds_test.go
LRS is disabled if this field is nil (is unset in json). The xds server
will be used if it's a pointer to an empty string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3210)
=> xds: change lrs server name field in xds balancer config to a string pointer

credentials/alts/internal/handshaker/handshaker.go
These APIs are unexported and always take 1 as an input. Therefore, we can simply remove the input argument.
=> credentials/alts: Simplify ALTS acquire and release APIs

internal/resolver/dns/dns_resolver.go, internal/resolver/dns/dns_resolver_test.go, internal/resolver/dns/go113.go
This cherry-picks #3165 (e5e980f2766388fc243cc4cf20c59b9c13affa8c) and adds #3212's methodology for determining if the error is truly an error or just an empty TXT record.
=> dns: reapply "dns: stop polling for updates; use UpdateState API"

server.go
Continuing the war on stacks, we can reduce the amount of stack required
per-RPC by combining defers from different components into one.
Each defer statement in process{Unary,Streaming}RPC goes on the stack
and occupies about 56-64 bytes the entire lifetime of an RPC, which
could be very long. More importantly, a call to runtime.morestack is
often required to allocate a new, larger stack when the handler
goroutine runs out of stack memory (Go's default stack size is 2 KiB).
Before:
$ go tool objdump <binary> | grep "TEXT.*processUnaryRPC(SB)" -A 10 | grep "SUBQ.*SP"
server.go:867   0x9132fb    4881ec80030000      SUBQ $0x380, SP
$ go tool objdump <binary> | grep "TEXT.*processStreamingRPC(SB)" -A 10 | grep "SUBQ.*SP"
server.go:1099  0x9151bb    4881ec68020000      SUBQ $0x268, SP
After:
$ …
=> server.go: combine defers to reduce stack usage

xds/internal/client/rds.go, xds/internal/client/rds_test.go, xds/internal/client/v2client_test.go
The client will look only at the last route in the list (the default
route), whose match field must contain a prefix field whose value is the
empty string and whose route field must be set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3239)
=> xds: Update the check for match field when handling an RDS response.

xds/experimental/xds_experimental.go, xds/internal/client/rds.go, xds/internal/client/rds_test.go
- install cds balancer by importing package cdsbalancer
- `net.SplitHostPort` fails when target doesn't have port, but we want to use the original string instead
=> xds: small fixes

xds/internal/balancer/xds_client_test.go, xds/internal/balancer/xds_client_wrapper.go
Errors will be handled specifically, depending on whether it's a
connection error or other types of errors.
Without this fix, balancer's callback will be called with <nil> update,
causing nil panic later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3240)
=> xds: skip callback if xds client reports error

examples/features/interceptor/README.md
`some-secrete-token` -> `some-secret-token`
=> Fix typo in README.md

xds/internal/balancer/xds_lrs_test.go, xds/internal/testutils/channel.go, xds/internal/testutils/fakexds/client.go
* Changed the `TestXDSLoadReporting` to simply verify that the edsBalancer starts a loadReport stream with the appropriate arguments. We should verify activity on the loadReport stream like how often load is reported, what values are reported in other tests (xdsClient tests).
* Added a new testutils/fakexds package. This will eventually contain the server as well, and will be used by callers as `fakexds.Client` and `fakexds.Server`. The existing testutils.xdsclient.go will eventually be phased out.
This PR is just the start of the test cleanup. I have lots more lined up, but it just became a little unmanageable after a point. So, will send out in bunches.
=> xds: Improve xds_lrs_test.go

dialoptions.go
Tell people to replace Dial + WithTimeout by DialContext + context.WithTimeout.
=> godoc: clarify WithTimeout deprecation note

xds/internal/client/cds.go, xds/internal/client/cds_test.go, xds/internal/client/client_test.go, xds/internal/client/eds.go, xds/internal/client/eds_test.go, xds/internal/client/lds.go, xds/internal/client/rds.go, xds/internal/client/types.go, xds/internal/client/v2client.go, xds/internal/client/v2client_ack_test.go, xds/internal/client/v2client_test.go
The client will send a request with version/nonce after receiving a
response, to ack/nack.
Ack versions for different xds types are independent.
Some other changes
- merge sendRequests to one shared function, with fields for version/nonce
- deleted enum for xds types, and always use const URL string
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3227)
=> xds: support ack/nack

balancer/grpclb/grpclb_picker.go, balancer/grpclb/grpclb_remote_balancer.go, balancer/grpclb/grpclb_test.go
Small refactor of tests:
- Add a channel to remoteBalancer on which to send received stats messages
- Change runAndGetStats to runAndCheckStats to allow for faster successful test
runs (no longer need to sleep for one whole second per test).
- Remove redundant leak check from runAndCheckStats, otherwise excess load
report messages not read from the channel will result in an infinite loop.
=> grpclb: do not send redundant empty load reports to remote LB

resolver_conn_wrapper.go
Although the existing code wasn't causing a deadlock or causing
goroutines to hang forever, this is cleaner and prevents any such thing
from happening in the future.
Fixes https://github.com/grpc/grpc-go/issues/3244.
=> grpc: Defer the unlock in newCCResolverWrapper

internal/profiling/buffer/buffer.go, internal/profiling/buffer/buffer_appengine.go, internal/profiling/profiling.go
=> profiling: Fix a data race in the circular buffer.

xds/internal/balancer/xds_test.go, xds/internal/testutils/channel.go, xds/internal/testutils/fakexds/client.go
* In xds_test.go:
* Get rid of the flaky logic to get the `latest fake edsLB` and use channels instead and make it explicit.
* Get rid of the `fakeXDSClient` implementation here and use the one from testutils instead.
* Use `testutils.Channel` wherever there is a need to wait with a timeout on a channel.
* Make necessary changes in the testutils package
* Also add a mutex to protect certain fields in `fakexds.Client` to prevent a data race.
=>  xds: Improve balancer/xds_test.go.

xds/internal/client/rds_test.go
The real test relies on req chan to know when the fake xds server
receives the request. Without this, req chan may unblock for the ack,
before the real watch handler is ready.
fixes #3264
=> xds test: read ACK to clear req chan

xds/internal/client/bootstrap/bootstrap.go, xds/internal/client/bootstrap/bootstrap_test.go
Changes to "xds_server" field in bootstrap file:
1. Field name is changed "xds_servers" (plural).
2. Field value should be a list of objects instead of a single object.
For now, we can ignore all entries except the first one.  In the future, we will add support for falling back to a secondary server when the primary is not reachable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3247)
=> xds: support multiple xds servers in bootstrap file

xds/internal/balancer/xds_client_test.go, xds/internal/balancer/xds_test.go, xds/internal/testutils/fakexds/client.go, xds/internal/testutils/fakexds/server.go
Simplified the tests by only testing what is required and faking out
whatever can be faked out.
Also added a fakexds.Server implementation. Will switch other users of
the existing fakeserver implementation after this PR is merged.
=> xds: Improve xds_client_test.go

internal/resolver/dns/dns_resolver.go, internal/resolver/dns/dns_resolver_test.go
Fixes #3252 
This is not a regression caused by #3228 as best I can tell, so this will not be going into the 1.26 release today.
=> dns: report errors from A record lookups instead of zero addresses

trace.go, trace_test.go
This PR fix `methodFamily` logic according to its go doc string and add a ut for it.
=> trace: fix getting family for the method

Documentation/encoding.md, codec.go, encoding/encoding.go, encoding/proto/proto.go, encoding/proto/proto_test.go, internal/leakcheck/leakcheck.go, internal/transport/controlbuf.go, internal/transport/http2_client.go, internal/transport/http2_server.go, internal/transport/transport.go, preloader.go, server.go, stream.go, vet.sh
Performance benchmarks can be found below. Obviously, a 8 KiB
request/response is tailored to showcase this improvement as this is
where codec buffer reuse shines, but I've run other benchmarks too (like
1-byte requests and responses) and there's no discernable impact on
performance.
We do not allow reuse of buffers when stat handlers or binlogs are
turned on. This is because those two may need access to the data and
payload even after the data has been written to the wire. In such cases,
we never return the data back to the pool.
A buffer reuse threshold of 1 KiB was determined after several
experiments. There's diminished returns when buffer reuse is enabled for
smaller messages (actually, a negative impact).
```
unary-networkMode_none-bufConn_false-keepalive_false-benchTime_40s-trace_fa …
```
=> codec/proto: reuse of marshal byte buffers

xds/internal/client/cds_test.go, xds/internal/client/eds_test.go, xds/internal/client/lds_test.go, xds/internal/client/rds_test.go, xds/internal/client/testutil_test.go
Share code for `TestHandlexDSrequest()`. The tests do very similar things: start a watch and compare the response.
The tricky part is the different `watch` function parameters. To avoid using `interface{}` everywhere (that will bypass all type checks), each xDS has a separate `watch` function, and the test function `switch` on the typeURL to know which to call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3267)
=> xds: client test cleanup

xds/internal/client/rds_test.go
Clear ACK request before starting the real RDS tests. This should only be necessary for RDS tests because RDS needs an existing LDS.
similar to #3266
fixes #3278
=> xds: fix RDS flaky tests due to ACK

resolver_conn_wrapper.go
This PR fixes typo from `resolver.ClientConnection` to `resolver.ClientConn`.
=> Fix resolver.ClientConnection to resolver.ClientConn

balancer/grpclb/grpclb_picker.go
This PR fixes `lbpb` package name typo from `lbmpb` to `lbpb`.
=> fix lbpb package name typo

xds/internal/balancer/xds.go, xds/internal/balancer/xds_test.go
We will add fallback support back when the design is finalized. Before that, fallback makes the code quite hard to follow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3287)
=> eds: delete fallback related code from the EDS balancer

service_config.go
This PR renames `initialBackoffMS` to `initialBackoff`.
=> internal: fix initialBackoff typo

credentials/alts/internal/authinfo/authinfo.go, credentials/credentials.go, credentials/credentials_test.go, credentials/oauth/oauth.go, credentials/tls.go, internal/transport/handler_server.go, internal/transport/http2_client.go
This PR does the following: 
1. Define a tri-state security level (SecurityNone, IntegrityOnly and PrivacyAndIntegrity) indicating the protection level of an established channel. 
2. Create `ConnAuthInfo` type struct that is a wrapper of credentials.AuthInfo and also contains the security level of an established channel. Existing `TransportCredentials` implementations are modified to return `ConnAuthInfo` upon finishing the handshake.
3. Associate a security level to each `credentials.PerRPCCredentials` implementations (JWT, Oauth2).  
4. Enforce the security level check when attempting to send `PerRPCCredentials` on a channel. For backward-compatibility we sill preserve the original checking behavior (i.e., using `RequreTransportSecurity()`).
=> credentials: create API for transport security level information

grpc_test.go, internal/grpctest/tlogger/tlogger.go, internal/grpctest/tlogger/tlogger_test.go, test/end2end_test.go
Implemented a logger that logs to testing's T struct. Removed glogger import from two tests because this logger replaces the glogger in those tests. Only tests using grpctest's RunSubTests use this logger, as the T object logged to is updated in that function's loop.
updates https://github.com/grpc/grpc-go/issues/3006
=> grpctest: implement grpclogger using testing.T and inject in tests

.travis.yml, Makefile, security/advancedtls/advancedtls_test.go
This PR include the changes to:
~~1. change function name `NewClient` and `NewSever` to `NewClientCreds` and `NewServerCreds`, since the two functions are creating TransportCredentials~~
2. fix an internal error in advanced_tls.test. Previous check is to check against the prefix of the ServerName, which might be different in various environments. We'd better not rely on checking that.
=> advancedtls: fix internal tests

xds/internal/balancer/edsbalancer/eds_test.go, xds/internal/balancer/edsbalancer/xds_client_wrapper.go, xds/internal/balancer/edsbalancer/xds_client_wrapper_test.go, xds/internal/client/bootstrap/bootstrap.go, xds/internal/client/bootstrap/bootstrap_test.go, xds/internal/resolver/xds_resolver.go, xds/internal/resolver/xds_resolver_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3330)
=> xds: propogate bootstrap error to grpc.Dial

clientconn.go, rpc_util.go
Fixes #1287
Reviving #2535, which github would not allow me to reopen.  Regarding the comment about `ClientConn() *ClientConn` from that PR, I don't think we will need such a method unless we need to extend the functionality of the generated code.  In this unlikely case, we could add it when it is needed, but use a new interface name to reflect the new functionality.
cc @broady
=> client: add interface for ClientConn to be accepted by generated code

balancer/grpclb/grpc_lb_v1/load_balancer.pb.go, benchmark/grpc_testing/services.pb.go, channelz/grpc_channelz_v1/channelz.pb.go, credentials/alts/internal/proto/grpc_gcp/handshaker.pb.go, examples/features/proto/echo/echo.pb.go, examples/helloworld/helloworld/helloworld.pb.go, examples/route_guide/routeguide/route_guide.pb.go, go.mod, go.sum, health/grpc_health_v1/health.pb.go, interop/grpc_testing/test.pb.go, profiling/proto/service.pb.go, reflection/grpc_reflection_v1alpha/reflection.pb.go, reflection/grpc_testing/test.pb.go, stats/grpc_testing/test.pb.go, stress/grpc_testing/metrics.pb.go, test/grpc_testing/test.pb.go, xds/internal/proto/udpa/service/orca/v1/orca.pb.go
This PR updates grpc-go to use the new generated code from #1287.
=> protobuf: update protoc-gen-go version and generated code

security/advancedtls/advancedtls.go, security/advancedtls/advancedtls_integration_test.go, security/advancedtls/go.mod, security/advancedtls/go.sum
This PR involves the following changes in advancedtls library:
1. bump the gRPC dependency version to 1.27.0
2. make changes on advancedtls.go to align with the new changes of tls.go in gRPC library
3. some small fixes in advancedtls_integration_test.go
=> advancedtls: use grpc 1.27.0 and small fixes

balancer/base/balancer.go, balancer/roundrobin/roundrobin_test.go, balancer_conn_wrappers_test.go, test/channelz_test.go, test/healthcheck_test.go
Fixes #3353 
This is essential, or else the channel will not be usable (no SubConns) and the resolver will never check for any update.
=> balancer/base: consider an empty address list an error

rpc_util.go
Clarify measurement used for send/receive message size call options
=> client: clarify units of send/receive message size call options

interop/grpclb_fallback/client.go
This file uses unix.TCP_USER_TIMEOUT which is defined only in linux.
=> interop: Build grpclb_fallback/client.go only for linux.

internal/grpctest/tlogger.go
Added a mutex to tLogger to prevent data race conditions to the global tLogger's internals.
Fixes #3371
=> testutil: add a mutex to tLogger to protect errors map

server.go, test/server_test.go
Add two new APIs in NewServer:
* ChainUnaryInterceptor
* ChainStreamInterceptor
fixes #3185 
I refer to [chaining client interceptors implementation](https://github.com/grpc/grpc-go/pull/2696) .
Tests for these APIs are minimum implementation.
If it seems to be missing, please let me know.
---
Another point, 
There are interceptors for ServerOption.
* UnaryInterceptor
* StreamInterceptor
* ChainUnaryInterceptor
* ChainStreamInterceptor
And there are interceptors for DialOption.
* WithUnaryInterceptor
* WithStreamInterceptor
* WithChainStreamInterceptor
* WithChainUnaryInterceptor
IMO, These API names will cause confusion.
* Is prefix `With` necessary or not
* Is this interceptor `ClientIntereptor`  or `ServerInterceptor` ?
Then, should we change APIs such as WithUnaryServerInterceptor, …
=> interceptor: new APIs for chaining server interceptors.

xds/internal/client/v2client.go, xds/internal/client/v2client_test.go
This can happen when the xds ClientConn is in transient failure (a
config error on the server address or creds, or a connection error).
When this happens, the new watches should still be handled, and should
be notified of failure when timeout.
=> xds: client should handle new watch requests even if there's no working stream

vet.sh
It seems go vet was not being run on the packages.
https://github.com/grpc/grpc-go/pull/3396 contains fixes.
=> vet.sh: ensure vet runs on all packages

interop/xds/client/client.go
Corrects a mistake from https://github.com/grpc/grpc-go/pull/3326
@menghanl
=> test: include xDS package in test client dependencies

interop/xds/client/client.go
One more fix for this. `server_id` is actually unused in OSS, the client's rpc service should report the distribution by server hostname instead.
@menghanl
=> test: record peers by hostname in xds client

balancer/rls/internal/cache/cache.go, balancer/rls/internal/cache/cache_test.go
Contains enough functionality to start working on the users of this
cache: the LB policy, picker and cache expiry goroutine.
=> rls: Initial implementation of the LRU cache.

xds/internal/client/v2client.go, xds/internal/client/v2client_ack_test.go
Even if the new request is for a new watch.
None and version are reset on new ADS streams.
=> xds: include nonce from the most recent response in new requests

xds/internal/balancer/edsbalancer/eds_impl.go, xds/internal/balancer/edsbalancer/eds_impl_test.go
If drops exist in the previous response, but is removed from the new response, the picker should be updated.
=> xds: handle removing drops

internal/transport/handler_server.go, internal/transport/http2_client.go, internal/transport/http2_server.go, stats/stats.go
I was trying to debug why the `OutTrailer.WireLength` field was always zero and I discovered that it was never set. This is because Header and Trailer WireLengths are difficult to calculate. They are compressed with hpack after the stats handler is called.
I looked into attaching them but couldn't find a good way to defer these calls until after the headers are encoded and the lengths are known so instead, I opted for comments and deprecation.
This pr should make it easier for the next reader to understand what's going on.
- I added comments to the struct initializations to make it more clear to the next reader wire we don't have WireLength fields.
- I marked the `OutTrailer.WireLength` field as deprecated because it is never set. Happy to remove the field if that's preferred. Wanted to …
=> stats: add comments about why out headers and out trailers have no wire length

balancer/rls/internal/keys/builder.go, balancer/rls/internal/keys/builder_test.go
This will be used by the RLS LB policy when it is processing config
updates and needs to make a decision as to whether or not the new config
specifies a new KeyBuilderMap.
=> rls: Add an Equal method to the KeyBuilderMap type.

balancer/rls/internal/cache/cache.go, balancer/rls/internal/cache/cache_test.go
* Add a Resize method which will be invoked by the RLS LB policy when it
receives a new cacheSize in its ServiceConfig.
* Change the size fields in the cache to int64. This is the type of the
cacheSize field in the proto.
* Store the BackoffState field in the cache.Entry by value instead of as
a pointer because it doesn not buy us much (the backoff state is not
shared between the data cache and the pending cache).
* Some cleanup in the tests.
=> rls: Some minor updates to the RLS cache.

balancer/rls/internal/builder.go, balancer/rls/internal/config.go, balancer/rls/internal/config_test.go
1. Store the RLS server name (lookupService field) as a string instead
of as a resolver.Target as this is passed to grpc.Dial when creating
the control channel.
2. Store the default target specified in the ServiceConfig in a field in
the lbConfig struct.
3. Move some constants defined in builder.go to config.go because they
are only used in the latter.
=> rls: LB config cleanup

clientconn.go
clientconn getResolver scheme param unused
fix #3445
=> client: fix getResolver to use scheme param

test/kokoro/xds.sh
This will enable the script to checkout the corresponding version of `run_xds_tests.py` from the `grpc/grpc` repo when running on release branches.
Another option would be hardcoding in the corresponding internal config file for the job on each branch, which would be passed to the script as an environment variable (Kokoro does not currently set the branch as one of the environment variables it automatically provides). This would work fine but require modifying the version number manually upon every release when creating the new config file, which could be slightly error prone. 
This will need to be backported to the v1.28.x branch to work :)
cc @menghanl
=> kokora: checkout matching grpc/grpc branch for xds test

credentials/alts/alts.go
See https://github.com/grpc/grpc/pull/17598 for discussion
This change will make it consistent with C++ and Java ALTS implementation.
=> alts: add trailing dot to metadata.google.internal

README.md
This error can happen when long lived streams are used
together with KeepaliveParameters that regularly
shut down existing connections.
=> README: add KeepaliveParameters hint to FAQ

channelz/service/func_linux.go, channelz/service/service.go
convertToPtypesDuration is used only in linux. So, moving to the linux
specific file so that the staticchecker does not complain on dawrin.
Fixes #2047
=> channelz: Make staticchecker happy on darwin.

internal/transport/handler_server.go, internal/transport/http2_client.go, internal/transport/http2_server.go, stats/stats.go, stats/stats_test.go
Currently, the request compression is recorded (on `stats.OutHeader` client-side and `stats.InHeader` server-side), but the response compression is never recorded. Although these compression codecs are often the same, the gRPC compression specification (https://github.com/grpc/grpc/blob/master/doc/compression.md) states that it's valid for them to be different.
- The pull request captures the response compression (on `stats.InHeader` client-side and `stats.OutHeader` server-side).
- This pull request moves the two fields (`Compression` and `Header`) above the comment `The following fields are valid only if Client is true.` because they are now both valid on the server-side and client-side.
=> stats: set response compression codec on stats.InHeader and stats.OutHeader

balancer/rls/internal/picker.go, balancer/rls/internal/picker_test.go
This change only renames the type and reformats comment lines. No change
in functionality. The rename was deemed necessary once I started
implementing the balancer and wanted to be consistent. The builder is
named `rlsBB`, the balancer is named `rlsBalancer`, so the picker should
be `rlsPicker`. Also, this rename allows the field in the balancer which
caches the last picker to be named `picker`.
=> rls: Rename type `picker` to `rlsPicker`.

test/kokoro/xds.cfg, test/kokoro/xds.sh
Also reduce the size of the grpc/grpc download
Analog of https://github.com/grpc/grpc-java/pull/6857. This allows Kokoro to upload individual test logs for easier viewing on sponge/dashboards.
cc @menghanl
=> kokoro: allow individual test case logs for xds

clientconn.go, dialoptions.go
Hullo! I'm working with a system that talks to some things via grpc and some things not via grpc. (actually, talking over a UNIX domain socket via grpc :grimacing:).
The non-grpc things are mostly HTTP requests that we do need to proxy. The grpc things, as noted, as via local sockets, which _can't_ and shouldn't be proxied.
Providing our own dialer is an option, but this seems a little cleaner and like other folks might also find it useful.
=> client: add a WithNoProxy dialoption

test/kokoro/xds.cfg, test/kokoro/xds.sh
Cherry-pick of https://github.com/grpc/grpc-go/pull/3478
cc @menghanl
=> kokoro: allow individual test case logs for xds (v1.28.x backport)

balancer/rls/internal/keys/builder.go, balancer/rls/internal/keys/builder_test.go
cmp.Equal is not supposed to be used in production code because of its
propensity towards panicking.
This equality will eventually be checked from the LB policy when it gets
a service config update.
Fixes #3472
=> rls: Manually implement equality of key builder maps.

balancer/grpclb/grpclb_remote_balancer.go
Minor typo fix in grpclib_remote_balancer.go.
change balaner with balancer
=> cleanup: fix typo in grpclib_remote_balancer.go

balancer/base/balancer.go, balancer/roundrobin/roundrobin_test.go, xds/internal/balancer/edsbalancer/eds_impl_priority_test.go
Roundrobin will remove all SubConns. The ClientConn will set SubConn state change to shutdown, and the overall state will turn transient failure.
=> balancer: change roundrobin to accept empty address list

internal/transport/handler_server.go, internal/transport/handler_server_test.go
This PR changes the `serverHandlerTransport` code to take header metadata from the stream (set via invocations of `SetHeader`) into account, both when implicitly sending headers, or when explicitly sending headers via `SendHeader` (merging any previously set metadata with the additionally supplied one, as per the docs).
It also fixes an issue with `SendHeader` where modifications to the passed metadata map after the `SendHeader` call has already returned might still affect the header values that get written to the stream.
Please check out the first commit in this branch (`3140f261`) for a state that only has the modified test (which of course fails) added.
Fixes #3483.
=> transport: fix handling of header metadata in serverHandler

xds/internal/client/types.go, xds/internal/client/v2client.go, xds/internal/client/v2client_ack_test.go
This can happen when the watch is canceled while the response is on wire.
Also, tag ACK/NACK with the stream so nonce for a new stream doesn't get updated by a ACK from the previous stream.
=> xds: update nonce even if the ACK/NACK is not sent on wire

examples/features/health/README.md, examples/features/health/client/main.go, examples/features/health/server/main.go
=> examples: add example to show how to use the health service

credentials/tls.go
=> credentials: Update doc strings for NewClientTLSFromCert et. al.

clientconn.go, clientconn_test.go, dialoptions.go
This commit allows blocking clients to receive a more informative error
message than "context deadline exceeded", which is especially helpful in
tracking down persistent client misconfiguration (such as an invalid TLS
certificate, an invalid server that's refusing connections, etc.)
=> client: option to surface connection errors to callers

credentials/alts/internal/conn/record.go
Part of the the server-side `InBytes` buffer is eventually passed to `conn.NewConn()`. Since the connection resulting from calling that API stays open as long as the gRPC channel is open, the original 64KB `InBytes` buffer will stay references for the entire channel lifetime and will never be released. This PR fixes that issue.
=> credentials/alts: Properly release server InBytes buffer after the handshake is complete.

.travis.yml, README.md, go.mod, go.sum, reflection/grpc_reflection_v1alpha/reflection.pb.go
Need to also update a `pb.go` file due to changes in Go 1.14's `gofmt` and `go-cmp` to version 0.4 to bring in a bug fix needed by 1.14.
=> doc: update README for supported Go versions and travis for tests

clientconn.go, internal/transport/http2_client.go, internal/transport/transport.go, internal/transport/transport_test.go
`transport.TargetInfo` has a subset of the fields that `resolver.Address` has. Using the latter makes it possible to pass address attributes over to the transport layer, so that they can be passed to the credential handshaker. This is in preparation for upcoming changes to the make it possible to pass address attributes to the handshaker.
=> internal/transport: Get rid of TargetInfo struct.

credentials/alts/internal/conn/record.go
Reverts grpc/grpc-go#3513
The change breaks interop tests: https://github.com/grpc/grpc/issues/22650
=> Revert "credentials/alts: Properly release server InBytes buffer after the handshake is complete."

xds/internal/client/v2client_rds.go, xds/internal/client/v2client_rds_test.go
see also https://github.com/grpc/grpc/pull/22675
=> xds: accept either "" or "/" as the prefix for the default route

test/creds_test.go, test/end2end_test.go
Addresses a TODO in the code and reduces the size of end2end_test.go
ever so slightly.
=> test: Move creds related to tests to creds_test.go

internal/envconfig/envconfig.go
I think we need check GRPC_GO_IGNORE_TXT_ERRORS instead of GRPC_GO_RETRY for value of TXTErrIgnore variable.
=> env: check GRPC_GO_IGNORE_TXT_ERRORS env var

internal/syscall/syscall_nonlinux.go
vet started failing on darwin after the recent package related lint changes.
=> internal: add missing package comment

benchmark/stats/stats.go
If a benchmark run did not specify req/resp payload curve files, and the
result from that run is used on the `benchresult` binary, it will
segfault because there is no check for the presence of the payload curve
option before printing the set of features used. Added a sanity check
there.
Fixes #3552
=> benchmark: Fix segfault in benchmark code.

security/advancedtls/advancedtls.go, security/advancedtls/advancedtls_integration_test.go, security/advancedtls/advancedtls_test.go
The main purpose of this PR is to set a new enum field `VerificationAuthType` for users to choose their own verification levels. Users could have three levels of verification: certificate and hostname check, certificate check only, and no check. The reasons for this change is:
1. We used to determine which level users are intended to set by checking some particular fields, such as if user set the root credential reloading field, etc. This not only needs users to read comments carefully, but also add a lot of if-else statements in our code that is hard to debug. By asking users to explicitly choosing one level, in accompany with the custom verification check, we offer more flexible APIs for users.
2. This is also to keep implementation align with other languages, like the constants [in C …
=> advancedtls: add fine-grained verification levels in XXXOptions

internal/status/status.go
This is a serious problem for it to exist, as it allows an OK status to have a non-nil error representation.
=> status: remove Error method accidentally added to *Status

internal/transport/transport.go, server.go
Currently (go1.13.4), the default stack size for newly spawned
goroutines is 2048 bytes. This is insufficient when processing gRPC
requests as the we often require more than 4 KiB stacks. This causes the
Go runtime to call runtime.morestack at least twice per RPC, which
causes performance to suffer needlessly as stack reallocations require
all sorts of internal work such as changing pointers to point to new
addresses.
Since this stack growth is guaranteed to happen at least twice per RPC,
reusing goroutines gives us two wins:
1. The stack is already grown to 8 KiB after the first RPC, so
subsequent RPCs do not call runtime.morestack.
2. We eliminate the need to spawn a new goroutine for each request
(even though they're relatively inexpensive).
Performance improves across the board. The …
=> server.go: use worker goroutines for fewer stack allocations

test/kokoro/xds.sh
A la https://github.com/grpc/grpc-java/pull/6889. This avoids the need to rebuild the gRPC server every time the test starts a VM; saves 20 minutes per test run for Java.
=> kokoro: use xds-test-server image

test/kokoro/xds.sh
Cherry-pick of https://github.com/grpc/grpc-go/pull/3564
cc @menghanl
=> kokoro: use xds-test-server image (v1.29.x backport)

test/kokoro/xds.sh
Cherry-pick of https://github.com/grpc/grpc-go/pull/3564
cc @menghanl
=> kokoro: use xds-test-server image (v1.28.x backport)

interop/xds/client/client.go, test/kokoro/xds.sh
Some of the xDS test cases should not have any failed RPCs. This adds a flag that will cause the client to fail with an error if any expected RPCs fail. Support for setting the flag when appropriate is being added in grpc/grpc#22763.
cc @menghanl
=> interop: add --fail_on_failed_rpc xds client flag

attributes/attributes.go, attributes/attributes_test.go, balancer/weightedroundrobin/weightedroundrobin.go, balancer/weightedroundrobin/weightedwoundrobin_test.go, xds/internal/balancer/edsbalancer/eds_impl.go
* Add methods to the `weightedroundrobin` package to add/get `AddrInfo` to/from `attributes.Attributes`.
* Update the edsBalancer implementation to send the weights as attributes using these methods.
* Update `attributes.WithValues` to work with a nil receiver to avoid call sites from having to perform nil checks and creating empty `Attributes` before being able to use this method.
=> Pass weights to wrr balancer through attributes.

balancer/rls/internal/balancer.go, balancer/rls/internal/balancer_test.go, balancer/rls/internal/builder.go, balancer/rls/internal/client.go, balancer/rls/internal/client_test.go, balancer/rls/internal/config.go, balancer/rls/internal/config_test.go, balancer/rls/internal/picker_test.go, balancer/rls/internal/testutils/channel.go, balancer/rls/internal/testutils/fakeserver/fakeserver.go, internal/testutils/channel.go
This PR adds a skeleton RLS LB policy implementation with just the logic to handle creation of the control channel upon receipt of the service config. The code contains a lot of TODOs which will be handled in the upcoming PRs.
The PR also contains the following other minor changes:
* `rlsBuilder` now builds an RLS LB policy
* Added `testutils.Channel` type which supports a receive operation on a channel with a timeout. This is heavily used in tests. Updated existing tests to use this type.
=> rls: LB policy with only control channel handling

security/advancedtls/advancedtls_integration_test.go, security/advancedtls/advancedtls_test.go
This PR does two things:
1. add field names for the unit tests for better readability
2. change field name `clientGetClientCert` to `clientGetCert`, to keep it align with other names in the same struct
=> advancedtls: add field names for unit tests

interop/xds/client/client.go
cc @menghanl 
This plus https://github.com/grpc/grpc/pull/22810 should fix/avoid the flakes introduced by adding the `--fail_on_failed_rpc` checks.
=> interop: increase xds test client rpc timeout

xds/internal/balancer/balancergroup/balancergroup.go, xds/internal/balancer/balancergroup/balancergroup_test.go
- Stop sending empty update to sub-balancers at init time
- At init, when only one sub-balancer reports transient failure, wait for other sub-balancers
- When aggregating states, consider a sub-balancer turns Connecting from TransientFailure still in TransientFailure, so aggregated state doesn't stay connecting for a long time
=> balancergroup: fix connectivity state

xds/internal/client/v2client_rds.go, xds/internal/client/v2client_rds_test.go
Because we only use the default route, this is check only the default route. We will need to check other routes when we support them.
=> xds: reject RDS response containing match with case-sensitive false

security/advancedtls/advancedtls_integration_test.go
This is to fix https://github.com/grpc/grpc-go/issues/3587 and be a better replacement of https://github.com/grpc/grpc-go/pull/3590.
@menghanl Could you please also take a look and see if we have any alternatives here? Thank you so much in advance!
=> advancedtls: remove test.Fatal() from child goroutine

xds/internal/client/v2client_lds.go, xds/internal/client/v2client_lds_test.go, xds/internal/client/v2client_test.go
When LDS tells client to make an RDS request, ConfigSource should be set to ADS.
=> xds_client: make sure LDS sets ConfigSource to ADS

examples/features/debugging/README.md
The old link resulted in a 404. It appears that the slug generation has been changed to use `-` instead of `_`.
This PR replaces the url in the documentation example with a working one.
=> doc: update "A short introduction to Channelz" url

benchmark/benchmark.go
Without this change, these goroutines spin after the connection is closed, so when you run a series of benchmarks they get more and more bogged down by spinning goroutines.
=> benchmark: exit from UnconstrainedStreamingCall() when stream is canceled

credentials/credentials.go, credentials/credentials_test.go, credentials/local/local.go, credentials/local/local_test.go, internal/transport/http2_client.go, test/end2end_test.go, test/local_creds_test.go
This PR implements gRPC Go local credentials. 
The local credentials should be used in either a UDS and local TCP connection. The former will be associated with the security level `PrigvacyAndIntegrity` while the latter is associated with `NoSecurity`. Notice that local credentials will be used to migrate the call sites of WithInsecure used in local connections.
=> credentials: local creds implementation

credentials/alts/internal/conn/record.go
Fixed the documentation of ALTSRecordCrypto to match https://golang.org/pkg/crypto/cipher/#AEAD. `dst` and `plaintext` may overlap fully, as well as not overlap at all.
@cesarghali
=> Fix ALTS record crypto interface comments

internal/transport/controlbuf.go, internal/transport/http2_client.go, internal/transport/http2_server.go
Fixes #3560 
This code is quite dense, so I broke the change into two parts: the first should be purely moving checks around, and the second is the meat of the change.
=> transport: move append of header and data down to http2 write loop to save garbage

internal/internal.go, service_config.go, xds/internal/balancer/balancer.go, xds/internal/client/client_watchers_rds.go, xds/internal/client/client_watchers_rds_test.go, xds/internal/client/client_watchers_service.go, xds/internal/client/client_watchers_service_test.go, xds/internal/client/v2client_rds.go, xds/internal/client/v2client_rds_test.go, xds/internal/resolver/serviceconfig.go, xds/internal/resolver/serviceconfig_test.go, xds/internal/resolver/xds_resolver.go, xds/internal/resolver/xds_resolver_test.go, xds/internal/testutils/fakeclient/client.go
This change adds support for route action being weighted cluster (instead of just one cluster). We still only support the default route (the last in the list).
Changes:
- xds_client: handle RDS response's weighted cluster fields, and propagate the update to xds resolver (by adding a fields to `ServiceUpdate`.
- This makes `ServiceUpdate` not comparable by `==`, thus the updates to use `cmp.Equal`
- xds_resolver: marshal weighted cluster into balancer config, which picks weighted_target as the top level balancer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3613)
=> xds: handle weighted cluster as route action

xds/internal/client/client_watchers_service_test.go
This test was added in a different PR, and test failed after merging.
=> internal: fix errors after merging

xds/internal/balancer/edsbalancer/eds.go, xds/internal/balancer/edsbalancer/eds_impl.go, xds/internal/balancer/edsbalancer/eds_impl_priority.go, xds/internal/balancer/edsbalancer/eds_impl_priority_test.go, xds/internal/balancer/edsbalancer/eds_impl_test.go, xds/internal/balancer/edsbalancer/eds_test.go, xds/internal/balancer/edsbalancer/xds_client_wrapper.go, xds/internal/client/errors.go, xds/internal/testutils/fakeclient/client.go
EDS balancer ignores all errors before this change.
Changes in this PR:
- in xds_client
- add error types to all errors returned by the xds_client
- in EDS balancer
- handle errors from the callback
- handle errors from resolver update
- both could send a fake empty update to close sub-balancers, so this change also makes sure eds_impl handles empty update (especially as the first one) correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3645)
=> xds: handle errors in eds balancer

credentials/local/local_test.go
When doing an internal import of #3517, there was an error - `Failed to listen: listen tcp [::1]:10000: bind: permission denied` in `local_test.go`. This PR fixes the issue.
=> credentials/local: fix incorrect binding of listener port

xds/internal/resolver/serviceconfig_test.go, xds/internal/resolver/xds_resolver.go, xds/internal/resolver/xds_resolver_test.go
- generate service config to use pickfirst with no address, to put clientconn  into transient failure
- forward other errors
=> xds: handle errors in xds resolver

xds/internal/client/client_callback.go, xds/internal/client/client_test.go, xds/internal/client/client_watchers.go, xds/internal/client/client_watchers_cluster_test.go, xds/internal/client/client_watchers_endpoints_test.go, xds/internal/client/client_watchers_lds_test.go, xds/internal/client/client_watchers_rds_test.go, xds/internal/client/client_watchers_service.go, xds/internal/client/client_watchers_service_test.go
- xds_client
- send resource-not-found error when a resource is removed for LDS or CDS
- handle LDS resource-not-found to cancel RDS watch
- test update because it was expecting no update when resource is removed
- test cleanup to apply timeout to channels
=> xds: handle errors in xds_client

balancer/grpclb/grpclb_test.go, stream.go, test/creds_test.go
The only time ClientTransport.NewStream returns an error is when the PerRPCCredentials error.  So, this makes it so that no NewStream error is retried transparently.
Fixes #3606
=> retry: prevent per-RPC creds error from being transparently retried

credentials/google/google.go, credentials/oauth/oauth.go, xds/internal/client/bootstrap/bootstrap.go, xds/internal/client/bootstrap/bootstrap_test.go
- use google default creds, so the client works not only on GCE (e.g. it also read env variable for creds).
- Change google default creds to use jwt directly if scope is not set.
- Leak check is disabled temporarily due to https://github.com/googleapis/google-cloud-go/issues/2417
=> xds: use google default creds

examples/examples_test.sh
(Hoping that this won't break any CI tests.)
@dfawley
=> examples: make test script output easier to read

server.go, vet.sh
=> doc: mark CustomCodec as deprecated

security/advancedtls/advancedtls.go, security/advancedtls/advancedtls_test.go
This PR does the following thing:
If users set `SkipVerification` to `False` yet did not provide with a valid `RootCertificateOptions`, a system default certificate `x509.SystemCertPool()` will be assigned in the `config()` function.
After this change:
If users choose to use default verification, clients are guaranteed to have a valid `RootCAs` certificate and servers are guaranteed to have a valid `ClientCAs` certificate.
@ZhenLian
=> advancedtls: Add system default CAs to config function

internal/grpclog/prefixLogger.go, xds/internal/balancer/cdsbalancer/cdsbalancer.go, xds/internal/balancer/cdsbalancer/logging.go, xds/internal/balancer/edsbalancer/eds.go, xds/internal/balancer/edsbalancer/eds_impl_priority.go, xds/internal/balancer/edsbalancer/logging.go, xds/internal/balancer/weightedtarget/logging.go, xds/internal/balancer/weightedtarget/weightedtarget.go, xds/internal/client/bootstrap/logging.go, xds/internal/client/client.go, xds/internal/client/client_loadreport.go, xds/internal/client/client_logging.go, xds/internal/resolver/logging.go, xds/internal/resolver/xds_resolver.go
All xds logs are in component `xds`.
This includes balancer `weighted_target` for now, which may need to change in the future.
Also fix logging depth.
=> xds: use logging components

clientconn.go, clientconn_test.go, service_config.go, service_config_test.go
=> service config: add default method config support

xds/internal/balancer/balancergroup/balancergroup.go, xds/internal/balancer/balancergroup/balancergroup_test.go, xds/internal/balancer/balancergroup/balancerstateaggregator.go, xds/internal/balancer/edsbalancer/eds_impl.go, xds/internal/balancer/edsbalancer/eds_impl_priority.go, xds/internal/balancer/edsbalancer/eds_impl_test.go, xds/internal/balancer/weightedtarget/weightedaggregator/aggregator.go, xds/internal/balancer/weightedtarget/weightedbalancerstateaggregator/balancerstateaggregator.go, xds/internal/balancer/weightedtarget/weightedtarget.go
Before, to use a balancer group, parent sends sub-balancer build/config, with sub-balancer weight to the balancer group. Balancer group builds the picker and sends to parent ClientConn. This has the limitation that the balancer group can only do weighted round robin between the sub-pickers.
With this change, balancer group is only responsible for managing sub-balancers/making subconns. It doesn't handle the balancer state update (with connectivity state and picker). The balancer group calls the balancer_state_aggregator whenever there's an picker update from any sub-balancer, and balancer_state_aggregator aggregates the states (including sub-pickers).
It's this way so the parent using balancer group can do more than weighted round robin with the sub-pickers (for example, routing balancer …
=> balancergroup: move balancer state (connectivity state and picker) building out

credentials/sts/sts.go, credentials/sts/sts_test.go
Implementation of call credentials based on https://tools.ietf.org/html/rfc8693.
=> credentials/sts: PerRPCCreds Implementation

clientconn.go
Fix healthcheck to health, which is the right package path to use.
=> cleanup: fix mention of healthcheck to health

Documentation/rpc-errors.md
These methods were moved into `internal/status` in https://github.com/grpc/grpc-go/pull/3432/files, so the doc links are outdated.
=> doc: fix references to status methods

examples/README.md
- Drop outdated text
- Retain what is unique to this page
- Refer reader to the quick start page for the rest
Contributes to https://github.com/grpc/grpc.io/issues/180
@dfawley /cc @ejona86 @jtattermusch
=> examples: cleanup README.md

README.md
- API reference link: use the same (canonical) link as the one used on grpc.io
- Put "Prerequisites" before "Installation" so that we don't have to repeat the prerequisite
- Set code-block styles where appropriate
- Copy edits
- Contributes to https://github.com/grpc/grpc.io/issues/180
@dfawley
=> README: adjust links, and slight rework of page

credentials/alts/internal/handshaker/service/service.go, credentials/alts/internal/handshaker/service/service_test.go
Previously, hsConn was a single value. If an application specifies 2 different handshaker service addresses, this would result in strange behavior where the first handshaker address that gets called into Dial would always be used. By using a map, we allow a handshaker connection per handshaker service address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3741)
=> credentials/alts: Change ALTS hsConn to a map

balancer/balancer.go, balancer/base/base.go, balancer/rls/internal/balancer.go, xds/internal/balancer/cdsbalancer/cdsbalancer_test.go
Closes #3180
This implements the final step of #3180, removing the backward-compatibility type aliases intended to provide a migration window for users of the removed, experimental API.
=> balancer: remove deprecated type aliases as planned

xds/internal/client/client_watchers_rds.go, xds/internal/client/client_watchers_service.go, xds/internal/client/client_watchers_service_test.go, xds/internal/client/envconfig.go, xds/internal/client/v2client_rds.go, xds/internal/client/v2client_rds_test.go
All new fields are guarded by env variable `GRPC_XDS_EXPERIMENTAL_ROUTING`.
The client copies the content from RDS response to xds resolver. It doesn't do
too much processing on the content (e.g. split routes into routes+actions, and
reuse action names).  The xds resolver will do these when generating service
config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3747)
=> xdsrouting: handle route fields in xds_client

xds/internal/balancer/xdsrouting/balancerstateaggregator.go, xds/internal/balancer/xdsrouting/logging.go, xds/internal/balancer/xdsrouting/routing.go, xds/internal/balancer/xdsrouting/routing_config.go, xds/internal/balancer/xdsrouting/routing_config_test.go, xds/internal/balancer/xdsrouting/routing_picker.go, xds/internal/balancer/xdsrouting/routing_picker_test.go, xds/internal/balancer/xdsrouting/routing_test.go
- state aggregator is very similar to weighted target 
-  but takes routes (matchers), instead of weights, and builds routing pickers.
- balancer handling new balancer consists of two parts
- update actions (sub-balancers)
- update routes (to aggregator, for pickers to use later)
- routing picker is very straightforward, it stops at the first match
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/grpc/grpc-go/3746)
=> xdsrouting: balancer implementation

cmd/protoc-gen-go-grpc/main.go
=> Support for proto3 field presence

examples/features/interceptor/client/main.go
If *grpc.PerRPCCredsCallOption is not found in the option array then change credentialConfigStatus to true and break from the loop. No need to iterate further.
=> examples: break from 'PerRPCCredsCallOption' status checking loop

security/advancedtls/advancedtls_integration_test.go, security/advancedtls/advancedtls_test.go
This PR migrates unit test and integration test of advancedtls library to grpctest.
@ZhenLian
=> advancedtls: migrate testing to grpctest

channelz/service/func_nonlinux.go, internal/channelz/types_nonlinux.go, internal/credentials/spiffe_appengine.go, internal/syscall/syscall_linux.go, internal/syscall/syscall_nonlinux.go, security/advancedtls/sni_appengine.go, xds/internal/client/v2/client.go
Support for Go1.9 and appengine was removed in https://github.com/grpc/grpc-go/pull/3767. But it looks like we still need some way to do things differently for certain appengine builds.
=> Add some appengine build constraints.

xds/internal/client/client.go, xds/internal/client/client_test.go, xds/internal/client/client_watchers.go, xds/internal/client/client_watchers_cluster_test.go, xds/internal/client/client_watchers_endpoints_test.go, xds/internal/client/client_watchers_lds_test.go, xds/internal/client/client_watchers_rds_test.go, xds/internal/client/client_watchers_service_test.go
Tests can pass a different value when necessary. This avoids overriding
a global variable from tests, leading to unnecessary races.
=> xds: Pass WatchExpiryTimeout to Client via Options.

xds/internal/balancer/edsbalancer/xds_client_wrapper_test.go, xds/internal/testutils/fakeserver/server.go
* One subtest should not depend on a previous one. So, refactored the
test to be a single one, instead of having multiple subtests.
* Added a channel on the fake server to notify when it receives a
connection. This test was sometimes failing because it went ahead and
sent EDS requests and expected responses, before the connection to the
fake server was up.
=> xds: Improve TestClientWrapperWatchEDS.

examples/features/debugging/client/main.go, examples/features/load_balancing/README.md, examples/features/load_balancing/client/main.go, examples/go.mod, examples/go.sum
And remove example usages of `WithBalancerName`
fixes #3811
=> examples: update grpc version

rpc_util.go
This was missed out in https://github.com/grpc/grpc-go/pull/3816.
=> grpc: Bump up support package version.
